### ISSUE TITLE
1.7.9 (and 1.8) Bandwidth graph blank when not selecting 1st month

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1013]
Bandwidth is stored by month, yet the date selector allows section of individual days, which leads to a blank chart when selecting a day past the 1st day of the current month.

We should limit that date selector to be months only.

OP: https://community.xibo.org.uk/t/bandwidth-date-selector-1-7-9/8442

**Comment by dasgarner** [comment]
The datetimepicker does have a setting for the minimum view allowed, which we could set to be a "Month" selector.

If we did that, we would need to check that it automatically selected the 1st of the month that was picked - as I suspect it will select the current day, and the month selected.

We could also use the resulting date object in PHP to always reset to the first of the month. Although if we are going to do this, I might be tempted to argue that we change the parameters to only accept `m-Y` and to create the appropriate date object from that.

**Comment by maurofmferrao** [comment]
Fixed in 1.8, need to be fixed for 1.70.10.
