### ISSUE TITLE
Preview does not handle empty regions 1.7/1.8

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1014]
If the layout contains empty regions, preview just shows the layout background.

An empty region shouldn't break it, but perhaps it should be used as an opportunity to hilight that the region is empty to the user - ie by making it red/transparent overlay?

**Comment by dasgarner** [comment]
Need to back port into 1.7.10 - re-targetting

**Comment by maurofmferrao** [comment]
Fixed in 1.8, need to be fixed for 1.70.10.
