### ISSUE TITLE
1.7 and android client time issue

### ISSUE THREAD

**Issue by knitehawk** [xibosignage/xibo#102]
the android 1.7 client, (while i might say i am kissing the ground with joy for!) is reporting the wring date to the cms. 
2015-01-30 00:42 is reported. i have checked the time and date in the android box and it's not that.
still checking to see if this affects scheduling.

**Comment by knitehawk** [comment]
date shown when clock date is applied in a text region is
th-54-yy
format is 
mm-dd-yy
so its Thursday the 57th of infinity?

**Comment by knitehawk** [comment]
sorry format is dd-mm-yy

**Comment by alexharrington** [comment]
Try changing the format to

[Clock|MM-DD-YYYY]

**Comment by alexharrington** [comment]
When adding a text item the substitution offered is:
![image](https://cloud.githubusercontent.com/assets/10450518/5974617/2d501962-a86e-11e4-871c-3b7ae8fe3343.png)

however when you subsequently edit the correct all capitals substitution is then suggested:
![image](https://cloud.githubusercontent.com/assets/10450518/5974632/5640405e-a86e-11e4-82d2-80b08b1b3aec.png)
