### ISSUE TITLE
v1.6.4 > 1.7.0 db upgrade error

### ISSUE THREAD

**Issue by scienceworld** [xibosignage/xibo#103]
![image](https://cloud.githubusercontent.com/assets/3997916/5971527/8eeb334a-a7fc-11e4-8d6d-e0c10e297ce9.png)

standard xibo v1.6.4 upgrade to v1.7.0.  error while performing the upgrade.

```
An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 80. Error Message = [SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'backgroundImageId' at row 12]
```

**Comment by alexharrington** [comment]
Looks like you have a layout with a missing background image - so perhaps you created the layout, and then deleted the background image?

**Comment by dasgarner** [comment]
This is these set of statements in `80.sql`

``` sql
UPDATE layout SET background = SUBSTRING_INDEX(background, '.', 1) WHERE IFNULL(background, '') <> '';

ALTER TABLE  `layout` CHANGE  `background`  `backgroundImageId` INT( 11 ) NULL DEFAULT NULL;

INSERT INTO `lklayoutmedia` (mediaid, layoutid, regionid)
SELECT backgroundimageid, layoutid, 'background' FROM `layout` INNER JOIN `media` ON media.mediaid = layout.backgroundImageId WHERE IFNULL(backgroundImageId, 0) <> 0;
```

I am not sure why that would fail as it should protect against empty backgrounds and for background s that have been deleted.

**Comment by bigxpicanha** [comment]
even updating an empty database, it will happen.
the same thing happened with me.
have a database running since version 1.2, and also unable to update to version 1.7.1

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
