### ISSUE TITLE
Player Resolution changes can cause Xibo to stop working correctly

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#1033]
A variety of symptoms present themselves, seemingly at random. Ranging from temporarily broken, down to completely broken.

All occurrences share a common visual clue, which is the Xibo content being shown gets cut off to a small window.

**Comment by alexharrington** [comment]
https://community.xibo.org.uk/t/screen-shrinks-to-the-top-left-of-the-screen/8638/9?u=alex has a potential fix

**Comment by dasgarner** [comment]
The documented workaround is the fix in this case.

**Comment by dasgarner** [comment]
Reopened due to the documented workaround ceasing to be viable (the registry settings take no effect any longer).

The suggestion is that we can handle resolution changes and resize the Player window accordingly (without adversely effecting the Player status)

https://msdn.microsoft.com/en-us/library/microsoft.win32.systemevents.displaysettingschanged.aspx

**Comment by wreality** [comment]
Running version 1.8.8 of the client (which I believe includes this fix, no?) and we're having issues with the player not handling resize events correctly (player  shrinks to upper corner if monitor is turned off).  Can also confirm the registry tweaks suggested in the FAQ category don't seem to work. :-)

Any help I can provide troubleshooting, happy to do so.

**Comment by dasgarner** [comment]
Thanks for the offer of help - please could you raise your issue on our community forum so that the support team can look over it, verify and create another bug for it if there are still cases where it is not resolved.

Thanks!
