### ISSUE TITLE
Custom module not working correctly

### ISSUE THREAD

**Issue by Techassi** [xibosignage/xibo#1034]
Hello guys,
I wrote a custom mudule based of the forecast module and the module template. In my module I make a API request. Here are some points which don't work for me:

- editing module settings and saving them
- Xibo Windows Player not showing the content in the right way (missing pictures and php code isn't working correctly)

[The module source code can be found here](https://community.xibo.org.uk/t/custom-module-not-saving-and-receiving-data/8704)
And here is my HTML template: 
```
<!doctype html>
<html lang="en">
    <head>
        <title>Xibo Open Source Digital Signage</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=[[ViewPortWidth]]" />
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <!-- Copyright 2006-2014 Daniel Garner. Part of the Xibo Open Source Digital Signage Solution. Released under the AGPLv3 or later. -->
        <!--[[[STYLESHEETCONTENT]]]-->
        <!--[[[HEADCONTENT]]]-->
    </head>
    <!--[if lt IE 7 ]><body class="ie6"><![endif]-->
    <!--[if IE 7 ]><body class="ie7"><![endif]-->
    <!--[if IE 8 ]><body class="ie8"><![endif]-->
    <!--[if IE 9 ]><body class="ie9"><![endif]-->
    <!--[if (gt IE 9)|!(IE)]><!--><body><!--<![endif]-->
        <div id="content">
            <div class="blur">
                <!--[[[HEADLINE]]]-->
                <ul>
                    <!--[[[BODYCONTENT]]]-->
                </ul>
            </div>
        </div>
    </body>
    <!--[[[JAVASCRIPTCONTENT]]]-->
</html>
```

The module code isn't the newest and I can link the new one in the comments if needed.
I made some minor changes e.g. adding a QRCode library to dynamically create QRCodes.

```
$qrUrl = urlencode($result['items'][$i]['_links'][0]['href']);

$output = $output . '<li class="' . selectClass($return['size']) . '"><div class="wrapper"><div class="icon"></div><div class="qr"><img src="modules/3rdparty/qrcode.php?link=' . $qrUrl . '"/></div><p>Distance: ' . $distance . ' m</p></div></li>';
```

And here is the qrcode.php code:

```
<?php 
	include 'phpqrcode.php';
	$url = $_GET['link'];

	QRcode::png($url);
 ?>
```
This file outputs a QRCode in png-format.

**Comment by alexharrington** [comment]
Your thread on the Community site is the correct place to discuss this. The Github Issues are for confirmed bugs in Xibo only. Thank you.

**Comment by Techassi** [comment]
But apparently no one can help me over there.

**Comment by alexharrington** [comment]
You posted your question less than 24 hours ago. You need to allow a reasonable amount of time for one of the developers to see the post, and then respond. Please keep in mind that they're offering support to you there as a free service, so it won't be something that they do as a priority. Commercial support is available if you have pressing requirements for a timely response.
