### ISSUE TITLE
High CPU usage on MySQL server when creating/editing layout

### ISSUE THREAD

**Issue by tvanham** [xibosignage/xibo#1035]
When we create or modify an existing layout within the Xibo web interface, we notice that on the (colocated) MySQL server (5.7.17) the CPU usage spikes. This is due to a single query from Xibo which is stuck on 'Sending data'.

The following query is executed:

`SELECT  media.mediaID,    media.name,    media.type,    media.duration,    media.userID,    media.FileSize,    media.storedAs,    media.valid,    media.moduleSystemFile,    media.expires,    IFNULL((SELECT parentmedia.mediaid FROM media parentmedia WHERE parentmedia.editedmediaid = media.mediaid),0) AS ParentID,  (SELECT GROUP_CONCAT(DISTINCT tag) FROM tag INNER JOIN lktagmedia ON lktagmedia.tagId = tag.tagId WHERE lktagmedia.mediaId = media.mediaID GROUP BY lktagmedia.mediaId) AS tags, (SELECT GROUP_CONCAT(DISTINCT `group`.Group)   FROM `group`    INNER JOIN lkmediagroup    ON `group`.GroupID = lkmediagroup.GroupID  WHERE lkmediagroup.MediaID = media.mediaID GROUP BY lkmediagroup.mediaId ) AS groups,    media.originalFileName  FROM media    LEFT OUTER JOIN media parentmedia    ON parentmedia.MediaID = media.MediaID  WHERE media.isEdited = 0  AND media.expires < '1486556447' AND IFNULL(media.expires, 0) <> 0`

This happens (in our case) when you select 'design' for an existing template or create a new one. No further actions are required. When the page is simply showing the blank/gray layout this query is launced every minute and keeps coming back until the server is clogged and stops responding.

Our MySQL server is upgraded from 5.1 to 5.7.17 which makes no difference. This problem was also showing in Xibo 1.7.4. Our current Xibo version is 1.7.9 but the problem persists.

**Comment by alexharrington** [comment]
Thanks for your detailed report. The project uses Github Issues only for verified bug reports which have been previously discussed over on our community support site. Please post your issue there, and we can convert it to a bug if a general issue is found. https://community.xibo.org.uk
