### ISSUE TITLE
My Schedule doesnt seem to be working.

### ISSUE THREAD

**Issue by karldonteljames** [xibosignage/xibo#1036]
Good Morning,
I'm currently trying to setup Xibo in my school, the screens are playing the default layout fine, and also playing the scheduled layout fine if i set it as the default for that screen. The screens are all in the same time zone, and the times between them are within 30 seconds. I've tried to schedule this layout per screen and per group and i'm getting the same "nothing changes" results. so far as i can see from the log file everything is ok. I've setup the schedule to run for 5 minutes every hour. The longest "Region" is 120 Seconds, and my update interval is 60 seconds.

Is anyone able to help please? I'm just stumped now.

Thanks.

Karl

UI Thread|09/02/2017 11:41:11|Info|MainForm|Client Initialised
RegisterAgentThread|09/02/2017 11:41:11|Info|RegisterAgent - Run|Thread Started
RequiredFilesAgentThread|09/02/2017 11:41:11|Info|RequiredFilesAgent - Run|Thread Started
ScheduleManagerThread|09/02/2017 11:41:11|Info|ScheduleManager - Run|Thread Started
LibraryAgent|09/02/2017 11:41:11|Info|LibraryAgent - Run|Thread Started
LogAgent|09/02/2017 11:41:11|Info|LogAgent - Run|Thread Started
RegisterAgentThread|09/02/2017 11:41:11|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:41:11|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 11:42:11|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:42:12|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 11:43:11|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:43:12|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 11:44:12|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:44:12|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 11:45:12|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:45:13|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 11:46:12|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:46:13|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 11:47:12|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:47:14|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 11:48:13|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:48:15|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 9.xlf
RequiredFilesAgentThread|09/02/2017 11:48:15|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_9|09/02/2017 11:48:15|Info|FileAgent - Run|File Downloaded Successfully. 9.xlf
FileAgent_layout_Id_9|09/02/2017 11:48:15|Info|Schedule - LayoutFileModified|Layout file changed: 9.xlf
UI Thread|09/02/2017 11:48:15|Info|PrepareLayout|A layout with 1 regions and 0 media has been detected.
UI Thread|09/02/2017 11:48:15|Info|PrepareLayout|Only 1 layout scheduled and it has nothing to show.
UI Thread|09/02/2017 11:48:15|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Only 1 layout schduled and it has nothing to show
UI Thread|09/02/2017 11:48:15|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Only 1 layout schduled and it has nothing to show
UI Thread|09/02/2017 11:48:25|Info|PrepareLayout|A layout with 1 regions and 0 media has been detected.
UI Thread|09/02/2017 11:48:25|Info|PrepareLayout|Only 1 layout scheduled and it has nothing to show.
UI Thread|09/02/2017 11:48:25|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Only 1 layout schduled and it has nothing to show
UI Thread|09/02/2017 11:48:25|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Only 1 layout schduled and it has nothing to show
UI Thread|09/02/2017 11:48:35|Info|PrepareLayout|A layout with 1 regions and 0 media has been detected.
UI Thread|09/02/2017 11:48:35|Info|PrepareLayout|Only 1 layout scheduled and it has nothing to show.
UI Thread|09/02/2017 11:48:35|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Only 1 layout schduled and it has nothing to show
UI Thread|09/02/2017 11:48:35|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Only 1 layout schduled and it has nothing to show
UI Thread|09/02/2017 11:48:45|Info|PrepareLayout|A layout with 1 regions and 0 media has been detected.
UI Thread|09/02/2017 11:48:45|Info|PrepareLayout|Only 1 layout scheduled and it has nothing to show.
UI Thread|09/02/2017 11:48:45|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Only 1 layout schduled and it has nothing to show
UI Thread|09/02/2017 11:48:45|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Only 1 layout schduled and it has nothing to show
UI Thread|09/02/2017 11:48:55|Info|PrepareLayout|A layout with 1 regions and 0 media has been detected.
UI Thread|09/02/2017 11:48:55|Info|PrepareLayout|Only 1 layout scheduled and it has nothing to show.
UI Thread|09/02/2017 11:48:55|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Only 1 layout schduled and it has nothing to show
UI Thread|09/02/2017 11:48:55|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Only 1 layout schduled and it has nothing to show
UI Thread|09/02/2017 11:49:05|Info|PrepareLayout|A layout with 1 regions and 0 media has been detected.
UI Thread|09/02/2017 11:49:05|Info|PrepareLayout|Only 1 layout scheduled and it has nothing to show.
UI Thread|09/02/2017 11:49:05|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Only 1 layout schduled and it has nothing to show
UI Thread|09/02/2017 11:49:05|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Only 1 layout schduled and it has nothing to show
RegisterAgentThread|09/02/2017 11:49:13|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
UI Thread|09/02/2017 11:49:15|Info|PrepareLayout|A layout with 1 regions and 0 media has been detected.
UI Thread|09/02/2017 11:49:15|Info|PrepareLayout|Only 1 layout scheduled and it has nothing to show.
UI Thread|09/02/2017 11:49:15|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Only 1 layout schduled and it has nothing to show
UI Thread|09/02/2017 11:49:15|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Only 1 layout schduled and it has nothing to show
RequiredFilesAgentThread|09/02/2017 11:49:15|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 9.xlf
RequiredFilesAgentThread|09/02/2017 11:49:15|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_9|09/02/2017 11:49:16|Info|FileAgent - Run|File Downloaded Successfully. 9.xlf
FileAgent_layout_Id_9|09/02/2017 11:49:16|Info|Schedule - LayoutFileModified|Layout file changed: 9.xlf
RegisterAgentThread|09/02/2017 11:50:13|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:50:16|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 9.xlf
RequiredFilesAgentThread|09/02/2017 11:50:16|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_9|09/02/2017 11:50:16|Info|FileAgent - Run|File Downloaded Successfully. 9.xlf
FileAgent_layout_Id_9|09/02/2017 11:50:16|Info|Schedule - LayoutFileModified|Layout file changed: 9.xlf
RegisterAgentThread|09/02/2017 11:51:13|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:51:17|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 9.xlf
RequiredFilesAgentThread|09/02/2017 11:51:17|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_9|09/02/2017 11:51:17|Info|FileAgent - Run|File Downloaded Successfully. 9.xlf
FileAgent_layout_Id_9|09/02/2017 11:51:17|Info|Schedule - LayoutFileModified|Layout file changed: 9.xlf
RegisterAgentThread|09/02/2017 11:52:14|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:52:17|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 9.xlf
RequiredFilesAgentThread|09/02/2017 11:52:17|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_9|09/02/2017 11:52:17|Info|FileAgent - Run|File Downloaded Successfully. 9.xlf
FileAgent_layout_Id_9|09/02/2017 11:52:17|Info|Schedule - LayoutFileModified|Layout file changed: 9.xlf
UI Thread|09/02/2017 11:52:18|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:52:18|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:52:29|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:52:29|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:52:39|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:52:39|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:52:50|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:52:50|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:53:00|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:53:00|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:53:11|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:53:11|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
RegisterAgentThread|09/02/2017 11:53:14|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:53:18|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 9.xlf
RequiredFilesAgentThread|09/02/2017 11:53:18|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_9|09/02/2017 11:53:18|Info|FileAgent - Run|File Downloaded Successfully. 9.xlf
FileAgent_layout_Id_9|09/02/2017 11:53:18|Info|Schedule - LayoutFileModified|Layout file changed: 9.xlf
FileAgent_media_Id_87|09/02/2017 11:53:18|Info|FileAgent - Run|File Downloaded Successfully. 87.jpg
RegisterAgentThread|09/02/2017 11:54:14|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:54:19|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 9.xlf
RequiredFilesAgentThread|09/02/2017 11:54:19|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_9|09/02/2017 11:54:19|Info|FileAgent - Run|File Downloaded Successfully. 9.xlf
FileAgent_layout_Id_9|09/02/2017 11:54:19|Info|Schedule - LayoutFileModified|Layout file changed: 9.xlf
UI Thread|09/02/2017 11:54:20|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:54:20|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:54:30|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:54:30|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:54:40|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:54:40|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:54:51|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:54:51|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:55:01|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:55:01|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:55:12|Error|MainForm - ChangeToNextLayout|Prepare Layout Failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
UI Thread|09/02/2017 11:55:12|Error|MainForm - ChangeToNextLayout|Layout Change to C:\XiboLIbrary\9.xlf failed. Exception raised was: Specified argument was out of the range of valid values.
Parameter name: Unable to set and start a media node
RegisterAgentThread|09/02/2017 11:55:14|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:55:20|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 9.xlf
RequiredFilesAgentThread|09/02/2017 11:55:20|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_media_Id_88|09/02/2017 11:55:20|Info|FileAgent - Run|File Downloaded Successfully. 88.jpg
FileAgent_media_Id_89|09/02/2017 11:55:20|Info|FileAgent - Run|File Downloaded Successfully. 89.jpg
FileAgent_layout_Id_9|09/02/2017 11:55:20|Info|FileAgent - Run|File Downloaded Successfully. 9.xlf
FileAgent_layout_Id_9|09/02/2017 11:55:20|Info|Schedule - LayoutFileModified|Layout file changed: 9.xlf
RegisterAgentThread|09/02/2017 11:56:15|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:56:20|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 9.xlf
RequiredFilesAgentThread|09/02/2017 11:56:20|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_9|09/02/2017 11:56:20|Info|FileAgent - Run|File Downloaded Successfully. 9.xlf
FileAgent_layout_Id_9|09/02/2017 11:56:21|Info|Schedule - LayoutFileModified|Layout file changed: 9.xlf
RegisterAgentThread|09/02/2017 11:57:15|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:57:21|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 9.xlf
RequiredFilesAgentThread|09/02/2017 11:57:21|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_9|09/02/2017 11:57:21|Info|FileAgent - Run|File Downloaded Successfully. 9.xlf
FileAgent_layout_Id_9|09/02/2017 11:57:21|Info|Schedule - LayoutFileModified|Layout file changed: 9.xlf
RegisterAgentThread|09/02/2017 11:58:15|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:58:22|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 9.xlf
RequiredFilesAgentThread|09/02/2017 11:58:22|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_9|09/02/2017 11:58:22|Info|FileAgent - Run|File Downloaded Successfully. 9.xlf
FileAgent_layout_Id_9|09/02/2017 11:58:22|Info|Schedule - LayoutFileModified|Layout file changed: 9.xlf
RegisterAgentThread|09/02/2017 11:59:15|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 11:59:22|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 9.xlf
RequiredFilesAgentThread|09/02/2017 11:59:22|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_9|09/02/2017 11:59:22|Info|FileAgent - Run|File Downloaded Successfully. 9.xlf
FileAgent_layout_Id_9|09/02/2017 11:59:22|Info|Schedule - LayoutFileModified|Layout file changed: 9.xlf
RegisterAgentThread|09/02/2017 12:00:15|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:00:22|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:01:16|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:01:23|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 9.xlf
RequiredFilesAgentThread|09/02/2017 12:01:23|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_9|09/02/2017 12:01:23|Info|FileAgent - Run|File Downloaded Successfully. 9.xlf
FileAgent_layout_Id_9|09/02/2017 12:01:23|Info|Schedule - LayoutFileModified|Layout file changed: 9.xlf
RegisterAgentThread|09/02/2017 12:02:16|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:02:26|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 9.xlf
RequiredFilesAgentThread|09/02/2017 12:02:26|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_9|09/02/2017 12:02:27|Info|FileAgent - Run|File Downloaded Successfully. 9.xlf
FileAgent_layout_Id_9|09/02/2017 12:02:27|Info|Schedule - LayoutFileModified|Layout file changed: 9.xlf
RegisterAgentThread|09/02/2017 12:03:16|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:03:27|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 9.xlf
RequiredFilesAgentThread|09/02/2017 12:03:27|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_9|09/02/2017 12:03:27|Info|FileAgent - Run|File Downloaded Successfully. 9.xlf
FileAgent_layout_Id_9|09/02/2017 12:03:27|Info|Schedule - LayoutFileModified|Layout file changed: 9.xlf
RegisterAgentThread|09/02/2017 12:04:16|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:04:27|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:05:16|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:05:28|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:06:17|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:06:28|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:07:18|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:07:29|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:08:18|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:08:29|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:09:18|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:09:30|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:10:18|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:10:30|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:11:19|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:11:31|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:12:19|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:12:31|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:13:19|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:13:32|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:14:20|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:14:32|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:15:20|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:15:32|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:16:20|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:16:33|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:17:20|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:17:33|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:18:21|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:18:33|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:19:21|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:19:34|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 12.xlf
RequiredFilesAgentThread|09/02/2017 12:19:34|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_12|09/02/2017 12:19:34|Info|FileAgent - Run|File Downloaded Successfully. 12.xlf
FileAgent_layout_Id_12|09/02/2017 12:19:34|Info|Schedule - LayoutFileModified|Layout file changed: 12.xlf
RegisterAgentThread|09/02/2017 12:20:22|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:20:35|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:21:22|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:21:35|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:22:22|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:22:36|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:23:22|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:23:36|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:24:22|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:24:36|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:25:23|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:25:37|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:26:23|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:26:38|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 12.xlf
RequiredFilesAgentThread|09/02/2017 12:26:38|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_12|09/02/2017 12:26:38|Info|FileAgent - Run|File Downloaded Successfully. 12.xlf
FileAgent_layout_Id_12|09/02/2017 12:26:38|Info|Schedule - LayoutFileModified|Layout file changed: 12.xlf
RegisterAgentThread|09/02/2017 12:27:23|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:27:38|Info|RequiredFiles - SetRequiredFiles|MD5 different for existing file: 12.xlf
RequiredFilesAgentThread|09/02/2017 12:27:38|Info|RequiredFiles - ReportInventory|Reporting Inventory
FileAgent_layout_Id_12|09/02/2017 12:27:39|Info|FileAgent - Run|File Downloaded Successfully. 12.xlf
FileAgent_layout_Id_12|09/02/2017 12:27:39|Info|Schedule - LayoutFileModified|Layout file changed: 12.xlf
RegisterAgentThread|09/02/2017 12:28:23|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:28:39|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:29:24|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:29:40|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:30:24|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:30:41|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:31:24|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:31:41|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:32:24|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:32:41|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:33:24|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:33:42|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:34:25|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:34:43|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:35:25|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:35:43|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:36:25|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:36:43|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:37:25|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:37:44|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:38:26|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:38:44|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:39:26|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:39:45|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:40:28|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:40:45|Info|RequiredFiles - ReportInventory|Reporting Inventory
RegisterAgentThread|09/02/2017 12:41:28|Info|RegisterAgent - Run|Thread Woken and Lock Obtained
RequiredFilesAgentThread|09/02/2017 12:41:45|Info|RequiredFiles - ReportInventory|Reporting Inventory

**Comment by alexharrington** [comment]
You really need to post support requests over on the Community Site at https://community.xibo.org.uk

The project uses Github issues for verified bug reports only.

A quick look at your log has `Only 1 layout schduled and it has nothing to show` standing out. I'd suggest that your layout is invalid in some way, perhaps because you have an empty region on it.

Start with a simple layout, with a single image on it. Note that a blank layout comes with a full screen region drawn for you so no need to add a second over the top.

If it isn't that, please post on the community site.

**Comment by karldonteljames** [comment]
Thanks Alex. The layout was change after this error. I've posted over at the Xibo Community.
