### ISSUE TITLE
XMDS Schedule Call - Dependents list too long

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1038]
When too many items are in a single layout, the schedule XML for layout dependents in the schedule call breaks.

We're unable to fix this without breaking back compatibility, but could we instead send down as many dependents as will fit in the available space, rather than sending down a broken list that prevents the Player from running the layout?

**Comment by dasgarner** [comment]
We can pick some predetermined number of dependencies - say 10. "as many as will fit" is difficult, because it depends on the ID's they have as to their string length.

**Comment by alexharrington** [comment]
We know the maximum string length, so surely it's just:

if len(dependents) <= max_string_length:
   node.property = dependents
else:
  tmp_dependents = ''
  foreach explode(dependents, ',') as dependent:
      if len(tmp_dependents + dependent) < max_string_lenth:
           tmp_dependents = tmp_dependents + ',' + dependent

  node.property = tmp_dependents
