### ISSUE TITLE
v1.70 bad link to release notes

### ISSUE THREAD

**Issue by scienceworld** [xibosignage/xibo#104]
Downloaded the latest cms v1.7 from xibo's home page
started to perform upgrade
clicked on Release notes button on upgrade page and got a 404 on the link.

http://xibo.something.xxx/manual/index.php?toc=developer_releasenotes&p=admin/release_notes

the cms v1.70 zip does not have a /manual folder.

**Comment by alexharrington** [comment]
https://github.com/xibosignage/xibo-cms/blob/develop/theme/default/config.php#L30
