### ISSUE TITLE
How to fix MySQL database PHP and Caleandar Extesion?

### ISSUE THREAD

**Issue by DJDaan1997** [xibosignage/xibo#1043]
MySQL database (PHP MySql)		MySQL support must be enabled in PHP.
Calendar Extension		PHP Calendar extension to function.

![xibo instal faill](https://cloud.githubusercontent.com/assets/7623456/23094881/0b952e38-f601-11e6-9f1e-5e69b7202a34.PNG)

**Comment by alexharrington** [comment]
Thank you for your post. The project uses Github issues for verified bugs only. Please post future support requests on our Community site here: https://community.xibo.org.uk

To answer your question, PHP 7 isn't supported by any current version of Xibo. You need to use PHP 5.6 for Xibo to work.
