### ISSUE TITLE
Retest all bugs from the first release candidate forwards

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#1047]
They can be marked with the "test passed" label when complete.

Do not start this item until all others are closed.

**Comment by dasgarner** [comment]
RC1 done and passed

**Comment by maurofmferrao** [comment]
RC2 done, all passed except two bugs that keep happening:
https://github.com/xibosignage/xibo/issues/933
https://github.com/xibosignage/xibo/issues/941

**Comment by dasgarner** [comment]
#933 is fixed.

**Comment by maurofmferrao** [comment]
Possible solution for the #941 problem commited.
