### ISSUE TITLE
1.7.0 date time picker behaves strangely

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#105]
![screenshot from 2015-01-30 09 59 39](https://cloud.githubusercontent.com/assets/10450518/5973980/c3244588-a866-11e4-9a39-6ac45cce593c.png)

When clicking the right arrow here, I'd expect to move to February but I get taken to the time picker for the currently selected day instead.

**Comment by dasgarner** [comment]
Library is: https://github.com/smalot/bootstrap-datetimepicker
