### ISSUE TITLE
DB upgrade failed from 1.6.3 to 1.7.0

### ISSUE THREAD

**Issue by DanTheMan-NL** [xibosignage/xibo#106]
I am upgrading my Xibo from 1.6.3 to 1.7.0 and the installation wizard gives me this error:
"An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 82. Error Message = [SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY']"

Under that line there is this line: Upgrading from database version 81 to 84
When I started this upgrade my database version was much older so someting has happened.

What to do?

**Comment by dasgarner** [comment]
Perhaps take a peek at #87 to see if the information there helps out.

Thanks,
Dan

**Comment by DanTheMan-NL** [comment]
Finaly! I updated both the 80.sql and 82.sql and restored the database twice but now it works! Maybe you should considering changing the source code?

Anyways loving the new style!! Now I'm gonna play with this.

**Comment by dasgarner** [comment]
we will be collecting up all these early changes and putting out a 1.7.1 in a short time frame. when you think about it, we have had 4 pre-releases and no-one found these! Shame
