### ISSUE TITLE
"Out of memory"

### ISSUE THREAD

**Issue by AllieKat** [xibosignage/xibo#107]
I'm continuing to get "Windows is running low on memory" errors after about 9 hours with the layout I posted in the other issue. There is literally nothing else running on this computer (Office 2013 is installed but not being used), after I removed LogMeIn for testing. I am also, finally, up to date on Windows updates (I found I wasn't since it was attached to a domain and looking for a WSUS server on the domain, rather than contacting Microsoft). None of that made a difference.

This is an Intel NUC i5 D54250WYKH with 4GB of RAM (though I had the same issue when I tried 16GB of RAM in it). Windows 8.1. Everything updated.

I ran 1.7 RC1 stable for several days before I put this up on a TV... no issue. I NEED to get this stable, and while I love Xibo cause it's open source and I like the design, I will use anything on this that'll be stable - I don't know of another open source option. 

Does anyone have any ideas to make this system stable? I'm thinking of trying Windows 7 on the machine.

**Comment by dasgarner** [comment]
I've had your layout running for 4 hours without any issues, but I do have windows 7 rather than 8 - so I suppose that is worth a try?

I have also made the registry patches to use IE9 rather than IE7 as the rendering engine - not sure if you have done that?

You do have 7 regions on your layout that require HTML rendering, which means 7 IE instances running in your layout, which is a lot - but as I said, it doesn't seem to fail on here.

I'll try and run my test for longer today and see where we end up.

**Comment by AllieKat** [comment]
I made that registry patch, then undid it when it didn't fix the date issue. Should I re-make that patch?

**Comment by dasgarner** [comment]
It would be good to rule it out, so yes please.

I'm 3 hours in and my memory usage for the main `XiboClient.exe` process is 80MB (actually lower than when it first started up).

**Comment by AllieKat** [comment]
I switched it to use IE 11 (I figured it'd have the most difference), no change - same error in about the same amount of time. 

Right now I just turned off the other thing I remember changing between my testing (which was fine) and deploying it - I set the screen shot interval to 0, I had put it on 15. We shall see what that does.

**Comment by dasgarner** [comment]
I will test with mine on 5 (it was previously 0)

**Comment by AllieKat** [comment]
Still getting it on zero. Time to install Windows 7, I think...

**Comment by dasgarner** [comment]
I ran for 4 hours without any memory bloating, so it may actually be a window 8 issue - we haven't tested on Windows 8, basically because we don't have it.

If Win7 solves it for you without **any** other changes, then that would be very interesting.

**Comment by luktho** [comment]
Hey guys.

Can confirm that on Win7 there could be same problems as AllieKat described in the first post. We at Musikhaus Thomann are using Win 7 Enterp
![xibo-error-outofmem](https://cloud.githubusercontent.com/assets/10848763/6041021/878fc6b2-ac78-11e4-9843-0bd5b88893ba.jpg)
rise 64Bit which is deployed via baramundi. Somehow it only occures on some systems.

We're using Shuttle DS81 barebones (poor build quality by the way - they are dying at random and we bought 20 devices from that 12 are already dead) and Dell Optiplex 9020micro (can't tell yet if the hardware is better or not). All clients are in the same vlan with static ip adresses. Xibo server and Xibo client are both ver. 1.7.0.

**Comment by AllieKat** [comment]
Thanks for the update, I'm going to put another drive in our system this weekend (to not touch the Win 8.1 install in case it fixes nothing to try Win 7) and put Windows 7 on it, assuming I have time.

**Comment by dasgarner** [comment]
@luktho did you ever experience the same issue with the 1.6 player? Or do you think this is something specifically effecting 1.7?

Looking at the stack trace there, the client is trying to flush the statistics log to the CMS - now I don't know whether that is just the particular point it ran out of memory, or whether that code is to blame... but I am wondering if it could be this: #127

**Comment by luktho** [comment]
Actually the problem occured on previous versions. We started installing xibo with 1.6 RC1. Will check the post and try to make some adjustments on the server side. Just switched to chrome engine, so tomorrow I can gather more information.

**Comment by dasgarner** [comment]
Tracked in #127 from now on.
