### ISSUE TITLE
Layout Designer: Impossible to create region with German locale

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1083]
1.8.0 custom install (tested in Docker too)

When switching language to German (de), clicking the Add Region button in the layout designer results in:
![image](https://cloud.githubusercontent.com/assets/10450518/24213611/03330f2e-0f2b-11e7-8d10-bed9323aa81e.png)

I also tried Spanish (es), with the same result.

Switching back to English (en_GB) and it works again.

OP: https://community.xibo.org.uk/t/xibo-cms-1-8-add-region/9210

**Comment by dasgarner** [comment]
![image](https://cloud.githubusercontent.com/assets/10400067/24215702/73ba431a-0f31-11e7-9148-431564a51c28.png)
