### ISSUE TITLE
Layout Designer: Adding image doesn't work with German locale

### ISSUE THREAD

**Issue by zemmediamatiker** [xibosignage/xibo#1091]
Xibo 1.8.0 custom install (Can't try with Docker in our environment)

When editing the schedule in a region and trying to add an image, nothing happens.
After I've seen this [issue #1083](https://github.com/xibosignage/xibo/issues/1083), I found out, that this has also something to do with the `de` locale. When I have switched back to `en_GB` everything seemed to run as expected.

![image](https://cloud.githubusercontent.com/assets/11920861/24285219/62409c1c-106f-11e7-82f3-c4d1d253b078.png)

**Comment by dasgarner** [comment]
Same root cause as #1083

**Comment by dasgarner** [comment]
Fixed in linked issue.
