### ISSUE TITLE
Xibo 1.8.0 - Log Level changes are not taken over

### ISSUE THREAD

**Issue by Mondlicht81** [xibosignage/xibo#1095]
Hi,

I tried to set the log level to another value than "Error". Unfortunately, although I get the message "Settings Updated", when I reload the settings page, it still stands on "Error".

Is this an already known issue?

**Comment by alexharrington** [comment]
Which of the Log Level settings are you changing?

How are you running 1.8.0? In Docker?

**Comment by Mondlicht81** [comment]
Yes, inside Docker.
I changed Setting --> Troubleshooting --> Log Level.

**Comment by Mondlicht81** [comment]
When updating the parameter inside the database manually, it's automatically set back to Error after some seconds...

`mysql> update setting set value='Info' WHERE settingid=30;
Query OK, 1 row affected (0.11 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from setting WHERE settingid=30;
+-----------+---------+-------+-----------+-----------------------------------------------------------------------------------------------+----------------------------------------------------------+-----------------+------------+-----------+------------+----------+---------+---------+------+
| settingid | setting | value | fieldType | helptext                                                                                      | options                                                  | cat             | userChange | title     | validation | ordering | default | userSee | type |
+-----------+---------+-------+-----------+-----------------------------------------------------------------------------------------------+----------------------------------------------------------+-----------------+------------+-----------+------------+----------+---------+---------+------+
|        30 | audit   | Error | dropdown  | Set the level of logging the CMS should record. In production systems "error" is recommended. | Emergency|Alert|Critical|Error|Warning|Notice|Info|Debug | troubleshooting |          1 | Log Level |            |       20 | error   |       1 | word |
+-----------+---------+-------+-----------+-----------------------------------------------------------------------------------------------+----------------------------------------------------------+-----------------+------------+-----------+------------+----------+---------+---------+------+
1 row in set (0.00 sec)

mysql> update setting set value='Info' WHERE settingid=30;
Query OK, 1 row affected (0.09 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from setting WHERE settingid=30;
+-----------+---------+-------+-----------+-----------------------------------------------------------------------------------------------+----------------------------------------------------------+-----------------+------------+-----------+------------+----------+---------+---------+------+
| settingid | setting | value | fieldType | helptext                                                                                      | options                                                  | cat             | userChange | title     | validation | ordering | default | userSee | type |
+-----------+---------+-------+-----------+-----------------------------------------------------------------------------------------------+----------------------------------------------------------+-----------------+------------+-----------+------------+----------+---------+---------+------+
|        30 | audit   | Info  | dropdown  | Set the level of logging the CMS should record. In production systems "error" is recommended. | Emergency|Alert|Critical|Error|Warning|Notice|Info|Debug | troubleshooting |          1 | Log Level |            |       20 | error   |       1 | word |
+-----------+---------+-------+-----------+-----------------------------------------------------------------------------------------------+----------------------------------------------------------+-----------------+------------+-----------+------------+----------+---------+---------+------+
1 row in set (0.00 sec)

mysql> select * from setting WHERE settingid=30;
+-----------+---------+-------+-----------+-----------------------------------------------------------------------------------------------+----------------------------------------------------------+-----------------+------------+-----------+------------+----------+---------+---------+------+
| settingid | setting | value | fieldType | helptext                                                                                      | options                                                  | cat             | userChange | title     | validation | ordering | default | userSee | type |
+-----------+---------+-------+-----------+-----------------------------------------------------------------------------------------------+----------------------------------------------------------+-----------------+------------+-----------+------------+----------+---------+---------+------+
|        30 | audit   | Error | dropdown  | Set the level of logging the CMS should record. In production systems "error" is recommended. | Emergency|Alert|Critical|Error|Warning|Notice|Info|Debug | troubleshooting |          1 | Log Level |            |       20 | error   |       1 | word |
+-----------+---------+-------+-----------+-----------------------------------------------------------------------------------------------+----------------------------------------------------------+-----------------+------------+-----------+------------+----------+---------+---------+------+
1 row in set (0.00 sec)

mysql> 
`

**Comment by Mondlicht81** [comment]
.....it seems I found the solution.New feature, I had to set the "elevate until" date. :-)
Ticket can be closed.
