### ISSUE TITLE
Settings: Support host level proxy exceptions

### ISSUE THREAD

**Issue by Mondlicht81** [xibosignage/xibo#1096]
I struggled with the proxy exceptions list, as I have quite a few urls that should not use the proxy.
With following change, the current URL is checked if the hosts in the exception list are matching:

/var/www/cms/lib/Service/ConfigService.php
```php
  /**
   * Should the host be considered a proxy exception
   * @param $host
   * @return bool
   */
  public function isProxyException($host)
  {

        $proxyException = $this->GetSetting('PROXY_EXCEPTIONS');
        /* return ($proxyException != '' && stripos($host, $proxyException) > -1); */
        $strippedHost=parse_url($host,1);
        $proxyExceptionArray = explode(',', $proxyException);
        foreach ($proxyExceptionArray as $proxyExceptionArrayEntry){
                if (stripos($strippedHost, $proxyExceptionArrayEntry) !== false)
                {
                        /* Debug::Audit($strippedHost . ' in ' . $proxyException . '. Included in: ' . $proxyExceptionArrayEntry); */
                        return (true);
                }

        }

         return (false);
    }
```
Now, if my URL is http://subdomain.mysite.net/something.html, "mysite.net" is enough, to define this page as not to be sent to the proxy server. This way the proxy exceptions list should work in the same way as e.g. in Firefox.

As you can see, the debug log is still in the 1.7.x format, therefore commented out. As I currently don't know how to do it in Xibo 1.8, please change as you wish.

**Comment by dasgarner** [comment]
Perhaps this would work as well?

```
 /**
   * Should the host be considered a proxy exception
   * @param $url The requested URL
   * @return bool is exception
   */
  public function isProxyException($url)
  {
        $proxyException = $this->GetSetting('PROXY_EXCEPTIONS');
        return ($proxyException != '' && stripos(parse_url($url, PHP_URL_HOST), $proxyException) !== false);
    }
```

Re logging - it isn't possible to log in here anymore, as it does not have access to the Log handler.

**Comment by Mondlicht81** [comment]
You're right, that works as well but is shorter.

**Comment by dasgarner** [comment]
What is the difference?

List: 1,2,3,4
URL: 4

Comparing 1 and 4, 2 and 4, 3 and 4, 4 and 4 or comparing 1,2,3,4 and 4 gives the same result?

**Comment by Mondlicht81** [comment]
In my case I have several sub-domains
sub.int.net.mycompany.com
sub2.whatever.mycompany.com
sub3.mycompany.com

To allow local connections for all those domains, I specified mycompany.com in the proxy exceptions list.

Now I want a newsfeed to be displayed: sub2.whatever.mycompany.com/newsfeed.rss
The host part of the URL: sub2.whatever.mycompany.com
The exception list: mycompany.com,localhost,anotherhost.com
If I compare the URL with the exception list, I find no match. Only if I check if any of the exception list entries is part of my URL host, I can find a match.

As soon as you have subdomains, it only works that way I would say.
