### ISSUE TITLE
DataSetColumnList API Method Returning "Access Denied"

### ISSUE THREAD

**Issue by MichaelHoughton** [xibosignage/xibo#110]
Hey Dan

Would you just mind testing the DataSetColumnList method for me in the API.

In 1.6, it worked fine.

In 1.7 I am getting an error below:

[error] => Array
        (
            [code] => 1
            [message] => Access Denied
        )

Please let me know if it works for you at your end.

Thanks again.

**Comment by dasgarner** [comment]
Hey,

I get this:

``` json
{
	"datasetcolumn": [
		{
			"datasetcolumnid": "1",
			"heading": "Col1",
			"listcontent": "",
			"columnorder": "1",
			"datatype": "String",
			"datasetcolumntype": "Value"
		}
	]
}
```

I've got my example api app connected to a super admin account in the CMS.

**Comment by MichaelHoughton** [comment]
Hey Dan - this seems to be working with the latest version :)
