### ISSUE TITLE
Add new module

### ISSUE THREAD

**Issue by luxferoo** [xibosignage/xibo#1100]
Hi everyone ,

I wrote a php script who can pull entries from an ldap directory and insert them into xibo tables .

I added a form into settings (implementing the setting table) so the user can add the Ldap informations and now I would like to know how can I add a simple button below or above the "Save" button so I can execute the synchronization using the button with ajax.

Thank's.

**Comment by alexharrington** [comment]
Thanks for your message.

The project uses Github issues for confirmed bug reports only. Any general questions or support requests should be posted over on the Community Site: https://community.xibo.org.uk - in this case, in the Dev category.
