### ISSUE TITLE
Windows Player 1.8.0 - XMR - Exception in run: unknown block type / handle invalid

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1103]
OP: https://community.xibo.org.uk/t/xibo-cms-1-8-xmr-exception-in-run-handle-invalid/9241/3

Multiple reports with and without Docker of this error when CMS and Player are on the same machine.

Unable to reproduce at this stage.

**Comment by dack** [comment]
I'm seeing this error with separate machines for CMS and player. I'm also seeing issues with certain PDF files not working - possibly related?

**Comment by dasgarner** [comment]
A full stack trace is not printed by `ToString()`, need to adjust.
