### ISSUE TITLE
XMDS: 'Invalid Character error' on displayRegister when using Commands having a non-alpha reference code

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1106]
It seems that command string added to a display profile is causing the display to return following error:
`Invalid Character Error`

As a result display can't fully connect to the CMS to download content and update display information on Displays page etc.

It could be also caused by actual invalid character in the command itself - in which case we could try to check for that in CMS.

**Comment by dasgarner** [comment]
Do we have any more information for this one? I.e. what was entered in the command/validation string to cause the issue?

**Comment by alexharrington** [comment]
Everything we tried for a shutdown command triggered it.

eg

shutdown.exe /r /t 0

shutdown -r -t 0

shutdown.exe

I'd not be surprised if anything in that field triggers this.

**Comment by dasgarner** [comment]
In the above case it was the reference code causing the error - OP had entered `shutdown -r now` as the reference code, which is invalid.

Add validation to the reference code form to prevent this data entry.
