### ISSUE TITLE
Schedule Now - 'Please enter a from date'

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1117]
If you enter value in 'Hours' or 'Minutes' field and click 'Save' nearly at the same time it will produce the following error:
![image](https://cloud.githubusercontent.com/assets/12148978/24662670/aab4892c-194d-11e7-8e93-55932d212e7b.png)

Which means that even though the value was entered it wasn't 'set' yet, hence the error on the form.

It shouldn't really happen in normal use, as you need to do that rather quickly, but it is possible to trigger it, perhaps there is a way to improve how CMS handles that.

**Comment by dasgarner** [comment]
I think the save button should call the same function that is called when any of the time part fields change
