### ISSUE TITLE
Not save any changes in the "Adminstration" option (v1.7)

### ISSUE THREAD

**Issue by vmesquita** [xibosignage/xibo#112]
In CMS version 1.7 I can not save any changes in the "Administration" option: Library Location, CMS Secret Key, Regional Timezone, etc, etc, etc.

**Comment by dasgarner** [comment]
Can you describe what happens? I can confirm this is working on our variety of test systems. Maybe you can also provide a log?

**Comment by vmesquita** [comment]
Please access my test environment to check yourself not save settings! (Option: Administration / Settings)
http://xibotst.hol.es/server / user: xibo_admin / pass: admin

**Comment by xibo-de** [comment]
look in the log files from webserver
maybe this helps

**Comment by vmesquita** [comment]
Version 1.6.4 works fine .. But version 1.7 not ...

**Comment by dasgarner** [comment]
For some reason your web server is issuing a 302 redirect to `http://error.hostinger.eu/403.php`

You will need to check in your webserver logs to find out why - nothing is logged in the Xibo log which implies that the request is not actually getting as far as Xibo.

**Comment by vmesquita** [comment]
Possibly are trying to access any folder or file for writing! If you change any settings and click save, will the Xibo CMS tries to create a folder or document temporarily?

**Comment by dasgarner** [comment]
If your library doesn't have a temp/ sub folder, it will try and create one - so yes, I suppose that would be a write action!

**Comment by vmesquita** [comment]
I checked the temp folder exists! 

My provider has released a php to check it funcion is working on the link below:
http://xibotst.hol.es/check.php?f=function (function = mail, etc)

To check the parameters of PHP:
http://xibotst.hol.es/phpinfo.php

What has changed for 1.6 to 1.7? Is it possible to know?

**Comment by dasgarner** [comment]
The settings are being saved via AJAX now - other than this, nothing has changed.

What has changed in your server environment? We will need some logging to find out why that request is being redirected

**Comment by vmesquita** [comment]
xibo-cms-1.7.1 works ok !!!!!!

**Comment by dasgarner** [comment]
OK great - I'm not sure why, but great :smile:
