### ISSUE TITLE
Users can't select display on the Schedule page and form

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1123]
When you user has permissions to access all relevant pages (schedule, display, layout etc) and has permissions to specific layouts, displays assigned as well - it's the same if user has permissions to absolutely everything.

That user can see the displays and layouts he has permissions to on corresponding pages in the CMS, the problem is user can't select any display on the schedule page / new event or schedule now forms - layouts are available without problems.

If we create a display group and assign displays to it then of course assign permissions for that displayGroup to our user, then user can see the display group on the schedule page / new event or schedule now forms, but individual display still are not on the list.

On displays page where user can see the displays, the 'Assign files' and 'Assign Layout' buttons return following errors:
`	/displaygroup/form/media/1	Access Denied#0 [internal function]: Xibo\Controller\DisplayGroup->mediaForm('1') #1 /var/www/cms/vendor/akrabat/rka-slim-controller/RKA/Slim.php(79): call_user_func_array(Array, Array) #2 [internal function]: RKA\Slim->RKA\{closure}('1') #3 /var/www/cms/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array) #4 /var/www/cms/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch() #5 /var/www/cms/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call() #6 /var/www/cms/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call() #7 /var/www/cms/lib/Middleware/Actions.php(141): Slim\Middleware\MethodOverride->call() #8 /var/www/cms/lib/Middleware/Theme.php(35): Xibo\Middleware\Actions->call() #9 /var/www/cms/lib/Middleware/WebAuthentication.php(132): Xibo\Middleware\Theme->call() #10 /var/www/cms/lib/Middleware/CsrfGuard.php(62): Xibo\Middleware\WebAuthentication->call() #11 /var/www/cms/lib/Middleware/State.php(109): Xibo\Middleware\CsrfGuard->call() #12 /var/www/cms/lib/Middleware/Storage.php(47): Xibo\Middleware\State->call() #13 /var/www/cms/lib/Middleware/Xmr.php(36): Xibo\Middleware\Storage->call() #14 /var/www/cms/vendor/slim/slim/Slim/Slim.php(1302): Xibo\Middleware\Xmr->call() #15 /var/www/cms/web/index.php(124): Slim\Slim->run() #16 {main}`

`	/displaygroup/form/layout/1	Access Denied#0 [internal function]: Xibo\Controller\DisplayGroup->LayoutsForm('1') #1 /var/www/cms/vendor/akrabat/rka-slim-controller/RKA/Slim.php(79): call_user_func_array(Array, Array) #2 [internal function]: RKA\Slim->RKA\{closure}('1') #3 /var/www/cms/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array) #4 /var/www/cms/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch() #5 /var/www/cms/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call() #6 /var/www/cms/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call() #7 /var/www/cms/lib/Middleware/Actions.php(141): Slim\Middleware\MethodOverride->call() #8 /var/www/cms/lib/Middleware/Theme.php(35): Xibo\Middleware\Actions->call() #9 /var/www/cms/lib/Middleware/WebAuthentication.php(132): Xibo\Middleware\Theme->call() #10 /var/www/cms/lib/Middleware/CsrfGuard.php(62): Xibo\Middleware\WebAuthentication->call() #11 /var/www/cms/lib/Middleware/State.php(109): Xibo\Middleware\CsrfGuard->call() #12 /var/www/cms/lib/Middleware/Storage.php(47): Xibo\Middleware\State->call() #13 /var/www/cms/lib/Middleware/Xmr.php(36): Xibo\Middleware\Storage->call() #14 /var/www/cms/vendor/slim/slim/Slim/Slim.php(1302): Xibo\Middleware\Xmr->call() #15 /var/www/cms/web/index.php(124): Slim\Slim->run() #16 {main}`

Additionally it seems that view/edit/delete permissions assigned to a specific display does not always guarantee that the user will be able to actually access edit/manage  etc buttons on that display - in some cases the row edit dropdown menu remains empty.

It could have something to do with displayId and displayGroupId changes made recently perhaps permissions are not always correctly assigned because of that?

The issue is non existent as a super user user type though.

**Comment by Zebwen** [comment]
Could you please confirm which version of CMS this issue is resolved in? Still present in 1.8.1. Is it corrected in 1.8.2?
