### ISSUE TITLE
User / user-groups right

### ISSUE THREAD

**Issue by tali1974** [xibosignage/xibo#113]
Hi.. nice work guys...

A user in one user group should not be able to se other users names under the "permission" option..
Now when a user open a layout or a region and press "permission" he can view all the users in the system, He/She should only be able to view users inside his own user-groups. 

Regards
T

**Comment by dasgarner** [comment]
We've discussed this before but not implemented it yet - the current thinking is:

Have a global setting called "Restrict users to only see peers in their Groups" which made it so that Group Admins / Users could only see other users in the groups. 

For example

Group A: User 1, User2, User3
Group B: User 4, User3
Group C: User1, User5

User 1 can see: User2, User3, User5
User 2 can see: User1, User3
User 3 can see: User1, User2, User4
User 4 can see: User 3
User 4 can see: User 1

**Comment by tali1974** [comment]
Thanks.. do you know when this will be implemented..

Or is there a way to remove the "permissions" for only "Users" group ?


Regards
T

Date: Sat, 31 Jan 2015 03:53:59 -0800

**Comment by tali1974** [comment]
May be we could add something very basic and easy like this....

in the pages under /lib/pages

we could add 

if usertypeid is = 3 (User) than don not show "permissions" option..

 
From: tahirzaman@hotmail.com
To: reply@reply.github.com
Subject: RE: [xibo] User / user-groups right (#113)
Date: Sat, 31 Jan 2015 14:54:15 +0100




Thanks.. do you know when this will be implemented..

Or is there a way to remove the "permissions" for only "Users" group ?


Regards
T

Date: Sat, 31 Jan 2015 03:53:59 -0800

**Comment by tali1974** [comment]
Maybe here... could add code to check the user role... if not Super Admin. dont show this permissions option...
if ($row['modifypermissions'] == 1)
            {
                // Permissions for Campaign
               
                $row['buttons'][] = array(
                        'id' => 'campaign_button_delete',
                        'url' => 'index.php?p=campaign&q=PermissionsForm&CampaignID=' . $row['campaignid'],
                        'text' => __('Permissions')
                    );
            }


From: tahirzaman@hotmail.com
To: reply@reply.github.com
Subject: RE: [xibo] User / user-groups right (#113)
Date: Sat, 31 Jan 2015 15:25:59 +0100





May be we could add something very basic and easy like this....

in the pages under /lib/pages

we could add 

if usertypeid is = 3 (User) than don not show "permissions" option..

 
From: tahirzaman@hotmail.com
To: reply@reply.github.com
Subject: RE: [xibo] User / user-groups right (#113)
Date: Sat, 31 Jan 2015 14:54:15 +0100




Thanks.. do you know when this will be implemented..

Or is there a way to remove the "permissions" for only "Users" group ?


Regards
T

Date: Sat, 31 Jan 2015 03:53:59 -0800

**Comment by dasgarner** [comment]
Unfortunately that isn't going to work for everyone - in some systems people want their users to be able to share their work.

If you just want to patch your own system, I would recommend the following changes to `lib/app/permissionmanager.class.php` after `Line #71

``` php
if ($this->user->usertypeid == 3) {
    $this->modifyPermissions = false;
}
```

**Comment by tali1974** [comment]
Great thanks so much. . I'll try it later today


Regards
Tahir Ali


-------- Original message --------

**Comment by dasgarner** [comment]
Great, i'll leave this issue around for the built in enhancement spoken about in my first comment.

**Comment by tali1974** [comment]
Dear i did add these lines, but that did not have any effect..

    public function Evaluate($ownerId, $view, $edit, $del)
    {
        $user =& $this->user;

        $this->ownerId = $ownerId;
        $this->view = $view;
        $this->edit = $edit;
        $this->del = $del;

        // Basic checks first
        if ($this->user->usertypeid == 1 || $ownerId == $user->userid)
        {
            // Super admin or owner, therefore permission granted to everything
            $this->FullAccess();
        }
        else if ($this->user->usertypeid == 2 && $this->view == 1)
        {
            // Group Admin and we have view permissions (i.e. this group is assigned to this item)
            $this->view = true;
            $this->edit = true;
            $this->del = true;
        }

ADD THE LINES HERE

if ($this->user->usertypeid == 3) {
    $this->modifyPermissions = false;
}

    }


Date: Sat, 31 Jan 2015 16:50:12 +0100
Subject: Re: [xibo] User / user-groups right (#113)
From: tahirzaman@hotmail.com
To: reply@reply.github.com






Great thanks so much. . I'll try it later today 






Regards
Tahir Ali





-------- Original message --------

**Comment by dasgarner** [comment]
Ah yes, sorry...

you also need to add the same at the end of the `FullAccess()` function in that same file.

Thanks,
Dan

**Comment by tali1974** [comment]
Thanks... that did work...


Date: Sun, 1 Feb 2015 04:48:49 -0800
