### ISSUE TITLE
Twitter module config help

### ISSUE THREAD

**Issue by pcrandrew** [xibosignage/xibo#114]
Hi, I think I have configured the Twitter module correctly in 1.7.0 with my Twitter API key and secret key. The CMS has web access and is accessing RSS feeds OK through layout previews and the web browser. When I add a Twitter feed to a layout, the log shows the messages shown below, suggesting that nothing is being returned from the curl_exec function in $result. Is there any generic help or obvious things to check first? 
Thanks, Phil. 

Bearer Token served from API, 

followed by 
```
 <errormsg>Undefined offset: 1</errormsg>
 <errornum>8</errornum>
 <errortype>Notice</errortype>
 <scriptname>C:\xampp\htdocs\xibo\modules\twitter.module.php</scriptname>
 <scriptlinenum>659</scriptlinenum> 
```
followed by 

 Twitter API returned status. Unable to proceed. 

followed by 
```
<errormsg>Undefined offset: 1</errormsg>
 <errornum>8</errornum>
 <errortype>Notice</errortype>
 <scriptname>C:\xampp\htdocs\xibo\modules\twitter.module.php</scriptname>
 <scriptlinenum>670</scriptlinenum>
```
followed by 

 Twitter Error: Unknown Error

**Comment by dasgarner** [comment]
I've swapped some things around for you in that file so that you should get some better error logging out of the `curl_exec` call. I'm not sure what we will find if i'm honest, but hopefully the error will be more meaningful

Can you try patching your `twitter.module.php` file?

**Comment by pcrandrew** [comment]
Many thanks - that revealed the problem to be with certificates. One more request - what do I have to do to install the twitter CA bundle to work with curl? Phil

**Comment by dasgarner** [comment]
It should be as simple as downloading the certificates onto the web server and then pointing to them in PHP ini:

`curl.cainfo=C:/path/to/cacert.pem`

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
