### ISSUE TITLE
Dayparting: User type user can't see created dayparts

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1140]
Currently even if user has all permissions on page security, while he can create a new daypart on Dayparting page, he will not see it on the list there or on schedule page.

The daypart is created correctly - super admin can see it, but it would seem that super admin is the only user type that can actually see/edit and use created dayparts.

Since user with permissions to Dayparting page can create them, that user should also be able to see and use them.

**Comment by easyled** [comment]
If SuperAdmin can create Dayparts, Users should be able to see Dayparts created by SuperAdmin, without specially being able to create dayparts. That could work as well in most user cases.

**Comment by dasgarner** [comment]
> If SuperAdmin can create Dayparts, Users should be able to see Dayparts created by SuperAdmin, without specially being able to create dayparts.

This would require a permissions menu item, same concept as on other objects covered by permissions.
