### ISSUE TITLE
Schedule - Overlay layout will show empty layouts list when there is no campaign in the CMS

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1148]
Currently when there is no campaign in the CMS when we try to schedule an overlay layout the 'Layout / Campaign' field will be empty.

If we add a campaign to the CMS, then the layouts list under  'Layout / Campaign' field on the schedule form will be populated correctly.

It seems to be a bug only with the web ui, as it is possible to schedule overlay layout event via API without problems.

One solution could be to add empty campaign record under line 89 - https://github.com/PeterMis/xibo-cms/blob/develop/views/schedule-form-add.twig#L89

ie add
```
{# Add a blank campaign record #}
{% set campaignOptions = [{id: "", value: ""}]|merge(campaignOptions) %}
```

Which will add empty campaign record and layouts will be populated correctly on the Overlay layout event, even without any campaigns in the system.

OP - https://community.xibo.org.uk/t/overlay-layout-bug-1-8-1/9728

**Comment by dasgarner** [comment]
I think this is mostly likely a JavaScript error - when the eventTypeId changes to Overlay Layout, some JS is run which removes all Campaign records from the drop down of campaign/layout.

This JS must be erroring.

Adding an empty Campaign record (while works) is probably not the approach to use, we should fix the JS error instead.

**Comment by dasgarner** [comment]
Turns out Peters suggestion is by far the easiest way to solve this issue.
