### ISSUE TITLE
Datasets - The formula text missing after upgrade 1.7.9->1.8.1

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1157]
We had a report saying that in 1.7.9 CMS Instance there was a formula column type with formula in Formula field, but after upgrade to 1.8.1 CMS version, the formula text in Formula field was gone.

We should investigate this report further.

**Comment by dasgarner** [comment]
I can't see anything obvious, we will need to try and recreate

**Comment by dasgarner** [comment]
Can't recreate
