### ISSUE TITLE
Unknown character set: 'utf16' upgrade 1.6.4 to 1.7.0

### ISSUE THREAD

**Issue by FireROR** [xibosignage/xibo#119]
And now...
An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 82. Error Message = [SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY']

Upgrading from database version 81 to 84

How to fix that?

**Comment by dasgarner** [comment]
Apologies, you can update `utf16` to `utf8` in `82.sql`, restore your backup and run the upgrade again.

This has already been fixed in the latest development branch code.

**Comment by FireROR** [comment]
I tried to run all the sql directly against to the db through mysql cli. And the system seems ok now. Does it work like that?

Thanks

**Comment by dasgarner** [comment]
Provided all of the SQL in 82, 83 and 84.sql is run then the upgrade will be complete. It may be better to resolve the issue with the utf16 declaration in `82.sql` and run from backup - but if you are happy you have run all of the necessary commands you should be OK.

**Comment by FireROR** [comment]
Everything seems ok but the library shows nothing..

**Comment by FireROR** [comment]
table lktagmedia is missing from the xibo database. I have to manual re-create to fix the pic issue.

Now everything is ok. (I didn't have the db backup and have to fix it instead of restore.)

Thanks a lot. Will do backup next time!!!

**Comment by dasgarner** [comment]
Ah right! :smile: yeah, backup is always advisable as we do miss some things sometimes (we can only test on N number of environments, etc).
