### ISSUE TITLE
Library - Shows incorrect value for all entries with German locale

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1193]
When we set German as CMS language and navigate to the library page it will not show a number of total entries in the library.

For example with English locale it will show:
`Showing 1 to 10 of 234 entries`
while with German locale it will show:
`Zeige 1 bis 10 von 10 Einträgen`

All items are still in the library (pages does work correctly), but the total number of entries is incorrectly presented.

**Comment by dasgarner** [comment]
Translation issue:

![image](https://user-images.githubusercontent.com/10400067/26973439-8d208934-4d0e-11e7-8ba8-a55e5a72113f.png)
