### ISSUE TITLE
Player: Hardware Acceleration for WebBrowser control

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#1197]
OP: https://community.xibo.org.uk/t/feature-bugfix-inside-activating-gpu-accelleration-for-xibo-for-windows-player-solution-for-slow-stuttering-marquee-ticker-effects/10130

Investigate and should everything be OK, make changes to the installer.

**Comment by schories** [comment]
Clarified the registry keys for 64 Bit and 32 Bit Windows. Thank you very much!
