### ISSUE TITLE
How to start Watchdog Service

### ISSUE THREAD

**Issue by ygurdag** [xibosignage/xibo#120]
I found documantation about watch service at http://xibo.org.uk/manual-tuttle/en/install_windows_client_watchdog.html
But cannot understand how to activate and where is the xml file for settings. 
Thanks

**Comment by dasgarner** [comment]
We are still running tests on it, if you want to try it then it can be found here: https://github.com/xibosignage/xibo-windows-client-watchdog/tree/master/bin/Release

**Comment by ygurdag** [comment]
Thank you,
I download source code. This works, but there is a problem. If xibo client gives error, there is a confirmation box (Windows Error Reporting) so it stays on screen even Watchdog restarts xibo player. I write some additional code for windows error reporting like this;
Process[] proc2= Process.GetProcessesByName("WerFault");

                            if (proc2.Length > 0)
                            {
                                
                                // Stop the exe's (kill them)
                                foreach (Process process in proc2)
                                {
                                    process.Kill();
                                }
                            }

So now, it closes error windows also..
Thanks

**Comment by dasgarner** [comment]
It would be great if you could submit a pull request for that modification?
