### ISSUE TITLE
Display page stop showing the screens

### ISSUE THREAD

**Issue by ptedeschi** [xibosignage/xibo#1203]
After enabling Curent Layout column , the display page stop showing the screens (Showing 0 to 0 of 0 entries (filtered from NaN total entries) even when my Dashboard shows them correctly.

This is the log error: 
1999	cf1185a	2017-05-28 15:16	WEB	GET	ERROR		/display	SQLSTATE[42S22]: Column not found: 1054 Unknown column 'currentLayout' in 'order clause' Exception Type: PDOException

**Comment by alexharrington** [comment]
Did you have a problem on a previous upgrade and skip a step perhaps? That might well have led to their being missing columns in your database.

We deal with support requests over on our Community Site https://community.xibo.org.uk

If you could post your request there, someone will try and help you.
