### ISSUE TITLE
Text not displayed after migration to 1.7

### ISSUE THREAD

**Issue by Sam68** [xibosignage/xibo#121]
I have migrate to 1.7.
Since it is not possible to display text in a Region.
The error occur by new layout and old layout

Thank for help

**Comment by dasgarner** [comment]
Can you be a little more specific?

Does the text display correctly in the CMS? Does it display in the Preview? Does it display in the Player?

If it displays in the CMS but not in the Player, can you try and "Verify All" from the CMS Modules page?

**Comment by Sam68** [comment]
Super :-)))
The "verify All" solve the problem !!!
But i have one more problem since the migration :
Embedded HTML don't work with this IFrame

<iframe width="976" height=0"609" frameborder="0" scrolling="no" src="
http://www.gmodules.com/gadgets/ifr?url=http://prac-gadget.googlecode.com/files/google-plus-slideshow.xml
&up_URL=
https://plus.google.com/photos/113071268644330883310/albums/6103445593786724577
&up_PWH=976
&up_PHT=609
&up_DTime=4000
&up_TTime=
&up_RND=No
&up_NAB=No
&up_CLP=No
&up_SCOL=%23c3d9ff
&up_BCOL=%23ffffff
&up_CCOL=%23ffffff">
Gadget Google - Diaporama d'un album Google+ -
http://www.liens-du-vin.ch/google-plus-slideshow.htm</iframe>

with version 1.6 everything worked



2015-02-02 13:12 GMT+01:00 Dan Garner <notifications@github.com>:

**Comment by dasgarner** [comment]
You have a problem with that HTML - look at the `<iframe width="976" height=0"609" frameborder="0" scrolling="no" src="` line

The height attribute is wrong (it resolves to 0) - it should be `height="609"`

**Comment by Sam68** [comment]
Merci beaucoup pour votre aide :-)
Samuel

2015-02-02 15:11 GMT+01:00 Dan Garner <notifications@github.com>:

**Comment by dasgarner** [comment]
De rien :smile:
