### ISSUE TITLE
Error transition menu (Xibo V1.7.0)

### ISSUE THREAD

**Issue by xibo-de** [xibosignage/xibo#122]
Hi,
if a normal user (not super_admin) calls the Administration -> transition menu, the message:

Application error, no permission for this page

is displayed.

Best regards, Hubert

**Comment by dasgarner** [comment]
Can you try unassigning and assigning the "Content" permission for that user?

**Comment by xibo-de** [comment]
The user is member of group "Users".

Group "Content" permission is enabled
 -> not working


both
Group "Content" permission is enabled
and
User "Content" permission is enabled
-> not working

**Comment by dasgarner** [comment]
Sorry to be pedantic, but did you un-assign and reassign?

I've run some tests and I can't get it to break :disappointed:

**Comment by xibo-de** [comment]
now, only Group "Content" permission is enabled and
it works !

my mistake, who can read ...
that's it: (unassigning and assigning).

Thank You

**Comment by dasgarner** [comment]
Great, glad it was simple!
