### ISSUE TITLE
Dashboard - Displays names with special characters are incorrectly displayed

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1233]
When have a display called for example:
46'' - a and we connect it to the CMS it will display correct name on the Displays page, but on Edit display form and on Dashboard page we will see `46&#34; - a`.

The `&#34;` is hmtl code for '', it seems to happen only when the name comes from the player - if we change the display name on Displays page to contain '' characters it will be shown fine on both Displays and Dashboard pages.

Examples of a device name with '' (coming from the player).

Displays page:
![image](https://user-images.githubusercontent.com/12148978/28012690-8a0de2a6-655e-11e7-8b07-9f1d6daa9e68.png)

Dashboard page:
![image](https://user-images.githubusercontent.com/12148978/28012858-1104a90c-655f-11e7-8538-cfd42cace01f.png)

If we change the name on Edit display page and manually enter name with '' (instead of html code that will be there) then it will show the names correctly.

**Comment by dasgarner** [comment]
This seems to only be an issue with the computer name when that computer name has a " in it. I'm not sure how to fix, it doesn't seem right to decode all entities when we receive a new register call - equally, notify status doesn't appear to be effected.

I think the display name returned by the player must contain the entities: https://github.com/xibosignage/xibo-dotnetclient/blob/develop/Logic/ApplicationSettings.cs#L372

Specifically

```
Environment.MachineName
```
