### ISSUE TITLE
Xibo installation for latest version

### ISSUE THREAD

**Issue by sreylak** [xibosignage/xibo#1237]
Thank you for your interest in the Xibo Project.

The Xibo Project uses Github Issues to record verified bugs only.

If you're having difficulties with Xibo, or need support,
please post on our Community Site here: https://community.xibo.org.uk 

If the issue you are having does turn out to be a verified bug, a 
representative will log it here as an issue on your behalf.

If you are sure the problem you have is a bug, and have verification,
please feel free to remove this text and log your issue, ensuring you
give as much detail as possible about your environment, steps to
replicate the issue, and the versions of Xibo CMS and Player that
you are using by number. Please avoid using "Latest" as this is 
ambiguous.

**Comment by sreylak** [comment]
I have use Xibo from 1.7.5 but after I install is easy but when I test with 1.7.9 version it very complicated.

**Comment by alexharrington** [comment]
Thank you for your interest in the Xibo Project.

The Xibo Project uses Github Issues to record verified bugs only.

If you're having difficulties with Xibo, or need support,
please post on our Community Site here: https://community.xibo.org.uk
