### ISSUE TITLE
Unable to StartNextLayout: Not valid: Unknown color

### ISSUE THREAD

**Issue by nagyrobi** [xibosignage/xibo#124]
My Android clients don't start playing anything. The error is:
Unable to StartNextLayout: Not valid: Unknown color
I'm using just the default "Welcome" layout which came with Xibo installation, only rewrote the text.

Both server and clients are 1.7

**Comment by dasgarner** [comment]
Ah, the default layout is slightly incorrect.

Can you edit the background colour and click save - that should solve the issue.

I'll fix the layout in the source.
