### ISSUE TITLE
Weather widget - Add an option to load in css from the pre-defined template on edit

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1241]
As it is when you override a template and make changes to it and save it, then after switching to another pre-defined template and clicking the override template button, all settings + CSS will be cached from the template you've edited before. 

Which has it's uses and prevents from deleting user custom template content, by switching to a different pre-defined template.

It could be a good idea to add an option ( a button perhaps) that would let user clear the cached css from the edited template and load in the CSS from the pre-defined template that's currently selected.

**Comment by dasgarner** [comment]
@PeterMis Need some clarification on this please - if I do as you've described, switch to another template and tick override again - the new template is already there.
