### ISSUE TITLE
Transitions - not showing out transitions with one item in the region

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1245]
Not sure if we can fix that, but it does seem like a bug to me.

Example:
New layout, one region, one image in the region, we add in/out transitions for the image (and exit for region).
It will show in transitions as it should, but then it won't show out transitions, it will just reload the layout.

We need to enable 'loop' on the region, then both transitions are displayed correctly, not sure if that's intended though.

If we add second image with in/out transitions, then it will correctly show in/out transitions for both images, as expected.

Affects both fade and fly transitions, for obvious reasons it's more noticeable with fly transitions.

There seems to be a little rendering issue with fly in transitions, seems to be hardware dependant though.
It starts to display the fly in transition, then stops, reloads the layout and starts again - there is a short video presenting the issue here https://community.xibo.org.uk/t/android-client-bug-with-fly-with-the-south-orientation/10864/5
It less noticeable on our recommended hardware, although you can still see it, perhaps it would be wise to investigate that further.

OP - https://community.xibo.org.uk/t/android-client-bug-with-fly-with-the-south-orientation/10864

**Comment by dasgarner** [comment]
Android bug - moved to the android bug tracker.
