### ISSUE TITLE
Layouts Background - Background image field disappears after uploading new background image

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1248]
When we open background menu for a layout, click on 'Add a new background image'  and upload new image, the field for 'Background Image' is no longer available in the form.

In most cases that would be fine, as presumably we want to set the uploaded image as a layout background, although perhaps we should leave the option to change the background without a need to save and reopen the form as well. 

OP - https://community.xibo.org.uk/t/selecting-background-pic-a-little-bit-puzzling/10900

**Comment by dasgarner** [comment]
Solved in #1244
