### ISSUE TITLE
Layouts - Multiple layouts import causing SQL deadlock

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1250]
When we try to import 2 or more layouts at the same time (ie in the same form), we may encounter 'Empty file upload result' error, if we look in the logs we can see relevant sqlstate errors:

`/layout/import | SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction Exception Type: PDOException`

`/layout/import | SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction#0 /var/www/cms/lib/Storage/PdoStorageService.php(209): PDOStatement->execute(Array) #1 /var/www/cms/lib/Entity/User.php(902): Xibo\Storage\PdoStorageService->update('UPDATE `user` S...', Array) #2 /var/www/cms/lib/Middleware/WebAuthentication.php(125): Xibo\Entity\User->touch() #3 [internal function]: Xibo\Middleware\WebAuthentication->Xibo\Middleware\{closure}() #4 /var/www/cms/vendor/slim/slim/Slim/Slim.php(1210): call_user_func_array(Object(Closure), Array) #5 /var/www/cms/vendor/slim/slim/Slim/Slim.php(1358): Slim\Slim->applyHook('slim.after.disp...') #6 /var/www/cms/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call() #7 /var/www/cms/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call() #8 /var/www/cms/lib/Middleware/Actions.php(142): Slim\Middleware\MethodOverride->call() #9 /var/www/cms/lib/Middleware/Theme.php(35): Xibo\Middleware\Actions->call() #10 /var/www/cms/lib/Middleware/WebAuthentication.php(132): Xibo\Middleware\Theme->call() #11 /var/www/cms/lib/Middleware/CsrfGuard.php(62): Xibo\Middleware\WebAuthentication->call() #12 /var/www/cms/lib/Middleware/State.php(117): Xibo\Middleware\CsrfGuard->call() #13 /var/www/cms/lib/Middleware/Storage.php(47): Xibo\Middleware\State->call() #14 /var/www/cms/lib/Middleware/Xmr.php(36): Xibo\Middleware\Storage->call() #15 /var/www/cms/vendor/slim/slim/Slim/Slim.php(1302): Xibo\Middleware\Xmr->call() #16 /var/www/cms/web/index.php(124): Slim\Slim->run() #17 {main}`

All tested layout import fine when imported one by one, the issue only occurs when we try to import multiple layouts.

OP - https://community.xibo.org.uk/t/fail-import-multi-layouts-on-cms-1-8/10938

**Comment by dasgarner** [comment]
Unfortunately the linked fix causes issues on first installation - the login form deadlocks.

I think it will be the case that any update to the user during login/logout will also deadlock.
