### ISSUE TITLE
Layout - Change Owner does not work correctly

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1254]
Currently when we change the owner of a layout, it will be updated in the 'Owner' column in web ui.

If we will try to filter the layout list by the owner, then it's clear that owner of that layout is not actually changed.

If we look at it via API (GET layout), then:
The "owner" will be changed (same as in web ui), but the
the "ownerId" (ie userId) remain unchanged

New 'owner' will also not have access to the layout, which confirms that the ownerChange is not actually working with Layouts currently.

Changing the owner via API seems to have the same result as the change in web ui.

The log line 
'Requesting update to a new Owner - id'
Is showing correct id, but after that the change is not made.

It's also working fine for example for media (via api and web ui), which uses the very same API call as layout change owner, the setOwner functions are the same between media and layout entities.

Perhaps something with the sql query and table update then?

**Comment by sgiunchi** [comment]
Using 1.8.3 I still see this bug. 
The "cascade" workaround works.
Tried on a pre-1.8 layout, not a new one.
