### ISSUE TITLE
DataSet import - enhancements 

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1260]
We may look into restricting the upload from to one .csv file, although there might be cases when it's better to allow multiple imports? In which case it might be better to leave it as it is.

Another mentioned suggestion was the column ordering, in 1.7.9, column order on import was pre-populated, in 1.8 without manually entering those values for each column, import will fail - without an error, but it will not import the data from .csv.  Perhaps we should bring this feature back?

OP - https://community.xibo.org.uk/t/csv-import-dataset-1-8-2/11059

**Comment by dasgarner** [comment]
I see no reason why we wouldn't allow multiple files to be uploaded by that form - it is already restricted to one at a time.

The other change has been made, defaulting the newly opened form to sequential column values.
