### ISSUE TITLE
Google Traffic - Incorrectly shows maps if default display long/lat is set to 0 in CMS settings

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1261]
If for some reason, user will change the default display longitude and/or latitude in CMS settings to 0.
Then google traffic (presumably everything that use display location) will show incorrect data - of course in this case the long/lat are set directly in the google traffic widget, we are not using display location, which is also broken with that setting, but that's to be expected.

There are also no logs that would imply that setting default lat/long to 0 is incorrect (ie it validates fine with it set like that).

We should either validate against 0 in lat/long settings or make sure that if it is set like that, then that it does not affect widgets that are using manually entered lat/long.

OP - https://community.xibo.org.uk/t/gps-traffic-error-positioning/11049/14

**Comment by dasgarner** [comment]
This is not a bug - who are we to say that 0/0 is an invalid lat/long
