### ISSUE TITLE
Xibo has stopped working

### ISSUE THREAD

**Issue by ygurdag** [xibosignage/xibo#127]
Hi,
I have reported same problem before, but now I have some more information about how this problem happens. 
To simulate problem on your side;
1. Open Display Setting Profiles, and add new one. On Troubleshooting tab set Log Level to "Audit". And on General tab set Collection Interval (in Seconds) to "30" seconds. 
2. Assign this setting to a client and wait for client takes new settings. 
3. Set a new layout with 1 picture and 3 seconds duration. And schedule this layout to the client.
4. After client takes new layout close client's internet connection. It will start to make lots of log files in library folder.
5. After client logs about 30-40 or more files, connect the internet again. 
6. At this time you can try to send a new layout (which have files for client should download)
Now Client will try to send log files and try the take information or files from server at the same time, and in 5 minutes or less client stops working. 

I know the parameters we set are not normal usage, but the most important thing for an application to be stable at very hard conditions. Because if client stops, there is an annoying box and it says "Xibo has stopped working" and you have to close this dialog box. If you don't have direct connection to client (team viewer, vnc exc.) this is big problem. 
I love this application and thanks for everyone who build and make something about it. Please take care about this very very important point. 
Best Regards
Michael.

**Comment by nagyrobi** [comment]
Is this Windows client?

**Comment by ygurdag** [comment]
Yes, 1.7.

**Comment by dasgarner** [comment]
I think we will need to make it so that it yields when sending back logs.

Very good catch - thank you!

**Comment by dasgarner** [comment]
I think that this is because the files took longer to send than it took for the next flush to occur (the time it took to generate 25 messages).

I've made changes to lock the process that sends the log files so that should this happen the threads will be queued up, waiting for the prior one to complete.

Please would you try the EXE from here: https://github.com/dasgarner/xibo-dotnetclient/tree/develop/bin/x86/Release
