### ISSUE TITLE
Ensure we display double spaces on key fields

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1273]
Currently it is possible to add space character to, for example, the layout name, in which case in CMS it will be no way to tell them apart in web ui (visible via API though).

That  is not intended, we should trim the spaces from such fields.

**Comment by dasgarner** [comment]
I'm worried about the scope of this change and have therefore pushed it into 1.9 where we will most likely implement an improved sanitiser.

**Comment by dasgarner** [comment]
On second thoughts - it would be better to ensure we display double spaces on key fields - we can do that with the `white-space:pre` modifier
