### ISSUE TITLE
Layout designer media upload causes unfavorable resize

### ISSUE THREAD

**Issue by Swwils** [xibosignage/xibo#1287]
Environment: 

Xibo Version 1.8.2 on Ubuntu 16.04 LTS docker in GCP

Browsers: Chrome, Firefox 

Client: 

Android V1.8 R102

Issue:

When uploading PNG and JPG of 1080x1920 (portrait) directly from the region timeline media uploader the media is scaled to a reduced filesize and then does not display at the signage native resolution. But this does not happen when uploading directly to the library.

For instance, our signs are 1080x1920 full HD in portrait orientation and when the timeline has items added from the Library (uploaded through the library interface) they appear on the sign at a native resolution; however when uploaded through the "image" selector on the region timeline e.g. not uploaded beforehand they appear slightly blurry due to a file size being smaller than the original file (resize). 

Here is a screenshot from the library showing the differences in file size from each upload [window.]

![capture](https://user-images.githubusercontent.com/7786680/29978110-be72ac18-8f37-11e7-862a-230255a331ce.PNG)

Uploading from the "library" for things previously uploaded in the library uploader shows the correct filesize before upload (40.65KB
![capture2](https://user-images.githubusercontent.com/7786680/29978173-ed1724e0-8f37-11e7-9528-141794c2262a.PNG)

Uploading from the region timeline and selecting "image" shows incorrect and resized filesize before upload is initiated (27.89KB)
![capture3](https://user-images.githubusercontent.com/7786680/29978206-1831e5d4-8f38-11e7-9d78-418be5c8225d.PNG)

Initially I thought that perhaps this layout or screen did not have the right resolution, but the layout is 1080p HD portrait which is correct for the source image at 1080w x 1920h - and the version uploaded from the library displays correctly, indicating that the screen playout is OK.

**Comment by alexharrington** [comment]
I'm pretty sure we investigated something along these lines before and it turned out to be browser-specific.

I'll have a go and see if I can replicate it here.

Sufficed to say, if it's doing it in the browser uploader before you even hit upload, then it suggests that it's client side JS in the uploader that's triggering that - and indeed it is a feature of that uploader to do that, although we have it turned off.

You're definitely not running any script blockers, and have cleared your web browser cache fully?

**Comment by alexharrington** [comment]
Confirmed on 1.8.2. Reproduction. Upload a 1080x1920 image to an image widget on a 1920x1080 layout, and it will be resized client side prior to upload.

![image](https://user-images.githubusercontent.com/10450518/30024313-231e7702-916b-11e7-9a33-0bbc5bcb5a1a.png)

Source file was 1.06MB

**Comment by Swwils** [comment]
Interestingly I cannot replicate in IE (typical!), but still have the issue in Chrome / FF even with cache clear and extensions disabled.
