### ISSUE TITLE
.NET CORE for windows player

### ISSUE THREAD

**Issue by rolembergfilho** [xibosignage/xibo#1289]
Hi,

I'm new here.

I would like to know if we can do some efforts to migrate Windows Player Project to .NET Core.

In really, it'll have 2 projects: 1 stable and actually functional .NET and another new one in .NET Core.

The target is deploy a player that works in Windows. Linux and Mac.

What do you think about this?

**Comment by alexharrington** [comment]
As far as I'm aware, .net core doesn't offer GUI classes.

We have plans and indeed development work underway for a Linux Player.

The place to read about those and have input is our Community Site: https://community.xibo.org.uk

We keep Github issues for tracking confirmed bugs only.
