### ISSUE TITLE
Not saving positions

### ISSUE THREAD

**Issue by jackson247** [xibosignage/xibo#129]
After placing everything where it needed to be Friday of last week, I come in Monday to make changes. When I moved a region it gave me the dimensions of "Nan x Nan". I saved the position and left the layout design and returned back to it.
This is when I saw that all of my regions were moved into the top right corner and their size reset. 

![Image of Issue](http://i.imgur.com/WhOR5hz.png)

I'm using v1.7.0, windows server
Is there something I'm doing wrong or is it another issue?
Thanks

**Comment by dasgarner** [comment]
It shouldn't ever say NaN (not a number), but I am not sure why it would.

Did you click "Save Positions" after making all your changes on Friday?

**Comment by jackson247** [comment]
I did. I made sure everything was set and saved when I left. Even if I save the positions after editing them with the "not a number", it places them back into the same positions in the top right. 

![Image](http://i.imgur.com/XNSBHUF.png)

As soon as I move a region it changes to NaN

**Comment by dasgarner** [comment]
Can you export your layout and put it somewhere we can download it? I can import it into our test system and see whats up.

**Comment by jackson247** [comment]
When trying to export I get:
"There has been an application error.Can't create ZIP. Error Code: 11"

**Comment by dasgarner** [comment]
It is trying to save a file in the temporary folder of your library and doesn't have permission to do so... perhaps your library isn't writeable?

**Comment by jackson247** [comment]
It seems like it didn't have the correct permissions. Thanks for the heads up! 

As for the problem above, it seemed to have fixed when I cleared the cache. The regions were still misplaced but after clearing it I was able to place them and it would save. 

Also the fix for: https://github.com/xibosignage/xibo/issues/131
