### ISSUE TITLE
Recent Log Messages - put the new ones on top

### ISSUE THREAD

**Issue by nagyrobi** [xibosignage/xibo#130]
A suggestion: it would be practical in Recent Log Messages to have the newest messages on top, that is, display the log in reverse order. The log window can become quite long after a while, and when debugging operation it's really annoying to have to scroll down after each page reload.

**Comment by dasgarner** [comment]
Hmm, interesting - the database is serving them in reverse order already, so perhaps the table sorter is responsible.

For your sanity in the mean time, you could use the log page filtered by the display.
