### ISSUE TITLE
Layouts page - Layout created from template do not save permissions correctly

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1302]
Scenario:
Create a template, assign view/edit with 'Cascade permissions to all items underneath this one' permissions to the template for a user.
Log in as that user and create a layout from the template
The layout will be created, but user won't be able to add any content to the regions that came with the template.

The reason behind that is, the permissions on regions created from templates are not saved at all.

The work around is, to assign view/edit with 'Cascade permissions to all items underneath this one' permission to this layout, which can be done by the user himself as he's the owner of the layout.

Obviously those permissions should stay as they are on the template.

Log error on access denied:

`Access Denied#0 [internal function]: Xibo\Controller\Playlist->libraryAssignForm('1216') #1 /var/www/cms/vendor/akrabat/rka-slim-controller/RKA/Slim.php(79): call_user_func_array(Array, Array) #2 [internal function]: RKA\Slim->RKA\{closure}('1216') #3 /var/www/cms/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array) #4 /var/www/cms/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch() #5 /var/www/cms/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call() #6 /var/www/cms/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call() #7 /var/www/cms/lib/Middleware/Actions.php(142): Slim\Middleware\MethodOverride->call() #8 /var/www/cms/lib/Middleware/Theme.php(35): Xibo\Middleware\Actions->call() #9 /var/www/cms/lib/Middleware/WebAuthentication.php(132): Xibo\Middleware\Theme->call() #10 /var/www/cms/lib/Middleware/CsrfGuard.php(62): Xibo\Middleware\WebAuthentication->call() #11 /var/www/cms/lib/Middleware/State.php(117): Xibo\Middleware\CsrfGuard->call() #12 /var/www/cms/lib/Middleware/Storage.php(47): Xibo\Middleware\State->call() #13 /var/www/cms/lib/Middleware/Xmr.php(36): Xibo\Middleware\Storage->call() #14 /var/www/cms/custom/XiboForLgMiddleware.php(223): Xibo\Middleware\Xmr->call() #15 /var/www/cms/vendor/slim/slim/Slim/Slim.php(1302): Xibo\Custom\XiboForLgMiddleware->call() #16 /var/www/cms/web/index.php(124): Slim\Slim->run() #17 {main}`

OP - https://community.xibo.org.uk/t/access-denied-in-layouts-created-from-template/11782/3

**Comment by dasgarner** [comment]
This is a problem with ownership rather than permissions - expected behaviour is that the owner of the new Layout, Regions, Playlists, Widgets is the user that created from the template. The permissions assigned should be according to the default permissions for new layouts configuration.
