### ISSUE TITLE
Layout Design region editor

### ISSUE THREAD

**Issue by jackson247** [xibosignage/xibo#131]
When designing the layout and I go into a region to edit it, the editor window is halfway off the screen. Not sure if it's my resolution or not.

Current resolutions: 1920 x 1200, 1600 x 900
Both of them show the same issue

![Image of Issue](http://i.imgur.com/eG7LOrc.png)

**Comment by dasgarner** [comment]
Did you upgrade from 1.6? I wonder if you have some files cached on your browser - try and Shift F5 to see if that helps.

**Comment by jackson247** [comment]
That seemed to work. I also switched to another workstation and that solved the issue. It was all client side.

**Comment by dasgarner** [comment]
Pleased you have it working!
