### ISSUE TITLE
DOCKER: Wrong information about DATABASE over manual.

### ISSUE THREAD

**Issue by lucasdiedrich** [xibosignage/xibo#1318]
Looking at [Docker Manual Page](https://xibo.org.uk/manual-tempel/en/install_docker_without_compose.html) we can look that it says that you can use **CMS_DATABASE** variables, which is obviously not working. It says that you can use it at **_cms-web_** container which doesn't exist also.

For now, i'm using compose and changing the MYSQL_DATABASE export variables over the xibosignage/xibo-cms container image.

**Comment by alexharrington** [comment]
Thanks for pointing that out.

We provide a compose file and config.env template for using a remote MySQL
server, which is correctly configured and commented. I'd suggest looking at
that as a basis for your needs until we can get that documentation updated.
