### ISSUE TITLE
Android: Modifying a layout while it's scheduled doesn't update on the client

### ISSUE THREAD

**Issue by nagyrobi** [xibosignage/xibo#132]
Using 1.7 CMS and Android clients. All registered and activated correctly.
- created a layout with a full screen video played in loop, and another one with a background picture and a clock
- scheduled them for 72 hours, 0 minutes and 0 seconds with the "Schedule Now" dropdown options to be played on two different clients
- waited for at least 10 minutes, the Android clients didn't do anything so I rebooted them
- this time they took the layout and started playing them.
- after a while I started modifying the layouts: added a text region to the video on the first one, and changed the background to a region slideshowing 3 pictures +the clock
- the updates didn't reach any of the clients (waited 15-20 minutes)
- restarting the Xibo app manually seems to fix it

Note that I do have a Display Setting Profile set for the Android clients, and there I've got Collect interval set to 1 minute.

**Comment by nagyrobi** [comment]
Might be related to https://github.com/xibosignage/xibo/issues/126#issuecomment-72501415

**Comment by dasgarner** [comment]
The player will only move on if the layout it is currently showing is no longer in the schedule, or naturally expires. By rebooting the box you are forcing the current layout to expire and hence the new one is loaded.

For Android specific issues it is better to contact Spring Signage (it will probably be me that answers anyway, but its important to keep a separation between the commercial player and the OSS project).

You won't get the same behaviour on windows if you have "Expire modified layouts" selected in your display profile - this is not yet supported on Android.
