### ISSUE TITLE
Windows player - webpages leaking memory 

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1322]
We had an issue when couple of webpages were open on a layout, the player/IE started leaking memory which lead to an error:
![image](https://user-images.githubusercontent.com/12148978/32319465-90c4d272-bfb2-11e7-931b-332bd3d80856.png)
In result of that layout/Xibo became unresponsive and had to my closed by 'End Task' in Windows Task Manager, I've tested it on my PC, the overall Memory usage was on about 30% - Xibo itself was using about 1.3GB of it.

Perhaps the following topic might be interesting to this case - https://stackoverflow.com/a/13352702

**Comment by dasgarner** [comment]
Unfortunately the linked code is for WPF rather than WinForms and I don't know if it is applicable or not - it certainly doesn't work out the box as it references things in the WPF stack, rather than the WinForms stack.

**Comment by buddyolpal** [comment]
We're having some issues with running content on a webpage for long periods. Seem to think it's a memory leak.

**Comment by dasgarner** [comment]
We're stuck trying to improve the memory management of the browser using our current implementation - so this will be addressed in the updated player when it is available.

If you have another example we can test with, then please do let us know.

**Comment by duhow** [comment]
I also have this error with multiple Grafana webbrowser elements, having
them with autorefresh 10 seconds and 10 minutes for the webbrowser element
/ full layer-slide.

**Comment by dasgarner** [comment]
Hopefully the edge browser has solved this - https://github.com/xibosignage/xibo-dotnetclient/issues/86
