### ISSUE TITLE
Stocks / Currencies - Yahoo API Broken

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1323]
Yahoo appear to have pulled their finance API which powers both the Stocks and Currencies module:

https://forums.yahoo.net/t5/Yahoo-Finance-help/Is-Yahoo-Finance-API-broken/td-p/250503/page/23

Calls to the webservice return no results currently.

![image](https://user-images.githubusercontent.com/10450518/32331063-d265886c-bfd9-11e7-9b9e-c79a3b526035.png)

Possible alternative data source here:
https://www.alphavantage.co

**Comment by laercionit** [comment]
Hello Alex,

I did test by the console and apparently this is ok, I think something has changed in the API:

[(https://developer.yahoo.com/yql/console/?q=show%20tables&env=store://datatables.org/alltableswithkeys#h=select+*+from+yahoo.finance.stocks+where+symbol%3D%22yhoo%22)]

[(https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20yahoo.finance.stocks%20where%20symbol%3D%22yhoo%22&diagnostics=true&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys)]

**Comment by dasgarner** [comment]
I don't see any way to keep the "Finance" module around after this change - we might need to retire that and then re-implement the Currencies and Stocks as their individual modules.

The finance module relies on direct YQL, which of course won't work anymore.

I'd suggest that we put a deprecation notice against the Finance module, saying that all Widgets should be migrated to use either Stocks or Currencies - and then retire it in 1.9
