### ISSUE TITLE
Ticker not scrolling

### ISSUE THREAD

**Issue by Pengu1** [xibosignage/xibo#133]
Running Xibo 1.7.0 (on Synology DSM 5.0). Xibo Player 1.7.4, Adobe Flash Player 16 ActiveX, Internet Explorer 11 on Windows 7 x64. 

I have created a layout with one ticker, and it is loaded by the player and displays either first or last item from RSS feed, depending if I select to take items from the start or the end of the feed, but no other items are shown, no scrolling or transition takes place. I am a Xibo newbie so maybe I've overlooked something essential, but I have tried so many different settings (including the initial "default" settings) that I have run out of ideas what to try. How do I get the ticker to scroll?

**Comment by jackson247** [comment]
I'm actually having the same issue. I can't get the text to move unless I use a Marquee effect.

**Comment by dasgarner** [comment]
@Pengu1 you have selected an effect on the Ticker Edit form?

@jackson247  Does the ticker effect apply in the CMS?

**Comment by Pengu1** [comment]
Missed the effect setting on the first page of the Ticker Edit form. Tried Scroll effect, but nothing happened, so switched to Marquee effect and, voila! Not so sure about the other effects, but for now I'm happy with Marquee left. Thanks for pointing out that setting, don't know why I did not see it.

**Comment by jackson247** [comment]
Same here. I cannot use anything else other than the Marquee effect on the ticker. If anything other than Marquee is selected, it will not scroll. I'm currently happy with Marquee scrolling, just wanted to point it out.

**Comment by dasgarner** [comment]
If you only have 1 single item then a lot of the effects may not do anything as they require two items to switch between.

I am fishing a little bit I know - but I can't think of anything else at the moment.

Can you try a simple test with a text item. Enter 2 paragraphs and select "Flip Horizontal" as the effect - does it work in the Layout Designer?

**Comment by jackson247** [comment]
Sorry for the wait. At the time I had 5 items from an RSS feed that I needed to scroll through on the ticker. The only way I got them to have any movement was to choose a Marquee effect. 

I have done what you asked with the text item and it does the same. It will show the one line of text but it will not move unless changed to a Marquee effect. All of those work as they are meant to.

**Comment by dasgarner** [comment]
Just a stab in the dark - can you try navigating to the Modules page and clicking "Verify All" in the top right?

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
