### ISSUE TITLE
Media Dashboard does not show media names

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1331]
As it is we have a 'Widget' column, which will show Widget name or if that's not provided in the widgetOptions then it will default to the widgetType instead, as quite often widget's do not have their custom names we end up with columns Widget and Type showing the same value.
In addition to that media names seems to be not passed correctly to widgetOption name parameter.

Especially for image and videos, we should ensure that it shows the media name instead of widget name there or create a new column to show that.

With that we get to the main issue, when we add a new image to a layout, it will have it's name in the timeline, which would suggest that the widget name should show that, but the actual name parameter in the widgetOptions is set to null (unless manually entered in the edit form) and the media Dashboard take the widget name from that: ie the following widget information:

```
"widgetId": 120,
        "playlistId": 54,
        "ownerId": 1,
        "type": "image",
        "duration": 10,
        "displayOrder": "3",
        "useDuration": "0",
        "calculatedDuration": "10",
        "widgetOptions": [
            {
                "widgetId": 120,
                "type": "attrib",
                "option": "align",
                "value": "center"
            },
            {
                "widgetId": 120,
                "type": "attrib",
                "option": "name",
                "value": null
            },
            {
                "widgetId": 120,
                "type": "attrib",
                "option": "scaleType",
                "value": "center"
            },
            {
                "widgetId": 120,
                "type": "attrib",
                "option": "valign",
                "value": "middle"
            }
        ],
        "mediaIds": [
            "55"
        ],
        "audio": [],
        "permissions": [],
        "tempId": null,
        "isNew": false,
        "name": "MyTestImage.jpg",
        "transition": "None / None"
    },

```

On the Media Dashboard in the Widget column we will see 'Image' as it defaults to widgetType when name parameter in the widgetOptions is null.

It should either take the name string outside of widgetOptions or more likely both name parameters should be the same, which is true when we change the widgetName on the Edit form, that will change the name parameter in widgetOptions and outside of it - perhaps the widgetOptions are not correctly set when we add a new widget to the timeline?

If it would set the name value in widgetOptions to the same value as name outside of that array then mediaDashboard should show that correctly.

**Comment by dasgarner** [comment]
The name widget option is an override and should only be non-null if the user has entered something in that field for the widget.
