### ISSUE TITLE
Audio added to widgets playback issues

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1333]
OP - https://community.xibo.org.uk/t/audio-in-timeline/12403/13

Audio assigned to widget issues:
It pretty much plays only on first run and after layouts reloads

Example scenario 1

let's say you have 2 regions
1st with an image 100s duration
2nd with two text items (or anything really) each with 10s duration and audio assigned to the first one

In this case we will hear audio only for the first 10s and then after layout reloads

Example scenario 2

1 region with 4 text items
1) text with 10s duration and audio assigned
2) text with 10s duration without audio
3) text with 10s duration and audio assigned
4) text with 10s duration without audio

Audio will play only for the first 10 seconds, 3rd text item will not have sound.

Additionally, audio assigned to widgets does not stay assigned to them after layout export/import
The file itself is imported to the new target CMS, but user needs to assign it to the widget manualy.

All of the above is ONLY regarding audio assigned to widgets, it does work fine when we use the Audio module.

**Comment by dasgarner** [comment]
is this windows player or android? or both

**Comment by PeterMis** [comment]
Windows only, I forgot to mention that, sorry!
