### ISSUE TITLE
Detect Language

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#135]
Nothing is in Portuguese, it is the language file, I can translate what you want.
If it is some setting I do not know where to start. rsrsr

Tested on two computers, one in Portuguese and one in English. But it keeps in English.

Default Language: pt_BR
Timezone: Sao Paulo
Date Format: d-m-Y H: i (I would - d-m-y HH:MM) Do not know if this formatting
Detect Language: Checked

**Comment by laercionit** [comment]
When you open the iphone, identified much of the language in Portuguese.
I made tests with IE, Chrome and Firefox. Only in English is displayed

**Comment by laercionit** [comment]
Dan, I remember you mentioning that would be keeping the launchpad.net for translation.

I can ask Leonidas that make any translation of terms for Portuguese.

**Comment by laercionit** [comment]
Dan, in launchpad.net, we are doing an update task forces the Portuguese language in Brazil. By downloading the pt_BR.mo file, and insert into the locate directory should appear my translations?

**Comment by dasgarner** [comment]
Hi,

Yes - Launchpad will be our place for translations and is already configured with the latest export of translation strings.

If you make some changes and then download pt_BR.mo and place in your `locale` folder - then those translations should also be applied in your CMS.

If you have "Detect Language" checked, Xibo will take the language preferences of your browser into consideration when showing the UI - if not, it will revert to the default.

There were some problems with this in the initial code, which have been patched in the latest xibo-cms repository.

Fully translating pt_BR would be a great contribution!

**Comment by laercionit** [comment]
Dan, I must download the developer version to test?

**Comment by dasgarner** [comment]
yes, please do - it makes sense to test with the latest bug fixes included.

**Comment by laercionit** [comment]
Dan, if you clear the Detect Language option, the system displays by default EN, same setting as default language pt_BR.

I managed only using the Detect Language option, with Iphone and appear in Portuguese, all other tests only in English.

I could not find the problem.

**Comment by dasgarner** [comment]
This is what I get when I untick detect language and fill in the default as pt_BR:

![image](https://cloud.githubusercontent.com/assets/10400067/6020372/315e5072-aba3-11e4-804e-330d1919471e.png)

You definitely have pt_BR in your language folder?

**Comment by laercionit** [comment]
Yes, the print shows the file in the directory.
The side menu works, but all internal areas the system does not. Only the
cell functioned as mentioned earlier.

[image: Imagem inline 1]

*Laercio Junior*
Cel./Pessoal: (21) 99162-7440
Email Pessoal: laercionit@gmail.com
MSN: laercionit@hotmail.com
Skype: laercionit



2015-02-03 10:50 GMT-02:00 Dan Garner <notifications@github.com>:

**Comment by dasgarner** [comment]
If one part of the system is translated and others are not, then this can only mean that those translations are not in the MO file.

The MO file contains all of the translations together, so it can't be half activated.

Looking in Launchpad, quite a few of the translations have been entered. When I download and pop that in my CMS much more of the UI is translated.

**Comment by laercionit** [comment]
Dan, please see carefully.
I'm saying that to do translations and put in the system, only accessing
the IOS can see the results in my language.

The system even informing the standard language and using any browser
without scoring detect language should appear all in Portuguese, as well as
when access by IOS.

**Comment by dasgarner** [comment]
Your default language looks like pt-BR instead of pt_BR ?

**Comment by laercionit** [comment]
To set default language to en_US
Do not select the option to detect language, the log appears the following return:

03/02/2015 15:13:23 CMS TranslationEngine InitLocal Creating new file streamer is locale / en_GB.mo



By checking the detect language, keeping the default language as en_US, we have the following Retono log:
03/02/2015 15:14:55 CMS TranslationEngine InitLocal Creating new file streamer is locale / pt-BR.mo


See the log is presenting en-GB and not en_US, as detected language and maintaining the standard language as secondary.



To make it work, I created a copy of the file to PT_BR.MO PT-BR.MO
In doing so the system worked with the option detect language, but still does not work with the default language option.




  // Firstly, it Sanitize
             $ requestedLanguage = str_replace ('-', '_', $ requestedLanguage);

**Comment by laercionit** [comment]
pt_BR, same name file pt_BR.mo

**Comment by laercionit** [comment]
After test some possibilities, i found at line 37 the follow code:

public static function InitLocale($language = NULL)
	{
        $localeDir	= 'locale';
        $default = ($language == NULL) ? Config::GetSetting('DEFAULT_LANGUAGE') : $language;

Maybe, for some reason i don't know why, the value of $language is not NULL and what we set as DEFAULT_LANGUAGE is ignored and it uses the $language at line 92:

// Are we still empty?
        if ($foundLanguage == '')
            $foundLanguage = $default;


We will have some problem if $requestedLanguage = "". I coudn't understand what make this line:

 // Try to get the local firstly from _REQUEST (post then get)
        $requestedLanguage = Kit::GetParam('lang', _REQUEST, _WORD, '');

**Comment by dasgarner** [comment]
I've re-written it to make it much easier to understand and follow.
