### ISSUE TITLE
Error running Library Tidy with datasets with spaces in column names

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1352]
`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS mediaId FROM dataset_9 UNION ALL SELECT Logos AS mediaId FROM dataset_16' at line 13#0 /var/www/cms/lib/Storage/PdoStorageService.php(232): PDOStatement;execute(Array)`

Appears to be a quoting issue here:
https://github.com/xibosignage/xibo-cms/blob/41b52ef49d1ec2233aa16de550f13e62c7083aff/lib/Controller/Maintenance.php#L259

OP: https://community.xibo.org.uk/t/upgrade-from-1-8-2-to-1-8-3-and-from-1-8-0-rc1-and-on-and-on/12598

**Comment by alexharrington** [comment]
There's potentially a part B to this too. See

https://community.xibo.org.uk/t/upgrade-from-1-8-2-to-1-8-3-and-from-1-8-0-rc1-and-on-and-on/12598/12?u=alex

Or may be a separate bug.

**Comment by dasgarner** [comment]
The second part of the bug is odd, as it doesn't make sense to have a Formula column with a DataType of "Library Image". However it is trivial to filter that out, so I have.
