### ISSUE TITLE
Manual: Apache reverse proxy example needs additional header

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1353]
OP: https://community.xibo.org.uk/t/client-talking-to-wrong-port/12634/4?u=alex

Example in the manual for an Apache reverse proxy (https://xibo.org.uk/manual-tempel/en/install_docker_linux.html) should pass the X-Forwarded-Proto header too.

**Comment by dasgarner** [comment]
Do we know what this should be?

**Comment by alexharrington** [comment]
SSLEngine On
ProxyPreserveHost On
RequestHeader set X-Forwarded-Proto "https"
