### ISSUE TITLE
Windows Player won't play Browser based Flash with CEF enabled

### ISSUE THREAD

**Issue by solutionssquad** [xibosignage/xibo#136]
Running the latest version with embedded Flash code inside the layout presents the 2 following errors:

Please upgrade your adobe flash player
Couldn't load plug-in.

**Comment by dkjain** [comment]
Guys, pls remember to always state your XIBO CMS & CLIENT environment details in your intial query i.e. OS, machine, CMS, client ver. etc. (could be in signature). This helps in resolving issues faster.

**Comment by dasgarner** [comment]
I've not tried this, so its a bit of an unknown... but I think you can get the binaries for the flash plugin as per [here](http://chromium.woolyss.com/#flash)

And then put them in your Xibo installation folder (under libs) as per [here](https://bitbucket.org/xilium/xilium.cefglue/issue/39/wpf-client-needs-to-support-flash-out-of)

**Comment by solutionssquad** [comment]
Indeed I should have specified.
This is happening on Windows 8 32 bit.
Server is running Version 1.7.0.
Player is running 1.7.0.

I did attempt to copy pepflashplayer32_16_0_0_296.dll from C:\windows\System32\Macromed\Flash to C:\Program Files\Xibo Player (there was no libs folder) however I'm still seeing the same issue.

This is occurring on 2 Windows 8 machines that I am using.

**Comment by dasgarner** [comment]
I'll mark this as a bug and see if I can work out how to include it... In the meantime I suppose reverting to IE works?

**Comment by solutionssquad** [comment]
I wish it did.
It was fine on 6.x but on the new system, having more than 3-4 flash items causes the rest to not display for some crazy reason.
Happens on 2 systems so I know it's not a resource issue.

**Comment by dasgarner** [comment]
odd... the flash display hasn't changed for years (and I mean years!).

Are you sure nothing else on the environment has changed in the mean time?

**Comment by solutionssquad** [comment]
Well, anything is possible but the only notable change was going from 1.6 to 1.7.

**Comment by solutionssquad** [comment]
Ok,

Here's what I'm finding:
It will play a flash file if it's being called as a media file, but it will not as a web page.
One example page I'm loading is "http://content.wdtinc.com/clients/wsvn/map.php?MAPID=13195&CLIENTID=20530"

I also tried running Xibo manually with the following but had no luck and no log file gets created:
"C:\Program Files (x86)\Xibo Player\XiboClient.exe" --log-file="cef.log" --ppapi-flash-path="C:\Program Files (x86)\Xibo Player\bin\pepflashplayer.dll"

**Comment by dasgarner** [comment]
Yeah, it won't be reading that command line parameter.

So just to be clear, if you take CEF entirely out of the picture (i.e. disable it), you see that the player will only open locally stored Flash files?

**Comment by solutionssquad** [comment]
If I take CEF out, it will play local flash and using the above URL.

**Comment by dasgarner** [comment]
OK, i've tagged this up as a Bug and changed the title. We will look at it when we can.

We will probably need a way to provide the flash plug-in (whether or not we can distribute that is another matter).

**Comment by solutionssquad** [comment]
I have no problem including the flash plugin manually (post install) if told how to, to get this working.

**Comment by dasgarner** [comment]
Sure - if it turns out that is easy I will let you know how to do it... I imagine we will have to load it in code rather than at start up.

**Comment by edwardborst** [comment]
I'm having the same issue. using version 1.7.5 (server/client).
Embeded flash in a website is not showing up. I found out that the flash plugin is loaded, but not showing.
In IE direct loading this page is showing the flash correctly. Is there a way around this?

**Comment by alexharrington** [comment]
CEF mode is experimental and may be removed. Please use Internet Explorer.
Alot of the memory handling issues have been fixed in recent releases.

**Comment by dasgarner** [comment]
CEF retired in 1.8
