### ISSUE TITLE
Twig form for generic files is missing

### ISSUE THREAD

**Issue by akatran** [xibosignage/xibo#1363]
Twig form for generic files is missing.

Error log shows:

> Unable to find template "genericfile-form-edit.twig" (looked into: /var/www/cms/modules, /var/www/cms/custom/IMWeather, /var/www/cms/views). Exception Type: Twig_Error_Loader

**Comment by alexharrington** [comment]
Thanks. We'll discuss on Community and log it as a bug once we have a reproduction :)
