### ISSUE TITLE
DataSets - .csv import with special characters / different language issues

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1367]
There seems to be an issue when importing a .csv file that contains special characters, some of the characters are converted to '?' or other symbols, Hebrew text is completely not imported - the rows that should contain the text in Hebrew are empty after import.

There is no problem to show the text with special characters in the dataSet, but it gets lost in the .csv import itself - probably due to character set not being correctly set/saved/recognized.

Import JSON, where we provide text with special characters in the json object, seems to correctly import the text to the dataSet via API.

We should make sure that .csv import supports those cases as well.

**Comment by dasgarner** [comment]
Do we have a sample CSV file that causes this problem?

**Comment by dasgarner** [comment]
The source CSV file provided by the OP (community post) is not UTF-8 encoded, which is the root cause of the problem. Nothing for us to fix here - but we will add some documentation to the manual.
