### ISSUE TITLE
Layout with Powerpoint downloads Powerpoint automatically on open

### ISSUE THREAD

**Issue by servicedelivery** [xibosignage/xibo#137]
Hi,

we use Xibo 1.7 and every time we open a layout (pressing Design), the containing Powerpoint gets automatically downloaded as index.php file. If i rename it to index.ppt you can see exactly the Powerpoint in the layout.
This download also happens if you double click in the layout area to change the layout content.

Thanks for your help.
Br,
Michael

**Comment by dkjain** [comment]
Guys, pls remember to always state your XIBO CMS & CLIENT environment details in your intial query i.e. OS, machine, CMS, client ver. etc. (could be in signature). This helps in resolving issues faster.

**Comment by servicedelivery** [comment]
Hi,

XIBO CMS 1.7 running on RHEL 6 on Apache Webserver 2.2.15 with PHP 5.3.3
The error happens in Chrome, IE, Firefox

**Comment by dkjain** [comment]
Please make sure that all modules are correctly installed. Starting CMS 1.7, this can be done within the CMS modules page at the top there is link "Verfiy All". Please click that and verify all that powerpoint module is correctly installed.

**Comment by servicedelivery** [comment]
I verified the modules without any problems but this error still occurs.
I also verified that xibo passes all environment checks without any issues.

Finally i found the problem: If preview enabled is set to true in the powerpoint module it will automatically download the file.
