### ISSUE TITLE
Xibo Android stopp working after some Houres... App Closed....

### ISSUE THREAD

**Issue by claudiobertsch** [xibosignage/xibo#1371]
We work with Android Xibo on an Amazon Fire TV stick. Version 1.6 worked fine. Since the update to 1.8, the APP relieves sporadically after several hours. We notice that because the app is closed. We restart the APP, then it works again. Unfortunately I see no error in the logfile.

**Comment by claudiobertsch** [comment]
We have two Amazon Fire TV Stick and two TVs. The problem is with both.

**Comment by dasgarner** [comment]
Please see https://xibo.org.uk/help#commercial for assistance with Xibo for Android (it is a commercial application)

**Comment by claudiobertsch** [comment]
OK! Sorry
