### ISSUE TITLE
Embedded HTML widget issues in 1.8.4

### ISSUE THREAD

**Issue by irltankman** [xibosignage/xibo#1379]
Our cloud hosted instance of Xibo was automatically updated to 1.8.4 at midnight last night. Since this occurred, 2 html embeds that were correctly filling the width and height of the available region have suddenly become scaled to a very small size. There is javascript as part of the embed that populates a HTML table as part of the EmbedInit call. Has there been changes in 1.8.4 that would be causing this?

**Comment by dasgarner** [comment]
None of the changes in 1.8.4 should have caused that - please can you email support@springsignage.com with your CMS details so that we can investigate for you?

**Comment by irltankman** [comment]
Will do

**Comment by dasgarner** [comment]
An issue has been found with rendering custom style sheets in embedded content - this is a regression from 1.8.3 and will need a patch - to follow.
