### ISSUE TITLE
CMS: PHP7 support

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#1382]
Get the CMS running on PHP7

**Comment by simhnna** [comment]
Is xibo compatible with php7?
The [manual](https://xibo.org.uk/manual/en/manual_install.html) still lists pretty old deps

**Comment by dasgarner** [comment]
Yes we are now compatible with PHP7 - I'll raise an issue to update the manual accordingly.

This issue is now closed, if you'd like to discuss further please open a topic on our community forum, thanks.
