### ISSUE TITLE
CMS selected columns don't persist long term

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1388]
If you go to the Displays page for example, and enable thumbnails column, then short term, that preference remains when you log out and in.

If however you log out for an extended period, that appears to be lost and the default returns.

OP: https://community.xibo.org.uk/t/column-visibility-enhancement-not-working/12956

**Comment by dasgarner** [comment]
I have set up a test CMS to try this out - I wonder if it might be a browser cache issue - i.e. perhaps the OP's browser cache wasn't refreshed on upgrade and therefore the settings aren't being written to the DB correctly.
