### ISSUE TITLE
Layering order not remembered in Region edit form

### ISSUE THREAD

**Issue by dkjain** [xibosignage/xibo#139]
Hi,

In Xibo CMS 1.7 (running on Windows 7) In Region option form, 'Layering text box does not show or rather forgets previously set z-index / layering number.

thanks
dkj

**Comment by dasgarner** [comment]
Hi,

I don't seem to be able to recreate the issue - can you provide a troubleshoot.txt file from the report fault page?

Thanks,
Dan

**Comment by dkjain** [comment]
Hi,

I tried recreating the issue in Firefox & Chrome but could not detect the problem this time. Currently ,this seems to be working. At the time of posting, may be under specific settings, conditions that seemed a problem/bug. Will report back if I am able to recreate the issue albeit with more specific details.

Issue status can be changed/removed.

thanks
dkj
