### ISSUE TITLE
Manual Position Web Page scaling doesn't work in Chrome

### ISSUE THREAD

**Issue by MarcelErdmann** [xibosignage/xibo#140]
Hi, I currently testing the new version 1.7
Client Windows 7 Version 1.7

I have a question about the appearance of Web pages

The best fit function has no effect on the presentation. Is this normal?

**Comment by dasgarner** [comment]
It may not, depending on the sizing of the webpage in question and the options you have provided. See the [manual](http://xibo.org.uk/manual/media_module_webpage.html) for more information.

**Comment by dasgarner** [comment]
IE looks to be working correctly, but Chrome doesn't as the `zoom` attribute is not interpreted on the `iframe`.

Will need to use a transform to scale the `iframe` correctly.

This means that Android and Windows players will need testing with this fix.
