### ISSUE TITLE
Implement callback feature

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1404]
There are use cases where communication between host and the web browser that player use would be beneficial for users.

As an example embedded html widget with embedded YouTube player, currently that widget has to have duration manually specified, in many cases we do not know how long the embedded video might be.

Which then leads to playback issues if the widget duration is longer or shorter than the embedded video, however if we could get back that information from the player and adjust the duration of the widget, we would then avoid such problems.

We will need to investigate how we can technically implement that and if it can be done in each supported player.

**Comment by dasgarner** [comment]
Moved: https://github.com/xibosignage/xibo-dotnetclient/issues/67
