### ISSUE TITLE
Multiple instances of 1.7.0 Client Running

### ISSUE THREAD

**Issue by wheels00000** [xibosignage/xibo#141]
So I've tried a clean install the issue keeps coming back, xibo client 1.7.0 keeps starting multiple instances of it's self and you get multiple layers running at a time. Anybody else having this problem or figure out a fix?

Windows 7 enterprise

**Comment by solutionssquad** [comment]
I'm seeing this on Windows 8 with 1.7.0

**Comment by xibo-de** [comment]
XiboClient.exe - 3 instances in Task Manager
Windows XP

**Comment by dasgarner** [comment]
With CEF enabled you will see many processes (one for each piece of content being rendered by the browser).

Without CEF enabled you should only ever see 2 processes.

**Comment by wheels00000** [comment]
It looks to be something with CEF disabling it fixed the problem.

**Comment by dasgarner** [comment]
#90.
