### ISSUE TITLE
SELinux label for volumes

### ISSUE THREAD

**Issue by ianharrier** [xibosignage/xibo#1418]
**Problem:** On Docker-based installations of Xibo (all versions), if SELinux is enabled on the Docker host (e.g. CentOS), the **cms-db** and **cms-web** containers have volume permission issues.

**Recommended solution:** Add [the SELinux label (i.e. `:z`)](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label) to all of the volume mounts in the `docker-compose.yml` file. I tried this on a clean install of CentOS 7 with Docker 1.12.6 and Docker Compose 1.18.0, and everything works as expected.

**Comment by alexharrington** [comment]
The manual page says specifically:

Use extreme caution with these options. Bind-mounting a system directory such as /home or /usr with the Z option renders your host machine inoperable and you may need to relabel the host machine files by hand.

I'm concerned that someone new to Docker might inadvertently hose their machine with our Docker file?

We can certainly mention the need to add a label for people running SELinux in the docs however.

**Comment by ianharrier** [comment]
> I'm concerned that someone new to Docker might inadvertently hose their machine with our Docker file?

My interpretation is that the Docker docs are warning against doing something like this: `-v /home:/some-container-path:z`, where the **root** of a system directory is mounted into a container. If Xibo users follow the official Xibo documentation, this should never be the case, as Xibo should be extracted to some directory other than the root of one of the system directories. For example, the official Xibo docs recommend `/opt/Xibo`.

VMware, for example, distributes Harbor (a Docker registry) using Docker Compose, and they include the SELinux label on [their docker-compose.yml file](https://github.com/vmware/harbor/blob/master/make/docker-compose.tpl), so I don't get the impression that it's too dangerous, if used correctly.

However, I definitely understand where you're coming from concerning admins who are new to Docker. If you're not comfortable adding the `:z` label, a mention about SELinux in the Xibo docs would be welcome! Thank you!

**Comment by alexharrington** [comment]
Thanks. I'll do a bit more reading and test it on a machine that doesn't use SELinux and see if that works too.

**Comment by alexharrington** [comment]
This was included in the standard docker files some time ago. Closing.
