### ISSUE TITLE
Best practice to split the display for 2 users

### ISSUE THREAD

**Issue by krajni** [xibosignage/xibo#142]
Hi Xibo-Team,

I would like to be able to split one Display for multiple Users. On the Windows Version we could just start 2 instances of Xibo and putting "half display sized" Layouts on the display but on the Android Version this is not possible. The easiest way would be to paste two Regions into one Layout and only enable one Side.This seams to work quite good, even if change the position from the region it doesn't cover the other region and it is not possible to delete the other Region neither. The remaining problem would be how to schedule the layouts. Is there a way to schedule only a region? It would be great to enable both Users to schedule their Media as they want for their Region.

Thanks in Advance

**Comment by krajni** [comment]
Just saw that there is now the possibility to use images in datasets. Maybe this would be a better approach. Is there an example for that?

**Comment by solutionssquad** [comment]
So far, I've found that it works when pointing to an external URL for the image.

**Comment by dasgarner** [comment]
I don't think we have an example for that at present, but basically as @solutionssquad said, it downloads an image from an external URL, saves it in a CMS cache and then transfers it to the players for playback.

Useful for pulling in external images, Google Maps Images API, etc.

@krajni regarding your initial question - you can't do what you want to do yet - scheduling inside regions. You can track the development of this feature here: #1
