### ISSUE TITLE
Text Editor cursor issues on newest Firefox

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1428]
We suspect this is something to do with the scaling we use to present the text inside the box at the correct size for the region (the red rectangle).

Firefox version 58.0.2

OP - https://community.xibo.org.uk/t/cursor-in-textbox-misbehaves-in-firefox/13370/7

**Comment by dasgarner** [comment]
Was this recreated on any particular size Layout? 58.0.2 Linux doesn't seem to have the issue as far as I can see.
