### ISSUE TITLE
Granular permissions

### ISSUE THREAD

**Issue by solutionssquad** [xibosignage/xibo#143]
This has plagued me for years on Xibo, so maybe we can finally fix it.
I need to give a user access to a specific item on a timeline, in a specific region of a layout.
The idea is to have a layout designed, and have the user locked out of most of it except a couple of timeline items such as pictures or text, so they can edit but not mess things up.

What I'm seeing is in order for them to even be able to get to edit the region, they need edit permissions on the layout and region.

This leads to them being able to mess things up.

This is happening on Windows 8 32 bit.
Server is running Version 1.7.0.
Player is running 1.7.0.

**Comment by dasgarner** [comment]
The only way to do this at the moment is to use the MediaManager dashboard - which lists out the regions and media they have permission to edit, without actually providing any way to move stuff around (i.e. resize).

**Comment by solutionssquad** [comment]
Ok, that's half way there! I can have them update their own images.
Is there a way to let them edit text?
I thought about using datasets but that wont allow any kind of formatting.

**Comment by dasgarner** [comment]
There shouldn't be anything preventing the media manager list showing text modules added to a layout (so that they can edit them directly from there)

**Comment by solutionssquad** [comment]
Dan,

Can you please elaborate on what you mean?
How do you or edit text modules in the media manager?

**Comment by dasgarner** [comment]
If your user has permission for a text module assigned to a region, then the edit form should be open-able from the media manager dashboard.

I'll admit I have not tried this recently.

What are you seeing? Are the text modules presented in the list?

**Comment by solutionssquad** [comment]
Are you referring to Library>Media?

If so, no it does not show up.
It only shows Flash, Font, Generic File, Image, Powerpoint and Video.

**Comment by dasgarner** [comment]
I mean the "dashboard" page for the user you have configured to use the media manager dashboard.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
