### ISSUE TITLE
display, sort/column view problem

### ISSUE THREAD

**Issue by sgiunchi** [xibosignage/xibo#1440]
Tried in 1.8.6.
Go in display, select to show the "Current Layout" column.
Select to sort by "Current Layout"
Hide "Current Layout".

Result: the display list is empty.
In debug: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'currentLayout' in 'order clause' Exception Type: PDOException

**Comment by dasgarner** [comment]
Current Layout column shouldn't be sortable as the value is computed rather than stored (its a transient value).
