### ISSUE TITLE
Users - Logged In status is inaccurate 

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1446]
On Users page we can enable 'Logged in?' column, which should show actual status of users in the CMS, however while it does correctly show users that are logged in, the users that aren't actually logged in often still have checkmark in this column which isn't correct.

It seems to be correctly updated when users specifically logout of the CMS, however if the user session ends the status is not updated to 0, hence it will show the user as still logged in on Users page.

**Comment by dasgarner** [comment]
So logged in / logged out only gets adjusted to X when the user manually uses the logout button, not when they timeout and leave of their own accord.

There are a bunch of options to consider:
 - set the flag during regular maintenance
 - set the flag during session expiry / garbage collection
 - make the column a computed column based on the current open sessions (i.e. get rid of it)

Please review the options and suggest the best course of action.

**Comment by PeterMis** [comment]
I guess it essentially puts that Logged in column on users page in a questionable position, do we actually need it at all? We will either have it show the same thing as sessions, hope for the best with updating flag on maintenance or we could completely remove it and just leave sessions as they are.

1) do we think it is really important to have it there updated every few minutes (maintenance run) and how would we determine if the user is logged in or not? How do we tell if the task should change the flag or not? Check sessions anyway? somehow tell if user was actually active?
It could be messy and redundant in my opinion.

2) 3) Similar results, but why have that in two places, if we base it on sessions anyway? As such my personal vote would go to 3 ie to get rid of that flag and have the computed column based on open sessions instead.

Clearing session in PHP can be slightly off at times, but at least we would have consistent output if we will base it on that and the login/logout actions update the active status of session just fine as well.

Obviously I can be convinced to other option if we think we need it and that it will be beneficial in a long run.

**Comment by dasgarner** [comment]
Great - my vote goes with option 3 as well. :makeitso:

Can I suggest that you handle modifying the column to be computed - I suggest we do this in the controller. We should also remove it from selection in the UserFactory, and remove it from the User Entity. It will be referenced in a few places - best to do a global find to see where, and remove it there too.

Once complete, I can handle removing the column from the Database in 1.8 and 2.0.
