### ISSUE TITLE
Always schedules should not be able to be set to repeat

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1447]
If a user selects "Always" as the dayparting type, then "Repeats" shouldn't allow them to set a repeat on that.

**Comment by dasgarner** [comment]
I suspect this is something to do with the logic in `setupScheduleForm` JavaScript function - it shows/hides options depending on what is selected on the form.

We moved the dayPart work into meta data when we added actual daypart records, so we most likely want to hide the repeats tab when `isAlways === 1`

**Comment by PeterMis** [comment]
I think it would be best to add class name for the `<li>` with Repeats tab in add/edit schedule twig pages and then access that via xibo-calendar.js to hide it completely when 'Always' is selected.

Seems to work well for me, but I'm open to suggestions if we think there is a more clever solution to this - commit below has the mentioned changes in it.

**Comment by dasgarner** [comment]
Apart from your [stray space](https://github.com/PeterMis/xibo-cms/commit/f97e2e6d4b485fc08b9b14a7ed863563c230d96c#diff-1c1d85d3b8b60c12dc9d925d7833a555R503) I think this is a great solution to the problem. Happy for that to go in.

**Comment by PeterMis** [comment]
Whoops, fixed here https://github.com/PeterMis/xibo-cms/commit/7575b5cc2f3c1a09121648974ac47d8cb5cb1e57 
I shall close this issue and open PR with my changes then
