### ISSUE TITLE
Ticker style thumbnails broken when using a CMS in a subdirectory

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1454]
![image](https://user-images.githubusercontent.com/10450518/37529213-7245dbbc-292e-11e8-8cca-e65b04c8442c.png)

Broken image URLs are like:
http://www.xxxxxxx.com/morenol/morenol/playlist/widget/form/templateimage/ticker/media-rss-with-title

whereas they probably should be:
http://www.xxxxxxx.com/morenol/playlist/widget/form/templateimage/ticker/media-rss-with-title

OP: https://community.xibo.org.uk/t/xibo-cms-1-8-7-missing-thumbnails-at-edit-ticker/13704

**Comment by dasgarner** [comment]
The API returns the image URL with the alias name at the front, but we (for some reason) strip the leading `/` (there is a comment saying we do this because the control is expecting a relative URL).

**Comment by dasgarner** [comment]
I think the attached commit will fix it, but would like to test on an aliased site first.
