### ISSUE TITLE
Schedule - Changes to recurring events do not invalidate display cache properly

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1457]
Create an event with recurrence schedule it to the player
Open schedule.xml / look at the status window
Make a change to the scheduled event (change end/start time)
Player will not pick up this change unless user clears the Displays cache.

The issue seems to only affect recurring events, changes made to non recurring events are correctly pushed and updated on the player.

**Comment by dasgarner** [comment]
I'm not sure if the above commit fixes the issue or whether it is more involved. Can you please pull and retest with your failing example?

**Comment by xibo-de** [comment]
Have the new Schedule.php downloaded and copied into the appropriate directory. Now, when changing the time in a repeating event, XMR will fire immediately (visible in the debug window). The player makes the change immediately. It seems like it will work correctly now. I did not test without a working XMR.

Best regards

Hubert
