### ISSUE TITLE
Displays page - Refresh button does not refresh screenshot column

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1458]
Currently the Refresh button is not correctly updating the screenshot thumbnail column, user needs to manually refresh the Displays page in the browser to see new screenshot.

The thumbnail seems to be cached and refresh button is not able to clear that cache at the moment.

We should investigate it further and see if we can improve that process.

OP - https://community.xibo.org.uk/t/xibo-cms-1-8-7-custom-and-xibo-co-uk-refresh-button-on-the-display-page-is-not-working-properly/13783

**Comment by dasgarner** [comment]
Try outputting the following cache control headers with the screenShot request (`\Xibo\Controller\Display::screenShot`)

```
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
```
