### ISSUE TITLE
Turkish translation for Statistics

### ISSUE THREAD

**Issue by kxibo** [xibosignage/xibo#1469]
Dashboard -> More Statistics 

Translation to Turkish does not occur for the Bandwidth section From Date and To Date fields.

Issue does not occur for the Time Disconnected section.

![image](https://user-images.githubusercontent.com/38042684/38254869-3fa714f0-3752-11e8-940f-0688bce3c7d6.png)

**Comment by PeterMis** [comment]
Commit - https://github.com/PeterMis/xibo-cms/commit/1877164d59988a7cb3e2630ce3212ceb55615217
