### ISSUE TITLE
Delays in selection of schedule

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#147]
I have over 300 displays, to open the option to select the displays or groups, I feel great slowness to select the item you and the item was marked.

![image](https://cloud.githubusercontent.com/assets/325662/6033074/23b70112-abf8-11e4-8835-832e8e6400d5.png)

**Comment by dasgarner** [comment]
FYI, that is this library: http://silviomoreto.github.io/bootstrap-select/

I guess most of your users wont have anything like that number? As they will see only a subset (the ones they have permissions for?)

**Comment by laercionit** [comment]
Hello Dan,

Yes, my users can see a small fraction of the total. But the problem I mentioned occurs even with users who have just two displays on your list. The slowness is not only the volume of data that the usario have access, I think is related to the volume of data in the database.

**Comment by dasgarner** [comment]
Really? The SQL that populates that list is loaded when the page loads, not when the list is clicked... when do you see the slowness?

**Comment by laercionit** [comment]
Dan, I made a short video showing what I see to help in the presentation of the problem.

https://www.youtube.com/watch?v=ABj-p9lw5Po&feature=youtu.be&hd=1

**Comment by dasgarner** [comment]
I see what you mean - I've made some changes to the calendar library that will hopefully assist with the issue.

Root Cause = each selection waits for the return from the DB
