### ISSUE TITLE
Member ORDER User Group

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#148]
By accessing the user group to manage members, the screen is presenting without alphabetical and users who are retired order.
On ordering think is simple and logical, but on users retirees listed, I believe it is not interesting, but it can be a matter of standard system concept.

![image](https://cloud.githubusercontent.com/assets/325662/6033860/68bd61fc-ac02-11e4-8863-9ec7455724ed.png)

**Comment by dasgarner** [comment]
Enhanced as requested. Retired users are not deleted, but also wont be shown.
