### ISSUE TITLE
Fonts: permissions cause issues with caching

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#1491]
Fonts with different user permissions cause problems with the font cache such that when a user uploads a new font, not all other users (or even all super admins) see it.

The only way (we think) to improve this is to drop the entire font cache for every user, each time a change it made.

It would also be good to only drop the display cache if the final css has changed.

**Comment by dasgarner** [comment]
It also seems unlike that font delete has the desired effect (i.e. it will still be in the CSS cache)

**Comment by Plikster1410** [comment]
Hi,
how are we supposed to "drop the entire font cache for every user" please?
Grtz

**Comment by dasgarner** [comment]
this is not something that can be done easily without a code fix from us.

If you're using docker you could delete the `library/cache` folder
