### ISSUE TITLE
Windows player - cannot access disposed object WebBrowser

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1494]
Consider layout with 3 regions, one widget in each one of them.

Say image, text and Ticker.

If we change the region position/resize region it will sometimes cause some of the regions to not be rendered at all until layout reloads.
The error in log that we can see about this is as follows:

``` Cannot dispose of web browser. E = Cannot access a disposed object.Object name: 'WebBrowser'. ```

It does not seem to happen if 'Expire modified layouts' is disabled, as then there is very slim chance of the race condition between layout being force expired and it being created.

We did receive a report that it can also happen with `Expire modified layouts` disabled.

Other players does not seem to be affected.

**Comment by dasgarner** [comment]
Dup? https://github.com/xibosignage/xibo/issues/1505
