### ISSUE TITLE
Remote datasets - truncate conditions needs to be adjusted 

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1497]
With current conditions we have there, it is very easy to ensure that dataSet data will never be truncated.

We're comparing the task `runTime` (localDate when the task is running) against `getNextClearTime()` which is `lastSync + clearRate`. 

It's not hard to ensure that runTime will never be `>` than `getNextClearTime()`, as a result truncate will never happen.

We need to investigate further and adjust the conditions to ensure that it works as expected.

**Comment by dasgarner** [comment]
This can only be solved with a DB change to store `lastClear` date on the DataSet. We can then compare `lastClear` with `clearRate` and accurately truncate regardless of the `lastSync` value.
