### ISSUE TITLE
Xibo Player 1.7 failed to connect to server

### ISSUE THREAD

**Issue by MysticShadowSong** [xibosignage/xibo#150]
Hello,

I have installed Xibo 1.7 but when I tried to connect the Player to the server, I get an error "The request failed with error message : An upgrade is pending. Visit http://192.168.X.X/xmds.php" and when I go to this URL, I get the same message. 
I have installed the latest CMS and Player so I don't understand why I get this message.
What can I do to solve this problem ?  

Thanks

**Comment by dasgarner** [comment]
You mat have installed over an old installation? In your CMS root folder there will be a file called `upgrade.php` - you will need to remove it.

**Comment by MysticShadowSong** [comment]
Many thanks, I deleted the file and now it works fine.
Thanks for your help and quick answer !

**Comment by dasgarner** [comment]
Welcome :smile:
