### ISSUE TITLE
xibo.css .Modal-dialog fixed width breaks layouts on mobiles

### ISSUE THREAD

**Issue by Swwils** [xibosignage/xibo#1500]
Sometimes I find myself needing to check schedules from a mobile device - dialogs spill past these devices widths, meaning that you have to use "desktop view" mode and scale down the display to do some actions which is a little tedious.

It seems a simple CSS fix will allow mobile devices to use bootstraps flexible widths to display everything property.

It seems its this CSS line in xibo.css is setting a static width here:

.modal-dialog {
    width: 900px; 
}

Can this be removed without breaking UI?

**Comment by Swwils** [comment]
It looks like this already exists for some viewports in bootstrap:

```
@media (min-width: 768px)
.modal-dialog {
    width: 600px;
    margin: 30px auto;
}
```

Maybe just a media wrap to improve UI then roll further changes in the upcoming UI overhaul?

**Comment by dasgarner** [comment]
Yeah, those existing media queries are there to give it widths for desktop (as I understand it). We just wanted more width - so a media wrap makes sense to me too.

Thanks!
