### ISSUE TITLE
Windows player -  Maximum concurrent downloads can be set to 0 or negative value

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1503]
Currently it is possible to set Maximum concurrent downloads in Windows Display profile or by directly editing Windows player config file to 0 or negative value, which will result in the following error when starting the player:
![image](https://user-images.githubusercontent.com/12148978/39570384-15b6d2ae-4ec0-11e8-89d0-bfb55a57d396.png)

We should protect against such values in this setting in the Windows display profile and also in the player code.

**Comment by dasgarner** [comment]
Done in the player

**Comment by PeterMis** [comment]
Done in the CMS - unless we think there is a better way to achieve that.
