### ISSUE TITLE
This webpage has a redirect loop

### ISSUE THREAD

**Issue by kaiserkreb** [xibosignage/xibo#153]
Hi there, I'm upgrading my CMS from 1.4.2 to 1.7. I've been following along with the upgrade process, and have just finished creating the database clone, copied the contents of the zip file (not overtop of previous stuff) into my 'htdocs' folder, and then replaced the settings file with the new database info. Now when I try to go to localhost/xibo it spins it's tires for a while and then says "This webpage has a redirect loop", and that's about where I'm stuck.
I've tried messing around with different database clones to see if I futzed up that process but it seems to be doing what it's supposed to so I'm at a bit of a roadblock.
 I'm pretty sure I've followed along with the instructions precisely, my apologies if I've missed something somewhere. 

Should I be attempting to upgrade to an intermediate version and then leaping to 1.7? I read another post on here that said that likely wouldn't be necessary so I haven't attempted it yet. 

Thanks for any help you can provide.

**Comment by dkjain** [comment]
You can try by first upgrading to 1.6 cause there have been DB schema changes from 1.4 to 1.6 and again from 1.6 to 1.7 so the upgrade process for 1.7 would assume a 1.6 db schema (if I am correct).

**Comment by dasgarner** [comment]
You should be able to upgrade all the way from 1.0 to 1.7 if you so desire.

Which URL are you hitting the redirect loop on? `install.php` ?

**Comment by kaiserkreb** [comment]
I'm not entirely sure and I'm not in the office to check right now, but this happens just when you go to 'localhost/xibo' in the browser after updating the server files in htdocs and changing the settings file to point to my cloned database.

**Comment by alexharrington** [comment]
Try clearing your web browser cache and then logging back in to Xibo. It should then prompt you to upgrade

**Comment by kaiserkreb** [comment]
I believe I tried that already but I'm going to run through the whole process again and see if I didn't miss a step somewhere.

**Comment by dasgarner** [comment]
It might be a problem with the information available in an early database like 1.4, which is preventing the up grader from actually starting.

If I get time I will try and run a test for you here.

**Comment by kaiserkreb** [comment]
OK, I grabbed the 1.60 server files and it seems to be happy with those. I'll run through this upgrade process and see if I can do 1.7 afterwards.

**Comment by kaiserkreb** [comment]
That seems to have worked. Sorry to bug you guys, I'm sure you're busy!

**Comment by dasgarner** [comment]
No problem - at least you have a workaround.
