### ISSUE TITLE
Weather: Template 1 references cloudy.jpg which does not exist

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#1538]
I don't think template 1 should have a background image - it is intended to be transparent, but the following CSS has made it into the template:

```
background-image: url('..\/cloudy.jpg');
```

We should remove it.

**Comment by PeterMis** [comment]
Template 8 also has a link to that file, as this file does not exist and Template 8 that actually uses background images have them set later in the template with correct file names.

I believe that link to cloudy.jpg can be removed from this template as well.

That's done in the commit below.
