### ISSUE TITLE
1.7 installation problem due to settings.php

### ISSUE THREAD

**Issue by spunner** [xibosignage/xibo#154]
I am trying to install 1.7 and have check marks on everything except "Write access required for settings.php and install.php"  There is no settings.php (assuming it should be in the /var/www/xibo) with the install.php.  I have chmod 777 install.php and the xibo directory.  Owner and group are apache. If I create a settings.php file and set it to 777, I get a message that xibo is already installed.  Guessing the install needs to generate the file, but isn't/can't for some reason.   Any ideas would be helpful.

**Comment by jackson247** [comment]
Is this a fresh install?

**Comment by spunner** [comment]
Yes.  Fresh install.  Have heard good things about Xibo and wanted to try it for myself.

**Comment by dasgarner** [comment]
The install needs to create that file, which means the user your web server is running under needs to be able to create files in the root folder of your CMS installation.

The exact test is:

``` php
return (is_writable("install.php") && (is_writable("settings.php")) || is_writable("."));
```

**Comment by spunner** [comment]
Don't understand what the code above does.  Am I supposed to type that in somewhere?  I made a test.php with that code and ran it from the site - does nothing.  Typed it into terminal and it returns - bash: syntax error near unexpected token `is_writable'

owner of xibo (recursive) is apache
group of xibo (recursive) is apache
xibo dir is set to 777
install.php is set to 777
settings.php does not exist.  Cannot make one and give 777 or it bypass install.

Thanks!

**Comment by alexharrington** [comment]
Your webserver cannot write a settings.php file. Either the permissions you're telling us are in place aren't or there is something else preventing your server from writing that file. Once your webserver can write there then the installation will proceed correctly.

**Comment by spunner** [comment]
had to turn off selinux.   Thanks.

**Comment by andrearos** [comment]
I've the same problem on IIS 8, Windows 2012 server, PHP 5.6, also with RW permissions to everyone.
The solution is to bypass the check in:
\config\config.class.php (3 hits)
	Line 633: 	  return (is_writable("install.php") && (is_writable("settings.php")) || is_writable("."));

I've substituted this line with:
return true;

the installation process created correctly the settings.php file.

**Comment by alexharrington** [comment]
On IIS you need to grant additional permissions for the webserver to create files. There's no need to modify the source code.

**Comment by FETommy** [comment]
Adding the local user IUSR with full control to the xibo folder worked for me on IIS Server 2008 R2

**Comment by gusgs05** [comment]
Thanks FETommy .
My problem is solved it

IIS 7.5 + PHP 5.5

**Comment by robert-scheck** [comment]
Disabling SELinux is a bad idea from the security perspective, instead it would be better to just configure SELinux properly:

    yum install /usr/sbin/semanage
    semanage fcontext -a -f a -t httpd_sys_rw_content_t '/var/www/html(/.*)?'
    restorecon -R /var/www/html/

Above assumes that Xibo is installed somewhere under `/var/www/html/` path.

**Comment by alexharrington** [comment]
This is a closed issue. @robert-scheck if you wanted to contribute an appropriate amendment to the install guide via a pull request that would be fab.

**Comment by robert-scheck** [comment]
@alexharrington, I am aware that this is a closed issue, however having the correct solution next to a workaround makes IMHO sense through (because if you search for the issue, you will find this ticket). Given contributing seems to require signing a CLA, I am not going to fill a pull request, sorry. Nevertheless, feel free to copy the three commands to the install guide/documentation.

**Comment by alexharrington** [comment]
It looks to me like your rules allow writing under /var/www/html however while that's necessary to generate settings.php, our recommended configuration would also require you to be able to write to whatever library directory you've chosen. As the projects officially supported platforms don't use SELinux I don't have access to test a suitable rule set for inclusion in the installation guide. If someone would like to contribute a tested working config via PR then we'll happily include it.
