### ISSUE TITLE
Formatting the date in Regional parameter cause a bug in the schedule process with custom hours.

### ISSUE THREAD

**Issue by michaelampr** [xibosignage/xibo#1541]
### Xibo Version
CMS 1.8.9

### Php Version
5.6.36

### Bug
1. Change the date format in **Parameters > Regional** from, for instance _Y-m-d H:i_ to _H:i d-m-Y_ (French format)
2. Try to schedule a new event using "custom" hours instead of "always".
Result: the event won't register. Works only when you select "always".

**Comment by dasgarner** [comment]
Thank you for your bug submission, i've recreated and fixed the issue for release in 1.8.10 (see the above commit if you'd like to attempt a patch).

The root cause is having the time portion on the string ahead of the date portion.
