### ISSUE TITLE
'Use the Display Location' on Forcast IO module

### ISSUE THREAD

**Issue by jackson247** [xibosignage/xibo#155]
When I select "Use the Display Location" from inside the module it does not display the correct weather information. I have gone in and set the long and lat of the display I am testing on. When I enter in the long and lat inside the module I get the correct results. Not sure if this is an error on my behalf.

**Comment by alexharrington** [comment]
You need to ensure you set LAT/LONG on the display record for each display. The preview shown in the CMS uses the default lat/long which is set in the server settings.
