### ISSUE TITLE
/playlist/form/library/assign/?_=1529962646832 Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by johndiego** [xibosignage/xibo#1555]
Hi guys, I 'm with one problem!
how i can solved this!
![deepinscreenshot_20180625183753](https://user-images.githubusercontent.com/18476845/41877313-2eb006e8-78a7-11e8-8efe-54aee5caec0e.png)
after cliked modal this close modal and show error console

/playlist/form/library/assign/?_=1529962646832 Failed to load resource: the server responded with a status of 404 (Not Found)
my docker composer this is same example in documentation.
sorry my bad 
![deepinscreenshot_20180625184424](https://user-images.githubusercontent.com/18476845/41877489-d210414a-78a7-11e8-8efa-7a218d6e73ad.png)
 english

**Comment by alexharrington** [comment]
Thanks for your message. The project uses Github Issues for verified bugs only. Please post your support request over on our Community site and we can try and help you there. Be sure to give as much information about your setup as possible - for example you don't give the CMS version you're using, or show your docker-compose files. Community is here: https://community.xibo.org.uk
