### ISSUE TITLE
CMS: Flash object obscures menu/edit forms when editing layouts in Xibo 1.7.0

### ISSUE THREAD

**Issue by Pengu1** [xibosignage/xibo#156]
When editing any layout where I have added a Flash object, it partially obscures (appears in front of) edit forms and/or the options menu on the left, making it virtually impossible to edit any settings for either the Flash object itself or any other objects on layout. It behaves the same way in both IE 11 and Firefox 35.0.1. My workaround so far is to add the Flash object as the last object, or temporarily remove it from the layout if I want to make changes.

In the example below I'm trying to edit the properties of a ticker in the same layout as the Flash object.

![flash on xibo](https://cloud.githubusercontent.com/assets/10815023/6051472/a6819050-acc8-11e4-9869-ceca2f6df298.PNG)

**Comment by solutionssquad** [comment]
I can report having the same issue.. and workaround.

**Comment by dasgarner** [comment]
You can disable previewing for Flash on the Modules page (as another workaround)

**Comment by solutionssquad** [comment]
How?

**Comment by Pengu1** [comment]
OK, thanks for the tip. Learning new things all the time. But still it's a
workaround, not a solution.

**Comment by dasgarner** [comment]
Quite right - hence the Bug Label :smile:
