### ISSUE TITLE
Missing Translation Ticker

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#157]
I am working with a very detailed translation into Portuguese of Brazil

Identified that the following items have no reference for translation.
Could please include?

Image overlaid with the Feed Content on the Left
Image overlaid with the Title
Prominent title with description and name separator
Title Only
Format
Right to Left (RTL)
Left to Right (LRT)

![image](https://cloud.githubusercontent.com/assets/325662/6053134/a55823f2-acc2-11e4-8fa4-fb4ffcb1a7f6.png)

![image](https://cloud.githubusercontent.com/assets/325662/6053202/a3127ce0-acc3-11e4-8bb7-ef315060a209.png)

**Comment by dasgarner** [comment]
All of those translations are already in there as it happens...

Have you considered trying the below procedure:

 1. Request a download of the pt_BR translation from Launchpad.
 2. Download it when you receive the email
 3. Download and Install [PoEdit](http://poedit.net/)
 4. Open the PO file you downloaded in POEdit
 5. Make the translations
 6. Upload the file to Launchpad (making sure you are on the pt_BR language)

**Comment by laercionit** [comment]
OK!  Closed.
