### ISSUE TITLE
Doubt - Wake-On-LAN

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#158]
This option works in client android?
This option only works if the CMS is on the same network of displays?

**Comment by alexharrington** [comment]
If your Android device were to support Wake on Lan then there's no reason it wouldn't work. I'm not aware of any Android device that does however (although one running Android x86 on effectively PC hardware would). Wake on Lan can be forwarded across subnets but yes it does generally assume that the client and server are on the same LAN.
