### ISSUE TITLE
Incorrect time zones when using calendar widget

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#1586]
CMS Version: 1.8.10

Description: Calendar widget using a different time zone than UTC (in this instance, CST), time is not correct. The date is 1 hour behind the calendar date in the ical feed.

**Comment by dasgarner** [comment]
Our timezone handling in `parseFeed` must be off - perhaps we shouldn't convert to the unixtimestamp in `substituteForEvent` ?
