### ISSUE TITLE
Xibo Player 1.7 is looking new content after about 15 minutes 

### ISSUE THREAD

**Issue by atiar-cse** [xibosignage/xibo#160]
Hi,

After updated the layout, Xibo Player is refreshing the new content after about 15 minutes. Previously there was a option to set "looking for new content" as minimum 30 seconds & it works fine. 
But in Xibo Player 1.7 i don't see any option like that to set the interval for new content.
For 1.7, Is there any option to refresh the new content instantly when updated? Or after 30 seconds?

Then it would be very great to me....

**Comment by alexharrington** [comment]
In 1.7 the settings for the clients are all in the CMS. You need to create a display profile and assign it to that display. You can then set the option for expire modified layouts.

**Comment by atiar-cse** [comment]
Thanks!
