### ISSUE TITLE
Export Database Backup not working

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#1603]
CMS Version: 1.8.10
Notes: Docker Install, Windows 10.

Issue: When selecting Export from the Settings menu, 404 not found error: 'Not found. The requested URL /index.php was not found on this server.

**Comment by dasgarner** [comment]
ZipArchive::addFile(): Invalid or uninitialized Zip object Exception Type: ErrorException

**Comment by alexharrington** [comment]
https://github.com/xibosignage/xibo-cms/blob/release18/lib/Controller/Maintenance.php#L394

Needs a further check for non-empty file. As it stands, that will always pass the even if mysqldump fails an empty file will be created.
