### ISSUE TITLE
Windows Player: Screen doesn't scale after display resolution increase

### ISSUE THREAD

**Issue by Techno11** [xibosignage/xibo#1604]
On the windows .NET client, the player does not scale properly after the resolution changes. For instance, when we turn off one of our displays at the end of the day, windows loses the resolution for the TV which our kiosk is connected to. In this case, Xibo scales to the smaller screen just fine. However, when we turn the TV back on the next day, Xibo is scrunched up in the corner of the screen, having not scaled back up to the 1080p that our TV is.
![example](https://user-images.githubusercontent.com/15097541/44045417-6e627d64-9ef6-11e8-9dcd-4c232823523e.jpeg)

**Comment by dasgarner** [comment]
Please can you discuss this on our community forum before creating an issue for it - we use GitHub for verified bugs only.

Background: #1527 
OP: https://community.xibo.org.uk/t/screen-shrinks-to-the-top-left-of-the-screen-windows-player/8638/9
