### ISSUE TITLE
Screenshots don't support Multi-Screen setups

### ISSUE THREAD

**Issue by aurorasmiles** [xibosignage/xibo#1606]
One of our clients uses multiple screens as one big screen. If I request a screenshot from this client, I only get a screenshot from one screen (the "first" screen in Windows) instead of a screenshot showing the complete layout.
Client version: 
windows 1.8.10-132
Server version:
1.8.9

**Comment by PeterMis** [comment]
Please can you discuss this on our community forum before creating an issue for it - https://community.xibo.org.uk/c/support

We use GitHub for verified bugs only, if we confirm that it is indeed a bug, then I will be happy to create an issue about it.
