### ISSUE TITLE
DataSets - library Image column can cause the row to become inaccessible 

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1608]
Scenario:

Create a dataSet, add library image column to it,
Add an image to the lirabry image column,
Replace and remove old revision of that image in Library (or just remove the image from library)
Try to edit the row in dataset.

It will show ` Cannot find media `, which is true if we remove old revision while replacing the media, however we should aim to handle it in a better way.

Either clear the image assignment in the dataSet if the image was removed or replaced (with delete old revision) or to update the image in the dataSet accordingly.

**Comment by dasgarner** [comment]
We can't fully fix in this release - the above fix allows the edit form to open, a full fix will be supplied in https://github.com/xibosignage/xibo/issues/1634
