### ISSUE TITLE
Investigate Mcrypt

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1615]
PHP 7.1 deprecates and PHP 7.2 removes the mcrypt module, as it's no longer maintained.

Investigate whether we still need mcrypt, or whether we can reasonably replace it with something else? I believe we used to use it for password hashing, but no longer do (using PHP's own salt/hash mechanism instead) and perhaps it's there for legacy only now?

**Comment by dasgarner** [comment]
The mcrypt extension is used by Slim 2, although is suggested rather than required.

Password checking (as you say) uses mcrypt only if the password has not yet been upgraded to the latest method. Removing it would mean that a user must go through the current release to get to the next.

**Comment by alexharrington** [comment]
So we could make it suggested but not required (with that caveat)?
