### ISSUE TITLE
Cache problem. Layout list, preview image (thumbnail) not updating

### ISSUE THREAD

**Issue by avanceja** [xibosignage/xibo#1616]
![01](https://user-images.githubusercontent.com/23653038/44445898-1b5c6780-a5e3-11e8-8bc7-9138aa727aa4.jpg)

In the Layout list if you copy a layout and then change its background image, it will not update until you clean the cache. It must be a way to force it to update like it happens on the design layout (instant update or ajax). But if you click on it, it will show the updated images (se "02" in the image).

**Comment by dasgarner** [comment]
Thank you for your bug report, we will take a look at it for the next release.

**Comment by dasgarner** [comment]
@PeterMis - all we need to do here is to include the `backgroundImageId` as a parameter to the request, so that when that changes it is a new unique request.
