### ISSUE TITLE
Calendar - not always returns correct items from the ics

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#1626]
With the previous fix, we've fixed the substitution timezones where there is no TZID specified for the event itself.

However the `eventsFromInterval` is returning items without the calendar timezone and so if TZID is also not specified, then in CMS it will show that no data was returned from the source, even though there are events that should be returned - it is testing it against UTC times from the ics not including the calendar timezone.

The fix to the timezones in substitutions also broke the translations, if user chooses to have day/month names in date format.

**Comment by dasgarner** [comment]
It also seems that if a fee has the DATE:VALUE syntax in any of its date fields, it fails to parse a date and crashes out.
