### ISSUE TITLE
Api displayprofile Get return empty config Array  xibo docker xibo-docker-1.8.10

### ISSUE THREAD

**Issue by firestorms321** [xibosignage/xibo#1627]
As long as a display profile was not saved in edit windows on the cms using the save button in the cms the config array is returned empty (did not try a save using the api)

this bug include the default profile installed by default as well as newly created one if you does not press save on the edit windows that apear after the creation
 
ex: {
		"displayProfileId": 3,
		"name": "Android",
		"type": "android",
		"config": [],
		"isDefault": "1",
		"userId": 1,
		"commands": []
	},

**Comment by dasgarner** [comment]
That's right - the profile only contains settings that have been overridden from the defaults - whats your use case please?

**Comment by firestorms321** [comment]
We will be using a custom module based on the embeded one that will Dynamicaly generate video link on each player

This will in the proof play mask what video is playing on each player so to keep a log of this on our side to do se we mainly need the display collection interval on each player to know the period where the concerned video has played

Not receving the config info even for unchanged setting can be problematic since we cannot guarantee that your default value will stay the same or is the same for each profile type

**Comment by PeterMis** [comment]
We've decided to change the way the config and config default is returned in the response, by introducing an `embed` parameter.

In short that's how it will work in 1.8.12:

If you just call the GET /displayprofile ie without `embed`
the config, configDefault and commands will not be loaded in the response

If you call GET `/displayprofile?embed=config`, then the current config will be loaded and added to the response, similarly with you add embed=commands, the commands saved for the profile will be loaded and added to the response. It is "," separated so you can call for example `/displayprofile?embed=config,commands` to add both config and commands to the response.

If you call GET `/displayprofile?embed=configWithDefault`, that will load the current config and the configDefault data (ie the default config for that display profile type).

I also ensured that the display profile config is populated with the default values when you add the display profile - hence it should return config data when you call the GET `displayprofile?embed=config` even if that display wasn't edited&saved yet.

**Comment by jeanfrancoisnoel** [comment]
good to know thank you for the efforts and fast response
