### ISSUE TITLE
Api call /clock dont return the server timezone 

### ISSUE THREAD

**Issue by jeanfrancoisnoel** [xibosignage/xibo#1629]
Not a bug but the return value dont return the exact timezone so it's impossible to take into account de daylight saving time if a event use the option Run at CMS Time?

Ex: 
{
	"time": "11:10 -04"
}

**Comment by alexharrington** [comment]
When Run at CMS time is ticked, the offset is handled CMS side based on the timezone the Player sends to the CMS. You don't need to account for it Player side too.
