### ISSUE TITLE
The Xibo default layout is always on

### ISSUE THREAD

**Issue by pierostz** [xibosignage/xibo#163]
Hello,

I deleted the default layout and created other two layouts and still the only thing I can get on my display is the default layout. Any scheduling of my layouts doesn't work also.
My server is on windows xp using XAMPP and my client is Windows 7 x86.

Thanks in advance.

**Comment by pierostz** [comment]
Hello again,

I seem to found the problem. It was a combination of setting the connection interval of the CMS and assigning the default layout to the display.

Thanks

**Comment by dasgarner** [comment]
Glad you have it working!

**Comment by pierostz** [comment]
Some more feedback on this (I don't know if I must open another thread).
Scheduling was done as described below.
1. Created two different layouts A and B.
2. Scheduled A and didn't play. I checked the priority checkbox and it worked.
3. Scheduled A and B at the same time and they didn't play.
4. Scheduled A and B at the same time with different order (1 and 2) and they didn't play.
5. Scheduled A and B at the same time with priority checkbox checked  and different order and Layout A played.
6. Scheduled A with priority checkbox checked and display order 2. Scheduled B 5 minutes later with priority checkbox checked and display order 1. A played but B never interrupted A to be played.

So it seems that the only thing that make the layouts to play is the priority checkbox and also there isn't seem to be any priority between the layouts in this way. 
How do I elaborate the issue?

Thanks in advance.

**Comment by dasgarner** [comment]
Delete all of your schedules so that you have an empty calendar. Schedule Layout A without priority ticked... what happens? 

Take a screen shot of the player information window (press i) so we can see what is happening

**Comment by pierostz** [comment]
Hello,

Did exactly what you said. It seems that we have a hint. The Layout A came up 5 minutes after it was scheduled. I schedule it for 15:20 and it showed up on 15:25. In the screenshot you can see that in the information window, the command was received at 15:20.

Is there any other setting that I have to change regarding the delay? 
![1522](https://cloud.githubusercontent.com/assets/3082659/6079986/42970e96-ae15-11e4-80a0-c9e14c162eea.png)

Thanks

**Comment by dasgarner** [comment]
When you did schedule it? The collection interval controls how often the player will check for new schedules. If you scheduled it in the CMS for 15:20 at 15:19 (for example), the player might have missed the start.

If you schedule it for 15:20 at 15:00, then the player will have that schedule in advance and start it on time.

Have you also checked the clock on your player PC?

**Comment by xadelfakis** [comment]
Dan,

i am colleague of Pieros. I schedule the two layouts at 16:15 to run the first one at 16:35 with priority 2 and length 40minutes, the second at 16:50 with priority 1 and length 20 minutes. What i expected is the first layout to run from 16:35 until 16:50 when the second one will interrupt the first due to priority and be played. What happened is, the first video started at 16:38, the second never started (i was waiting for it until 17:20). I found some errors in log file you can see attached. Also the time of server and player is exactly the same since they capture the time from the same server (i double checked it) 

![log](https://cloud.githubusercontent.com/assets/10922877/6108972/24bc9522-b080-11e4-93d2-b0ee096ea95c.png)
Thanks

**Comment by dasgarner** [comment]
I think we will need you to switch your player over the "auditing" and recapture the logs. The Player thinks there is something wrong with your layout ID:6 and is therefore refusing to play it.

**Comment by xadelfakis** [comment]
We did exactly the same tests today. The player reaction is the same but there are no threads on player. But i noticed something different. Lets start from beginning. At 10:15 i scheduled two different layouts. One to be played at 10:40 for 45 minutes and priority 2 and another one to be played at 10:55 for 20 minutes with priority 1. The noticed for the first video arrived at 10:40 but played at 10:43. The second video never played. At 11:10 i decided to make some changes to the schedules and move the schedules an hour ahead. I started from video 1. When i saved the changes the video 2 started playing. It was like video 1 was not allowing video 2 to be played. Remember that video 1 had priority 2 and video 2 priority 1. I do not know if you have version 1.7.1 installed, but can you check this scenario on your system? I think that priorities do not work as they have to work.

Regarding the logs you asked. Is there any log file in the xibo directory or only the web one. Or at least is there any easy way to export the log file? Copy paste tens of pages is lost of time. Anyway on the log files doesn't seem to be anything wrong. I attached some logs


![log](https://cloud.githubusercontent.com/assets/10922877/6125720/ed9485b2-b121-11e4-85d5-4a94c7a341eb.png)

**Comment by dasgarner** [comment]
There is a "save log" button at the bottom of the client information screen.

I think there is a misunderstanding regarding priority - the priority is a check box, either ON or OFF. I think you are talking about "Display Order", which is only the order of display.

If you have Layout A on at 10:40 and then Layout B on at 10:55, but layout A has a video lasting 2 hours - layout B will never show.

**Comment by xadelfakis** [comment]
This changes a lot. What is the meaning of display order?

**Comment by dasgarner** [comment]
It is the order the layouts will be displayed in rotation for the period they are scheduled.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
