### ISSUE TITLE
Cannot remove tags from Displays

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#1632]
CMS Version: 1.8.11

Issue: Add a tag to a Display. Cannot remove tag, when Save is selected, Unexpected Error returned.
Once a tag has been applied to a Display Group, you cannot add Displays to the group, or remove Displays already assigned to the Group. Display group also cannot be deleted once a tag has been applied.

**Comment by PeterMis** [comment]
The fix in the commit above did allow to remove the tag and save the display/displayGroup, however if user tried to remove the tagged display/displayGroup then it would still return an error about sql Constraint violation.

We need to ensure that we unassign the tags before we try to delete the displayGroup, it is implemented in the commit below.
