### ISSUE TITLE
Import Backup Database Not working

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#1636]
CMS Version: 1.8.11

Issue: When trying to upload a backup Database in CMS, after clicking Start Upload, Empty File Upload Result message is shown. Does not upload backup.

**Comment by dasgarner** [comment]
Import database is a security risk and prone to error. It hasn't ever been in 1.8 for this reason and therefore the bug is actually that the button still exists. 

We will remove the button and associated code.
