### ISSUE TITLE
api call : /stats Lacking displayId for proofOfPlay  

### ISSUE THREAD

**Issue by jeanfrancoisnoel** [xibosignage/xibo#1639]
The call return the display name but not it's id, since the display name is not set as unique and can be changed at any time the id should be provided to allow a definitive identification to be used with the other provided id  : layoutId, widgetId and mediaId

while the call allow to filter by display id it would require an individual api call for each player instead of a single call

**Comment by PeterMis** [comment]
Thank you for bringing this to our attention, we can certainly add the displayId to the API response, we shall do that in 1.8.12.
