### ISSUE TITLE
python client transition out

### ISSUE THREAD

**Issue by ronansalmon** [xibosignage/xibo#164]
using version 1.6.0-rc2, xibo freeze whenever there is an exit transition on a region.
I use a layout containing one fullscreen region containing 3 webpages.

Looking at the logs (see below), I can see that M8b80d0c83aa336bf12fd685676a8b80d-44-45 is deleted and then queued.
The layout was scheduled to end up at 2015-02-04 14:20:00, and there was nothing schedule after.

LOG: 2015-02-04 14:19:55 (.enqueue:4588) 3 info Enqueue: del M8b80d0c83aa336bf12fd685676a8b80d-44-45
LOG: 2015-02-04 14:19:55 (.enqueue:4594) 3 info Queue length is now 1
LOG: 2015-02-04 14:19:55 (.frameHandle:4613) 5 debug Removed node M8b80d0c83aa336bf12fd685676a8b80d-44-45
LOG: 2015-02-04 14:20:01 (.finishTick:4275) 2 info XiboLayoutManager: finishTick() (Mode3) -> Destroying current layout
LOG: 2015-02-04 14:20:01 (.dispose:2124) 5 info R52f885fbb5a9c-44 is disposing.
LOG: 2015-02-04 14:20:01 (.dispose:2138) 5 info Region Options: transOut -> fly
LOG: 2015-02-04 14:20:01 (.dispose:2138) 5 info Region Options: transOutDuration -> 3000
LOG: 2015-02-04 14:20:01 (.dispose:2138) 5 info Region Options: transOutDirection -> E
LOG: 2015-02-04 14:20:01 (.dispose:2150) 5 info R52f885fbb5a9c-44 starting exit transition
LOG: 2015-02-04 14:20:01 (.__init__:30) 2 info FlyTransition plugin loaded!
LOG: 2015-02-04 14:20:01 (.dispose:2155) 5 info R52f885fbb5a9c-44 control passed to Transition object.
LOG: 2015-02-04 14:20:01 (.calculateNextTick:2687) 2 audit XmdsScheduler: LayoutID 466: From: 1422946800.0 To: 1423056000.0 (Now: 1423056001.68)
LOG: 2015-02-04 14:20:01 (.calculateNextTick:2706) 2 audit XmdsScheduler: Not setting a nextStartTick as no future schedule.
LOG: 2015-02-04 14:20:01 (.calculateNextTick:2712) 2 audit XmdsScheduler: Not setting a nextFinishTick as no future schedule.
LOG: 2015-02-04 14:20:01 (.run:40) 5 info Running FlyOut transition
LOG: 2015-02-04 14:20:01 (.enqueue:4588) 3 info Enqueue: anim ('linear', 'M8b80d0c83aa336bf12fd685676a8b80d-44-45', 3000, 'x', 0, -1090.0, <bound method FlyTransition.next of <FlyTransition(Thread-19003, started 140284860098304)>>)
LOG: 2015-02-04 14:20:01 (.enqueue:4594) 3 info Queue length is now 1
LOG: 2015-02-04 14:20:01 (.frameHandle:4745) 0 audit An unspecified error occured: anim : ('linear', 'M8b80d0c83aa336bf12fd685676a8b80d-44-45', 3000, 'x', 0, -1090.0, <bound method FlyTransition.next of <FlyTransition(Thread-19003, started 140284860098304)>>)
LOG: 2015-02-04 14:20:02 (.enqueue:4588) 3 info Enqueue: setOpacity ('infoRFGreen', 0)
LOG: 2015-02-04 14:20:02 (.enqueue:4594) 3 info Queue length is now 1

Any ideas ?
Thanks,
Ronan

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
