### ISSUE TITLE
Font not displaying correctly

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#1641]
CMS: 1.8.11
Players: Windows 1.8.10-132, Android 1.8 R107

Issue: tested 2 fonts, one is woff format, the other is otf. 

The woff font imports into Library and can be seen, but does not appear as an option in the Text widget under fonts.

The otf file imports fine, and can be set in Text widget. On Android, the font is displayed correctly when scheduled, on Windows, the font appears as Times New Roman. 

I have a copy of the font for testing should you need it.

**Comment by dasgarner** [comment]
This is a problem with the font file itself - the meta data in the font didn't match the actual font name and therefore IE11 wouldn't display it.

Nothing we can do here as long as we have to use IE11, therefore marking as won't fix.
