### ISSUE TITLE
Power Point is not enable

### ISSUE THREAD

**Issue by hsanchez08** [xibosignage/xibo#165]
My problem is when I try to put a powerpoint file in a layout, xibo shows me any time that I open that layout that I have to open or save the file, and then when I run the xibo client, shows a message that the powerpoint is not enable on this display, could you help me pls? regards

**Comment by dkjain** [comment]
Can u try this, plz
https://answers.launchpad.net/xibo/+faq/2569

**Comment by hsanchez08** [comment]
I already did that, in the last version, now the issue is presented when I updated the xibo to the version 1.7. The thing is when I upload the file to the server in the webpage on xibo, And when I run the client, just show me the message that is not enable on this display, but doesn't do any action, or open the powerpoint

**Comment by dasgarner** [comment]
You need to enable it - create a display profile for windows, edit it and turn on PowerPoint

**Comment by hsanchez08** [comment]
the problem is that happen in all profiles of windows, power point is enable, this is that happens
![6](https://cloud.githubusercontent.com/assets/10869753/6080183/0ec75724-add4-11e4-9f22-eda5f9887370.png)

![7](https://cloud.githubusercontent.com/assets/10869753/6080185/1370779c-add4-11e4-83a1-92c1af23c4a7.PNG)

**Comment by Speedy-Gonzalez** [comment]
Have you assigned your display profile (with PowerPoint enabled) to your display?

**Comment by hsanchez08** [comment]
OHH! Thank you, is in the panel of display profile that I have to enabled! now its working good!
