### ISSUE TITLE
Weather Widget: "Concurrent record locked, time out" error when not configured correctly

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#1650]
CMS version: 1.8.11

Issue: If the weather widget has not been configured correctly (API key was not entered), "Concurrent record locked, time out" error occurs. Unexpected error message is seen on the layout page.

**Comment by dasgarner** [comment]
I think this happens because the "Configuration Exception" isn't being caught correctly by the Module Widget.

What should happen is that if we are in a preview, the error should be displayed, but if we are via XMDS it should return empty.

In both cases the widget cache should be unlocked.
