### ISSUE TITLE
Export layout broken where a media item has been edited

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1657]
Where a media item is replaced from the library, but the old version is not deleted and existing layouts not updated (ie where database holds isEdited=1 for a media item), exporting that layout ends in a broken export since those media items are not included in the exported zip file.

To replicate, create a layout. Add two videos. Now go to the media library, and replace one video, unticking the update and delete options.

Now export the layout, and see that the zip file contains only one of the videos included in the layout.

Peter identified that the SQL run in export is limited to where media.isEdited=0

**Comment by PeterMis** [comment]
In case that Alex has mentioned, [this loop](https://github.com/xibosignage/xibo-cms/blob/release18/lib/Entity/Layout.php#L1100) seems to be executed only once, as we get only one item in the array.

The query seems to run through [this condition](https://github.com/xibosignage/xibo-cms/blob/release18/lib/Factory/MediaFactory.php#L608) with `mediaId = -1` as such the "AND media.isEdited = 0" is added to the final query and therefore the edited media is not returned in the `getByLayoutId` and therefore it is not added to the zip archive.
