### ISSUE TITLE
Power Point 

### ISSUE THREAD

**Issue by solutionssquad** [xibosignage/xibo#166]
Running Windows 8 32 bit.
Server is running Version 1.7.0.
Player is running 1.7.0.
System has Power Point viewer installed.

When embedding a ppt file, the viewer shows "open" "save" "cancel" instead of opening the file.
I have tried running the following with no luck:

http://xibo.org.uk/manual/en/media_module_powerpoint.html
http://wiki.xibo.org.uk/wiki/Install_Guide_NET_Client#Windows_Modifications

**Comment by dkjain** [comment]
Can u try this, plz
https://answers.launchpad.net/xibo/+faq/2569

**Comment by solutionssquad** [comment]
Making progress....
That helped but now it opens PPT in a separate window.

**Comment by Action01** [comment]
I had a similar problem, only difference is that I use PowerPoint in stead of the Viewer...

My solution was to apply the following registry changes:
(The BrowserFlags enables Internet Explorer to open Powerpoint, EditFlags opens the file in stead of showing the open/save dialog)

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PowerPoint.Show.8]
"BrowserFlags"=dword:800000A0
"EditFlags"=hex:00,00,01,00

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PowerPoint.Show.12]
"BrowserFlags"=dword:800000A0
"EditFlags"=hex:00,00,01,00

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PowerPoint.ShowMacroEnabled.12]
"BrowserFlags"=dword:800000A0

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PowerPoint.SlideShow.8]
"BrowserFlags"=dword:800000A0

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PowerPoint.SlideShow.12]
"BrowserFlags"=dword:800000A0

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PowerPoint.SlideShowMacroEnabled.12]
"BrowserFlags"=dword:800000A0
```

**Comment by dasgarner** [comment]
Full PowerPoint has to be installed to get PowerPoint to display - the viewer is not sufficient. You may consider exporting your PPT as a MP4 as an alternative.
