### ISSUE TITLE
Stocks Widget reports Change value incorrectly

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#1660]
CMS Version: 1.8.11

Issue: Created a Stocks widget. When checking the results tab in Edit Stocks, the Change value is a negative value instead of positive. 

Note: Customer discovered the bug and created a Community post. Includes screenshot of the incorrect value. Tested locally and on cloud, issue is the same.

https://community.xibo.org.uk/t/stock-module-with-wrong-change-sign/16029/2

**Comment by alexharrington** [comment]
Calculation happens here:
https://github.com/xibosignage/xibo-cms/blob/release18/lib/Widget/Stocks.php#L385
