### ISSUE TITLE
Local Video, Video and Video In Widget message incorrect

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#1661]
CMS Version: 1.8.11

Issue: Add Local Video/Edit Local Video Widget displays a message stating:
 "Please note that video scaling and video streaming via RTSP is only supported by Xibo for Android at the current time. The HLS streaming Widget can be used to show compatible video streams on Windows"

Change the above message to say Android Player instead of Xibo for Android.

Notes: Message is at these locations:

https://github.com/xibosignage/xibo-cms/blob/release18/modules/localvideo-form-add.twig#L89
https://github.com/xibosignage/xibo-cms/blob/release18/modules/localvideo-form-edit.twig#L90

**Comment by alexharrington** [comment]
Should also mention that the webOS Player supports RTSP there too.

**Comment by dasgarner** [comment]
The same is true on the Video module.

**Comment by DanielBW1** [comment]
https://github.com/xibosignage/xibo-cms/blob/release18/modules/video-form-edit.twig#L114

The above twig also contains a Xibo reference.
