### ISSUE TITLE
Video Loop not saving

### ISSUE THREAD

**Issue by solutionssquad** [xibosignage/xibo#167]
Windows 8 32 bit.
Server is running Version 1.7.0.
Player is running 1.7.0.

Adding a video to a layout, then editing and checking Loop does not save.
When you go back in, the loop option is unchecked.

**Comment by dkjain** [comment]
Try using Chrome

**Comment by solutionssquad** [comment]
Same.

**Comment by dasgarner** [comment]
Reported in #79
