### ISSUE TITLE
Improve the video form with a check box to "play until the end"

### ISSUE THREAD

**Issue by nagyrobi** [xibosignage/xibo#168]
When one uploads a video file to the library, the "Duration" field should be automatically filled with the length of the video.

**Comment by dasgarner** [comment]
We've tried this before, the libraries available aren't very good.

What is wrong with setting it to 0?

**Comment by nagyrobi** [comment]
How will the system know then how long the video needs to play?

**Comment by donnyyeo** [comment]
0 setting means play until end of video. Tested it many times. No issue.

**Comment by nagyrobi** [comment]
Hmm. Very unusal approach, but I certainly agree it's usable. I don't recall reading anywhere about this in any documentation or the CMS interface, so how am I supposed to know?

May I suggest to add this information to the bubble/balloon which pops up in the CMS interface when hovering the mouse above the related duration fields? So that the next user like me would save you from asking this again.

**Comment by dasgarner** [comment]
I've changed the title and made this an enhancement request

**Comment by nagyrobi** [comment]
OK thanks

**Comment by nagyrobi** [comment]
This may break https://github.com/xibosignage/xibo/issues/151 , as if the real length of the video is not known, the duration of the layout cannot be computed...

But nevertheless, it's important to let users know that 0 does have a meaning,
