### ISSUE TITLE
upgrade 1.6.4 to 1.7.0 mysql error

### ISSUE THREAD

**Issue by lpadumorvan** [xibosignage/xibo#169]
I will upgrade xibo 1.6.4 to 1.7.0. It gives this:
An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 80. Error Message = [SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9' for key 'PRIMARY']

Then if I press "next" button, I have this:
An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 80. Error Message = [SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'render_as']

**Comment by dasgarner** [comment]
When did you get your download? That particular error should have been fixed a few days after we released (and we patched the download files)

This is discussed in #87, #106, #103, #74, #70, #68, #65

**Comment by lpadumorvan** [comment]
I download now. I start the installation again and I have this :
An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 80. Error Message = [SQLSTATE[42S01]: Base table or view already exists: 1050 Table '`xibo`.`displayprofile`' already exists]
Upgrading from database version 72 to 84

I press the "next" button and I have this:
An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 80. Error Message = [SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'render_as']
Upgrading from database version 72 to 84

**Comment by dasgarner** [comment]
You need to revert to your backup - the installation has failed and left your database in a partially upgraded state - unfortunately the only way to run the installation again is to revert the database and then start the installation again.

**Comment by lpadumorvan** [comment]
Before the new installation, I have put my backup ! I use xibo long time, the updates are always gone well !

**Comment by dasgarner** [comment]
Sorry, I don't understand? You have got your backup? Just restore that and repeat the installation - no problem :smile: 

We do try and make it so that they always go well - unfortunately this time we missed some things that didn't effect our test systems.

**Comment by lpadumorvan** [comment]
I have restore my backup and I have repeat the installation and ever the same error.

**Comment by dasgarner** [comment]
it just isn't possible to have the same error that you first reported - that has been fixed in the latest 1.7.1 release download.

So please confirm you have:
 * A backup of your previous version **before** you attempted any upgrade
 * The latest 1.7.1 released code (re-download it)

If this fails then you will need to manually run the contents of each file from `install/database/` folder, starting at the file related to your version and going upwards until done. If you are on 1.6.4 you will need to run `70.sql` onwards.

**Comment by lpadumorvan** [comment]
I use the backup of my previous version before any upgrade, but same error.
I try with 1.7.1 but same error
I have 1.6.4
For manual upgrade, are you sure to begin with 70.sql, because in 70.sql, I read "UPDATE `version` SET `app_ver` = '1.6.2'" ?

**Comment by dasgarner** [comment]
sorry, you are correct I meant to say `80.sql` onwards.

**Comment by lpadumorvan** [comment]
But before to make the upgrade I have NOT the displayprofile table (phpmyadmin view) I have only "display" table and "displaygroup" table.
Next the error message "displayprofiles already exists", I do not see the displayprofile table ! (with phpmyadmin)

**Comment by dasgarner** [comment]
I'm sorry, but if MySQL says it exists, it must exist...

I think your only option is to run through those files manually - somehow your database is in a mess and the auto-ugprade will not work.

**Comment by lpadumorvan** [comment]
Incredible : mysql say it exists, but it really not exists...
I have downgrading mysql 5.5 to mysql 5.1 and now it's ok, upgrade was success...

**Comment by dasgarner** [comment]
we've had some real odd things with this upgrade which we have never seen before - but I think yours is the oddest!

At least you have it solved.
