### ISSUE TITLE
dynamic display group by tag

### ISSUE THREAD

**Issue by sgiunchi** [xibosignage/xibo#1699]
I put displays in different dynamic groups.
To do so, I use strings in the display name, but it only allows 50 characters so there's no much space for the real name (which is the only field shown in some lists).
It would be useful to have dynamic display groups to filter by tag and not (only) by substring in the name.

**Comment by dasgarner** [comment]
Sounds like a useful feature to me - if you'd like to see it implemented please create a feature topic in our community so that it is considered for the roadmap.

This bug tracker is only used for verified bugs and features we've added to the roadmap.

Thanks!
