### ISSUE TITLE
1.7 - After Upgrade Layout (embedded-escale-invalid)

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#17]
Originally reported by @laercionit https://bugs.launchpad.net/xibo/+bug/1397762

"Embedded and Ticker invalid scale on 1.7 Layout After Upgrade"

**Comment by laercionit** [comment]
Dan, the tests I did, using the 1.7 RC1 client on windows, the results are the images I sent. It's all out of scale as before. The problems are in tickers and embedded.

How can I help you better understand the problem.
Want admin access to my test with CMS 1.7 RC1 and point a windows and android display to perform your tests?

**Comment by laercionit** [comment]
The regions will be resized to fit with the new resolution, but you may need to adjust the content manually.

This message makes sense.
Do you have any way to keep editing the resolution or template to maintain compatibility with the previous model size of the contents.

I ask because I could create a new standard and leave the old layouts following this pattern, otherwise I will have problems to migrate and get fit all at the same time.

**Comment by laercionit** [comment]
We could adjust the layout upgrade function to implement the necessary changes in formatting aimed not be that kind of impact.

Size source ticker and embedded option, I totally viable.

Independende than set, I could not do my work embeded content with the correct scale as it was before ....

**Comment by laercionit** [comment]
Dan, I downloaded the latest version of the GIT repository.
I did some more tests.

We had 3 problems:

error-Embedded in the layout designer
ok-Embedded in the player
error-BUG-Ticker font size
error-Clock function in Javascript has problem with the code we used previously. Only appears with the calendar date.


Embedded in the designer, without scoring the scala option worked, but need to put in zoom = 1.6 to represent reality, but it was very large and had to use the browser zoom out ... Is there any option to tell the system which the default ZOOM and this adjustment in the layout designer to be representing reality?

In the embedded player worked well, without making any changes, MAINTAINING cms in the scale option unchecked.

The tickers used the font size 20 in the version 1.6.4. In tests 1.7 RC1, increase needed to stay as before. I believe the upgrade function could automatically increase these sources to perform the upgrade. I think it would just multiply by a factor of upgrade to get the correct value of the font size.

On the clock, I did not understand the problem, cause the code worked before and not now. The layout that sent me the UOL, I put the watch otherwise. Is it something related?

**Comment by dasgarner** [comment]
Hi Laercio,

There has been a massive change to the way the layouts are stored as explained in the release notes. Previously they were stored at the designer resolution of 800 x 450, now they are stored at the display resolution of 1920 x 1080.

When you are upgrading an old layout, Xibo automatically adjusts the region sizes and positions so they are stored using the new format, but there are simply too many unknowns to upgrade all of the region content.

**Upgrading the Layout is optional** and old layouts should continue playing as before without upgrading. You can therefore "trickle" feed the changes across your network, or only adopt the new format for new layouts.

To better understand I think we need a few things:

1. A screen shot of the Layout Designer **before** upgrading to 1.7, showing the ticker text
2. A screen shot of the player output (got this, attached) 
![image](https://cloud.githubusercontent.com/assets/10400067/5833939/6d750838-a150-11e4-9451-a2f2a24a5827.png)

3. Upgrade to 1.7
4. Before doing anything, export the layout and send
5. Pick one problem at a time (for example the ticker) and focus our attentions there

**Comment by laercionit** [comment]
Hello Dan, 

1- Layout Designer Before Upgrade
Scale Weather forecast embedded direct the layout designer. Not with the Scala Marked option, checking is better in the designer and client error in windows.

Note the size of the source ticker at the bottom of the player.
![layoutdesigner-beforeupgrade](https://cloud.githubusercontent.com/assets/325662/5867414/f2c54ef2-a282-11e4-95ad-0e2df8b57150.JPG)

**Comment by laercionit** [comment]
Export layout not working, I can not generate the file for you. Timeout

**Comment by laercionit** [comment]
The export feature is working only for layouts that have been updated to version 1.7. If the layout is not updated the export does not work.

**Comment by laercionit** [comment]
Print layout running on the client windows, the layout running is not updated to version 1.7.

Everything running smoothly on windows client (Feed and Embedded).
Note the main difference in embedded to the weather and the calendar and clock in the bottom of the player. Only the calendar is displayed in the designer.

![windowsclient-beforeupgrade](https://cloud.githubusercontent.com/assets/325662/5867862/85a4ad76-a288-11e4-87d0-cfc489ba2cbd.jpg)

**Comment by laercionit** [comment]
Now the image of the designer layout after performing the upgrade layout.

Note that the source of the ticker was very small. The weather forecast did not change any look. The clock and calendar continue with the same problem.

In short, after performing the upgrade, only the source of the ticker change presented.
![layoutdesigner-afterupgrade](https://cloud.githubusercontent.com/assets/325662/5867922/52cf0152-a289-11e4-97c9-da37e62b4c95.JPG)

**Comment by laercionit** [comment]
About the export, the problem is not being updated or not. As I understand it is the amount of items in the timeline that generates timeout functionality.

Deleted several items and follows the layout of the file after updating.

**Comment by laercionit** [comment]
Now the windows image client running layout after performing the upgrade. Same problems.
![windowsclient-afterupgrade](https://cloud.githubusercontent.com/assets/325662/5867992/8ebde178-a28a-11e4-8fab-47ba9ca80247.jpg)

**Comment by laercionit** [comment]
Using the ZOOM layout designer using the zoom navedador by adjusting the font size of the ticker, I can leave the optimal viewing. only for representation.

Desiner ZOOM 1.6
Chrome Zoom 67%
Font Ticker - 20 to 48
![representation-designerzoom](https://cloud.githubusercontent.com/assets/325662/5868042/5b87de8e-a28b-11e4-9fee-e64f933c9708.jpg)

**Comment by laercionit** [comment]
I could not send the file by Git.
Follow by email - support@springsignage.com

**Comment by dasgarner** [comment]
Hi Laercio,

### Upgrading Layout
I understand exactly what you are seeing - but I don't think that is an issue - in fact it is exactly what the "upgrade layout" message warns you about.

### Weather
Before the upgrade it was incorrectly presented in the Layout Designer, after the upgrade it was incorrectly presented in the Layout Designer - that is what the scale button is for (to scale the embedded output to the size of the layout, rather than just taking the size of the designer).

### Export
I will submit a bug for this - it sounds like a time out serving all of those files down in 1 ZIP file. There may not be anything that can be done about this, other than to enable `SENDFILE_MODE` so that the web server is responsible for serving the file.

### Clock
I will import your layout and explore why the clock does not work.

**Comment by dasgarner** [comment]
Your clock embedded item doesn't work because you have the <script> in the HTML section and you have EmbeddedInit declared twice (once in the HTML section and once in the script section). With scale content ticked, it fits nicely in the designer and the client (without any adjustments, because the region is so small).


The weather does need some adjustment to scale correctly in the designer and the layout - but I think that is because you have the width and height mixed up. I set mine to this and it looked good:  style="height:350px;width:245px;border:0;" scrolling="no"

Please also remember that Layouts are designed in their native resolution now - meaning 1920x1080 in this case - this means that only the designer is scaling, everything else is native resolution - which should make things *much* easier to design.

### Layout Upgrades
Upgrading a Layout will not automatically try to adjust the items mentioned above - who is to say that changing the font size on the ticker from 20 to 48 is always the right thing to do? If we could always make that decision then we would have upgraded all layouts when the CMS upgrade occurred.

The scale factor for most layouts will be 2.4 - but I don't see how we can set that automatically as it won't always be the case.

**Comment by laercionit** [comment]
Dan,

The Scale option leaves the embeded with best view, but it is wrong in the
client.
The scale option should only affect the designer?

About the source of feed, there is nothing we can do to automatically
adjust the font to make the upgrade?


*Laercio Junior*
Cel./Pessoal: (21) 99162-7440
Email Pessoal: laercionit@gmail.com
MSN: laercionit@hotmail.com
Skype: laercionit



2015-01-23 7:18 GMT-02:00 Dan Garner <notifications@github.com>:

**Comment by dasgarner** [comment]
The scale option is correct in the final layout (for me), but your weather iframe sizes need changing as suggested: `style="height:350px;width:245px;border:0;" scrolling="no"`

We could go through and adjust all the font sizing to be 2.4 times bigger - maybe this could be provided as a check box for the user to choose whether or not that is desirable.

**Comment by dasgarner** [comment]
OK, so I have added an option to the Layout Upgrade which asks the user whether they want to up-scale the media assigned to the layout.

If the option is ticked, it will update any font sizing, width and height properties of the media contained in the layout.

**Comment by laercionit** [comment]
About Endebbed, understood that by scoring scale is best view in the designer is wrong and the client?

**Comment by dasgarner** [comment]
1.6 = embedded scale was wrong
1.7 = embedded scale is correct if you tick the box

Take an example - you have a region that is 1920x1080, inside you have an iframe with your weather feed that is 1920x1080 (i.e. full screen).

**1.6**
The player shows the iframe at 1920x1080 if you are on a 1920x1080 screen, it shows the frame at 1920x1080 if you are on a 1280x720 screen, it shows the frame at 1920x1080 if you are on a 800x450 screen.

The designer shows the iframe at 1920x1080 in a 800x450 window (the size of the layout in the designer)

**1.7 without scale ticked**
same

**1.7 with scale ticked**
The player shows the iframe at 1920x1080 if you are on a 1920x1080 screen, it shows the frame at 1280x720 if you are on a 1280x720 screen, it shows the frame at 800x450 if you are on a 800x450 screen.

The designer shows the iframe at 800x450 in a 800x450 window (the size of the layout in the designer)

**Comment by laercionit** [comment]
Scale OFF Designer
Scale Off Client (Show)

     [image: Imagem inline 6]                                           [image:
Imagem inline 3]



Scale ON Designer (Very Small, but visible )                        Scale
ON - Result Client (Show error, )

     [image: Imagem inline 4]
   [image: Imagem inline 5]




Dan, the scale option should only change the display in the designer? If
this somehow impacting the implementation of the client windows. See the
above tests ....

**Comment by dasgarner** [comment]
## Scale ON
### Client
![image](https://cloud.githubusercontent.com/assets/10400067/5879005/68c3b512-a323-11e4-94fc-12e4697e2fe1.png)

### Designer
![image](https://cloud.githubusercontent.com/assets/10400067/5879010/73043254-a323-11e4-80a6-0b2cd23e2bd2.png)

## Scale OFF

### Client
![image](https://cloud.githubusercontent.com/assets/10400067/5879067/f1ee1710-a323-11e4-9eed-054e63ebee66.png)

### Designer
![image](https://cloud.githubusercontent.com/assets/10400067/5879025/9f74cdc6-a323-11e4-917d-e61d2e1d1ce2.png)

**Comment by dasgarner** [comment]
Scaling is important if you will use the same layout on multiple screen resolutions - other than that, it doesn't matter if its on or off.

This was tested using the latest ZIP from the xibosignage/xibo-cms repository, develop branch.

**Comment by laercionit** [comment]
The CMS and Client code I have is the launch of version RC1. You are doing
the tests using TRUNK?

*Laercio Junior*
Cel./Pessoal: (21) 99162-7440
Email Pessoal: laercionit@gmail.com
MSN: laercionit@hotmail.com
Skype: laercionit



2015-01-23 15:20 GMT-02:00 Dan Garner <notifications@github.com>:

**Comment by dasgarner** [comment]
I am doing the tests using: git@github.com:xibosignage/xibo-cms.git

**Comment by dasgarner** [comment]
I did have a thought - when you upgraded your layout did you select the 1080p resolution and is that the resolution you are testing in your player?

The scale option works when the resolution of the layout is different to the resolution of whatever is displaying it - meaning Xibo is trying to help you when the resolutions don't match.

Assuming your layout resolution is 1920 x 1080, your designer resolution is 800x450 - meaning the iframe is 2.4 times smaller - so the iframe will be scaled down by 2.4 times.

If your client resolution is 1280 x 720, then it is 1.5 times smaller than the layout - so the iframe will be scaled down by 1.5 times.

**Comment by laercionit** [comment]
Dan,

I think we arrived at a solution.
Upon upgrade, selecting the 720P resoluççao and checking the scale option
is perfect in the designer and the client.

On the clock, something changed in the CMS code to work or function
javascript?



*Laercio Junior*
Cel./Pessoal: (21) 99162-7440
Email Pessoal: laercionit@gmail.com
MSN: laercionit@hotmail.com
Skype: laercionit



2015-01-23 16:24 GMT-02:00 Dan Garner <notifications@github.com>:

**Comment by dasgarner** [comment]
Great!!

Regarding the clock, the order in which we include javascript has changed slightly to make the page load quicker in the client (less chance of seeing any sign of loading).

This doesn't effect embedded items that have the script and html in the correct boxes - unfortunately for your clock you have a function called EmbedInit() in the HTML and also an empty function called EmbedInit in the script box - the empty one overrides the other.

You can either move them into the correct boxes, or remove the one from the script box.

Hope that helps!

**Comment by laercionit** [comment]
This all resolved DAN.
Now to launch with its functionality upgrade with the source set, will solve all my problems!

We go to the next! Thanks again for the support and guidance ...

**Comment by dasgarner** [comment]
You are welcome! Thanks for the assistance getting to the bottom of the issue!
