### ISSUE TITLE
Power Point Issue

### ISSUE THREAD

**Issue by hsanchez08** [xibosignage/xibo#170]
The issue is when I upload a file in powerpoint,whenever I open the viewer of xibo shows me a message that I have to open, save, or cancel, everytime even if I save the file.

![7](https://cloud.githubusercontent.com/assets/10869753/6080317/a7dd23de-add5-11e4-8470-cb13ef0c6437.PNG)

And in the client doesn't  display anything

![6](https://cloud.githubusercontent.com/assets/10869753/6080320/b4252376-add5-11e4-8c00-ebd4f886aacd.png)

**Comment by Speedy-Gonzalez** [comment]
Please open only one issue per problem. You can reopen your issue #165 if your problem still exists. Thanks.

**Comment by hsanchez08** [comment]
ok, thank you, you can closed this issue, regards
