### ISSUE TITLE
Windows Player should only check each unique layout in the schedule is valid once

### ISSUE THREAD

**Issue by xibo-de** [xibosignage/xibo#171]
Running Windows XP.
Server is running Version 1.7.0.
Player is running 1.7.0.

Xibo stops immediately after start. In the Client Library i found after one start many (236) log files:

![logfiles](https://cloud.githubusercontent.com/assets/10655684/6080431/89f4bd6e-ae11-11e4-9f33-4a0e5fdc9e9d.jpg)

Contents of the log files:

<trace date="2015-02-06 14:53:32" category="Error"><message>Layout invalid: 15</message><method>ScheduleManager - LoadNewSchedule</method><logdate>06.02.2015 14:53:32</logdate><thread>ScheduleManagerThread</thread>
</trace>
<trace date="2015-02-06 14:53:32" category="Error"><message>Layout invalid: 15</message><method>ScheduleManager - LoadNewSchedule</method><logdate>06.02.2015 14:53:32</logdate><thread>ScheduleManagerThread</thread>
</trace>
<trace date="2015-02-06 14:53:32" category="Error"><message>Layout invalid: 15</message><method>ScheduleManager - LoadNewSchedule</method><logdate>06.02.2015 14:53:32</logdate><thread>ScheduleManagerThread</thread>
</trace>
<trace date="2015-02-06 14:53:32" category="Error"><message>Layout invalid: 15</message><method>ScheduleManager - LoadNewSchedule</method><logdate>06.02.2015 14:53:32</logdate><thread>ScheduleManagerThread</thread>
</trace>
<trace date="2015-02-06 14:53:32" category="Error"><message>Layout invalid: 15</message><method>ScheduleManager - LoadNewSchedule</method><logdate>06.02.2015 14:53:32</logdate><thread>ScheduleManagerThread</thread>
</trace>
<trace date="2015-02-06 14:53:32" category="Error"><message>Layout invalid: 15</message><method>ScheduleManager - LoadNewSchedule</method><logdate>06.02.2015 14:53:32</logdate><thread>ScheduleManagerThread</thread>
</trace>

**Comment by xibo-de** [comment]
The error occurred on our Public Test System.

In the calendar is the scroll become very slow. But there are no items to see.

What struck me. In the table schedule_detail are 1,150,589 entries.

![schedule](https://cloud.githubusercontent.com/assets/10655684/6081476/0f2763f8-ae1a-11e4-9faa-7d61b11be1b5.jpg)
![schedule_detail](https://cloud.githubusercontent.com/assets/10655684/6081477/0f27859a-ae1a-11e4-9dc1-4ec0659abb94.jpg)

**Comment by dasgarner** [comment]
On the client side, in the library, can you see what is inside the `schedule.xml` file?

**Comment by xibo-de** [comment]
Have already eliminated the error. Tables schedule and schedule_detail I deleted. After that, everything works again.

I think there is a public stupid testuser creating a recurring event (repeat every 1 minute).for years.

Picture 1 event_id: 25

 As a result, many records in the table schedule_detail. After that, nothing works.

**Comment by dasgarner** [comment]
Hmm, its interesting actually - I think the schedule manager could be cleverer - it doesn't need to check the same layout a million times if there are a million items in the schedule.
