### ISSUE TITLE
Windows Client: Volume settings not sticking.

### ISSUE THREAD

**Issue by solutionssquad** [xibosignage/xibo#172]
This is happening on Windows 8 32 bit.
Server is running Version 1.7.0.
Player is running 1.7.0.

In older versions, you were able to go into Windows, volume mixer, mute Xibo, and the setting would stick on restart.
With the latest version, it does not.
According to the following URL, it's up-to Xibo to allow that setting to stick.

http://lifehacker.com/5862661/set-volume-levels-for-individual-programs-in-windows

"This is down to each individual program's designers whether to support the feature."

**Comment by dasgarner** [comment]
We've certainly not had code for that in the past, so I am not sure how/why it would have worked or stopped working that way.

Will need some investigation.

**Comment by dasgarner** [comment]
I can't find anything that tells me how or why this might have changed. Are you sure that you could do this with older versions on the exact same PC you have currently?

**Comment by solutionssquad** [comment]
Yes.
I did find a workaround (don't remember what at this point, but it included registry changes).

**Comment by dasgarner** [comment]
Thanks for the response - if you do remember could you fill in the details in the below topic?

[Moved here](https://community.xibo.org.uk/t/windows-client-volume-settings-not-sticking/64) until we can verify it as a bug.
