### ISSUE TITLE
Theme for Analogue Clock states Light regardless of settings.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#1722]
CMS Version: 1.8.11

Issue: Create a Clock Widget and set Clock Type to Analogue. Change the Theme to Dark and Save. If you now access the Edit Widget settings, it will state that the Theme is Light. 

Note: The Analogue Clock does change to Dark theme, it is only in the Edit Widget window that it states Light incorrectly. Also scheduled the Clock to my Player, which displayed the correct Theme I had set for the Widget.

**Comment by PeterMis** [comment]
Fixed here - https://github.com/PeterMis/xibo-cms/commit/9ddeef40165130571c3698045584626daa3c477e
