### ISSUE TITLE
Embedded Google Slides displaying on Windows Player has a grey square in the top corner.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#1739]
Player version: Xibo for Windows 1.8.10-122 and 1.8.12-133

Issue: When using Google Slides in an Embedded Widget, a grey square appears in the top left corner. 

Notes: Not seen on Xibo for Android. A forum user has posted that they have a potential fix for the issue: https://community.xibo.org.uk/t/issue-with-google-slide-embed/15929/22

**Comment by DanielBW1** [comment]
Further posts have been added to the Community Post. A User has found a workaround for this issue which involves disabling Flash

**Comment by dasgarner** [comment]
Fixed in edge player: https://github.com/xibosignage/xibo-dotnetclient/issues/73
