### ISSUE TITLE
With German translation the layout designer options button looks bad

### ISSUE THREAD

**Issue by Speedy-Gonzalez** [xibosignage/xibo#174]
I've made two screenshots. Here you can see what it looks like when German translations are enabled:
![with_width](https://cloud.githubusercontent.com/assets/1389907/6085119/3b6c0ce4-ae37-11e4-8dac-40b7fb64e3c0.png)

And here I've made some changes to the css file ("bootstrap.min.css" .col-md-1 width):
![without_width](https://cloud.githubusercontent.com/assets/1389907/6085122/3ef27ff6-ae37-11e4-8684-2b9813cd9820.png)
But I don't know if this change will break other CMS sites. Could you please check? There is so much space left in the center of the side, so the layout name could be displayed there.
Thanks!

**Comment by dasgarner** [comment]
We probably just want to change the DIV to col-md-2 rather than changing bootstrap.

**Comment by Speedy-Gonzalez** [comment]
Created a pull request.

**Comment by dasgarner** [comment]
Great, i'll check it out
