### ISSUE TITLE
CMS is not correctly adjusting the schedule for Players in different time zones.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#1741]
CMS Version: 1.8.12, CMS timezone set to GMT.

Issue: Set up a Player with a time zone of GMT -5, Eastern Time (US and Canada) configured in the system settings (tested on Windows). Create a Layout for the Display and give it a Custom Dayparting based on the local time of the Player device, with "Run at CMS Time?" unticked. The Layout will not appear at the time scheduled.

Note: This was also tested by setting the time zone on the player device to Singapore timezone (GMT +8). The Layout appeared at the correct time.

**Comment by dasgarner** [comment]
For clarity - CMS is 12:00 GMT, Player is 7AM, you come into the CMS and set the event for 7:15AM, and it doesn't work.

Root cause: we only serve the schedule from the top of the hour CMS time onward.
