### ISSUE TITLE
curl libsigcplusplus returns Not Found on Xibo-Linux

### ISSUE THREAD

**Issue by leandroschelb** [xibosignage/xibo#1751]
When running the command: "sudo docker build -t xibo-linux ." (note: in README 'docker' is misspelled as 'docket') in Ubuntu 18.04.2 LTS:

https://github.com/GNOME/libsigcplusplus/archive/${SIGC}.tar.gz, SIGC=2.10.0 returns Not Found, Changed to https://github.com/libsigcplusplus/libsigcplusplus/releases/download/2.10.0/libsigcplusplus-${SIGC}.tar.xz

The tar and cd commands needed to be updated, the final RUN commands was:

RUN ACLOCAL_PATH="/usr/local/share/aclocal" && \
    export ACLOCAL_PATH && \
	curl -o /root/libsigcplusplus.tar.gx -SL https://github.com/libsigcplusplus/libsigcplusplus/releases/download/2.10.0/libsigcplusplus-${SIGC}.tar.xz && \
    cd /root && \
    tar -xf libsigcplusplus.tar.gx && \
    cd libsigc++-${SIGC} && \
    ./autogen.sh && \
    make && \
    make install && \
    cd /root && \
    rm -r /root/libsigc++-${SIGC} && \
    rm /root/libsigcplusplus.tar.gx

**Comment by alexharrington** [comment]
Thanks for your report.

It's already been fixed in one of our teams local branch and will be pulled in at next merge.
