### ISSUE TITLE
mysql error update 1.6.4 to 1.7.0 

### ISSUE THREAD

**Issue by bigxpicanha** [xibosignage/xibo#177]
An error occurred populating the database. Statement number: 56. Error Message = [SQLSTATE[HY000]: General error: 1005 Can't create table 'xibo.#sql-187c_2368' (errno: 121)]

**Comment by dasgarner** [comment]
ok, that is an odd one... if you can provide us your database backup we can take a look for you

**Comment by bigxpicanha** [comment]
Ok. But where do i put the database, e,mail ??

Conectado pela Motorola


Dan Garner <notifications@github.com> escreveu:


ok, that is an odd one... if you can provide us your database backup we can take a look for you

-

**Comment by dasgarner** [comment]
if you aren't comfortable putting it online you can wetransferit to support@springsignage.com

**Comment by bigxpicanha** [comment]
my database is too big, the backup file is 238 MB, how can i send you?

**Comment by dasgarner** [comment]
wetransferit to support@springsignage.com

**Comment by bigxpicanha** [comment]
I Get The 1.6.4 And Try To Update, The Same Error

**Comment by sanjak26** [comment]
we get the same problems to upgrade from 1.4 to 1.7 
we have also tried to upgrade from 1.6 to 1.7 ,
do u have any solution ?
we get the following problem 
An error occurred populating the database. Statement number: 56. Error Message = [SQLSTATE[HY000]: General error: 1005 Can't create table 'xibo.#sql-450f_191' (errno: 121)]

**Comment by dasgarner** [comment]
@bigxpicanha has reported that on an empty 1.6.4 installation the same error message is experienced 
``` sql
[SQLSTATE[HY000]: General error: 1005 Can't create table 'xibo.#sql-187c_2368' (errno: 121)]
```

In both cases the statement number is 56, which is: 
``` sql
UPDATE `setting` SET cat = 'general', ordering = 90, usersee = '1', userchange = '1', `default` = '1', `title` = 'Enable Library Tidy?' WHERE setting = 'SETTING_LIBRARY_TIDY_ENABLED';
```

Looks totally unrelated.


Can you both change link 283 of `lib/pages/install.class.php` so that it reads:

``` php
throw new Exception(sprintf(__('An error occurred populating the database. Statement number: %d. Error Message = [%s]. SQL[%s]'), $sqlStatementCount, $e->getMessage(), $sql));
```

And then run the upgrade again?

**Comment by bigxpicanha** [comment]
statement number 56
#1054 - Unknown column 'ordering' in 'field list'

**Comment by bigxpicanha** [comment]
about "Can you both change link 283 of lib/pages/install.class.php so that it reads:"
after change link 283 

![error updating 1 7 0](https://cloud.githubusercontent.com/assets/10884470/6127398/8eb985e8-b111-11e4-9c6a-5a10f6e5d41f.JPG)

**Comment by dasgarner** [comment]
Sorry, I told you completely the wrong file.

`lib/pages/upgrade.class.php`

Line 259

``` php
throw new Exception(sprintf(__('An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: %d. Error Message = [%s]. File = [%s]. SQL = [%s].'), $i, $e->getMessage(), $sql_file, $sql));
```

**Comment by bigxpicanha** [comment]
Unfortunately it did not work again
I think I'm doing something wrong,
unfortunately I do not know PHP
![error updating 1 7 0 after line 259 update](https://cloud.githubusercontent.com/assets/10884470/6132186/045fc778-b138-11e4-96a4-70dc7588d415.JPG)

**Comment by bigxpicanha** [comment]
See if done right, please
I opened a file called "upgrade.class", located the line 259 and replaces the informed by you.
After saving the file tried to update, but gave error again, as follows ...

![error after upgrade php](https://cloud.githubusercontent.com/assets/10884470/6133081/94d24b68-b13e-11e4-9eb7-43e422a4d9b9.JPG)

**Comment by sanjak26** [comment]
we get the same

**Comment by bigxpicanha** [comment]
nothing??

**Comment by dasgarner** [comment]
We are working as fast as we can!!!

The screenshot you posted shows an installation not an upgrade - I thought you were running an upgrade?

**Comment by bigxpicanha** [comment]
Sorry, did not rush, just wanted to see if I was doing something wrong.

**Comment by bigxpicanha** [comment]
Sobre a atualização, vou te enviar a sequencia de telas
como segue
![upgrade](https://cloud.githubusercontent.com/assets/10884470/6167095/8d39e152-b29e-11e4-8211-13a41e7ae46b.JPG)

**Comment by bigxpicanha** [comment]
in sequence
![sequencia 1](https://cloud.githubusercontent.com/assets/10884470/6167103/ad60e43a-b29e-11e4-8db5-5475acc09451.JPG)
![sequencia 2](https://cloud.githubusercontent.com/assets/10884470/6167107/b6392914-b29e-11e4-92db-507c00774de3.JPG)
![sequencia 3](https://cloud.githubusercontent.com/assets/10884470/6167110/b89078e8-b29e-11e4-9d3b-74ea1d3ad2bc.JPG)
![sequencia 4](https://cloud.githubusercontent.com/assets/10884470/6167111/bb471f9c-b29e-11e4-8f2a-610b74f00842.JPG)

**Comment by bigxpicanha** [comment]
it automatically returns to the screen, as if asking a new facility.
Sequence of installation:
I formatted a server running Windows 2012 server.
installed Xampp 1.7.7
installed the version 1.6.4
After working version, do the following:
Copy the contents of 1.7.0 zipped folder into the folder Xibo
then in the browser http: // localhost / Xibo
previously sent screens show the messages.
I do not know if I'm being clear, because my English is very bad.

**Comment by bigxpicanha** [comment]
Não sei se vocês instalarem a versão 1.6.4 e tentarem atualizar, 
Pois já tentei em Windows 7, Windows 2003 server e por último Windows 2012 server.

**Comment by dasgarner** [comment]
So you are installing a brand new database and it fails on statement 56 each time.

Statement 56 is:

``` sql
ALTER TABLE `blacklist`
  ADD CONSTRAINT `blacklist_ibfk_1` FOREIGN KEY (`MediaID`) REFERENCES `media` (`mediaID`),
  ADD CONSTRAINT `blacklist_ibfk_2` FOREIGN KEY (`DisplayID`) REFERENCES `display` (`displayid`)
```

This doesn't seem to be the cause of the error.

On a **new database** can you try the instructions for modifying the install.class.php file? SO we can see what statement it actually fails on?

Change link 283 of lib/pages/install.class.php so that it reads:

`throw new Exception(sprintf(__('An error occurred populating the database. Statement number: %d. Error Message = [%s]. SQL[%s]'), $sqlStatementCount, $e->getMessage(), $sql));`

**Comment by bigxpicanha** [comment]
![erro update database](https://cloud.githubusercontent.com/assets/10884470/6234066/b630780e-b6be-11e4-8040-91be48b850c4.JPG)

**Comment by bigxpicanha** [comment]
this error happens when I try to update manually
is the same error

**Comment by bigxpicanha** [comment]
after #70 
![erro novo 56](https://cloud.githubusercontent.com/assets/10884470/6248257/fd503372-b764-11e4-8319-c907dfd2937d.JPG)

**Comment by dasgarner** [comment]
Sorry, but I really can't help you further until you answer my questions.

**Comment by bigxpicanha** [comment]
after updating the link 283 install.class.php

![apos atualizar link 283](https://cloud.githubusercontent.com/assets/10884470/6266242/10239246-b81e-11e4-829a-88903522efc3.JPG)

**Comment by dasgarner** [comment]
Can you try changing Line 65 of `install/master/structure.sql` so that it reads:

``` sql
  `displayid` int(11) NOT NULL AUTO_INCREMENT,
```

In context that is:

``` sql
CREATE TABLE IF NOT EXISTS `display` (
  `displayid` int(11) NOT NULL AUTO_INCREMENT,
  `isAuditing` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'Is this display auditing',
```

**Comment by bigxpicanha** [comment]
![changed line](https://cloud.githubusercontent.com/assets/10884470/6327044/7f28aee0-bb36-11e4-9ce0-a9e1dfa42125.JPG)

![after change line 65 of structure](https://cloud.githubusercontent.com/assets/10884470/6327116/27bcd7ac-bb37-11e4-97b0-7abb4980253e.JPG)

**Comment by dasgarner** [comment]
Just delete those lines then and see if it proceeds

**Comment by bigxpicanha** [comment]
after delete those lines, all started with "ALTET TABLE"

![after delete lines](https://cloud.githubusercontent.com/assets/10884470/6369945/f7ff0258-bcc9-11e4-9ce0-369aa6bbceb9.JPG)

**Comment by dasgarner** [comment]
Make sure your existing database is **empty**

**Comment by bigxpicanha** [comment]
But I need to update the version.
Then I install the empty database?
How do I restore the backup later, if the versions are different ?.

**Comment by dasgarner** [comment]
You are running the installer - which means you must install into an empty database...

If you are updating an existing version you must be missing your `settings.php` file from the installation - otherwise you would be in the **updater** and not the **installer**

All of the instructions I have given you are for installation, not update.

**Comment by bigxpicanha** [comment]
I own a 4GB database with information and been driven programming (1.6.4)
How do I upgrade to the latest version without I lose my data ??
please, help-me

**Comment by dasgarner** [comment]
This is getting a little frustrating for us both :smile: 

To upgrade you need to follow the instructions in the release notes - **BUT** I am sure you will receive the same error as installation, and I don't know why.

I don't know how to solve your problem - all I can recommend is to contact someone in the [Xibo directory](http://xibo.org.uk/directory) and ask them to do the upgrade for you as a commercial project.

**Comment by bigxpicanha** [comment]
ok, sorry for disturbing you
