### ISSUE TITLE
Name / Description field adding to Media in Regional Timeline 

### ISSUE THREAD

**Issue by andyrogers2012** [xibosignage/xibo#178]
Hi

When using certain types of media (Ticker, Text or Webpage), it is currently very hard to identify which object has what content as in the Regional Timeline view it only displays these references and does not give the user an additional field to enter a meaningful description for their chosen media on these types.

This causes an administration nightmare when trying to alter one particular text media when you have got quite a few in one presentation.  You have to keep going in and out of each one to make sure you have go the correct one.

If in these situations for media Text, Ticker, Webpage an additional field of say Name or Description was available just like in the Embedded media type this new field could then be displayed as the name in Regional Timeline view instead of the media type of "Ticker, Text or Webpage".

![image](https://cloud.githubusercontent.com/assets/1714633/6090452/c61bf874-ae71-11e4-9b7b-ab5314222bd3.png)

I know this sounds like a small trivial change request, but it would be really help to most end users who use Xibo heavily.

**Comment by laercionit** [comment]
What the version your CMS ?

**Comment by laercionit** [comment]
Since version 1.6.3 there is an optional field called NAME. This item appears in the timeline if it is filled.
For Ticker and Embedded Types ONLY.

It would be useful to Text and Webpage also ..

**Comment by andyrogers2012** [comment]
Woops you are correct sorry, shows its late at night here (02:55 am).
I was going through checking the other media types since if I was reporting for Text & Webpages mights as well have also done any other missing types but didn't spot this on the Ticker sorry.
Must have been thinking was still on 1.6.2 which are using on our live install.

I am currently testing 1.7.0 before a live roll out soon, but am going to possibly hang on for 1.7.1 to fix early release issues.

**Comment by dasgarner** [comment]
1.7.1 is out now :smile:

**Comment by andyrogers2012** [comment]
Yes have jsut upgraded to 1.7.1 thanks, but my original issue about Name / Description field adding to Text / Webpages does not exist so not sure why this question has been closed.

**Comment by dasgarner** [comment]
Sorry, I missed the enhancement request. Tagged up now.

**Comment by andyrogers2012** [comment]
Submitted Pull Request https://github.com/xibosignage/xibo-cms/pull/31 which should resolve this issue
