### ISSUE TITLE
2.0.1 Install fails on MySQL 5.7

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1780]
When installing a fresh CMS against MySQL 5.7, the `20180130073838 InstallMigration` migration fails with the error:

    SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 38

Complete log as follows:
```
cms-web_1  | New install
cms-web_1  | Provisioning Database
cms-web_1  | Phinx by CakePHP - https://phinx.org. 0.9.2
cms-web_1  | 
cms-web_1  | using config file .varwwwcmsphinx.php
cms-web_1  | using config parser php
cms-web_1  | using migration paths 
cms-web_1  |  - /var/www/cms/db/migrations
cms-web_1  | warning no environment specified, defaulting to: production
cms-web_1  | using adapter mysql
cms-web_1  | using database cms
cms-web_1  | 
cms-web_1  |  == 20180130073838 InstallMigration: migrating
cms-web_1  | 
cms-web_1  |                                                                                
cms-web_1  |   [PDOException]                                                               
cms-web_1  |   SQLSTATE[22001]: String data, right truncated: 1406 Data too long for colum  
cms-web_1  |   n 'title' at row 38
```

Can be replicated simply by swapping 5.6 for 5.7 in the mysql image line of the standard `docker-compose.yml` file.

OP: https://community.xibo.org.uk/t/sqlstate-22001-string-data-right-truncated-1406-data-too-long-for-column-title-at-row-38/18374

**Comment by vanvlietautogroep** [comment]
In the file "db\migrations\20180130073838_install_migration.php" on row number 1093 (The insert for option "TRANSITION_CONFIG_LOCKED_CHECKB") te title: "Allow modifications to the transition configuration?" is 52 characters long where 50 is max.
