### ISSUE TITLE
Update To and From times stored in incorrect format

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#1791]
CMS Version: 1.8.12

Issue: The Update To and From times are on occasion being stored in hh:mm:ss format instead of hh:mm. 

Notes: 
This has been seen on Android and webOS Display Groups.

**Comment by alexharrington** [comment]
I wonder if it's worth considering having XMDS correct it on the way through? We seem to have had a recent spate of these causing issues, and Player side changes take a very long time to percolate through, and while I think it's not  a bad thing for the Players to accept either, if we can have the CMS just strip the trailing `:00` and that fixes it for every Player out there already then that seems to me to be worthwhile?
