### ISSUE TITLE
Playlist closure table not updated

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1797]
Seen on a 2.0.1 CMS on Community, the Playlist closure table was not correctly updated and hence no media items are added to RF.

OP: https://community.xibo.org.uk/t/players-not-downloading-media-from-playlists/18208/26

**Comment by rd98ac** [comment]
Is there a quick/dirty temp fix to this in the meantime? All our layouts are essentially broken until it's resolved (which I know isn't your problem).

**Comment by rd98ac** [comment]
I just noticed - when I made a change to an existing playlist, even after waiting the requisite minute for the "Update Dynamic Playlists" task to run, the layouts using that playlist break. I will attempt to break them one more time to verify this is the case.

**Comment by dasgarner** [comment]
Are these dynamic Playlists then in your case?

**Comment by rd98ac** [comment]
No, not in this case - I am manually populating the items in the playlist. I just wasn't sure if that job was required to update the layouts.

**Comment by dasgarner** [comment]
Ah OK, thanks for the clarification.

When you make manual changes to a Playlist you would expect the Layout Status to go from a tick/!/x to the cogs to indicate that it is building. The Regular Maintenance task will then build the Layout and update the assignments necessary.

However, the closure table mention in this report will be updated only as you assign/unassign Playlists from a Sub-Playlist. Updating a Playlist has no effect on the closure table.

**Comment by rd98ac** [comment]
Ok ... so that I have a better understanding of this "closure table" (I haven't been able to find a table like this in the DB) - if I remove and re-add the playlists on the layouts affected, moving forward we shouldn't have this issue, am I correct? If so I will take the leap and just update the 60-odd layouts we have in the meantime.

**Comment by dasgarner** [comment]
The table is called `lkplaylistplaylist` and it maps the relationship between sub-playlists and their playlists (allowing for nesting - i.e. having a Playlist with a Sub-Playlist which itself has Playlists).

It only gets updated when Sub-Playlist widgets are touched - i.e those assignments are changed, a playlist is deleted, a sub-playlist is deleted, etc.

Editing your Layouts and removing/re-adding the sub-playlist widget ought to fix it, although it is a mystery how it gets into that state in the first place. I've not been able to recreate it despite some fairly aggressive saving and editing of Sub-Playlists.

**Comment by rd98ac** [comment]
Ya I saw that table, but wasn't sure. I'll take a look. I've worked with databases / web development for 15-20 years now and even with the greatest of referential integrity and constraint checking, tables end up messed on occasion! Keeps us employed I say..

**Comment by dasgarner** [comment]
Haha, it does indeed. If you find anything fishy looking i'm happy to dig in and see if we can work out why it ends up like that.

**Comment by rd98ac** [comment]
Not sure if this is relevant, but when I add timeline items to a playlist, going back to the list of playlists I see the clock icon as expected. This stays until the job runs to recalculate the duration (assuming is the regular maintenance job that handles that?). If I just delete an item from the playlist (and not add one), the old timeline duration still appears, it doesn't trip a recalculation.
