### ISSUE TITLE
Language links in English manual incorrect

### ISSUE THREAD

**Issue by Speedy-Gonzalez** [xibosignage/xibo#180]
When you go to the manual http://xibo.org.uk/manual/ and want to select another language you get e.g. http://xibo.org.uk/fr/index.html instead of http://xibo.org.uk/manual/fr/index.html

It happens just on the manual site. When you go directly to http://xibo.org.uk/manual/en everything is alright.

**Comment by dasgarner** [comment]
Fixed it!
