### ISSUE TITLE
Wider options dialog (fits better with other languages then English)

### ISSUE THREAD

**Issue by Speedy-Gonzalez** [xibosignage/xibo#181]
The options dialog fits fine with English translations. In other languages (e.g. German) the dialog is just too small.

![xibo_options_dialog](https://cloud.githubusercontent.com/assets/1389907/6091574/1e1fc050-aeb3-11e4-84ad-cc0409a63196.png)

I played around with the CSS and changed the width value (from bootstrap.min.css, class modal-dialog)
![xibo_modal_dialog_width](https://cloud.githubusercontent.com/assets/1389907/6091579/61f1a082-aeb3-11e4-9bdd-8533a0a27536.png)

Now it looks fine for almost every option dialog (some phrases are just too long in German, you can't consider all phrases)

**Comment by nagyrobi** [comment]
+1 for this

**Comment by dasgarner** [comment]
Can you put that change in `xibo.css`? if you target the same CSS selectors it will override without modifying the core bootstrap files.

**Comment by Speedy-Gonzalez** [comment]
I've created a Pull Request.

**Comment by dasgarner** [comment]
Thanks!
