### ISSUE TITLE
Duration for Items in Dynamic Playlist does not change once set.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#1815]
CMS version: 2.0.2

Issue: create a Dynamic Playlist. the items that are added will use the default duration set for the Module. Once the Playlist has been created, the duration of the Media items cannot be changed.

**Comment by dasgarner** [comment]
This was re-raised here: https://community.xibo.org.uk/t/dynamic-playlist-media-duration/21978
