### ISSUE TITLE
Database schema for display varies between upgrade and fresh install

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1825]
There appear to be differences in the database schema between 2.0.2 as an upgrade and as a fresh install on the `display` table.

OP reported the following log message that triggered this investigation:
```RegisterDisplay SQLSTATE[HY000]: General error: 1364 Field ‘lastAccessed’ doesn’t have a default value```

Specifically:
- [ ] `lastaccessed` on an upgrade is `Null=YES`. On a fresh install it's `Null=NO`
- [ ] `license` on an upgrade is `Null=YES`. On a fresh install it's `Null=NO`
- [ ] `email_alert` on an upgrade is `Default=1`. On a fresh install it's `Default=0`
- [ ] `alert_timeout` on an upgrade is `Default=0`. On a fresh install it's `Default=NULL`
- [ ] `ClientAddress` on an upgrade is `varchar(100)`, `Null=YES`. On a fresh install it's `varchar(50)`, `Null=NO`
- [ ] `MacAddress` on an upgrade is `Null=YES`. On a fresh install it's `Null=NO`
- [ ] `LastChanged` on an upgrade is `Null=YES`. On a fresh install it's `Null=NO`
- [ ] `NumberofMacAddressChanges` on an upgrade is `Default=0`. On a fresh install it's `Default=NULL`
- [ ] `LastWakeOnLanCommandSent` on an upgrade is `Null=YES`. On a fresh install it's `NULL=NO`
- [ ] `displayprofileid` on upgrade is `Key=`. On a fresh install, it's `Key=MUL`. Missing index?

**Comment by moobyfr** [comment]
I've upgraded to 2.0.3 from 2.0.1 but I'm missing in particular default value for 'NumberofMacAddressChanges'

**Comment by alexharrington** [comment]
There are no database schema changes in patch releases, so there won't be any database changes made to your install until you upgrade to 2.1.0 when it is released.
