### ISSUE TITLE
Collapsible menu does not work

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#183]
After merging the Collapsible menu into xibosignage/xibo-cms it does not work on Chrome. See below screenshot for test:

![image](https://cloud.githubusercontent.com/assets/10400067/6092048/58585548-aec2-11e4-856f-e386e8bf58c5.png)

**Comment by dasgarner** [comment]
@laercionit

**Comment by laercionit** [comment]
Dan, did the tests.
For some reason when you enter the code for override.css xibo.css no longer works.

Remains in override.css works. I will look more closely and generate commit again.

**Comment by dasgarner** [comment]
I've fixed this by changing the order of the included CSS files. I'd imagine there was something after xibo.css which overrode some of your new styles.

**Comment by laercionit** [comment]
Yes, the problem was the Dashboard.css.

Identified the problem, but do not know if I could change the header.php.

*Laercio Junior*
Cel./Pessoal: (21) 99162-7440
Email Pessoal: laercionit@gmail.com
MSN: laercionit@hotmail.com
Skype: laercionit



2015-02-08 12:05 GMT-02:00 Dan Garner <notifications@github.com>:

**Comment by laercionit** [comment]
Dan, like the outcome? He was very good in my opinion.

About the layout as a whole, I have another one made from scratch if you want to analyze.

**Comment by laercionit** [comment]
Menu without scroll bar...

![image](https://cloud.githubusercontent.com/assets/325662/6097092/30a9f252-af96-11e4-8be9-55b4f9c9c516.png)

**Comment by dasgarner** [comment]
Yup, i'd like to look at it. Can it be wrapped into a new theme subfolder?

**Comment by laercionit** [comment]
OK, Dan

I will include the Default-NEW directory for your review.
I make a PULL only the directory of the new theme?

**Comment by dasgarner** [comment]
Just commit and push it to your local one, I can look at it from there and we can decide if we pull it in or not.

**Comment by laercionit** [comment]
OK Dan, Done....
