### ISSUE TITLE
Reduce CMS menu items height

### ISSUE THREAD

**Issue by nagyrobi** [xibosignage/xibo#184]
The menu column on the left of the CMS scrolls off a Full HD screen. This makes workflow slow, because each time one clicks anywhere, the page with the whole menu reloads and every time has to be scrolled down again (when examining the Log, for example).

This could be easily fixed by simply reducing the individual height of the menu items, so that they all fit into 1080px including most common browser toolbars. Full HD is a very common screen resolution on machines used for administering the CMS. It would also look better imho...

The picture below shows it using Firefox with the favorites toolbar hidden.
![xibo_cms_menuitems_too_tall](https://cloud.githubusercontent.com/assets/1550668/6092696/e002e310-aee9-11e4-98af-833243b62cbf.png)

**Comment by dasgarner** [comment]
@laercionit - thoughts?

**Comment by laercionit** [comment]
My choice for this theme would be default.

What do you think? I need to make some adjustments in CSS, but I would be this way.

https://cloud.githubusercontent.com/assets/325662/6097099/76cbac8a-af96-11e4-8ed1-9d8216e7c8d7.png
![image](https://cloud.githubusercontent.com/assets/325662/6097340/d1b1395c-afa1-11e4-8ef6-e29ef0aee621.png)

![image](https://cloud.githubusercontent.com/assets/325662/6097341/da41976a-afa1-11e4-8414-c34df682577f.png)

**Comment by laercionit** [comment]
The main problem is the issue of tables, many information. It is great for use in browsers, but for mobile, have no option of taking some columns simply looks good viewing difficult.

**Comment by nagyrobi** [comment]
Why not just simply reduce the menu cell height?

**Comment by nagyrobi** [comment]
I've submitted a patch with reduced menu items height, check and see if you like it. 

![xibo_cms_menuitems_fix1](https://cloud.githubusercontent.com/assets/1550668/6098520/851a7e88-afe1-11e4-884c-b23ba919eb58.png)

**Comment by laercionit** [comment]
Good Job!

**Comment by dasgarner** [comment]
I must admit I personally liked the larger menu items - mainly because I keep pressing the wrong ones :smile: 

I'm not adverse to dropping the size down.. if that is what everyone would prefer

**Comment by dasgarner** [comment]
I've merged this into develop and have been trying it out - and I must say I really cannot get on with it... it makes the menu much harder to use IMO.... the items are too close together, which means it hard to differentiate between them.

I'm not saying its perfect as it is, but I don't like that alteration :smile:

**Comment by nagyrobi** [comment]
Well it's all subjective :)

IMHO it was much worse to keep scrolling the screen to reach those menus at the bottom. I'll make a special updated version for you with taller items, OK? Hold on...

**Comment by nagyrobi** [comment]
Well to be honest, I like it better this way, because I can switch very fast between the menu items without the need to scroll back and forth. It's there at a glance, it's easy to get an overview of the whole thing.

How do you mean "hard to differentiate"? You just have to read the menu text...
I've even grouped the categories a bit, so that helps more to focus easier on what type of task one wants to do.

**Comment by dasgarner** [comment]
They are too close together - with the original spacing it was nice and clean and clear... the reduced spacing makes it look cluttered and hard to read.

Just my opinion!

The look we are going for is clean and uncluttered, which is incidentally why I am not keen on the white borders in the screenshot from laercionit

If you are dead set on your adjustments, pop them in a subfolder under `theme/`, copy the `config.php` and the file you changed into it and set that as your default theme in global settings.

**Comment by nagyrobi** [comment]
It's a subjective aestethics feeling that we both have and see different. I don't find it cluttered and hard to read at all on my 22" FullHD screen of my desktop, and 17" FullHD screen of my laptop.

It's more hard and difficult to use when having to scroll uselessly IMHO, and that's what effectively hardens the usage, takes away precious time from the user. There are other places in the CMS design where this happens (for example in the media content library table, where if one happens to upload a file with a long filename, the whole table goes off the screen to the right with all the dropdown menu icons, so again to reach them, the user has to scroll to the right at the bottom of the screen only to reach the menus...
(I was planning to make a fix for this too, by splitting the filename string to multiple lines keeping the cell width maxed)

**Comment by dasgarner** [comment]
that is a different thing entirely - forcing a break inside the table is a great idea.

Of course its down to a subjective opinion - I spend a LOT of time using the CMS, in multiple tabs, switching around testing obscure configs, etc. I routinely have 4 sessions open on different screens and they all have different resolutions 1366x768, 1440x900, 1690x1050 and 1920x1080... All I am saying is that I found it **harder** to use when they were squashed together.

It would be useful to get other peoples opinions - that's all I am saying

**Comment by nagyrobi** [comment]
Is there a voting engine on GitHub? Like forums have...

**Comment by dasgarner** [comment]
No there isn't...

I think that the best course of action is to create a variant of the default theme, called "compact" or something similar and pop those files in there that I mentioned.

We can push that theme with the release and then people have the option how they want to use it - best of both worlds! 

We shouldn't make an arbitrary decision, the user should choose.

**Comment by nagyrobi** [comment]
That's a good idea. Could you please do it for 1.7.2?

**Comment by andyrogers2012** [comment]
+1 for having an additional "compact" theme.
Best of both worlds, end user then can choose what suits them best

**Comment by dasgarner** [comment]
a "compact" theme it is then - if you could modify your original change to include this, that would be great.

We'd need a folder under theme called "compact", a config.php file in there that had appropriate information inside it and then the file you changed (in its correct folder).

**Comment by nagyrobi** [comment]
done: https://github.com/nagyrobi/xibo-cms/tree/develop/theme/compact

**Comment by dasgarner** [comment]
grand: https://github.com/xibosignage/xibo-cms/pull/30

i'll merge when I can.
