### ISSUE TITLE
Unable to assign images for video from library

### ISSUE THREAD

**Issue by andyblackham** [xibosignage/xibo#186]
Just upgraded a freshly installed 1.7.0 to a 1.7.1 - the upgrade seemed to go without issue.

I am creating a layout.
Then editing the timeline, I 'Add Media' from (I have used video and image)

I can upload new items, select them (+ button) and order the items in the timeline, but the assign button, bottom right has no function and I cannot complete the action.

This means I cannot create new content.

**Comment by laercionit** [comment]
+1 for this...

**Comment by nagyrobi** [comment]
Wow. Should release 1.7.2 immediately with this, because people can delete content from layouts but cannot put anything back in...

**Comment by DruryP** [comment]
Hi Guys, Am having the same issue, note that the issue has been identified and resolved.  How do we go about getting the patches for this?

Cheers

Phil

**Comment by nagyrobi** [comment]
- Go to https://github.com/dasgarner/xibo-cms
- Click "Download ZIP"
- Extract lib/data/region.data.class.php and lib/modules/module.class.php from the ZIP to your 1.7.1 location and overwrite in the corresponding directories.

**Comment by dasgarner** [comment]
The release has been patched so you can re-download the ZIP from the website. Relatively small exposure luckily!

**Comment by andyrogers2012** [comment]
Wow, this was a really quick bug fix.  Upgraded last night to 1.7.1 and started to hit my head against a brick wall wondering what I had done wrong.

Thanks for the quick fix.

**Comment by DruryP** [comment]
Hi,  Just applied the recommened patch and all is now working.  Would like to echo "andyrogers2012" about the turnaround speed on this bug fix.  Well done and thanks very much.


Phil

**Comment by dasgarner** [comment]
Its a shame it got in there - entirely my fault!

**Comment by kevinrsalisbury** [comment]
Thanks, Dan. Will upgrade now. Sorry I did not see this post earlier! -Kevin

**Comment by dasgarner** [comment]
No problem!
