### ISSUE TITLE
XIBO Example Twitter Module

### ISSUE THREAD

**Issue by willitas** [xibosignage/xibo#187]
Greetings, I've migrated to version 1.7 of Xibo, but I can not connect the module to the application of twitter, there is no documentation about the API would be good to publish a step-by-step testing module facilictar Guide

**Comment by dasgarner** [comment]
It would be good to do that - you are correct - I have marked as an enhancement.

Basically you register a new application on twitter and copy the API key and secret into the twitter module.

**Comment by dasgarner** [comment]
Improve the Twitter Manual page to take the user through installing the module and getting the API Key. Also include a section for the Xibo Cloud configuration which shows how to connect the Twitter Module to their account
