### ISSUE TITLE
Windows player v2-R200 can't connect to SNI-hosted CMS

### ISSUE THREAD

**Issue by goetzc** [xibosignage/xibo#1886]
Hey there. CMS version 2.0.4 is installed using Docker and works correctly with HTTPS on a multi-host server. 

Android player can connect to it, but the Windows player (xibo-client-v2-R200-win32-x86.msi) fails with the following error:
`“The underlying connection was closed: An unexpected error occurred on a send.” ` 

![image](https://user-images.githubusercontent.com/2220440/62094292-35b2b280-b242-11e9-8794-c4419c6d7713.png)

with no more information. After moving the CMS to a single application server, the player connects without issue.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/2220440/62094616-5596a600-b243-11e9-947f-57776769b2ff.png">

**Comment by alexharrington** [comment]
Thanks for your report.

The Player will certainly connect to an SNI enabled host. We have that configuration regularly ourselves. There's something else about your host that is causing the issue. I'd have a look at your Windows event log as I'm fairly sure it's related to your Windows security policy.

We keep GitHub answers for verified bugs only. Please post over on our Community site for support.
