### ISSUE TITLE
New XML Tags in Ticker ?

### ISSUE THREAD

**Issue by heikopae** [xibosignage/xibo#189]
Server is running Version 1.7.0.

Hi,

Is it possible to put in the ticker new xml tags? For example: [content:encoded]
So that the content between <content:encoded> and  </content:encoded> will be displayed.

Heiko

**Comment by dasgarner** [comment]
Have you tried the [Content] tag?

**Comment by heikopae** [comment]
Hi Dan,

it works with the 'content' tag after I remove some
disturbing html Tags like img, p, span etc.

Thank You very much.
-- 
mit freundlichen Gr�ssen

Heiko Paepenm�ller

VI Technology GmbH
Bornholmstr. 20, 33729 Bielefeld
Tel.: +49 521 77027680
Fax : +49 521 77027689
E-mail: heiko.paepenmoeller@xibo-de.com
Internet: www.xibo-de.com

VI Technology GmbH
Gesch�ftsleitung: Heiko Paepenm�ller
Handelsregister : Amtsgericht Bielefeld HRB 37756
Sitz der Gesellschaft: Bielefeld
Ust.-Id: DE 813 656 135

**Comment by dasgarner** [comment]
Great! There is a stripTags option if you are using an external feed that you can't change.
