### ISSUE TITLE
XiboLinux Player not compiling with Boost 1.71

### ISSUE THREAD

**Issue by tasaif** [xibosignage/xibo#1938]
base64_encode has been changed to base64::encode and accepts different parameters
base64_decode has also been changed

README says:
- `Boost.System>=1.69`, `Boost.Date_Time>=1.69` and `Boost.Thread>=1.69`

**Comment by alexharrington** [comment]
Thanks for your message.

Please could I ask you post it in the Linux Player issue tracker as it won't be addressed here.

https://github.com/xibosignage/xibo-linux/issues

I believe we use 1.69 currently so I'd suggest using that in the interm,

Best wishes

Alex
