### ISSUE TITLE
Investigate move to alpine 3.11 / php 7.3 for official Docker images

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#1939]
alpine 3.8 goes end of support in less than 12 months, and php 7.2 goes end of support in to security fixes only in ~ 2 months.

I expect fairly minimal payload to that!

https://www.php.net/supported-versions.php
https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases

**Comment by alexharrington** [comment]
PHP 7.4 is in stable now so perhaps target that instead for 2.3 so we have the full 2 years of active support for it.

**Comment by dasgarner** [comment]
Alpine 3.11 which brings PHP 7.3.13
7.4 isn't packaged yet, but 7.3.13 is supported for longer in Alpine 3.11
