### ISSUE TITLE
Clock Entry 2 times in the menu (V1.7.1)

### ISSUE THREAD

**Issue by xibo-de** [xibosignage/xibo#194]
Clock Entry 2 times in the menu.

![clock-menue](https://cloud.githubusercontent.com/assets/10655684/6105759/06736b60-b05b-11e4-8de7-ecf832a1255a.jpg)

**Comment by dasgarner** [comment]
1.7.1 installed it automatically as it was missing from the 1.7.0 install. In hindsight I should have put this in the 1.7.0 upgrade SQL file. 

I will move it.

**Comment by nagyrobi** [comment]
OK but how should one delete it if already there?

**Comment by dasgarner** [comment]
Either disable one of them using the Module Administration page, or its a database job (unfortunately).

**Comment by xibo-de** [comment]
Today I downloaded xibo-cms-develop.zip. The .sql files from install / database I have copied to the installation directory of 1.7.1. After installation, I have again two times the clock module.

**Comment by dasgarner** [comment]
The clock is only inserted in 84.sql and will only be run going to version 84 (1.7.0)

**Comment by nagyrobi** [comment]
What's the database job to be executed? Deleting a row is enough?

**Comment by dasgarner** [comment]
yes, from the modules table.

**Comment by nagyrobi** [comment]
No indexes to fix and other magic, right?

**Comment by dasgarner** [comment]
That is correct - just delete the duplicate module record.
