### ISSUE TITLE
Client crashes after 1.7.1 upgrade

### ISSUE THREAD

**Issue by athesing** [xibosignage/xibo#196]
Hello,

I upgraded to CMS 1.7.1 this morning and I am experiencing client crashes on all three of my windows client machines.  From what I read, I shouldn't have had to update the client version.

I debugged the error and it looks like the client is looking for a log file that does not currently exist.  I've attached an example of what i'm seeing.  This same error occurs for all three machines i'm running.
![error](https://cloud.githubusercontent.com/assets/10927410/6111836/55eb144a-b051-11e4-85c9-dacef2124411.png)

**Comment by dasgarner** [comment]
I don't think this is caused by the 1.7.1 CMS update, it is most likely a player issue. I've marked it as a bug and will look at it this week.

**Comment by dasgarner** [comment]
Can you try the EXE from the attached commit?

**Comment by athesing** [comment]
Fixed the problem on all 3 machines.  Thank you for your help!

**Comment by dasgarner** [comment]
Fantastic, thank you for the feedback!
