### ISSUE TITLE
Can't upload new Media item to replace existing, error occurs.

### ISSUE THREAD

**Issue by andyrogers2012** [xibosignage/xibo#200]
I am currently using 1.7.1 Server, and have come across an issue when updating media.

I usually update media and keep the same filenames, which in 1.6.x I had no issues with, however in 1.7.1 i have come across this where it is saying "You already own media with this name. Please choose another". 
I have tried to change the name used which I have given to the media in the name box, but this makes no difference I always keep no getting this error.

![2015-02-09 23_03_59-xibo digital signage](https://cloud.githubusercontent.com/assets/1714633/6117945/97f27e28-b0b0-11e4-96f4-f46a8553e9d2.png)

Can you please look into and advise if I need to change some option, or if this is a bug?

I managed to upload one successfully first time around on top of an existing one with the same name, but this then left a duplicate entry in my media list of the old one being listed and the new one being listed separately but with different ID's the old one with the original ID and new media with a new ID again this didn't happen in the 1.6.x .

This this something to do with the additional option of "Delete the Old Version?"

**Comment by andyrogers2012** [comment]
Did this again, but with the option of "Delete the old version?" disabled and this worked as expected, so possibly looks like an issue when used with this check box enabled.

**Comment by dasgarner** [comment]
I've not been able to recreate the issue actually - can you give a step by step process to repeat, using a fresh media item?

This is what I did:
 - Upload a new image
 - Edit the image, upload a new one, tick delete
 - It swapped
 - Assign the image to a Layout
 - Edit the image, upload a new one, tick replace and delete
 - It swapped

**Comment by andyrogers2012** [comment]
Ok ill do some more digging and trying to replicate from scratch, somethiing is very strange with this.
Just tried to alter one of the effected slides slightly from within a Layout and it comes up with the same message at the bottom even though Iam not even uploading a new image

![2015-02-10 19_08_26-xibo digital signage](https://cloud.githubusercontent.com/assets/1714633/6134333/6fd4187c-b158-11e4-9118-ac3acb3fac20.png)

**Comment by andyrogers2012** [comment]
Ok have managed to re-create in 1.7.1 CMS the issue that I had originally reported.  Original error title was a little misleading so have renamed this issue slightly as its not related to the media being update with same filename.

To reproduce I did the following, but can be re-produced without using a layout but used this to simulate how I have worked with setting up and assigning media to a Layout.

1)  Create a New blank Layout called "Test Layout"
2)  Uploaded new media to Xibo Called Test1.jpg & Test2.jpg
3)  Assigned Test1.jpg & Test2.jpg to my "Test Layout" Layout
4) Modify my media Test1.jpg & Test2.jpg slightly and re-save with same filenames
5) Upload modified files into Xibo CMS via Library but making sure "Delete the old version?" is unticked.  N.B.  This is how they would have come across from 1.6.4 in this state as this option was not available in 1.6.x
6) Check my "Test Layout" to make sure media has been updated which has been
7) Modify Test1.jpg again & re-save with same filename again.
8) Update Test1.jpg in Library again but this time with leaving "Delete the old Version?" checkbox ticked.  Then click "Save".
This replicates how I originally came across this issue when trying to update an existing image for the first time using 1.7.1 after upgrading from 1.6.4
9) Picture updates, but then immediately in the library a duplicate entry appears for the Test 1.

![2015-02-10 20_13_44-xibo digital signage](https://cloud.githubusercontent.com/assets/1714633/6136698/d07b4d00-b16a-11e4-80aa-ef60bb275af6.png)

10) Now if you try to update the media again in the library or via the Layout you get the 
following error at the bottom and can no longer update this media.

![2015-02-10 19_08_26-xibo digital signage](https://cloud.githubusercontent.com/assets/1714633/6134333/6fd4187c-b158-11e4-9118-ac3acb3fac20.png)

Hope this all makes sense, any questions please do ask....

Thanks in advance

**Comment by dasgarner** [comment]
If the media has already been revised once, and the delete old version check box is marked, the current revision is deleted - but the prior one is persisted, meaning that a duplicate appears.

The duplicate is actually the 1st revision of the file.

Delete old version should remove all old versions.

**Comment by neilherbertuk** [comment]
I've just come across this issue and am running 1.7.4 - The above git commit is already in place so has not completely fixed the issue. 

![capture](https://cloud.githubusercontent.com/assets/5868029/10632549/16b60c40-77dd-11e5-8269-c6c366f03384.JPG)

**Comment by dasgarner** [comment]
The fix wouldn't have resolved any occurrences that already existed, as those items would have already become "detached".

If this is happening with an entirely new set of files, then please create a new issue for it.

Thanks
