### ISSUE TITLE
Revisit: Scheduling-Disallow Minute/Hourly repeats to be indefinite (or too long)

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#2005]
Currently we patched 6 months for hourly, which will still be problematic. We need to reconsider how we manage the cache so that we can forward populate from a point in time, rather than going back to the start.

**Comment by dasgarner** [comment]
We also need to confirm that the 6 monthly patch for Hourly got cherry picked into release22 please.

**Comment by dasgarner** [comment]
This is the patch we applied to 2.1 customer account to allow longer periods: https://github.com/PeterMis/xibo-cms/commit/afaf597dfc0f9322cb2f0b3a328f3fb10b6ce45c

**Comment by dasgarner** [comment]
Broadly the plan is as follows:
 - [ ] Disable validation in 2.1.3
 - [ ] Disable validation in 2.2.2

Then in 2.3
 - [ ] Update repeating events to only show one time per day
 - [ ] Add details to the event to clearly show that there are additional repeats
 - [ ] See if this improves the performance of the return to a point where we can use it
 - [ ] If not, look int a more efficient way to cache those events
