### ISSUE TITLE
Delete the old version? default setting in Settings

### ISSUE THREAD

**Issue by andyrogers2012** [xibosignage/xibo#201]
Would it be possible if the new option of "Delete the old version?" in the media library for all media could be made into a setting weather it is Ticked or not by default for the user

![2015-02-09 23_24_39-xibo digital signage](https://cloud.githubusercontent.com/assets/1714633/6118200/2035e0e8-b0b3-11e4-9f8a-51d39e8e6d00.png)

Thanks

Andy

**Comment by andyrogers2012** [comment]
Dan

I have done the workings to get the "Delete the old version?" setting reading from the database and saving and using the stored option upon this form being loaded which works successfully on my test install.

Im not 100% sure about the SQL file as im not sure how Xibo calls this upon triggering an upgrade, so have done what I can in this by looking at previous version i.e. 85.sql and called it 86.sql.

On this one I think I will need your guidance just in this area please.

BTW I have also learned how to "branch" out my commit :) this time around

Thanks in advance 

Andy

**Comment by dasgarner** [comment]
You've done it almost exactly right :smile: - I've commented on the commit so that you can see what needs altering.

There is one bit missing - locale/dbtranslate.php - this file contains strings that are in the DB which should end up in the POT file for translation (only code strings end up in the POT file).

Thanks a lot!

**Comment by andyrogers2012** [comment]
Dan

I have updated files after your comments thanks and have re-committed them.

Please see commit https://github.com/andyrogers2012/xibo-cms/commit/7f149cb030b1ca92a4e71b711fbe0f0ae48d0b9c

Thanks

Andy
