### ISSUE TITLE
Schedule Menu: Deleting Display Group while selected in Filter causes error

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2012]
CMS Version: 2.1.2

Issue: Create a Display Group. Now go to the Schedule menu and select that Group in the "Select Displays" filter. Now return to the Display Group menu and delete that Group. When you try to return to the Schedule menu, an error is returned and you cannot access the options.

Notes: 
- Does not occur on other versions of CMS.
- Logging out of the CMS, closing the browser, then restarting the browser and logging back on clears the issue.
- Only appears to affect the Select Displays filter in Schedule, no other filters return the same error.

**Comment by dasgarner** [comment]
This is already fixed in >=2.2
