### ISSUE TITLE
Library Size Box

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#203]
Currently for providing content to multiple customers using a shared CMS.
The Dashboard is an important tool, but currently only the administrator uses.

I wonder if there is interest in just indicate the total files that the user has access. Respecting the idea Admin view all / GroupAdmin view the total of your group / user only your files.

Ratify that is not important or impediment, but we could default the dashboard screen for all user if this adjustment is implemented.

I would be very happy to see this kind of implementation in version 1.8.

![image](https://cloud.githubusercontent.com/assets/325662/6119270/a34832b6-b0ad-11e4-83b9-88f09441c0f2.png)

![image](https://cloud.githubusercontent.com/assets/325662/6119295/07196a94-b0ae-11e4-922a-b542be4bc3b6.png)

**Comment by PeterMis** [comment]
Unlike the amount of display, this one doesn't work yet - it shows 100% of everything regardless of user permissions.
