### ISSUE TITLE
Image Resize Task - not updating md5 and fileSize

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#2032]
The Image Processing Task is not calculating the fileSize after resize and md5 calculation seem to return value for the pre-resize image.

We are calling $media->save() on it, which does not update md5 or fileSize in database.

Because of that old md5 and fileSize are in database, which then causes problems when player downloads the file and the checksum does not match.

**Comment by alexharrington** [comment]
As a workaround you can set resize threshold higher than resize limit value in CMS Settings on Default tab.
