### ISSUE TITLE
Now Showing Box

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#205]
I looked in the manual and could not identify the exact definition of "Now showing" the Dashboard.

Total Layouts, Layouts Total scheduling, Now Playing (Default / Scheduling) ... many choices and questions ...

In this print I sent, appears the number 113, but there is a single display connected to the test environment. But there are many scheduled and used as default since it came from a backup of my system in production.

![image](https://cloud.githubusercontent.com/assets/325662/6119586/ed12b020-b0b1-11e4-896b-7b35f108a284.png)

**Comment by dasgarner** [comment]
It is a count of scheduled layouts right now across all displays. It doesnt try to reduce that to the logged in displays, or the displays the user has access to.

It could do...
