### ISSUE TITLE
Bandwidth Usage

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#206]
This BOX is really cool, a good insight on bandwidth. In this box we're showing all the bandwidth grouped by month, but do not know if it's correct or not definition.

For this reason, I ask if there is interest in adjusting to group bandwidth for displays that the user has access. Respecting the setting of User / Group Admin and Admin

At the moment we do not use the Dashboard to the user, but it is such an interesting panel that small adjustment would allow the use.

Ratify that is no problem or urgency, but it would be very interesting.

Note: Please note that all boxes, only the Activity Display this using logic to check that the user has access.

![image](https://cloud.githubusercontent.com/assets/325662/6119684/3bfc97b8-b0b3-11e4-8ed4-8d4d23d029f6.png)

**Comment by alexharrington** [comment]
Laercio. I'm not sure "Doubt" is the right word for all of these. Doubt means for example if you weren't sure if someone were dishonest or not you would doubt their intentions. It would be better not to use that word IMHO :)

**Comment by laercionit** [comment]
Alex, sorry for my English.
It was a question, understanding of the functionality.
What is the best word to classify?

**Comment by alexharrington** [comment]
Question would probably be best - but actually I don't think you need to prefix any word at all :)

**Comment by dasgarner** [comment]
I've tagged this up as an enhancement - it would be good to make the entire dashboard user aspected so that you could use it for non-admin users too.

The restriction in this case would be against the Displays that the user had access to.
