### ISSUE TITLE
Optimise XMDS submit stats

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2065]
Investigate whether we can optimise the process of each stats request.

We could consider caching of look-ups, refactoring any duplication, etc.

We could also consider refactoring which bits of the logic are performed in XMDS and which bits are performed in the TimeSeriesStore classes - for example, if we had addStat take an individual record, and then had a "addStatFinalise" method which actually wrote the data - would that allow us to remove duplication?

**Comment by dasgarner** [comment]
Due to some performance issues we will need to address this issue in 2.2.3 instead of 2.3. I think the changes made already should be compatible.

**Comment by ifarzana** [comment]
Review Fix xibosignage/xibo#2083
