### ISSUE TITLE
Text not showing on display when server is unavailable

### ISSUE THREAD

**Issue by andyrogers2012** [xibosignage/xibo#207]
Hi

I have been doing to maintenance on our xibo server, and have come to notice since upgrading to 1.7.1 that on the client display if a Text field, or Embedded page are due to be displayed when the server is offline for whatever reason, nothing gets displayed on the screen for these slides just a blank screen.

As soon as the server is back online the media is available again.

In 1.6.x Text / Embbedded type media used to still show and load external references when the server is offline.

Can you please look into and advise if this is meant to happen now, or if this is possibly a bug.

Thanks

Andy

**Comment by ygurdag** [comment]
Same issue

**Comment by dasgarner** [comment]
Can you try the EXE from the linked commit? I think I have resolved the issue.

**Comment by andyrogers2012** [comment]
Ok have tested the linked commit EXE and can confirm that it works for Text Media, but unfortunately if it is a Embedded type it still shows a blank page.
I have 4 of these which display embedded images / content from external websites which did work with 1.6.x when the server was offline.

Thanks for the quick response again

**Comment by andyrogers2012** [comment]
If a bug like has been marked as closed but a fix has been released for part of the issue should I be opening a new bug or still commenting against the closed one?

**Comment by dasgarner** [comment]
You can continue to comment if you don't think it has been fixed - we get to these as quickly as we can, but there is a lot of communication occurring at the moment.

I've made another adjustment, which I hope will solve the issue for embedded and text (and any other type that doesn't have built in caching options).

**Comment by andyrogers2012** [comment]
Confirmed working as expected now with Embedded & Text media as reported.

Thanks again for the quick turnaround.

**Comment by Carlos-Costa** [comment]
Hello, i have this problem to.. what i have to do... download this files and replace them?

**Comment by dasgarner** [comment]
Yes, exactly - or wait for the next release which will contain the fixes.
