### ISSUE TITLE
Document region loop in the CMS to prevent confusion

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2075]
@tashamy1 to provide the rules

**Comment by Tashamy** [comment]
When should the Region Loop be enabled?
- If your Region contains more than one Widget, Loop should not be enabled.
- If your Region contains one Widget, and that Widget is a 'fixed' item (eg Text), Loop should not be enabled.
- If your Region contains one Widget, and that Widget needs to update periodically (eg RSS Ticker Widget), Loop can be enabled ONLY if the Widget needs to update MORE frequently than the duration of the overall Layout.
