### ISSUE TITLE
Assign to Library (Help me please)

### ISSUE THREAD

**Issue by mnjhost** [xibosignage/xibo#208]
Hi, Not sure if this is related to version 1.71 but here is my problem. I have 1.70 working on one server and thought rather than upgrade I would setup another server with 1.71. Everything went well and everything works ok, only when I upload any content to the library and try to assign it to a Layout the Assign button does nothing. Now this works on 1.70 and everything has been setup the same so should work. Any ideas guys/girls.
Please this is urgent for me as I am stuck. So when I am in the layout and click the + sign the media sits in the top window, but then when I click Assign it does nothing and I have to cancel. Everything works ok if I select one of the other items like clock . The server is a Ubuntu box and the clients are windows. Like I said the 1.70 version works perfectly. I have checked all of the files on the server and cannot find the problem. 
Cheers Guys/Girls

Mike

**Comment by mnjhost** [comment]
One other comment. I did notice that under modules that the Video and Images has a x under the Colum (Library Media) it shows a tick in each of the enabled, assignable and enabled. Could this x in the library media be part of my problem? even though I have uploaded video to the library its not been seen?

**Comment by andyrogers2012** [comment]
This sounds like the same issue at https://github.com/xibosignage/xibo/issues/186 which has already been fixed.

Try and download 1.7.1 again from the website and either reinstall from scratch again, or just use the mentioned files from within the download and replace on your current install

**Comment by mnjhost** [comment]
I will give that a try Andy, thanks for the quick response and your support:-) will feedback once I have tried

**Comment by mnjhost** [comment]
Sorted, all working fine. Thanks for the top support and have a great day

**Comment by dasgarner** [comment]
Thanks @andyrogers2012
