### ISSUE TITLE
ForecastIO Module

### ISSUE THREAD

**Issue by kevinrsalisbury** [xibosignage/xibo#211]
When using the Forecast IO module, there is only a Unix Time field available. Is there a clean way to present the date of the week in the forecast, perhaps calculated from the provided unix time field from Forecast IO? Example using the default options in Xibo's Forecast IO module.
![forecastio](https://cloud.githubusercontent.com/assets/5348334/6129011/f26e2b42-b108-11e4-9bc9-7072a85ef392.JPG)

**Comment by kevinrsalisbury** [comment]
...either a date or a day of the week like "Monday", "Tuesday", etc. OR to be really slick, "Today", "Tomorrow", "Thursday", "Friday", "Saturday", etc...

**Comment by MedusaDelft** [comment]
I don't know how to commit this, and I haven't tested it thoroughly, but try adding this:
forecastio.module.php, line 662 add:

		$orig_time = setlocale(LC_TIME, 'nl_NL', 'Dutch', 'nld_nld'); // replace with your own local
		$data->currently->day = strftime("%A", $data->currently->time);

At line 675 (just after the 'for' statement):

			$data['daily']['data'][$i]['day'] = strftime("%A", $data['daily']['data'][$i]['time']);

At (new) line 678 (just before the return), add this:

		setlocale(LC_TIME, $orig_time);


Now open the theme you use (eg. modules/theme/forecastio/daily.template.json) and add the code:

		[day]<br />

at the place you want the day to be displayed. I've put it just after the tag:

		<div class=\"day\">[day]<br />

And that's all....
If someone knows a better solution (mine is not perfect), please feel free to share it!

**Comment by kevinrsalisbury** [comment]
Thanks! Question from a php newbie, would you have any idea if my line 662 would be something like this (I am selecting US English)?

LC_TIME, 'en_US', 'English', 'en_US.utf8'

**Comment by kevinrsalisbury** [comment]
...and what is the third LC_TIME string used for? FWIW, locale -a provides the following en.us choices for me;
en_US
en_US.iso885915
en_US.utf8

**Comment by MedusaDelft** [comment]
Sounds about right (first comment). About the second comment: It's part of setlocale-function, not the LC_TIME constant. From my memory (I might be wrong!): basically it walks through all given options till it find one that match. Please see the description of the function at php.net/setlocale for more information.

**Comment by kevinrsalisbury** [comment]
Thanks! And for new 678 - I assume you mean before the 'Return' but After the '{'?

**Comment by kevinrsalisbury** [comment]
Works great! Thank you very much!

**Comment by dasgarner** [comment]
This would be a useful enhancement - we will take the locale from the default CMS language, provide a place to override that on the forecastio form and replace setLocale with http://php.net/manual/en/class.intldateformatter.php

**Comment by MedusaDelft** [comment]
Good point!

**Comment by supportreq** [comment]
Hi @dasgarner, can we also have some like this 
![weather-sample](https://cloud.githubusercontent.com/assets/4680404/6282057/2a40f2a0-b8f4-11e4-8d4d-cc94d0b70f59.jpg)

Current Day's weather in a bigger font and rest 4 days forecast in a smaller fashion..

**Comment by dasgarner** [comment]
I personally don't have the design skills to make that, but if someone could make that then we would be **more than happy** to include it as a template for the module... it looks lovely by the way...

I'd imagine the background wouldn't be there in the module - so that the user could put what they wanted underneath.

**Comment by supportreq** [comment]
@dasgarner I agree, I need your help in fetching 4days forecast.

**Comment by MedusaDelft** [comment]
I had a brief look at the api yesterday evening. It seems you can't request a number of days. What I currently am doing is hiding the last two days using css. Not the nicest way, but it seems to work.

**Comment by supportreq** [comment]
@MedusaDelft how are you fetching 7 days? I am just able to fetch a single day

**Comment by MedusaDelft** [comment]
I've chosen the 'daily'-template and set 'size' to 1, before I checked the override template function.

First part (the container) in which dailyForecast is replaced by the day-template

    <div class="container">
        <div class="daily-forecast">[dailyForecast]</div>
    </div>

The day-template:

    <div class="day"><div class="weekday">[day]</div>
        <div class="day-icon"><i class="wi [wicon]"></i><br />Min.: <span class="minTemp">[temperatureMin]</span><i class="wi wi-degrees"></i>C<br />Max.: <span class="maxTemp">[temperatureMax]</span><i class="wi wi-degrees"></i>C</div>
        <div class="day-desc"><br />[summary]</div>
    </div>

Using CSS I removed the last two 'day' columns I've created.

**Comment by MedusaDelft** [comment]
My current design (not yet finished!)

![image](https://cloud.githubusercontent.com/assets/10947534/6309795/fb977b24-b950-11e4-89ee-8394fe14264d.png)

Included some javascript to round the temperature and multiply the humidity. Unfortunately, it is currently not possible to include an own font (except loading it directly from a repository). Another thing that is a pitty is that jQuery is loaded after the content (so  $(document).ready  is not possible at this time).

Now, let's see if I can create something similar to @supportreq example.

**Comment by MedusaDelft** [comment]
Not finished yet, and it's not the best background for @supportreq example, but it's getting there.

![image](https://cloud.githubusercontent.com/assets/10947534/6311208/aa716aa2-b95f-11e4-89ef-9488777a8e1c.png)

**Comment by MedusaDelft** [comment]
I've created a bunch of HD backgrounds like the one shown above. If someone wants it, you can [download them here](http://www.computercreations.nl/assets/downloads/backgrounds_curved.zip)

**Comment by asrarak** [comment]
@MedusaDelft thats great dude

**Comment by andyrogers2012** [comment]
@MedusaDelft  really like the first design

**Comment by supportreq** [comment]
@MedusaDelft the backgrounds are amazing!!

how did you implement the template? unable to do it.. please guide..

**Comment by MedusaDelft** [comment]
I've just put them in as a background for the layout

**Comment by MedusaDelft** [comment]
@andyrogers2012 I've now even created an animated background for this one ;-)

**Comment by dasgarner** [comment]
@MedusaDelft great, just great - are you planning on providing the template files for this so that we can include them?

> Unfortunately, it is currently not possible to include an own font (except loading it directly from a repository). Another thing that is a pitty is that jQuery is loaded after the content (so $(document).ready is not possible at this time).

Custom fonts uploaded using the font module should be included - they are written into `fonts.css` and included in all modules.

jQuery is loaded at the end of the HTML on purpose - so that the page loads as quickly as possible. I overlooked the potential of including JavaScript. That should really have its own box and be included after jQuery in the HTML.

**Comment by MedusaDelft** [comment]
I've tried uploading a font, but it doesn't seem te get included in fonts.css (or loaded). At least, with a preview it falls back to the default font I entered.

javascript-box should be great!

I've trouble making a template, see one of my other issues

**Comment by dasgarner** [comment]
You followed the instructions? ;-) at the moment you have to Edit and Save it to install the font (already on the list to improve).

**Comment by MedusaDelft** [comment]
I can't remember to 'edit' the font. I'll give it a try tonight and let you know. Thanks!

**Comment by MedusaDelft** [comment]
After a lot of trying, I found the problem!  Not sure where the problem lies. I use 'PoiretOne-Regular' from google-fonts. When uploading, the default name is the filename. I've changed that to 'PoiretOne Regular'.  But google's example gives you 'Poiret One' to use in css-tags. So that's why I did have a problem :-)

**Comment by dasgarner** [comment]
So when you use the name you provided to Xibo, it works?

**Comment by MedusaDelft** [comment]
Yes, it works, but do have a problem (again) with the fonts.css. On the client it won't update. The file on the client is gone (deleted I suppose), but no new file in the library-directory. Server side preview seems fine (various slides with various fonts). Have not yet had time to investigate.

**Comment by dasgarner** [comment]
We've had a few others reporting issues with this, but haven't been able to isolate the problem. The fonts.css file should be in the `media` table and in the CMS library (and edited when new fonts are added). It should then be in the media inventory call on every Display.

**Comment by MedusaDelft** [comment]
I'm not sure what the 'media inventory call' on the client is, but I suspect the  requiredFiles.xml.  I have not yet started my client. I've had a look at the contents of the library-directory on the client.
In the requiredFiles.xml  (and the cacheManager.xml) a reference to 'fonts.css' is not there. After starting the client, it's stil not there.

The file is present in the library-directory on the CMS.

When I look in the media table the record for 'fonts.css' is there and seems fine, except for 1 thing. The file size in the library-directory on the CMS-side is 481  where the record in the table indicates  488.

I guess that's where it goes wrong!

**Comment by MedusaDelft** [comment]
Hum.... I've corrected the file size in the table and removed the MD5. Edited a font to get a new MD5 (filesize is not changed). Restarted my client, but still no fonts.css on the client-library or in the requiredFiles.xml

**Comment by dasgarner** [comment]
[L150](https://github.com/xibosignage/xibo-cms/blob/develop/modules/font.module.php#L150)

Should be:

``` php
$media->addModuleFile('modules/preview/fonts.css', 0);
```

Although I am a bit confused how this ever worked.

**Comment by supportreq** [comment]
Hi @MedusaDelft @dasgarner can you help me with the design?

How do I get the temperatures for the next 4 days? If you can share the template it will be great!

**Comment by MedusaDelft** [comment]
I've created a pull-request for the template you presented first. But it does contain some javascript and  a link to google-fonts and lacks the background (which you can download, see comment above).

**Comment by supportreq** [comment]
@MedusaDelft the script in HTML preview looks fine. But on the Android Client the weather symbol covers more than 90% of the screen

**Comment by MedusaDelft** [comment]
Most android browsers are terrible in supporting css/html5. I'm sorry. Please adjust the font-size for the weather symbol in css.

**Comment by dasgarner** [comment]
I've added a new type of substitution for this (the original issue). You can now use [time|FORMAT] where format is the format mask for the date you want.

To achieve the localised date name - you would add [time|D] to the template.

**Comment by guidoaguiar** [comment]
@MedusaDelft , hey thanks for all your help given here, 

also i would like to ask for the code to recreate the orange theme you have posted.

its possible?

**Comment by dasgarner** [comment]
It is included in Xibo from 1.7.3 onwards - the orange background isn't there, but you can use any background you want under the forecast (it is just the layout background).

Please discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
