### ISSUE TITLE
Configuration > CMS Theme setting

### ISSUE THREAD

**Issue by nagyrobi** [xibosignage/xibo#212]
Please make a dropdown with a selectable list of the installed themes. Currently one has to type in the theme name, but has no clue, looking at the interface, what else is available on the system.

**Comment by dasgarner** [comment]
We need special consideration here for service providers who may have a pre-set theme (or themes) that they want available to their users.

Service providers could always grey out the theme selector, but they may want to offer a selection.

**Comment by nagyrobi** [comment]
Use a php array in the config file, which would list which themes would appear in the selector dropdown. Service providers can edit this config as they want.

**Comment by laercionit** [comment]
Pretty cool this functionality.
Thinking about it, I think great for service providers have the option to set the theme settings.

I imagine that in the future we could have various themes and give the user option to choose, or service providers set the theme in the user registration.
