### ISSUE TITLE
Multiple RSS Feeds in a Region - Single Item Horizontal Slide Transisition

### ISSUE THREAD

**Issue by kevinrsalisbury** [xibosignage/xibo#213]
Is is possible on the subject feature to have the first RSS item (single item) display this way (via Horizontal Slide)? At the moment the first RSS item appears with no animation.

**Comment by kevinrsalisbury** [comment]
Nevermind. I see I had to enable in/out transitions - which appear to be supported by Android clients?

**Comment by kevinrsalisbury** [comment]
I will close the issue for now, although single regions that have multiple RSS feed tickers still seem to have poor transistions regardless of setting. As a new user, it could be somthing I am doing wrong - but I think it would be nice future feature to have the transisition effect apply to the first RSS item if desired.

**Comment by dasgarner** [comment]
I think that in/out transitions would solve the issue (they were supported by the ubuntu and android player), but I will also look into ways of making that happen within the ticker itself so that it would be supportable on windows.

Maybe adding an empty item at the beginning would do the trick.
