### ISSUE TITLE
2.3.0 install fails on MySQL 5.7

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#2133]
2.3.0 install fails on MySQL 5.7 with the error

`SQLSTATE[HY000]: General error: 1364 Field ‘edit’ doesn’t have a default value`

Error comes from https://github.com/xibosignage/xibo-cms/blob/175ca0320ab6d77e1291126c62b6e93b9ee250a7/db/migrations/20191205180116_add_playlist_dashboard_page_user_migration.php#L59-L65

Need to set `edit` and `delete` on those three inserts.

OP: https://community.xibo.org.uk/t/new-install-xibo-error-sql-during-install/22022

**Comment by dasgarner** [comment]
This also seems to effect mysqld 5.6.35

logs from our standard container:

```
cms-db_1 | 2020-02-25 15:01:50 0 [Note] mysqld (mysqld 5.6.35) starting as process 1 ... 
cms-web_1 | == 20191205180116 AddPlaylistDashboardPageUserMigration: migrating
cms-web_1 |
cms-web_1 | In PdoAdapter.php line 134: 
cms-web_1 |
cms-web_1 | SQLSTATE[HY000]: General error: 1364 Field 'edit' doesn't have a default value 
```
