### ISSUE TITLE
CMS Transfer to another CMS: entering the URL of current CMS issue.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2134]
Issue: When using the Transfer to another CMS funtionality, you can enter the URL and Key of the CMS the Player is already connected to. This can cause the Player to become stuck in a loop. 

Suggestion: A check that would ensure this is not possible.

**Comment by dasgarner** [comment]
This check should be handled player side as its a valid use case to enter the same CMS URL (in the event you are moving your CMS instance, you'd want to send the new address, which will become the same address after you've moved it, and it needs to be like that to give the players time to move).
