### ISSUE TITLE
Widgets are missing in Designer when using Safari Browser. [Mac only]

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2137]
CMS Version: 2.3.0

Safari Browser versions: 12.2, 13.0.4

Issue: When using Xibo CMS, most of the Widget tiles are not appearing in Designer.

**Comment by auchri** [comment]
Hi,

is it possible to fix this problem in 2.3.3? It's very annoying and I hope this can be fixed before the next major release.

**Comment by dasgarner** [comment]
We're very happy to take a PR that fixes the issue in `release23` or in `develop` and then include in accordingly.

Unfortunately none of our team have a Mac and therefore its very difficult for us to fix it.
