### ISSUE TITLE
Script/automate the install.php configuration steps

### ISSUE THREAD

**Issue by snibble** [xibosignage/xibo#214]
I've been playing around with creating a Vagrantfile that can stand up a VM with a running and ready-to-go Xibo CMS server install from scratch. I managed to get through all of the prerequisite installs, configuring the database, and downloading and installing Xibo (1.7.1). What I wind up with is an install that redirects to index.php, ready for the user to walk through the configuration steps.

What I want next is to automate those configuration steps so that I wind up with a ready-to-go (but empty) Xibo server at which I can point clients and get the default layout shown (ideally, without ever touching the server). This seems plausible because all of the configuration steps are entering data that I already know or have the opportunity to make up on-the-spot.

Initial experiments make me think most of the trick is replacing install.php with setup.php...but I suspect that there will be a few additional gotchas that crop up along the way (like encrypting passwords? ...or that "SECRET_KEY" that appears in settings.php?).

Longer-term, it might be nice to even pre-populate the CMS with a few bits of media, a layout, a schedule, etc. And maybe after I get the feel for this, I'll find it fits better as a puppet or chef implementation. But, for now, it's just an inline shell script in the Vagrantfile.

Consider this an invitation to collaborate. Stop by and see me at https://github.com/snibble/xibo_vagrant.

**Comment by dasgarner** [comment]
This would be useful for me :smile: at the moment my VagrantFile means I have to run through the install script myself.

The SECRET_KEY is used to salt various hashes, just needs to be random - encrypting passwords is handled by MD5 and setting CSPRNG = 0 in the user table, when they log in for the first time they will be converted to a proper password hash.

You'd have to generate `settings.php` and delete `install.php`.

Layouts that need to be added can be done so via adding the exported layout.zip file to the theme/default/layouts folder.

Not sure how you may want to achieve adding bits of media / schedules.

**Comment by snibble** [comment]
Yeah, getting settings.php swapped for install.php gets most of the job done, I think. I still need to find where a few things live (like the library path and the server key).

**Comment by dasgarner** [comment]
A fresh install gives you a "user" record for xibo_admin, which you will want to update the username/password for (the password is just a MD5 hash until the first time that user logs in, then it is swapped for a more secure hash)

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
