### ISSUE TITLE
WebOS license versions shown in the CMS need to be renamed as 'WebOS 1.8 R19 ' instead of ' lg 1.8 R19 ' 

### ISSUE THREAD

**Issue by Coccinell12** [xibosignage/xibo#2140]
WebOS license versions shown in the CMS need to be renamed as 'webOS 1.8 R19 ' instead of ' lg 1.8 R19 '  to match the version titles in the Xibo website> downloads section.

**Comment by dasgarner** [comment]
@PeterMis - I don't see any elegant way to do this, other than an if statement for the `clientType`
