### ISSUE TITLE
Dataset View: Rows per page issue.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2177]
CMS Version: 
2.3.2

Issue: 
Create a Dataset with more than one column. For my test I created 2 String Value Columns. Add data to the Rows for those Columns. Next add a Dataset View Widget to a Layout and use that Dataset with it, making all columns available. If you set `Rows per Page` to a number other than 0, this causes the row data to join together, no longer leaving space between each row entry.

Note: When 
- `Rows per Page` is set to 0, the issue does not occur.
- Possible workaround: If you keep `Rows per Page` set to 0 but set the number of Rows you wish to display using the `Upper Row Limit` option, the items remain spaced apart.

**Comment by dasgarner** [comment]
@maurofmferrao I seem to recall you had a CSS fix for this?
