### ISSUE TITLE
Resolutions enabled - deleted!

### ISSUE THREAD

**Issue by andyblackham** [xibosignage/xibo#218]
When managing resolutions there is an 'Enabled' tick box.
Editing a resolution and unpicking this, seems to delete the resolution.

This is not normal enabled / disabled behaviour.
I would expect the resolution to remain but not have an enabled tick and not be available for add template use.

Disable is not delete!

**Comment by dasgarner** [comment]
The Grid needs a filter form to show disabled resolutions.
