### ISSUE TITLE
error in display log

### ISSUE THREAD

**Issue by andyblackham** [xibosignage/xibo#219]
I'm getting this hundreds of times in my display log (I only have one display right now.

37587	2015-02-10 21:53:14	Client	onTrimMemory	Trim Request [level=20] at Total:384. Used: 21. Device Total: 21. Device Free: 0

what does it mean?
thanks

**Comment by dasgarner** [comment]
Its an Android issue - we are sorting it with the next release.

It means your device is reporting that it is low on memory (which may or may not be true)

**Comment by andyblackham** [comment]
Thanks, will that be soon?

I’m on the springsignage site buying my first client!
Will I need to pay for an update?
andy

**Comment by dasgarner** [comment]
Andy - best ask us directly - we like to keep the open source bit separate if we can :smile:
