### ISSUE TITLE
Layout Designer: Implement the Interactive Drawer

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2190]
When a Layout is downloaded to the Player and shown, it must be sure that all of its interactive elements are also downloaded. Xibo needs to have a way for these to be attached to a Layout at design time, and served in the XLF, import/export and XMDS.

We could have an area in the designer which would “open out” like a drawer from the side, and you could drag/drop Widgets into it as you do for normal Regions.

**Comment by maurofmferrao** [comment]
The empty drawer message isn't being shown, the fix is to pass the layout's drawer to the render template in drawer.js

`const html = drawerTemplate({
        drawer: lD.layout.drawer,
        widgets: widgetArrayFiltered,
        readOnlyModeOn: readOnlyModeOn,
        searchQuery: self.searchQuery,
        trans: drawerTrans
    });`
