### ISSUE TITLE
Xibo 1.7.5 broadcast address not valid 

### ISSUE THREAD

**Issue by thelinux20** [xibosignage/xibo#2193]
![brd](https://user-images.githubusercontent.com/63676526/80211752-caa5d900-8625-11ea-9f36-65a98a92f57e.png)

can any one help with that please what is the problem.

Thanks

**Comment by dasgarner** [comment]
Hi!
GitHub is for verified bugs only - please can you ask your question on the Xibo Community - as soon as anyone has time to answer they will get back to you on there.
Best wishes,
Dan

**Comment by thelinux20** [comment]
hey sir i asked

**Comment by thelinux20** [comment]
I dig a little and i found that it's a bug

**Comment by thelinux20** [comment]
because i use apache2 as web server and nginx as proxy.
when display added it added with the same address duplicated. so i go to my database and i delete one ip and then it's work. so please how can i store the ip of display just one's.
Hope That I make It clear 
Thanks.

**Comment by alexharrington** [comment]
Xibo 1.7 is no longer developed or supported. You should upgrade, or look at configuring your webserver to pass through the correct IP address through to Xibo.

**Comment by thelinux20** [comment]
I understand that is no longer supported. But can you please show me how to do it if you can i really in miss with that error. 

And Thanks

**Comment by alexharrington** [comment]
I'm afraid I can't. You would need to look in to that yourself (and post in the appropriate place).

**Comment by thelinux20** [comment]
ok thanks so basically if my root directory is   /home/site/web/sign.soft.com/public_html
I add this ling to my nginx conf

 location /home/site/web/sign.soft.com/public_html {
        proxy_pass  http://143.250.5.51:8080;
   }

 Please confirm if you can

And Thanks again.

**Comment by alexharrington** [comment]
I'm afraid I can't. You would need to look in to that yourself (and post in the appropriate place).

**Comment by dasgarner** [comment]
The project uses this for bug tracking, not support - please direct your question into the Xibo Community.

Many thanks.
