### ISSUE TITLE
Link to the date format manual section from Global Settings

### ISSUE THREAD

**Issue by auchri** [xibosignage/xibo#2199]
Hello,

I did not found an existing issue, so I create a new one :)
CMS version: 2.3.1

- Navigate to Schedule -> Add Event
- Set the end time to e.g. May 6, 2020
![image](https://user-images.githubusercontent.com/5092164/80963593-8c6f9d00-8e0f-11ea-9bd5-c924bc3f3c93.png)

Expected value of the input field: `06.05.2020`
Current value: `0606.0505.2020202020202020`

It seems that the values of the day, month and year are added for every letter of the date format (e.g. YYYY -> `2020*2020*2020*2020`)

![image](https://user-images.githubusercontent.com/5092164/80963316-fcc9ee80-8e0e-11ea-8b13-f16e7619ecfb.png)

The same for the time field:
![image](https://user-images.githubusercontent.com/5092164/80963363-1408dc00-8e0f-11ea-8682-3b4cf5621b8e.png)

and also the same for the beginning fields.

Date format in the settings:
![image](https://user-images.githubusercontent.com/5092164/80963449-3c90d600-8e0f-11ea-8bdd-eb4bc2c003ed.png)

**Comment by dasgarner** [comment]
Thanks for your report - we use PHP date format - see: https://xibo.org.uk/docs/setup/date-format-php

So in your case the correct format mask is `d.m.Y H:i`

**Comment by auchri** [comment]
Thank you for your answer!

Maybe that link should be added to the setting, so that everyone knows which values are valid :)

**Comment by dasgarner** [comment]
Sure, good idea! thanks
