### ISSUE TITLE
Mail list

### ISSUE THREAD

**Issue by cjohnert** [xibosignage/xibo#222]
Sorry if this is a dumb question, but is there a mail list that I can get on to be notified when there are new versions of Xibo released?  I find that I frequently miss releases.

**Comment by nagyrobi** [comment]
+1 for this

**Comment by dasgarner** [comment]
We only have the RSS feed and the twitter account (xibosignage) at the moment... unfortunately mailing lists are too expensive (there are a LOT of users)

**Comment by cjohnert** [comment]
Thank you for the response ... I will subscribe to your RSS feed.?



Chris Johnert
Tech Office ITA
x5454
________________________________

**Comment by dasgarner** [comment]
Sure - http://xibo.org.uk/feed/
