### ISSUE TITLE
Set display use Global Timeout - Not Save

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#223]
Hello Guys, I hope to work with the information below to help identify the problem.

I have analyzed the background version 1.7 along with the APK for this release.

I noticed that the display settings relating to the Use Global Timeout are not being applied. The system marks the device as offline without taking consideration of the parameter. This option also is not being saved when you click save.

Also we can not set the timeout to manually by the display when not want to use the global parameter.

I realized that the client uses the parameter set in profile - Collect interval perfectly, but ranks as offline or not, ignoring the global timeout parameter. When this occurs the client presents the msg to Enable Register Error due.

This msg is removed only to reopen the client or change the default layout.

Thank you for agility and always hope these evidences help in some way.

**Comment by dasgarner** [comment]
I hope the issue is only that the option is not being saved when you click OK - therefore its always OFF and therefore its always not tested.

**Comment by laercionit** [comment]
Dar, did not realize tests in routine maintenance yet.
I realized that this not saving this option, click OK.

Also I noticed that the display is receiving the classification offline lasting less than the global timeout parameter., Ignoring the parameter that was set in the global settings. My configuration with this Timeout 30 minutes, just long events in offline alerts are generated.

This marking and offline based on the collect interval display profile.

Could you please correct this? This will be a major headache for my support team, generate false offline events will be very complicated.
