### ISSUE TITLE
Dashboard Bandwidth Graph inaccurate/missleading when Displays have been deleted recently while BW is exceeded 

### ISSUE THREAD

**Issue by Coccinell12** [xibosignage/xibo#2230]
If the Bandwidth allowance has been exceeded and Displays are deleted, the Dashboard graph doesn't really reflect that the Bandwidth is consumed as per example attached.  The last month indicates Bandwidth available although there is none, the Bandwidth consumed by the recently deleted Displays doesn't appear. 

![image](https://user-images.githubusercontent.com/10400067/82346402-507f2f00-99ee-11ea-98d5-c73b5ce37517.png)

**Comment by dasgarner** [comment]
It would be nice if we could show the deleted displays as a grey stack

**Comment by dasgarner** [comment]
As its a summary chart we will just include the deleted displays the overall count, more statistics breaks that out by deleted/not deleted.
