### ISSUE TITLE
How to communicate with Xibo server using API XiboAPI ?

### ISSUE THREAD

**Issue by Pavi-thra** [xibosignage/xibo#224]
We are planning to develop a front end for server side... Can u give us some idea on API to communicate
with server for changing the layout programmatically ?

**Comment by dasgarner** [comment]
The only documentation we have on the API is here: http://xibo.org.uk/manual/en/api.html and I have written a basic example in PHP here https://github.com/dasgarner/xibo-example-api

**Comment by Pavi-thra** [comment]
thank u for ur reply...we r trying that front end using .net ...can u help us how to use the api ?

**Comment by dasgarner** [comment]
Sorry, we don't have any .NET wrappers for the API at present. If you are after commercial services then you need to look in the [Xibo Directory](http://xibo.org.uk/directory)
