### ISSUE TITLE
restart the client if error rendering ?

### ISSUE THREAD

**Issue by pb7892** [xibosignage/xibo#225]
Hello everyone!

I wondered womething :

Some of pyclient users (1.4 on 10.04 or 1.6 on 12.04, it is the same) are aware on that "error rendering + re-rendering - skipping" issue which occures html contents - embedded, pages, or even text, datasets or ticker content - is not displayed some time.

There is nothing to do about that as it comes from berkelium bugs.

But is there a way, in the XiboClient.py or anywhere else, to make the client just restart when this error occures ?

My idea is that it could be better to see a few second of the splash than an empty region.

**Comment by alexharrington** [comment]
You could certainly patch it to do that. That error message just means the client is retrying though (and it will happen nearly every time you show web/text/HTML etc) so I think you'll find it just restarts constantly.

The client as it stands is deprecated and there won't be any further development on it, so if you'd like to patch it yourself you are very welcome but we won't be releasing a new version.
