### ISSUE TITLE
Playlist Timeline: Widget list is partially obscured.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2254]
CMS version: 2.3.4

Issue: open a Playlist Timeline. At the bottom of the page, the Widgets are partially obscured, only half of the Widget tile is shown.

**Comment by maurofmferrao** [comment]
That behaviour happens when using FR as language, which creates a module with a wider name ("Vue d'une base de données"), which brakes the height of the module list. The names need to be trimmed and maybe shown in a popup on hover.
