### ISSUE TITLE
Rendering issue when usign pt-br language

### ISSUE THREAD

**Issue by tcpfm** [xibosignage/xibo#2258]
Hello Xibo Team,

We are facing an issue when using pt-br as a default language on our Xibo instance version 2.3.4.
As you can see on the attached ![screenshot](https://user-images.githubusercontent.com/46029023/84403784-77d7af00-abdc-11ea-9a15-ae22bb7ab6f3.png), under the "Design" layout page, the bottom buttons are out of the screen and some others are rendering incorrectly, a possible css issue?!

Please, let me know if you need some other information about this issue!

Thank you and Best Regards,

**Comment by dasgarner** [comment]
Thank you for your report - this might be related to #2125 
@maurofmferrao please can you take a look?

**Comment by maurofmferrao** [comment]
It is indeed related to #2254, it will be fixed for 2.3.5 ( and 3.0 alpha/beta versions )
Thank you for the report @tcpfm

**Comment by tcpfm** [comment]
Thank you so much for your fast reply!
