### ISSUE TITLE
RSS Feed not showing

### ISSUE THREAD

**Issue by robertnl1985** [xibosignage/xibo#226]
hello,

i have a rss feed in xibo version 1.7.0 but it wil not showing my feed. i use this code in the rss feed but it wil not showing.

<p>
	<span style="font-family: trebuchet ms,helvetica,sans-serif"><span style="color: #000066">[Title] - [Date] - [Description] </span></span></p>

**Comment by MedusaDelft** [comment]
I had the same problem. Check the client-side. It looks like the MD5-file check fails (resulting in 0-bytes filesizes). I've manually updated these files and it works. So I guess it has something to with uploading (binary/ascii) the files or the MD5-signature.

**Comment by dasgarner** [comment]
@robertnl1985  does the feed show in the Layout Designer when you are using the CMS?

Please **don't** manually update player side files :smile:

**Comment by robertnl1985** [comment]
hi all,

when i do showing preview the rss is not working in 1.7.0 we have a clean install of xibo i have delete the old files from de client but it is not working.

**Comment by robertnl1985** [comment]
@dasgarner  no i using the rss option for this: [Title] - [Date] - [Description]

**Comment by dasgarner** [comment]
But does the feed show in the Layout Designer?

If not - can you run through the report fault page and put the resulting file somewhere we can look at it?

**Comment by SJCommanda** [comment]
We stopped using twitter feeds last year when twitter changed something in its RSS feeds.
It has not worked since. Have they changed it back?

**Comment by robertnl1985** [comment]
in embedded mode it is working well only in exsist xibo clients but when i install a new client from xibo 1.7.0 then is only shows the name of the twitter account.

**Comment by dasgarner** [comment]
Sorry, but what you have said makes no sense. Please clearly state 1 problem at a time and we will help resolve it.

Your RSS feed - does it work in the Layout Designer?

**Comment by robertnl1985** [comment]
it is working in the preview layout but not on the client self

**Comment by dasgarner** [comment]
OK great - I understand now.

Can you try going to the CMS -> Modules -> Verify All (button top right), then wait for the Display to get a Tick in the Status.

Does that help?

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
