### ISSUE TITLE
Suggestion: Extension check when uploading a file to CMS

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2264]
Issue: If you upload a file type that is not a valid extension for any of the modules, the file will continue to upload, then return the message "Extension <extension> does not match any enabled Module". This can cause a long wait for confirmation that it will not successfully upload if the file is large or the network connection is slow.

Suggestion: Some form of pre-upload check that will confirm if the format is listed as a valid extension in a module.

**Comment by dasgarner** [comment]
If we can listen to blueimp and detect when a file has been loaded into the form, we could run something like [muxjs](https://github.com/videojs/mux.js/) on the file to get various bits of information from it.

This would let us detect what type of file it is, what codec is it and ultimately whether or not that is supported.

If this isn't a go-er, we ought to be able to get the file name before we upload the file and do a basic extension check on it.
