### ISSUE TITLE
Feature: Schedule Time Disconnected reports

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2266]
Feature: Add the ability to schedule a Time Disconnected report via CMS. This report should also have the option to be sent to email addresses. The report can also be exported from CMS, which is not currently possible.

**Comment by dasgarner** [comment]
This needs more clarification

**Comment by dasgarner** [comment]
@ifarzana I think this is already done as part of the restructuring?

**Comment by ifarzana** [comment]
yes, that has been included in the latest cms version. The report is on develop.
