### ISSUE TITLE
Reports restructuring

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2268]
All of our scheduled reports are currently in the "Proof of Play" menu. As we expand our reporting capabilities it would be better to restructure this menu system so that we can include reports which are not specific to proof of play.

Suggest that the reports menu is changed to look like:
 - All Reports
 - Report Schedules
 - Saved Reports

In All Reports we show the card style view that we currently have, but with all other reports too.

Suggest we also need a category for reports so that we can organise and filter this page by category.

**Comment by dasgarner** [comment]
We should also assign a feature (i.e. a page) to each report to decide which permissions are required to see it.

**Comment by ifarzana** [comment]
Schema Version in Saved Report: We provide schema version 1 to reports that were generated before 3.0.0-alpha. New Saved Report will have schema Version set to 2
