### ISSUE TITLE
Error to change scheduled layout 

### ISSUE THREAD

**Issue by Jonatanestam** [xibosignage/xibo#2274]
Hello, 
A few weeks ago I upgrade Xibo CMS 2.3.0 to 2.3.4
Before everything worked fine, but now I can't edit Scheduled Layout (If Dayparting is Always).
A can create a scheduled Layout, but once schedule is created, I can't edit it, a message appears:

**“Unexpected Error, please contact support”** 

**I have activated debug mode and these are errors:**

``` /var/www/html/mydomain.com/lib/Middleware/Actions.php(150): Slim\Middleware\MethodOverride-&gt;call()
 /var/www/html/mydomain.com/lib/Middleware/Theme.php(36): Xibo\Middleware\Actions-&gt;call()
 /var/www/html/mydomain.com/lib/Middleware/WebAuthentication.php(131): Xibo\Middleware\Theme-&gt;call()
 /var/www/html/mydomain.com/lib/Middleware/CsrfGuard.php(63): Xibo\Middleware\WebAuthentication-&gt;call()
 /var/www/html/mydomain.com/lib/Middleware/State.php(121): Xibo\Middleware\CsrfGuard-&gt;call()
/var/www/html/mydomain.com/lib/Middleware/Storage.php(48): Xibo\Middleware\State-&gt;call()
 /var/www/html/mydomain.com/lib/Middleware/Xmr.php(37): Xibo\Middleware\Storage-&gt;call()
/var/www/html/mydomain.com/vendor/slim/slim/Slim/Slim.php(1300): Xibo\Middleware\Xmr-&gt;call()
/var/www/html/mydomain.com/web/index.php(127): Slim\Slim-&gt;run()
{main}",,DEBUG
77,672b6fc,"2020-06-24 17:44:54",WEB,/schedule/1392,PUT,"SQLSTATE[01000]: Warning: 1265 Data truncated for column 'recurrence_type' at row 1 Exception Type: PDOException",,ERROR
78,672b6fc,"2020-06-24 17:44:54",WEB,/schedule/1392,PUT,"Storage rollback.",,DEBUG
79,672b6fc,"2020-06-24 17:44:54",WEB,/schedule/1392,PUT,"Request stats: {
    &quot;default&quot;: {
        &quot;select&quot;: 11
    },
    &quot;log&quot;: {
        &quot;insert&quot;: 13
    },
    &quot;length&quot;: 0.46667814254760742,
    &quot;memoryUsage&quot;: 9210176,
    &quot;peakMemoryUsage&quot;: 9280296
```

**My environment**
Xibo CMS Version: 2.3.4
PHP v7.2.19
Operating System: CentOS Linux release 7.6.1810.2.el7.centos.x86_64
Linux Kernel: 3.10.0-957.12.1.el7.x86_64
CPU: Intel® Core™ i7 CPU 870 @ 2.93GHz
RAM: MemTotal 16163660 kB

php.ini
upload_max_filesize = 5000M
post_max_size = 1000M
max_file_uploads = 50
memory_limit = 8000M
max_execution_time = 9400
max_input_time = 9400

**Comment by dasgarner** [comment]
We fixed an issue in 2.3.4 where it was possible to have a recurring schedule which then got set to an always daypart #2239

Essentially the fix sets recurrence type to an empty string on edit, if it is an always daypart.

I think your version of MySQL would rather this was set to NULL instead of empty string. Can you try the attached patch?

**Comment by Jonatanestam** [comment]
I have tried patch , unfortunately it doesn't work. 

**These are errors:**
`4935,3ff6404,"2020-06-29 10:56:43",WEB,/schedule/2113,PUT,"Checking permissions against the logged in user: ID: 6, Name: jonatan, UserType: 1",,DEBUG`
`4936,9b35e9f,"2020-06-29 10:56:43",WEB,/schedule/data/events,GET,"Parsing event dates from 1591002000 and 1591002020",,DEBUG`
`4937,3ff6404,"2020-06-29 10:56:43",WEB,/schedule/2113,PUT,"SQLSTATE[01000]: Warning: 1265 Data truncated for column 'recurrence_type' at row 1#0 /var/www/html/mydomain.com/lib/Storage/PdoStorageService.php(242): PDOStatement-&gt;execute(Array)`

`#1 /var/www/html/mydomain.com/lib/Entity/Schedule.php(786): Xibo\Storage\PdoStorageService-&gt;update('\n          UPDA...', Array)`
`#2 /var/www/html/mydomain.com/lib/Entity/Schedule.php(624): Xibo\Entity\Schedule-&gt;edit()`
`#3 /var/www/html/mydomain.com/lib/Controller/Schedule.php(1451): Xibo\Entity\Schedule-&gt;save()`
`#4 [internal function]: Xibo\Controller\Schedule-&gt;edit('2113')`
`#5 /var/www/html/mydomain.com/vendor/akrabat/rka-slim-controller/RKA/Slim.php(79): call_user_func_array(Array, Array)`
`#6 [internal function]: RKA\Slim-&gt;RKA\{closure}('2113')`
`#7 /var/www/html/mydomain.com/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)`
`#8 /var/www/html/mydomain.com/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route-&gt;dispatch()`
`#9 /var/www/html/mydomain.com/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim-&gt;call()`
`#10 /var/www/html/mydomain.com/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash-&gt;call()`
`#11 /var/www/html/mydomain.com/lib/Middleware/Actions.php(150): Slim\Middleware\MethodOverride-&gt;call()`
`#12 /var/www/html/mydomain.com/lib/Middleware/Theme.php(36): Xibo\Middleware\Actions-&gt;call()`
`#13 /var/www/html/mydomain.com/lib/Middleware/WebAuthentication.php(131): Xibo\Middleware\Theme-&gt;call()`
`#14 /var/www/html/mydomain.com/lib/Middleware/CsrfGuard.php(63): Xibo\Middleware\WebAuthentication-&gt;call()`
`#15 /var/www/html/mydomain.com/lib/Middleware/State.php(121): Xibo\Middleware\CsrfGuard-&gt;call()`
`#16 /var/www/html/mydomain.com/lib/Middleware/Storage.php(48): Xibo\Middleware\State-&gt;call()`
`#17 /var/www/html/mydomain.com/lib/Middleware/Xmr.php(37): Xibo\Middleware\Storage-&gt;call()`
`#18 /var/www/html/mydomain.com/vendor/slim/slim/Slim/Slim.php(1300): Xibo\Middleware\Xmr-&gt;call()`
`#19 /var/www/html/mydomain.com/web/index.php(127): Slim\Slim-&gt;run()`
`#20 {main}",,DEBUG`

**Comment by dasgarner** [comment]
Which version of MySQL are you using please? I will create a test locally with that same version and see if I can recreate.

**Comment by Jonatanestam** [comment]
Thanks for your attention.

**mysql  Ver 15.1 Distrib 10.4.8-MariaDB, for Linux (x86_64)**

**Comment by dasgarner** [comment]
I have just tried with MariaDB 10.4.8 and I can edit Schedule without any errors. It did indeed error with the message you provided without the patch applied.

I think you might not have applied the patch?

**Comment by Jonatanestam** [comment]
Yes, it's true.
I'm sorry,  I only applied patch  for #2239.
Now, I applied patch for #2274 and all works fine.

Many thanks.
