### ISSUE TITLE
Copyright not showing

### ISSUE THREAD

**Issue by waarsenburg** [xibosignage/xibo#228]
When configuring a ticker, I want to add Copyright text. However, the text never appears as the last item in the feed, as the config screen suggests.
I use a RSS-feed, Duration 4, Effect Marquee up, Template is Prominent title with description and name separator, speed 3, Text Direction LTR, Number of Items 15, Take items from the start of the feed, Duration is per item ticked, update interval 5 mins, and of course Copyright text defined.
The CMS has version 1.7.1, player is Windows 1.7.0

**Comment by kevinrsalisbury** [comment]
I have seen this same issue using different template, effects and different timing. I wonder if it is designed for a url instead of text?

**Comment by dasgarner** [comment]
hmm, interesting... it has somehow been left off when we implemented the [Copyright] template tag to extract the copyright from the feed itself.

Marked as a bug.
