### ISSUE TITLE
Shell Commands Widget: Changing type does not clear previous settings.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2288]
CMS version: 2.3.5

Issue: Create a Shell Command Widget in your Layout. Enter a command into any of the command boxes for Linux/Android, Windows, webOS or Tizen. Save the Widget. Now edit the Widget again but this time choose a stored command and save to confirm. The manual command written initially will still be stored in the widget settings.

Note: You can see the command listed in the preview window for Layout designer, even though the Widget is set to a stored command.

**Comment by dasgarner** [comment]
Instead of clearing the stored commands, I've adjusted the preview to show the command listed if selected. Reason being, it is quite handy to have the existing commands persisted if the user changes their mind.
