### ISSUE TITLE
android_licence.php

### ISSUE THREAD

**Issue by heinola** [xibosignage/xibo#229]
Ben getting this error in apache2 that Ossec is giving me a level 2 alert off and on..
########################################
OSSEC HIDS Notification.
2015 Feb 10 09:42:21

Received From: xmds3->/var/log/apache2/error.log
Rule: 1002 fired (level 2) -> "Unknown problem somewhere in the system."
Portion of the log(s):

[Tue Feb 10 09:42:20.480525 2015] [:error] [pid 27489] [client 192.168.1.103:35767] script '/var/www/html/xibo/android_licence.php' not found or unable to stat
##########################################

I checked for this android_licence.php at the DIR indicated and there is no file by this name.

What should I be looking at for a fix

**Comment by dasgarner** [comment]
You can create an empty file there called android_licence.php and in it put:

``` php
<?php
exit();
?>
```

**Comment by heinola** [comment]
pew pew fixed  ty for the info
just wanted to clean up the logs a bit :)

**Comment by dasgarner** [comment]
Great - we might ship an empty file in the release. Thanks for the info.
