### ISSUE TITLE
Some repeat Event schedules do not fit the day view calendar

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2294]
CMS Version: 2.3.5, 1.8.13

Issue: Create the following events:

Event 1:
- Start at 00:00
- End at 03:00 (same date as start date)
- Repeat every 3 hours.

Event 2:
- Start at 00:30
- End at 01:00
- Repeat every 1 hour

If you check the day view calendar, the repeats begin to fall out of sync with the 30 minute time rows. This causes the events to be shown beyond the daily calendar.

**Comment by dasgarner** [comment]
Sorry for the late assign @maurofmferrao - could you take a quick look to see if there is anything we can do about this?

**Comment by dasgarner** [comment]
I thought I had it, but I didn't :-)

This is to do with the way the items are floated and stacked- the margin-top is respective to the item stacked above it once they reflow at the page width.
