### ISSUE TITLE
Time Disconnected Summary report does not export well

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2303]
This is a problem with mPDF not rendering the `div` inside the `table`.

Multiple workarounds have been tried - including using another table, different progress bars, and eventually `<progress>` gives a better result, but cannot be styled.

We either need to get `<progress>` styling correctly, or look at some alternatives.

One idea would be to provide a PHP endpoint which generates a gauge on the fly given a percentage and two colours (this would then be referenced in an `<img>`).

Another idea is to ship an image with has a progress bar for every occasion (1 to 100) and set that as the background image on the `td` (if that is possible).

**Comment by dasgarner** [comment]
This has been largely solved by swapping the naming of the report over to "Time Connected" and reversing the logic for all the bars so that they show time connected. The `<progress>` element gives us the below, which we can't style in mPDF, hence the need to reverse the report.

**Comment by dasgarner** [comment]
Same root cause for #2301

**Comment by ifarzana** [comment]
#2301 is a duplicate
