### ISSUE TITLE
Tags - improve the API response

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#2306]
As it stands we don't load any objects to which the tag is assigned to on GET /tag call, which should be done perhaps if the corresponding value for embed parameter is passed with the request.

We may also need to look at the format in which the Tag options come back from API.

**Comment by dasgarner** [comment]
I don't think embedding those objects would be wise, instead we should hide those properties in the API response. Reason being that we can't page those properties and could potentially end up with an enormous response (imagine a tag which is on 1000 Layouts).
