### ISSUE TITLE
2.3.5 - Invalid layouts sent to Players

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#2309]
If you create a layout that has a single region on it, and in the region put one media item with an expiry time in the past, the CMS sends to the Player an XLF containing the region node, but no media nodes.

The CMS recognises that the layout is invalid in the status, but appears to continue to send it to the Player.

**Comment by dasgarner** [comment]
Having reviewed the logic for this, I think it is a problem which has been solved by #2281
