### ISSUE TITLE
Cannot find playlist issue

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2312]
CMS Version: seen on 2.3.6 but could be an issue on 1.8.13

Issue: Some layouts cannot be deleted, opened in layout designer, copied or exported. When attempting to do any of the mentioned actions, an error is returned stating "cannot find playlist". 

Notes: This has been seen on layouts with tick, cross and cog statuses. Some layouts with this issue will still have a duration for the layout, while others do not.

**Comment by dasgarner** [comment]
In the examples provided the user who owns the Playlist has been deleted. Perhaps this is a hangup from #2061 ?

I think it is safe in the case of Playlists to LEFT OUTER JOIN with the user table, so that a super admin should be able load and cascade permissions down.
