### ISSUE TITLE
Interactive Feedback snagging

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2317]
- Can "Region" have a title? "Target Region"
 - Help text changes (Natasha to provide)
 - Action for a Widget - Web Hook, missing trigger code

**Comment by Tashamy** [comment]
Target (help text) - If your Widget is a Shell Command you can select to target 'Screen' to run the command without affecting any Regions. For all other Widgets select 'Region' as target.

**Comment by Tashamy** [comment]
When Trigger Type is Touch/Click on Add Action for Layout form, could the Trigger Code be hidden?

**Comment by Tashamy** [comment]
Action for a Region - Web Hook missing Trigger Code

**Comment by Tashamy** [comment]
Could we have separate forms for Add Action for Layout / Region / Widget for different help texts?

Add Action for Layout > Action Type (help text) Next / Previous item in the Schedule

Add Action for Region > Action Type (remove Next / Previous from drop-down or would the Next / Previous Widget in the Region Timeline apply, if so same help text as for Widget below)

Add Action for Widget > Action Type (help text) Next / Previous Widget in the Region Timeline

**Comment by dasgarner** [comment]
@PeterMis what do you think about these changes?

**Comment by PeterMis** [comment]
I think this looks mostly sensible, I may have some clarification questions when I get around to making those changes, if so we will discuss them.
