### ISSUE TITLE
Calendar Widget to have a "Group by Day" option for grouping into Monday/Tuesday/etc

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2318]
Could we fulfil this with a filter and grouping option on date?

OP: https://community.xibo.org.uk/t/calendar-widget-day-grouping/23410

**Comment by dasgarner** [comment]
Mauro - i think this might play into the calendar work you're looking at soon.

**Comment by maurofmferrao** [comment]
This issue is solved by using the Agenda view on the new Calendar widget
