### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by mymactek** [xibosignage/xibo#232]
Hello,

Was updating one of our servers (/FISD) to 1.7, and now one of our other servers @ root on the server ( no folder just root ) states :

Incompatible database version detected. Please ensure your database and website versions match. You have database 80 and website 72

This is our production server, and the update was not on this server it was within one of the folders

This error  Server ( .../ )
Updating server ( .../FISD )  

Please assist asap,
Thanks
Ryan

**Comment by mymactek** [comment]
trying to update server to newest 1.7.1 and got the following error

![image](https://cloud.githubusercontent.com/assets/10713173/6155645/832eefee-b1fa-11e4-8ba8-03ba38d2c6cf.png)

**Comment by Speedy-Gonzalez** [comment]
It sounds a bit like both installations use the same DB.

**Comment by mymactek** [comment]
I got it to work from 81, now stating …. “ 1.7 alpha2” for the version at the bottom …
upgrading 81 to 85 ….

“ An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 82. Error Message = [SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY’]”

**Comment by dasgarner** [comment]
It sounds a lot like your installations are sharing the same database - which is not a supported operation. Xibo must have 1 database per installation.

To resolve this issue it feels like you will need to roll back to your prior installation, ensure that your settings.php file in each installation point to different databases and then run the latest 1.7.1 upgrade again on each installation individually.

The error message you are getting means that a partial upgrade has been run on your database and now it is stuck because it doesn't know what statements it needs to run.

**Comment by mymactek** [comment]
Dan,

Thank you for the help.

I have double checked and each installation is running on its own database. I don’t know what happened or how it happened running the upgrade on the FISD server, and it messed up this one. I re-ran the 1.7.1 upgrade and the following came up ….

An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 82. Error Message = [SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dssxibo.template' doesn't exist]

Thank you.

**Comment by mymactek** [comment]
Ok getting this error : 

An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 82. Error Message = [SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY’]

from :


INSERT INTO `tag` (`tagId`, `tag`) VALUES
(1, 'template'),
(2, 'background'),
(3, 'thumbnail’);

**Comment by mymactek** [comment]
Ok Have gotten the update to progress some but running into : 

An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 82. Error Message = [SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tags' in 'field list']

Please help.
Thanks

**Comment by mymactek** [comment]
got it, fixed.

**Comment by dasgarner** [comment]
Sorry - I was engaged in another task. Glad you have it sorted.

**Comment by mymactek** [comment]
No problem. Took it line by line on the sql update. Don't know what original happened but it like partially upgraded then stopped. So had some new tables and such. But all working now.Thanks On Thu, Feb 12, 2015 at 5:05 PM,  xibosignage/xibo <reply@reply.github.com> wrote:            Sorry - I was engaged in another task. Glad you have it sorted.

**Comment by mymactek** [comment]
do have another question…
Updating another server and on update 81 SQL it stated  this was already present :

ALTER TABLE  `media` ADD  `moduleSystemFile` TINYINT NOT NULL DEFAULT  '0’;

Re-run the installation, and it just hangs ….in chrome the icon just spins at the top, or in safari it shows about 1/4 way progress then stays there …
any advice ?

Thanks

**Comment by dasgarner** [comment]
That SQL only appears once, so it must have had a partial upgrade in the past.

If the upgrade hangs, then i'd imagine there is some stuff in the DB that is taking a long time to convert over. You might want to run those SQL statements manually again in that case.

The upgrades are only SQL files, so they can be run in ascending order to achieve the same result as the upgrade routine itself.

**Comment by mymactek** [comment]
I got it to work. :-)

Do have a question though … on the main ‘dashboard’ on the bottom right - the news feed … what format do you have it in ?
Would like to show our news from our Wordpress site …

Thanks

**Comment by dasgarner** [comment]
Create a new theme folder under themes - copy the config.php file in from the default theme and change the "latest_news_url" setting.

Update the CMS Settings global theme to be the name of your new theme.

**Comment by mymactek** [comment]
Do you just use wordpress to fill in the newsfeed ?
Regular RSS from wordpress that is …

Thanks

**Comment by dasgarner** [comment]
Any RSS feed will work :smile:

**Comment by mymactek** [comment]
I copied the theme directory, and changed the config.php file.
In settings changed it to “ DSSTheme “ and now the page is blank …

LOL - What did I do wrong ?

**Comment by mymactek** [comment]
Ok got the original theme to come back up …
So does the folder have to EXACT of what is typed into the “GLOBAL_THEME_NAME” ?
Thanks

**Comment by dasgarner** [comment]
yes, they are matched on the name.

It looks at the global theme name, looks for a folder with the matching name and then looks for a config.php file inside that folder... if any of the above doesn't match, it wont work.
