### ISSUE TITLE
Enhancement: Include Help text for Screen Dimensions option in Edit Display menu.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2328]
CMS Version: 2.3.7

Issue: Go to the Edit Display window for an Android Display. On the Profile Settings menu, the Screen Dimensions field does not explain how to correctly enter the top, left, width, and height values, and in what order. This can cause incorrect configurations to be entered.

Note: The Windows player has a separate field for Top, Left, Width and Height.

**Comment by dasgarner** [comment]
@maurofmferrao i've made a change here to pull the help text from the Display Profile form onto the Display Edit profile overrides table. How difficult to you think it would be to display that help text if the setting is already overridden or if user clicks on the edit button?

**Comment by maurofmferrao** [comment]
I think we can do something like grabbing the title you've added and append a new muted text element under the content.
If we add this after [line 740](https://github.com/dasgarner/xibo-cms/blob/71b4c57bbfb32bc9509f9de57e9f8b447c0d81ec/views/display-page.twig#L740) it will add the help text every time the override field is generated:

```javascript
// Add help text if exists on label
var inputHelpText = $(temp1).parent('tr').find('td:first strong').attr('title');
if(inputHelpText) {
    $(temp1).append('<div class="text-muted">' + inputHelpText + '</div>');
}
 ```

**Comment by dasgarner** [comment]
That works a treat! Thanks
