### ISSUE TITLE
File in version.json is invalid

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#233]
Hello Dan,

I do not know if it's something serious, seeking work, following which identified the log.

![image](https://cloud.githubusercontent.com/assets/325662/6160109/6e4e728e-b245-11e4-84ca-3c985694e69f.png)

**Comment by dasgarner** [comment]
That is actually OK - it just means that the file you have set to be installed has not yet downloaded. I'll switch that to an audit type of message which should suppress it.

**Comment by dasgarner** [comment]
Oh, it already is an audit type message - so I guess you have auditing enabled on that display. In which case this is normal.
