### ISSUE TITLE
Error in Register: null

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#234]
This error occurs at times, is not common, but whenever there is check that the equipment is with internet access perfectly. The server also is with good performance and receiving connections from other displays in test.

![image](https://cloud.githubusercontent.com/assets/325662/6160164/0d20689a-b246-11e4-9f14-e53e6a2b351d.png)

**Comment by dasgarner** [comment]
I think we have now solved this with you, correct?

**Comment by laercionit** [comment]
Dan, this log was generated yesterday, even after use of client r52.
The APK is working better now, although still present connectivity errors and other small problems, I have used the springsignage email channel.

**Comment by dasgarner** [comment]
OK, thanks.
