### ISSUE TITLE
Issue searching for accents in the Library search field

### ISSUE THREAD

**Issue by Tashamy** [xibosignage/xibo#2343]
Reported here for info : https://community.xibo.org.uk/t/problem-in-the-library-search-field/23705

**Comment by dasgarner** [comment]
The OP asks for Media named `Cartório` to be returned when searching for `Cartorio`, but these are essentially different words (technically no different to searching for `Carturio`?).

If we had some sort of fuzzy search index then perhaps we could do this - unfortunately however this is out of scope for our basic LIKE/RLIKE filtering capabilites.
