### ISSUE TITLE
Using "- "in a search field returns a SQL error

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2344]
CMS Version: 2.3.7

Issue: Enter the following into a search box in CMS:
```
- <any characters>
```
This will return the following error:

SQLSTATE[42000]: Syntax error or access violation: 1139 Got error 'empty (sub)expression' from regexp Exception Type: PDOException

**Comment by dasgarner** [comment]
its the space after the `-`
`- Three` so that gives the same problem
the tokeniser changes that into two separate clauses (due to the space)
`-` and `Three`
and `-` on its own, isn't a valid clause
