### ISSUE TITLE
Enhancement: Screenshot options for Tizen profiles to be changed

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2345]
CMS Version: 1.8.13, 2.3.7

Enhancement: Tizen can return screenshots up to 720x576 resolution. Currently the options in CMS are Thumbnail, HD and FHD. Enhancement to replace the options with Thumbnail and Standard.

**Comment by dasgarner** [comment]
Currently:

```
{ id: 1, value: "Thumbnail"|trans },
{ id: 2, value: "HD"|trans },
{ id: 3, value: "FHD"|trans }
```

What should the ID of the new "Standard" option be? 2?

**Comment by DanielBW1** [comment]
Thank you Dan. Yes could id 2 be set to standard and id 3 hidden for now? Checked with the developers and this would be the best solution for now, in case any changes to screenshots are added in future releases/firmwares.
