### ISSUE TITLE
Assign column in Library and not able to assign to a layout

### ISSUE THREAD

**Issue by mohamedirfan6186** [xibosignage/xibo#235]
![issue](https://cloud.githubusercontent.com/assets/10971289/6162367/feedb624-b29a-11e4-8353-8832d7362f08.png)

Dear All,

         Can you please help us to solve the issue as in the layout we are not able to assign any images or videos. It just freezes and not allowing to assign image to the region. But we are able to upload am image. Please have a look and suggest us with proper solution. 

Regards,
I Mohamed Irfan

**Comment by nagyrobi** [comment]
Re-download 1.7.1, and reinstall php files.

**Comment by mohamedirfan6186** [comment]
Tried 3-4 times. The same issue. The Assign option freezes.

**Comment by mohamedirfan6186** [comment]
The same issue persist. Can we have a remote session. I can give you the remote access. so that you can help me. Please.
