### ISSUE TITLE
Permanent 60 seconds Publish timeout

### ISSUE THREAD

**Issue by leofass** [xibosignage/xibo#2356]
Hello Xibo team,

We are facing an issue before click on "Publish" layout button.
All the time we try to publish a heavy layout (more than 4000 Spots) we get a static 60 seconds timeout on Chrome Developer Tools (Network session).
We have already tried to increase all of the parameter as you can see below:

Attached are two images that shows the 60 seconds timeout.

To solve this fastly, is there a static value hardcoded that controls this timeout, or any other parameter that let us configure on our server?

php.ini
max_input_time=180
default_socket_timeout=180
max_execution_time=180

apache2/default.conf
<IfModule reqtimeout_module>
  RequestReadTimeout header=20-180,MinRate=500 body=20,MinRate=500
</IfModule>

mysql.cnf
[mysqld]
innodb_lock_wait_timeout=180
net_write_timeout=70
log-error=/var/log/error.log
slow_query_log=on
slow_query_log_file=/var/log/mysql/slowquery.log

enabled venvs
CMS_APACHE_TIMEOUT=180
CMS_PHP_MEMORY_LIMIT=512M
CMS_PHP_MAX_EXECUTION_TIME=600
CMS_APACHE_START_SERVERS=3

![Clipboard - 19 de Novembro de 2020 10_54](https://user-images.githubusercontent.com/8985359/99676040-c07e7880-2a56-11eb-9441-7939f5a661ac.png)
![Clipboard - 19 de Novembro de 2020 10_53](https://user-images.githubusercontent.com/8985359/99676042-c1170f00-2a56-11eb-9760-882b3cf80fca.png)

Please feel free to ask me if you need something else.

Thank you and Best Regards,

**Comment by alexharrington** [comment]
Thanks for your message.

4000 widgets on a layout is a huge number. The time you're seeing is the time it's taking for your server to try and build a layout from that. You're then hitting some kind of timeout or memory limit and that is why the request fails.

Ultimately it's well outside what we expect you to have on a single layout, so wouldn't be something we would be able to address. You should split your content in to smaller layouts and use a campaign to group them. Even if you did get it to publish I don't think any of our Players will deal with that kind of volume of widgets in a single layout. You will undoubtedly hit issues there as well.

We also use Github Issues to track verified bugs only. We don't use it for support. If you have future support requests and are self-hosting, then feel free to post on our Community Forum where members of the community may be able to assist you. If you have a Cloud hosted account, or paid support contract, then you are welcome to contact our service desk.
