### ISSUE TITLE
Bug Update 1.70 >>> 1.7.1 - Font Module

### ISSUE THREAD

**Issue by MarcelErdmann** [xibosignage/xibo#236]
Hello,

a small bug report

after the update (1.7.0 >>> 1.7.1) the font module is disabled. (in 1.7.0 was enabled)

After activating in 1.7.1 everything is OK (The fonts are still installed)

**Comment by dasgarner** [comment]
Thanks, we will take a look.

**Comment by dasgarner** [comment]
I'm at a loss for recreating this one - I have looked at all the updates between 1.7.0 and 1.7.1 (essentially 1 file) and we don't set the font module to disabled anywhere... i'm really not sure how to proceed as I cannot recreate.
