### ISSUE TITLE
Make sure we've renamed Permissions to Sharing in all places

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2362]
An example of where we haven't:

![image](https://user-images.githubusercontent.com/10400067/100117247-80f7c800-2e6c-11eb-9098-2c5da57f8182.png)

**Comment by Tashamy** [comment]
Labelled Permissions on the Tools menu in the Layout Designer as well as a right click on Widgets on the timeline and right click on Regions in editor.

**Comment by Tashamy** [comment]
Share forms are also labelled 'Permissions for X'
