### ISSUE TITLE
Template for Using Style Sheets on DataSets in Tickers

### ISSUE THREAD

**Issue by solane** [xibosignage/xibo#237]
Is there a standard template that I can use in the 'optional style sheet' menu of a dataset in a ticker. When you create a normal dataset you get a style sheet template to start from however in the ticker you get nothing. I have tried copying my style sheet across but that doesn't seem to change a thing.

Thanks

**Comment by dasgarner** [comment]
No there isn't...

What exactly do you want to change? Ticker datasets are displayed similarly to RSS feeds.

**Comment by solane** [comment]
I want to be able to center the information in the area and reduce the paragraph spacing but nothing I try in the optional style sheet changes anything.

Thanks

![ticker](https://cloud.githubusercontent.com/assets/10942349/6266319/d4ac795a-b82f-11e4-89ff-968e15fb347f.JPG)

**Comment by dasgarner** [comment]
What template and settings have you used to get that far with it? I'm imagining that each "row" is a column in your dataset and that you have 5 items shown "side by side" ?

Why not use the datasetview for this? It is designed to show tabular data

**Comment by solane** [comment]
Yes each row is a column in my dataset. Yes they are shown side by side because otherwise the table only shows 1 column of data. I have tried to edit the css in so many ways in the optional style sheet but nothing i try changes anything to do with spacing or centering the dataset in the middle of the area.



![nothing works](https://cloud.githubusercontent.com/assets/10942349/6348864/ed8a49e4-bc1b-11e4-9ddb-216442645479.JPG)

**Comment by dasgarner** [comment]
So you need to style this:

``` html
<body>
  <div id="content">
    <div class="page">
     <div class="item">...</div>
     <div class="item">...</div>
     <div class="item">...</div>
     <div class="item">...</div>
     <div class="item">...</div>
    </div>
  </div>
</body>
```

The ... inside the item div is your template content, so most likely some paragraphs.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
