### ISSUE TITLE
RemoteDataSet: Unable to get Data for %s because the response was not valid JSON

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2383]
Looks like this is due to not rewinding the Response stream if we've used the body to calculate a caching header.

**Comment by 11dev** [comment]
Hallo!
I have just downloaded and installed the Xibo CMS v. 3.0.3 and I have the same issue. What should I do to solve?
Kind regards,
Emanuele

**Comment by dasgarner** [comment]
Hello,

This issue is also fixed in 3.0, so I think you might be experiencing a different issue. Please can you direct this support request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!

**Comment by 11dev** [comment]
Hallo.
Thank you for your response, I thought it should be already fixed, but the
problem is apparently identical. I'll follow your advice, anyway.
Best regards,
Emanuele

Il giorno mer 3 nov 2021 alle ore 09:04 Dan Garner ***@***.***>
ha scritto:
