### ISSUE TITLE
Write Manual FAQ for setting windows player registry to use IE11

### ISSUE THREAD

**Issue by JianjianHuang** [xibosignage/xibo#239]
Hi Dan

I played nasa hdtv using embed media type via IE.

Vesrion: server 1.7.0, client 1.7.0, OS win8.1 64 bits, IE 11.

The content cannot be played, I then removed the <meta http-equiv="X-UA-Compatible" content="IE=edge" />, the display is OK.

So it seems on IE11, we decared <!doctype html>, we don't need that line.
https://msdn.microsoft.com/en-us/library/ie/bg182625(v=vs.85).aspx
Am I right?

Thanks.
Jianjian

**Comment by JianjianHuang** [comment]
Sorry, I deleleted the line
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

**Comment by JianjianHuang** [comment]
Sorry, I deleted the line <meta http-equkv="X-UA-Compatible" content="IE=edge" />

**Comment by JianjianHuang** [comment]
Sorry, I deleted the line meta http-equiv="X-UA-Compatible" ....

**Comment by dasgarner** [comment]
Sorry Jianjian, you lost me a little bit...

Do you mean this line `<meta http-equiv="X-UA-Compatible" content="IE=edge" />` in `HtmlTemplate.htm` ?

I thought that line would be forcing IE to adopt the latest rendering engine...

I wonder if the WebBrowser control has been updated in windows 8.1

**Comment by JianjianHuang** [comment]
Yes, Dan,I mean that line.
I copy and paste that line in this forum, but the content was gone after I click comment button.

I removed that line before navigate like this:
html = html.Replace("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />","");

I checked my IE,it is in edge mode.

Thanks.
Jianjian

**Comment by JianjianHuang** [comment]
Yes, Dan,I mean that line.
I copy and paste that line in this forum, but the content was gone after I click comment button.

I removed that line before navigate like this:
html = html.Replace("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />","");

I checked my IE,it is in edge mode.

Thanks.
Jianjian

**Comment by JianjianHuang** [comment]
Yes, Dan, I mean that line.
I copy and paste that line in this forum, but the content was gone after I click comment button.

I removed that line before navigate like this:
html=html.Replace("<meta http-equive=....","");   (I tried several times with that full line here, after click comment, it became html=html.Replace("","");)

I checked my IE, it is in edge mode.
Thanks
Jianjian

**Comment by dasgarner** [comment]
this uses markdown syntax so you can use backticks to comment code...

I am not sure that commenting out that line will work correctly on older systems - we still need to support people running XP.

Why would you not play embedded TV using the local video module instead? Assuming you have a streaming URL.

**Comment by JianjianHuang** [comment]
Hi Dan

If that line can really be removed on IE11, we can check IE version before remove it.

I use embedded media type to play the nasahdtv, because I did not find the streaming url, they share it by embedded code.
www.ustream.tv/nasahdtv

Thanks
Jianjian

**Comment by dasgarner** [comment]
I am happy for that to happen if we can correctly detect IE11 **in the webbrowser control** - do you know how we can do that?

**Comment by JianjianHuang** [comment]
Hi Dan

Can we try this: _webBrowser.Version.Major >= 11

Thanks
Jianjian

**Comment by dasgarner** [comment]
Are you able to add that logic to your fork and submit a pull request?

**Comment by JianjianHuang** [comment]
Hi Dan

Today I changed the following in regedit and leave the http-equiv unchanged
HKEY_LOCAL_MACHINE
   SOFTWARE
      Microsoft
         Internet Explorer
            Main
               FeatureControl
                  FEATURE_BROWSER_EMULATION
                     xiboclient.exe = (DWORD) 00011001

11001 is for ie11 edge mode. It solved my nasahdtv issue. 

from https://msdn.microsoft.com/en-us/library/ee330720(v=vs.85).aspx
Here is a reference to Internet feature controls (also called feature control keys), which are Registry keys that manage individual features Windows Internet Explorer and applications hosting the WebBrowser Control control. .......................

So this is the correct way for webcontrol? 
Sorry for confusing you.

Thanks
Jianjian

**Comment by JianjianHuang** [comment]
Hi Dan

Today I changed the following in regedit and leave the http-equiv unchanged
HKEY_LOCAL_MACHINE
SOFTWARE
Microsoft
Internet Explorer
Main
FeatureControl
FEATURE_BROWSER_EMULATION
xiboclient.exe = (DWORD) 00011001

11001 is for ie11 edge mode. It solved my nasahdtv issue.

from https://msdn.microsoft.com/en-us/library/ee330720(v=vs.85).aspx
Here is a reference to Internet feature controls (also called feature control keys), which are Registry keys that manage individual features Windows Internet Explorer and applications hosting the WebBrowser Control control. .......................

So this is the correct way for webbrowser control? 
Sorry for confusing you.

Thanks
Jianjian

**Comment by dasgarner** [comment]
We already know about those keys - we don't set them by default as they can cause issues with other content (such as flash).

I think we will leave it as it is then, and tag this up to write a proper FAQ for the IE settings.
