### ISSUE TITLE
Tags on media items are not imported into CMS.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2391]
CMS Version:
2.3.8

Issue:
Create a layout that uses media items with tags. Export the layout and import it into a new CMS. The tags on the media items are not imported.

Notes:
- The media items will instead have the imported tag only

**Comment by dasgarner** [comment]
I am not sure if this is desired or not - maybe the tags could be exported in the ZIP and then imported as an option? In either case I think this is an enhancement rather than a bug.
