### ISSUE TITLE
Layout Export doesn't obey Media Sharing settings

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2393]
If you export a Layout containing Media which is not shared with you, that media is still in the exported Layout.

Two strategies for dealing with this:

 - Disallow exporting the Layout
 - Automatically remove the Widgets containing non-shared Media

**Comment by dasgarner** [comment]
@alexharrington please can we have some input on how we want this to work?

**Comment by alexharrington** [comment]
I think showing a warning, but allowing you to export what you're allowed to access would be most sensible? That way you know it's not complete, but we aren't preventing an export of what you do have access to either.

**Comment by dasgarner** [comment]
Removing media/dataset's from the export is much larger scope that previously thought, and not something we think we can undertake as part of a patch release.

We will therefore do two things:

- [ ] 2.3.9: put a notice on the export form stating that if you don't have permissions for everything in the Layout, the export might fail, and then make it fail under that scenario
- [ ] 3.0.0-rc2: add a new feature for `layout.export` which explicitly states that you have permission to export any Layout which you can edit, including any media belonging to it, regardless of whether that is shared with you or not.

**Comment by alexharrington** [comment]
2.3.9 action point is fine.
I'm not sure 3.0.0-rc2 action point is viable. Couldn't a user with that permission create a tag-based playlist and export all media items owned by anyone with an arbitrary tag applied?

**Comment by alexharrington** [comment]
OK I think your proposal is viable then - so we give people the option to do it without having to grant superadmin.
