### ISSUE TITLE
xibo client build for anycpu

### ISSUE THREAD

**Issue by JianjianHuang** [xibosignage/xibo#240]
Hi Dan

I tried to display website via cef on my win8.1 64bits pc.

Version: server 1.7.0, client 1.7.0, OS win8.1 64bits.

The xibo always stopped after some time, I downloaded a 64 bit libcef library, and then build xibo application for any cpu. it's stable now.

Thanks.
Jianjian

**Comment by dasgarner** [comment]
Interesting - we have always built and shipped as a 32bit application because of compatibility with the WMP DLL and Flash DLL. Do you happen to know whether those still work with you x64 buildprofile?

**Comment by stanleysct** [comment]
Hi,

I am trying to open MainForm using Visual Studio 2012 I got the following error:

Message	1	Could not find type 'XiboClient.ApplicationSettings'.  Please make sure that the assembly that contains this type is referenced.  If this type is a part of your development project, make sure that the project has been successfully built using settings for your current platform or Any CPU.	C:\Users\Stanley\Desktop\xibo-dotnetclient-master\MainForm.Designer.cs	43	0	

Appreciate if someone can give a glue. Thank you.

**Comment by dasgarner** [comment]
MainForm is not designed to be opened in designer mode... and what does that have to do with the original question?

**Comment by JianjianHuang** [comment]
Hi, Dan

To test video and flash on this build, I created a layout, one youtube region, one video region, one flash region, one webpage region, and another two regions for clock and weather each.

The default browser is CEF.

The other regions are playing very well except flash, the flash can be played every time when xibo started, when the layout restarted again, the flash region disappeared.

I then tried to change the flash code like this, move controls.add and show from documentcompleted event to flash constructor, and add _disposed variable and change documentcompleted event as same as it's in iewebmedia.

Then flash works well.

I am still testing this layout on two machines, cms 1.7.0, client 1.7.0, os 8.1 64bits, the difference is the default browser, one is cef, another is ie.


Thanks
Jianjian

**Comment by dasgarner** [comment]
Hi Jianjian,

Is there any possibility of you forking the repository and putting these changes in branches for me to look at? I can then compare your branch with the master and see exactly what has changed.

I also want to make sure you are talking about the flash module and not flash inside a website? We haven't been able to get Flash to work in CEF at all, so would be very interested if you have.

**Comment by JianjianHuang** [comment]
Hi Dan

I will try to find how to do it then I will put the changes in a branch.

Yes, I see the flash playing by a webrowser control, though the other web medias are played by cef if you set the default browser as cef.

Thanks
Jianjian

**Comment by JianjianHuang** [comment]
Hi Dan

It's done.

I forked, and the changed file is on jianjianhuang-patch-1 branch.

Thanks
Jianjian

**Comment by stanleysct** [comment]
Hi Dan,

I understand the python player no longer support. May I know is there any plan for cross platform xibo player beside windows player or android player? 

Thanks

Regards,
Stanley

**Comment by Speedy-Gonzalez** [comment]
@stanleysct See issue #29.

Please try not to mix up stuff. Open a new issue or use the search function to find an answer. :wink:

**Comment by dasgarner** [comment]
@JianjianHuang can you submit a pull request for that so that I see it and your changes?

Thanks,
Dan

**Comment by JianjianHuang** [comment]
https://github.com/JianjianHuang/xibo-dotnetclient/pulls
