### ISSUE TITLE
Video Widget scale type text to be updated.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2403]
CMS Version:
2.3.8

Issue:
The Scale Type option on the configuration tab for the Video widget currently states:

`How should this video be scaled? Please note that video scaling is only supported by Android, webOS and Tizen players at the current time.`

Xibo for Windows now supports stretched content on the WPF versions of the player. Above message in the widget needs to be updated.

**Comment by dasgarner** [comment]
> How should this video be scaled? Please note that video scaling is only supported by Android, webOS and Tizen players at the current time.

change to:

How should this video be scaled? Please note that video scaling is not supported by Xibo for Windows earlier than v2 R255 or Xibo for Linux.
