### ISSUE TITLE
Template Add/Edit has fields it shouldn't

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2407]
Anything we set when we create a Layout shouldn't be available on the template add/edit form - so no:
 - enable stats
 - automatically apply transitions
 - code identifier

It also says "edit layout" in the title bar and "retire this layout" in the help text

**Comment by Tashamy** [comment]
Changes to text from Row Menu actions from Templates grid:
Delete - help text needs amending from Layout to Template. Suggest: "Are you sure you want to delete this Template? Media will be unassigned and any Layout specific media such as Text/RSS will be deleted"
Retire - change to Template
Share - change to Share Options for Template?

The Templates grid does not have an Advanced Tab to be able to view Retired Templates.
