### ISSUE TITLE
Forecast Problem

### ISSUE THREAD

**Issue by levece** [xibosignage/xibo#241]
Hi there
weather module does not load information, I already put the API KEY Forecast, and this works well in the page "https://api.forecast.io/forecast". I put the data troubleshoot here:

Date,Page,Function,Message
"2015-02-12 14:44:45","","","<errormsg>file_get_contents(): Unable to find the wrapper &quot;https&quot; - did you forget to enable it when you configured PHP?</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\3rdparty\forecast.php</scriptname>
<scriptlinenum>29</scriptlinenum>
"

**Comment by xibo-de** [comment]
Try the following script to see if there is an https wrapper available for your php scripts.

<?php
$w = stream_get_wrappers();
echo 'openssl: ',  extension_loaded  ('openssl') ? 'yes':'no', "\n";
echo 'http wrapper: ', in_array('http', $w) ? 'yes':'no', "\n";
echo 'https wrapper: ', in_array('https', $w) ? 'yes':'no', "\n";
echo 'wrappers: ', var_dump($w);
?>

**Comment by levece** [comment]
I'm sorry but what is the exact file in which I have to look for the scripts?

**Comment by xibo-de** [comment]
Create e.g. test_wrapper.php with content from my first post.
Copy the file to the web server in the http directory.

Call the script, for example: http://xxxxx.xxx/xxxxxxx/test_wrapper.php
Please replace xxxx with your data.

**Comment by xibo-de** [comment]
What shows the script ?

**Comment by levece** [comment]
ok this is the result:
openssl: no http wrapper: yes https wrapper: no wrappers: array(10) { [0]=> string(3) "php" [1]=> string(4) "file" [2]=> string(4) "glob" [3]=> string(4) "data" [4]=> string(4) "http" [5]=> string(3) "ftp" [6]=> string(3) "zip" [7]=> string(13) "compress.zlib" [8]=> string(14) "compress.bzip2" [9]=> string(4) "phar" }

**Comment by xibo-de** [comment]
In the php.ini file you enable or add this lines if not exists:

extension=php_openssl.dll
allow_url_fopen = On

Stop and Start Webserver.

**Comment by levece** [comment]
ok I already make the changes and reboot the server. but the forecast still does not give me information.

openssl: yes http wrapper: yes https wrapper: yes wrappers: array(12) { [0]=> string(3) "php" [1]=> string(4) "file" [2]=> string(4) "glob" [3]=> string(4) "data" [4]=> string(4) "http" [5]=> string(3) "ftp" [6]=> string(3) "zip" [7]=> string(13) "compress.zlib" [8]=> string(14) "compress.bzip2" [9]=> string(5) "https" [10]=> string(4) "ftps" [11]=> string(4) "phar" }

**Comment by levece** [comment]
--------------------------------------
Environment Checks
--------------------------------------
<table class="table">
    <thead>
        <tr>
                                    <th class="group-false">Item</th>
                        <th class="group-false" data-sorter="tickcross">Estado</th>
                        <th class="group-false">Advice</th>
                                </tr>
    </thead>
    <tbody>
                <tr >
                                                <td>Versión de PHP</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP version 5.3.3 or later required. Detected 5.4.7</td>
                                            </tr>
                <tr >
                                                <td>File System Permissions</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>Write access required for settings.php and install.php</td>
                                            </tr>
                <tr >
                                                <td>Base de datos MySQL (PHP MySql)</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>MySQL support must be enabled in PHP.</td>
                                            </tr>
                <tr >
                                                <td>Base de datos MySQL (PDO MySql)</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PDO support with MySQL drivers must be enabled in PHP.</td>
                                            </tr>
                <tr >
                                                <td>Extensión  JSON</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>Se requiere extensión de la función PHP JSON.</td>
                                            </tr>
                <tr >
                                                <td>Extensiones SOAP</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>Se requiere extensión  de la función  PHP SOAP.</td>
                                            </tr>
                <tr >
                                                <td>Extensión GD</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>Extensión PHP GD o función.</td>
                                            </tr>
                <tr >
                                                <td>Sesión</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP session support to function.</td>
                                            </tr>
                <tr >
                                                <td>FileInfo</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>Requires PHP FileInfo support to function. If you are on Windows you need to enable the php_fileinfo.dll in your php.ini file.</td>
                                            </tr>
                <tr >
                                                <td>PCRE</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP PCRE support to function.</td>
                                            </tr>
                <tr >
                                                <td>Gettext</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP Gettext support to function.</td>
                                            </tr>
                <tr >
                                                <td>Extensión Calendario</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP Calendar extension to function.</td>
                                            </tr>
                <tr >
                                                <td>Extensión DOM</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP DOM core functionality enabled.</td>
                                            </tr>
                <tr >
                                                <td>Extensión DOM XML</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP DOM XML extension to function.</td>
                                            </tr>
                <tr >
                                                <td>Extensión Mxrypt</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP Mcrypt extension to function.</td>
                                            </tr>
                <tr >
                                                <td>Permitir que PHP abra URLs externas</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>You must have allow_url_fopen = On in your PHP.ini file for RSS Feeds / Anonymous statistics gathering to function.</td>
                                            </tr>
                <tr >
                                                <td>DateTimeZone</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>This enables us to get a list of time zones supported by the hosting server.</td>
                                            </tr>
                <tr >
                                                <td>Large File Uploads</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>Support for uploading large files is recommended.</td>
                                            </tr>
            </tbody>
</table>

--------------------------------------
LOG Dump
--------------------------------------
Date,Page,Function,Message
"2015-02-13 12:06:08","module","","<errormsg>Undefined property: stdClass::$currently</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>656</scriptlinenum>
"
"2015-02-13 12:06:08","module","","<errormsg>Trying to get property of non-object</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>656</scriptlinenum>
"
"2015-02-13 12:06:08","module","","<errormsg>Creating default object from empty value</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>656</scriptlinenum>
"
"2015-02-13 12:06:08","module","","<errormsg>Undefined index: daily</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:06:08","module","","<errormsg>Undefined offset: 1</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:06:08","module","","<errormsg>Undefined offset: 2</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:06:08","module","","<errormsg>Undefined offset: 3</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:06:08","module","","<errormsg>Undefined offset: 4</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:06:08","module","","<errormsg>Undefined offset: 5</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:06:08","module","","<errormsg>Undefined offset: 6</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:04:36","module","","<errormsg>Undefined property: stdClass::$currently</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>656</scriptlinenum>
"
"2015-02-13 12:04:36","module","","<errormsg>Trying to get property of non-object</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>656</scriptlinenum>
"
"2015-02-13 12:04:36","module","","<errormsg>Creating default object from empty value</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>656</scriptlinenum>
"
"2015-02-13 12:04:36","module","","<errormsg>Undefined index: daily</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:04:36","module","","<errormsg>Undefined offset: 1</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:04:36","module","","<errormsg>Undefined offset: 2</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:04:36","module","","<errormsg>Undefined offset: 3</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:04:36","module","","<errormsg>Undefined offset: 4</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:04:36","module","","<errormsg>Undefined offset: 5</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:04:36","module","","<errormsg>Undefined offset: 6</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:04:20","module","","<errormsg>Undefined property: stdClass::$currently</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>656</scriptlinenum>
"
"2015-02-13 12:04:20","module","","<errormsg>Trying to get property of non-object</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>656</scriptlinenum>
"
"2015-02-13 12:04:20","module","","<errormsg>Creating default object from empty value</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>656</scriptlinenum>
"
"2015-02-13 12:04:20","module","","<errormsg>Undefined index: daily</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:04:20","module","","<errormsg>Undefined offset: 1</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:04:20","module","","<errormsg>Undefined offset: 2</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:04:20","module","","<errormsg>Undefined offset: 3</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:04:20","module","","<errormsg>Undefined offset: 4</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:04:20","module","","<errormsg>Undefined offset: 5</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:04:20","module","","<errormsg>Undefined offset: 6</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:03:05","","","<errormsg>file_get_contents(https://api.forecast.io/forecast/0b313389f38bb6d3fb4c782c5e7b475/50.8249287,-0.1423327?units=si&amp;lang=es&amp;exclude=flags%2Cminutely%2Chourly): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden
</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\3rdparty\forecast.php</scriptname>
<scriptlinenum>29</scriptlinenum>
"
"2015-02-13 12:03:05","","","<errormsg>Creating default object from empty value</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\3rdparty\forecast.php</scriptname>
<scriptlinenum>30</scriptlinenum>
"
"2015-02-13 12:03:05","","","<errormsg>Undefined property: stdClass::$currently</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>656</scriptlinenum>
"
"2015-02-13 12:03:05","","","<errormsg>Trying to get property of non-object</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>656</scriptlinenum>
"
"2015-02-13 12:03:05","","","<errormsg>Creating default object from empty value</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>656</scriptlinenum>
"
"2015-02-13 12:03:05","","","<errormsg>Undefined index: daily</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:03:05","","","<errormsg>Undefined offset: 1</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:03:05","","","<errormsg>Undefined offset: 2</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:03:05","","","<errormsg>Undefined offset: 3</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:03:05","","","<errormsg>Undefined offset: 4</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:03:05","","","<errormsg>Undefined offset: 5</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:03:05","","","<errormsg>Undefined offset: 6</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\xampp\htdocs\cartelera\modules\forecastio.module.php</scriptname>
<scriptlinenum>666</scriptlinenum>
"
"2015-02-13 12:02:54","Client","[UI Thread] xmds_GetResource","Unable to get Resource: Requested an invalid file."
"2015-02-13 12:02:54","Client","[UI Thread] xmds_GetResource","Unable to get Resource: Requested an invalid file."
"2015-02-13 12:02:54","Client","[UI Thread] xmds_GetResource","Unable to get Resource: Requested an invalid file."
"2015-02-13 12:02:54","Client","[UI Thread] xmds_GetResource","Unable to get Resource: Requested an invalid file."
"2015-02-13 12:02:54","Client","[RegisterAgentThread] RegisterAgent - Run","WebException in Run: No es posible conectar con el servidor remoto"
"2015-02-13 12:02:54","Client","[RegisterAgentThread] RegisterAgent - Run","WebException in Run: No es posible conectar con el servidor remoto"
"2015-02-13 12:02:54","Client","[ScheduleAgentThread] ScheduleAgent - Run","WebException in Run: No es posible conectar con el servidor remoto"
"2015-02-13 12:02:54","Client","[RequiredFilesAgentThread] RequiredFilesAgent - Ru","WebException in Run: No es posible conectar con el servidor remoto"

--------------------------------------
Display Dump
--------------------------------------
DisplayID: 1
Display: CARTELERA-PC1
Default Layout: Ojo Pelao horizontal Noviembre 2014
Logged In: 1
Last Accessed: 1423845394
Interleave: 0
Licensed: 1

DisplayID: 2
Display: PC LEO
Default Layout: Ojo Pelao Vertical Twitter Nov 2014
Logged In: 1
Last Accessed: 1423765488
Interleave: 0
Licensed: 1


--------------------------------------
Settings Dump
--------------------------------------
Setting: MEDIA_DEFAULT - Value:   public

Setting: LAYOUT_DEFAULT - Value:   public

Setting: defaultUsertype - Value:   Group Admin

Setting: userModule - Value:   module_user_general.php

Setting: defaultTimezone - Value:   America/Caracas

Setting: mail_to - Value:   mail@yoursite.com

Setting: mail_from - Value:   mail@yoursite.com

Setting: jpg_length - Value:   10

Setting: ppt_length - Value:   10

Setting: swf_length - Value:   10

Setting: audit - Value:   error

Setting: LIBRARY_LOCATION - Value:   C:\Libreria\

Setting: HELP_BASE - Value:   http://www.xibo.org.uk/manual-tuttle/

Setting: PHONE_HOME - Value:   Off

Setting: PHONE_HOME_URL - Value:   http://www.xibo.org.uk/stats/track.php

Setting: PHONE_HOME_DATE - Value:   0

Setting: SERVER_MODE - Value:   Production

Setting: MAINTENANCE_ENABLED - Value:   Off

Setting: MAINTENANCE_EMAIL_ALERTS - Value:   On

Setting: MAINTENANCE_KEY - Value:   changeme

Setting: MAINTENANCE_LOG_MAXAGE - Value:   30

Setting: MAINTENANCE_STAT_MAXAGE - Value:   30

Setting: MAINTENANCE_ALERT_TOUT - Value:   12

Setting: SHOW_DISPLAY_AS_VNCLINK - Value:   0

Setting: SHOW_DISPLAY_AS_VNC_TGT - Value:   _top

Setting: MAINTENANCE_ALWAYS_ALERT - Value:   Off

Setting: SCHEDULE_LOOKAHEAD - Value:   On

Setting: REQUIRED_FILES_LOOKAHEAD - Value:   172800

Setting: REGION_OPTIONS_COLOURING - Value:   Permissions Colouring

Setting: LAYOUT_COPY_MEDIA_CHECKB - Value:   Unchecked

Setting: MAX_LICENSED_DISPLAYS - Value:   0

Setting: LIBRARY_MEDIA_UPDATEINALL_CHECKB - Value:   Unchecked

Setting: USER_PASSWORD_POLICY - Value:   

Setting: USER_PASSWORD_ERROR - Value:   

Setting: MODULE_CONFIG_LOCKED_CHECKB - Value:   Unchecked

Setting: LIBRARY_SIZE_LIMIT_KB - Value:   0

Setting: MONTHLY_XMDS_TRANSFER_LIMIT_KB - Value:   0

Setting: DEFAULT_LANGUAGE - Value:   es

Setting: TRANSITION_CONFIG_LOCKED_CHECKB - Value:   Unchecked

Setting: GLOBAL_THEME_NAME - Value:   default

Setting: DEFAULT_LAT - Value:   51.504

Setting: DEFAULT_LONG - Value:   -0.104

Setting: SCHEDULE_WITH_VIEW_PERMISSION - Value:   Yes

Setting: SETTING_IMPORT_ENABLED - Value:   1

Setting: SETTING_LIBRARY_TIDY_ENABLED - Value:   1

Setting: SENDFILE_MODE - Value:   Off

Setting: EMBEDDED_STATUS_WIDGET - Value:   

Setting: PROXY_HOST - Value:   

Setting: PROXY_PORT - Value:   0

Setting: PROXY_AUTH - Value:   

Setting: DATE_FORMAT - Value:   Y-m-d H:i

Setting: DETECT_LANGUAGE - Value:   1

Setting: DEFAULTS_IMPORTED - Value:   1

Setting: FORCE_HTTPS - Value:   0

Setting: ISSUE_STS - Value:   0

Setting: STS_TTL - Value:   600

Setting: MAINTENANCE_ALERTS_FOR_VIEW_USERS - Value:   0

Setting: CALENDAR_TYPE - Value:   Gregorian

**Comment by dasgarner** [comment]
Thanks for posting the logs - but it would be great to post them as a file somewhere we can reference instead (it makes it impossible to see what is happening in the thread).

Your problem is actually solved, its just that Xibo has cached your old result.

If you change the forecast lat/long slightly then your cache will be invalidated and it should work

**Comment by levece** [comment]
thanks that solve my problem

**Comment by dasgarner** [comment]
welcome!

**Comment by xibo-de** [comment]
have no idea

http://www.xibohost01.com/test17x
User: test
Pw test
Layout: Forecast.io

Compare the settings

perhaps again Log Dump

**Comment by jopper1988** [comment]
I have the same problem

**Comment by dasgarner** [comment]
the problem has been solved by the OP - so have you tried following the conversation and repeating the steps?

**Comment by jopper1988** [comment]
I did everything what is said here but nothing works :(

**Comment by dasgarner** [comment]
I don't think your problem is the same as the OP - I've commented on your other issue. Lets leave this one closed.

**Comment by jopper1988** [comment]
ok
