### ISSUE TITLE
Unable to upload media via URL

### ISSUE THREAD

**Issue by leofass** [xibosignage/xibo#2415]
Hello Xibo Team,

We are facing an issue when trying to upload a media via URL under xibo 2.3.8 docker version.
It occurs with any media URL we try.

As you can see on the attached image
![Screenshot_20210209_181202](https://user-images.githubusercontent.com/8985359/107429815-25e87f80-6b03-11eb-8491-9d93cf9eb9b0.png), we filled the URL field with https://perfil.napratica.org.br/assets/v2017/desktop-logado-estilo-trabalho-a1f71fc369d0edf18289273f74f5a5b068bc34520b155c06a84a0c1616ae5571.png
and named the media as 'test', but when we click 'Save', we get the message 'Cannot find media', any other upload method works perfectly, and this same method works fine under xibo 2.3.7 docker version too.

Please, let me know if you need something else to help us to solve this issue.

Thank you and best regards,

**Comment by dasgarner** [comment]
Thank you for your report.

@PeterMis I thought we fixed this already, but I can't find an issue for it anywhere - can you confirm? Thanks.

**Comment by PeterMis** [comment]
Yes I can indeed confirm that we've fixed it already, the 2.3.9 and 3.0.0rc1 releases will have it fixed.

For reference : https://github.com/xibosignage/xibo-cms/commit/1e5c606406d8df31722a3fd21d796d8724465a7d
