### ISSUE TITLE
1.7.1 design format layout upgrade via options menu not working

### ISSUE THREAD

**Issue by hcjsy** [xibosignage/xibo#242]
Editing a layout, and it says this is an old format layout, please considering upgrading using the options menu.

When I click on this, I'm getting a pop up message : Not Found The requested URL /&ajax=true was not found on this server.

**Comment by dasgarner** [comment]
Erm, that is odd... are you using the default theme? (i.e. no changes to Xibo at all, just a vanilla upgrade)?

We might need to connect to your CMS to experience the problem for ourselves - would that be possible?

**Comment by hcjsy** [comment]
yes default theme. you would need to rdp in as its internal

**Comment by jonwitts** [comment]
I am also getting the same error. Just upgraded from 1.4.2 to 1.7.1 today and when trying to upgrade layouts I get the same message. See below:

![xibo-upgrade-display](https://cloud.githubusercontent.com/assets/8962587/6214576/7d998c74-b5f1-11e4-94c7-95c20ead02c6.png)

All default here; no edits to xibo code at all...

Jon

**Comment by solutionssquad** [comment]
Me 3

**Comment by dasgarner** [comment]
are you all upgrades? maybe try clearing the cache?

its the standard form render that happens when all forms load and the file it is trying to load is the same file that renders the designer itself - so it must be there...

**Comment by jonwitts** [comment]
OK... Have just tried from home and I have successfully upgraded all of our templates; must have been cached at work... Odd though as I tried a Ctrl + F5 and multiple browsers too... Anyhow all good for me now.

Thanks,
Jon

**Comment by hcjsy** [comment]
I've done ctrl-f5 and tried it on different browsers , was an upgrade from your last stable version, 1.6.2 ?

**Comment by dasgarner** [comment]
do you have a proxy between yourself and the Xibo install that might be giving you a cached file pre-upgrade?

**Comment by hcjsy** [comment]
no on local lan

**Comment by dasgarner** [comment]
strange :unamused: 

are you familiar enough with Developer Tools to check the network tab and see which pages it is actually requesting?

**Comment by hcjsy** [comment]
the url on the drop down menu for upgrade layout is : http://servername/index.php?p=layout&modify=true&layoutid=10

When I go to developer tools, and network.
Get request with 404 is: http://servername/&ajax=true?_=1424186302281

**Comment by dasgarner** [comment]
the URL should be `index.php?p=layout&q=upgradeForm&layoutId=10` so that does at least explain the error.

I think the linked commit might fix it.

**Comment by hcjsy** [comment]
in my layout.class.php
my url is already set to : index.php?p=layout&q=upgradeForm&layoutId=

**Comment by hcjsy** [comment]
I copied both files from that link and saved them, and now working as expected :)

**Comment by dasgarner** [comment]
great!
