### ISSUE TITLE
Unable to parse media:content elements in RSS feeds.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2423]
CMS Version:
2.3.8, 3.0.0 RC1

Issue:
Create a layout with an RSS ticker widget. Add to the ticker an RSS feed that has media:content elements. These should be able to be returned using the snippet [media:content|image|url]. The tag does not return the images.

Notes:
The issue does not effect CMS 1.8.13.

**Comment by dasgarner** [comment]
This is due to the images in the feed having a query string after them, i.e. `?xyz`
We need to strip the query string from the URL before passing to Intervention Image.
