### ISSUE TITLE
xibo 1.7.0 screensaver not working

### ISSUE THREAD

**Issue by hcjsy** [xibosignage/xibo#243]
I've copied the scr from one of the xibo clients to a computer running 8.1. I've installed the screensaver, but when I click on settings it thinks and does nothing, the same for preview.

**Comment by StephenRoddick** [comment]
I haven't looked at 1.7.0 yet but I'd expect the .scr is a hook into the installed client.  If you simply copy the .scr to a different computer it won't hook int the xibo client because it isn't actually installed.

**Comment by hcjsy** [comment]
ah ok, that's annoying as I dont want to be installing the xibo client on all machines

**Comment by dasgarner** [comment]
Unfortunately it is not possible to just copy one file out of an installation to a new machine and have it work - there are lots of dependencies that need to be in place (and accessible).

The same goes for an EXE - you can't just take it out of its installation folder and pop it anywhere :smile: 

Installing is the only route for now - but we do take your point that a self-contained scr would be nice.
