### ISSUE TITLE
Display Map View

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2433]
Show displays on a map.

Probably a new page, accessible from the Display Admin page.

Each pin on the map could be expanded to show some more details about the Display.

**Comment by Tashamy** [comment]
https://community.xibo.org.uk/t/use-gps-coordonates-to-have-a-map-in-the-admin-console/24348

**Comment by ifarzana** [comment]
The map view of displays are on Develop Natasha, if you would like to have a look please and provide feedback. Thanks
