### ISSUE TITLE
Improve Campaign Layouts assignment

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#2434]
The new implementation will drop displayOrder, being the order of that array the representation of the display order in that campaign. 

That means that for a single layout assignment for a campaign, we only need to send a single ID to the Campaign controller. 

As for the campaign add/edit form, it will receive simple an array of layouts in play order to be rendered. To save it won't need to send the assign and unassing arrays, but only the final array of IDs, that then will be processed by the back-end.

There's also some tweaks that can be made in the UI:

- The sort-able elements have all the same width, making it easier to manipulate, and maybe have them sorted in columns.
- Each element can have a text input stating the numbered order, and on change, move that element to said position, updating all other values.
- Locked elements will be rendered, bot not movable, all the other elements can be positioned before, after, or among them.

### API changes
The API needs to change:

- [x] Remove unassign call
- [x] Modify the assign call to be for a single `layoutId`
- [x] Add an array of `layoutIds` to the add/edit calls, which will be the complete set of layout assignments in order

Add/Edit will still need to check the permissions of the layoutIds provided. The array will include any assignments the user doesn't have direct permissions for, but these should still be allowed by virtue of them already being assigned (need to check quantity of assignments to prevent adding extra).

**Comment by dasgarner** [comment]
Campaign Edit has also got a new parameter called `manageLayouts` which you have to set to 1/true/on to alter the Layout assignments.
