### ISSUE TITLE
Media upload to library: Previously saved empty or duplicate tags issue.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2439]
CMS Version:
2.3.9

Issue:
Incorrectly saved tags from previous CMS versions may cause issues and so should be investigated.

Notes:
Empty or duplicate tags can cause an issue when being validated/saved.

**Comment by dasgarner** [comment]
This is fixed in v3 - in v2 there isn't really much we can do and the user should manually delete the duplicate tags from the tags user interface.
