### ISSUE TITLE
Can't Assign any connet

### ISSUE THREAD

**Issue by Andy2789** [xibosignage/xibo#244]
I unable to assign content to any playlist, design or element. The content uploads to the library ok, but when you select add and then assign nothing happens. So we are currently unable to add any new content to our displays.

**Comment by MarcelErkens** [comment]
same issue here. Can assign a clock, webpage, rss feed, etc, but no Images, movies and or PPT's uploaded or in the library.

CMS =1.7.1 on ubuntu 14.10

**Comment by dasgarner** [comment]
sorry, I think this has been discussed here: #186
