### ISSUE TITLE
Some changes to layouts do not update player schedule

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2442]
CMS Version:
2.3.9

Issue:
Create a layout and add an image from the library. Publish the layout and schedule it to a player. Wait for the player status to be green in the Displays menu. Now checkout the layout, add another image then publish it again. The status of the player remains 
green in the Displays menu, no changes are sent to the player. 

Notes:
- Status page in player lists the previous ID of the layout and continues to show that old version. 
- If you check the Manage logs in CMS, the layout will be missing. 
- You can clear the issue by clearing the display cache, adding/removing a scheduled event or restarting the player. 
- Also seen with webpage widget.
- Adding a different widget type to the layout can stop the issue from occurring.

**Comment by dasgarner** [comment]
I encountered this problem today also.
I add this note because I could not clear it by restarting the player, I had to reschedule or clear the display cache.
