### ISSUE TITLE
Upgrade path

### ISSUE THREAD

**Issue by StephenRoddick** [xibosignage/xibo#245]
Could you please confirm the upgrade path for 1.4.x to 1.7.0.

I expect it will be 1.4.x -> 1.6.x -> 1.7.x.  If you could confirm that it would be appreciated.

**Comment by alexharrington** [comment]
In theory you can go from 1.0 to 1.7 in one step, however 1.7 has a new updater and someone else reported issues going from 1.4 to 1.7, so I would recommend going to 1.6.4 first, then 1.7.1.
