### ISSUE TITLE
Repeating for the 'nth week' of a month does not give the desired outcome

### ISSUE THREAD

**Issue by Tashamy** [xibosignage/xibo#2466]
2.3.9
 When Scheduling an Event and using Repeats, the monthly repeat option of the 'nth week' does not give the desired repeat.

**Comment by dasgarner** [comment]
Please can we have an example to recreate this issue?

**Comment by alexharrington** [comment]
https://community.xibo.org.uk/t/error-when-try-viewing-a-scheduled-events-for-a-display/24776/5

Steps as set out in this users PDF

**Comment by dasgarner** [comment]
To recreate:

![image](https://user-images.githubusercontent.com/10400067/113285915-6bdfe980-92e3-11eb-8d36-e21225012b0d.png)

The 31st is the 5th Wednesday (not many months have these!)

![image](https://user-images.githubusercontent.com/10400067/113285944-74d0bb00-92e3-11eb-90a8-c9d143569af5.png)

1st event is right on the 31st to the 3rd.

Next event created is 4th August which is a Wednesday, but is definitely not the 5th Wednesday

**Comment by alexharrington** [comment]
That's an interesting point then. I took that configuration to mean "the 4th Wednesday each month". Is that not what it does?

**Comment by dasgarner** [comment]
No, its repeat monthly on the nth Wednesday, repeating every N months

The "nth day" is determined by the start day of your event.

The error for the OP I think relates to the fact he is on the 5th Wednesday, which we don't cater for.. I guess we drop back to the 4th Wed on months that don't have a 5th one?

**Comment by alexharrington** [comment]
I'm pretty sure elsewhere we let you have a start event that doesn't fit the sequence.

ie Start Monday 8am, End Monday 5pm, Repeats weekly on Tuesdays - I've checked and that appears to do what it should.

In my view it should make the first event as specified, and then repeat that event on the 4th Weds of the month thereafter.

**Comment by dasgarner** [comment]
If the config is as below:

![image](https://user-images.githubusercontent.com/10400067/113294395-d4809380-92ee-11eb-8e31-52a76657d739.png)

But the month doesn't have 31 days - should there:
 - be an even on the last day of the month
 - be an event on the first day of the next month
 - skip it

My inclination is to skip it, and to apply the same logic to the original problem, i.e. if you select that you want the event on the 5th Wednesday, but there isn't a 5th Wednesday, we skip it.

This brings it more inline with what you get on Google Calendar, where if the option isn't viable, it doesn't present it. (In fact it morphs the "on the 5th Wednesday" to "on the last Wednesday", which would be better).


I think we have enough to investigate this further now, thank you.
