### ISSUE TITLE
Web page Region Border

### ISSUE THREAD

**Issue by chriskemp010** [xibosignage/xibo#247]
I have a Web Page region that appears to have a small border around it since upgrading to 1.7.1

**Comment by dasgarner** [comment]
Can you elaborate?

Do you mean in the CMS, Player, Preview? What's inside it the webpage, what settings do you have?

**Comment by chriskemp010** [comment]
Hello,

In the player. It looks like an iframe  when you've not specifically told it no border.

It's a php page pulling various calendar events from a database. Was fine in 1.6

Cannot get access to a screen shot at moment.


Regards

Chris Kemp
Trust IT Network Engineer
3rd Line IT Support
Thinking Schools Academy Trust

c/o Chatham Grammar School for Boys

Sent from Samsung Mobile


-------- Original message --------
From: Dan Garner
Date:16/02/2015 19:10 (GMT+00:00)
To: xibosignage/xibo
Cc: CHRIS KEMP
Subject: Re: [xibo] Web page Region Border (#247)


Can you elaborate?

Do you mean in the CMS, Player, Preview? What's inside it the webpage, what settings do you have?

—
Reply to this email directly or view it on GitHub<https://github.com/xibosignage/xibo/issues/247#issuecomment-74557827>.

________________________________

This email is from Chatham Grammar School for Boys and any attachments are confidential to the intended recipient(s) and the contents may be legally privileged. It is intended solely for the person(s) to whom it is addressed. If you are not an intended recipient please note that any form of distribution, copying or use of this communication or the information within it is strictly prohibited and may be unlawful, If you have received this communication in error please notify the sender and delete the message.

This email and any attachments cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, delayed, incomplete, or contain viruses. Chatham Grammar School for Boys does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission or the consequences thereof.

Although reasonable precautions are taken to ensure this email and any attachments do not contain any viruses, Chatham Grammar School for Boys cannot accept responsibility for any loss or damage arising from the use of this email or attachments.

Any views or opinions expressed in this email and any attachments are those of the author only and may not necessarily reflect the views of Chatham Grammar School for Boys. Chatham Grammar School for Boys accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided. This email and any attachments do not create any legally binding rights or obligations whatsoever.

Chatham Grammar School for Boys, Holcombe, Letchworth Avenue, Chatham, ME4 6JB, +44 (0)1634 830083.
The Chatham Grammar School for Boys is part of The Thinking Schools Academy Trust, The Rochester Grammar School, Maidstone Road, Rochester, Kent, ME1 3BY. Telephone: +44 (0)1634 843049. Company Limited by Guarantee Registered in England and Wales. Company Number: 07359755.

**Comment by dasgarner** [comment]
I think the attached file will fix it - can you try replacing the `HtmlTemplate.html` file in your CMS installation. you will need to edit your layout in some way to trigger the download to the player.

**Comment by chriskemp010** [comment]
Hello,
That doesn't seem to have fixed it.  I can confirm that the relevant HTML file in the client library has updated with the extra 3 lines that refer to the iframe border.

![xiboiframeerror](https://cloud.githubusercontent.com/assets/10992313/6412442/beea0d92-be7b-11e4-8fc9-1376060970a1.png)

**Comment by dasgarner** [comment]
Ca you dropbox us the HTML file in the player library? We will have a play with it and see what needs to be done to remove the borders.

**Comment by chriskemp010** [comment]
Here are 2 HTML files that basically load in Intranet pages running php scripts.

https://www.dropbox.com/l/vDhBGDDh4GlUq75ih60eht
https://www.dropbox.com/l/2HdOkutHCGIMmfbY0hgCSq

interestingly, they display fine on a screensaver client.

**Comment by dasgarner** [comment]
Are these running on XP? I have no idea why they would work OK on a screensaver client - unless they are running on a different PC/OS?

You could try the attached patch to `webpage.module.php`

**Comment by chriskemp010** [comment]
Hello, the frameborder setting in webpage.module.php has sorted it.

**Comment by dasgarner** [comment]
Fantastic - thanks for the feedback.
