### ISSUE TITLE
Schedule: a midnight to midnight daypart event appears on both days

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2473]
For example: 

![image](https://user-images.githubusercontent.com/10400067/114266810-455f3400-99f0-11eb-8a4f-9c56361c9ea3.png)

**Comment by dasgarner** [comment]
@maurofmferrao i've fixed this I think, but i'm not confident in the logic - please can you take a look to see if you agree? Thanks

**Comment by maurofmferrao** [comment]
> @maurofmferrao i've fixed this I think, but i'm not confident in the logic - please can you take a look to see if you agree? Thanks

I believe that will fix it indeed :)
