### ISSUE TITLE
Question: Can MariaDB be used instead of MySQL?

### ISSUE THREAD

**Issue by jokay** [xibosignage/xibo#2475]
Is it possible to use **MariaDB** instead of **MySQL** or is there any limitation which makes MySQL a requirement?

**Comment by alexharrington** [comment]
We don't test with MariaDB, but as long as it's a version of it that is compatible with MySQL 5.7 then in theory it would work.

We use GitHub issues for logging and resolving verified bugs only. If you have general questions, or need support, please use our Community site - https://community.xibo.org.uk
