### ISSUE TITLE
Cleanup stat table

### ISSUE THREAD

**Issue by jokay** [xibosignage/xibo#2477]
Is there a good way to delete old data in the `stat` table as the backup becomes bigger and bigger 🧐 

Or is there some kind of retention policy which can be set?

**Comment by alexharrington** [comment]
There's an archive task to do that which you can configure. Please can I ask that you direct support requests to our Community site. We cannot provide you with support here. https://community.xibo.org.uk

**Comment by jokay** [comment]
Follow-up https://community.xibo.org.uk/t/cleanup-tables-stats-auditlog-log/24872.
