### ISSUE TITLE
2FA setup returns error.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2480]
CMS Version: v3.0.0 RC3

Issue: When setting up 2FA for a User account, the following error is returned:

```Unable to find template "email-template.twig.twig"```

Note: The customer was attempting to set up email 2FA.

**Comment by frazer-xibo** [comment]
If you enable the Password Reminder feature in the CMS, and then click on the 'Forgotten your password?' link on the login page and click 'Send Reset', the same error can be seen: _Unable to find template "email-template.twig.twig"_
