### ISSUE TITLE
Deprecate: web based maintenance route

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2481]
CMS versions earlier than 1.7 had a maintenance routine which was called via a URL and protected with a maintenance key, etc. This was largely replaced in 1.8 with the Task runner and two new maintenance tasks, Daily and Hourly.

The maintenance via URL mechanism has been maintained all the way through 1.8 and v2 for backwards compatibility and for users without any way to run the Task Runner.

We would like to deprecate the web based maintenance route for 3.1 as part of a wider refactoring project, and would remove:
 - the web route
 - the setting for protecting the web route (maintenance key)

The documentation related to it would need to be modified.

We want to do this because it means tasks only have to run in one place, and that maintenance related activities can ultimately be split out into separate tasks to make them more efficient. It also means all users will have access to things like stats archive, which currently does not run through the maintenance web route.

**Comment by dasgarner** [comment]
@alexharrington I suspect you will have input as to whether or not this can be done - and/or if it needs to be replaced with a way to call the task runner from a web route.

**Comment by alexharrington** [comment]
My feeling is it can go as you propose. Thanks.
