### ISSUE TITLE
Edit Layout window in designer does not show all columns when made visible

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2482]
CMS Version: 3.0.0 RC3

Improvement: Open a layout in designer and go to the Actions tab on the Edit layout window. If you click the column visibility button and make all columns visible, not all columns can be seen if the page is scaled to 100%.

Notes: I can see all of the columns if I zoom the page out to 75%.

**Comment by maurofmferrao** [comment]
The Action tab doesn't have a Column visibility option now, so it seems like this bug report was for a deprecated feature
