### ISSUE TITLE
Default duration on widgets in drawer are not obeyed.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo#2484]
Player Version: 
300.2 Alpha

Issue: 
Create a layout that has a widget in a region and another in the drawer with duration set to default. Now set up a Navigate to Widget action so that when the region widget is clicked it will display the widget in the drawer. Clicking the screen will cause the widget in the drawer to appear but only for a second, maybe two before returning to the region widget.

Notes: 
- Tested using an image widget in the drawer, which had a default duration of 10 seconds.
- Manually setting a duration resolves the issue.

**Comment by dasgarner** [comment]
I have transferred this issue to the CMS as I think its likely the duration is wrong in the XLF file.

**Comment by dasgarner** [comment]
Unfortunately I can't recreate this issue - perhaps it has been solved by some other change in the meantime. We can do another round of player testing to see if this still occurs.

**Comment by DanielBW1** [comment]
Thank you Dan, I will give this another test at a later date and let you know if I can recreate it 👍

**Comment by dasgarner** [comment]
The moment I remove it from the milestone, I manage to recreate it.

I have a weather widget in the drawer showing a duration of 10 seconds, but in the XLF it shows as follows:

```
<media id="6203" type="forecastio" render="html" duration="1" useDuration="0" fromDt="1970-01-01 01:00:00" toDt="2038-01-19 03:14:07" enableStat="1">
```

On the player then, it only gets shown for 1 second before returning to the prior normal widget.

**Comment by DanielBW1** [comment]
Strange, I couldn't replicate it on one of the newer players, 300.5 I think? But if you have now seen it then I guess it was still lingering there and I missed it the second time. 🙂

**Comment by dasgarner** [comment]
It was a CMS issue when there was only 1 item in the drawer - all sorted now in any case. Thanks for your double checking.
