### ISSUE TITLE
Displays: multi-select menu, hard to see the item you want

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2515]
Can we organise this menu better? It would be nice if the options were put in logical groups with dividers between them, etc. If it followed the same order as the row menu, with dividers, etc that would be fine I think.

![image](https://user-images.githubusercontent.com/10400067/119330199-dd05a280-bc7d-11eb-82e5-7b015e931a8c.png)

**Comment by maurofmferrao** [comment]
The multi-select buttons that are being copied to the multi select option also need a fix. Pages like Tasks grid are showing empty drop ups

![image](https://user-images.githubusercontent.com/18596680/122063451-2e6e0100-cde8-11eb-9cf4-1b3f1722ca6f.png)
