### ISSUE TITLE
Licensing email address not updating

### ISSUE THREAD

**Issue by andyblackham** [xibosignage/xibo#253]
When I first setup the CMS I entered an email address for client licensing purposes.
Now I actually want to deploy the server for public trial, I want to use a different address.

I've updated the CMS setting and saved it, but when I go to the Android Xibo client, the previous email address still shows.

So, I don't seem able to license the client (about says True (trial).

**Comment by dasgarner** [comment]
Please contact us via our help desk for Android issues. Thanks!
