### ISSUE TITLE
Library shows old revisions

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2540]
Upload an image, edit the image, upload a replacement, do not delete old revisions, both files show up in the library.

**Comment by dasgarner** [comment]
Also a problem in 2.3.10 - OP reports it was ok in 2.3.6

**Comment by PeterMis** [comment]
Apologies for the confusion, this seems to be indeed v3 only, in 2.3.x we have default for the isEdited filter, which isn't the case in v3 - I will change the milestone and get that fixed.
