### ISSUE TITLE
3.0.0 docker installation: mysql container fails to start

### ISSUE THREAD

**Issue by sergey-selivanov** [xibosignage/xibo#2542]
In both xibo-docker.zip and xibo-docker.tar.gz files provided under 3.0.0 release, there are improper double quotes in docker-compose.yml around a mysqld command, like \\\ and // instead of straight ones lke || . This prevents mysql container to start, with cycling errors.

```
diff docker-compose.yml docker-compose.yml.orig
12c12
<         command: mysqld --sql_mode="ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
---
>         command: mysqld --sql_mode=“ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION”

```

**Comment by dasgarner** [comment]
Thank you very much, this was an attempt to fix another problem we had with upgrading. I've rolled back the change and will republish the release.

Your report is much appreciated!

**Comment by sergey-selivanov** [comment]
Glad to help, thanks!
