### ISSUE TITLE
RSS Ticker only showing one item

### ISSUE THREAD

**Issue by jbirdkerr** [xibosignage/xibo#255]
I would like to display a ticker that displays the 5 newest items in an RSS feed in a Marquee. No matter what RSS feed I use, the ticker will only display the newest item in the feed repeatedly. The feed has other items in it, but Xibo will not display any of them. Any ideas? I've included my current settings below.

Version: 1.7.1

General Tab:
* Feed URL: http://feeds.techzine.nl/techzine/mixed
* Name: News
* Duration: 3
* Effect: Marquee Left

Appearance:
* Template: Title Only

Format:
* Speed: 5
* Text Direction: LTR
* Number of Items: 5
* Items per page: 1
* Take items from the: Start of the Feed
* Duration is per item: checked

Advanced:
Update interval: tried 0 & 120

Any help would be greatly appreciated!

Thanks,
Justin

**Comment by dasgarner** [comment]
Sorry to report that it seems to work here.... [this is my layout](https://dl.dropboxusercontent.com/u/353651/export_255.zip) if you wanted to try and import it to see if I did anything differently.

**Comment by jbirdkerr** [comment]
Thanks for the help. Looks like "Show items side-by-side" was checked under Advanced. Once I unchecked, the RSS feed worked fine. Thanks for your help, dasgarner!
