### ISSUE TITLE
Layouts and screens disapear after migration from 3.0.0-rc3 to 3.0.0

### ISSUE THREAD

**Issue by oteixido** [xibosignage/xibo#2553]
Dear.

I've upgraded from release 3.0.0-rc3 to release 3.0.0. Before upgrading, I saw layouts and screens, but after upgrading I can't see them. I have upgraded twice with the same result.

Finally, I found that the solution is changing language from Catalan(ca) to English (en_GB).

I've been looking for a related issue in 3.0.0 release notes, but I have not found anything.

Thanks in advance,
Oriol.

**Comment by PeterMis** [comment]
This looks like an issue with escaping the translations in both of these pages, we will make sure to fix this in 3.0.1.

Thank you for bringing this to our attention!
