### ISSUE TITLE
jpg images won't display on android client

### ISSUE THREAD

**Issue by kb2faf** [xibosignage/xibo#259]
Here is the error message.  prepareImage - Exception. Ex = null  

This starting occurring after upgrading from 1.6.4 to 1.7.0.

Any layouts that had been designed before the upgrade, will still correctly display the jpg image.  Any changes or uploading new jpg's to the library and then placing them in a layout will not display.  

Suggestions?

Thank you

Chris

**Comment by dasgarner** [comment]
Sorry, you need to contact Spring Signage for Android support.
