### ISSUE TITLE
1.7 RC1 - Chage Change formatting time downtime 

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#26]
Change formatting time downtime for hours or minutes. This in seconds, generating huge numbers and meaningless to the end user.

In my opinion in HH: MM would be perfect.

**Comment by dasgarner** [comment]
Downtime? You mean "Availability" on the statistics page?

HH:MM is not something that can be scaled on a chart, although we may be able to format the tool tip. Perhaps the scale should be in minutes?

**Comment by laercionit** [comment]
This DAN, sorry.
Availability "on the statistics page....

Scale in minutes and fomat show on the CMS to HH: MM.
This is possible already in RC1?

**Comment by dasgarner** [comment]
No - I will work that in now!
