### ISSUE TITLE
Text Media Setting to "not chunk" paragraphs and items

### ISSUE THREAD

**Issue by MedusaDelft** [xibosignage/xibo#260]
When I write some text media, CK editor is automatically putitng text in paragraphs. I guess these paragraphs are causing my text on the client being displayed in steps and the the line-breaks. 

Eg:
![image](https://cloud.githubusercontent.com/assets/10947534/6199082/6aa1e672-b42d-11e4-87fd-fe6967bbea62.png)

If I manually create only one <p> tag with all my text, it works the way I want it. Not sure if this is a bug, but the manual doesn't say anything about this behaviour (http://www.xibo.org.uk/manual/en/media_module_text.html).

**Comment by dasgarner** [comment]
What is it about the end display of it that you don't want?

If you have an effect selected which is designed to show items in a queue, then it will break them up and do that. If you dont want that you can set the effect to a continual effect (or no effect) and the output will be exactly as you see.

The manual is not as good as it needs to be, sorry.

**Comment by MedusaDelft** [comment]
Ah, ok, now I understand that this behaviour is by design. I'll update the CKeditor generated html to get the effect I want and explain to my client that he can not have what he wants without knowing about HTML. Thanks!

**Comment by dasgarner** [comment]
Well, maybe it warrants a check box - I am open to suggestions.... what did you want it to do?

**Comment by MedusaDelft** [comment]
My text contained several type-sizes. I wanted the whole text to to scroll in at once, but default CKeditor creates seperate paragraphs for each line.  Now I've put all in one-div, which works too (but a bit more difficult to explain to my customer).

**Comment by dasgarner** [comment]
Ah, I see what you mean - it would be preferable in your case to scroll in without "chunking" (for the want of a better word)
