### ISSUE TITLE
Media text: text in black opens on black background

### ISSUE THREAD

**Issue by MedusaDelft** [xibosignage/xibo#262]
CKeditor shows black text on black background when editting. Switching to 'source' and 'back' shows the text on white.

**Comment by Speedy-Gonzalez** [comment]
See issue #179.

**Comment by MedusaDelft** [comment]
Yes, probably similair. Couldn't make up if your issue was on edit too. Sorry if it is a duplicate.

**Comment by dasgarner** [comment]
Its screwed on edit and I don't know how to fix it...

When CKEditor switches between source and visual views it resets the background color of the text area.

**Comment by MedusaDelft** [comment]
I suppose it’s a bug in CKeditor?  I noticed that the  .cke_wysiwyg_div { background-color: #fff; }  was not active on opening the editor (hence the black background), but switching to source it is. Switching back to wysiwyg, it is still active.

I’ve made a change to a property in   /skins/moono/editor.css:

.cke_wysiwyg_frame,.cke_wysiwyg_div{background-color:transparent}

It was ‘#FFF’.  That seems to work, at least in Chrome. Have not checked others.

**Comment by dasgarner** [comment]
This is what the CMS does when CKEditor loads:

``` javascript
$("#cke_ta_text .cke_contents").css({
    background: $('#layout').css('background-color');
});
```

Perhaps that is the wrong approach - i'm not sure.

**Comment by Speedy-Gonzalez** [comment]
If I understand right, you just only set the background color of the editor depending on the layout background color.

As far as I have figured this out, the font color is always set through the theme/default/libraries/ckeditor/contents.css (```color: #333```).

@dasgarner You said in #179:
>This is set by the JavaScript that loads the text editor - it is supposed to be a complimentary colour and depends on your background colour.
>
>The bug is that the text field opens empty - it should open with a
>
>that contains a replaceable #Color# tag

So there is already JavaScript code for setting the font color or do you mean, setting the background color, like you mentioned above?

**Comment by dasgarner** [comment]
The background colour is always set according to the layout background colour, correct.

The foreground colour is set to a complimentary colour, **if the template is being switched, or we are a new item**.

The code is all in the `text_callback` of `xibo-forms.js`

``` javascript
       // Set something sensible based on the color of the layout background
        var color = $c.complement($("#layout").data().backgroundColor);

        // Get the current template selected
        var templateId = $("#templateId").val();
            
        $.each($('.bootbox').data().extra, function(index, value) {
            if (value.id == templateId) {
                // Substitute the #Color# references with the suggested complimentary color
                $("#ta_text").val(value.template.replace(/#Color#/g, color));
                $("#ta_css").val(value.css);
            }
        });
```

You see that it relies on the `#Color#` template tag in the template to know where to switch out (this is currently missing, hence the other bug).

**Comment by Speedy-Gonzalez** [comment]
Thanks. I'll have a look at this, but I never worked with CKEditor yet, so it will take a while.

What confuses me a little bit is that we don't have a theme/default/libraries/ckeditor/adapter folder with the jQuery Adapter. See http://docs.ckeditor.com/#!/guide/dev_jquery.

Running the CKEditor builder (tested with standard and full preset) gives me a ZIP-Archive with an adapter folder and the jQuery adapter file.

**Comment by dasgarner** [comment]
I'm not using the jQuery adaptor - couldn't get the thing to work originally.

It feels like I upgrade CKEditor with every other release (which I suppose does make some sense!!) - I am happy for that to happen, provided the functionality remains the same. Is there anything in particular in the release notes that we are interested in?

**Comment by Speedy-Gonzalez** [comment]
I have opened another [pull request](https://github.com/xibosignage/xibo-cms/pull/35) (with an alternative (better) solution and closed the other pull request). This should fix this problem.
