### ISSUE TITLE
Background images aren't checked for size rules

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2627]
Take the same oversized image and try to upload it in a Region and as a Layout Background image. In the first case layout publish will be prevented, in the second case it will be allowed. It should be prevented in both cases.

**Comment by maurofmferrao** [comment]
I've tested this and I could publish with the image as an element, but both image in Region (Playlist) and Layout Background failed to Publish.

So we need to make sure we also prevent publishing with an oversized image as Element right @dasgarner ?
