### ISSUE TITLE
Dataset Insert image

### ISSUE THREAD

**Issue by Carlos-Costa** [xibosignage/xibo#264]
Hello,

How to insert a image im Dataset field..?

Can you give me a example..?

Thank You

Carlos Costa

**Comment by vendelec** [comment]
this feature is not supported yet.
I have asked the same question and got that answer !

**Comment by Carlos-Costa** [comment]
Thank you... if you put a link from web for an image, it works... but you cant insert from media library...

**Comment by Carlos-Costa** [comment]
Like http://www.xxx.com/image.jpg

**Comment by dasgarner** [comment]
It is designed to download and cache images from the web - the functionality to insert images from the library hasn't been developed yet (it wasn't actually requested until recently)
