### ISSUE TITLE
Investigate upgrading pdfjs for the PDF widget

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2648]
There are a number of changes/fixes we could take advantage of.

**Comment by dasgarner** [comment]
The furthest we can go back is v2.3.200 because anything after that uses `() =>` syntax and therefore drops support for IE11 and some early versions of android webview.

Missing commit: https://github.com/dasgarner/xibo-cms/commit/9149a4944ab9e844589af03496b51329f1a26b6a

**Comment by dasgarner** [comment]
@maurofmferrao sorry to share this one with you, but I think you did some work on paging for the PDF widget? If that is correct, please can you verify that this bump to the pdfjs version doesn't break/impact that work? Thanks.

**Comment by maurofmferrao** [comment]
The only thing that was changed to fix PDF duration was the XHR status handling for the `xiboIC.setWidgetDuration` call, so I'm pretty sure that the new code for pdfjs doesn't affect that :)

**Comment by dasgarner** [comment]
Great, thanks for confirming!
