### ISSUE TITLE
Layout Import : incorrect check for which method should be used

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#2649]
We incorrectly check region/widget actions on the Layout, it seems to happen AFTER we decide which way the Layout should be loaded (by json or xlf).

Which in cases where there are no drawers and no actions directly on the Layout object, will result in the import via xlf, which means certain bits might be missing - actions are only imported when we use loadByJson method.

Additionally I think we should import Layout Code when loading via xlf, that seems to be missing completely.

**Comment by dasgarner** [comment]
Should we consider always importing by json if the file is present? Are there any disadvantages to that?
