### ISSUE TITLE
Xibo on Android

### ISSUE THREAD

**Issue by chorata** [xibosignage/xibo#265]
Hello to Xibo team,

Оur company is testing the Xibo on Android with the new versions of Xibo(Server is Version 1.7.0 and cilent is Xibo_for_Android_v1.7_R52.apk)

We have a issue and if you can help before we go production with Xibo on android.
So the issue is that when we put a web page of our design on the screen and put a flash on the web page the flash is load with green arrow down and it is not playing automatic. What can we do and why is happening?

thanks very much for your support

**Comment by chorata** [comment]
we updated all test servers to 1.7.1, but still the same thing the flash is load with green arrow down and it is not playing automatic.

**Comment by andyblackham** [comment]
Does your Android device have flash player installed?
If you view the web page in the standard web browser does it display properly??
andy

**Comment by chorata** [comment]
"Does your Android device have flash player installed?"Yes i have install adobe flash player for android.
"If you view the web page in the standard web browser does it display properly??" Yes

**Comment by dasgarner** [comment]
Unfortuantely Flash is not supported on Xibo for Android
