### ISSUE TITLE
Duration field allows you to enter . or ,  (dot / comma) but removes it on save without warning

### ISSUE THREAD

**Issue by MedusaDelft** [xibosignage/xibo#266]
When I enter a duration for images (but I suspect other media items have the same behaviour), like  2.5 seconds, the value is saved normally only to discover later that the duration is now 25 seconds (!). A warning and not saving would be nice, or saving and a warning afterwards. It doesn't seem to matter if a dot or a comma is entered. (XiboCMS 1.7.1)

**Comment by dasgarner** [comment]
well, the sanitization library is converting it to an int, I suppose it should be erroring when its not an int
