### ISSUE TITLE
Schedule Multiple Events (same time)

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#267]
Hello,

Dan, I could not quite understand the system manual.

Today, when I want to run several layouts in a row, I need to create a campaign, enter the layouts in their respective orders and schedule the campaign. This feature works very well.

When you create multiple schedules for the whole day, according to the image, only the first layout (Display Order 1) runs, the others are downloaded to the display but do not run. How not know if this correct, I decided to create this issue.

Note: I am not using priority on any events

![image](https://cloud.githubusercontent.com/assets/325662/6203986/7bc6bdca-b521-11e4-9255-7ea2e98d2e60.png)

**Comment by laercionit** [comment]
Do not know how, but it worked now!
Edited orders again, and it worked.
There was no item with the same number in the ordering, but did not work, after editing some events, began operating.

**Comment by laercionit** [comment]
It has something wrong, did some more schedules of events and did not work.
I'm testing in windows and android.

**Comment by dasgarner** [comment]
It will play them in rotation in the order you specify, unless there is something wrong with any of the layouts, in which case those will be removed from the rotation.

Nothing has changed in this regard in the new version - its all exactly the same as it has been for years.

**Comment by laercionit** [comment]
Hello Dan,

I will do more tests then, shut the issue and I will updating the information of the tests. Thanks again for the guidelines.
