### ISSUE TITLE
Multiple Layout Editor tweaks

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#2681]
- [x] Folder button doesn't show Label when replacing Media
<img src="https://user-images.githubusercontent.com/18596680/145558329-baf06953-b11a-41b8-a598-cf0542b326c9.png" height="200">

- [x] Breadcrumb: Prevent edit region "move" on a Published layout
- [x] Breadcrumb: Disable Widget click (and refresh)
- [x] Breadcrumb breaks selection (+editing) of Drawer widgets
- [x] Create upload button for Audio, Image and Video
- [x] Prevent Properties Panel form load for !enabled modules ( and show message )
- [x] Disable toolbar features (Audio, Video, Others,..) based on Disabled modules
- [x] Show the duration for Audio+Video modules for each preview card

**Comment by dasgarner** [comment]
It doesn't seem possible to edit a widget in the drawer.
