### ISSUE TITLE
Docker Development Environment setup - no user on first start

### ISSUE THREAD

**Issue by SiSa2106** [xibosignage/xibo#2687]
You did a real great job by providing these cool Digital Signage Tool.

As I cloned it and tried to run it there was one big problem, not mentioned anywhere (following the exact dev-steps to get the containers running with Docker.

But there was always an Error in the LogIn (or better say, where the input filed would be expected) saying that
fontCKEditorConfig returning null instead of a string

So I commented line 132 in /xibo-cms/lib/Middleware/Theme.php out 
$view['ckeditorConfig'] = $container->get('mediaService')->setUser($container->get('user'))->fontCKEditorConfig(RouteContext::fromRequest($request)->getRouteParser());

out and it work as expected without any errors.

Was a little searching and try-and-error work but finally it worked (returned null because no user was found - first start)

maybe that could be a little help and help other developers (maybe noobs in that topic like I am) to fix that bug and get all working perfectly.

:)

But to be honest, you are doing a really, really, really great work with Xibo :)

**Comment by dasgarner** [comment]
Thanks for reporting this issue @SiSa2106 - by the way if you want to run in production you don't need to clone the repository - just grab the release docker files and run those.

---------------

@PeterMis when you get some time before beta release, it would be interesting to see why the `entrypoint.sh` didn't add a user on first start. It should do if the DB doesn't exist.

**Comment by PeterMis** [comment]
We couldn't recreate this and the code looks like it should always add a user on fresh installation.

That said we will leave this issue open, just without milestone for now.
