### ISSUE TITLE
No images on media-rss-with-left-hand-text.template.json

### ISSUE THREAD

**Issue by waarsenburg** [xibosignage/xibo#269]
No images appear when using the media-rss-with-left-hand-text.template.json. Probable cause: wrong image definition in template, combined with \r\n characters in definition.
In media-rss-with-left-hand-text.template.json:
<SNIP>
:"<div class=\"image\">[linkfoto|image]\r\n<div class=\"cycle-overlay\">......
</SNIP>
Compare with media-rss-with-title.template.json:
<SNIP>
"<div class=\"image\">[Link|image]<div class=\"cycle-overlay\">......
</SNIP>
Changing [linkfoto|image] to [Link|image] and removing \r\n solved it for me.
Tested with http://www.nu.nl/rss

**Comment by dasgarner** [comment]
Thanks for report and analysis - tagged bug for fix.
