### ISSUE TITLE
Cannot Delete Empty Folder

### ISSUE THREAD

**Issue by billc1965** [xibosignage/xibo#2696]
Version 3.0.3

If I create a folder and put content in it, then move that content to another folder, in some instances I cannot delete that now-empty folder.

I created a folder named **\content\layout-holidays** and put five layouts in that folder with no issue. Then I realized that I should have more efficiently made that **\content\layouts\holidays** so created that and then moved those five layouts into that folder. I cannot delete the **\content\layouts\layout-holidays** folder. I am 100% sure there is no other content type in that folder. I have seen this once before and have an "orphaned" folder hanging off the root.

- In some cases I can remove all content and successfully remove the folder.
- I have restarted the server and tried to delete them with no success.
- I have tried to delete these folders over several days with no success.
- I am able to rename these folders with no issue.
- I have tried to put content in those folders and then remove that content; still no ability to delete the empty folder.
- It is likely coincidence that this has happened with layouts in both cases but perhaps not.

**Comment by PeterMis** [comment]
Hey there,

I'd suggest updating your CMS to the newest release (3.0.5), you've likely encountered this bug with selectFolder/Edit Layout change folder - https://github.com/xibosignage/xibo/issues/2616

Once you update your CMS, if you move the affected Layouts between folders again, it should update folder links of all relevant content of the Layout.

If any issues persist after upgrade, please post your question/bug report on our Community site: https://community.xibo.org.uk

**Comment by billc1965** [comment]
Thank you. I looked for a known bug but must have missed it, so apologies for that. Will update and retry; I'll advise if I continue to see an issue.
