### ISSUE TITLE
Interactive Signage

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#27]
Issue to collect thoughts and feedback on what Interactive Signage should be available within Xibo. We have two main thoughts at present:

## Touch Screen Interaction
Providing a mechanism in Xibo for defining click-able areas and then a way to respond to those clicks and do certain things.

## Event Driven Actions
Provide a mechanism to respond to outside events, these could be generated by a helper application for each type of event.

 - An example could be a signal received over a COM port
 - A socket connection
 - Listening to a HTTP page for a change in status (perhaps consuming a JSON string)
 - Responding to removable media being plugged in (playback without a connected CMS)
 - Listening to XMDS for instructions to do something

## Actions
Support for:
 - Counter Module
 - Loading new items into a region
 - Loading a new Playlist (#1) into a region
 - Moving forwards and backwards in the schedule
 - Loading an entire layout
 - Resuming the interrupted region / layout from exactly where it was (mid video for example)

**Comment by pubblisoft** [comment]
Chrome App client driven: 

I have already developed three years ago an app built-in chrome for digital signage, but it was not a good solution. In public place there is not enough interaction control with chrome and a javascript chrome app works slowly. Basically it's hard to build a safe kiosk in chrome.

**Comment by pubblisoft** [comment]
Chrome App signage:

https://github.com/cooperhewitt/chromecast-signage

or

chromecast.com by google

or 

https://code.google.com/p/risevision/source/checkout

or 

http://www.novisign.com/android/android-based-digital-signage/

... anymore ?

**Comment by dasgarner** [comment]
Please can we keep separate conversations on separate threads? This is nothing to do with a Chrome Client - this is to do with interactive signage.

I know you want to develop touch events into a Xibo client, which would be great. If you want to develop a new client at the same time - that is also great - but #29 is the place it discuss this.

**Comment by supportreq** [comment]
This will really take xibo to the next level which will accept inputs from the user and become a truly interactive signage

**Comment by pubblisoft** [comment]
I think The first simple step should be to modify The click reaction in The client. For example to show a web popup page on click.

**Comment by dasgarner** [comment]
It doesn't make any sense implementing tiny bits of a feature at one time. We need to fully specify what is required in a blueprint and then implement the feature in larger logical milestones. This makes implementing, testing and most importantly supporting the change far simpler.

**Comment by dasgarner** [comment]
Moved further discussion to https://community.xibo.org.uk/t/interactive-signage/103. Thanks for the comments so far.
