### ISSUE TITLE
Connectors: flag to show/hide pre-installed connectors

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2708]
A white label may want to hide some of the connectors in addition to disabling them.

**Comment by PeterMis** [comment]
I didn't see this issue, however it is fixed in my PR, commit reference - https://github.com/PeterMis/xibo-cms/commit/c36a43f288684b17948bb6537e6f9e986367bb6d

added isVisible flag to connectors table and handling where needed.
