### ISSUE TITLE
Widgets: pre-navigate off screen

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2715]
We have put in some ground works for pre-navigation of widgets so that a player can load a widget in readiness before "starting it" when it gets moved on screen.

Currently this is available in Android on the Text widget (without any paging) and on the embedded widget with an option called `isPreNavigate`.

Before we can take advantage of this option more generally, we need to adapt widgets so that they render their first frame and then "pause" until told they are visible.

From the player side, if we're loading the web widget off screen we should append `&visible=0` to the URL we load to activate this mode. Once we've moved the widget on screen, we should call `xiboIC.setVisible()` to start the rendering.

**Comment by dasgarner** [comment]
A good example for where this currently doesn't work well is ironically the text widget. The text in this widget only gets rendered after setVisible has been called. So it gets rendered off screen as a blank widget, moved on screen, and then rendered.

What should happen is that the first text item is fully rendered __before__ setVisible is called.

**Comment by ifarzana** [comment]
This is being handled by the changes in V4.
