### ISSUE TITLE
Layout/Playlist Editor: minimum resolution

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2720]
We should decide where we draw the line for effective Layout Editor usage and swap the UI to show a message saying "Layout Editor not supported at this resolution", or simplify the editor down to a usable set of features.

**Comment by myymi** [comment]
This is bad and should not be forced. Some of my users still have just fullhd monitors and they get an error.

**Comment by maurofmferrao** [comment]
> This is bad and should not be forced. Some of my users still have just fullhd monitors and they get an error.

Thank you for your feedback! We did some research for most used resolutions and opted to display the message for window sizes below 1200px in width and 600px in height. This means that Full-HD (1920x1080) should be supported by the editor, even with browser toolbars or sidebars.

Could you provide an example of the resolution and workspace setup where the error is occurring? That will help us investigate further.

**Comment by myymi** [comment]
Good day. When you use Windows with 150% scaling on FullHD monitor, you'll stumble into this. I have some colleagues with not the greatest eyesight and they have constant trouble. 
So basically it's acessibiliy issue. 
If it does not break something or have some performane penalties, please don't force this minimum resolution. 
As It's basically piece of arbirtary code that doesn't have any real purpose other than just saying "you have to use bigger monitor!", it's counter-productive. 
I figure that users should have choice to use whatever resolution as long as they are happy using it.

**Comment by dasgarner** [comment]
I understand your position, but we have to balance that against the complaints of "the editor doesn't work" which turn out to be people trying to use it on mobile/tablet which are not supported platforms. The reality is that the editor is a visual tool which we have designed to work at a minimum resolution.

Perhaps we can find a middle ground whereby we display a dismissible notice instead of what we've currently done. @maurofmferrao please can you take the action?

**Comment by myymi** [comment]
Thank you for suggestion! Dismissable notice would be great middle ground for accessibility for those not so lucky in optical department.

**Comment by maurofmferrao** [comment]
I've created a new issue so we can change the way we present that information for the users to be able to turn the warning off and keep using the editor: https://github.com/xibosignage/xibo/issues/3512

Thank you for your feedback @myymi !
