### ISSUE TITLE
XMDS Soap Error

### ISSUE THREAD

**Issue by mymactek** [xibosignage/xibo#274]
have this error ... Multiple times on " LOG "
Anyway to fix it ?

Thanks guys !

2576099	2015-02-16 09:04:56	CMS			<errormsg>Undefined variable: type</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\dssserver\www\lib\service\xmdssoap4.class.php</scriptname>
<scriptlinenum>932</scriptlinenum>
2576098	2015-02-16 09:04:43	CMS			<errormsg>Undefined variable: type</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\dssserver\www\lib\service\xmdssoap4.class.php</scriptname>
<scriptlinenum>932</scriptlinenum>
2576097	2015-02-16 09:04:30	CMS			<errormsg>Undefined variable: type</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>C:\dssserver\www\lib\service\xmdssoap4.class.php</scriptname>
<scriptlinenum>932</scriptlinenum>

**Comment by dasgarner** [comment]
you can take the latest version of that file from my fork of xibo-cms, develop and replace your installed one with it.

**Comment by dasgarner** [comment]
or you can set your server to Production mode and the log level to Error (as it should be when running a production system)

**Comment by mymactek** [comment]
Copied and over-wrote the contents of the file.
Logged back in, and ALL logs were cleared.
So far no XMDS errors ...

Thanks

**Comment by mymactek** [comment]
Ok still getting the same error, just took a few min to populate.
Server is in production mode, with Log level to Error.

Did copy and replace the XMDS Soap 4 file contents.

Please advise.
Thanks

**Comment by mymactek** [comment]
2614239	2015-02-17 09:12:59	CMS			<errormsg>DOMDocument::loadXML(): Couldn't find end of Start Tag html line 1 in Entity, line: 1</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\dssserver\www\lib\service\xmdssoap4.class.php</scriptname>
<scriptlinenum>757</scriptlinenum>
2614238	2015-02-17 09:12:59	CMS			<errormsg>DOMDocument::loadXML(): attributes construct error in Entity, line: 1</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\dssserver\www\lib\service\xmdssoap4.class.php</scriptname>
<scriptlinenum>757</scriptlinenum>

**Comment by mymactek** [comment]
2614195	2015-02-17 09:12:33	CMS			<errormsg>DOMDocument::loadXML(): Opening and ending tag mismatch: trace line 1 and log in Entity, line: 1</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\dssserver\www\lib\service\xmdssoap3.class.php</scriptname>
<scriptlinenum>633</scriptlinenum>

**Comment by dasgarner** [comment]
Are you sure you got the file from the develop branch?

**Comment by mymactek** [comment]
YepLogged in to GitHub Clicked on xibosignage Then to cms/lib And copied the soap 3 & 4 files On Tue, Feb 17, 2015 at 9:19 AM,  xibosignage/xibo <reply@reply.github.com> wrote:            Are you sure you got the file from the develop branch?

**Comment by dasgarner** [comment]
I meant from my fork: https://github.com/dasgarner/xibo-cms/tree/develop/lib/service

**Comment by mymactek** [comment]
Ok copied both from that link ....
Will update

**Comment by mymactek** [comment]
Didnt see any more error messages for a few min, but then the following populated ... some say going to be discarded, but wanted to send to make sure nothing is messed up.

Thanks Dan !





2614800	2015-02-17 09:33:12	Racer - 50th Host - Android2	Client	onTrimMemory	Trim Request [level=15] at Total:384. Used: 38. Device Total: 38. Device Free: 0
2614799	2015-02-17 09:33:09	Best Western - Host - Android	XMDSSoap4	SubmitLog	Malformed XML from Player, this will be discarded. The Raw XML String provided is: <log><trace date="2014-11-07 15:02:45" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 8</message></trace><trace date="2014-11-07 15:02:45" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 8</message></trace><trace date="2014-11-07 15:03:57" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 15:03:58" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 15:05:16" category="error"><method>Schedule</method><message>expected: START_TAG {http://schemas.xmlsoap.org/soap/envelope/}Envelope (position:START_TAG <html {http://www.w3.org/XML/1998/namespace}xml:lang='en' lang='en' dir='ltr'>@3:78 in java.io.InputStreamReader@420a5e88) </message></trace><trace date="2014-11-07 15:05:17" category="audit"><method>RequiredFiles</method><message>expected: START_TAG {http://schemas.xmlsoap.org/soap/envelope/}Envelope (position:START_TAG <html {http://www.w3.org/XML/1998/namespace}xml:lang='en' lang='en' dir='ltr'>@3:78 in java.io.InputStreamReader@42271900) </message></trace><trace date="2014-11-07 15:08:54" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 8</message></trace><trace date="2014-11-07 15:08:54" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 8</message></trace><trace date="2014-11-07 15:10:16" category="error"><method>Schedule</method><message>Unable to resolve host "dealer.dsstexas.com": No address associated with hostname</message></trace><trace date="2014-11-07 15:10:16" category="audit"><method>RequiredFiles</method><message>Unable to resolve host "dealer.dsstexas.com": No address associated with hostname</message></trace><trace date="2014-11-07 15:10:37" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 6</message></trace><trace date="2014-11-07 15:10:37" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 6</message></trace><trace date="2014-11-07 15:11:54" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 12</message></trace><trace date="2014-11-07 15:11:54" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 12</message></trace><trace date="2014-11-07 15:13:35" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 8</message></trace><trace date="2014-11-07 15:13:35" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 8</message></trace><trace date="2014-11-07 15:45:17" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 15:46:17" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 6</message></trace><trace date="2014-11-07 15:47:17" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 8</message></trace><trace date="2014-11-07 15:48:17" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 15:49:17" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 8</message></trace><trace date="2014-11-07 15:50:17" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 15:51:17" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 8</message></trace><trace date="2014-11-07 15:52:17" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 15:53:17" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 8</message></trace><trace date="2014-11-07 15:55:15" category="error"><method>HeartBeatReceiver - onReceive</method><message>Activity not visible, restarting.</message></trace><trace date="2014-11-07 15:56:36" category="error"><method>RequiredFiles</method><message>Unable to report media inventory: null</message></trace><trace date="2014-11-07 16:00:36" category="error"><method>Schedule</method><message>failed to connect to dealer.dsstexas.com/205.209.245.61 (port 80) after 20000ms</message></trace><trace date="2014-11-07 16:00:56" category="audit"><method>RequiredFiles</method><message>failed to connect to dealer.dsstexas.com/205.209.245.61 (port 80) after 20000ms</message></trace><trace date="2014-11-07 16:20:36" category="error"><method>Schedule</method><message>failed to connect to dealer.dsstexas.com/205.209.245.61 (port 80) after 20000ms</message></trace><trace date="2014-11-07 16:27:02" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 16:27:12" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 16:28:12" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 16:29:12" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 16:30:12" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 16:31:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 16:32:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 16:33:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 16:34:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 16:35:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 12</message></trace><trace date="2014-11-07 16:36:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 7</message></trace><trace date="2014-11-07 16:37:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 16:38:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 16:39:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 16:40:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 16:41:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 16:42:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 16:43:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 16:44:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 16:45:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 16:46:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 7</message></trace><trace date="2014-11-07 16:47:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 16:48:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 16:49:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 16:50:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 16:51:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 16:52:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 16:53:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 16:54:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 16:56:13" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 7</message></trace><trace date="2014-11-07 16:57:02" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 16:57:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 16:58:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 16:59:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 17:00:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:01:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 17:02:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:03:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 17:04:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:05:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 17:06:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 12</message></trace><trace date="2014-11-07 17:07:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:08:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 17:09:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:10:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 17:11:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:12:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 17:13:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:14:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 17:15:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:16:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 7</message></trace><trace date="2014-11-07 17:17:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 12</message></trace><trace date="2014-11-07 17:18:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:19:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 17:20:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:21:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 17:22:14" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:23:15" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 17:24:15" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:25:15" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 17:26:15" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:27:02" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:27:15" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:28:15" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 17:29:15" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:30:15" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 17:31:15" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:32:15" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace><trace date="2014-11-07 17:33:15" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 10</message></trace><trace date="2014-11-07 17:34:15" category="error"><method>onTrimMemory</method><message>Trim Request at Total:384. Used: 9</message></trace></log>
2614798	2015-02-17 09:33:09	CMS			<errormsg>DOMDocument::loadXML(): Couldn't find end of Start Tag html line 1 in Entity, line: 1</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\dssserver\www\lib\service\xmdssoap4.class.php</scriptname>
<scriptlinenum>756</scriptlinenum>
2614797	2015-02-17 09:33:09	CMS			<errormsg>DOMDocument::loadXML(): attributes construct error in Entity, line: 1</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\dssserver\www\lib\service\xmdssoap4.class.php</scriptname>
<scriptlinenum>756</scriptlinenum>
2614796	2015-02-17 09:33:09	CMS			<errormsg>DOMDocument::loadXML(): error parsing attribute name in Entity, line: 1</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\dssserver\www\lib\service\xmdssoap4.class.php</scriptname>
<scriptlinenum>756</scriptlinenum>
2614795	2015-02-17 09:33:09	CMS			<errormsg>DOMDocument::loadXML(): Couldn't find end of Start Tag html line 1 in Entity, line: 1</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\dssserver\www\lib\service\xmdssoap4.class.php</scriptname>
<scriptlinenum>756</scriptlinenum>
2614794	2015-02-17 09:33:09	CMS			<errormsg>DOMDocument::loadXML(): attributes construct error in Entity, line: 1</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\dssserver\www\lib\service\xmdssoap4.class.php</scriptname>
<scriptlinenum>756</scriptlinenum>
2614793	2015-02-17 09:33:09	CMS			<errormsg>DOMDocument::loadXML(): error parsing attribute name in Entity, line: 1</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\dssserver\www\lib\service\xmdssoap4.class.php</scriptname>
<scriptlinenum>756</scriptlinenum>

![image](https://cloud.githubusercontent.com/assets/10713173/6230830/4d0b0be0-b688-11e4-9d86-56fdfd49ed49.png)

![image](https://cloud.githubusercontent.com/assets/10713173/6230835/564588f2-b688-11e4-86ae-b058b99040f0.png)

**Comment by mymactek** [comment]
All XMDS logs are gone,now this is only thing showing ....

ID
Date
Display
Page
Function
Message
2615356	2015-02-17 09:44:02	Fuzzy Taco 101 Slide - Android	Client	onTrimMemory	Trim Request [level=15] at Total:384. Used: 26. Device Total: 26. Device Free: 0
2615355	2015-02-17 09:43:02	Fuzzy Taco 101 Slide - Android	Client	onTrimMemory	Trim Request [level=15] at Total:384. Used: 26. Device Total: 26. Device Free: 0
2615351	2015-02-17 09:44:13	Racer - 50th Host - Android2	Client	onTrimMemory	Trim Request [level=15] at Total:384. Used: 38. Device Total: 38. Device Free: 0
2615350	2015-02-17 09:43:13	Racer - 50th Host - Android2	Client	onTrimMemory	Trim Request [level=15] at Total:384. Used: 38. Device Total: 38. Device Free: 0
2615234	2015-02-17 09:42:46	Stuarts PitStop - lvlland - Android	Client	HeartBeatReceiver - onReceive	Activity not visible, restarting.

**Comment by dasgarner** [comment]
Sounds like its working well now...

The discarded logs are a player side issue that will be fixed in the latest (yet to be released). The fact they are discarded is unfortunate but unavoidable until the players send correct logs.

They are only incorrect occasionally, so nothing to worry about for now.

Thanks,
Dan
