### ISSUE TITLE
Improve layout delete message when attempting to delete a layout assigned to a campaign

### ISSUE THREAD

**Issue by MichaelHoughton** [xibosignage/xibo#277]
When deleting some layouts from the API, the following error is returned:

    SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`xibo7`.`lkcampaignlayout`, CONSTRAINT `lkcampaignlayout_ibfk_2` FOREIGN KEY (`LayoutID`) REFERENCES `layout` (`layoutID`))

**Comment by dasgarner** [comment]
Well, the message isn't very good - but I would imagine those layouts are assigned to a campaign.

**Comment by MichaelHoughton** [comment]
Hey @dasgarner - yes, you are spot on, those layouts are assigned to a campaign :)
