### ISSUE TITLE
Access Denied MySQL Error When Upgrading or Fresh Install of V1.7.1

### ISSUE THREAD

**Issue by JELedoux** [xibosignage/xibo#278]
Every time I try to do either an upgrade from v1.6.4 to v1.7.1 or a fresh install of v1.7.1, I get the following MySQL error messages

Create New DB:
Could not create a new database with the administrator details [lpdxibox_root]. Please check and try again. Error Message = [SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'lpdxibox_root'@'localhost' to database 'lpdxibox_v17']

Use Existing DB:
Could not connect to MySQL with the administrator details. Please check and try again. Error Message = [SQLSTATE[28000] [1045] Access denied for user 'lpdxibox_root'@'localhost' (using password: YES)]

I am using x10hosting.com for my site host. I am able to install (and re-install) v1.6.4 using the same credentials without any issues.

Thank you.

**Comment by alexharrington** [comment]
That measns that the username/password combination you have doesn't have permission to create a database on the server. If it's a hosting environment then normally they create a database for you, in which case use the existing database option in the installer to install in to that (assuming it's empty)

**Comment by dasgarner** [comment]
The technical difference between the two versions is that in 1.7 we use PDO for the installation routine, 1.6 was still on the mysqli module.

Why that makes a difference, I don't know. I'm thinking it doesn't like your database name for some reason, but I can't think why that would be.
