### ISSUE TITLE
Short events can't be seen in daily schedule view

### ISSUE THREAD

**Issue by ddille678** [xibosignage/xibo#279]
If an event is scheduled for 15 minutes or less, it becomes unreadable/clickable in the daily view of the schedule. Screenshot below.

![xibo-error](https://cloud.githubusercontent.com/assets/3801907/6234932/8af4d322-b6ac-11e4-8209-fd6ad60964c0.PNG)

**Comment by laercionit** [comment]
+ 1 for this...

**Comment by dasgarner** [comment]
What would be the suggestion? Just make each row larger?

**Comment by laercionit** [comment]
I think we can do the same as Google Calendar. Here is the size in the right proportion, like this implemented in Xibo. But when you click or hover, we have the detail of the event.

![image](https://cloud.githubusercontent.com/assets/325662/6266321/13ee1ac6-b81f-11e4-8898-2c857959ef16.png)

**Comment by ddille678** [comment]
I support the above idea of having a pop up similar to Google Calendar as a long term solution.

As far as a short term solution, simply increasing the size of the div on hover works well in my testing.

**Comment by dasgarner** [comment]
Ah, so the row expands only when hovering over it - I like that as a short term solution. Thanks.

**Comment by dasgarner** [comment]
Would you be able to explain how you got the row size increase to work? The events are overlaid on top of the grid, so expanding the row doesn't actually do anything.
