### ISSUE TITLE
API code uses DOMElement as its base currency, should really be using Array

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#28]
Found during the course of investigation on #24.

The API uses DOMElement to pass between the base class and the class responsible for formatting the response to either json or xml.

At present the code incorrectly expects different parameters to the same overridden methods (json expects arrays and xml expects DOMElements).

The base currency should really be an array, meaning json responses can be `json_encoded` straight out the gate, and XML responses can be array to XML conversions (which is easy).

**Comment by PeterMis** [comment]
It works for most templates, although for 5 days, one in a big circle, to have days names in other language, you still need to change language in the settings not only on the module.

**Comment by dasgarner** [comment]
I'm not sure why this fix is attached to this issue - but your findings are valid. I've submitted a new issue for that here: https://github.com/xibosignage/xibo/issues/573
