### ISSUE TITLE
Request screen capture brand as online

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#283]
Hello Dan,
I noticed a strange behavior. I'm sure the display this offline. I disconnected the internet 21:20. You can confirm the information by the last screen capture image.

The system marks as well offline, but after performing the screenshot request, it updates the date / time of the last connection and reports that display this online.

See the video below:
https://www.youtube.com/watch?v=CUdM95UMx9E&feature=youtu.be

**Comment by dasgarner** [comment]
Can you try the display.data.class.php file in the above commit?

**Comment by laercionit** [comment]
OK Dan, the change in file solved the problem.
Now the offline display does not change status when requesting screenshot.
