### ISSUE TITLE
Display Group Copy - Members and assignments are not copied when requested

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#2843]
When respective copy checkbox is selected, the members and assignments are not copied over correctly.

This is likely due to how we save the new Display Group - when the second save happens after load, none of the assignments/members will be there, therefore on second save, nothing will get assigned to new display group. 
Copy members and assignments should happen after first save (to get the id) and then second save will manage all the relevant and requested links.

**Comment by dasgarner** [comment]
https://github.com/dasgarner/xibo-cms/commit/dd4b0db9d984d2dbfaa17994fd7d959251f351d6
