### ISSUE TITLE
RSS v1.7 - new formatting?

### ISSUE THREAD

**Issue by husph** [xibosignage/xibo#286]
Hi!
Just wanted to check if there has been any changes to formatting RSS from 1.4.2 to 1.7.1.
A feed that works perfect in 1.4.2 shows absolutley nothing in 1.7.1.
1.7.1 have no problem in showing other feeds, just this one.
So I just wanted to check if there has been any changes in the upgrades that can cause this in any way, or if it is within my system the problem can be (closed ports between servers or something).

**Comment by dasgarner** [comment]
The old template tags should work in the same way as before - however the entire RSS engine has changed between 1.4 and 1.7.

RSS is parsed CMS side and transferred to the player completely rendered. So it is likely that your CMS cannot get to that feed, or that the CMS feed parser doesn't understand that feed for some reason (check logs).

**Comment by husph** [comment]
This is what I can get of the logs (I think):
424773	2015-02-20 15:37:08	STK-ISIT-SCOM	Client	[UI Thread] xmds_GetResource	Unable to get Resource: Unable to get the media resource
424775	2015-02-20 15:37:49	STK-ISIT-SCOM	Client	[UI Thread] xmds_GetResource	Unable to get Resource: Unable to get the media resource
424777	2015-02-20 15:38:29	STK-ISIT-SCOM	Client	[UI Thread] xmds_GetResource	Unable to get Resource: Unable to get the media resource

**Comment by husph** [comment]
I also get this A LOT:
425036	2015-02-20 15:41:36	CMS			<errormsg>Undefined variable: config</errormsg>
<errornum>8</errornum>
<errortype>Notice</errortype>
<scriptname>D:\xampp\htdocs\xibo\lib\app\thememanager.class.php</scriptname>
<scriptlinenum>57</scriptlinenum>

**Comment by dasgarner** [comment]
The undefined variable has been fixed (or reported at least, I can't remember).

We will need to enable auditing, recreate the issue and then check in the logs again. By recreating the issue, loading the layout in the designer and getting the empty preview of that RSS feed will be sufficient.

**Comment by husph** [comment]
Is there any problem with feeds using httpS ?

**Comment by mattdreher** [comment]
I was doing some testing my self and found that it doesn't display RSS feeds that are using HTTPS but if I copy the file locally to a non HTTPS server it works.

**Comment by dasgarner** [comment]
Your PHP installation is most likely not configured correctly to download HTTPS using cURL. See [this article](http://snippets.webaware.com.au/howto/stop-turning-off-curlopt_ssl_verifypeer-and-fix-your-php-config/).

**Comment by mattdreher** [comment]
Yes, this solved my issue.  Basically the Curl module doesn't have any CA Certs by default for my Windows installation.  I had to download a copy of the cacerts file, add my own CA to the bottom of it, then update the curl.cainfo setting in the php.ini to get it to work.  Thanks for pointing me in the right direction.

For the Option to set in PHP.ini - http://php.net/manual/en/curl.configuration.php
For the CA Extract - http://curl.haxx.se/docs/caextract.html

**Comment by dasgarner** [comment]
Fantastic - i'm glad you got that working.
