### ISSUE TITLE
WidgetAddEvent is never dispatched

### ISSUE THREAD

**Issue by SamueleVanini** [xibosignage/xibo#2860]
Hi,
While developing a custom widget that needs to adjust its duration dynamically, I noticed that the event WidgetAddEvent is never dispatched. It is saved as a reference inside the module by the method `Xibo\Controller\Module.addWidget(Request $request, Response $response,$type, $id)`, to be later called by `Xibo\Widget\ModuleWidget.saveWidget()` . 
The problem is that WidgetEditEvent will override it. It happens because `saveWidget()` is called only by the widget’s method `edit()`, which in turn is called from the module’s `Xibo\Controller\Module.editWidget().`

The version of the CMS: 3.1.3
I also wrote a post on this on your blog, you can find it here: [post](https://community.xibo.org.uk/t/bug-event-listener-doesnt-catch-widgetaddevent-event/27731)

**Comment by dasgarner** [comment]
I've answered your community post - we will investigate to see why the event isn't being fired (I think it should be as the code stands now).

**Comment by dasgarner** [comment]
We've confirmed that the WidgetAddEvent is dispatched as expected.

Logs with test middleware:

![image](https://user-images.githubusercontent.com/10400067/189700444-573fe09f-daee-4dcd-9908-7247c511e625.png)

```    /**
     * @param \Psr\Http\Message\ServerRequestInterface $request
     * @param \Psr\Http\Server\RequestHandlerInterface $handler
     * @return \Psr\Http\Message\ResponseInterface
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $this->getLog()->debug('Process');

        /** @var EventDispatcherInterface $dispatcher */
        $dispatcher = $this->app->getContainer()->get('dispatcher');

        $dispatcher->addListener(WidgetAddEvent::$NAME, function() {
            $this->getLog()->debug('WIDGET ADD');
        });

        $dispatcher->addListener(WidgetEditEvent::$NAME, function() {
            $this->getLog()->debug('WIDGET EDIT');
        });

        // Next middleware
        return $handler->handle($request);
    }
```
