### ISSUE TITLE
xibo redirect web error unexpected error, please contact support

### ISSUE THREAD

**Issue by pbunluesin** [xibosignage/xibo#2866]
Hello,

I got error from Xibo docker when I access to xibo website and after that 3-4 minutes it redirect to logout page and show error 
"unexpected error, please contact support"

when I checked docker-compose logs , it seems like does not show any error for me.

could you please advise ?
![Capture](https://user-images.githubusercontent.com/3583606/184816915-4f584f32-53eb-4465-a601-15fe54068c93.JPG)

below is docker-compose file and config.env

> version: "2.1"
> 
> services:
>     cms-xmr:
>         image: xibosignage/xibo-xmr:0.9
>         ports:
>             - "9505:9505"
>         restart: always
>         env_file: config.env
>         mem_limit: 2G
>     cms-web:
>         image: xibosignage/xibo-cms:release-3.1.4
>         volumes:
>             - "./shared/cms/custom:/var/www/cms/custom:Z"
>             - "./shared/backup:/var/www/backup:Z"
>             - "./shared/cms/web/theme/custom:/var/www/cms/web/theme/custom:Z"
>             - "./shared/cms/library:/var/www/cms/library:Z"
>             - "./shared/cms/web/userscripts:/var/www/cms/web/userscripts:Z"
>             - "./shared/cms/ca-certs:/var/www/cms/ca-certs:Z"
>         restart: always
>         links:
>             - cms-xmr:50001
>         environment:
>             - XMR_HOST=cms-xmr
>             - CMS_USE_MEMCACHED=true
>             - MEMCACHED_HOST=cms-memcached
>         ports:
>             - "80:80"
>         env_file: config.env
>         mem_limit: 2G
>     cms-memcached:
>         image: memcached:alpine
>         command: memcached -m 256
>         restart: always
>         mem_limit: 512M
>     cms-quickchart:
>       image: ianw/quickchart
>       restart: always

![cms-config](https://user-images.githubusercontent.com/3583606/184817926-7d9c45a0-2580-4dac-8428-106c23982316.JPG)

**Comment by dasgarner** [comment]
Hi and thank you for reporting this issue!

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this support request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!
