### ISSUE TITLE
Creating a New Ticker the Description field is missing

### ISSUE THREAD

**Issue by andyrogers2012** [xibosignage/xibo#288]
When creating a new ticker the Description field is missing, but when you come to edit the Ticker the field is present

**Comment by andyrogers2012** [comment]
Was pointed this out by a user, but upon saving you are immediately prompted with the "Edit Dialog" which has this present.

**Comment by dasgarner** [comment]
Yeah, adding is a cut down form as we don't yet know the full set of fields to display (they are different depending on the source).

The description could come across as its common to both, but I am not sure that is necessary?
