### ISSUE TITLE
Library: users with a library quota cannot upload

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2889]
Root Cause: a SQL connection error checking the quota.

**Comment by Adrian-WND** [comment]
#2889 Hello, I set the library quota from user to  0. User still cannot upload or modify library. Regards,

**Comment by dasgarner** [comment]
This problem would also be evident if your user has a quota set via a group membership - that may be the cause?

**Comment by Diogofgg05** [comment]
Did you fix it?
Because I also have this problem and I don't know how to fix it.
