### ISSUE TITLE
Colour option missing when creating new Forecast I/O

### ISSUE THREAD

**Issue by andyrogers2012** [xibosignage/xibo#289]
Colour option is missing when creating new Forecast, but appears when editing

Xibo CMS 1.7.1

**Comment by dasgarner** [comment]
Reported here - I didn't change the title though, my bad #238

**Comment by dasgarner** [comment]
I'll close the other issue and leave this one here...

**Comment by andyrogers2012** [comment]
sorry didn't see that in the bug list.  Done a Pull Request to fix see above
