### ISSUE TITLE
Deleting display causes all other displays to go 'out of date'

### ISSUE THREAD

**Issue by tmknight** [xibosignage/xibo#2890]
CMS: V3.1.3 (been evident for several v3.x versions)
Display client: Latest

Action: Select display drop-down menu, delete (as global admin)
Result: Display deleted and (nearly) all other displays show out-of-date a few seconds later for several minutes
Expected: Display deleted and no affect on other displays

**Comment by dasgarner** [comment]
This might be due to the deleted display belonging to one or more display groups, which are updated as part of the delete. In turn the display group update triggers an update to its remaining members.

Do you think this could explain it in your case?

Thanks

**Comment by tmknight** [comment]
Yes, the display was member of display groups.  Why would the other members need updating on the client side - should they have need to know what other displays are in the group or their status?

**Comment by dasgarner** [comment]
It doesn't seem like they should need to know - there may be a reason though. I'll mark this up to investigate.
