### ISSUE TITLE
Notify current layout does not work

### ISSUE THREAD

**Issue by ygurdag** [xibosignage/xibo#292]
Hi,
Even you set "Notify current layout" from Display Setting Profiles, it does not work. I check source code of .net client and it sends the current layout to server' s service but server always write to database as "0". 
Thanks

**Comment by dasgarner** [comment]
I don't see why that would be the case - `lib/data/display.data.class.php` line 432 correctly pulls in the currentLayoutId.

I think we'd need some logging from your Display (enable global auditing, enable display auditing, filter the log on "NotifyStatus".

**Comment by ygurdag** [comment]
![x_dotnet](https://cloud.githubusercontent.com/assets/8157977/6343077/0aa54ae6-bbeb-11e4-870e-6bccc14217b0.png)
![x_mysql](https://cloud.githubusercontent.com/assets/8157977/6343078/0aa9a596-bbeb-11e4-8bb3-3eca38c33b61.png)
As you can see from screen shots, .net client sends current layout as "15" which is true. But on database it never chances. Where do I make wrong? Display settings : auditing on, notify current layout: on.
Thanks

**Comment by dasgarner** [comment]
> I think we'd need some logging from your Display (enable global auditing, enable display auditing, filter the log on "NotifyStatus".

We need to make sure that 15 is actually getting to the CMS - if you have enabled auditing on that display and global logging you should see a NotifyStatus message in the logs.

**Comment by ygurdag** [comment]
Cannot see that information.

**Comment by dasgarner** [comment]
That is thoroughly unhelpful...

**Comment by ygurdag** [comment]
I mean check the server logs and cannot see any information with  NotifyStatus. Maybe client does not send NotifyStatus.

**Comment by dasgarner** [comment]
You have a screen shot of the code with a breakpoint set and broken over the command to send. When you execute that command do you not get an entry in your web server access logs? 

Are you sure you have auditing on globally and on the display record?

The notify is working on every test I have done... hence the confusion.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
