### ISSUE TITLE
Commands: Add option to `With Selected` to execute command 

### ISSUE THREAD

**Issue by tmknight** [xibosignage/xibo#2927]
Feature request to allow execute of commands available to multiple selected devices via `With Selected`.

I can see some challenges if selected devices are of different OS, however, having this feature available will be a time saving feature.  I'm certain backend checks can be implemented or leveraged to avoid sending a command meant for Windows to Android, etc.

A simple example for this would be to send a command to restart the OS on multiple endpoints.

**Comment by dasgarner** [comment]
I did get an error the first time I tried this, but subsequently it has been fine.

I think this is a ✅
