### ISSUE TITLE
Jalali calendar

### ISSUE THREAD

**Issue by miladsunboy** [xibosignage/xibo#293]
The event did not inserted into the Jalali calendar

**Comment by dasgarner** [comment]
Please provide more information.

**Comment by miladsunboy** [comment]
1-when i set start time and end time and press save , event did not inserted . this massage ''Your start time is in the past. Cannot schedule events in the past''  is appeared but i insert it correct

2-when i click into start time and end time to set date , Gregorian calender loded

**Comment by dasgarner** [comment]
> ''Your start time is in the past. Cannot schedule events in the past'' is appeared but i insert it correct

Will be fixed in the latest release

> 2-when i click into start time and end time to set date , Gregorian calender loded

Will also be fixed in the latest release (but you will need to clear your cache to get the changes)

**Comment by miladsunboy** [comment]
Thanks for the answer
