### ISSUE TITLE
Display map is only showing 10 displays at one time

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#2934]
Display Map - Remove pagination from map view of displays

**Comment by avrovulcanxh607** [comment]
Could we also get the level of "grouping" reduced. At the moment, zooming out groups the screens together somewhat early so it's hard to see all the locations.

A full screen view could be useful as well but not a high priority.

**Comment by dasgarner** [comment]
@avrovulcanxh607 thanks for your feedback. We have added a full screen option as requested.

We're not sure about the grouping - with the examples we have it only groups where pins would overlap each other - can you describe a bit more the issue you're seeing?

Thanks!

**Comment by avrovulcanxh607** [comment]
@dasgarner Excellent, will look forward to that update. Would quite like to show that on a display in our office!

Re: the grouping, I've attached a few images showing the issue - in the first image you can see a seperate screen, but one 'notch' of zoom out causes it to be absorbed into the adjacent group. I don't think it's far enough that they'd have overlapped, but I could be wrong...

![image](https://user-images.githubusercontent.com/15457757/205696717-72932b31-80ea-4309-9433-332e96ca828b.png)
![image](https://user-images.githubusercontent.com/15457757/205696817-d84e3c77-0df1-4ecd-9e36-7d8208e87c18.png)

**Comment by dasgarner** [comment]
@ifarzana what do you think? I looks to me like the smaller second screen shot should be able to show the right hand pin independently without overlapping the icons?

**Comment by ifarzana** [comment]
We have set the map cluster property in the following way now: it will show smaller clusters/points if you zoom in. I hope this solves the grouping of clusters that you have asked for. Thanks.

**Comment by dasgarner** [comment]
Great, thanks!
