### ISSUE TITLE
CAS Authentication middleware does not reject login attempt for retired user.

### ISSUE THREAD

**Issue by phanku** [xibosignage/xibo#2945]
Hello,

My development team has identified a verifiable and replicable bug within version 3.2.1 of the CMS.

The issue:
Retired users are still able to login to the CMS when CAS authentication is implemented. 

How to replicate:
We are using the Docker version of the Xibo CMS.

1. Set a viable CAS authentication server within the /custom/settings-custom.php file.
2. Verify the CAS login process works by logging into the CMS. 
3. Set the retired flag on the user account. 
4. Logout and then log back in using CAS and take note that the user was granted access.

The solution:
After some research we have determined that the /lib/Middleware/CASAuthentication.php file is missing the code needed to check if the user account has been retired. 

We believe this is true based on the correction made to the login process in commit [0bcd52faa9b9fe82c0aea94510af93263eef43bd](https://github.com/dasgarner/xibo-cms/commit/0bcd52faa9b9fe82c0aea94510af93263eef43bd).

**Comment by dasgarner** [comment]
Thank you for this report and diagnosis, we will resolve this issue in the next release. I have added it to the appropriate milestone.
