### ISSUE TITLE
Feature Request: Bulk lat/long update

### ISSUE THREAD

**Issue by avrovulcanxh607** [xibosignage/xibo#2949]
It would be helpful to have more display settings available to be updated for multiple screens simultaneously, through the "with selected" tab.

I'd like to be able to select multiple screens and set all of their details (lat/long, type, size etc) once, rather than having to go into each one and update them.

**Comment by dasgarner** [comment]
It's great to have your input and this is certainly a good idea. So that we can keep the right people involved in feature discussions, we have those on the [Community](https://community.xibo.org.uk/c/features/8). It would be most appreciated if you'd re-post over there.

Thanks!
