### ISSUE TITLE
Upgrading from 1.6 to 1.71

### ISSUE THREAD

**Issue by eleeptg** [xibosignage/xibo#295]
Trying to determine best way to upgrade. It would seem that I should upgrade all the windows clients first before tackling the server. Due to changes on the server end... Will the 1.7.0 client work against the 1.6 server until I upgrade all my clients and then save upgrading the server for last?

**Comment by dasgarner** [comment]
Actually you should do it the other way - the versioning is in the CMS end rather than the player end.
