### ISSUE TITLE
Ad Campaigns/Displays: fix column datatypes in migration

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2953]
Users who installed 3.3.0 will have the wrong datatypes for the below fields:
 - `display.costPerPlay`
 - `display.impressionsPerPlay`
 - `campaign.spend`
 - `campaign.impressions`

Add a migration to fix this.

Note: users who installed or upgraded after 3.3.1 was released will already have the right datatypes.

**Comment by ifarzana** [comment]
Westphal migrations already have the following as decimal 
- Display `costPerPlay` and `impressionsPerPlay` 
- Campaign `spend` and `impressions` 

@dasgarner Should we say this is already done?

**Comment by dasgarner** [comment]
This issue is about users who have installed v3.3, so the migrations that exist already will have run and put the columns in incorrectly.

So we need new migrations to detect if those columns have the wrong datatype and change them if necessary.

Make sense?

**Comment by ifarzana** [comment]
Thank you for your reply, I think I got it now, so 3.3 users have those migrations but they already ran and was set to integers. 

I will create new migrations.

**Comment by ifarzana** [comment]
https://github.com/xibosignage/xibo-cms/pull/1569
