### ISSUE TITLE
Displays: cost/impressions per play should accept decimal values

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2954]
Presently they are integers in the fields, API and database. We should update the API to pull in these fields as double, and update the form to accept double.

The fields should be `DECIMAL(10, 4)` (10 significant digits, 4 decimal places) which will allow a maximum of `999999.9999` and we should update the migration to fix this. In v4 we should add a new migration to fix this: #2953

**Comment by ifarzana** [comment]
https://github.com/xibosignage/xibo-cms/pull/1513
