### ISSUE TITLE
Ad Campaigns: spend/impressions should accept decimal values

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2955]
We should update the migration added in 3.3.0 to set these fields to `DECIMAL(30, 4)` instead. 
In v4 we should add a new migration to fix this: https://github.com/xibosignage/xibo/issues/2953

We should also check that the submitStats API (and the audience connector) allow that to be totalled up correctly.

**Comment by ifarzana** [comment]
https://github.com/xibosignage/xibo-cms/pull/1513
