### ISSUE TITLE
Cannot copy Layouts in with a # in their name

### ISSUE THREAD

**Issue by provalida** [xibosignage/xibo#296]
Hi,

when I try to copy a layout in Xibo 1.7.1, I get a garbled popup and can only close it. Was also seen in 1.6.x

![xibo digital signage_2015-02-19_12-57-47](https://cloud.githubusercontent.com/assets/3933355/6266366/f6d72fc6-b838-11e4-931b-828aa0c79481.png)

Same with Firefox, Chrome or IE. Server is CentOS 6.6 with Apache 2.2, PHP 5.3.29, MySQL 5.5.40

**Comment by dasgarner** [comment]
Can you run through the Report Fault page and put the log file somewhere for us to look at?

This is usually a javascript issue (cached from a prior version) so you might just try clearing your cache - I doubt this is it has you have used several browsers to test.

**Comment by provalida** [comment]
Attached the report here:
--------------------------------------
Environment Checks
--------------------------------------
<table class="table">
    <thead>
        <tr>
                                    <th class="group-false">Element</th>
                        <th class="group-false" data-sorter="tickcross">Status</th>
                        <th class="group-false">Hinweis</th>
                                </tr>
    </thead>
    <tbody>
                <tr >
                                                <td>PHP-Version</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP Version 5.3.3 oder höher erforderlich. Detected 5.3.29</td>
                                            </tr>
                <tr >
                                                <td>Rechte im Dateisystem</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>Write access required for settings.php and install.php</td>
                                            </tr>
                <tr >
                                                <td>MySQL Datenbank (PHP MySql)</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>MySQL Unterstützung muss in PHP aktiviert sein.</td>
                                            </tr>
                <tr >
                                                <td>MySQL Datenbank (PDO MySql)</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PDO Unterstützung für MySQL Treiber muss in PHP aktiviert sein.</td>
                                            </tr>
                <tr >
                                                <td>JSON-Erweiterung</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP JSON für diese Funktion erforderlich.</td>
                                            </tr>
                <tr >
                                                <td>SOAP-Erweiterung</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP SOAP für diese Funktion erforderlich.</td>
                                            </tr>
                <tr >
                                                <td>GD-Erweiterung</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP GD für diese Funktion erforderlich.</td>
                                            </tr>
                <tr >
                                                <td>Sitzung</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP Session Unterstützung für diese Funktion erforderlich.</td>
                                            </tr>
                <tr >
                                                <td>FileInfo</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>Benötigt die PHP FileInfo Unterstützung um zu funktionieren. Falls Sie unter Windows arbeiten, müssen Sie die php_fileinfo.dll in Ihrer php.ini Datei aktivieren.</td>
                                            </tr>
                <tr >
                                                <td>PCRE</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP PCRE Unterstützung für diese Funktion erforderlich.</td>
                                            </tr>
                <tr >
                                                <td>Text erhalten</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP GETTEXT Unterstützung für diese Funktion erforderlich.</td>
                                            </tr>
                <tr >
                                                <td>Kalender-Erweiterung</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP Kalender Erweiterung erforderlich</td>
                                            </tr>
                <tr >
                                                <td>DOM-Erweiterung</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP DOM Core Funktionalität eingeschaltet.</td>
                                            </tr>
                <tr >
                                                <td>DOM XML Erweiterung</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP DOM XML Erweiterung erforderlich.</td>
                                            </tr>
                <tr >
                                                <td>Mcrypt Erweiterung</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP Mcrypt Erweiterung erforderlich</td>
                                            </tr>
                <tr >
                                                <td>PHP erlauben externe URLs zu öffnen</td>
                                                <td><span  class="glyphicon glyphicon-exclamation-sign"></span></td>
                                                <td>Sie müssen allow_url_fopen = On in Ihrer PHP.ini gesetzt haben, damit RSS-Feeds / die anonyme Statistiksammlung funktionieren.</td>
                                            </tr>
                <tr >
                                                <td>DateTimeZone</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>Dies ermöglicht uns eine Liste der unterstützten Zeitzonen des Servers abzufragen</td>
                                            </tr>
                <tr >
                                                <td>Große Dateiuploads</td>
                                                <td><span  class="glyphicon glyphicon-exclamation-sign"></span></td>
                                                <td>Sie wollen vermutlich das Hochladen von Dateien erlauben, die grösser sind, als es Ihre PHP-Konfiguration gegenwärtig zulässt.<br />Wir empfehlen Ihnen, die PHP post_max_size und upload_max_size auf mindestens 128MB zu setzen, sowie die max_execution_time auf mindestens 120 Sekunden zu erhöhen.</td>
                                            </tr>
            </tbody>
</table>

--------------------------------------
LOG Dump
--------------------------------------
Date,Page,Function,Message
"2015-02-19 12:56:20","layout","","Loading permissions for layoutid 6"

--------------------------------------
Display Dump
--------------------------------------
DisplayID: 3
Display: EMPFANGTV
Default Layout: ### Standard provalida
Logged In: 1
Last Accessed: 1424346820
Interleave: 0
Licensed: 1


--------------------------------------
Settings Dump
--------------------------------------
Setting: MEDIA_DEFAULT - Value:   public

Setting: LAYOUT_DEFAULT - Value:   public

Setting: defaultUsertype - Value:   User

Setting: userModule - Value:   module_user_general.php

Setting: defaultTimezone - Value:   Europe/Berlin

Setting: mail_to - Value:   admin@yoursite.com

Setting: mail_from - Value:   mail@yoursite.com

Setting: jpg_length - Value:   10

Setting: ppt_length - Value:   120

Setting: swf_length - Value:   60

Setting: audit - Value:   audit

Setting: LIBRARY_LOCATION - Value:   /opt/xibo/

Setting: HELP_BASE - Value:   http://www.xibo.org.uk/manual/

Setting: PHONE_HOME - Value:   Off

Setting: PHONE_HOME_URL - Value:   http://www.xibo.org.uk/stats/track.php

Setting: PHONE_HOME_DATE - Value:   0

Setting: SERVER_MODE - Value:   Production

Setting: MAINTENANCE_ENABLED - Value:   Off

Setting: MAINTENANCE_EMAIL_ALERTS - Value:   On

Setting: MAINTENANCE_KEY - Value:   changeme

Setting: MAINTENANCE_LOG_MAXAGE - Value:   30

Setting: MAINTENANCE_STAT_MAXAGE - Value:   30

Setting: MAINTENANCE_ALERT_TOUT - Value:   12

Setting: SHOW_DISPLAY_AS_VNCLINK - Value:   0

Setting: SHOW_DISPLAY_AS_VNC_TGT - Value:   _top

Setting: MAINTENANCE_ALWAYS_ALERT - Value:   Off

Setting: SCHEDULE_LOOKAHEAD - Value:   On

Setting: REQUIRED_FILES_LOOKAHEAD - Value:   172800

Setting: REGION_OPTIONS_COLOURING - Value:   Media Colouring

Setting: LAYOUT_COPY_MEDIA_CHECKB - Value:   Unchecked

Setting: MAX_LICENSED_DISPLAYS - Value:   0

Setting: LIBRARY_MEDIA_UPDATEINALL_CHECKB - Value:   Unchecked

Setting: USER_PASSWORD_POLICY - Value:   

Setting: USER_PASSWORD_ERROR - Value:   

Setting: MODULE_CONFIG_LOCKED_CHECKB - Value:   Unchecked

Setting: LIBRARY_SIZE_LIMIT_KB - Value:   0

Setting: MONTHLY_XMDS_TRANSFER_LIMIT_KB - Value:   0

Setting: DEFAULT_LANGUAGE - Value:   en_GB

Setting: TRANSITION_CONFIG_LOCKED_CHECKB - Value:   Unchecked

Setting: GLOBAL_THEME_NAME - Value:   default

Setting: DEFAULT_LAT - Value:   51.504

Setting: DEFAULT_LONG - Value:   -0.104

Setting: SCHEDULE_WITH_VIEW_PERMISSION - Value:   No

Setting: SETTING_IMPORT_ENABLED - Value:   Off

Setting: SETTING_LIBRARY_TIDY_ENABLED - Value:   Off

Setting: SENDFILE_MODE - Value:   Off

Setting: EMBEDDED_STATUS_WIDGET - Value:   

Setting: PROXY_HOST - Value:   

Setting: PROXY_PORT - Value:   0

Setting: PROXY_AUTH - Value:   

Setting: DATE_FORMAT - Value:   Y-m-d H:i

Setting: DETECT_LANGUAGE - Value:   1

Setting: DEFAULTS_IMPORTED - Value:   1

Setting: FORCE_HTTPS - Value:   0

Setting: ISSUE_STS - Value:   0

Setting: STS_TTL - Value:   600

Setting: MAINTENANCE_ALERTS_FOR_VIEW_USERS - Value:   0

Setting: CALENDAR_TYPE - Value:   Gregorian


--------------------------------------
Sessions Dump
--------------------------------------
UserAgent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
RemoteAddress: 192.168.77.126
Session Data
pagename|s:6:"layout";token|s:32:"956caa18373537e60d2bf81687acb729";token_timeout|i:1424346987;message|s:0:"";username|s:10:"xibo_admin";usertype|s:1:"1";display|a:5:{s:14:"filter_display";s:0:"";s:19:"filter_displaygroup";i:0;s:15:"filter_showView";i:0;s:18:"filter_autoRefresh";i:0;s:13:"DisplayFilter";i:0;}gridToken|s:32:"88205112eadb1188d64304714f57eb3b";gridToken_timeout|i:1424346988;sessions|a:3:{s:6:"Filter";i:0;s:11:"filter_type";s:0:"";s:13:"filter_fromdt";s:0:"";}layout|a:9:{s:13:"filter_layout";s:0:"";s:13:"filter_userid";i:0;s:14:"filter_retired";i:0;s:20:"filterLayoutStatusId";s:1:"1";s:17:"showDescriptionId";s:1:"2";s:8:"showTags";i:0;s:13:"showThumbnail";i:1;s:11:"filter_tags";s:0:"";s:12:"LayoutFilter";i:0;}timeLineView|s:4:"list";content|a:10:{s:4:"type";s:6:"ticker";s:11:"filter_type";s:0:"";s:11:"filter_name";s:0:"";s:12:"filter_owner";i:0;s:14:"filter_retired";i:0;s:26:"filter_duration_in_seconds";i:0;s:20:"filter_showThumbnail";i:0;s:8:"showTags";i:0;s:6:"Filter";i:0;s:9:"mediatype";s:5:"video";}template|a:3:{s:11:"filter_name";s:0:"";s:11:"filter_tags";s:0:"";s:6:"Filter";i:0;}userid|s:1:"1";DisplayGroupIDs|a:0:{}user_admin|a:3:{s:15:"filter_username";s:0:"";s:17:"filter_usertypeid";i:0;s:6:"Filter";i:0;}54e5c617192c0|s:32:"d9fd0e844708efde8582825916957e6b";54e5c617192c0_timeout|i:1424344599;
----

**Comment by dasgarner** [comment]
It is because you have a `#` in the name

**Comment by provalida** [comment]
ok, so we can work around this easily.
But it might be better to prevent layout names with # in it or to escape this so it works with # in the names.

**Comment by dasgarner** [comment]
Will do - hence the bug tag.

Thanks,
Dan
