### ISSUE TITLE
Forecast IO behind PROXY server

### ISSUE THREAD

**Issue by jopper1988** [xibosignage/xibo#298]
When i use the Forecast IO the icons don't work. The only thing is see is alien icons how can i use other icons ?

![alien](https://cloud.githubusercontent.com/assets/5737203/6268282/dbb5aaac-b84b-11e4-86f9-1a138812e603.png)

This are the settings
![forecast io settings](https://cloud.githubusercontent.com/assets/5737203/6268283/dd9e6322-b84b-11e4-97f1-d1c86a663bae.png)

**Comment by xibo-de** [comment]
maybe this helps
https://github.com/xibosignage/xibo/issues/241

**Comment by jopper1988** [comment]
I have tried but al the thing there i've already tried. 

The only thing i see is

--
  o
---

powered buy forecast

**Comment by dasgarner** [comment]
What happens if you press "Request Forecast" at the bottom of that form?

**Comment by jopper1988** [comment]
If i do that then i get a alien icon. 
![alien](https://cloud.githubusercontent.com/assets/5737203/6284807/e8a953ae-b8f4-11e4-8f50-da560cfbc313.png)

**Comment by dasgarner** [comment]
The request forecast button should populate content in the "Forecast" tab - this is the data we get back from forecast API - can you screenshot that?

**Comment by jopper1988** [comment]
Do you mean this one:

![forecast io](https://cloud.githubusercontent.com/assets/5737203/6284924/37449270-b8f6-11e4-9b42-7edff20dddf1.png)

**Comment by dasgarner** [comment]
Are you sure you aren't in an alien hotspot??

It actually looks like the result we get from the forecast API is totally empty - the alien represents an unmapped state (the empty state).

I think you will need to uncomment some code for us to work out what it wrong.

`modules/forecastio.module.php`
Line 646: `Debug::Audit('Data: ' . var_export($data, true));`

Then go to report fault, follow the instructions, when asked to recreate press "request forecast" again.

**Comment by jopper1988** [comment]
Here is the link to the file:

http://www.filedropper.com/troubleshoot_1

**Comment by dasgarner** [comment]
OK so:
```
file_get_contents(https://api.forecast.io/forecast/yourkey/53.231218,6.570643?units=auto&amp;lang=nl&amp;exclude=flags%2Cminutely%2Chourly): failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

And yet the link works perfectly when I try it here... maybe a network issue? Can you try that link (with your APK key) directly from your web server?

**Comment by jopper1988** [comment]
If i try it on the server then i get a download message that it will download a .json file

**Comment by dasgarner** [comment]
and what is in the file?

**Comment by jopper1988** [comment]
I have uploaded the file

http://www.filedropper.com/jsonfile

**Comment by dasgarner** [comment]
OK - so I don't know then... sorry

The server can reach the file link PHP cannot reach that exact same link - failing with this message `file_get_contents(https://api.forecast.io/forecast/yourkey/53.231218,6.570643?units=auto&amp;lang=nl&amp;exclude=flags%2Cminutely%2Chourly): failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

**Comment by MedusaDelft** [comment]
What type of webserver do you use? IIS, apache?  file_get_contents has some limitations in some circumstances. Maybe it has something to do with encoding?

**Comment by jopper1988** [comment]
I use xampp on my server.

**Comment by MedusaDelft** [comment]
Are you behind a proxy/firewall (software)?  What if you raise your default_socket_timeout setting in php.ini?

**Comment by jopper1988** [comment]
I'm behind a proxy/firewall, only the rss feed works very well. But i will give it a try to raise the timeout. 

What do you need to know for encoding ?

**Comment by MedusaDelft** [comment]
Apparently encoding-differences can be a problem (eg. server: ISO-variant, client: UTF8).

From stackoverflow.com as an answer on the error message mentioned above (maybe @dasgarner can comment on this if this is the case (I'm not able to look into the code now)):
Are you behind a proxy? If so, you'll need to tell PHP about it using stream_context_set_default  or by passing a context created with stream_context_create  as the third param to file_get_contents 

http://stackoverflow.com/questions/3931912/file-get-contents-failed-to-open-stream-connected-party-did-not-respond

**Comment by jopper1988** [comment]
I'm using XAMPP for the webserver. Do need to adjust that or do i need to code into Xibo ?

**Comment by dasgarner** [comment]
Forecast IO doesnt work with Proxy support at the moment. It needs enhancing. I will tag it up accordingly.

**Comment by dasgarner** [comment]
The attached commit contains some modifications which should enable proxy support on the forecast module.

**Comment by mattgrimley** [comment]
Spot on @dasgarner :)

Thanks so much mate, working perfectly for me!

**Comment by dasgarner** [comment]
Great - I will close this out then! Cheers for the fast feedback!

**Comment by jopper1988** [comment]
This don't work for me.

**Comment by dasgarner** [comment]
Its probably cached - try changing the lat/long slightly, or deleting the files in the cache folder in the CMS library

**Comment by jopper1988** [comment]
I get the very strange picture
![forecast](https://cloud.githubusercontent.com/assets/5737203/6505712/42881ac2-c345-11e4-874d-fc2ee0bb7491.png)

**Comment by dasgarner** [comment]
> No data returned, please check error log

**Comment by jopper1988** [comment]
I can't find nothing in the error log within the CMS

**Comment by dasgarner** [comment]
Make sure you have auditing enabled? It is not possible for there to be nothing in the log after doing a request.
