### ISSUE TITLE
Ad Campaign Scheduler : when run manually creates duplicate schedules

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#2980]
If user runs the background task manually it will create the same schedules on each run within the same hour.

**Comment by dasgarner** [comment]
After discussion, we decided that this isn't an issue. Users shouldn't generally be encouraged to run the task manually and the reasons for doing so are limited to debugging. For example running the task manually to get a campaign scheduled last minute is not a use case, campaigns should be planned days in advance, not hour by hour.
