### ISSUE TITLE
Tutorial walk through dead ends

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2982]
OP: https://community.xibo.org.uk/t/live-tutorials-not-up-to-date/28615

The tutorial walk-through has some dead-ends in v3, see the OP for more details.

**Comment by dasgarner** [comment]
**Test**

 - Display tour ❌ this tour gets stuck on the "authorise display" step
 - Content tour ❌ everything worked except "Publish" at the end. I had to wait a long time between clicking the button and publishing for it to register the step
 - Scheduling tour ✅

**Comment by maurofmferrao** [comment]
> **Test**
> 
> * Display tour x this tour gets stuck on the "authorise display" step
> * Content tour x everything worked except "Publish" at the end. I had to wait a long time between clicking the button and publishing for it to register the step
> * Scheduling tour white_check_mark

Thank you for testing, I will investigate those 2 cases. The last one used to have a fixed timer so that the message could appear after publishing ( that may take a while ), but I will try to have a trigger element that can shorten the timer if exists. 🤞🏻

**Comment by maurofmferrao** [comment]
After having tested some runs, I can't replicate the 2 failed tests you found:
 - "**authorise display**" worked every time
 - "**Publish**" refreshed the page and the message appeared right away
 
But by trying to crash the tutorial, I managed to make one of the steps to get stuck and repeat the message even after pressing the button.

So it's not really stable and unfortunately I'm not sure we can improve it more using this library... 😞

**Comment by dasgarner** [comment]
The content one I think we can accept as a limitation as I was able to proceed.

The display one gets me every time - I think because on develop I have selected to "automatically submit this form".

**Comment by maurofmferrao** [comment]
> The display one gets me every time - I think because on develop I have selected to "automatically submit this form".

Got it now! it was exactly that. I will try to fix it

**Comment by maurofmferrao** [comment]
A new PR with the fix: https://github.com/xibosignage/xibo-cms/pull/1568

**Comment by dasgarner** [comment]
Retested and all looks good on the Display tour ✅
