### ISSUE TITLE
Widgets: Twitter Metro render crash with limited elements 

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#2985]
If the number of Tweets to return ( Count ) is lower than the number of elements that are needed to fill the metro grid, the renderer will crash and show just a few items.

The culprit is the `checkBackgroundImage` function in `xibo-metro-render,js`, that needs to validate if the array item is defined to avoid crashing.

```
if (array[index] == undefined) {
  return false;
}
  ```

**Comment by dasgarner** [comment]
Tested before and after patch. ✅
