### ISSUE TITLE
Audience Connector: Regular Maintenance fails with Campaign not found

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2987]
If you enable the audience reporting connector and delete an Ad Campaign which has had some activity (collected some stats), then the regular maintenance task fails with "Campaign not found".

There are two things to resolve here:

 1) it should not be possible for a connector to completely fail the regular maintenance task - we should wrap the dispatcher in a try/catch, but also as a matter of best practice ensure that the handler catches any errors which occur inside it.

 2) if a stat is processed for a campaign that does not exist anymore, it should be skipped instead of crashing

**Comment by ifarzana** [comment]
https://github.com/xibosignage/xibo/issues/2956#event-8013464758, this issue has been resolved by decreasing the `lastRunMessage` to 254 characters, that would mean we may loose some error logs generated by Audience Connector, Can you provide your suggestion regarding this @dasgarner ?

**Comment by ifarzana** [comment]
I suggest we make lastRunMessage column type to text

**Comment by dasgarner** [comment]
The `lastRunMessage` isn't supposed to show full error details, these are to be logged in the error log. The last run message is for general information - for example "Audience Connector: exported 3452 stats, 10 failed."

**Comment by dasgarner** [comment]
What we have now is an improvement as the task does not fail, however it logs the same message over and over without progressing: 



![Image](https://user-images.githubusercontent.com/10400067/212745869-69fbff9a-9c5b-4b7c-b5de-afa077764c96.png)

**Comment by dasgarner** [comment]
I have put this follow on problem into a separate issue which better describes why it is happening.
