### ISSUE TITLE
Twitter Module Tweet Photo not showing

### ISSUE THREAD

**Issue by mbreckers** [xibosignage/xibo#299]
I have a display showing with the twitter module on it. Module works fine except if there is a photo in the tweet then photo doesnt show.

Running 1.7.1 on Windows 7

**Comment by dasgarner** [comment]
Whereabouts doesn't it show? The designer or the player?

**Comment by mbreckers** [comment]
It shows perfectly on the designer but doesn't show on the player

**Comment by michaklein** [comment]
Hi, I have a similar problem, but I don't get the images in the player AND the designer. The profile pics are shown but not the pics in the post itself. Xibo 1.7.1

**Comment by mbreckers** [comment]
Sounds like we're having the same problem, I had to add the [Photo] variable to the design template. It shows fine on the designer but there is only an empty line where the photo should be on the display. I'm guessing it's just a problem with the code specifically in the twitter module but it's too complicated for me to go through the module code

**Comment by michaklein** [comment]
Ah thanks! I couln't find the documentation and didn't know the variable. I just added [Photo] and now it's the same behavoir as you described.

**Comment by mbreckers** [comment]
Yeah I had to look at the code for the twitter module to find the variable. Clearly it does work cause it shows up in the designer. It's just an issue between the server and the player

**Comment by michaklein** [comment]
By the way: Same problem with the android player.

**Comment by dasgarner** [comment]
In all likelihood, the player hasn't finished downloading all of those images, so it shows what it can (i.e. just the rest of the template).

If your twitter module is on screen for a long duration, then it could be a while before it refreshes and uses the downloaded images - it might even be that new images are required before it refreshes.

What is the duration on the twitter media item?

**Comment by michaklein** [comment]
The duration was 20 seconds, 4 tweets. In the module config:  cache period 300 sec, cache period 24 (hours). I now tried different settings, e.g. media item duration 60 sec for 4 tweets, cache periods longer and shorter... I don't get the images.

**Comment by mbreckers** [comment]
Mine is 90 seconds, alternating with an image in the region which shows for 30 seconds, so basically comes round every two minutes.

Cache period is 300 seconds and the Cache period for images is one hour.

Layout shows for 24 hours a day, except for two hours between seven and nine PM.

**Comment by mbreckers** [comment]
From what I can tell the profile images are downloading to the client local Xibo Library, but the photo's on individual tweets arent.

**Comment by dasgarner** [comment]
I've just happened across the issue, can you try adding a line to `modules/twitter.module.php` ?

In between line [928](https://github.com/xibosignage/xibo-cms/blob/develop/modules/twitter.module.php#L928) and 929, add:

``` php
$layout->AddLk($this->layoutid, 'module', $file['mediaId']);
```

**Comment by mbreckers** [comment]
Just tried it, can confirm that it worked for me :)

**Comment by dasgarner** [comment]
That's great - we will get that added to 1.7.2

**Comment by michaklein** [comment]
Hi Dan, works fine! Thank you for your quick help!!

**Comment by hcjsy** [comment]
that worked for me for [photo]. Is there a list of twitter variables we can use ?

**Comment by dasgarner** [comment]
Currently:

[Tweet]
[User]
[ScreenName]
[Date]
[ProfileImage]
[Photo]
