### ISSUE TITLE
Audience Reports: minor adjustments and snagging

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#2998]
Total rows, rounding, etc

**Comment by ifarzana** [comment]
Audience reporting connector:

## Campaign Proof of Play
 * Total row added
 * Rounding on the spend/impressions column

## Display played percentage
 * Table: order by spend descending
 * Charts: contrasting text colour for labels
 * Rounding

## Display ad plays
 * Chart for spend
 * Spend in the table
