### ISSUE TITLE
Xibo 1.7.1 - Unable to "re-add" a client on same CMS 1.7.1

### ISSUE THREAD

**Issue by D0NZAUKER** [xibosignage/xibo#300]
Hello,

I had to uninstall / reinstall Xibo client 1.7.0 on a Windows pc, before doing this, I have deleted the display in CSM but after the reinstallation I'm unable to add again the client display in CMS.
I receive the message "Display is awaiting licensing approval from an Administrator." but the display is not listed in the CMS (1.7.1) so I cannot authorize it !

I tried to uninstall again the client and change the client ID string without success.
I think it's not a network issue, anyway changing ip address can solve ?
Restarting Apache webserver ?
How to completely remove Xibo ? After reinstalling I see that configuration options are already set as in the previous installation.

Regards.

**Comment by D0NZAUKER** [comment]
I have added a different display client ad it worked, so it's possible that the affected machine was "banned" from CMS ???

**Comment by dasgarner** [comment]
It may not have been deleted cleanly for some reason. Best thing to do is change the "hardware key" in the Player Settings.

**Comment by D0NZAUKER** [comment]
Hello,

I already tried this solution, at first I only edited the last 5 digits of the existing ID without sucess, then I also tried with "califragilisticexpialidocious".
Same story :\

**Comment by dasgarner** [comment]
hmm, the only thing that identifies the player in the CMS is that key - each new key should generate a new display record - as you have noted with an entirely new player.

Unless the key is not being saved for some reason.

You could try setting the CMS log level to "audit" and then trying the connection again - the log should then have a "RegisterDisplay" log message which shows the key the player is sending.

**Comment by D0NZAUKER** [comment]
I have taken a drastic decision, I'm rebuilding from scratch the machine :smile_cat:

**Comment by D0NZAUKER** [comment]
Ok, reinstalling Windows from scratch solved the issue, anyway I was unable to reuse old display name.

**Comment by dasgarner** [comment]
OK, well at least you have it resolved!
