### ISSUE TITLE
Player Status Window : webOS and Tizen improve data presentation

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#3004]
Currently for webOS/Tizen we do some processing on the data received from the players, calling `JSON.stringify` on arrays and formatting space.

v4 webOS/Tizen players will change the format in which json data is sent to the CMS on notifyStatus and CMS should be adjusted to adapt to those changes.

We may need to get the player version before we call display status in CMS and handle the webOS/Tizen data processing differently depending on that - to make sure older players are still formatted the way the are now in v4.

**Comment by dasgarner** [comment]
I have tested this but have further questions ❌
