### ISSUE TITLE
PDF Widget: External preview speed differs from editor preview

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#3033]
Steps to reproduce:
 1. Create a PDF widget with Duration set to 5 seconds and with `Duration is per page` checked.
 2. Preview on the Viewer and check that each page shows for 5 seconds.
 3. Go back to the Layout grid page and use the row menu to preview.
 4. Now each page only shows for about 1 second.

**Comment by ifarzana** [comment]
The problem still persists unfortunately.

**Comment by maurofmferrao** [comment]
I noticed that it wasn't working in develop and ran `Verify All` modules, and it seems to be working now, can you check again please @ifarzana . Still needs to be fixed for v4 tough.

**Comment by ifarzana** [comment]
`Verify All` needed to be applied and then the preview worked as expected :heavy_check_mark:
