### ISSUE TITLE
Problem with connecting to Canva

### ISSUE THREAD

**Issue by myymi** [xibosignage/xibo#3034]
I have followed this instruction to the letter: https://xibosignage.com/docs/setup/canva-integration
I still get {"error":0,"message":"API configuration problem, consult your administrator"} on the connection window.
My system is self-hosted xibo server, upgraded to the latest. Custom install, not docker, on Ubuntu 20.04 LTS.
I also uploaded troubleshoot dump from the time I tried to connect to my xibo server.
[Xibo_Canva_troubleshoot.zip](https://github.com/xibosignage/xibo/files/10999161/Xibo_Canva_troubleshoot.zip)

**Comment by dasgarner** [comment]
Hi and thank you for reporting this issue!

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this support request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

Thanks!

**Comment by dasgarner** [comment]
When you do take this over to community here is the relevant log file:

```
1629477,b9524bb,"2023-03-17 10:09:25",AUTH,/api/authorize/,GET,"Unable to read key from file /data/xibodata/certs/private.key",,ERROR
1629478,b9524bb,"2023-03-17 10:09:25",AUTH,/api/authorize/,GET,"API configuration problem, consult your administrator",,ERROR
```

This means that your Xibo installation has not been configured correctly and therefore Canva cannot connect to your CMS API.

**Comment by myymi** [comment]
Thank you for quick reply! This last hint gave me an idea where to look at, so I can fix it myself now I guess.
