### ISSUE TITLE
Forecast IO - add various enhancements

### ISSUE THREAD

**Issue by MedusaDelft** [xibosignage/xibo#304]
When I use Standard International Units, temperatures are returned with decimals (eg:  0.86   or  2.72).

Please add an option for the temperature to round these. I suggest:
0 -> no decimals     eg:  1  or  3
1 -> 1 decimal         eg:  0.9  or  2.7
2 -> 2 decimals       eg:   0.86  or  2.72

Maybe this can be used to the other options Forecast IO returns (windspeed, pressure etc).

Windspeed is returned in "miles per hour". Other conversions don't have  "Beaufort".

Windbearing is returned in degrees (0 is absolute north). Is it possible to return a text-value (like north/east/south/west) or an arrow pointing in the direction. These should probably be new properties.

Can "humidity" also be expressed as a percentage?

Is it possible to add a javascript-textarea (like css is present now) when 'override template' is selected, so we can animate icons, add an arrow for windbearing ourselfs or do other stuff?

**Comment by dasgarner** [comment]
[temperatureFloor] gets you the rounded temperature figure. I think the wind speed issue is a problem with the API, everything else seems feasible.

By the way - if you do come up with interesting templates - it would be great to include them. There are template files in the theme folder `modules/theme/forecastio/`

**Comment by MedusaDelft** [comment]
[temperatureFloor]  gives me two dashes. It is not defined in the Forecast api, see:
https://developer.forecast.io/docs/v2

If I create a descent design, I'll let you know.

**Comment by MedusaDelft** [comment]
wind speed is returned. Unfortunately not the beaufort scale. This is the array for the beaufort scale:

    array( 0	=> array('mph'	=> array(0, 0.7)
					,'kmh'	=> array(0, 1.1)
					,'ms'	=> array(0, 0.3)
					)
		,1	=> array('mph'	=> array(0.7, 3.4)
					,'kmh'	=> array(1.1, 5.5)
					,'ms'	=> array(0.3, 1.5)
					)
		,2	=> array('mph'	=> array(3.4, 7.4)
					,'kmh'	=> array(5.5, 11.9)
					,'ms'	=> array(1.5, 3.3)
					)
		,3	=> array('mph'	=> array(7.4, 12.2)
					,'kmh'	=> array(11.9, 19.7)
					,'ms'	=> array(3.3, 5.5)
					)
		,4	=> array('mph'	=> array(12.2, 17.9)
					,'kmh'	=> array(19.7, 28.7)
					,'ms'	=> array(5.5, 8)
					)
		,5	=> array('mph'	=> array(17.9, 24.1)
					,'kmh'	=> array(28.7, 38.8)
					,'ms'	=> array(8, 10.8)
					)
		,6	=> array('mph'	=> array(24.1, 31)
					,'kmh'	=> array(38.8, 49.9)
					,'ms'	=> array(10.8, 13.9)
					)
		,7	=> array('mph'	=> array(31, 38.4)
					,'kmh'	=> array(49.9, 61.8)
					,'ms'	=> array(13.9, 17.2)
					)
		,8	=> array('mph'	=> array(38.4, 46.3)
					,'kmh'	=> array(61.8, 74.6)
					,'ms'	=> array(17.2, 20.7)
					)
		,9	=> array('mph'	=> array(46.3, 54.8)
					,'kmh'	=> array(74.6, 88.1)
					,'ms'	=> array(20.7, 24.5)
					)
		,10	=> array('mph'	=> array(54.8, 63.6)
					,'kmh'	=> array(88.1, 102.4)
					,'ms'	=> array(24.5, 28.4)
					)
		,11	=> array('mph'	=> array(63.6, 72.9)
					,'kmh'	=> array(102.4, 117.4)
					,'ms'	=> array(28.4, 32.6)
					)
		,12	=> array('mph'	=> array(72.9, 10000)
					,'kmh'	=> array(117.4, 10000)
					,'ms'	=> array(32.6, 10000)
					)

Obviously, the 10000 for beaufort 12 is made up by me.

**Comment by MedusaDelft** [comment]
@dasgarner Dan, how do I include a template.json?  If I create one and open the Forecast IO, an option is added to the 'Weather template' select-box, but it's value and name are blank.
Is there a naming convention or do I have to do more (registering the template?)

**Comment by dasgarner** [comment]
You just drop the file in, nothing more. You need to make sure your json file includes all the fields in the current examples and that your HTML is properly escaped.

If you look at your forecast tab on the media module (as a super admin) you will see that we output the JSON for the template currently on that item.


[temperatureFloor] is added by Xibo - you should see it in the forecast request tab.


I still think Beaufort should be added to the API source as it depends on the units they decide to output. But I suppose we could so some matching, swapping and replacing.

**Comment by MedusaDelft** [comment]
I noticed the temperatureFloor in the xibo forecast request tab. But it displays a dash for me.

For 'current'  it DOES show the temperatureFloor. BUT for 'daily' it shows a dash (on the bottom of the tab). Apparently that's the one used when processing the 'daily' chunk.

I agree with you on the api side for Beaufort. That would be the place to be. I was suprised it wasn't there.

**Comment by dasgarner** [comment]
In `modules/forecastio.module.php` at [L690](https://github.com/xibosignage/xibo-cms/blob/develop/modules/forecastio.module.php#L690)

Try:

``` php
$data['daily']['data'][$i]['wicon'] = (isset($icons[$data['daily']['data'][$i]['icon']])) ? $icons[$data['daily']['data'][$i]['icon']] : $icons['unmapped'];
            $data['daily']['data'][$i]['temperatureFloor'] = (isset($data['daily']['data'][$i]['temperature'])) ? floor($data['daily']['data'][$i]['temperature']) : '--';
```

**Comment by MedusaDelft** [comment]
@dasgarner this won't work. In the daily array, it's not 'temperature' but 'temperatureMax' or 'temperatureMin'.

I suggest:

			$data['daily']['data'][$i]['temperatureFloor'] = (isset($data['daily']['data'][$i]['temperatureMax'])) ? floor($data['daily']['data'][$i]['temperatureMax']) : '--';

**Comment by dasgarner** [comment]
I think these items can now be closed.
