### ISSUE TITLE
Reporting: Time Connected Summary does not show connected displays

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3043]
- Investigate time connected summary report that currently does not show connected displays. 
- If for a selected time range a display was not disconnected at all and connected for the whole time then the report should show a connected record.

**Comment by dasgarner** [comment]
Tested ✅ 

Please can we add some rounding for wetphal.



![Image](https://github.com/xibosignage/xibo/assets/10400067/c1ee1c00-a3f0-44e2-b93a-92a9e8b5d656)
