### ISSUE TITLE
DB: switch collation to utf8mb4_unicode_ci

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3044]
OP: https://community.xibo.org.uk/t/use-utf8mb4-to-support-emojis/29130

We also need to change the SET NAMES command in PDO Storage Service.

**Comment by dasgarner** [comment]
After discussing with Alex, we think it's possible to make these changes in a migration.

**Comment by LiaraAlis** [comment]
I also did this with my database. I encountered no problems. But you should note that the conversion may take some time.

**Comment by dasgarner** [comment]
Thanks for confirming.

> But you should note that the conversion may take some time.

That is what we're worried about - particularly on a large database - but we think we can come up with a sensible procedure for it.

**Comment by LiaraAlis** [comment]
Maybe you can make the conversion optional for existing systems? It is possible to add a command or something that you have to execute manually? If this is an option, we should find a solution to switch which `SET NAMES` command to execute. Maybe with a config file this is only created on a fresh install or similar?
