### ISSUE TITLE
Vulnerability disclosure

### ISSUE THREAD

**Issue by SharonBrizinov** [xibosignage/xibo#3049]
Hi!

Sorry for posting this here but [we (Claroty Team82)](https://claroty.com/team82) are trying to find the proper way to responsibly report & disclose a couple of security issues we've found in Xibo CMS. What's the best way to do this? we prefer to not expose them here publicly.

Thanks!

**Comment by dasgarner** [comment]
Hi, thank you for raising this here. You can email us on support@xibosignage.com in order to disclose the vulnerabilities.

Best wishes,
Dan
