### ISSUE TITLE
Suggestion: add a button 'Apply' on media dialogs

### ISSUE THREAD

**Issue by MedusaDelft** [xibosignage/xibo#305]
Suggestion: add a button 'Apply' to media dialogs (eg. Text, Forecast IO, Ticker)  where you can override the default template.  Is probably saves a lot of time when changing css properties (and html)

Now I have to save, reload the preview, open the dialog again, go the the right tab, scroll down (sometimes), make the change and try again.

Using the 'apply' button, the values get saved (code probably is there already), but the dialog stays open.

Possible pitfalls: ? values that should be there but who are not there yet ?

**Comment by dasgarner** [comment]
that is a good idea - no pitfalls as far as I can see, although it might need some new javascript to reapply the preview on apply

**Comment by MedusaDelft** [comment]
Great, thanks!
I don't mind refreshing the preview of the layout. It's on another tab anyway.

**Comment by dasgarner** [comment]
ah right, yes I suppose it would be as it is covered
