### ISSUE TITLE
Folders : Initial Folder not always correct on add/edit forms

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#3056]
It looks like "sometimes" without any cache/browser localStorage on first form render the folder selector in the form defaults to root (1) folder for objects that are in a sub-folders

Steps to easily replicate this:

- Log out of the CMS.
- Clear the cache in the browser or go to the login page in an incognito browser window.
- Log in
- Go to Layouts and click All Folders.
- Choose a sub folder with a layout, open edit form :  Current Folder will say root

If you close the edit window and edit the layout again, this time it will correctly state the sub folder it is saved in

**Comment by dasgarner** [comment]
✅ tested
