### ISSUE TITLE
Black Screenshot thumbnail (Only Videos)

### ISSUE THREAD

**Issue by vmesquita** [xibosignage/xibo#306]
When is showing videos on Xibo Client, the screenshot thumbnail is black. When is showing an image, the screenshot is ok! This is a problem or need some adjustment?
Version: CMS - 1.7.1 / Android 1.7 R52

**Comment by laercionit** [comment]
+1 for this

**Comment by dasgarner** [comment]
Its a problem we can't get around at the moment... the video doesn't render in the same "hierarchy" as the rest of the objects on screen, meaning the video is a void (it shouldn't be considered a black space, it is actually a hole)

As we develop the video functionality further it may be possible to request a frame snap from the video - but that is not something we have at the moment.
