### ISSUE TITLE
Powerpoint

### ISSUE THREAD

**Issue by jojooper** [xibosignage/xibo#307]
Hello.  I'm having a problem getting powerpoint to work.  When I update the layout with a powerpoint, I get a pop up asking if I want to open or save.  If I click open, it open in powerpoint and not in the browser.  How do I get it to run in the Zibo client?  I'm using CMS 1.7.1 and the client is on a Win 8.1 box.  I've enabled Chrome and also made it the default browser, but that made no difference.  Everything else seems to be working nicely.
Thanks,
Jojo

**Comment by Speedy-Gonzalez** [comment]
I don't think PowerPoint will work in Chrome.

Have you tried this http://xibo.org.uk/manual/en/media_module_powerpoint.html#machine_preparation or https://answers.launchpad.net/xibo/+faq/2569.

**Comment by jojooper** [comment]
Thanks for the info.  I'll give that a try and let you know how it goes.
