### ISSUE TITLE
Folders : non super admin user created folder permission issue

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#3072]
OP - https://community.xibo.org.uk/t/cms-backend-campaign-not-showing-created-folder/29581

Folders do not have owners, when non super admin user creates a Folder under Root Folder, then that user will not have permissions to it - meaning rename will not work and on page reload that folder will be hidden from the user.

When the same user creates a folder under a folder to which they have view/modify permissions, then it works correctly.

**Comment by dasgarner** [comment]
What was out solution here, to prevent that?

**Comment by PeterMis** [comment]
Yes, as per the linked commit, added check to the condition for folder create in context menu and adjusted the folder.add feature description to better describe what it actually does

**Comment by dasgarner** [comment]
✅ tested
