### ISSUE TITLE
Tags : issues with required value

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#3073]
Adding/Editing a Tag with `required value?` checkbox enabled throws `provided tag xxxx requires a value` error and the form cannot be submitted.

The validation of this should happen on tagLink only, Tag object itself no longer has value associated with it, as such the condition in `validateTagOptions()` will always fail when adding/editing a Tag with isRequired.

**Comment by ifarzana** [comment]
Tested :heavy_check_mark:
