### ISSUE TITLE
Folders : homeFolderId not handled on Folder delete

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#3083]
When we attempt to delete a Folder that is set as a homeFolderId to any existing user, this operation will throw SQL constraint error.

```
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`cms`.`user`, CONSTRAINT `user_ibfk_2` FOREIGN KEY (`homeFolderId`) REFERENCES `folder` (`folderId`))
```

The same issue affects v4.
This should be handled on Folder delete - either directly in sql in Folder entity before delete from folder table or via event.

**Comment by dasgarner** [comment]
✅ tested
