### ISSUE TITLE
Reporting: time connected report with "tall rows"

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3084]
If a the calculated percentage has a lots after the decimal point, the row expands in height and you get "blue padding" around it which looks strange.

Can we make sure that we format the percentage correctly to prevent this from happening?

E.g.

![image](https://github.com/xibosignage/xibo/assets/10400067/39107fd6-5814-4a3e-a686-f3a2ca76c7b0)

**Comment by ifarzana** [comment]
Looks good on develop

Tested :heavy_check_mark:
