### ISSUE TITLE
Missing images in documentation / Layouts / Regions

### ISSUE THREAD

**Issue by andyblackham** [xibosignage/xibo#309]
the page 
http://xibo.org.uk/manual/en/layouts_regions.html

has three missing images, 404 on the following:
http://xibo.org.uk/manual/en/img/layouts_designer_region_resize.png

http://xibo.org.uk/manual/en/img/layouts_designer_region_resize_handles.png

http://xibo.org.uk/manual/en/img/layouts_designer_region_menu.png

**Comment by MedusaDelft** [comment]
Found another one:
[http://www.xibo.org.uk/manual/en/advanced_database_model.html]http://www.xibo.org.uk/manual/en/advanced_database_model.html

**Comment by MedusaDelft** [comment]
Found another two:
(Adding data  and  Importing from CSV file)
http://www.xibo.org.uk/manual/en/media_datasets.html

**Comment by MedusaDelft** [comment]
Another missing image
http://www.xibo.org.uk/manual/en/displays.html  -->  http://www.xibo.org.uk/manual/en/img/displays_cms_media_inventory.png
