### ISSUE TITLE
User: force password change should disallow the prior password

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3090]
OP: https://community.xibo.org.uk/t/bug-forcing-password-changes-doesnt-actually-force-real-password-changes-all-v3-versions/29910

There is reasonable expectation that the new password will be different from the existing one, and so we should validate that. In effect we will be validating that the new password does not generate the same hash as the current one.

**Comment by ifarzana** [comment]
Tested :heavy_check_mark:
