### ISSUE TITLE
Colour picker rendered off screen when at the bottom of the property panel

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3092]
<img width="306" alt="image" src="https://github.com/xibosignage/xibo/assets/10400067/30a61a84-53c0-4f29-b43c-c442f2e8d2d6">

**Comment by rubenpingol-xibo** [comment]
✅ Tested (in both ways 1. manual addition of color picker into the xml and 2. resizing window)

**Comment by maurofmferrao** [comment]
@rubenpingol-xibo I've created a new PR to fix the case when we have a short form and a colour picker at the end of it. It will become a scroll area even with all the space to be rendered.
Can you please re-test it as soon as it gets merged? Thank you!

![Image](https://github.com/xibosignage/xibo/assets/18596680/2ce72521-d55f-439c-b09d-8e49ac26f269)

**Comment by rubenpingol-xibo** [comment]
Sure

**Comment by rubenpingol-xibo** [comment]
✅ Re-tested
