### ISSUE TITLE
[4.0.0] fresh installation, no login, only upgrade message

### ISSUE THREAD

**Issue by pxlcore** [xibosignage/xibo#3096]
Hi,

I've downloaded the new Xibo CMS 4.0.0 tarball and installed it on a fresh Apache Webserver with MariaDB.
The installation process runs without errors.

At the end of the installation process you have to enter the library location and server key.
After entering these information and click NEXT, I got the following message:

```
The CMS is temporarily off-line as an upgrade is in progress. 
Please check with your system administrator for updates or refresh your page in a few minutes.
```

What parameter do I have to change to disable this message?
Is this an error in the install routine? I didn't upgrade anything.

Thank you for you help.
Greetings.

**Comment by dasgarner** [comment]
That message usually indicates that some of the database migrations are still pending. If you run `vendor/bin/phinx migrate` what output do you see?

**Comment by pxlcore** [comment]
Hi Dan,

thank you for this hint!

My user did not have sufficient rights. :(

```
[...] INDEX command denied to user 'xibo'@'localhost' [...]
```

I added the INDEX privilege to the user. That worked perfectly.


Thank you very much.

Problem is solved. You can close this issue.

Greetings from Germany.

**Comment by dasgarner** [comment]
Ah, that makes sense!

Thanks and greetings from the UK!
