### ISSUE TITLE
Function not implemented: AH00141: Could not initialize random number generator

### ISSUE THREAD

**Issue by vinnco** [xibosignage/xibo#3097]
When installing the docker of Xibo V4.0, it will throw a `Function not implemented: AH00141: Could not initialize random number generator`-error. 
According to various sources, this is due to an lower kernel-version. Unfortunately, we use Docker on a Synology NAS, wherefore updating the kernel is not possible. 
Could there be a image/version which is suitable for kernel-versions of 3.10?

`Linux SGH-NAS 3.10.108 #64570 SMP Fri Jun 2 23:36:41 CST 2023 x86_64 GNU/Linux synology_braswell_916+`
`Synology DS916+`
`DSM 7.2-64570 Update 1`

NextCloud faces the same problem,  they used php:8.0-apache-buster to counter the issue.
[https://github.com/nextcloud/docker/issues/1574](https://github.com/nextcloud/docker/issues/1574)

**Comment by dasgarner** [comment]
Thanks for creating this issue, sorry I didn't see it before creating one myself from your community post: https://github.com/xibosignage/xibo/issues/3099

Closing this one as a duplicate (because we've started processing the other one already).
