### ISSUE TITLE
Best practice for timings in layouts

### ISSUE THREAD

**Issue by andyblackham** [xibosignage/xibo#311]
Let me give a hypothetical scenario, and see what people think...

I require a layout, with three regions:
Region 1 contains a video, the videos total play length, fade in to fade out is 180 seconds.
Region 2 contains a digital clock
Region 3 contains a ticker

I would like the layout to play the video and end, moving on to the next scheduled item immediately.

Questions:
a. If I have already set the media's duration in the media view, do I need to set it elsewhere?
b. Should I set the clock length to 180 seconds too?
c. If I set the ticker to a per-item duration, does the number of items affect the play length?
d. If I set the ticker to a total ticker duration (lets say 180 again) how can I control the on screen time per item? As I have no control over the number of items in external feeds, can this affect the view time per item - i.e. total time / items = time per item?
e. what does setting a play time of 0 do to the different item types?

thanks
andy

**Comment by dasgarner** [comment]
Hi Andy,

Sorry for brief answers :)

a) No
b) It doesn't matter, as long as it is not more than the video length
c) Yes (number of items * duration per item)
d) Set the number of items you want to take from the feed - only way to guarantee each items time without effecting total length
e) You can only set it on video (or should only be able to)

**Comment by andyblackham** [comment]
Thanks Dan, and for clarity, does setting the video duration to 0 mean play
to end and stop or loop?

a

**Comment by alexharrington** [comment]
Play to end and stop
