### ISSUE TITLE
Playlist Editor: Delete button on Rich Text input deletes selected widget

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#3115]
If we add a Widget that has Rich Text input ( like `Clock - Digital` ), and press the Del key whilst editing the Rich Text editor, the widget will be deleted. We need to make sure that the Del only deletes an element if we're not focused on any input field.

Also, Delete doesn't work if we open the inline Playlist Editor and go back to the Layout Editor.

**Comment by dasgarner** [comment]
✅ tested both
