### ISSUE TITLE
Layout Editor Viewer: Default text isn't the same as preview

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#3117]
The default text for the editor is browser defined and not the same as we have in the preview, we need to set that with CSS to match it.

**Comment by rubenpingol-xibo** [comment]
Hey @maurofmferrao, what do you mean by default text? Is this a text element when added to the editor?

**Comment by maurofmferrao** [comment]
When we had a text element to the editor, without changing the font type, and then preview, the font-type of the preview would be different.

**Comment by dasgarner** [comment]
✅ the default text is the same in the preview and player

**Comment by rubenpingol-xibo** [comment]
✅ tested
