### ISSUE TITLE
A way to load additional files

### ISSUE THREAD

**Issue by MedusaDelft** [xibosignage/xibo#312]
I'm trying to create a moving background for my weather forecast IO-module (media on a region in a layout). I've read that I regions can't overlap (currently). So I use CSS to center my content and put a background in the div which I animate with keyframes.
For the background-image i currently need to enter an URL to a live website or the library on the xibo-server. Is there a way to support additional files like these (background-)images, fonts etc.?
Or do I have to be patient and wait for Xibo 1.8 ?

**Comment by dasgarner** [comment]
Well, there will be a way to do this in 1.8.

In the mean time the workaround is a little clunky - you upload the file to the library, make a note of its file ID, reference that in your CSS/HTML as a local reference, with the original extension (i.e. 14.jpg) and then assign those files to your display (display page, assign files).

They will be downloaded by the Display and available as your local reference in the HTML as the HTML file is stored in the local library folder along with the assigned file.

**Comment by MedusaDelft** [comment]
Great tip! I did not know that. Thanks!   (I used the reference ID already for my moving background, but loaded it off the narrowcasting-server)

**Comment by dasgarner** [comment]
Right, yeah.

The bit we will automate is referencing it and assigning it - but at least you can take those steps manually for now.
