### ISSUE TITLE
RSS widget: add support for non-standard/other image enclosures

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3121]
v3 supported pull an image from a generic tag such as `[media:content|image]`. v4 does not and therefore lacks some capability we had previously.

Add a new select list with some common image tag properties, and the option to provide a custom one.

We should also handle and populate this property on upgrade from v3.

OP: https://community.xibo.org.uk/t/v4-0-0-some-bugs-zmq-problems/29954/6

**Comment by maurofmferrao** [comment]
Tested! ✅
