### ISSUE TITLE
Unlogical name of button

### ISSUE THREAD

**Issue by MedusaDelft** [xibosignage/xibo#313]
When I edit the name of a dataset, I'get presented a dialog. To save the changed name, I have to click on the button named 'Edit'. In other dialogs, the name of the button to save seems to be called 'Save'.

**Comment by andyblackham** [comment]
would this be better as 'Update' ?

**Comment by MedusaDelft** [comment]
Why not 'save' like all/most other dialogs?

**Comment by dasgarner** [comment]
Save sounds sensible to me...
