### ISSUE TITLE
Weather widget: changing the language doesn't affect the whole template

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3130]
It actually only effects the weather summary returned by Open Weather.

We could get some easy wins (date/time, etc) by setting the moment locale to lang selected, instead of the global locale. There will be things that still aren't translated - such as "Humidity", "Wind", etc, as these are hard coded in the template.

**Comment by ifarzana** [comment]
Claimed

**Comment by ifarzana** [comment]
Wind, Humidity, Temperature etc. were not translated

https://develop.xibo.co.uk/layout/designer/2698

**Comment by ifarzana** [comment]
:white_check_mark: tested
