### ISSUE TITLE
Embedded: Your library reference 0 does not exist

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3134]
It is not possible to embed HTML/JS content which has `[0]` array accessors inside due to the following error message:

<img width="248" alt="image" src="https://github.com/xibosignage/xibo/assets/10400067/d8f1b1f3-b21f-4ce0-92d6-682940955180">

**Comment by maurofmferrao** [comment]
The message keeps appearing for the array accessors, but we now have a help text message explaining not to use them, so I guess this is how it's supposed to be. Tested! ✅

**Comment by dasgarner** [comment]
Actually I don't think that's right/good enough. I'll move this issue into the next milestone for further consideration.

**Comment by dasgarner** [comment]
I have added more help text to explain what the user should do. 

The only way we could improve this further is to have a different notation for library references, which would be a larger change. E.g `$#1234#$`

**Comment by maurofmferrao** [comment]
Tested! ✅
