### ISSUE TITLE
Upgrade: v3 to v4 no modules enabled

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3137]
After upgrading from v3 to v4 none of the modules are enabled.

**Comment by dasgarner** [comment]
The root cause of this issue appears to be a duplicate module in the pre-upgrade database, causing the migration which converts those modules to bomb out.

The workaround is to manually go and enable the modules you want.

**Comment by PeterMis** [comment]
Tested ✔ (3.3.8 with duplicate modules -> upgrade to develop (4.0.4) everything looks good)
