### ISSUE TITLE
Media dataset shows green borders + text but does not save

### ISSUE THREAD

**Issue by MedusaDelft** [xibosignage/xibo#314]
On the 'advanced' tab of a media dataset, when I fill in '1' for 'Lower row limit'  and '0' for 'Upper row limit' and hit 'save', I see green for text and field borders, but it does not save. No other message visible. When I fill in '1' for 'Upper row limit' the values are saved and the dialog will close.

I noticed some other strange behaviour. After a couple of tries to save the dialog with the error, and in the end filling in '1' for 'Upper row limit', saving and opening the dataset again, I noticed that the selected fields are trippled!

**Comment by dasgarner** [comment]
When I do that I get `Upper limit must be higher than lower limit` as an error message.... odd!

Can you run through the fault page and let us have the logs?

**Comment by MedusaDelft** [comment]
Have you tried it when editting? I should have mentioned that. Sorry!  
Now on another screen, I do get the message, but it falls of my screen as it is at the bottom. And still all 4 fields and text labels are green.

**Comment by dasgarner** [comment]
> I do get the message, but it falls of my screen as it is at the bottom

Can you scroll down to it?

> And still all 4 fields and text labels are green.

The green indicates that the fields have valid values according to the type of value we are expecting. The more complicated validation logic happens after you press OK.

**Comment by MedusaDelft** [comment]
Ok, I understand now. We/I do usually give fields a red border with it's message underneath the field that has errors (complicated or not). So there's the confusion with the green fields coming from I guess. Please close if you keep it this way.

**Comment by dasgarner** [comment]
If you would like to make those enhancements - we'd be more than happy with that behaviour. The error returned from the call would have to contain the form field that errored somewhere i'd imagine - by name, as we have that information.
