### ISSUE TITLE
Webpage widget with & in the URL does not work

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3140]
If you insert amp; after each ampersand in the URL it then works on the R400 player but doesn’t show in the preview

**Comment by dasgarner** [comment]
This exposes several issues:
- [ ] The webpage widget should be `native` not `html`
- [ ] We shouldn't be outputting any options in `html` widgets
- [ ] We are not outputting the property values in the XLF options

**Comment by PeterMis** [comment]
Tested ✔ ( looks like it works correctly on the players now)

The preview in Layout Editor did not seem to work for webpage (regardless if it has & in the url or not ), not sure if that's expected
