### ISSUE TITLE
Embedded widget: Javascript content script tags

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3141]
We used to suggest users put in their own script tags, which was not technically possible in v4, so we now suggest that they dont. However, there was no auto-upgrade of that and we don't gracefully fall back - we should.

**Comment by maurofmferrao** [comment]
When migrating an Embedded widget from v3 to v4 with `link` tags in HEAD content, it failed in v4 ( because they were inside the `script` tag ). Maybe we need to add a new field in v4 for Javascript (without script tags) and keep the HEAD content with script tags like in v3.

**Comment by maurofmferrao** [comment]
Tested! ✅
