### ISSUE TITLE
Playlist Editor: some items are missing the file name

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3142]
For now, we just check if the name on the widget is null/undefined. But by saving some other widget property, the name gets changed to empty string (''), and that removed it from the Item in the playlist

OP: https://community.xibo.org.uk/t/v4-0-2-layout-playlist-not-all-filenames-are-showing/30003

**Comment by Eldertoon** [comment]
Hi,
After upgrading (3.3.7>4.0.1>4.0.2), names are missing in many of my playlists and I don't see any workaround to find the corresponding files (preview could be used, but that would be a tough work).
Note that most of the files are used only once, so this seems only to be cache related or something like that.
![image](https://github.com/xibosignage/xibo/assets/7791681/7a8dfa0a-5dfe-49aa-9ec2-e5d422bb4f96)

**Comment by dasgarner** [comment]
Thank you - yes that is what this bug is describing too, and will be fixed in 4.0.3
