### ISSUE TITLE
Widget: DataSet [DisplayId] filtering doesn't work on the player

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3144]
If you filter your dataset by [DisplayId] or [DisplayGeoLocation], it does not work.

**Comment by PeterMis** [comment]
There seems to be also a more general problem with `[DisplayGeoLocation]`. 

It supposed to be used in a formula column in dataSet, however as we are not replacing it when validating the formula, mysql will likely fail there.

It also looks like after mysql upgrade the `GEOMFROMTEXT` replacement we were using to create the point for CMS is no longer correct syntax - it should be `ST_GEOMFROMTEXT` instead.

I will include the above fixes in this issue.

**Comment by dasgarner** [comment]
:white_check_mark: tested (works with displayId 0 and on the player).

Discovered https://github.com/xibosignage/xibo/issues/3177 during this test.
