### ISSUE TITLE
Widget: embedded has transparent, scale and preload defaulted differently in v4

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3146]
All three options here appear to be enabled by default when adding a new embedded widget in v4:

![image](https://github.com/xibosignage/xibo/assets/10400067/dd72afed-c436-489a-980f-264ca2d2a32d)

Whereas they were all off by default in v3.

‘Background Transparent?’ and ‘Preload’ both break Youtube as only audio plays with a black screen while using ‘Background Transparent’ and ‘Preload’ starts the video offscreen.

**Comment by maurofmferrao** [comment]
Default options are now set to `off` by default, and embedded Youtube plays with `Background Transparent` and `Preload` ✅
