### ISSUE TITLE
Restricted User cannot access timeline edit page

### ISSUE THREAD

**Issue by jonwitts** [xibosignage/xibo#315]
We recently upgraded from 1.4 to 1.7 and have now come across this issue. We have a screen set up which our catering staff access to update the menus daily. We had it set up as follows in 1.4:
*Catering Layout - Catering Users View and Edit permission
*Region Permissions - Catering Users View and Edit permission
*Media Permissions on Timeline - Catering Users View and Edit permissions

The Catering Users group had the following permissions:
Page Security: Content, Homepage and Login, Layouts, Users and Groups
Menu Security:
Dashboard - Layouts, Manual
Design - Layouts
Top Nav - Design

This allowed these users (in 1.4) to update just this single timeline item (A text media item) without editing any other parts of the design. However since upgrading to 1.7.1 when a user in this group tries to open the timeline for editing they are presented with this error:

"Application Message
You do not have permission to access this page."

I have turned on debugging and replicated this issue and have copied the contents of the data file below (as I am not allowed to upload it to this post!).

Jon

**Comment by dasgarner** [comment]
Try un-assigning the "Layouts" permission and reassigning it. That should "flush" the permissions through.

**Comment by jonwitts** [comment]
No joy... I unassigned and reassigned all three permissions, the layout, the region and the the timeline media with no change...

Jon

**Comment by dasgarner** [comment]
Sorry, I meant the permissions to the Layout **page** on the User Group.

**Comment by jonwitts** [comment]
That did the job; thanks Dan!
