### ISSUE TITLE
Global elements: disappear on publish (if not edited)

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3151]
OP: https://community.xibo.org.uk/t/dissapearing-global-elements-clean-install-cms-4-0-2-docker-windows-player-v4-r400/30023

**Comment by dasgarner** [comment]
The root cause is that on publish the `widgetId` in the element isn't updated to the new published widgetId

**Comment by rubenpingol-xibo** [comment]
✅ Tested
