### ISSUE TITLE
Widget: text flickers after upgrade (rich text)

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3157]
This is because we're applying an effect of "noTransition" when we used to be able to select "none". None doesn't appear in the list anymore either.

**Comment by dasgarner** [comment]
Testing: 
 * the "none" effect is available again ✅ 
 * paged/marquee effects will work ✅ 
 * speed isn't defaulted to something sensible anymore ❌ 


Regarding speed, I am not sure what we did previously, but it seems that the default value for speed must have changed somewhere as if you pick an effect without a speed it transitions very quickly.

**Comment by maurofmferrao** [comment]
I've create a new issue for next sprint(s) to set the default speed value based on the type of the effect
