### ISSUE TITLE
Shell command, How to make windows reboot command i Layouts

### ISSUE THREAD

**Issue by Jorgen67** [xibosignage/xibo#316]
Hi.
i am having problems finding out how to make shell commands in my layout

I need to send reboot command to my windows xibo client, both XP and Win 7.
I search for some hours but can only find answers on how to get Linux players reboot....

Wath exactly do i write in the windows command line?
![xibo shell command](https://cloud.githubusercontent.com/assets/11158623/6327270/617ea8da-bb5a-11e4-99f2-ed73b48450f1.jpg)

**Comment by Jorgen67** [comment]
Xibo server 1.7.1, Client 1.7.0

**Comment by alexharrington** [comment]
You'd need to get a command line that will restart the PC - something like

shutdown /r

Alex

**Comment by Jorgen67** [comment]
Hi Alex, i know the command, but my client don't do anything if i write shutdown /r /f in the windows command.

If i get on the client an write this command in "RUN" field, it works fine, but not via Layout.
I tried to put it in a layout, i tried to put it in a region in layout, but it won't work.
I opened the log file for the display/client and it says Shell command are disabled, but in settings/applications it is enabled
![shell command](https://cloud.githubusercontent.com/assets/11158623/6328065/859dbb58-bb63-11e4-9ee9-79ec5c7905dd.jpg)

**Comment by alexharrington** [comment]
You need to enable shell commands for the CLIENT (not the module) in Display Settings and whitelist the commands you want to run

**Comment by Jorgen67** [comment]
Nice.... That was it..


Thanks  ;)

**Comment by Jorgen67** [comment]
But.... Next problem, after reboot the player again reboot.... 

What do i do wrong here.... i read some place that the player execute the shell command once and then delete the shell command automatic...

**Comment by alexharrington** [comment]
It'll run the layout (and hence the command) all the time the layout is scheduled. So you need to make sure that the layout isn't set scheduled after you want it to start back up.

So for example, put your reboot command in a priority layout that's only scheduled to run for 1 minute (with the priority box ticked!). That way it'll run the command, cause a shutdown, then by the time the PC starts back up that layout won't be valid to be shown any longer and it won't show the layout (and hence run the command) again.

**Comment by Jorgen67** [comment]
Super

Thanks
