### ISSUE TITLE
Playlists: cannot scroll, the scroll bars are not displayed

### ISSUE THREAD

**Issue by robogito** [xibosignage/xibo#3161]
Xibo v.4.0.3 

Tested in Chome and Firefox. Message in console window displays:

`DataTables warning: table id=libraryItems - Requested unknown parameter 'thumbnail' for row 0, column 4. For more information about this error, please see http://datatables.net/tn/4`

**Comment by dasgarner** [comment]
Thank you for reporting this bug - please can you give us some more information as it isn't clear where you're seeing this problem. Thanks.

**Comment by robogito** [comment]
1. Navigate to Library->Playlists
2. Add more than 10 Playlists
3. If necessary, make the browser window smaller so that the scroll bars are visible

I have 30 playlists, if I set the number of display to 25, then the table goes down and no scroll bars are displayed.
I can't reach the entries below the visible one ...

**Comment by dasgarner** [comment]
Recreated, thank you!

**Comment by rubenpingol-xibo** [comment]
✅ Tested
