### ISSUE TITLE
Update Xibo to 1.7 without cloning database

### ISSUE THREAD

**Issue by sammoos80** [xibosignage/xibo#317]
Because of some Twitter problems I would like to upgrade our Xibo system from 1.6.4 to 1.7.1
 The problem is however that I do not have any rights to make new databases so it is also impossible for me to clone the Xibo database. The ICT department of our University created a database for me. I do have access to phpMyAdmin where I can make a backup of the database. According to the upgrading protocol I have to clone the existing Xibo database, which is not possible for me. However I cannot really see why I have to clone the database, I assume it is an extra safety feature.
 So my question is:
 Can I upgrade to 1.7.1 without cloning the database and only make a backup in case something goes wrong?
 Thanks!
 Sam

**Comment by dasgarner** [comment]
Yes - but you have to be confident that you can restore your backup should something go wrong.
