### ISSUE TITLE
Status Dashboard : SQL error when ordering by Faults column

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#3170]
When User attempts to order the Displays grid on Status Dashboard page by Faults column it throws SQL error - the ORDER BY clause is empty.

This is because in ajax data section for this table, we do
```
dataToSend.columns.pop();
```

Which makes sense on the Display page, as we do have buttons column as the last one there, however...we do not have buttons on that grid on the Status Dashboard, which makes is so the last column, that happens to be the `countFaults` column, is removed from the data we send to the backend. Which then makes SQL issues down the line - as the column name to order by comes up as an empty string.

This affects v4 as well, same issue, same fix.

**Comment by dasgarner** [comment]
✅ tested - I can order by the faults column
