### ISSUE TITLE
Calendar elements: Data not being formatted on preview

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#3172]
Event elements' data is being formatted in the editor viewer:
![image](https://github.com/xibosignage/xibo/assets/18596680/24c49453-b754-4d37-9729-5d20976c0dd4)

But not in preview:
![image](https://github.com/xibosignage/xibo/assets/18596680/9a62ad9a-42ba-46e8-a87c-4168cdf02db8)

**Comment by dasgarner** [comment]
This may be related (and resolved by) https://github.com/xibosignage/xibo/issues/3138

**Comment by maurofmferrao** [comment]
Tested! It works now ✅
