### ISSUE TITLE
Widget: DataSet Image Slideshow doesn't show DataSet Field when the dataset has no image columns

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3178]
This is confusing as it isn't clear what the user needs to do. A message should be displayed asking them to select a dataset with an image field.

**Comment by rubenpingol-xibo** [comment]
Tested by @maurofmferrao and this is already working.

**Comment by rubenpingol-xibo** [comment]
Apparently, it's working for elements but not for static widget.

**Comment by dasgarner** [comment]
✅ tested
