### ISSUE TITLE
Editor Viewer: Show empty regions

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#3179]
In some cases the editor might end up having a `frame` region without any `widget`, so it won't be visible on the viewer (it's rendered, but invisible).

We need to show those error regions on the viewer and [layer control](https://github.com/xibosignageltd/xibo-private/issues/526) so that they can be selected and deleted.

**Comment by dasgarner** [comment]
I can see the region in the viewer, but not in the layer control:

![Image](https://github.com/xibosignage/xibo/assets/10400067/f98870e5-23fb-4c16-8146-290dbb1cc73a)

I can't see a zone in the layer control either:

![Image](https://github.com/xibosignage/xibo/assets/10400067/03c3eb9f-9fc7-4922-bde2-0868921daabd)

**Comment by maurofmferrao** [comment]
They will be added to the layer control on this issue: https://github.com/xibosignageltd/xibo-private/issues/526

**Comment by dasgarner** [comment]
OK thanks, in that case this works ✅
