### ISSUE TITLE
Fonts dont work in Player

### ISSUE THREAD

**Issue by Carlos-Costa** [xibosignage/xibo#318]
XIBO 1.7.1 -  WINDOWS CLIENT
Hello, if you upload a Font that you dont have in Windows folder Fonts, the font you uploaded will not work in player client..

**Comment by dasgarner** [comment]
Have you followed instructions and clicked "Edit" and Save after uploading?

Does the font work in the CMS?

**Comment by Carlos-Costa** [comment]
Yes the font work in CMS.. The problem is in client player windows, if you dont have the font installed in windows the font dont work..

**Comment by dasgarner** [comment]
Maybe duplicate of #337
