### ISSUE TITLE
Folder search filter

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3183]
As the number of folders a user has access to grows, it becomes harder to find the right folder in the list. It would be useful to have a search filter for them to quickly narrow down the folders shown to the ones that match.

**Comment by Anthony-Quirante** [comment]
Design recommendations can be found **[here](https://www.figma.com/proto/RUoIeIfqgIWQbKjin5CHdw/Search-filter-sidebar-changes?type=design&node-id=1-2&t=mIMu8SDN04oe36BE-1&scaling=min-zoom&page-id=0%3A1&mode=design)**

Things to note:

- Search text field should use the same the outline and fill colors in the other text fields
- Change Home and Folder icon colors to blue #0E70F6
- Remove the dotted vertical and horizontal lines
- Change arrow / triangle icons to chevron (bootstrap icons can be found **[here](https://icons.getbootstrap.com/?q=chevron)**)

**Comment by Anthony-Quirante** [comment]
I just rechecked this and looks great. This is good to go from my end.
