### ISSUE TITLE
Elements: duplicate group doesn't work

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3190]
OP: https://community.xibo.org.uk/t/calendar-event-stencils-not-formatting-date/30193/6

Duplicating a single element works, but not a group of elements.

**Comment by ifarzana** [comment]
Tested :heavy_check_mark:

**Comment by sasch901** [comment]
Hey, duplicating a Group in 4.0.15 is not possible if you have two groups. https://community.xibo.org.uk/t/duplicate-calendar-groups-error/33743
