### ISSUE TITLE
Docker: automatic database backups not running v4

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#3194]
Since v4, no automatic daily backups are being created in `shared/backup/db` as they should be.

https://github.com/xibosignage/xibo-cms/blob/4.0.4/docker/entrypoint.sh#L235

Cause is this line - there is 1 `*` missing from the cron job definition preventing the job from running properly.

```
    echo "*/15 * * * * root /etc/periodic/15min/cms-db-backup > /dev/null 2>&1" > /etc/cron.d/cms_backup_cron
 ```

Amending to that and restarting the container fixes the issue.

**Comment by PeterMis** [comment]
Tested ✔️
