### ISSUE TITLE
Text flashes on-screen once and then disappears when a weather widget is also present

### ISSUE THREAD

**Issue by rubenpingol-xibo** [xibosignage/xibo#3195]

**Comment by kioskgypsy** [comment]
Hello, I was the person that reported this bug, I am already running a beta version of Android for another bug and this text bug is holding up my client demo/deployment. Any timeframe on the fix and release?

**Comment by dasgarner** [comment]
One half of the issue has been solved and committed into the `develop` branch/docker tag - text doesn't disappear anymore. The other half of the issue - text flashing - is being worked on now with a view to solving and committing into develop this week.

The 4.0.5 release will be on 14th Nov and include these fixes.

**Comment by kioskgypsy** [comment]
Thanks Dan, once fixed, is there anyway to get beta/fix release before that
date? I'm currently running one now for the Config not showing up on
loading.  Thanks!

Regards,

Edward J Crowley
URway Holdings, Consulting & Customer Experience Solutions
Sent Willingly from my Android Mobile, 512.657.3530

**Comment by dasgarner** [comment]
If you're using Docker then you can get the `develop` tag which contains those fixes (be sure to switch back post-release). If you're on Xibo cloud please open a ticket with our support team they will take a look to see if its patchable.

**Comment by kioskgypsy** [comment]
Thanks Dan, appreciate the support.

Regards,

Edward J. Crowley
URway Holdings
512.657.3530
***@***.***
https://www.pinterest.com/kioskgypsy/
https://www.linkedin.com/in/edwardjcrowley

Partner Links
https://armstrongalliancegroup.com/
https://www.conceptkiosk.com/


*"Consulting & Customer Engagement Solutions for Today's Connected Digital
World"*

**Comment by dasgarner** [comment]
✅ tested
