### ISSUE TITLE
Users permissions for Campaigns (v1.7.1)

### ISSUE THREAD

**Issue by JoeyGnarf** [xibosignage/xibo#320]
Hello,

On a clean install I added a new user, type user, initial user group Users. This user did not get access to the Design->Campaigns page. And somehow I cannot set (menu) security permissions to allow access to the Design->Campaigns page. I keep getting the error *"There has been an application error.You do not have permission to access this page."*

Is this intended design? Many thanks in advance!

Joey

**Comment by dasgarner** [comment]
It doesn't sound quite right! You (as an admin) should never receive the "you do not have permission" error.

For your user - unassigning and assigning the permissions to the "Layout" on the "User Group" page permissions should do the trick.

**Comment by debain** [comment]
I can confirm. The same for Template permission, it doesn't work - you do not have permission... (As a test: assigning DataSet permission to a user works)
I have the following problem which may have to do with this issue:
- it's not possible to assign users to a newly created group (Application Error: Error getting users). first i had to add a user and select the newly created group as the inital group

Unassigning and assigning didn't help.

**Comment by JoeyGnarf** [comment]
Thanks for the response. The problem is with the user only. Unassigning and assigning the rights for Menu Security -> Design Menu -> Campaigns for both the user as well as the user group did not help.

**Comment by dasgarner** [comment]
I mean "unassign" the Layout Page in Page Permissions for your user or user group. Then assign it again.

**Comment by debain** [comment]
Thanks, now it works!
On the user > page security nothing was assigned. I selected layout and template an now it is ok.
But i am sure i did this before - so something i changed elsewere had this effect i think - maybe creating/deleting users or groups

**Comment by dasgarner** [comment]
Deleting groups would have cleared the permissions and you would have had to re-enter - so perhaps that is it!
