### ISSUE TITLE
Display Profile : Some config settings not encoded correctly after v4 migrations

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#3202]
The main culprit seems to be the Player Software migration in v4, where we save the display profile config / display override config during the migration to adjust the `versionMediaId` - if there was one set.

When we save the config in the migration, it is possible that settings that may require json_encode, like on/off timers will not be encoded correctly.

**Comment by ifarzana** [comment]
:white_check_mark: tested
