### ISSUE TITLE
Layout : Full screen Layout created from Media/Playlist missing modifiedDt

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#3204]
In the process of creating a full screen Layout for Media/Playlist Schedule, we never look up the layout record in the database.
Unfortunately we also do not set modifiedDt on the object on save. 

The `xlfToDisk()` which saves the Layout last during this operation, saves it with `setModifiedDt` set to false, as such it attempts to use the modifiedDt from the Layout object - since it's not set it is null, which can potentially throw sql error preventing completion of this operation.

**Comment by dasgarner** [comment]
✅ tested
