### ISSUE TITLE
DataSet Column : Cannot save a Column with list content

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#3205]
When attempting to save a Column with list content, we try to validate it, by checking if the provided list matches existing values for that column.
Which in itself is likely correct, however we also pass `datasetcolumnid` parameter to the query and then we do not use it in the actual SQL statement, which makes mysql 8 sad and we get the following error: 
`SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens`

**Comment by ifarzana** [comment]
:white_check_mark: tested
