### ISSUE TITLE
Schedule Grid : Recurrence description incorrect for weekly repeats

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#3207]
Recreate : 
Set repeat weekly, every Monday
The description will say that it repeats on Sunday instead.

The root cause seems to be that array returned from `Carbon::getDays();` that we use to determine the day name starts with Sunday, while in our array `recurrenceRepeatsOn` first element is Monday .

We also do not seem to cover cases where more than one day is selected correctly.

**Comment by ifarzana** [comment]
:white_check_mark: tested
