### ISSUE TITLE
Add name for webpages and other items that don't have them..

### ISSUE THREAD

**Issue by mattdreher** [xibosignage/xibo#321]
Currently it is very difficult to manage the order of items.  Adding an optional name for the items like webpages would be very helpful.

![image](https://cloud.githubusercontent.com/assets/362301/6333782/8e81bf7a-bb55-11e4-9a14-564d23d4c0d7.png)

**Comment by alexharrington** [comment]
Please don't make this mandatory! Naming every text item (as it used to be required to do) was a total waste of time

**Comment by dasgarner** [comment]
Sure, will mimic the way it works on tickers, etc... optional name field that when empty defaults to the media type name.

**Comment by andyrogers2012** [comment]
Please see issue https://github.com/xibosignage/xibo/issues/178 where this has already been submitted as a Pull Request along with Text field Description. :)

**Comment by dasgarner** [comment]
Hi @andyrogers2012 - I hadn't forgotten about that (well not completely!) :smile: I just kept this tagged up to make a generic "pull the name if it exists" behaviour for where-ever the name is displayed.

**Comment by andyrogers2012** [comment]
Hi Dan, I think on the module side now this is covered on most if not all of them.  But if you can make something generic to fill the gaps that would make sense thanks.

**Comment by PeterMis** [comment]
You can give a name(optional) to any module, most of them have some generic names ie "clock" "twitter" but poor webpage module doesn't have any generic name at the moment.

**Comment by dasgarner** [comment]
Are you sure?
