### ISSUE TITLE
Widget: Shell Command broken when migrating from v3

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3217]
All commands come as freeText and seem to be broken.

v3 preview:

![image](https://github.com/xibosignage/xibo/assets/10400067/d88b10da-1d67-4bea-907d-8058b137302f)

v4 preview:

![image](https://github.com/xibosignage/xibo/assets/10400067/05fe84ec-3c13-45a1-864d-102263c27609)

**Comment by maurofmferrao** [comment]
Tested! ✅
