### ISSUE TITLE
Weather: Background image path wrong when migrating from v3 to v4

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3218]
The background image doesn't get displayed, and we see the following in the generated CSS for the widget HTML:

![image](https://github.com/xibosignage/xibo/assets/10400067/f3fc63ab-cf46-4ac1-9983-3ca8f3c0fd02)

**Comment by dasgarner** [comment]
I believe this is because the image attributes are set to themselves:

```
{
    "option": "night-clear-image",
    "type": "attrib",
    "value": "night-clear-image",
    "widgetId": 94
}
```

So when we come to do the substitution we get:

```
.bg-clear-night {
    background-image: url("{% if nightClearImage %}{{ nightClearImage }}{% else %}[[assetId=wi-night-clear]]{% endif %}");
}
```

Saving any part of the widget solves the issue because we do not save default values to their properties anymore.

**Comment by maurofmferrao** [comment]
Tested! ✅
