### ISSUE TITLE
Improve Rich Text module

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#3219]
## Improve widget:
  - [x] Add `stylesheet` field
  - [x] Add new checkbox options for advanced controls (JS+CSS).
    
## Improve rich text control:
Users find the editor to be more confusing than in v3. We need to make some changes to make it more user friendly.
- [x] Add view source option
- [x] Playlist Editor: Editor has some hard coded dimensions, maybe we need to bring back the target dimensions controls. 
- [x] When opening the editor, we need to calculate the default zoom to be either the playlist width or height.
- [x] Also, the detached editor looks a bit confusing by not being fullscreen and centred.
- [x] Fix the click twice to dismiss the detached editor bug.
- [x] Smart scale button ( width or height ) 
- [x] Zoom to width
- [x] Zoom to height

**Comment by PeterMis** [comment]
Tested ✔
