### ISSUE TITLE
RSS Ticker: Marquee inconsistent behaviour between versions

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#3222]
In v3, `Prominent title with description and name separator` template with marquee left shows Title and Description in the same line, whilst in v4 it scrolls with the intended design.

The problem is when we migrate from v3 to v4. In that case, we need to make sure that it renders the same way.

**Comment by dasgarner** [comment]
The v4 marquee effect is correct and it is unliked that anyone has used the marquee effect with this template (as it doesn't make sense).
