### ISSUE TITLE
Sample Data: When to show?

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#3224]
We're currently showing sample data even when a module is properly configured (e.g. Calendar widget with no events returned ).

Sample Data only makes sense to be shown when a module/widget is invalid.

**Comment by rubenpingol-xibo** [comment]
To be clear here, when the module is properly configured (e.g. Calendar widget), this means it has a valid **Feed URL**. And when there is no event from the provided **Feed URL**, there should be no items to be shown as well in the calendar. Is this correct?

We will only show **Sample Data** only when;

1) The module is not properly configured (e.g. Calendar widget with no **Feed URL** provided)
2) Provided with invalid **Feed URL** or the module is invalid
   _This can mean that the response from the backend for the widget data could be something like_

```
{
  success: false,
  error: 0,
  message: "The iCal provided is not valid, please choose a valid feed\n"
}
```

**Comment by maurofmferrao** [comment]
Yes, that's correct. We only want to show Sample Data when the widget is not configured ( `isValid` is false ). For calendar it makes sense to have it like this. Not sure about something like RSS if the feed is valid but returns no items, since the interface will not show anything, not sure if we need to mark isValid as false in that case @dasgarner ?

**Comment by rubenpingol-xibo** [comment]
Alright, thanks for confirming. How about for RSS when the feed is valid but no items, what should we display on the editor and on preview?

**Comment by dasgarner** [comment]
I've opened a discussion on this so we can work out what we want to do.

**Comment by maurofmferrao** [comment]
@rubenpingol-xibo I just found that Attribution for Weather is behaving in a different way than the other elements in the same widget



![Image](https://github.com/xibosignage/xibo/assets/18596680/ad7c1a46-4727-4835-826f-f81fd59c7566)

**Comment by dasgarner** [comment]
✅ tested
