### ISSUE TITLE
Widget: static templates should offer some customisation - changing colours, fonts, etc

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3226]
In v3 you could do that with the CSS override, which has been removed. We should therefore provide some customisation properties to do common things (colours, fonts, sizes, etc).

E.g. countdown, clock, data widget static templates, etc.

**Comment by ifarzana** [comment]
:white_check_mark: tested

**Comment by PeterMis** [comment]
✔️ Tested
