### ISSUE TITLE
Schedule: Agenda view time box appears over event form

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3227]
Seen on 4.0.4

Issue:
Go to the Agenda view. Open the Add event or edit event form. The timeline box will always appear on top of the form.

Example:
Set the timeline to 12:00, then open the add event form. You can see it on the form:

![4a7aea75b90a9adb1f53b9cf52bcc7072542ffb2_2_690x417](https://github.com/xibosignage/xibo/assets/3999746/f043cd87-fac0-4ac0-ae25-39cbe4864cc9)

**Comment by dasgarner** [comment]
✅ tested
