### ISSUE TITLE
Xibo Client (1.6.4) memory leak

### ISSUE THREAD

**Issue by df4gg55** [xibosignage/xibo#323]
It is found that the memory usage of Xibo Client (1.6.4)will be grown if network is disconnected. It will grow from 36MB to 1GB after running for 3 hours which causing out of memory.Is there anyone can help to study together,Thank you.

**Comment by dasgarner** [comment]
This is a known problem with the way logging functions and has been fixed in 1.7 series. We will release a patch to 1.6 series when we have time to do so.
