### ISSUE TITLE
Widget: elements using "pin data slot" no longer work

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3238]
These did work in 4.0.4, so this is a regression.

**Comment by rubenpingol-xibo** [comment]
The issue here is that the **pin data slot** stops working when there are multiple slots being pinned of the same type. It only pins the highest pinned slot and marks other pinned slots as empty

**Comment by seederp2p** [comment]
Is this present on weather elements? Example: temperature?

I tried to pin data slot but it shows the forecast for other days....

**Comment by sasch901** [comment]
> These did work in 4.0.4, so this is a regression.

Oh, i had it also in 4.0.4

**Comment by ifarzana** [comment]
:white_check_mark: tested
