### ISSUE TITLE
Automatically update datasets

### ISSUE THREAD

**Issue by danjimenezm** [xibosignage/xibo#324]
Hello, I would like to know if there is any way to setup a script to update or replace datasets on the Xibo CMS. 
Xibo is really nice but I need a way to automate this, so that I can show some tables and indicators on real time (or close to it).

Thanks in advance.

**Comment by MedusaDelft** [comment]
I suggest you use a ticker (rss feed)

**Comment by alexharrington** [comment]
Datasets can be updated via the API. You'd need to write an app to communicate via the API and upload your data that way.

http://xibo.org.uk/2014/02/19/scripting-xibo-content-management-a-brief-tour-of-the-api/
http://xibo.org.uk/manual/api_datasets.html
