### ISSUE TITLE
Layout Preview: Weather or dataset elements are not properly shown in preview

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3240]
In the layout preview, black screen is shown when weather or dataset elements are previewed.

However, if you preview multiple times, elements do appear.

**Comment by rubenpingol-xibo** [comment]
Hi @ifarzana, do you have the link to the layout where you encountered this?

**Comment by ifarzana** [comment]
https://develop.xibo.co.uk/layout/designer/2804

**Comment by ifarzana** [comment]
:white_check_mark: tested
