### ISSUE TITLE
Elements: Multiple widgets of the same type in canvas

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#3244]
When we add an element of a given data-type, we create a module of that data-type to provide data for that element. If we add a second element of that same data-type, it will use the same data configuration, either for paging or for different type ( username and description ).

We might want to add more than one module, so we need to give the user a way to decide to add the new element into a totally new module.

How it works:

 - Add the widget without any choice for the first element of one given type.
 - If we had another element of that type, we show a modal with a grid that lists the existing Widgets in Canvas, or to create a new one.
 - For already added Elements, we can have a drop down at the top of the Properties Panel to select another widget of the same type in Canvas.

**Comment by ifarzana** [comment]
Looks good to me.  :white_check_mark: tested
