### ISSUE TITLE
Layout Editor: first element added does not set layout duration

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3249]
Create a new layout, drag on an element which does not have a widget (global element or image). The layout duration updates to 0:01.

**Comment by dasgarner** [comment]
This is expected because the duration of the canvas widget is 1 second by default. The duration will update once a widget has been added, or if the user goes and sets a duration explicitly.

We can leave this open as there are some ongoing discussions about how duration should be handled.
