### ISSUE TITLE
Display management enhancement

### ISSUE THREAD

**Issue by Blacksnow91** [xibosignage/xibo#325]
Hi there! 

I'm a member of a student association in a French engineering school (EISTI), and we're using Xibo to provide the school and students a communication vector. But as we are planning to scale up from 3 to many displays , it will be a major problem to start clients. We're using for now the machines' bios. But those machines sometimes loose their configurations.

Do you think you could add the ability to send a WoL packet to every display when we want and having the possibility of scheduling it (every weekdays, Mondays, Tuesdays, and so forth)

Bests, 
Valentin FAMELART

**Comment by alexharrington** [comment]
Xibo already supports sending a Wake on Lan packet. You need to be running the maintenance.php script on a schedule (as recommended in the manual) and then select the option to send a wake on lan packet is the display options.
