### ISSUE TITLE
Elements: Multiple widgets v2

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#3257]
Relates to https://github.com/xibosignage/xibo/issues/3244

Multiple widgets needs to be simplified, since it's not really clear what it does right now.

The top element in the property panel will now only have the name of the widget, that will be generated using a new property for each XML module and template.

Adding elements/stencil for a module will always add to the last selected/edited configuration.

To create a new configuration, we will use the context menu in the viewer where we will have a new option for New configuration. That will then create a new widget, move the element to that widget and reload the property panel in a clear state.

**Comment by ifarzana** [comment]
✅ tested
