### ISSUE TITLE
Program Icons

### ISSUE THREAD

**Issue by mymactek** [xibosignage/xibo#326]
What program do you use to make the .ico file for the Visual basic project ?

You have 4, 8 and 32 bit in different sizes. Please let me know.
Thanks

**Comment by mymactek** [comment]
I edited the program files and such. and Keep getting the following error : 

Error	1	Invalid Resx file. Invalid length for a Base-64 char array or string. Line 738, position 5.	C:\Users\Ryan\Downloads\xibo-dotnetclient-develop\xibo-dotnetclient-develop\Forms\OptionForm.resx	738	5	

Only thing I can think of and see if the .ico file - i changed the file but dont have as many as originally in it.

Thanks for your help.

**Comment by dasgarner** [comment]
Just an on-line converter (there are many available)

You probably what to replace the ICO using the GUI rather than copying it straight into the resx
