### ISSUE TITLE
Layout Import: an image layout does not show the image

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3262]
1. Create a layout with only an image.
2. Publish and export the layout.
3. Import the layout into a different CMS.

Expected result: The image is displayed.
Actual result: The image is not displayed.

Note: The layout image is successfully imported into the CMS library, but we observed that the widget option table (elements) had a mediaId that was not updated with the current CMS mediaId.

**Comment by dasgarner** [comment]
✅ tested (by Israt)
