### ISSUE TITLE
Dashboards : Media Manager throws unexpected error for non super admin users

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#3263]
When we build the query to get all relevant media on that page, we do not pass `$params` to the sql select statement, which then throws sql error upon execution.

The params come from `viewPermissionSql()`, as such are not needed for super admin users. 
However when we do actually attempt to check the permissions for other user types, we need to have userId and relevant entities params in the query.

**Comment by dasgarner** [comment]
✅ tested
