### ISSUE TITLE
Newbie.  No data

### ISSUE THREAD

**Issue by acade** [xibosignage/xibo#327]
I have just downloaded and installed CMS and the client, but no data comes into the client.  I am sure that I am missing something extremely simple.  The displays registers in CMS and I am able to license it, but its status never changes, nor does the client get any files. Thanks for any help

This is what comes up in the log:

LibraryAgent|2/24/2015 2:35:04 PM|Error|LibraryAgent - Run|Exception in Run: Could not find file 'C:\Users\cadea\Documents\Xibo Library\requiredFiles.xml'.
ScheduleManagerThread|2/24/2015 2:35:04 PM|Error|ScheduleManager - LoadNewSchedule|Layout invalid: 0
UI Thread|2/24/2015 2:35:04 PM|Error|MainForm - ChangeToNextLayout|Layout Change to  failed. Exception raised was: Default layout
ScheduleAgentThread|2/24/2015 2:35:05 PM|Error|ScheduleAgent - Run|Exception in Run: Client found response content type of 'text/html; charset=UTF-8', but expected 'text/xml'.
The request failed with the error message:
--
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:xmds" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:ScheduleResponse><ScheduleXml xsi:type="xsd:string"><?xml version="1.0"?>
<schedule>
  <default file="5"/>
  <dependants>
    <file>jquery-1.11.1.min.js</file>
    <file>xibo-layout-scaler.js</file>
    <file>xibo-webpage-render.js</file>
    <file>moment.js</file>
    <file>jquery.marquee.min.js</file>
    <file>jquery-cycle-2.1.6.min.js</file>
    <file>xibo-text-render.js</file>
    <file>xibo-dataset-render.js</file>
    <file>flipclock.min.js</file>
  </dependants>
</schedule>
</ScheduleXml></ns1:ScheduleResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

--.
RequiredFilesAgentThread|2/24/2015 2:35:05 PM|Error|RequiredFilesAgent - Run|Exception in Run: Client found response content type of 'text/html; charset=UTF-8', but expected 'text/xml'.
The request failed with the error message:
--
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:xmds" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:RequiredFilesResponse><RequiredFilesXml xsi:type="xsd:string"><?xml version="1.0"?>
<files>
  <file type="media" id="9" size="95785" md5="3c9137d88a00b1ae0b41ff6a70571615" download="xmds" path="jquery-1.11.1.min.js"/>
  <file type="media" id="10" size="2466" md5="3659986d00e56c929218084aeb991cca" download="xmds" path="xibo-layout-scaler.js"/>
  <file type="media" id="11" size="4338" md5="8e9fe8361b485da58dc788389f88adfd" download="xmds" path="xibo-webpage-render.js"/>
  <file type="media" id="12" size="26051" md5="04cfd84078efafd4ca0928326885cfa1" download="xmds" path="moment.js"/>
  <file type="media" id="13" size="2248" md5="2286bb4f44d9ea301131a25c5204ca0a" download="xmds" path="jquery.marquee.min.js"/>
  <file type="media" id="14" size="28669" md5="4310a8127c98c2fc13d1f6597c338e6f" download="xmds" path="jquery-cycle-2.1.6.min.js"/>
  <file type="media" id="15" size="9086" md5="55991caa2c44b85d0604349da0f8c42b" download="xmds" path="xibo-text-render.js"/>
  <file type="media" id="16" size="1585" md5="ffcde6f93e4ac6cb6d4dddad45d344db" download="xmds" path="xibo-dataset-render.js"/>
  <file type="media" id="17" size="20242" md5="cd44dfb10cf85968f429871c1334ee78" download="xmds" path="flipclock.min.js"/>
  <file type="layout" id="5" size="2053" md5="7660f3ceabacdd9e50119290565241d1" download="xmds" path="5"/>
  <file type="resource" id="3244" layoutid="5" regionid="47ff29524ce1b" mediaid="522caef6e13cb6c9fe5fac15dde59ef7" updated="1424785317"/>
  <file type="resource" id="27311" layoutid="5" regionid="53654d56726e0" mediaid="11846d5d9f686fb75fc9dad0b19ca9de" updated="1424785317"/>
  <file type="blacklist"/>
</files>
</RequiredFilesXml></ns1:RequiredFilesResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

--.
RegisterAgentThread|2/24/2015 2:35:05 PM|Error|RegisterAgent - Run|Exception in Run: Client found response content type of 'text/html; charset=UTF-8', but expected 'text/xml'.
The request failed with the error message:
--
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="urn:xmds" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:RegisterDisplayResponse><ActivationMessage xsi:type="xsd:string"><?xml version="1.0"?>
<display status="0" code="READY" message="Display is active and ready to start." version_instructions=""><CollectInterval type="int">30</CollectInterval><PowerpointEnabled type="checkbox">1</PowerpointEnabled><StatsEnabled type="checkbox">1</StatsEnabled><SizeX type="double">0</SizeX><SizeY type="double">0</SizeY><OffsetX type="double">0</OffsetX><OffsetY type="double">0</OffsetY><ShowInTaskbar type="checkbox">1</ShowInTaskbar><ClientInfomationCtrlKey type="checkbox">0</ClientInfomationCtrlKey><ClientInformationKeyCode type="word">I</ClientInformationKeyCode><CursorStartPosition type="string">Bottom Right</CursorStartPosition><DoubleBuffering type="checkbox">1</DoubleBuffering><EmptyLayoutDuration type="int">10</EmptyLayoutDuration><EnableMouse type="checkbox">1</EnableMouse><EnableShellCommands type="checkbox">0</EnableShellCommands><ExpireModifiedLayouts type="checkbox">1</ExpireModifiedLayouts><LogLevel type="word">error</LogLevel><LogToDiskLocation type="string"/><MaxConcurrentDownloads type="int">2</MaxConcurrentDownloads><ShellCommandAllowList type="string"/><UseCefWebBrowser type="checkbox">0</UseCefWebBrowser><SendCurrentLayoutAsStatusUpdate type="checkbox">0</SendCurrentLayoutAsStatusUpdate><ScreenShotRequestInterval type="int">0</ScreenShotRequestInterval><DisplayName type="string">OITKNGGUEST01</DisplayName><ScreenShotRequested type="checkbox">0</ScreenShotRequested></display>
</ActivationMessage></ns1:RegisterDisplayResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

--.
ScheduleManagerThread|2/24/2015 2:35:14 PM|Error|ScheduleManager - LoadNewSchedule|Layout invalid: 0
UI Thread|2/24/2015 2:35:14 PM|Error|MainForm - ChangeToNextLayout|Layout Change to  failed. Exception raised was: Default layout
ScheduleManagerThread|2/24/2015 2:35:24 PM|Error|ScheduleManager - LoadNewSchedule|Layout invalid: 0
UI Thread|2/24/2015 2:35:24 PM|Error|MainForm - ChangeToNextLayout|Layout Change to  failed. Exception raised was: Default layout

**Comment by acade** [comment]
Looking through the client log, it says that it can't connect to the remote server, but I am able to connect my display to the CMS??

**Comment by dasgarner** [comment]
Your CMS is outputting this error message ahead of the XML:

```
Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
```

Which is causing the XML response to be malformed.

You need to put your CMS in Production mode so that errors are not output - or fix the problem with your PHP installation as described in the error message.

**Comment by genscherk** [comment]
Was there any resolution to this, I have the exact same problem.

**Comment by dasgarner** [comment]
As in the prior comment, this was an environment issue that should be solved by ensuring that your PHP installation does not output errors.

Please feel free to continue the discussion on the community site.

Please discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
