### ISSUE TITLE
Dataset with Library Images: not Displayed on First Attempt on players

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3272]
Steps to Reproduce: (on 4.0.6)

1. Create a layout with dataset having an image column, using string template with placeholders on a playlist
2. Publish layout
3. Verify that the images are now visible on preview

Expected Behavior:
Images should be displayed on the player at first attempt. 

Actual Behavior:
Images are not shown on the player the first time. after checking out and publishing again the images appear

Reference layout
(On Develop) ID: 1502 Layout ID (3092)

**Comment by dasgarner** [comment]
Library images are not correctly added to the `display_media` table by Widget Sync.
