### ISSUE TITLE
Clock Widget: Unable to upgrade digital clock from V3 to V4

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3275]
An issue arises during the upgrade process from V3 to V4, where a layout featuring a digital clock does not undergo the expected upgrade. Instead, the upgraded layout displays an analogue clock.

It looks like we return the first module which is clock -analogue rather than the clock-digital https://github.com/xibosignage/xibo-cms/blob/develop/lib/Factory/ModuleFactory.php#L358

**Comment by dasgarner** [comment]
Just a note that we fixed and tested this before, so there must be something more: https://github.com/xibosignage/xibo/issues/3109

**Comment by dasgarner** [comment]
Related issue regarding the analogue clock: https://github.com/xibosignage/xibo/issues/3314

**Comment by ifarzana** [comment]
:white_check_mark: tested
