### ISSUE TITLE
Click on editing the layout name more than once, it opens multiple ‘Modals’ with the name editing form

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3278]
OP: https://community.xibo.org.uk/t/v4-0-6-shedule-menu-bugs-layout-editor-bugs/30752

![image](https://github.com/xibosignage/xibo/assets/10400067/b700ef65-e943-45d4-8efc-0a135f93c308)

![image](https://github.com/xibosignage/xibo/assets/10400067/27066052-3276-4fab-97d4-7d326cf22cb9)

**Comment by ifarzana** [comment]
:white_check_mark: tested
