### ISSUE TITLE
All Launchpad Answers've Gone

### ISSUE THREAD

**Issue by precoggy** [xibosignage/xibo#328]
There was a lot of information on Launchpad answers why you deleted all?

You might say before delete. What we gonna do now? Because we are 1.4.2 users and there was everything about 1.4.2.

I will cry now. :)

Did u delete all? or can u bring them all?

**Comment by alexharrington** [comment]
Unfortunately in order to stop people posting new questions there we've had to disable Launchpad Answers. 1.4.2 is now two stable versions out of date and has a number of issues. You need to upgrade and keep current.
