### ISSUE TITLE
v3 weather widget edit form takes a long time to open

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3280]
OP: https://community.xibo.org.uk/t/layout-designer-weather-widget-slow-to-load/30635/7

It turns out we call `getBackgroundOptions()` on the module widget, which does an unpaged query on the library for weather background images.

**Comment by dasgarner** [comment]
This does not affect v4, where we use a select2 and query for initial value.

**Comment by ifarzana** [comment]
:white_check_mark: tested
