### ISSUE TITLE
Docker "latest" not updated

### ISSUE THREAD

**Issue by cschmidtoptima** [xibosignage/xibo#3283]
Hello,

the "latest" tagged xibo docker image is still on 4.0.5 and should also be updated to 4.0.6

Thank you

**Comment by dasgarner** [comment]
Thanks for reporting this - it looks like the automated build failed: https://github.com/xibosignage/xibo-cms/actions/runs/7180082043/attempts/1


I've re-run it: https://github.com/xibosignage/xibo-cms/actions/runs/7180082043
