### ISSUE TITLE
Twitter - Search Term - Tweet Only one User

### ISSUE THREAD

**Issue by vmesquita** [xibosignage/xibo#329]
Is it possible to search tweet only one user?
Example: Shows only tweet of @folha

**Comment by vmesquita** [comment]
Look in: https://twitter.com/search-advanced
https://twitter.com/search?q=from%3Afolha&src=typd

**Comment by dasgarner** [comment]
Yes - just use that as your search term

**Comment by vmesquita** [comment]
To search tweet only user @folha:
Search Term:  from:folha

Thanks!

**Comment by dasgarner** [comment]
If you fancy sharing tips and tricks, please feel free to do so here: [community.xibo.org.uk](http://community.xibo.org.uk)
