### ISSUE TITLE
Layout Editor: Undo button broken

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#3292]
Undo button isn't placed in a position where it's visible, and its functionality is broken.

**Comment by ifarzana** [comment]
### Test Case 1:

1. Add a Calendar (static widget)
2. Add Feed URL
3. Set `Number of Items` to 10
4. Set `Update Interval (mins)` to 60
(Widget is saved)
5. Click on `Undo`

Expected:  `Update Interval (mins)` goes back to empty
Actual: Seeing error `Revert Failed: Missing Required property Feed URL`


### Test Case 2:

1. Do **Step 1 to 4** of Test Case 1
2. Refresh the page
3. Set `Number of Items` to 5
(Widget is saved)
4. Set `Update Interval (mins)` to 120
(Widget is saved)
5. Click on `Undo`

Expected:  `Update Interval (mins)` goes back to 60
6. Click on `Undo` again
`Number of Items` to 10

Actual: `Update Interval (mins)` and `Number of Items` cannot be reverted

**Comment by ifarzana** [comment]
Looks good to me :+1: 

:white_check_mark: tested
