### ISSUE TITLE
SAML: add simple group assignments via SSO

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3297]
Configurable behaviour from inside `settings-custom.php`.

2 new settings:

 - group attribute name
 - group extraction regex

If the group attribute name is specified we check for groups in that attribute using the group extraction regex to pull out the group name.

Once we have a list of groups we compare the list we get to the group membership of that user in Xibo. We remove the user from any groups that are not in the response but exist in Xibo, and add them to any groups that exist in Xibo that are in the response. 

Groups which do not match a group in Xibo are ignored (no JIT).

Users who match no groups should be allocated the default group as if they logged in with JIT as a fresh user.

**Comment by southerngrampiansshirecouncil** [comment]
Hi @dasgarner this looks to be a great feature. Could you please provide a regex example? We are utilising EntraID for SAML, and have groups listed under "groups" attribute, however the matching does not seem to work fully.

Both Xibo and Entra have the same groups, eg: "Xibo - DPT1, Xibo - DPT2"

**Comment by southerngrampiansshirecouncil** [comment]
Hi @alexharrington a forum post has been added [https://community.xibo.org.uk/t/saml-sso-simple-group-assignments/31313](https://community.xibo.org.uk/t/saml-sso-simple-group-assignments/31313), however the request was more about adding a regex example in the comments to settings-custom.php

**Comment by dasgarner** [comment]
As discussed with @ifarzana, this has been tested by the OP and during development with a sample IdP.
