### ISSUE TITLE
Error on mysql database creation (xibo cms 1.7 rc1)

### ISSUE THREAD

**Issue by Megahulk** [xibosignage/xibo#33]
Hi,

I use the following setup:
- Windows 7 Pro 32 bit
- IIS 7
- PHP 5.3.9 (max execution time 300)
- MySQL 5.6

during Xibo 1.7-rc1 installation I get the following error:

An error occurred populating the database. Statement number: 89. Error Message = [SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'userChange' at row 26]

I deleted the database several times and retried the installation, the result is always the same.

I would be very thankful for any help,

Carsten

**Comment by dasgarner** [comment]
Hi,

Can you confirm whether this is a new fresh installation or a upgrade?

Thanks,
Dan

**Comment by Megahulk** [comment]
Hi,

it is a fresh installation.

Kind regards,

Carsten

**Comment by dasgarner** [comment]
I think I found the issue - can you download the data.sql file from the referenced commit and pop that in your install/master/ folder ?

**Comment by Megahulk** [comment]
The bug is fixed. Thank you :-)
