### ISSUE TITLE
Playlist Timeline: Owner filter showing empty in the dropdown list

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3302]
Tested on: Develop (4.0.6)

Issue:
Create a playlist and go to Timeline. now select any of the media options and click the Owner filter. No users are reported:

![777674310d8eb13faea9d5940447d40876e2e423](https://github.com/xibosignage/xibo/assets/3999746/506bbae4-9c4a-4f5d-ab35-06328a8baeeb)

Note:
This issue does not occur in the editor, only when adding media to a playlist on the Playlists page.

**Comment by dasgarner** [comment]
✅ tested
