### ISSUE TITLE
Font not working in CMS 

### ISSUE THREAD

**Issue by ianniow** [xibosignage/xibo#331]
Have uploaded a font saved, edit and save.
Font appears as a choice in the text editor.
Change the text to that font nothing appears to change. Select preview and the font works. Allocate this to a display and it is the same as the editor window, ie not the chosen font.
Sever is ubuntu and client is windows 7. Xibo version 1.7.1
Font is downloaded to the client in the data folder.
Any ideas

**Comment by mrweekender** [comment]
I also have this issue. Windows 7 client/ Ubuntu Server. I even tried installing the font on the W7 client but to no avail. The CIS window tells me the files were uploaded to the client?

**Comment by ianniow** [comment]
The same here I also checked in the xibo library folder and the font is there.

**Comment by JianjianHuang** [comment]
I tested font today, it works.
1 check the font name in your font file, save the correct font name in the library
2 when the font file was downloaded to your local, double click it and then install it.

**Comment by ianniow** [comment]
Thanks for the reply.
As far as I can see that is the case it is installed on the local machine but I think that the problem maybe the name when I added the font called dk_crayon_crumble I called it chalk in the media library. do i need to name the font the same as the ttf file that I am uploading

**Comment by JianjianHuang** [comment]
Not the file name, but the font name in the font file.

**Comment by dasgarner** [comment]
Might be related to #337

**Comment by ianniow** [comment]
It would appear that this is now working. @dasgarner tried your solution but did not appear to up load the file. Put the true, false back and tried @JianjianHuang suggestion so called the font exactly the same as the ttf file name and it now appears in the cms text editor and also on the local display

**Comment by ianniow** [comment]
I think I have spoken to soon I have copied the 1.7.1 files into the live folder and upgraded the live database. 
Added the font and it did not appear in the editor.
Came back an hour later it was there but could not use it.
went on another pc and could use it.
Came back to the original pc and could not use it.
Does not make sense

**Comment by ianniow** [comment]
I think that I have got to the bottom of this. Once you have added the font to the media you have to clear the cache before you go into a layout to use it. I could then successfully add the font to the text although it did not give me a real time wysiwyg on the same pc if I click preview layout all is fine. but not when scheduled. The font is downloaded into the library. I also installed it onto the local pc in the hope that it could display it. I have also had a play with removing the false true as per @dasgarner and this just confuses me especially as I got different result using Chrome or IE7 for editing.

**Comment by dasgarner** [comment]
There is a note in the documentation about clearing your cache - this is because the fonts.css file gets cached by the browser and therefore doesn't contain the changes until you clear cache.

The false > true flag switch in the other bug has nothing to do with the CMS side, but without that flag switch its pot luck whether that file gets downloaded to the CMS or not.

So I think you had 2 issues - cache on CMS side and not downloaded CSS file on player side.
