### ISSUE TITLE
Layout Editor: positioning of background image behind region is wrong

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3315]
When clicking on the region shown below, you'd expect the background to resize and be positioned behind:

<img width="1298" alt="image" src="https://github.com/xibosignage/xibo/assets/10400067/603131e1-827f-48eb-a41d-55028a69ddda">

Instead it looks like this:

<img width="1296" alt="image" src="https://github.com/xibosignage/xibo/assets/10400067/4fbef629-319a-4763-9547-c66a13099706">

I believe this might be related to a change made in the Image widget: https://github.com/xibosignage/xibo-cms/pull/2260/commits/138c270c8043ad7415837ccad30663fed6920501

If the designer window is smaller than the background image, it works:

<img width="1018" alt="image" src="https://github.com/xibosignage/xibo/assets/10400067/59a02cf4-0328-4369-bc64-72b18335571f">

**Comment by dasgarner** [comment]
@PeterMis I can't remember if the fix applied also effects v4, or whether this issue will be v3 only?

As for what we do - we probably ought to allow upsize in this case, but not in the case we applied the fix for 😄

**Comment by PeterMis** [comment]
@dasgarner It was added to the WidgetDownloader I believe, so it might need some condition for that there as well.

**Comment by ifarzana** [comment]
:white_check_mark: tested
