### ISSUE TITLE
Elements: positioned incorrectly after switching resolutions

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3330]
If you create a layout with one resolution, place elements, etc, and then change resolution, the elements look OK in the editor, but not in the player/preview.

**Comment by dasgarner** [comment]
The first part of this issue has been resolved - the canvas region and layout orientation are changed along with the layout dimensions.

However, we still have elements positioned at the original dimensions and they are not moveable in the editor. @maurofmferrao do you think there is anything we can do about this?



![Image](https://github.com/xibosignage/xibo/assets/10400067/8e2ab932-6d85-4b10-acb2-562afb7fe295)

**Comment by maurofmferrao** [comment]
> However, we still have elements positioned at the original dimensions and they are not moveable in the editor. @maurofmferrao do you think there is anything we can do about this?

We're planning to add keyboard controls to move element in the Editor for a future release, that could help, but I think we can have a dedicated button in the Position tab ( under the "Make this fullscreen..." button ) that would appear when an object was outside of the Layout view, that would bring back to view?

**Comment by ifarzana** [comment]
:white_check_mark: tested

**Comment by dasgarner** [comment]
Reopening to test the layout view button.

**Comment by ifarzana** [comment]
:white_check_mark: retested
