### ISSUE TITLE
Layout Preview: Media and Youtube Embed play at the same time when in a playlist

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3333]
ID 1636
The layout contains a playlist widget, which has a video, followed by an embed widget, which contains a Youtube video script.

Issue:
If you preview the mentioned layout with the sound on, you can hear that the sound for the embed is playing from the beginning, even though it should start after the video has ended.

Note: I tested this on my XfW player (R402), XfA (R403) and XfT (R402 pre-release) and I could not see the issue occurring. It appears to be a layout preview issue only.

**Comment by dasgarner** [comment]
✅ tested
