### ISSUE TITLE
Layout Editor: Paste on code input doesn't trigger save

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#3338]
When pasting some code ( HTML+CSS+JS ) into the form code inputs, the form doesn't save automatically and so the widget doesn't reload on the viewer to show those changes.

How to replicate:
 - Add embedded widget
 - Paste some HTML code in the HTML input
 - Check that the widget in the viewer doesn't reload
 
 NOTE: If we unselect the widget, the form will save and reload the widget since we have pending changes to save

**Comment by ifarzana** [comment]
:white_check_mark: tested
