### ISSUE TITLE
'Unknown Color' Error with Transparent Background

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3341]
ID 1916 (dev)

![image](https://github.com/xibosignage/xibo/assets/3999746/180dd529-182e-49f6-9ee8-738e1f2f9531)

### Issue
When you add transparency to the layout background color, the Android player fails to show it and generates the `Unknown color` error in the logs.

* Note that, adding transparent color to element do not cause any issue.

![image](https://github.com/xibosignage/xibo/assets/3999746/488ce6e3-fb28-4f0c-aff6-193c03a0ddf5)

**Comment by maurofmferrao** [comment]
We need to remove transparency for the Layout Background colour.
