### ISSUE TITLE
xfA V3 Player: shows items more frequently than desired

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3343]
ID 1921 (dev)

### Issue

The V3 player does not maintain the duration per item. It displays the items faster than the desired seconds. For example, the layout should have shown three pages (with 3 slots) for at least 5 seconds, but it shows them for approximately 2 seconds. 

Note that, the duration of the layout(15s) is maintained.

Steps to recreate:
1. Add a RSS Ticker element (i.e., Title) with url - `https://www.wired.com/feed/category/business/latest/rss`
2. Set Number of Items to 8 and 
3. Check `duration is per item`
4. Set duration to 5 seconds

**Comment by dasgarner** [comment]
It doesn't work because in `decorateElement` `renderData` is null

I think that happens because on a v3 widget the URL is null, because data is already provided
