### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by serifcakir** [xibosignage/xibo#335]
Hi,

The problem comes when it loops. When the series to start if it becomes
black screen for about 1 sec and then starts running again.

Anyone have a solution or have the same problem?

**Comment by dasgarner** [comment]
Its not a problem - its just the way it works (the layout is reloading)

**Comment by serifcakir** [comment]
But every minute?

**Comment by dasgarner** [comment]
If your layout loops every minute, what else could it do?
