### ISSUE TITLE
cron and tasks not working

### ISSUE THREAD

**Issue by UnitronGroup** [xibosignage/xibo#3351]
all docker versions 4.x.x
cron in cms container not working therefore tasks not working.

In an unprivileged container, /etc/pam.d/cron needs to have pam_loginuid.so set to optional in order for cron to work. 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=762157

suggested workaround from there, add the following to the Dockerfile:
`RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/cron`

**Comment by alexharrington** [comment]
Thanks for taking the time to report this.

I tested our 4.0.7 release container here and cron seems to be working as expected - tasks are being run and backups taken.

Perhaps there's another reason for your issue? The most common issue we see where tasks aren't running is because the `MYSQL_PASSWORD` chosen has special characters which are problematic when passed by environment variable. It would be worth checking you've not done that.

**Comment by UnitronGroup** [comment]
checked MYSQL_PASSWORD and has no special characters, actually is the same like in a working 3.3.9 version.
what I did:
-loging in the container
-removed all the cron jobs from /etc/cron.d and added only a simple job(no . or - in name)
-started cron with -L 5 option and nothing, no logs also.
-installed rsyslog on container
-now I could see the error from the debian bug 762157 running cron `Cannot make/remove an entry for the specified session`
-changed the pam_loginuid.so from required to optional in the /etc/pam.d/cron configuration and everything started working.

more users have this problem I think
https://community.xibo.org.uk/t/cms-tasks-not-being-run/30374

regards

**Comment by UnitronGroup** [comment]
ok, added --cap-add AUDIT_CONTROL to docker-compose.yml and is working for me also.

**Comment by alexharrington** [comment]
What's the host OS that you're running on please?

**Comment by UnitronGroup** [comment]
Alma linux 9 and podman version 4.6.1 with podman-compose version 1.0.6.
just tested and if I start podman-compose through systemd service is also working without modifications.
problem solved.
