### ISSUE TITLE
Setting a layout background color shows error on Android Player

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3366]
ID: 1966

### Steps to recreate:

- Create a layout
- Change the layout background to rgb(255,0,0)
- Publish and schedule on a player

### Expected
- rgb(255,0,0) or red is the layout background

### Actual
- The layout background color remains black
- Player Status Shows `Unknown Color` Message

**Comment by dasgarner** [comment]
The android player only accepts HEX colour codes for the layout background colour (I believe windows is the same).

I think it is correct to show an error in this case, would you agree?

**Comment by dasgarner** [comment]
@ifarzana just waiting on your comment for the above to see if we can close this out as unplanned.

**Comment by ifarzana** [comment]
Yes, this can be closed as unplanned. Thanks
