### ISSUE TITLE
 Stock: Static Template - duration per item considering individual duration rather than pages

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3368]
ID: 1835

Stock static template 2 with duration per item is applied to the item rather than the page.

Steps to reproduce:
-  Create a layout with Stock Static Template 2
-  Set 8 Stock symbols
-  Check Duration is per item
-  Set Items Per Page as 3
-  Set duration as 5 seconds

Expected:
Each page should be displayed for 5 seconds
Total layout duration should be 15seconds (for 8 items in three pages)

Actual:
Total layout duration shows 40 seconds

**Comment by maurofmferrao** [comment]
The problem in this case is that the template doesn't have a `numItems` defined, so the back-end doesn't calculate the duration for Duration Per Item. In the front-end animation, that case would change pages each 5s but still play for 40s.
