### ISSUE TITLE
World Clock: Background color not displaying on Windows Player

### ISSUE THREAD

**Issue by gracec20** [xibosignage/xibo#3369]
**ID:** 1982

**Player:** Windows 4 R402.1

### Steps to recreate:

1. Create a layout
2. Add "World Clock - Text" or "World Clock - Time and Date" widget
3. Configure the background color of the widget to be different than the layout background
4. Publish and schedule on Windows player

### Expected

- The background color set for the World Clock widget should be displayed consistently across all platforms, including the Windows Player.
- Layout Design: <img width="950" alt="widget-bg" src="https://github.com/xibosignage/xibo/assets/162089615/a0c35bef-5ac0-43ce-ba4f-2661a3896bc8">

### Actual

- The World Clock widget's background color is not showing up on a Windows Player
- However, the background color is displayed correctly on an Android Player <img width="932" alt="widget-bg-actual" src="https://github.com/xibosignage/xibo/assets/162089615/346ea254-81bd-4068-a16d-4e3880319a6b">

**Comment by dasgarner** [comment]
This bug also effects other widgets.
