### ISSUE TITLE
fonts.css not added as system file in media table

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#337]
#211 - comments towards the end about fonts.css

**Comment by dasgarner** [comment]
L150

Should be:

$media->addModuleFile('modules/preview/fonts.css', 0);
Although I am a bit confused how this ever worked.

**Comment by veshant** [comment]
Hi @dasgarner,
I tried changing line 150 of the font module.  However it didn't work.

**Comment by dasgarner** [comment]
Interesting - can you have a look in your media table for `fonts.css` and see if it has the `modulesystemfile` column with a 1 in it?

Maybe if it is added once incorrectly, it is not updating it.

I will look further.

**Comment by veshant** [comment]
@dasgarner where can I find the media table?

**Comment by dasgarner** [comment]
@veshant - as a first step can you try the latest patch I supplied? I think I have covered all possibilities now.

**Comment by veshant** [comment]
Hi @dasgarner,
Everything seems to be fine now.  Thanks a lot for the help!

**Comment by dasgarner** [comment]
Great, thanks for the feedback.
