### ISSUE TITLE
Date format in ticker not displaying in regional default language format

### ISSUE THREAD

**Issue by MedusaDelft** [xibosignage/xibo#338]
When i set the default language in the regional tab (administration - settings - regional) to 'nl_NL' and set the date format field in a ticker (edit ticker - advanced) to 'D d M', it still displays in english.

@dasgarner I suppose it needs the same fix as the date format in ForecastIO.

**Comment by dasgarner** [comment]
Yes, I would imagine the same fix will need to be applied.
