### ISSUE TITLE
Formatting a RSS Feed not possible

### ISSUE THREAD

**Issue by debain** [xibosignage/xibo#339]
As a test: change the font-size in Feed-Template on a Feed (wich has a div tags inside the description - useful for formatting with CSS). It won't resize font...

The problem is that inserting a DIV into a paragraph results in a seperation of both.
See: http://stackoverflow.com/questions/10921418/div-automatically-added-in-item-get-description-using-simplepie

FIX: replace all p elements with div elements in the Feed-Template.

**Comment by MedusaDelft** [comment]
Which versoin of Xibo do you use?
On windows (and I think it is a CK-conf-setting) CKeditor uses a p-tag as default (as do the templates for the ticker!) instead of a div-tag. When I try to change a font-size, a seperate span-tag is created within the default p-tag.
So in my case, your fix creates an error.

**Comment by debain** [comment]
Yes you are right. i didn't test that in the wysiwyg. i changed it in the source code and in the template json file. Then this should be changed in the ckeditor too.

**Comment by dasgarner** [comment]
We aren't going to change all P tags to DIV tags - that would cause untold repercussions...

DIV tags inside the item description violates the RSS specification.

I don't think it is unreasonable to require users to enter their own HTML and formatting when they are using item descriptions with HTML in them and/or the Content tag.

**Comment by debain** [comment]
I don't agree.  In feed validator from w3c:
This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations. (description should not contain data-title attribute)

If you are right, there should be a validation and correction of feeds - Lot of feeds are not working (working in simplepie). Strip tags removes the text completly - so thats not an option.
All drupal and wordpress feeds i tested are not working! It should really be possible to integrate them.

**Comment by debain** [comment]
The following settings are working:

	config.enterMode = CKEDITOR.ENTER_BR;
	config.fillEmptyBlocks = false;
	config.forceEnterMode = true;
	config.ignoreEmptyParagraph = true;

i am going to test.
Note: It is recommended to use the CKEDITOR.ENTER_P setting because of its semantic value and correctness. The editor is optimized for this setting.
http://docs.cksource.com/ckeditor_api/symbols/CKEDITOR.config.html#.enterMode

**Comment by debain** [comment]
As far as i have tested it is working. For advanced users - it is now also possible to allow the class attribute and then customize the content of the feed via CSS (image size, link color, etc).
I have created a new template json file with DIV instead of P. (let the old one as they are)
For the CKEDITOR settings: it would be better to have template specific settings or the possibility to overwrite...
Here is a layout if somebody want to test this. It contains example for standard drupal feed (with divs - formatted with CSS) and a webpage with links to lot of drupal sites:
http://s000.tinyupload.com/index.php?file_id=50744128196267318232

**Comment by dasgarner** [comment]
I don't advocate or recommend changing the CKEDITOR config file to move away from P tags. The config we have has been thoroughly tested and it would be a shame to jump to BR instead of P for no good reason.

Supporting HTML content inside the feed means that the CMS no longer has control over how the feed is aligned when applying an effect to it. It is also very confusing when designing your template, because you can never know how it will look until the content has been substituted - you also can't guarantee your content will stay in the same format (unless you own the feed)

Having a template included which is designed to be used `raw` makes sense, giving people the opportunity to supply their own HTML/CSS if their feed contains HTML - this would be an "advanced use" without ticking override.

**Comment by debain** [comment]
Ok, i understand that. It is all ok for me.
What's no ok and in my opinion a bug: if a user adds a feed and is unable to format it. See this example: http://s000.tinyupload.com/index.php?file_id=79891255004703675857 font size in description isn't correctly displayed (because DOM structure isn't the same in preview/design and the ckeditor. so in your solution the CMS don't have control for formatting the description inside the wysiwyg editor!)
Again, if i am not doing something wrong, strip tags isn't an option, because it removes the description completely. there should be the option "html to plaintext"...

**Comment by dasgarner** [comment]
Sorry, but I don't follow.

If the feed description contains HTML, then I don't see how the user can ever expect to format it inside the editor - at this point the editor becomes useless and may as well just be a plain text box for HTML editing.

I thought strip tags would just strip the tags and not the content between them - seems pretty dumb for it to strip the entire lot.

**Comment by debain** [comment]
yes, only over CSS (field below ckedior) if you know the class inside the item of the feed (see first example i uploaded, there i format feeds link pink and the image size....) - that's why i wrote for advanced users, you don't see that in the ckeditor, only in preview... but that's no so important, i can made a template for me... forget about that

The bigger problem and the bug im talking about is in the second layout i uploaded.
you can see i tried to set the font-size of the description - but it is not working. or does it work for you? what if you import the layout? how big is the font-size of description in the design/preview/android-cient?

**Comment by debain** [comment]
Here is the wrong html:

	<div class="item cycle-slide cycle-slide-active" style="width: 1920px; height: 1080px; position: absolute; top: 0px; left: 0px; z-index: 99; opacity: 1; display: block; visibility: visible;"><div class="image">
	<div class="cycle-overlay">
	<p style="font-family: Arial, Verdana, sans-serif; font-size:52px; color:yellow; margin-top:300px;">Peugeot 208 1.6 BlueHDI - most economical cars</p>

	<p style="font-family: Arial, Verdana, sans-serif; font-size:148px; margin-top:25px;"><span style="font-size:168px;"></span></p><div>
		  <a href="http://www.autoexpress.co.uk/peugeot/208/90608/peugeot-208-16-bluehdi-most-economical-cars"><img title="Peugeot 208 2015 facelift front orange" alt="Peugeot 208 2015 facelift front orange" src="http://cdn2.autoexpress.co.uk/sites/autoexpressuk/files/styles/thumbnail_large/public/1/24/16463261652036296637_0.jpg?itok=XrWhKafl" typeof="foaf:Image"></a>  </div>
	<span>
		  <span><a datatype="" property="rdfs:label skos:prefLabel" typeof="skos:Concept" href="http://www.autoexpress.co.uk/car-group-tests">Car group tests</a></span>
	  </span><span>
		  <span><span content="2015-02-26T10:07:00+00:00" datatype="xsd:dateTime" property="dc:date">26 Feb, 2015</span></span>
	  </span><p></p>
	</div>
	</div>
	</div>

As you can see, the description is outside the P tag and therefore font-size is not applied.

**Comment by debain** [comment]
To be clear: The raw template could also fix this, but the better way would be to have a "plaintext" option . For me it is not a problem, but for a normal user.

**Comment by debain** [comment]
For Information: simplepie does not use strip_tags() PHP function :) See Sanitize.php from simplepie.
As a test: replace 989 in ticker module with:
    $replace = strip_tags($item->get_description(), "<img><a>");
That is working as expected: all IMG and A tags are there and the font-size is correct!

**Comment by dasgarner** [comment]
I think I see what you are saying - but my point is that if the description element of the RSS feed contains HTML content, then I don't see how we can expect the FORMAT applied in the CKEDITOR to have any effect.

The formatting provided in the CKEditor is only for text content - you have a workaround for one permutation of HTML in the content, but there are unlimited combinations as it depends on the feed....

That is what I don't understand! Perhaps I am being stupid :smile:

**Comment by debain** [comment]
I am sure you are not :) sorry and I don't speak english very...
In ticker module you are using strip_htmltags() from simplepie. See http://phpcrossref.com/xref/simplepie/library/SimplePie/Sanitize.php.html . For me this function is not working correctly (or i don't understand how it works - for me it removes the decription completly). You wrote:
"I thought strip tags would just strip the tags and not the content between them"
Thats what i am talking about - and i am sure it works with the normal php strip_tags function or with sometthing like htmlpurifier see this: http://stackoverflow.com/questions/12362426/strip-tags-disallow-some-tags

Thanks for your help and please close this issue now - if you are not interested a solution working with every feed. i am going to implement this for me and write my own ticker module.

**Comment by debain** [comment]
Here is the first version. please have a look or test and please tell me if it is possible to integrate this (or the reason why not/the problems). Again, otherwise it is possible to maintain my own module or feed-filter if this is not an option - no problem for me.
(Install htmlpurifier to 3rdparty/htmlpurifier and apply the following patch to the ticker module)

	--- ticker.module.php_old       2015-03-03 19:33:16.848447899 +0100
	+++ ticker.module.php   2015-03-03 19:35:24.505365375 +0100
	@@ -885,12 +885,6 @@
				 $feed->strip_attributes($attrsStrip);
			 }
	 
	-        // Get a list of tags to strip
	-        if ($this->GetOption('stripTags') != '') {
	-            $tagsStrip = array_merge($feed->strip_htmltags, explode(',', $this->GetOption('stripTags')));
	-            $feed->strip_htmltags($tagsStrip);
	-        }
	-
			 // Init
			 $feed->init();
	 
	@@ -1013,6 +1007,15 @@
								 break;
						 }
					 }
	+
	+                               if ($this->GetOption('stripTags') != '') {
	+                                       require_once '3rdparty/htmlpurifier/library/HTMLPurifier.auto.php';
	+
	+                                       $config = HTMLPurifier_Config::createDefault();
	+                                       $config->set('HTML.ForbiddenElements', array_merge($feed->strip_htmltags, explode(',', $this->GetOption('stripTags'))));
	+                                       $purifier = new HTMLPurifier($config);
	+                                       $replace = $purifier->purify($replace);
	+                               }
	 
					 // Substitute the replacement we have found (it might be '')
					 $rowString = str_replace($sub, $replace, $rowString);

**Comment by debain** [comment]
Sorry, we don't need this patch. The problem is, that it is not possible to set "Allowable Attributes" to "style" and "Strip Tags" to "div,p"...
If i don't set "Allowable Attributes" everything is working !
Maybe there should be a note on the advanced settings tab... I will make some test, maybe that is the solution.

**Comment by dasgarner** [comment]
I think that patch is OK - basically taking the "strip tags" function from SimplePie and adding a more advanced HTMLPurifier library to remove the tags only.

I am happy with that - if you can submit a "pull" request and also sign the CLA then I will include the change.
