### ISSUE TITLE
schedule.xml file truncated

### ISSUE THREAD

**Issue by xibo-de** [xibosignage/xibo#340]
Xibo Client 1.7.0 / Windows XP
Xibo Server 1.7.1

Layout "50-JPGs" with 50 JPGs

In schedule.xml are only 42 + 1/2 entries.
![schedule xml-1](https://cloud.githubusercontent.com/assets/10655684/6387439/86b042fc-bd8b-11e4-8b3a-4fb7cf9f644c.jpg)
![schedule xml-2](https://cloud.githubusercontent.com/assets/10655684/6387443/8f39a594-bd8b-11e4-941d-4ff28610c739.jpg)

**Comment by dasgarner** [comment]
Can you add a log message in xmdssoap4.class.php to see where they are being truncated?

anywhere around line 684 - Debug::Error($dependents);

**Comment by xibo-de** [comment]
"2015-02-26 11:34:15","Client","[ScheduleManagerThread] ScheduleManager - Run","Schedule Timer Ticked"
"2015-02-26 11:34:15","Client","[UI Thread] Media - SignalElapsedEvent","Media Complete"
"2015-02-26 11:34:15","Client","[UI Thread] Region - DurationElapsedEvent","Media Elapsed: 165.jpg"
"2015-02-26 11:34:15","Client","[UI Thread] Region - SetNextMediaNode","New media detected image"
"2015-02-26 11:34:15","Client","[UI Thread] Region - CreateNextMediaNode","Creating new media: image, 167"
"2015-02-26 11:34:15","Client","[UI Thread] Region - StartMedia","Starting media"
"2015-02-26 11:34:15","Client","[UI Thread] Region - Stop Media","Stopping media"
"2015-02-26 11:34:15","Client","[ScheduleManagerThread] ScheduleManager - Run","Schedule Timer Ticked"
"2015-02-26 11:34:15","Client","[UI Thread] Media - SignalElapsedEvent","Media Complete"
"2015-02-26 11:34:15","Client","[UI Thread] Region - DurationElapsedEvent","Media Elapsed: 165.jpg"
"2015-02-26 11:34:15","Client","[UI Thread] Region - SetNextMediaNode","New media detected image"
"2015-02-26 11:34:15","Client","[UI Thread] Region - CreateNextMediaNode","Creating new media: image, 167"
"2015-02-26 11:34:15","Client","[UI Thread] Region - StartMedia","Starting media"
"2015-02-26 11:34:15","Client","[UI Thread] Region - Stop Media","Stopping media"
"2015-02-26 11:34:15","Client","[ScheduleManagerThread] ScheduleManager - Run","Schedule Timer Ticked"
"2015-02-26 11:34:15","Client","[UI Thread] Media - SignalElapsedEvent","Media Complete"
"2015-02-26 11:34:15","Client","[UI Thread] Region - DurationElapsedEvent","Media Elapsed: 165.jpg"
"2015-02-26 11:34:15","Client","[UI Thread] Region - SetNextMediaNode","New media detected image"
"2015-02-26 11:34:15","Client","[UI Thread] Region - CreateNextMediaNode","Creating new media: image, 167"
"2015-02-26 11:34:15","Client","[UI Thread] Region - StartMedia","Starting media"
"2015-02-26 11:34:15","Client","[UI Thread] Region - Stop Media","Stopping media"
"2015-02-26 11:34:15","TranslationEngine","InitLocale","Resolved language DE not available."
"2015-02-26 11:34:15","Display","Touch","IN"
"2015-02-26 11:34:15","XMDSSoap4","Schedule","159.jpg,160.jpg,164.jpg,161.jpg,163.jpg,162.jpg,166.jpg,165.jpg,167.jpg,169.jpg,168.jpg,173.jpg,172.jpg,170.jpg,171.jpg,174.jpg,175.jpg,176.jpg,178.jpg,198.jpg,177.jpg,186.jpg,188.jpg,183.jpg,179.jpg,187.jpg,207.jpg,185.jpg,180.jpg,181.jpg,184.jpg,182.jpg,194.jpg,191.jpg,189.jpg,192.jpg,190.jpg,197.jpg,193.jpg,195.jpg,196.jpg,199.jpg,203.j"
"2015-02-26 11:34:05","Client","[ScheduleManagerThread] ScheduleManager - Run","Schedule Timer Ticked"
"2015-02-26 11:34:05","Client","[UI Thread] Media - SignalElapsedEvent","Media Complete"
"2015-02-26 11:34:05","Client","[UI Thread] Region - DurationElapsedEvent","Media Elapsed: 166.jpg"
"2015-02-26 11:34:05","Client","[UI Thread] Region - SetNextMediaNode","New media detected image"
"2015-02-26 11:34:05","Client","[UI Thread] Region - CreateNextMediaNode","Creating new media: image, 165"
"2015-02-26 11:34:05","Client","[UI Thread] Region - StartMedia","Starting media"
"2015-02-26 11:34:05","Client","[UI Thread] Region - Stop Media","Stopping media"
"2015-02-26 11:34:05","Client","[ScheduleManagerThread] ScheduleManager - Run","Schedule Timer Ticked"
"2015-02-26 11:34:05","Client","[UI Thread] Media - SignalElapsedEvent","Media Complete"
"2015-02-26 11:34:05","Client","[UI Thread] Region - DurationElapsedEvent","Media Elapsed: 166.jpg"
"2015-02-26 11:34:05","Client","[UI Thread] Region - SetNextMediaNode","New media detected image"
"2015-02-26 11:34:05","Client","[UI Thread] Region - CreateNextMediaNode","Creating new media: image, 165"
"2015-02-26 11:34:05","Client","[UI Thread] Region - StartMedia","Starting media"
"2015-02-26 11:34:05","Client","[UI Thread] Region - Stop Media","Stopping media"
"2015-02-26 11:34:05","Client","[ScheduleManagerThread] ScheduleManager - Run","Schedule Timer Ticked"
"2015-02-26 11:34:05","Client","[UI Thread] Media - SignalElapsedEvent","Media Complete"
"2015-02-26 11:34:05","Client","[UI Thread] Region - DurationElapsedEvent","Media Elapsed: 166.jpg"
"2015-02-26 11:34:05","Client","[UI Thread] Region - SetNextMediaNode","New media detected image"
"2015-02-26 11:34:05","Client","[UI Thread] Region - CreateNextMediaNode","Creating new media: image, 165"
"2015-02-26 11:34:05","Client","[UI Thread] Region - StartMedia","Starting media"
"2015-02-26 11:34:05","Client","[UI Thread] Region - Stop Media","Stopping media"
"2015-02-26 11:34:02","Client","[ScheduleAgentThread] ScheduleAgent - Run","Thread Woken and Lock Obtained"
"2015-02-26 11:34:02","Client","[RegisterAgentThread] RegisterAgent - Run","Thread Woken and Lock Obtained"
"2015-02-26 11:34:02","Client","[ScheduleAgentThread] ScheduleManager - GetSchedul","Getting the Schedule XML"
"2015-02-26 11:34:02","Client","[RegisterAgentThread] RegisterAgent - Run","Thread Woken and Lock Obtained"
"2015-02-26 11:34:02","Client","[ScheduleAgentThread] ScheduleManager - GetSchedul","Getting the Schedule XML"
"2015-02-26 11:34:02","Client","[RegisterAgentThread] RegisterAgent - Run","Thread Woken and Lock Obtained"
"2015-02-26 11:34:02","Client","[ScheduleAgentThread] ScheduleManager - GetSchedul","Getting the Schedule XML"
"2015-02-26 11:34:02","TranslationEngine","InitLocale","Resolved language DE not available."
"2015-02-26 11:34:02","Display","Touch","IN"
"2015-02-26 11:34:02","","","<errormsg>Undefined variable: type</errormsg>

**Comment by dasgarner** [comment]
OK that is a bit of a shame... I will need to think about how we work around that. I don't really want to introduce another query for each layout (that could get resource intensive).

For now, can you split your layout into 2, just to work around this issue?

**Comment by xibo-de** [comment]
yes i do, thanks

**Comment by dasgarner** [comment]
This is a breaking change and would mean that we needed to increment XMDS versions. Each `<layout>` node will need to have a child node called `<dependants>` which contained nodes for all file names required for that Layout.

The schedule manager of each player would then need to parse that instead of the dependants attribute.

It would also mean *XMDS* needed to run a subsequent query against each Layout in the schedule to return its dependants.

**Comment by dasgarner** [comment]
This now needs to be fixed in the players and the manual
