### ISSUE TITLE
Widget: Weather widget displays "No results returned, please configure Open Weather Map Connector!"

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3400]
Error messages from widgets should be displayed in the layout editor only; they should never be displayed on the player itself. This bug is to find out why that was appears to the be case for the weather widget.

This was seen on the Tizen Player, but logically might effect other players also.

----------

The schedule for layout ID 848 (a layout used in an internal test CMS) presents the following error on the Tizen Player:
`No results returned, please configure Open Weather Map Connector!` 

However,

- A newly created layout with a weather static template, specifically  `Portrait - Current day, 2 day forecast` displays correctly on the Tizen Player.
- A copy of the layout also functions without any issues.

**Comment by rubenpingol-xibo** [comment]
I can't seem to replicate this anymore. Upon checking the code, the **No data message** error is always set to `display: none` except when we are in the editor and the connector encounters error.
