### ISSUE TITLE
Dataset Static Templates - Column Ordering Not Preserved

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3402]
### Description:
- When adding a dataset with multiple columns and using a static template for layout, the user can't keep the chosen column order.

### Steps to Reproduce:
1. Add a dataset with multiple columns.
2. Incorporate the dataset into a layout using the `Striped blue table with darker blue header` static template.
3. Choose which columns to display and specify the order.
4. Click away from the properties panel.

Observe if the preview reflects the specified column order.

### Expected Result: 
- The columns are displayed by their set order.

### Actual Result: 
Reopen the properties panel
- After setting the order and clicking away, the preview does not reflect the ordering. Upon reopening the properties panel, the ordering is lost.

**Comment by dasgarner** [comment]
@maurofmferrao this seems to be a FE issue as no API calls are made as the column order is changed.
