### ISSUE TITLE
wrong statistic Xibo Server 1.7.1

### ISSUE THREAD

**Issue by xibo-de** [xibosignage/xibo#341]
Xibo Client 1.7.0 / Windows XP
Xibo Server 1.7.1
Collection Time: 33 seconds

Layout "50-JPGs" with 50 JPGs

The Xibo client shows all of the 50 JPGs. In the statistic are only 10 JPGs shown.

![statistik01](https://cloud.githubusercontent.com/assets/10655684/6388700/1957c510-bd9d-11e4-9805-caec8deaa4ee.jpg)
![statistik02](https://cloud.githubusercontent.com/assets/10655684/6388702/1d4768ce-bd9d-11e4-82dc-19b6c863814e.jpg)

**Comment by dasgarner** [comment]
We will need a log of the SubmitStats XMDS call to see what is being sent back by the player.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!

**Comment by xibo-de** [comment]
I sent it for the second time by mail.

**Comment by dasgarner** [comment]
I haven't had any mail from you - can you put the log file on-line somewhere and repost on the new site.

**Comment by xibo-de** [comment]
entry not found under https://community.xibo.org.uk/

http://www.stoffzeit.biz/tmp/troubleshoot.txt

**Comment by xibo-de** [comment]
![mail](https://cloud.githubusercontent.com/assets/10655684/6595442/a93144f2-c7ea-11e4-979a-9e85fbca329f.jpg)

**Comment by dasgarner** [comment]
> entry not found under https://community.xibo.org.uk/

What do you mean by that? The site doesn't work?

**Comment by dasgarner** [comment]
These messages are odd:

> "2015-02-26 13:17:40","XMDSSoap4","SubmitStats","2015-02-26 13:18:29"

The message logged in there should be the entire logXML as sent by the player - and yet it seems that it is a single entry per item. I am not sure why that would be.

**Comment by xibo-de** [comment]
I had understood that the records have been moved

probably should I create a new entry under https://community.xibo.org.uk/

**Comment by dasgarner** [comment]
Right - no we haven't moved them - separating out the bugs, features and support would take too long... we have just switched to the new area.

We will still track verified bugs here and manage development from here - but all discussion should be on the community page.

**Comment by xibo-de** [comment]
With the final exe (last) there are no statistics, no entries in the database.

223	2015-03-11 14:59:36	XIBO-PC-DI	XMDSSoap4	SubmitLog	Log submitted without a date or category attribute
222	2015-03-11 14:59:36	XIBO-PC-DI	XMDSSoap4	SubmitLog	Log submitted without a date or category attribute
221	2015-03-11 14:59:36	XIBO-PC-DI	XMDSSoap4	SubmitLog	Log submitted without a date or category attribute
220	2015-03-11 14:59:36	XIBO-PC-DI	XMDSSoap4	SubmitLog	Log submitted without a date or category attribute
219	2015-03-11 14:59:36	XIBO-PC-DI	XMDSSoap4	SubmitLog	Log submitted without a date or category attribute

**Comment by dasgarner** [comment]
I've just run up the player whilst disconnected from the internet so that the `stats.xml_xxxxxx` files build up in the library folder.

Looking in one of those files I get the below:

``` xml
<stat type="Layout" fromdt="2015-03-11 15:38:45" todt="2015-03-11 15:38:55" layoutid="6" scheduleid="0" mediaid=""></stat>
<stat type="Media" fromdt="2015-03-11 15:38:46" todt="2015-03-11 15:38:55" layoutid="6" scheduleid="0" mediaid="21"></stat>
<stat type="Media" fromdt="2015-03-11 15:38:47" todt="2015-03-11 15:38:55" layoutid="6" scheduleid="0" mediaid="1c3f4e3039ed6274339369c95422ca8c"></stat>
<stat type="Media" fromdt="2015-03-11 15:38:47" todt="2015-03-11 15:38:55" layoutid="6" scheduleid="0" mediaid="32"></stat>
<stat type="Media" fromdt="2015-03-11 15:38:48" todt="2015-03-11 15:38:55" layoutid="6" scheduleid="0" mediaid="28"></stat>
```

Can you check the same on your installation?

**Comment by dasgarner** [comment]
I see what I have done - I will fix it and provide a commit

**Comment by xibo-de** [comment]
>Can you check the same on your installation?
I think that is no longer needed?

**Comment by dasgarner** [comment]
Right - no longer needed for that. I found the problem.

I hope everything is now resolved.
