### ISSUE TITLE
Marquee not working for more than 1 item in RSS feed

### ISSUE THREAD

**Issue by hhuber66** [xibosignage/xibo#342]
Hello all,
I have a RSS feed with more than one item. I want to show this in a region on the bottom side of the display in one line and effect "Marquee".
This does not work as Xibo is rendering the feed in more than one line.
Here are some examples for better understanding.
I want to have:
Titel Item1 Description Item1 Titel Item2 Description Item2 Titel Item3 Description Item3 and so on.

But Xibo is doing:
Titel Item1 Description Item1 
Titel Item2 Description Item2 
Titel Item3 Description Item3 

Can someone please tell me if this is possible?

Perhaps this is only removing a linefeed within the PHP-Code?

Thanks in advance for your helpful answers

**Comment by dasgarner** [comment]
Your feed must have some extra HTML markup inside it, which is forcing a line break. You can strip out unwanted tags using the strip tags functionality in the advanced tab.  You'd need to check what is coming back to be sure, but you could try DIV and P to start.

**Comment by hhuber66** [comment]
Hello Dan,
thanks for your very quick reply. 
Your answer brings me to the right way, although it is not the solution.
I have defined a custom css for my newsfeed. Whenever I use this it is generating paragraphs for the output. I have now copied and modified a template for the newsfeed and this works fine for me.

**Comment by dasgarner** [comment]
Great, glad you have it working!
