### ISSUE TITLE
Media: Large image thumbnail generation and resizing problems

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3428]
We are facing issues with thumbnail generation and image resizing for images larger than 6000px on any side, leading to potential memory usage errors.

Tasks:

**Thumbnail Generation**:
- Prevent the return of full-size images when thumbnails are requested.

**Thumbnail Resizing**:
- Errors may occur when resizing very large images to 120x120 thumbnails. 
- Find a way to resize or load images larger than 6000px for previews.

**Unused Parameter Handling**:
- The `isThumb=1` parameter isn't used anywhere, leading to full-size images being returned. 
- Remove this parameter if it is not needed.

**Relevant API Endpoints** needs further investigation:
- GET /library/download/33
- GET /library/thumbnail/{mediaId}

**Comment by dasgarner** [comment]
> Find a way to resize or load images larger than 6000px for previews.

I am not sure this can be achieved.
