### ISSUE TITLE
Proxy settings doesn't work - tickers

### ISSUE THREAD

**Issue by DanTheMan-NL** [xibosignage/xibo#343]
I can't use third party ticker feeds in my xibo template. I have looked up the error and the Xibo forum tells me this has something to do with the proxy in our office domain. 

Whenever I use the correct proxy settings we don't see any connections to our proxyserver from the server Xibo is setup. Is there anything we do wrong? I typed in the proxyserver name and the correct port but there is nothing send to our proxyserver.

Do I have to fill this somewhere else too?

**Comment by dasgarner** [comment]
No - that should be it.

Which version are you using?

**Comment by DanTheMan-NL** [comment]
I am currently using v1.7.1

**Comment by dasgarner** [comment]
If you have specified those settings in the CMS setting then they will be used for tickers. What is the error you are getting?

**Comment by DanTheMan-NL** [comment]
The client always gives this error: "Unable to get Resource: Unable to get the media resource".
The CMS tells me: "Loading SimplePie to handle RSS parsing.http://rss.cnn.com/rss/edition.rss"
"Feed Error: This XML document is invalid, likely due to invalid characters. XML error: Mismatched tag at line 7, column 8"

**Comment by jopper1988** [comment]
Is the proxy don't block it? I'm also behind a proxy and we had to open something in the proxy. 

But can you make fault report to see where is goes wrong ?

**Comment by DanTheMan-NL** [comment]
Hello Jopper, 

We have looked up the traffic from this server to the proxy and there is no traffic. We used the application splunk to look it up for us but strange enough there is nothing send to the proxyserver.

**Comment by jopper1988** [comment]
Then i think there is a firewall that is blocking the connection. Because the traffic is not reach the proxy. So i think there is something blocking it like a spamfilter or a corporate firewall.

**Comment by DanTheMan-NL** [comment]
I think that's also not the problem because when I use a wget from the Xibo server to an internet adress it works and it shows on the proxyserver.

So there is somehing in Xibo that seems to block it or is not setup right.

**Comment by jopper1988** [comment]
Can you make a screenshot of the proxy that you fill in on the CMS and the CLient

**Comment by DanTheMan-NL** [comment]
I'm afraid I cannot take a screenshot because the server address I typed in I cannot make public over the internet.

But in the Settings > Network I type in the following:
Proxy URL: "FQDN of server" have tried with http:// in the front and without.
Proxy port: 8080

I have tried it with and without account because they setup this server can connect to the internet without authentication. So at least splunk should tell me that there is something send to our proxyserver.

**Comment by jopper1988** [comment]
Did you also put this into the client?

**Comment by DanTheMan-NL** [comment]
Yes and that also doesn't work. But the server goes and get the RSS feed of the internet so there is no need to put this in the client.

**Comment by dasgarner** [comment]
> Loading SimplePie to handle RSS parsing.http://rss.cnn.com/rss/edition.rss"
"Feed Error: This XML document is invalid, likely due to invalid characters. XML error: Mismatched tag at line 7, column 8

This message would indicate that the XML document returned by the feed is not a valid XML feed (which seems very unlikely from CNN). Perhaps the Proxy is altering the document in some way? Does your XML document via WGET look ok?

**Comment by DanTheMan-NL** [comment]
Finaly got it working!! 
Somehow the Xibo Network settings don't work right. After setting our proxy adres multiple times in the Xibo settings and in Linux files it didn't work.

Now we changed the firewall settings to send all outgoing traffic from port 80 and 443 to an ip-adres from our proxy. Whatever Xibo and/or linux is saying it is send to the proxy.

**Comment by dasgarner** [comment]
Great, glad you have it working!

**Comment by DanTheMan-NL** [comment]
Yeah! Only one question: where to change the color of the RSS feed?
This used to work in older versions from Xibo.

**Comment by trevorff** [comment]
What proxy are you using? Maybe there is some issue with it? I always use some socks5 from http://buy.fineproxy.org/eng/ website, and everything was really good for me.

**Comment by DanTheMan-NL** [comment]
@trevorff We have a highly advanced Bluecoat proxy at work ;-)
