### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by tezza1971** [xibosignage/xibo#3432]
When using the official version of the docker compose file, I had an error where authentication to the mysql database failed.

I fixed the issue by adding a named network to the compose file and assigning it to each service. So now the web app and the mysql server are on the same network.

I'm not sure what gave rise to this circumstance but I think adding a fixed network to the official compose file won't hurt and it could potentially save someone a tonne of time.

I'm using 4.0.11 on debian 12 (6.1) with latest official (not package) version of docker ce.

This is my first experience with xibo. I posted about the error here...
https://community.xibo.org.uk/t/installation-is-broken-mysql-access-denied/31874/2

**Comment by dasgarner** [comment]
Thanks for letting us know - someone will take a look at that via your community post and open an issue once we find the root cause. I hope you enjoy using Xibo.
