### ISSUE TITLE
Widget: cache not ready improvements

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#3434]
Cache is only generated via XTR Widget Sync, however the player should return old cache if the new cache has not yet been generated, assuming it still has that data and it has not completely expired.

Currently once the data has been expired, it never gets returned, meaning there is always a period of time when the cache is not ready for the player to download.

**Comment by sasch901** [comment]
Hey, is this the same problem like in the community?https://community.xibo.org.uk/t/datasets-cache-not-ready/31245

**Comment by dasgarner** [comment]
It could be, yes. We're still testing the suggested fix to see if it improves the situation.

**Comment by pedroponte** [comment]
I am still getting what it seems to be the same issue, when adding a dataset to a layout.
Running v4.1.1 on docker.

Could you give me any hints to where I might need to look at?

TIA @dasgarner 

<img width="987" alt="Screenshot 2024-10-26 at 13 11 09" src="https://github.com/user-attachments/assets/5bf02b3d-79c1-4549-b31d-2a8f541d2b7c">

**Comment by pedroponte** [comment]
I solved it by looking at this [ticket](https://community.xibo.org.uk/t/r403-dataagent-cache-not-ready/32734/28) and increasing the memcached memory limit. Restarted all 3 containers, xibo and memcached and now working fine..!
