### ISSUE TITLE
Schedule Event: Add Form Modal Doesn't Close on Save When Criteria is Added

### ISSUE THREAD

**Issue by nadzpogi** [xibosignage/xibo#3444]
**Steps:**
1. Go to the "Schedule" page and click [Add Event].
2. Fill in the required details under the "General" tab.
3. Fill in any details under the "Criteria" tab.
4. Click the "Save" button.

**Expected Behavior:**
- The form should save the event, close the modal, and show a success message.

**Actual Behavior:**
- The modal remains open, and the "Save" button shows a continuous loading state.
- The page is still operable, but the modal does not close as expected.
- When page is refreshed, you can see that the form is successfully saved.
- Schedule response in developer tools shows `<br/><b>Warning</b>:  foreach() argument must be of type array|object, null given in <b>/lib/Entity/Schedule.php</b> on line <b>503</b><br/>...`

**Comment by dasgarner** [comment]
This also needs to be cherry-picked into release40 please
