### ISSUE TITLE
Ticker: Add checkbox to disable date sorting (Google calendar with wrong sort)

### ISSUE THREAD

**Issue by Rating** [xibosignage/xibo#345]
Updated my Xibo version from 1.6.* to 1.7.1 and I works and looks really good. But one thing is not working for me anymore. I use a ticker with a Google Calender to show todays events. It worked perfect before the update.

The sorting were after days, before. Now its after last added. Is it possible for me to change this somehow?

**Comment by dasgarner** [comment]
1.6 and 1.7 both used SimplePie for RSS feed parsing. The CMS parses the feed and sends the rendered content to the Player.

Sorting the feed is would have to occur in `modules/ticker.module.php` around line 876. You would need to add:

``` php
$feed->enable_order_by_date(false)
```

**Comment by Rating** [comment]
Thank you! Works like before now!

**Comment by dasgarner** [comment]
OK great - I am going to add an option for this in the next release (on the edit form).
