### ISSUE TITLE
Editor Toolbar: Inline playlist throws JS error on slow networks when closing

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#3450]
Steps to replicate bug:
- Go to Layout Editor
- Add a new playlist to the layout
- Open Dev Tools
- Set Network throtling to slow 3G
- Open Inline Playlist Editor and quickly close it
- A error will be thrown in the console because the toolbar wasn't properly initialized

**Comment by gracec20** [comment]
TEST: /Layout END
