### ISSUE TITLE
Spanish translation error in "Users" tab of the 

### ISSUE THREAD

**Issue by Davido264** [xibosignage/xibo#3469]
On the spanish translation, there is an error in the "Users" tab of the "Features" form. The issue resides here:

![image](https://github.com/user-attachments/assets/1f0e9116-0610-461f-b9a6-01abfef758af)

_"Funções de Usuário"_ and _"As notificações aparecem na barra de navegação"_ are not in Spanish, they are in Portuguese. The correct translations are _"Funciones de Usuario"_ and _"Las notificaciones aparecen en la barra de navegación"_

**Comment by dasgarner** [comment]
Thank you for reporting the issue; Xibo uses an open translation system over on Launchpad. More details here: https://community.xibo.org.uk/t/how-can-i-translate-xibo/11183

I believe I have corrected those: 
 - https://translations.launchpad.net/xibo/4.1/+pots/default/es/+translate?batch=10&show=all&search=User+functions
 - https://translations.launchpad.net/xibo/4.1/+pots/default/es/+translate?batch=10&show=all&search=notifications+appear
