### ISSUE TITLE
Layout preview: Unsupported/Erroring videos cause the preview to stop (e.g WMV files)

### ISSUE THREAD

**Issue by maurofmferrao** [xibosignage/xibo#3473]
`.wmv` video files do not play in any modern browser; they do play in IE11 via ActiveX or Silverlight. We should handle this in two different ways (preview vs player).

## Preview
An error message should be shown in place of the video, saying what was wrong. It should be shown for a short time, e.g. 5 seconds.

## Player
The video should be skipped (immediately expired), and a fault should be reported indicating the video failure.

**Comment by dasgarner** [comment]
It is not clear whether this ever worked (I think perhaps not as it did not have any special case).

To fix this we will likely require additional libraries to handle video playback, which may be something we want to do, but is too much change for 4.1. Moving this to 4.2.

**Comment by dasgarner** [comment]
Description updated after discussion.

**Comment by dasgarner** [comment]
Closing as solved.
