### ISSUE TITLE
When an RSS Feed has no items, the region shows up black...

### ISSUE THREAD

**Issue by mattdreher** [xibosignage/xibo#348]
Running v1.7.1 using Chrome embedded.

When an RSS Feed has no items in it, the region will show up as black.  This is even if the region has a background color set.  On the CMS, it shows up as white but on the Windows client it shows up as black.

Expected behavior would for it to be transparent if there was no background color set and for it to be the color of the background color if there was one set even if there were no items present in the feed.

**Comment by dasgarner** [comment]
If a feed is empty, the CMS will return an error when the Player tries to download the file, which will should cause the player to either:
 - use a cached version
 - skip the layout

By the sounds of it, the player is electing to put an empty webpage up instead (which is a black space if it doesn't populate it with anything).

**Comment by dasgarner** [comment]
This will be solved in #404 - will mark this as closed and track on that issue.
