### ISSUE TITLE
Weather Widget: Unable to Configure or Add to New Layouts

### ISSUE THREAD

**Issue by Does-This-Work** [xibosignage/xibo#3504]
Hi,

I am currently experiencing an issue with the weather widget in Xibo. Although it successfully displays the weather when I preview a layout that includes it, I am unable to see or add the weather widget to a new layout.

**Steps Taken:**
1. I added a free API key to Xibo.
2. After further reading, I realized I needed the "One Call API 3.0" key, which I have now obtained and configured.
3. Despite these steps, I still cannot see the weather widget as an option when creating or editing a layout.
4. I then added the Xibo Exchange and downloaded a template that includes the weather widget. When I play this layout, the weather widget displays the correct weather information.
5. I can see the widget in the template, but when attempting to configure it, I receive the following error message:
"This widget isn't enabled and can't be configured, please contact your administrator for help."

**Expected Behavior:**
The weather widget should be available to add in the layout editor.

**Actual Behavior:**
While the weather widget functions correctly in pre-existing layouts, it is not visible or available when trying to add it to a new layout. Additionally, I receive the error message above when attempting to configure the widget in an existing layout.

![image](https://github.com/user-attachments/assets/51790fca-7271-4485-b8be-6321f0211a66)
![image](https://github.com/user-attachments/assets/8907b993-be17-4da0-9b5d-3d8f58a3608f)
![image](https://github.com/user-attachments/assets/1cbd1168-e4d3-4ea9-a270-a701a3ce4f40)
![image](https://github.com/user-attachments/assets/4289ae33-10b2-4e81-815c-fe66f05ba6b6)

**Comment by dasgarner** [comment]
Hi and thank you for getting in touch. 

Xibo's development team use Github for verified bug reports and feature specifications only. Please can you direct this request to our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

If a bug arises from our investigation in community, we can take the necessary steps to report a public bug here.

Thanks!
