### ISSUE TITLE
upgradeing xibo from 1.6.4 to 1.7.1 

### ISSUE THREAD

**Issue by sagraw56** [xibosignage/xibo#351]
when i try to upgrade from xibo 1.6.4 to 1.7.1 i get this error An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 82. Error Message = [SQLSTATE[HY000]: General error: 1364 Field 'DisplayOrder' doesn't have a default value]

**Comment by pmeagher** [comment]
I had the same issue with my update. Make sure you do a full backup of the database! Mine did not backup as It should and it messed up the database to a point where it was easier to drop the database and start from scratch. I am not sure why that issue came up but I did not end up figuring it out.

**Comment by dasgarner** [comment]
Try #330 .
