### ISSUE TITLE
Remote Dataset: Unexpected error for long URI string

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3511]
CMS Version: 4.0.15, 4.1.0

When attempting to configure a remote dataset with a long URI, an error occurs. After entering the URI in the Remote Dataset settings and selecting the "Test Data Root" option, an error message is displayed.

`SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'uri' at row 1`

**Steps to Reproduce:**

- Go to Datasets and add a dataset
- Enter a long URI into the Remote -> URI settings.
- Click "Test Data Root" to trigger the error.
- Try saving the dataset settings, which results in an unexpected error.

Actual Behaviour
The system truncates the URI, leading to a database error

**Comment by dasgarner** [comment]
Add some validation to present a better error message.
