### ISSUE TITLE
Schedule: Validation error with up cursor input in Hours

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3518]
Bug: Seen on version 4.0.15, 4.1.1

A validation error occurs when the `hours` are incremented using the up cursor. However, if the user types the hour directly into the input field, the event schedules successfully.

Steps to Reproduce:
- Add a Schedule Event
- Set the `Dayparting` to `Custom.`
- Enable `Use Relative time.`
- Variant A: Type 1 in the `Hours` field manually and save the event.
Actual Result: The event is scheduled successfully.

Variant B: Use the up cursor to increment the `Hours` field from 0 to 1 and then save the event.
Actual Result: The system display san error message stating: `Cannot have an end time earlier than your start time.`

**Comment by maurofmferrao** [comment]
Can you please test this again in 4.1.1 @ifarzana ? It works for me if I save with 1 after clicking on the Hour field (empty) and pressing up, or if I start with 0 and also press up.

**Comment by ifarzana** [comment]
I have taken this steps

[Screencast from 14-10-24 13:50:23.webm](https://github.com/user-attachments/assets/e714b4be-4df6-43b0-8e70-efab8b1ea3d6)
