### ISSUE TITLE
Schedule Filter: Cannot clear dates when selecting a range

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3519]
The Close (`X`) buttons next to the From and To date fields are not functioning as expected. 

Steps to Reproduce:

- Go to the Schedule.
- Set a date range in the From and To fields.
- Click the Close (X) buttons next to the date fields.

Expected Result:
Clicking the `x` buttons should immediately clear the selected dates and update the schedule results without refreshing the page.

Actual Result:
The dates are not cleared when the `x` buttons are clicked. After refreshing the page, the dates are cleared, and all schedule results are displayed.

Screenshot:
![image](https://github.com/user-attachments/assets/d49b87f5-4972-4d16-8edf-16c29b73d03d)

**Comment by maurofmferrao** [comment]
This is working for me in `develop` and `kopff`, can you please check if this is still happening @ifarzana ?

**Comment by ifarzana** [comment]
I can see some errors in console now.

```
Uncaught Error: Calendar: Wrong date format NaN-NaN-NaN. Should be either "now" or "yyyy-mm-dd"
```
