### ISSUE TITLE
Client Update

### ISSUE THREAD

**Issue by pmeagher** [xibosignage/xibo#352]
Is there any way to force the client to update without closing out of the player and re-opening it? In 1.6 i remember a setting, I believe, that determines how often it checks for updates. Is there a setting for this in 1.7.1?

**Comment by dasgarner** [comment]
Please read the [installation guide](http://xibo.org.uk/manual/en/install_windows_client.html) and the [display profiles](http://xibo.org.uk/manual/en/displays_settings.html) section.
