### ISSUE TITLE
Menuboard Element: Name text cutoff with Fit to selection and gradient settings

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3520]
In the Menuboard product/categories, a change in the appearance of the name element causes text cutoff in the Name field.

Steps to reproduce:

- Apply both `Fit to selection` and `Use gradient for the text?` to the name element.
- Notice that the text in the Name field gets cut off.

Expected behaviour:
The name text should display correctly without being cut off when both are applied.

![image](https://github.com/user-attachments/assets/f3ca3de1-c20a-47b1-bad9-14c30991b0b0)

**Comment by maurofmferrao** [comment]
Related to gradient in #3522 , might be fixed by fixing that issue.

**Comment by maurofmferrao** [comment]
The way that we use to render gradients uses a background mask with the text as mask that then renders just the text with gradient.

That means the text shows on the overflow if the text passes the area.

![Image](https://github.com/user-attachments/assets/275276e8-4300-47f9-a3f3-f79a9e65fa4c)

 But unfortunately for fonts that span outside the font space itself, it cuts them.

![Image](https://github.com/user-attachments/assets/0fdd8893-ce37-49d4-8066-f884b58b8f80)
