### ISSUE TITLE
Schedule: Unable to edit repeats option

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3521]
CMS Version: 4.0.15, 4.1.1

When attempting to edit the `Repeats` option for a scheduled event that was previously set as `Daily` and trying to change it to a `Minute` repeat type, an error occurs. 

The error message states: `Repeats selection is invalid for Always or Daypart events,`

Steps to Reproduce:

- Open a scheduled event previously set with `Daily` repeats.
- Change the repeat option to `Per Minute`
- Save the event.

Expected Result: The "Repeats" option should be editable, and the new repeat type should be saved without error.

**Comment by dasgarner** [comment]
This was closed as not planned because it turns out not to be a bug.
