### ISSUE TITLE
Dynamic Playlist: Ordering disruption with empty playlist in a sub-playlist

### ISSUE THREAD

**Issue by ifarzana** [xibosignage/xibo#3539]
When an empty dynamic playlist is included alongside other populated dynamic playlists, the intended sequence of media items is disrupted.

Steps to Reproduce:

1. Create three dynamic playlists:
   - Playlist One: Contains media items A1, A2, A3, A4, A5, and A6.
   - Playlist Two: Contains a single media item B1.
   - Playlist Three: Leave this playlist empty.

2. Configure the layout 
    - Add these three playlists as a sub-playlist on the layout:
    Expected order:

![image](https://github.com/user-attachments/assets/8e1ce0c3-c8bb-4fe4-b0f4-537a5d28f19d)

4. Observe the playback sequence in Layout Preview

Expected Behaviour: The playlists should display in the following order: A1 B1 A2 B1 A3 B1 A4 B1 A5 B1 A6 B1

Actual Behaviour: When the empty playlist (Playlist Three) is included, the sequence is disrupted, resulting in a disordered playback. For example: A1 B1 A1 A2 B1 A2 A3 B1 A3 A4 B1 A4 A5 B1

Additional Findings:

Removing the empty playlist resolves the issue and restores the correct order.

An internal dev environment has a layout (ID 2506) showcasing the issue.

**Comment by dasgarner** [comment]
@PeterMis does this get solved with these changes? https://github.com/xibosignage/xibo/issues/3535

**Comment by PeterMis** [comment]
This behaviour is actually expected and intentionally handled this way.

When an empty Playlist has number of spots defined and is not the first playlist, then it is changed to `Fill` and uses first playlist content to fill the required number of spots.

It would be ignored when empty if
- it was the first playlist and had spots set
- it did not have spots set

**Comment by dasgarner** [comment]
@ifarzana does Peter's reply make sense? do you have any follow up?

**Comment by ifarzana** [comment]
It makes sense, I'll follow up with support team, Thanks.
