### ISSUE TITLE
CMS Layout Designer context menu disappears behind nav menu

### ISSUE THREAD

**Issue by xibo-de** [xibosignage/xibo#355]
Xibo Server 1.7.1
Google Chrome Version 40.0.2214.115 m
![hidden2](https://cloud.githubusercontent.com/assets/10655684/6409621/88129b0a-be66-11e4-8098-5cc4593852cc.jpg)

**Comment by MedusaDelft** [comment]
There are more problems with this context-menu. The selection box is not always available after a reload of the screen. It has to 'disappear' first before it is clickable.

Sometimes items can't be clicked if the menu is larger than the height of the region.

**Comment by Speedy-Gonzalez** [comment]
https://github.com/xibosignage/xibo-cms/pull/19 with this pull request I introduced a bigger standard region. I've tested my "fix" if it also solves your problem and even with the small screen of my laptop (1280x800) I can see all of the menu (with German translations).

The fix should be available with Xibo 1.7.2

**Comment by xibo-de** [comment]
the fix works great ...

thanks

**Comment by dasgarner** [comment]
It needs its z-index adjusting (just in case you want a real thin left hand region) I'm not sure about the really short regions, i've also noticed the issue.

**Comment by cgslaughter** [comment]
I have had that issue as well after updating to 1.7.2. I was able to fix it by completely clearing my browsers cache and cookies

**Comment by PeterMis** [comment]
Test:Passed
