### ISSUE TITLE
CKEditor toolbar fails to apply formatting to table content

### ISSUE THREAD

**Issue by gracec20** [xibosignage/xibo#3551]
CKEditor toolbar does not function as expected when editing tables and their contents. While the toolbar works correctly for other non-table elements such as simple text, attempting to edit table content causes the toolbar to unexpectedly close without applying the selected formatting (e.g., color, bold).

https://github.com/user-attachments/assets/adead638-f61b-465e-8530-b1256cf8845e

**Comment by maurofmferrao** [comment]
This is the same issue as https://github.com/xibosignage/xibo/issues/3546
 It will be fixed there!
