### ISSUE TITLE
CMS 1.7.1 User Group Member error

### ISSUE THREAD

**Issue by solane** [xibosignage/xibo#356]
Hi I have recently added a new user group so that I can give new users different permissions from others however when I go to select 'Members' I get the error message 'Error getting users' (see photo).

Weirdly the groups that I created a while back still allow me to see and change the members.

Any thoughts on why this error might be happening?

Thanks
Sam

![error getting users](https://cloud.githubusercontent.com/assets/10942349/6415933/1a31573c-be9a-11e4-9217-8975d98222ff.JPG)

**Comment by frankverdonk** [comment]
Same here,, rg Frank

**Comment by dasgarner** [comment]
Silly mistake on my part - sorry. See attached patch.

**Comment by xibo-de** [comment]
after applying the Patch:

View
![usergroup-1](https://cloud.githubusercontent.com/assets/10655684/6541725/432c3204-c4e1-11e4-99a3-98130d9161fd.jpg)

Modification and Save
![usergroup-2](https://cloud.githubusercontent.com/assets/10655684/6541729/5a49668c-c4e1-11e4-855a-6c4028c40276.jpg)

new view: mini and test not saved
![usergroup-3](https://cloud.githubusercontent.com/assets/10655684/6541730/623c7b86-c4e1-11e4-8390-6e121d7a9db1.jpg)

**Comment by dasgarner** [comment]
I don't seem to be able to recreate that problem - did you take the whole file, or just the changes specific to the commit?

**Comment by xibo-de** [comment]
Best you try it yourself - User and Pw per Mail
