### ISSUE TITLE
HELP Parse error with Xibo Software!

### ISSUE THREAD

**Issue by Auburn1** [xibosignage/xibo#358]
I have downloaded Xibo Software recently and have been running into trouble with the code. Below is a screenshot of the error we are getting in the file "include.php" 
![halpp](https://cloud.githubusercontent.com/assets/11217539/6417858/568ba92e-be7e-11e4-875f-e7b41f3002f5.png)
We have tried moving the code elsewhere in the document but the error line moves with the code. We are running XAMPP Software with Xibo if that has anything to do with it. Here is the line of the code from the file where the error is occuring.
![morehallpp](https://cloud.githubusercontent.com/assets/11217539/6417927/e6daa30e-be7e-11e4-884e-9ddbc22db713.png)
If you have any questions please ask, we are welcome to any help!

**Comment by dasgarner** [comment]
What version of PHP are you running? You need 5.3.3 or later

**Comment by Auburn1** [comment]
we are now running the newest version of php that we could find, 5.2.22. We are still running into the same error

**Comment by Auburn1** [comment]
Are PHP was out dated, but we did just update it to 5.6.6. We are still having the same problem also we updated are mysql files. Any other ideas? Thanks

**Comment by dasgarner** [comment]
Are you sure you are having the same problem? anonymous functions are supported in PHP 5.3.3 and above.

You could try rewriting it as:

``` php

$autoloader = function ($class) {
    Kit::ClassLoader($class);
};

spl_autoload_register($autoloader);
```

But you might experience problems elsewhere.

**Comment by Auburn1** [comment]
We replaced the code with the code above and we are still receiving a parse error. We also placed an echo right after the function declaration we never got there. We moved the code up to see if the error followed the code and it did.
![prob](https://cloud.githubusercontent.com/assets/11217539/6467443/30b76906-c19c-11e4-9e05-c1d3dd3cc7e5.png)

**Comment by dasgarner** [comment]
I really don't know - sorry.

Here is the [PHP Manual](http://php.net/manual/en/function.spl-autoload-register.php) for how this function works. Perhaps you will find some clues why it doesn't work for you?

**Comment by MedusaDelft** [comment]
PHP is not running in CLI mode?  If so, this might cause an error for autoloading.

**Comment by Auburn1** [comment]
@MedusaDelft What does running in CLI mode mean?

**Comment by Auburn1** [comment]
If anybody does know what " Kit::ClassLoader($class);" calls to that would help us greatly! thanks

**Comment by MedusaDelft** [comment]
@Auburn1 CLI is Command Line Interface.

**Comment by Auburn1** [comment]
@medusaDelft How would we go about checking that

**Comment by dasgarner** [comment]
Its a class loading routine that takes the class name and locates the appropriate include file. It is absolutely required to have the auto_loader working so that does need to be called.

Perhaps you could try rewriting as this (slightly different from prior suggestion)

``` php
function autoloader($class) {
    Kit::ClassLoader($class);
}

spl_autoload_register('autoloader');
```


-------
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
