### ISSUE TITLE
Export / Import Layout

### ISSUE THREAD

**Issue by xibo-de** [xibosignage/xibo#361]
Hello,

If I as a user (user type: user) import a layout, I can not access the regions and content.
First the Super Admin must assign rights.

![import-export](https://cloud.githubusercontent.com/assets/10655684/6430657/c4fa69ea-c013-11e4-9806-b22a020db0e5.jpg)

**Comment by dasgarner** [comment]
Ah, that isn't right... tagged as a bug.

**Comment by fogsag** [comment]
I tried this patch. Regions are now editable. But when i edit a region, there is no content (ticker) in the "Region Timeline" - it is blank.

![xibo_region_empty](https://cloud.githubusercontent.com/assets/11313608/6505153/65776d90-c33f-11e4-80a4-636683456833.png)

**Comment by fogsag** [comment]
It works as root but not as user. Another permission problem?

**Comment by dasgarner** [comment]
Hmm, it should be setting the importing user as the owner of each media assignment - which seemed to work when I tested it.

Can you import a fresh one and then immediately export and provide the ZIP?

**Comment by fogsag** [comment]
Export from 1.7.0 as root: http://s000.tinyupload.com/?file_id=08737355078285178883
Export from 1.7.1 after import: http://s000.tinyupload.com/index.php?file_id=08495712501013460476

**Comment by fogsag** [comment]
For information: i applied the patch only in version 1.7.1 (Updated import to set the userid correctly / 11d4858)

**Comment by fogsag** [comment]
diff layout_alt.xml layout.xml 
	2c2
	< <layout width="1920" height="1080" resolutionid="9" bgcolor="#000000" schemaVersion="2"><region id="54f88640cbf12" userId="1" width="1920" height="1080" top="0" left="0"><media id="58285662debd3b86ad376563009678ea" type="ticker" render="native" duration="7" lkid="" userId="1" schemaVersion="1">
	---
	> <layout width="1920" height="1080" resolutionid="9" bgcolor="#000000" schemaVersion="2"><region id="54f88640cbf12" userId="3" width="1920" height="1080" top="0" left="0"><media id="58285662debd3b86ad376563009678ea" type="ticker" render="native" duration="7" lkid="" userId="1" schemaVersion="1">

**Comment by dasgarner** [comment]
I see the issue now... please try the second patch.

**Comment by fogsag** [comment]
Works great. Thanks!

**Comment by dasgarner** [comment]
Brilliant!
