### ISSUE TITLE
TV-Stream

### ISSUE THREAD

**Issue by Knapec** [xibosignage/xibo#363]
Is it possible to use Xibo for distribution from DVB-T MPEG-2 live stream to client computers?

**Comment by mattgrimley** [comment]
You can embed a live stream, but you need something to host it.. (i.e. TV decoding and stream serving isn't handled by XIbo).

We use a dedicated machine with TVHeadend which shares a web-accessible stream of the current channel. We then embed that stream in a layout using the "Embedded HTML" object.

I had to fiddle with it a bit to get subtitles working, but it runs flawlessly now on 5 displays simultaneously.

**Comment by nagyrobi** [comment]
Wow! Can you please share how you did it?

**Comment by andyblackham** [comment]
I've come to ask this exact question.  I'd like to know what the components are.
thanks
andy

**Comment by mattgrimley** [comment]
Well, first up you need to get a working TVHeadEnd server running. I followed a guide and the only issue i had was getting a relevant driver for my USB tv decoder.. This took a bit of hunting around and a few attempts at different drivers, but I found one that worked in the end.. I used a bunch of different guides, but big chunks of this one https://tvheadend.org/boards/4/topics/10322 were my basic steps (you can skip the HDHomeRun sections and the US channel guides, unless you have that hardware)

I can't remember if i had to install something for channel descriptions, but i certainly skipped the EPG program guide data stuff.. I think it can download basic info over the stream using "Over the air grabbers".

Now, you should be able to test your streaming.. In the manager, click "Watch TV" and then select "BBC News" - you get a link for M3U playlist.. download this and open it in VLC player. You should see the video. Test that subtitles work from the menu.

Now for the Xibo bit:
You need VLC installed on your client machine.

Create an "Embedded" item on a region timeline on a page in Xibo.
Note: You need either to enable anonymous access to the page or create a user with a non-secure password on the tvheadend box. in the below example, you will need to customise the line:
```
http://username:password@hostname:9981/playlist/channelid/33
```

Settings for the Embedded HTML

HTML To Embed
```
<body bgcolor="#000000" onload=start()>
    <object classid="clsid:9BE31822-FDAD-461B-AD51-BE1D1C159921" codebase="http://downloads.videolan.org/pub/videolan/vlc/latest/win32/axvlc.cab" width="749" height="420" id="vlc" events="True">
      <param name="Src" value="http://username:password@hostname:9981/playlist/channelid/33" />
      <param name="ShowDisplay" value="False" />
      <param name="AutoLoop" value="False" />
      <param name="Controls" value="False" />
      <param name="AutoPlay" value="True" />
    </object>
  </body>
```

Head Content to Embed
```
<script type="text/javascript">
function EmbedInit() {
    // Init will be called when this page is loaded in the client.
    timeout = setTimeout(subtitles,1000);
    return;
    }
function subtitles() {
    var vlc = document.getElementById("vlc");
    <!--vlc.audio.toggleMute();-->
    vlc.subtitle.track='505';
    vlc.video.deinterlace.enable("blend")
    }
</script>
```

I had issues getting the embedded VLC to display consistently (i just saw a black page sometimes), and my rather naff solutions were twofold; I added a video item to the Xibo timeline to show the BBC intro (12 seconds), this seems to give the page chance to load properly.. and i inserted a delay in the subtitles loading, which again seems to allow it to load properly. My TV item loads for 720 seconds and then it recycles back to the 12 seconds BBC intro video.

Sorry i can't give you a better guide, i do wish i'd made proper notes when setting it up and if i redo it, i will!!

Good Luck,
Matt

**Comment by dasgarner** [comment]
If anyone ever wanted to write this up into a Guide for the Manual - that would be fantastic :)

**Comment by andyblackham** [comment]
I’m part way through getting it setup.

I’ll look at documenting it once I’ve confirmed the processes, prerequisites
and assumptions.
andy

From:  Dan Garner <notifications@github.com>
Reply-To:  xibosignage/xibo
<reply+00a686d50f4ecf90fc31564d270f43a1480413dd22671d3592cf0000000111101e9a9
2a169ce038a8e1b@reply.github.com>
Date:  Thursday, 5 March 2015 13:39
To:  xibosignage/xibo <xibo@noreply.github.com>
Cc:  Andy Blackham <andy.blackham@ntlworld.com>
Subject:  Re: [xibo] TV-Stream (#363)


If anyone ever wanted to write this up into a Guide for the Manual - that
would be fantastic :)

—
Reply to this email directly or view it on GitHub
<https://github.com/xibosignage/xibo/issues/363#issuecomment-77364650> .

**Comment by nagyrobi** [comment]
Thanks.

Reading it through, seems this is a specific solution relying on Windows and AciveX control of VLC integrated in the web browser.

I'd like to achieve something similar using the Android version of Xibo client.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
