### ISSUE TITLE
Ubuntu CMS says layout valid. Win7 client says layout invalid

### ISSUE THREAD

**Issue by marshalldavis** [xibosignage/xibo#364]
Here are my environments, just for troubleshooting.
CMS:
Ubuntu 14.04 LTS 64-bit.
Fresh install built for xibo CMS.
xibo 1.6.x updated to 1.7.1

Clients:
Win7 Enterprise 64-bit
Fresh install built for xibo client.
xibo 1.6.x updated to 1.7.1

I had everything working beautifully for a few weeks. I have several displays that I have had working since 1.6.x. I have updated to 1.7.0 and saw issues and upgraded to 1.7.1 on both clients and server to make sure a bug fix might have been issued. Both CMS and clients are running 1.7.1, and I can't get much of anything other than a xibo signage splash screen on the clients.

Looking through the client logs, it shows the layouts are invalid. The CMS believes that the layouts are valid. Looking at the info on the client, most of the files are still at 0%. The only files at 100% are the layout files(which are invalid on the client) and a "resource<hex garbage>.htm" file. The issue seems to revolve around the MD5 between the CMS and clients are not the same, as I get those errors too.

I have went through and in every place I know about, I have set the media, layouts, and displays to have permissions to everything and everyone for viewing.

I tried deleting all of the files from the xibo library on a client after reading some of the posts, as it is supposed to re-download the files.

I have also seen another post in here to wipe out the MD5 hashes that the CMS created for the files, but I haven't tried that yet. I feel uncomfortable about tampering with the database unless I'm sure that is the root cause.

Let me know if I could provide more information for you. Perhaps I'm missing something simple?

Thanks for all of the hard work. I'll help however I can.
Marshall

**Comment by nagyrobi** [comment]
Did you also upgrade the layouts in the CMS one by one?

**Comment by marshalldavis** [comment]
Yes. I went one step further and created a new layout on 1.7.1 with nothing but a static image in a region. I made it the default layout for a client, and it sent the layout to the client, but also says the layout is invalid. Layout is valid on CMS though.

**Comment by marshalldavis** [comment]
As an update, I cleared the MD5 hashes from the media table in the database. The database looks like it re-created them automatically. Unfortunately, this seems to have made no change when updating the clients. They still claim the MD5 hashes are not the same. It looks like I'm just going to wipe everything out and find another solution.

**Comment by dasgarner** [comment]
It sounds to me like your CMS library is missing or you don't have permission to read/write from it... that would explain why the files the CMS serves don't match MD5 and why Layout files work (they are stored in the DB, not in the library).

Check your library location.

**Comment by marshalldavis** [comment]
I blew away the DB and xibo and re-installed 1.7.1, letting the installer create the DB and building everything over again. That seems to have fixed it. I'm not sure why the CMS library would be missing or not have permissions. Xibo was writing files in there, such as the weather icons, and media I uploaded. None of that should have changed.

**Comment by dasgarner** [comment]
> Xibo was writing files in there, such as the weather icons

Probably not the case then - it may have been the "File Download Mode" setting in the CMS (unless configured correctly it should be set to "Off")

In any case, pleased you have it working.

**Comment by marshalldavis** [comment]
I do seem to remember that setting in the CMS, that had the option of Apache or IIS or Off. I might have set it to Apache when tinkering and started this entire mess. If that is the case, then I feel embarrassed, but I'm okay with embarrasment if it helps us move forward and will help some other poor soul that might inadvertently turn it on and find an answer here.

**Comment by dasgarner** [comment]
I wouldn't feel embarrassed - that setting needs some better explanation in the manual and a bigger warning sticker.
