### ISSUE TITLE
Blank Page After Logging Into 1.7.1

### ISSUE THREAD

**Issue by JELedoux** [xibosignage/xibo#365]
After doing a new successful install of 1.7.1 on my x10hosting.com site, right after entering in my login credentials, I get a blank white page and no errors.  What could be causing this?

Thank you.

**Comment by Speedy-Gonzalez** [comment]
What OS do you use?

When I started to use Xibo under my Fedora environment I had the same problem (sorry I didn't reported it yet). I had installed the apache and PHP and the Xibo installer had done his job without warnings, but I got a blank page.

The solution that worked for me was to install an missing PHP extension. My system was missing the "php-pecl-zip" PHP extension. Please check if you have installed this extension.

**Comment by JELedoux** [comment]
I've tried it under Windows 7 64-bit and Windows 8.1 64-bit.  On both of those OS, I tried it running Internet Explorer 11 and Firefox 34.0.5.  All with the same result.

**Comment by JELedoux** [comment]
MY SOLUTION: In the x10hosting.com Control Panel, look in the Software and Services section.  Click on the Select PHP Version and click the checkbox next to "zip".  Click on the Save button and all is right with the world.
