### ISSUE TITLE
Change default layout at once for multiple displays

### ISSUE THREAD

**Issue by nagyrobi** [xibosignage/xibo#368]
There should be an option in the CMS where the user could select a number of displays, and change settings at once for them. 

I need to change the Default Layout for a big number of displays and I have to do it one by one...

The top title row has a check all option, a dropdown should be present at the end of the row just like each display has. Care should be taken to only change the values which were modified, not all of them.
Could also be done through the Groups feature, using temporary groups just to set common settings.

**Comment by laercionit** [comment]
+1 for this
