### ISSUE TITLE
1.7.x not able to load a page or script from solarlog

### ISSUE THREAD

**Issue by DVC-it** [xibosignage/xibo#369]
After  successfully running an install of 1.7.x against my www.tclip.nl site, putting script in xibo or loading my HTML page at http://www.tclip.nl/www/index-mulder.html, I get a blank white page and no errors. 
When I load it over the preview the page is okee or over android it is perfect only windows blank page.

What could be causing this?

Thank you.

**Comment by dasgarner** [comment]
When you say "windows" do you mean the Layout Designer in the CMS? Or the Windows Player?

The Layout Designer in the CMS won't show you a preview if you have your webpage selected to "open natively".

**Comment by DVC-it** [comment]
I mean the, the Layout Designer is showing up perfect in scripting  or loading the webpage. The Windows player 1.7.1 will not show up the design at all of this particuler page or script.

**Comment by dasgarner** [comment]
In that case my guess would be that the version of IE the windows player is using is too early to support SVG. You may want to try [this](https://github.com/dasgarner/xibo-manual/blob/develop/source/en/faq_webbrowser_emulation.md) - its not a complete article yet, sorry - hopefully you will get the idea.

**Comment by DVC-it** [comment]
Thanks, it works with registry registration to get the .NET framework in the WebBrowserControl to run.

**Comment by dasgarner** [comment]
Fantastic!
