### ISSUE TITLE
lkcampaignlayout no default displayorder value

### ISSUE THREAD

**Issue by scienceworld** [xibosignage/xibo#370]
when running 82.sql when upgrading from 1.6.4 to 1.7.1 get a SQL error (1364) field 'DisplayOrder' doesn't have a default value while performing sql statement on row 51 inserting into 'lkcampaignlayout'.

the table structure does not have a default value.
![image](https://cloud.githubusercontent.com/assets/3997916/6447395/cc35ad1a-c0c6-11e4-9922-c7aa9a47ca86.png)

setting displayorder column to default value of 0 fixes the problem.

**Comment by dasgarner** [comment]
Thanks!
