### ISSUE TITLE
1.7.x CMS allow copy of display hardware key

### ISSUE THREAD

**Issue by scienceworld** [xibosignage/xibo#373]
While performing an upgrade, or a reinstall of the client it is useful for a xibo client to retain the same display hardware key as it used previously.  As a time saver one would copy the display ID from the server and paste onto the client.  

The hardware key field is protected to prevent selecting and copying so one has to transcribe by hand.

![image](https://cloud.githubusercontent.com/assets/3997916/6448010/bff03ab6-c0cb-11e4-9f0e-63333d1e0747.png)

**Comment by dasgarner** [comment]
This will only effect upgrades from 1.6 to 1.7 - and only where the hardware key has been modified (or the CPU/HDD changed in the player since the 1.6 installation).

I agree it would be nice to copy that field - I have found that irritating myself.

**Comment by scienceworld** [comment]
Thanks!
