### ISSUE TITLE
Windows xibo client Transitions v1.7.1

### ISSUE THREAD

**Issue by scienceworld** [xibosignage/xibo#374]
I'm trying out transitions and haven't been able to get them to work yet.  I've enabled in and out transitions from the transitions screen. 

I've enabled transitions in and out on the playlist editor for media items.

The windows xibo client is not displaying transitions between images in a timeline as well as the CMS preview is also not displaying transitions.

Simple Fade In 500ms North settings for transition in and no effect.

![image](https://cloud.githubusercontent.com/assets/3997916/6451976/26d3c43a-c0e7-11e4-83bd-f6f47e0fd964.png)

**Comment by mbreckers** [comment]
As far as I'm aware the transitions are Linux only

**Comment by dasgarner** [comment]
Correct - Linux and Android only at present. We are working on it in #29

**Comment by scienceworld** [comment]
can we add a comment on the CMS that indicates the players transition features work on?  

my entire set up uses windows clients, and I didnt find anything in the manual or while setting transitions that indicated that it was linux client only.

**Comment by dasgarner** [comment]
They are disabled by default for exactly that reason.

Top of the transitions page in the manual:
>Xibo supports basic transitions between Region Playlist items. These are supported in the Ubuntu and Android Display clients only.

**Comment by scienceworld** [comment]
it did it for me again, but only the first time I did it.

1) design layout
2) click on edit time line
3) click on switch to grid
4) click on in transition from drop down
5) save
6) return to list view
7) repeat, and the symptoms do not re-occur.

must be a cookie or user preference non-initialization thing.  can't repeat a second time.
