### ISSUE TITLE
Playlist Grid Features

### ISSUE THREAD

**Issue by scienceworld** [xibosignage/xibo#375]
Hi there, I love the new grid feature of the timeline editor within a layout!

Just hoping we can add a few more features to it.

With Selected
-add/change permissions
-add/change transitions
-change duration

Grid
-drag and drop re-ordering

Persistence
-when editing an item in the grid, specifically transitions, you leave the timeline editor, a new popup opens with transition settings, when you close that the timeline editor re-opens and your back in the List view of the media items within the timeline.  The gird is meant to be quicker, i think, but with this in ability to keep your current state it's quite a bit slower.

**Comment by dasgarner** [comment]
#382 for persistence - I will try and recreate but I think this should work (hence separate issue). Other items are enhancements, tagged accordingly.

**Comment by dasgarner** [comment]
We are going to supersede this issue with this one: https://github.com/xibosignage/xibo/issues/556 as we are hoping to phase out the grid view in favour of a more adaptive timeline view.

The grid view still functions as if previously did and the persistence bug has been solved as far as I am aware.
