### ISSUE TITLE
Clock Manual, add supported formats.

### ISSUE THREAD

**Issue by scienceworld** [xibosignage/xibo#376]
Love the new clock. Yay!

Looking for a couple enhancements with regards to time formatting.

in addition the existing HH:mm for 24hr clock, be able to support [hh:mm aa] for 12hr clock with am/pm. presently hh:mm works, but pads the time with a leading zero if less than 12.  eg "02:44".  Ideally it would display as "2:44 pm"

**Comment by dasgarner** [comment]
Does h:mm work?

**Comment by scienceworld** [comment]
Yes! it works!

Can this be added to documentation and within the clock html editor area?

![image](https://cloud.githubusercontent.com/assets/3997916/6467441/088742bc-c183-11e4-8d80-080a6ae96510.png)

![image](https://cloud.githubusercontent.com/assets/3997916/6467445/14275bb6-c183-11e4-9230-ec58194a223b.png)
