### ISSUE TITLE
Xibo client shows cached images from website (not being updated correct when images are replaced)

### ISSUE THREAD

**Issue by HollandHards** [xibosignage/xibo#377]
We use xibo to display time-table for students. Xibo displays the content using the 'website'-slide. 

When we update images of the schedule on the website; xibo keeps showing old content/schedule. (students miss class , end up at wrong room).

When i restart the client; xibo starts shows the correct (most recent content/imaged). 

However, i don't feel fancy restarting every client after every update on ext. website. 

Any suggestions?

**Comment by alexharrington** [comment]
The client will obey the cache control values your webserver sends it. You need to ensure that your webpages/images are sent to the client with appropriate cache ttl values. You can configure that on your webserver
