### ISSUE TITLE
Missing PowerPoint instructions from the Manual

### ISSUE THREAD

**Issue by CactusPiquant** [xibosignage/xibo#378]
Hello.

I'm currently trying to get Xibo working, being a trainee in an organization. Everything worked fine with the first client, but I have an issue with the others.

This may be outdated, but it's giving a good idea of my problem.
http://wiki.xibo.org.uk/wiki/Install_Guide_NET_Client#Windows_Modifications
"The first time you run Xibo with a Powerpoint, you might get a popup appear that asks what Xibo should do with the Powerpoint file. The popup actually originates from Internet Explorer. Choose to "Open" the file, and untick the box so you won't be prompted again."

The prob is that I'm not getting the box to untick, so that popup is appearing everytime. I tried to downgrade from IE 11 to 10, but it didn't do anything. I also tried to modify the BrowsersFlags key in the registry to get this working the right way but it was no use.

I'm actually thinking about taking an iso of the computer which is working and install this windows 7 config on the others. 

Thanks for reading and for the future answers. I apologize for my english, truth is that it's not my main language. Have a nice day.

**Comment by waarsenburg** [comment]
Change/add the following registry keys:
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PowerPoint.Show.8]
"BrowserFlags"=dword:800000A0
"EditFlags"=hex:00,00,01,00

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PowerPoint.Show.12]
"BrowserFlags"=dword:800000A0
"EditFlags"=hex:00,00,01,00

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PowerPoint.ShowMacroEnabled.12]
"BrowserFlags"=dword:800000A0

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PowerPoint.SlideShow.8]
"BrowserFlags"=dword:800000A0

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PowerPoint.SlideShow.12]
"BrowserFlags"=dword:800000A0

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\PowerPoint.SlideShowMacroEnabled.12]
"BrowserFlags"=dword:800000A0

and your popups will disappear. It's not a XIBO issue, but a Windows issue.

**Comment by CactusPiquant** [comment]
I know it was a Windows issue, but you were probably conscious about this, I found the solution nowhere and it was still xibo related.
Sorry if I posted at the wrong place, trying this right now. Thanks for your help.

**Comment by dasgarner** [comment]
Please see the manual for more detail: http://xibo.org.uk/manual/media_module_powerpoint.html#machine_preparation

**Comment by mattgrimley** [comment]
Hey @dasgarner i tried the registry change from the machine preparation page above and the "fixit" and neither solved it for me, however, the broader changes as recommended by @waarsenburg above did work for me. (The office 2010 fixit in point of fact reported that it could not run on my machine)

My install is Office 2010 on a Windows 7 64bit machine.

Either way, cheers for sharing @waarsenburg !

**Comment by dasgarner** [comment]
I thought they were the same - but they aren't :smile: 

Tagged up to fix the manual.
