### ISSUE TITLE
Twitter module typo in German locale

### ISSUE THREAD

**Issue by Mondlicht81** [xibosignage/xibo#380]
This is just about a small typo: The Twitter module is called "Weitter" in the German locale (file locale/de.mo)
I can't change it by myself since the file seems to be coded binary. But I think you should find it easily.

**Comment by dasgarner** [comment]
Perhaps you could look here - [Translation Project](https://translations.launchpad.net/xibo/github/+pots/default/de/+translate?batch=10&show=all&search=twitter)

Translations can be changed via a web UI. Once changed they will be included with the next release.

**Comment by Speedy-Gonzalez** [comment]
I already fixed this on 2015-01-22. You can download the newest de.mo file here (but you need a launchpad account) or you wait for the next Xibo release (the newest translations should then be included)

**Comment by dasgarner** [comment]
thanks @Speedy-Gonzalez

**Comment by Mondlicht81** [comment]
Ok, thanks. I'll check this out.
