### ISSUE TITLE
Grid timeline transition doesn't open correct view

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#382]
Persistence
-when editing an item in the grid, specifically transitions, you leave the timeline editor, a new popup opens with transition settings, when you close that the timeline editor re-opens and your back in the List view of the media items within the timeline. The gird is meant to be quicker, i think, but with this in ability to keep your current state it's quite a bit slower.

**Comment by scienceworld** [comment]
I think this depends on the opening state of the timeline editor

if you open the timeline editor and its in list view, and you change to grid view then edit transitions you return to list view.

if you open the timeline editor and switch to grid view and close, when you re-enter you're automatically in grid view.  Then if you edit the transitions you return to grid view.

2 potential solutions.  
1)  save the layout state prior to going to a modal popup
2)  dont use a modal popup for transition editing.  stack the popup on top of the existing timeline editor, or edit transition in-line, so as to not leave the grid/list view altogether.  preferable.

**Comment by dasgarner** [comment]
it should already do 1, hence the bug. 2 is a bit more involved and would be a general enhancement to the way grids work (for a later release)

**Comment by dasgarner** [comment]
I can't recreate this issue at the moment - I have tried:

 1. Open the Layout Designer
 2. Edit a Region Timeline
 3. Opens with List View
 4. Select Grid View
 5. Select Edit Transition
 6. Save or Cancel
 7. Return to Grid View

What am I doing wrong to recreate the issue?

**Comment by scienceworld** [comment]
it did it for me again, but only the first time I did it.

1) design layout
2) click on edit time line
3) click on switch to grid
4) click on in transition from drop down
5) save
6) return to list view
7) repeat, and the symptoms do not re-occur.

must be a cookie or user preference non-initialization thing. can't repeat a second time.

**Comment by dasgarner** [comment]
The preference for whether to load the timeline or grid is stored in the User Session - so I suppose if the session gets blasted away for some reason it would default back to the List.

Sessions to occasionally get regenerated for security purposes, but I don't think that would do this very specific behaviour.

Don't suppose you have another tab open that might be loading the List?

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
