### ISSUE TITLE
Dataset: Styling rows based on data 

### ISSUE THREAD

**Issue by dkjain** [xibosignage/xibo#386]
Hi,
Is there any way individual rows can be styled based on the data/keywords in the cell. For example "if the data in a row contains particular keyword "Delayed" then fonts should be colored yellow. Like the one you see in public places such as Railways, Airports etc. Attached a sample screenshot.

thanks
dkj

Attachment:
![schedule_table](https://cloud.githubusercontent.com/assets/10743577/6479183/2fee8902-c267-11e4-96e7-aa95eb8a09e1.jpg)

**Comment by dkjain** [comment]
I have found a possible solution to custom  style rows based on data/keyword however it require use of Javascript as shown on this stackoverflow answer. The problem is where/how do i 
reference/add the required JS file so that dataset can use that file.

http://stackoverflow.com/questions/15740005/giving-custom-classes-to-each-td-for-styling-datatables-jquery

Can it be added inside the box titled "Stylesheet for the Table" input box enclosed within <script> tag? 

Thanks
dkj

**Comment by MedusaDelft** [comment]
That won't work. It is stylesheet information that will end up between <style>-tags. I guess we need an additional javascript box there.

**Comment by dkjain** [comment]
Hi,

Does anyone knows where and how to correctly include/reference "datatables.min.js" & "datatables.min.css" and put $(document).ready(function().......)  dataTables code in the right place inside modules/preview/HTMLtemplateforgetresour
ce.html

I am using CMS 1.6.4.

Thanks
dkj

**Comment by dasgarner** [comment]
I'm reluctant to include that library as standard as I think its overkill for any use case I can come up with?

As @MedusaDelft mentioned, its a simple piece of JavaScript that is required. We would need to modify the DataSetView module to support that.

**Comment by dkjain** [comment]
I think you are right and for the next release, it would be better if that's made a standard feature. Since the next release might not be soon, could you plz help me with that small piece of code and direction in which file to include it, it would really help out.

**Comment by dasgarner** [comment]
You'd need to edit `datasetview.module.php`, put your files to include in the "InstallFiles" method and then append those same files to the $headContent variable in GetResource (on around like 436).

Your script could be added to the existing document read function on line 452

**Comment by dkjain** [comment]
Hi,
I am using CMS 1.6.4 and there is no "InstallFiles" (it's in 1.7.1) method in datasetview.module.php. There is ofcourse a HTMLtemplateforgetresource.html while it's missing in 1.7.1.

**Comment by dasgarner** [comment]
Well in that case you would have to add the contents of both JavaScript files to the HTMLTemplate - there isn't any other way.

-------
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
