### ISSUE TITLE
font.css not being created on windows xibo player

### ISSUE THREAD

**Issue by veshant** [xibosignage/xibo#387]
I have added a few fonts to xibo.  On the web preview, it works fine.  But on the windows client, I see that the font files are downloaded and listed as 32.tff, 33.tff ... to 41.tff .  I see that in the html files, it refers to a font.css file.  However, the file is not being created.  I checked the info screen by pressing "i", but there are no errors listed and all the files are downloaded 100%.

**Comment by MedusaDelft** [comment]
This is a known issue. Please see issue #337 (and #211 nearly at the end).

**Comment by veshant** [comment]
Thanks.
