### ISSUE TITLE
xibo on Raspberry Pi 2

### ISSUE THREAD

**Issue by ketagrip** [xibosignage/xibo#388]
I have installed Ubuntu 14.04 on a Pi 2 and wanted to install the xibo 1.6 python client but the only install I can find is for Ubuntu 12.04.
will this change or has anyone been able to put older versions of Ubuntu on the Pi 2

**Comment by dasgarner** [comment]
We've discontinued the current [Ubuntu Player](http://xibo.org.uk/2014/12/15/xibo-for-ubuntu-alpha-discontinuation-notice/) and have started working on a new one: #29
