### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by datensysteme** [xibosignage/xibo#389]
using latest version, server and client both the same machine, windows 8,1

Layout contains 1 webpage 20 sec and one image 5 sec

Webpage comes, image comes, webpage comes, image comes 2 sec and client crash with return to desktop
on version 1.6.3. this configuration worked.Installing 1.7.x after deinstall client and remove complete server folder

**Comment by dasgarner** [comment]
Can you try [this exe](https://github.com/dasgarner/xibo-dotnetclient/blob/develop/bin/x86/Release/XiboClient.exe) and let us know if it improves?

**Comment by datensysteme** [comment]
sorry for the delay...

This exe cannot be installed on Windows 8, there is an Windows error immediatly after double click (in German: Dieses Programm funktioniert nicht mehr,English: This Software does not work any more)

May be I am not able to download it correctly (dont know how to do in github)

**Comment by xibo-de** [comment]
same here: size after download only 29 KB

**Comment by dasgarner** [comment]
You sure you aren't downloading the linked page instead of the file itself?

Try clicking the link and then selecting "Raw" to download the file.

**Comment by xibo-de** [comment]
Xibo Client 1.7.1 crahs constantly on different client PCs

with and without CEF browser

mostly just jumps back to the desktop and nothing in windows event viewer.

but this time with:

Anwendung: XiboClient.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund eines Ausnahmefehlers beendet.
Ausnahmeinformationen: System.OutOfMemoryException
Stapel:
   bei System.Drawing.Graphics.FromHdcInternal(IntPtr)
   bei System.Drawing.Font.GetHeight()
   bei System.Drawing.Font.get_Height()
   bei System.Windows.Forms.DataGridViewRow..ctor()
   bei System.Windows.Forms.DataGridViewRow.Clone()
   bei System.Windows.Forms.DataGridView.get_RowTemplateClone()
   bei System.Windows.Forms.DataGridViewRowCollection.AddInternal(Boolean,
System.Object[])
   bei System.Windows.Forms.DataGridViewRowCollection.Add()
   bei XiboClient.Log.ClientInfo.AddToLogGrid(System.String,
XiboClient.LogType)
   bei XiboClient.Log.ClientInfoTraceListener.Write(System.String,
System.String)
   bei XiboClient.Log.ClientInfoTraceListener.WriteLine(System.Object,
System.String)
   bei System.Diagnostics.TraceInternal.WriteLine(System.Object,
System.String)
   bei XiboClient.Video.Dispose(Boolean)
   bei System.ComponentModel.Component.Finalize()
--------------
Name der fehlerhaften Anwendung: XiboClient.exe, Version: 2.0.0.0,
Zeitstempel: 0x54f1c816
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 6.1.7601.18409,
Zeitstempel: 0x531599f6
Ausnahmecode: 0xe0434352
Fehleroffset: 0x0000812f
ID des fehlerhaften Prozesses: 0x77c
Startzeit der fehlerhaften Anwendung: 0x01d059e863b98402
Pfad der fehlerhaften Anwendung: C:\Program Files\Xibo Player\XiboClient.exe
Pfad des fehlerhaften Moduls: C:\Windows\system32\KERNELBASE.dll
Berichtskennung: 7cae633c-c63f-11e4-a85b-d02788a23017

**Comment by dasgarner** [comment]
We can't diagnose further until you have tried with the EXE I linked

**Comment by xibo-de** [comment]
Right click and save did not work but it works with RAW

I have it now and i test it

Thanks

**Comment by datensysteme** [comment]
sorry, click on raw downloads a XiboClient.exe with 1,11 MB. IE and Firefox. 
Not installable.

**Comment by xibo-de** [comment]
google chrome worked

**Comment by xibo-de** [comment]
With the exe from above:

Using CEF: 24h without problems

**Comment by xibo-de** [comment]
With the exe from above:
2 PCs, the screenshot function no longer works, goes only once

**Comment by datensysteme** [comment]
I am still NOT ABLE to download this exe. FileSize 1,11 MB, not installable

**Comment by dasgarner** [comment]
I've rebuild it and pushed it - but I really dont know what it doing on...

Just navigate to this page: https://github.com/dasgarner/xibo-dotnetclient/blob/develop/bin/x86/Release/XiboClient.exe

And click "Raw" to download the file.

**Comment by datensysteme** [comment]
excuse forthe Troubles....
I click on RAW and get a XiboClient.exe with 1.167.872 Bytes (like several times before)

This is what I get on double click:
![screenshot](https://cloud.githubusercontent.com/assets/11315109/6593939/21389b98-c7dd-11e4-8745-b9065e34f2ce.png)
I think 1,1 MB is too small for a XiboClient.
Erasing temp IE files brings no solution

**Comment by dasgarner** [comment]
You are replacing the EXE with the EXE you already have in your installation? It won't run standalone - it needs to be copied over the top of an existing install.

**Comment by xibo-de** [comment]
just downloaded and works
gerade runtergeladen und funktioniert

![eigenschaften](https://cloud.githubusercontent.com/assets/10655684/6594127/b897cb16-c7de-11e4-8801-8bfcb0706acc.jpg)

**Comment by xibo-de** [comment]
With the exe from above:

Using CEF: 66h without problems

test continues ...

**Comment by datensysteme** [comment]
If you had said that only the exe in the installation directory has to be replaced, then the test would have gone faster

Test in Progress, works by now

What we test: Website and Image changing all 10 sec

**Comment by xibo-de** [comment]
can you test the screenshot function ?

**Comment by datensysteme** [comment]
allthough I do not need this Funktion, i tried it by "Screenshot anfordern". 
Effekt after Client restart: Client Crash like before
No solution by copying the new Client again.
I have to start from the beginning.....

**Comment by dasgarner** [comment]
Sorry - we recently moved community support to [community.xibo.org.uk](http://community.xibo.org.uk)  - I have probably been a bit fast switching to a "developer" mode in here, hence the short instructions about replacing the EXE.

I think that the original problem is solved? There may be an issue with screenshots - but we can discuss that in a new topic on [community.xibo.org.uk](http://community.xibo.org.uk)
