### ISSUE TITLE
Change order of options to delete item timeline

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#395]
Dan, I'm honestly ashamed to open up this request.
I realize que the natural user to remove the timeline of the item is to click OK to delete, And Then, without looking at the options.

This created a serious their situations such as file volume in the library, Causing the performance problem That We Mentioned in the paging.

The two requests I made about deleting files and files of users do not use.

My analysis is que the simple change of the ordination of combobox options would help, and this routine add and remove items.

It may be an immature opinion, but I see que user is a special being of nature still unknown! lol

1 - Delete this Media
2 - Unassign from this region and remove
3 - Unassign from this region only

This is possible or believes it unnecessary?

**Comment by dasgarner** [comment]
I don't see any reason why we couldn't re-order those.

I suppose we need to be careful when we consider future developments (like playlists), which will make the link between media and widgets (items on the playlist / region) even more detached.
