### ISSUE TITLE
Display add issue

### ISSUE THREAD

**Issue by manish1987** [xibosignage/xibo#397]
Running xibo1.6 on ubuntu 12.04. I have same 5 client and i configure with server address and xmds key.
But when i login in to server side at the Display it is show me only 1 display and IP address randomly change with my 5 client machine. And what ever i run layout it is run on all 5 display. how can i add one by one display i need to run all the display different layout. any one can help me on this

**Comment by dasgarner** [comment]
You need to make sure the clientID (hardware key) on each player is different. You can adjust that in the CFG file.
