### ISSUE TITLE
Database problems in the setup wizard

### ISSUE THREAD

**Issue by nspaul** [xibosignage/xibo#398]
When I go through the installation wizard, I can't get past the database setup page. If I choose "Create a new database" and give it all the info, it does indeed create the database and the user, but I get the following error at the top of the screen:

```An error occurred populating the database. Statement number: 90. Error Message = [SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '82, 'LIBRARY_MEDIA_DELETEOLDVER_CHECKB','Unchecked','dropdown','Default the chec' at line 1]. File = [Array]. SQL = [(82, 'LIBRARY_MEDIA_DELETEOLDVER_CHECKB','Unchecked','dropdown','Default the checkbox for Deleting Old Version of media when a new file is being uploaded to the library.','Checked|Unchecked','defaults',1,'Default for "Delete old version of Media" checkbox. Showen when Editing Library Media.','dropdown','',50,'Unchecked',1)].```

If I use the "Use an existing database" option, I get this error:

```An error occurred populating the database. Statement number: 56. Error Message = [SQLSTATE[HY000]: General error: 1005 Can't create table 'xibo.#sql-6a46_89' (errno: 121)]. File = [Array]. SQL = [ALTER TABLE `blacklist` ADD CONSTRAINT `blacklist_ibfk_1` FOREIGN KEY (`MediaID`) REFERENCES `media` (`mediaID`), ADD CONSTRAINT `blacklist_ibfk_2` FOREIGN KEY (`DisplayID`) REFERENCES `display` (`displayid`)].```

Is there something wrong with my MySQL installation, or is this something wrong with the xibo wizard?

**Comment by dasgarner** [comment]
Please make sure you are using the official release download - that code is from the development branch which hasn't been tested yet.
