### ISSUE TITLE
Xibo doesn't get past login screen V 1.7.1

### ISSUE THREAD

**Issue by sjfraser** [xibosignage/xibo#399]
Hello,

I have a fresh install of xibo 1.7.1 cms .  When I use my browser to go to the site xibo.example.com I get the login page.  When I put in the username and password the screen flashes and I am back at the login screen this time with a new url showing in the address bar xibo.example.com/index.php?p=index

When I check the database, every time I try to login I get a new entry in the sessions table.  I have tried truncating the table and then when I login I get a "This session has expired" message when I try to login again from that page it stays on the page.  When I truncate the table and then login it creates a row with lastpage set to login, then I get a new record each time I click on login with the lastpage column having a value of index. Each row has a unique session_id.

I am currently using CentOS 6.6 with php 5.5.22 , (And I have previously tried CentOS 6.6 with the native php 5.3.3) I haven't been able to get either to work, they both have the same result.

If anyone has any idea of what may need tweaking I would greatly appreciate it.

Thank you,
Shawn Fraser

**Comment by dasgarner** [comment]
Do you have cookies enabled in your browser?

It sounds like your browser is sending a new session id with each request

**Comment by sjfraser** [comment]
Thank you for pointing out the issue.  I deleted my firefox profile and it now works.  

Thanks !
Shawn
