### ISSUE TITLE
LayoutRegionMediaDetails API Call throwing 500 Error in 1.7

### ISSUE THREAD

**Issue by MichaelHoughton** [xibosignage/xibo#40]
When calling the API, the method: LayoutRegionMediaDetails is throwing a 500 error.
![screenshot from 2015-01-23 15 54 44](https://cloud.githubusercontent.com/assets/5341149/5877628/bd0edb02-a318-11e4-8a12-4a8f23b7b1b4.png)

This worked fine in 1.6.4.

Would you be able to test it at your end and see if it works?

Thanks again.

**Comment by dasgarner** [comment]
I've not had the opportunity to test it yet, but I think the attached commit will solve it. Just about to pull that into develop branch.

**Comment by MichaelHoughton** [comment]
Thanks Dan, this has fixed it :)

**Comment by dasgarner** [comment]
Great!

I can feel some re-factoring coming on for the next version :)

**Comment by MichaelHoughton** [comment]
Hey @dasgarner - not sure if you have Unit Tests in place, but for this sort of stuff, it would be a big help.  Means you can run the tests and see what is broken without needing to re-test the whole application.

**Comment by dasgarner** [comment]
Well, that is a good point - no, there aren't any unit tests as such and yes there should be. There have been pressing demands to get 1.7 out, which has taken priority. We do have a python api test library started and we do have the bones of a webdriver based UI testing suite - but they are miles away from complete.

1.8 will be quite a big re-factor where we will pull the XLF into the data model, which means representing regions and media in the DB. That will allow us to support playlists that are reusable across many layouts, and even dynamic playlists.

This means a lot of the core code needs re-factoring - we plan to use a far more OO approach (keep in mind some of the current code is from 2005!) with objects to represent each of the items we are interested in, with factory classes to get and fetch them, etc. At this point I will be adding unit tests (if you have good suggestions for a framework, then please let me know).

**Comment by MichaelHoughton** [comment]
Hey Dan

This all sounds good.  Overall, the code is good, it can just get very complex in parts!

I don't know about frameworks for unit testing, but myself, I am a CakePHP developer - though in terms of general frameworks, there are many good ones.  Given the complexity of the database set up, any framework with a good ORM would make life a lot easier (no more writing SQL!), so I would say CakePHP, Laravel or Yii frameworks would be the ones to consider.

**Comment by dasgarner** [comment]
Rewriting into Laravel is something i've looked at - but it would represent an enormous body of work :-)

I'm thinking that PHPUnit would be the best choice, but of course will do some more research when the time comes!
