### ISSUE TITLE
Enhancement: Refresh screen only when there are updates on Winodws client

### ISSUE THREAD

**Issue by veshant** [xibosignage/xibo#400]
The windows client refreshes and there is a brief second where the modules disappear then reapear.  The screen every 60 seconds, because that is the duration I set, but it would be preferred if it only refreshed when there are any updates.  Even when there are no changes made, the screen refreshes.  Would like to see this fixed.  Thanks for the great software anyways.

**Comment by dasgarner** [comment]
This is the way Xibo works - it is not something to "fix". Your layout is coming to an end and the next layout is being loaded (happens to be the same one in your case).

If you don't want that to happen, put the duration up.
