### ISSUE TITLE
Can not install on AWS

### ISSUE THREAD

**Issue by jimboobrien** [xibosignage/xibo#405]
Hey guys, 

I'm a web developer, and I mostly work with Wordpress. 

I have been using Xibo and like it as my digital signage CMS. 

I have been trying to move my install to Amazon web services, but because of the way your install  is set up I cannot figure out how to get it to install on a LMAP stack. 

Any ideas or help? I'm not interested in purchasing cloud hosting from Xibo.

- Jim

**Comment by dasgarner** [comment]
I've personally never done it, sorry

**Comment by jimboobrien** [comment]
Xibo provides Cloud Hosting. Therefore it can be done. Do the devs at Spring Signage take care of those instances? Why is there no documentation on how to use cloud platforms yourself?

Can I help in creating the documentation for this? I have gotten about 90% through the AWS setup, but can't get the install script to start. 

- Jim

**Comment by nagyrobi** [comment]
What do you mean by "cannot figure out how to get it to install on a LMAP stack"?

I moved the running Xibo CMS from one Ubuntu machine to another very easily.
- installed phpMyAdmin, took a backup of the Xibo database
- made a backup of the /var/www/html directory (this is where I had the CMS php files installed at)
- made a backup of the library directory (in my case this way /var/www/xibosomething)
- copied all these to the new machine, kept all the paths the same
- with phpMyAdmin on the new machine restored the database from backup
- also with phpMyAdmin assigned manually permissions to a new database user with a password, and updated it manually in Xibo's config file
- checked the directory permissions on the new machine to be all correctly accessible by the web server user.

**Comment by jimboobrien** [comment]
First of all i meant LAMP stack. 

I'm not trying to MOVE and install. 
I want to start fresh with a brand new install of Xibo. 

I have a LAMP stack on AWS and I ssh into the instance, upload the xibo tar, unzip it and then go to (ip address)/xibo to start install and I get nothing....

I can get wordpress to install no problem, but I just cant get the Xibo install script to start.

Any ideas?

- Jim

**Comment by nagyrobi** [comment]
are you sure it unzips to the correct path? Is the LAMP stack properly configured to parse php in that path? How about unzipping directly to the web root?

**Comment by andyblackham** [comment]
Jim, there are a lot of pre-requisites for Xibo to work.  Do you have them all?

what OS are you using?

**Comment by dasgarner** [comment]
> Xibo provides Cloud Hosting. Therefore it can be done. Do the devs at Spring Signage take care of those instances? Why is there no documentation on how to use cloud platforms yourself?

You are making a big assumption here about what we have used to configure our service - we don't run on AWS and have never run on AWS, hence I don't know how to help you set it up.

Xibo can be installed on a LAMP stack and there are [clear instructions](http://xibo.org.uk/manual/en/install_cms.html) on how to do so. You may decide to use a VPS, such as Digital Ocean and there are instructions for that [here](https://www.digitalocean.com/community/tutorials/how-to-install-xibo-on-ubuntu-12-04).

As for why there isn't more documentation - perhaps you'd like to write up your experience once you get it working? And we can include it as a FAQ on our [community site](https://community.xibo.org.uk)?

**Comment by jimboobrien** [comment]
Hey guys,

I may not have the right permissions on the files in the instance. I'll go chown them later and see if that was my problem. Here is a list of commands I ran when I started the instance:

how to prepare instance:

sudo yum update

sudo su

yum install httpd

service httpd start

yum install php php-mysql

yum install mysql-server

service mysqld start

mysqladmin -uroot create myblog

mysql_secure_installation

- don't enter password for root -

y
y
y
y

- I did this process with and without the mysql-secure-installation - 

cd/var/www/html

wget https://github.com/xibosignage/xibo-cms/archive/1.7.1.tar.gz

tar -xfvz 1.7.1.tar.gz

- unzip to xibo folder -

- Navigate to XXX.XXX.XXX.XXX/xibo -

**Comment by andyblackham** [comment]
Hi - looks like you have a redhat / centos / fedora type platform.

have a look here:
https://github.com/xibosignage/xibo/issues/263

there are a lot of yum packages to install.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
