### ISSUE TITLE
Advanced - 500 Internal Server Error

### ISSUE THREAD

**Issue by cgslaughter** [xibosignage/xibo#406]
I have Xibo 1.6.3 installed and running for a while. Suddenly when trying to access "Advanced" (index.php?p=log&), the browser spins for a while and then produces 500 Internal Server Error. I thought that maybe the log file was too large, so I deleted the log file, but still have the same problem. Everything else on the server and in Xibo seems to be working fine. Windows Server 2012 logs also document the 500 Internal Server Error, but give no information as to what the problem was. Has anyone else experienced this? Can anyone help trace down in Xibo what is happening?

**Comment by dasgarner** [comment]
Its the log table, rather than log file.
``` sql
TRUNCATE TABLE `log`;
```
