### ISSUE TITLE
Client 1.7.1 closes unexpectedly

### ISSUE THREAD

**Issue by JanTee** [xibosignage/xibo#408]
After we updated to Xibo client 1.7.1 we have problems with freezing or shut down of the client
we run xibo client on a wireless win 7 home ed sp1
earlier client 1.6.3 worked day and night without problems
Any clue to why they behave this way
Maybee serverrelated becase they all go down at the same time

**Comment by pmeagher** [comment]
I read somewhere that it had to do with IE "leaking" memory, becoming bloated and crashing. I am having the same issue with a couple of my clients and am trying the solution listed in #36; I am trying to use the CMF browser rather than IE.  I have yet to see issues, but it has only been an hour.

**Comment by stevepmitchell** [comment]
This has happened to me on two different displays, both using CMF browser.  It has happened 4 times on two of these displays in the last two days.  

I am rolling back to 1.7.0 as these are in production.  Any suggestions appreciated.

**Comment by dasgarner** [comment]
We've done a lot of work on this over the last few weeks... in particular we have taken steps to completely disable CEF if it is switched off and to fix other memory leaks in the code that have "for some unknown" reason started to be a problem.

You can try the [exe](https://github.com/dasgarner/xibo-dotnetclient/blob/develop/bin/x86/Release/XiboClient.exe) from my development branch, which we hope to test, merge and release by early next week,

**Comment by stevepmitchell** [comment]
I have confirmed that disabling CEF stops the crashes.  Unfortunately, we chose Xibo because of the better web rendering available via Chrome.  IE rendering is OK, but we can get that level of quality from other signage systems.  

Hopefully this will be addressed sometime soon.

We have also rolled back to 1.7.0 until we do more testing.

**Comment by dasgarner** [comment]
1.7.0 has all the same issues a 1.7.1 did (if not more). What we have now will most likely be released as 1.7.2 and then we will look at the CEF issues and see if we can come up with a sensible way to integrate that without crashes.

**Comment by stevepmitchell** [comment]
1.7.1 without CEF still crashes.  5 displays died last night at random times.  
1.7.0 does not. I'm going back (again) on all of my displays.

**Comment by JanTee** [comment]
Comment to dasgarner
"You can try the exe from my development branch, which we hope to test, merge and release by early next week,"

I have tried the EXE from development, and finds it to solve my problem
Screen one has the new EXE, works perfektly, no shutdown
Screen 2-6 still old EXE, keeps closing, so now i will try on all screens
Looks promising

**Comment by dasgarner** [comment]
> 1.7.0 does not. I'm going back (again) on all of my displays.

I have no idea why that would be the case, but if 1.7.0 works for you then by all means stick to it. 1.7.2 has been released now, which is essentially 1.7.1 with a few extra tweaks.

**Comment by dasgarner** [comment]
@JanTee great! sounds like we might have it then!
