### ISSUE TITLE
Add logo Ticker source

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#41]
The ticker functionality is spectacular, helps users and can enter more interesting content from sources outside the system.

Currently use a region in front of the ticker region to insert an image. The image of the logo of the ticker provider.

When we have multiple tickers and different news providers, starts to get complicated.

Inform the duration of imagems, to synchronize with the duration of the ticker...lol

My request is the ticker configuration screen, include a field image logo ticker. If the image is inserted, we allow the user to enter in front of the ticker when it is displayed in the designer and display.

What do you think?

**Comment by laercionit** [comment]
![ticker-logo-example](https://cloud.githubusercontent.com/assets/325662/5885265/c9da4a00-a350-11e4-8ba4-ed518bad301e.JPG)

**Comment by dasgarner** [comment]
Yes, great idea. 

This would actually be handled by this: https://github.com/xibosignage/xibo/issues/21
