### ISSUE TITLE
New User Groups: Error getting users

### ISSUE THREAD

**Issue by SiegfriedP** [xibosignage/xibo#411]
When I make a new User Group and try to open the members page to assign users, I get "Error getting users".

Under Advanced - Log I find:

293627 2015-03-09 15:54:37 CMS group  <errormsg>Error getting users</errormsg>
 <errornum>256</errornum>
 <errortype>User Error</errortype>
 <scriptname>/var/www/lib/pages/group.class.php</scriptname>
 <scriptlinenum>718</scriptlinenum>
 
293625 2015-03-09 15:54:30 CMS   <errormsg>Undefined variable: type</errormsg>
 <errornum>8</errornum>
 <errortype>Notice</errortype>
 <scriptname>/var/www/lib/service/xmdssoap4.class.php</scriptname>
 <scriptlinenum>932</scriptlinenum>
 
293623 2015-03-09 15:54:30 CMS   <errormsg>Undefined variable: type</errormsg>
 <errornum>8</errornum>
 <errortype>Notice</errortype>
 <scriptname>/var/www/lib/service/xmdssoap4.class.php</scriptname>
 <scriptlinenum>932</scriptlinenum>
 
293621 2015-03-09 15:54:30 CMS   <errormsg>Undefined variable: type</errormsg>
 <errornum>8</errornum>
 <errortype>Notice</errortype>
 <scriptname>/var/www/lib/service/xmdssoap4.class.php</scriptname>
 <scriptlinenum>932</scriptlinenum>
 
293619 2015-03-09 15:54:30 CMS   <errormsg>Undefined variable: type</errormsg>
 <errornum>8</errornum>
 <errortype>Notice</errortype>
 <scriptname>/var/www/lib/service/xmdssoap4.class.php</scriptname>
 <scriptlinenum>932</scriptlinenum>
 
293617 2015-03-09 15:54:30 CMS   <errormsg>Undefined variable: type</errormsg>
 <errornum>8</errornum>
 <errortype>Notice</errortype>
 <scriptname>/var/www/lib/service/xmdssoap4.class.php</scriptname>
 <scriptlinenum>932</scriptlinenum>

**Comment by dasgarner** [comment]
We are moving discussion and support over to [community.xibo.org.uk](https://community.xibo.org.uk), so we would appreciate you asking on there in future.


This is reported and fixed in #356
