### ISSUE TITLE
upgrade ubuntu client to 14.04 LTS

### ISSUE THREAD

**Issue by danielzzz** [xibosignage/xibo#416]
hi, It seems that the current ubuntu client is limited to ubuntu 12.04 which is going out of support soon. 
do you have any plans for 14.04 support?

best, dan

**Comment by alexharrington** [comment]
Hi Dan

Development is discontinued on that client. Please see the notice on the website:
http://xibo.org.uk/2014/12/15/xibo-for-ubuntu-alpha-discontinuation-notice/

Work has already started on a new codebase which will run on Ubuntu 14.04, but there's no fixed timescale for that at present.
