### ISSUE TITLE
RSS Feed Not working

### ISSUE THREAD

**Issue by splist** [xibosignage/xibo#419]
System: Windows CSM 1.7.1, Windows client. 1.7.1 

When using the RSS Feed ticker nothing shows up. there is no text in the Layout Designer, no text in the layout preview, and nothing in the Client Display. I believe i have tried everything in the previously mentioned issues. 

The RSS feeds used to work with 1.6.4

Any help is greatly appreciated.

**Comment by alexharrington** [comment]
Are these HTTPS feeds? Perhaps check you've got CURL setup properly if they are:
https://community.xibo.org.uk/t/using-tickers-and-other-external-resources-over-https/46

**Comment by splist** [comment]
I have checked the Feeds that I am using, and none of them are HTTPS feeds

**Comment by alexharrington** [comment]
Is there anything logged showing there's a problem fetching the feed? Is your CMS behind a proxy server (and if so, have you configured the proxy settings in the CMS settings?).

In 1.6 series the clients fetch RSS feeds themselves. From 1.7 onwards the CMS collects and parses the RSS feeds and distributes the feeds to the clients - so if your CMS can't see the feed then nothing will work.

**Comment by splist** [comment]
I have enabled auditing on the logs but they are empty i don't think they settings are being saved for my logging, i am not behind a proxy server. I have manually opened the RSS feeds on the CMS as well.

**Comment by alexharrington** [comment]
If you have debug/audit set on then there should be loads of things in the log. Perhaps there's a problem writing to the log table on your database - a crashed table maybe?

**Comment by splist** [comment]
To make sure I am looking in the right place for the log: it is in the CMS under Advanced - Log correct.

**Comment by alexharrington** [comment]
Yes. You'll need to adjust the filter to show you all logs from the last 300 seconds or so I would think.

Alternatively use the Report Fault wizard in the CMS. When it asks you to recreate the problem, go and edit the layout and edit the RSS feed, then once edited preview the layout and then go back to the wizard.

That will give you a troubleshoot.txt file with any logs inside it. Have a look through and see what's in there.

**Comment by splist** [comment]
I ran the Report fault Wizard and there was nothing in the troubleshoot.txt file of use. only all modules and my session info at the bottom of the file. I looked at my log table and it is full of data 835 MiB, just not displaying in the CMS so I'm not sure where to go now..

**Comment by alexharrington** [comment]
What's the feed URL you're trying to use and how have you got it setup?

It does sound as if there's some issue seeing the database however if you can't get any log information to show in the CMS regardless of selecting all the options to show everything in the log filter.

**Comment by splist** [comment]
Here is what the RSS Feed: http://www.nhl.com/rss/news.xml
General: 30 seconds per item Marquee Down
Appearance is: Image Overlaid with the Feed Content on the Left
Format: Speed 2  text direction LTR  Number of Items 14    items per page 1  take items from the start of the feed
Duration is per item
 update Interval 5 min

This error is shown with debugging on in the Layout Preview: Fatal error: Using $this when not in object context in D:\xampp\htdocs\xibo\lib\data\file.data.class.php on line 212

**Comment by alexharrington** [comment]
In that case I'd say your library location isn't writable

Make sure that the user your webserver runs as has access to write to your
library directory.

That should be logging an error but it's failing to do so, so I'll mark
that up as a bug.

**Comment by alexharrington** [comment]
https://github.com/xibosignage/xibo-cms/blob/develop/lib/data/file.data.class.php#L212

**Comment by splist** [comment]
That did the trick, odd it was writable with 1.6.4, thanks for all of your help.
