### ISSUE TITLE
1.7 - Scheduling Translations Missing - PT-BR

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#42]
In the scheduling screen, identified some items that are not translated to Portuguese of Brazil

I will use this bug to list items for translation PT-BR be allowed to act this way.
If you accept, could change the name to bug Translations Portuguese-Brazil Missing.
![capturar](https://cloud.githubusercontent.com/assets/325662/5885405/5044e580-a353-11e4-8478-5db1482cb31b.JPG)

**Comment by dasgarner** [comment]
As it happens all of those strings are translatable in the latest repository. Once I hook up an automatic import into Launchpad Translations you will be able to go in and translate those for yourself.

I'm going to pull in the xibo-cms develop branch for translation in Launchpad (we will still use Launchpad for Translations as that seems to be the best system available).

**Comment by laercionit** [comment]
Dan, just upgraded my test environment with the 1.7 final version.
Do not see the translations correctly.

**Comment by dasgarner** [comment]
They haven't been translated by anyone yet: https://translations.launchpad.net/xibo/github/+pots/default/pt_BR/+translate?batch=10&show=all&search=Year

**Comment by laercionit** [comment]
What do you want me to translate?

*Laercio Junior*
Cel./Pessoal: (21) 99162-7440
Email Pessoal: laercionit@gmail.com
MSN: laercionit@hotmail.com
Skype: laercionit



2015-01-26 18:38 GMT-02:00 Dan Garner <notifications@github.com>:

**Comment by dasgarner** [comment]
We import all of our translatable strings into Launchpad and then community contributions are used to complete the translations.

The pt_BR translation is here: https://translations.launchpad.net/xibo/github/+pots/default/pt_BR/. Any help you can provide translating into Brazilian would be most appreciated.

At any point you can request an export of the translations, call the file `pt_BR.mo` and copy it into your locale folder and the translation will automatically be adopted by the CMS.
