### ISSUE TITLE
Support and Discussion moved to community.xibo.org.uk

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#423]
We have moved all discussion and support to http://community.xibo.org.uk, please update your bookmarks!

You can sign in with your GitHub ID - so those of you that created one specially for Xibo can still use it.

This issue tracker will now be for **verified issues only**, these are issues previously discussed on community.xibo.org.uk.

New support/discussion type issues will be asked to repost in the new area.

Thanks,
Dan

#332

**Comment by alexharrington** [comment]
Bump
