### ISSUE TITLE
Manage Membership - Error Getting Users

### ISSUE THREAD

**Issue by fward1208** [xibosignage/xibo#425]
![error](https://cloud.githubusercontent.com/assets/11433306/6610600/0551bb16-c838-11e4-914d-4ecd682fb324.jpg)
I reviewed and applied the fix for #356, but this only resolve the ability to retrieve the users list when opening the new group. When trying to assign users to the group I get the same error message.

**Comment by dasgarner** [comment]
Could you try the above commit?

**Comment by fward1208** [comment]
It resolved the issue. Thanks for the help.
