### ISSUE TITLE
Simple change of ownership on Layouts

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#429]
Implement a very simple change of ownership on Layouts where you can select a Layout and update the owner to a different user.

This function could be used as a 2 step process for deleting a user who has dedicated access to a Layout (often the case with service providers - they create a layout owned by the admin and give a user edit access).

**Comment by laercionit** [comment]
Just to complement the functionality, I think important to change the owner of the layout and the REGIONS for the new user.

**Comment by dasgarner** [comment]
That would be out of scope for this simple change (remember this is only to facilitate the delete action)

**Comment by PeterMis** [comment]
It is tested and fine
