### ISSUE TITLE
1.7 Options remove items timeline grid 

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#43]
Options remove items timeline grid

When selecting the timeline to remove an item, appears the following options:
Remove the Region
Remove the region and Retire
erase Media

These options could be listed also in the timeline of the grid for mass action on the items.

I think relevant
![capturar](https://cloud.githubusercontent.com/assets/325662/5885438/fff0d5fc-a353-11e4-9448-4942ca6a2ffd.JPG)

**Comment by dasgarner** [comment]
Implement in #556
