### ISSUE TITLE
webpage is not the same as original website

### ISSUE THREAD

**Issue by sleffu** [xibosignage/xibo#435]
I have my website http://www.uffels.nl/index.php/svb1. I have edited the css yesterday. Only the webpage on the xibo client is showing the original css from the website. Is it a problem with cache? I cannot solve the problem.

**Comment by alexharrington** [comment]
The Player will obey the cache control directives your server sends and hold things like CSS in cache for the appropriate duration. You'll need to clear the cache in Internet Explorer and optionally adjust your webserver to send shorter cache TTLs for things like CSS if quick updates are important to you.

Additionally, community support has moved over to https://community.xibo.org.uk so if you have further support requests that would be the appropriate place to post them. Github issues is now exclusively for confirmed bugs already discussed on the Community site.

Best wishes
Alex
