### ISSUE TITLE
Error while Installation. Statement number: 89

### ISSUE THREAD

**Issue by alejleva** [xibosignage/xibo#439]
Hello, 
Any idea as of why I get that error ? I'm new to PHP. I was trying to create a new database. 
Thank you.
Beginning of the error: 

"An error occurred populating the database. Statement number: 89. Error Message = [SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'ordering' at row 62]. File = [Array]. SQL = [INSERT INTO `setting` (`settingid`, `setting`, `value`, `fieldType`, `helptext`, `options`, `cat`, `userChange`, `title`, `validation`, `ordering`, `default`, `userSee`, `type`) VALUES (1, 'MEDIA_DEFAULT', 'private', 'dropdown', 'Media will be created with these settings. If public everyone will be able to view and use this media.', 'private|public', 'permissions', 1, 'Media Permissions', '', 20, 'private', 1, 'word'), (2, 'LAYOUT_DEFAULT', 'private', 'dropdown', 'New layouts will be created with these settings. If public everyone will be able to view and use this layout.', 'private|public', 'permissions', 1, 'Layout Permissions', '', 10, 'private', 1, 'word'), (3, 'defaultUsertype', 'User', 'dropdown', 'Sets the default user type selected when creating a user.\r\n"

**Comment by dasgarner** [comment]
This appears to be a bug.

Line 275 of `lib/install/master/data.sql` should read:

``` sql
(83, 'LIBRARY_MEDIA_DELETEOLDVER_CHECKB','Unchecked','dropdown','Default the checkbox for Deleting Old Version of media when a new file is being uploaded to the library.','Checked|Unchecked','defaults',1,'Default for "Delete old version of Media" checkbox. Shown when Editing Library Media.', '', 50, 'Unchecked', 1, 'dropdown'),
```

**Comment by alejleva** [comment]
Thank you but how do you fix the issue? The line 275 for me is number (82). (83) is line 276. I replaced line 276 with the new one but the error is still there.

**Comment by dasgarner** [comment]
Please follow the instructions exactly :smile: the numbers to the left side are pure co-incidence

**Comment by alejleva** [comment]
Got the new file but the error is still there.
Pastebin of the error: http://pastebin.com/wpDzFR7P

**Comment by dasgarner** [comment]
I've commented in the commit - you still have the old file
