### ISSUE TITLE
Improve Black List Functionality so that Black Listed videos are easy to see

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#44]
Show the midiaid the timeline and grid helps the user to not have to go in the library could to identify which video is in blacklist. Basically an adjustment aiming usability and maintenance.

**Comment by PeterMis** [comment]
Blacklist was revamped in 3.1.0-alpha, details can be found here - https://github.com/xibosignage/xibo/issues/2529.
With that, I will close this issue.
