### ISSUE TITLE
Default user screen filter and show

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#442]
In layouts and media, we have by default the display of items that are active. Items that are retired are not displayed, only using the filter function.

We could standardize this screen following the usability of the parts of the system model.

![image](https://cloud.githubusercontent.com/assets/325662/6723293/97d5f9b6-cdc4-11e4-8161-558ce0d62ab1.png)

**Comment by dasgarner** [comment]
> We could standardize this screen following the usability of the parts of the system model.

What do you mean? It is desirable to hide the retired objects (this is true throughout the UI)

**Comment by laercionit** [comment]
Hello Dan, the user screen is not the combobox Retired, I inserted the image to illustrate.
Where are shown on the screen only users who are active, although there is the retired column. To mark the user as retired, there is no show or select that user again for activation. Sorry, I think my reference image was very good, and confused him.

**Comment by dasgarner** [comment]
I understand now - you want the retired filter **added** - it doesn't currently exist.
