### ISSUE TITLE
Error set Users Retired

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#443]
When we mark a user as he retired some user list, no longer can view or reactivate the user. Only through the database you can undo the action.

![image](https://cloud.githubusercontent.com/assets/325662/6723320/01bec5f6-cdc5-11e4-8617-14b944e751a9.png)

**Comment by dasgarner** [comment]
You just show retired users in the filter?

**Comment by laercionit** [comment]
Dan, I found relevant break in two different issues.

A related display of the grid and filter and the other with respect to define a user to retired

https://github.com/xibosignage/xibo/issues/442
https://github.com/xibosignage/xibo/issues/443

**Comment by dasgarner** [comment]
OK, will mark this as duplicate of #442
