### ISSUE TITLE
Android Display Sync

### ISSUE THREAD

**Issue by mymactek** [xibosignage/xibo#445]
Hello,

Is it possible to sync a couple of the android screens ? Like playing a display wall, or multiple displays on one wall...and need it to play certain videos at the same time ( per say a Jet flying through them ). 

Thanks, let me know.

**Comment by dasgarner** [comment]
It is not possible i'm afraid, although would be an interesting technical challenge!

Please discuss things like this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
