### ISSUE TITLE
Two Marquees Duplicating

### ISSUE THREAD

**Issue by ChrisTheMeat** [xibosignage/xibo#447]
Hello:

I have two marquees on the same layout.  One is Marquee Up and the other is Marquee Left.  They both have different content.  When I do a Preview Layout, everything appears correctly, however when I have the client running on another machine, both fields display the same content from the Marquee Left region.  If I change the Marquee Up region to static instead of Marquee, the correct text is displayed, but not scrolling up as I would like.  Any idea what may be causing this issue?

**Comment by dasgarner** [comment]
Please discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
