### ISSUE TITLE
URI formats are not supported

### ISSUE THREAD

**Issue by jvargasfeliz** [xibosignage/xibo#448]
hello people,
I´m trying to run xibo-client over a windows 7 machine. I have xibo cms in ubuntu as a server and my windows pc has connection with the server. 

I put the address of my server, the key of my sever and the address of my library. All of these are ok.
When I click on save it shows me a message (display is active and ready to start) thats mean the configuration are ok too. (I have already gave permission over the server to the display).
The matter is when I click on Launch client it shows me an error that says URI formats are not supported and Its doesnt work. 

Can u please help me!

Pos: sorry for my reading part.

**Comment by dasgarner** [comment]
Please discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
