### ISSUE TITLE
Added Fonts not in the Editor

### ISSUE THREAD

**Issue by MichaelSchmidts** [xibosignage/xibo#449]
I have added a New Font. But it is not in the Editor. I have already cleaned my browser cache and i have used some other browser. But it doesnt work... I use Version 1.7.2. Server Ubuntu 14.04.2.
Can somebody help me

**Comment by dasgarner** [comment]
Please discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
