### ISSUE TITLE
Improved disk space quota

### ISSUE THREAD

**Issue by laercionit** [xibosignage/xibo#45]
This functionality would be very interesting for companies and administrators who use the tool.

We Could have the functionality to set quota of disk space per user and per user group. We currently have the option just by CMS (some or not), I think they are complementary.

This would help in stimulating the user uploads content to clean que que items are no longer used in Their display case.

Whenever the screen upload content Appears, We Could present the user quota and how much he has used and available to perform the upload.

We Could be related to an item in the library statistics, where he had his share of viewing, used space, available space and splits for each media type for each percentage.

What do you think?

We currently have a quota of disk space for the entire system sharing this Among all users share.

**Comment by laercionit** [comment]
Dan, this item could be scheduled for release 1.7.2 with investment in development? If so, could you tell me the cost of evaluation?

**Comment by dasgarner** [comment]
Full spec and blueprint: https://community.xibo.org.uk/t/library-quota-for-user-groups-and-users-blueprint/21
