### ISSUE TITLE
Says CMS is already installed when settings.php exists

### ISSUE THREAD

**Issue by MichaelHoughton** [xibosignage/xibo#455]
When you initially go to install Xibo, you get asked to create the following files:

"Write access required for settings.php and install.php"

However, after creating settings.php and chmod 777 settings.php, you then get the following error:

"The CMS has already been installed. Please contact your system administrator."

The installation is effectively stuck in no man's land.

**Comment by dasgarner** [comment]
You aren't being asked to create the file, just to allow that file to be written (i.e. folder create permissions). Perhaps the wording could be adjusted, but it has been worded in that fashion for a long time without many complaints :smile:

Please discuss on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
