### ISSUE TITLE
Could not update display

### ISSUE THREAD

**Issue by PatricN** [xibosignage/xibo#456]
Hi, 

Situation: clean install server+client,

I see my new display at the console, but when I select "license"to Yes, I cannot save the display.

Here's the log:

--------------------------------------
Environment Checks
--------------------------------------
<table class="table">
    <thead>
        <tr>
                                    <th class="group-false">Item</th>
                        <th class="group-false" data-sorter="tickcross">Status</th>
                        <th class="group-false">Advice</th>
                                </tr>
    </thead>
    <tbody>
                <tr >
                                                <td>PHP Version</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP version 5.3.3 or later required. Detected 5.3.28</td>
                                            </tr>
                <tr >
                                                <td>File System Permissions</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>Write access required for settings.php and install.php</td>
                                            </tr>
                <tr >
                                                <td>MySQL database (PHP MySql)</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>MySQL support must be enabled in PHP.</td>
                                            </tr>
                <tr >
                                                <td>MySQL database (PDO MySql)</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PDO support with MySQL drivers must be enabled in PHP.</td>
                                            </tr>
                <tr >
                                                <td>JSON Extension</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP JSON extension required to function.</td>
                                            </tr>
                <tr >
                                                <td>SOAP Extension</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP SOAP extension required to function.</td>
                                            </tr>
                <tr >
                                                <td>GD Extension</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP GD extension to function.</td>
                                            </tr>
                <tr >
                                                <td>Session</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP session support to function.</td>
                                            </tr>
                <tr >
                                                <td>FileInfo</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>Requires PHP FileInfo support to function. If you are on Windows you need to enable the php_fileinfo.dll in your php.ini file.</td>
                                            </tr>
                <tr >
                                                <td>PCRE</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP PCRE support to function.</td>
                                            </tr>
                <tr >
                                                <td>Gettext</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP Gettext support to function.</td>
                                            </tr>
                <tr >
                                                <td>Calendar Extension</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP Calendar extension to function.</td>
                                            </tr>
                <tr >
                                                <td>DOM Extension</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP DOM core functionality enabled.</td>
                                            </tr>
                <tr >
                                                <td>DOM XML Extension</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP DOM XML extension to function.</td>
                                            </tr>
                <tr >
                                                <td>Mcrypt Extension</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP Mcrypt extension to function.</td>
                                            </tr>
                <tr >
                                                <td>Allow PHP to open external URLs</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>You must have allow_url_fopen = On in your PHP.ini file for RSS Feeds / Anonymous statistics gathering to function.</td>
                                            </tr>
                <tr >
                                                <td>DateTimeZone</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>This enables us to get a list of time zones supported by the hosting server.</td>
                                            </tr>
                <tr >
                                                <td>ZIP</td>
                                                <td><span  class="glyphicon glyphicon-ok"></span></td>
                                                <td>This enables import / export of layouts.</td>
                                            </tr>
                <tr >
                                                <td>Large File Uploads</td>
                                                <td><span  class="glyphicon glyphicon-exclamation-sign"></span></td>
                                                <td>You probably want to allow larger files to be uploaded than is currently available with your PHP configuration.<br />We suggest setting your PHP post_max_size and upload_max_size to at least 128M, and also increasing your max_execution_time to at least 120 seconds.</td>
                                            </tr>
            </tbody>
</table>

--------------------------------------
LOG Dump
--------------------------------------
Date,Page,Function,Message
"2015-03-24 17:39:17","Display","Edit","IN"
"2015-03-24 17:39:17","Display","Edit","Validation Complete and Passed"
"2015-03-24 17:39:17","Display","Edit","SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field"
"2015-03-24 17:39:17","Data Module","SetError","Data Class: Error Number [25000] Error Message [Could not update display]"
"2015-03-24 17:39:17","display","","<errormsg>Could not update display</errormsg>
<errornum>256</errornum>
<errortype>User Error</errortype>
<scriptname>/var/www/vhosts/totaal-ict.eu/httpdocs/narrow/lib/pages/display.class.php</scriptname>
<scriptlinenum>164</scriptlinenum>
"
"2015-03-24 17:39:17","display","","Creating a Response Manager to deal with the HALT Error."
"2015-03-24 17:39:16","Display","Edit","IN"
"2015-03-24 17:39:16","Display","Edit","Validation Complete and Passed"
"2015-03-24 17:39:16","Display","Edit","SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field"
"2015-03-24 17:39:16","Data Module","SetError","Data Class: Error Number [25000] Error Message [Could not update display]"
"2015-03-24 17:39:16","display","","<errormsg>Could not update display</errormsg>
<errornum>256</errornum>
<errortype>User Error</errortype>
<scriptname>/var/www/vhosts/totaal-ict.eu/httpdocs/narrow/lib/pages/display.class.php</scriptname>
<scriptlinenum>164</scriptlinenum>
"
"2015-03-24 17:39:16","display","","Creating a Response Manager to deal with the HALT Error."
"2015-03-24 17:38:40","Display","Edit","IN"
"2015-03-24 17:38:40","Display","Edit","Validation Complete and Passed"
"2015-03-24 17:38:40","Display","Edit","SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field"
"2015-03-24 17:38:40","Data Module","SetError","Data Class: Error Number [25000] Error Message [Could not update display]"
"2015-03-24 17:38:40","display","","<errormsg>Could not update display</errormsg>
<errornum>256</errornum>
<errortype>User Error</errortype>
<scriptname>/var/www/vhosts/totaal-ict.eu/httpdocs/narrow/lib/pages/display.class.php</scriptname>
<scriptlinenum>164</scriptlinenum>
"
"2015-03-24 17:38:40","display","","Creating a Response Manager to deal with the HALT Error."
"2015-03-24 17:38:31","DisplayProfile","LoadDefault","Load Default windows"
"2015-03-24 17:38:28","display","","Retreiving list of displaygroups for admin with SQL: SELECT displaygroup.DisplayGroupID, displaygroup.DisplayGroup, displaygroup.IsDisplaySpecific, displaygroup.Description   FROM displaygroup  WHERE 1 = 1  AND displaygroup.IsDisplaySpecific = 0  ORDER BY displaygroup.DisplayGroup "
"2015-03-24 17:38:28","DisplayProfile","LoadDefault","Load Default windows"
"2015-03-24 17:37:20","Display","Edit","IN"
"2015-03-24 17:37:20","Display","Edit","Validation Complete and Passed"
"2015-03-24 17:37:20","Display","Edit","SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field"
"2015-03-24 17:37:20","Data Module","SetError","Data Class: Error Number [25000] Error Message [Could not update display]"
"2015-03-24 17:37:20","display","","<errormsg>Could not update display</errormsg>
<errornum>256</errornum>
<errortype>User Error</errortype>
<scriptname>/var/www/vhosts/totaal-ict.eu/httpdocs/narrow/lib/pages/display.class.php</scriptname>
<scriptlinenum>164</scriptlinenum>
"
"2015-03-24 17:37:20","display","","Creating a Response Manager to deal with the HALT Error."
"2015-03-24 17:37:17","DisplayProfile","LoadDefault","Load Default windows"
"2015-03-24 17:37:14","display","","Retreiving list of displaygroups for admin with SQL: SELECT displaygroup.DisplayGroupID, displaygroup.DisplayGroup, displaygroup.IsDisplaySpecific, displaygroup.Description   FROM displaygroup  WHERE 1 = 1  AND displaygroup.IsDisplaySpecific = 0  ORDER BY displaygroup.DisplayGroup "
"2015-03-24 17:37:14","DisplayProfile","LoadDefault","Load Default windows"
"2015-03-24 17:36:25","Display","Edit","SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field"
"2015-03-24 17:36:25","display","","<errormsg>Could not update display</errormsg>
<errornum>256</errornum>
<errortype>User Error</errortype>
<scriptname>/var/www/vhosts/totaal-ict.eu/httpdocs/narrow/lib/pages/display.class.php</scriptname>
<scriptlinenum>164</scriptlinenum>
"
"2015-03-24 17:36:25","Display","Edit","SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field"
"2015-03-24 17:36:25","display","","<errormsg>Could not update display</errormsg>
<errornum>256</errornum>
<errortype>User Error</errortype>
<scriptname>/var/www/vhosts/totaal-ict.eu/httpdocs/narrow/lib/pages/display.class.php</scriptname>
<scriptlinenum>164</scriptlinenum>
"
"2015-03-24 17:36:25","Display","Edit","SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field"
"2015-03-24 17:36:25","display","","<errormsg>Could not update display</errormsg>
<errornum>256</errornum>
<errortype>User Error</errortype>
<scriptname>/var/www/vhosts/totaal-ict.eu/httpdocs/narrow/lib/pages/display.class.php</scriptname>
<scriptlinenum>164</scriptlinenum>
"
"2015-03-24 17:36:25","Display","Edit","SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field"
"2015-03-24 17:36:25","display","","<errormsg>Could not update display</errormsg>
<errornum>256</errornum>
<errortype>User Error</errortype>
<scriptname>/var/www/vhosts/totaal-ict.eu/httpdocs/narrow/lib/pages/display.class.php</scriptname>
<scriptlinenum>164</scriptlinenum>
"
"2015-03-24 17:36:24","Display","Edit","SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field"
"2015-03-24 17:36:24","display","","<errormsg>Could not update display</errormsg>
<errornum>256</errornum>
<errortype>User Error</errortype>
<scriptname>/var/www/vhosts/totaal-ict.eu/httpdocs/narrow/lib/pages/display.class.php</scriptname>
<scriptlinenum>164</scriptlinenum>
"
"2015-03-24 17:36:24","Display","Edit","SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field"
"2015-03-24 17:36:24","display","","<errormsg>Could not update display</errormsg>
<errornum>256</errornum>
<errortype>User Error</errortype>
<scriptname>/var/www/vhosts/totaal-ict.eu/httpdocs/narrow/lib/pages/display.class.php</scriptname>
<scriptlinenum>164</scriptlinenum>
"
"2015-03-24 17:36:24","Display","Edit","SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field"
"2015-03-24 17:36:24","display","","<errormsg>Could not update display</errormsg>
<errornum>256</errornum>
<errortype>User Error</errortype>
<scriptname>/var/www/vhosts/totaal-ict.eu/httpdocs/narrow/lib/pages/display.class.php</scriptname>
<scriptlinenum>164</scriptlinenum>
"
"2015-03-24 17:36:24","Display","Edit","SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field"
"2015-03-24 17:36:24","display","","<errormsg>Could not update display</errormsg>
<errornum>256</errornum>
<errortype>User Error</errortype>
<scriptname>/var/www/vhosts/totaal-ict.eu/httpdocs/narrow/lib/pages/display.class.php</scriptname>
<scriptlinenum>164</scriptlinenum>
"
"2015-03-24 17:36:23","Display","Edit","SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field"
"2015-03-24 17:36:23","display","","<errormsg>Could not update display</errormsg>
<errornum>256</errornum>
<errortype>User Error</errortype>
<scriptname>/var/www/vhosts/totaal-ict.eu/httpdocs/narrow/lib/pages/display.class.php</scriptname>
<scriptlinenum>164</scriptlinenum>
"
"2015-03-24 17:36:23","Display","Edit","SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field"
"2015-03-24 17:36:23","display","","<errormsg>Could not update display</errormsg>
<errornum>256</errornum>
<errortype>User Error</errortype>
<scriptname>/var/www/vhosts/totaal-ict.eu/httpdocs/narrow/lib/pages/display.class.php</scriptname>
<scriptlinenum>164</scriptlinenum>
"
"2015-03-24 17:36:21","Display","Edit","SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field"
"2015-03-24 17:36:21","display","","<errormsg>Could not update display</errormsg>
<errornum>256</errornum>
<errortype>User Error</errortype>
<scriptname>/var/www/vhosts/totaal-ict.eu/httpdocs/narrow/lib/pages/display.class.php</scriptname>
<scriptlinenum>164</scriptlinenum>
"

--------------------------------------
Display Dump
--------------------------------------
DisplayID: 1
Display: NB-5CG44404G7
Default Layout: 
Logged In: 1
Last Accessed: 1427214946
Interleave: 0
Licensed: 0

--------------------------------------
Settings Dump
--------------------------------------
Setting: MEDIA_DEFAULT - Value:   private

Setting: LAYOUT_DEFAULT - Value:   private

Setting: defaultUsertype - Value:   User

Setting: userModule - Value:   module_user_general.php

Setting: defaultTimezone - Value:   Europe/Amsterdam

Setting: mail_to - Value:   mail@yoursite.com

Setting: mail_from - Value:   mail@yoursite.com

Setting: jpg_length - Value:   10

Setting: ppt_length - Value:   10

Setting: swf_length - Value:   10

Setting: audit - Value:   audit

Setting: LIBRARY_LOCATION - Value:   \\\\library/

Setting: HELP_BASE - Value:   http://www.xibo.org.uk/manual/en/

Setting: PHONE_HOME - Value:   On

Setting: PHONE_HOME_URL - Value:   http://www.xibo.org.uk/stats/track.php

Setting: PHONE_HOME_DATE - Value:   0

Setting: SERVER_MODE - Value:   Production

Setting: MAINTENANCE_ENABLED - Value:   Off

Setting: MAINTENANCE_EMAIL_ALERTS - Value:   On

Setting: MAINTENANCE_KEY - Value:   changeme

Setting: MAINTENANCE_LOG_MAXAGE - Value:   30

Setting: MAINTENANCE_STAT_MAXAGE - Value:   30

Setting: MAINTENANCE_ALERT_TOUT - Value:   12

Setting: SHOW_DISPLAY_AS_VNCLINK - Value:   

Setting: SHOW_DISPLAY_AS_VNC_TGT - Value:   _top

Setting: MAINTENANCE_ALWAYS_ALERT - Value:   Off

Setting: SCHEDULE_LOOKAHEAD - Value:   On

Setting: REQUIRED_FILES_LOOKAHEAD - Value:   172800

Setting: REGION_OPTIONS_COLOURING - Value:   Media Colouring

Setting: LAYOUT_COPY_MEDIA_CHECKB - Value:   Unchecked

Setting: MAX_LICENSED_DISPLAYS - Value:   0

Setting: LIBRARY_MEDIA_UPDATEINALL_CHECKB - Value:   Unchecked

Setting: USER_PASSWORD_POLICY - Value:   

Setting: USER_PASSWORD_ERROR - Value:   

Setting: MODULE_CONFIG_LOCKED_CHECKB - Value:   Unchecked

Setting: LIBRARY_SIZE_LIMIT_KB - Value:   0

Setting: MONTHLY_XMDS_TRANSFER_LIMIT_KB - Value:   0

Setting: DEFAULT_LANGUAGE - Value:   en_GB

Setting: TRANSITION_CONFIG_LOCKED_CHECKB - Value:   Unchecked

Setting: GLOBAL_THEME_NAME - Value:   default

Setting: DEFAULT_LAT - Value:   51.504

Setting: DEFAULT_LONG - Value:   -0.104

Setting: SCHEDULE_WITH_VIEW_PERMISSION - Value:   No

Setting: SETTING_IMPORT_ENABLED - Value:   1

Setting: SETTING_LIBRARY_TIDY_ENABLED - Value:   1

Setting: SENDFILE_MODE - Value:   Off

Setting: EMBEDDED_STATUS_WIDGET - Value:   

Setting: PROXY_HOST - Value:   

Setting: PROXY_PORT - Value:   0

Setting: PROXY_AUTH - Value:   

Setting: DATE_FORMAT - Value:   Y-m-d H:i

Setting: DETECT_LANGUAGE - Value:   1

Setting: DEFAULTS_IMPORTED - Value:   1

Setting: FORCE_HTTPS - Value:   0

Setting: ISSUE_STS - Value:   0

Setting: STS_TTL - Value:   600

Setting: MAINTENANCE_ALERTS_FOR_VIEW_USERS - Value:   0

Setting: CALENDAR_TYPE - Value:   Gregorian

Setting: DASHBOARD_LATEST_NEWS_ENABLED - Value:   1

Setting: LIBRARY_MEDIA_DELETEOLDVER_CHECKB - Value:   Unchecked

Setting: USE_INTL_DATEFORMAT - Value:   0

--------------------------------------
Sessions Dump
--------------------------------------
UserAgent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36
RemoteAddress: 46.145.191.66
Session Data
pagename|s:5:"fault";token|s:32:"e3d3ba9a608e8e754d415364da0197b1";token_timeout|i:1427215176;message|s:0:"";userid|s:1:"1";username|s:5:"admin";usertype|s:1:"1";display|a:6:{s:14:"filter_display";s:0:"";s:16:"filterMacAddress";s:0:"";s:19:"filter_displaygroup";i:0;s:15:"filter_showView";i:0;s:18:"filter_autoRefresh";i:0;s:13:"DisplayFilter";i:0;}gridToken|s:32:"0d94538323e8f57f2087e34b5fcaf205";gridToken_timeout|i:1427215108;log|a:8:{s:6:"Filter";i:0;s:11:"filter_type";i:0;s:15:"filter_function";s:0:"";s:11:"filter_page";s:0:"";s:13:"filter_fromdt";s:0:"";s:14:"filter_display";i:0;s:14:"filter_seconds";s:3:"120";s:21:"filter_intervalTypeId";s:1:"1";}
----

**Comment by alexharrington** [comment]
Please post support requests over on the Community site:

https://community.xibo.org.uk

This issue tracker will is for verified issues only, these are issues previously discussed on community.xibo.org.uk.
