### ISSUE TITLE
Xibo Reporting Incorrect Size During Upload

### ISSUE THREAD

**Issue by fward1208** [xibosignage/xibo#457]
Upload fails due to incorrect size report: 

Xibo Ui reports size as 39.63 MB while windows shows size is 37.7 MB.

Upload stops when the full 37.7 MB is done, but states it cannot find file due to erroneous size difference.

![size](https://cloud.githubusercontent.com/assets/11433306/6813448/991dfc48-d24b-11e4-8c42-8bba1f794df7.jpg)
![size_correct](https://cloud.githubusercontent.com/assets/11433306/6813451/9d638f02-d24b-11e4-904b-f2e835c9059d.jpg)

**Comment by dasgarner** [comment]
I doubt the incorrect file size has anything to do with the upload failure. The file size and progress is presented for informational purposes only (although it is usually correct).

Please discuss on [community.xibo.org.uk](http://community.xibo.org.uk), we will need the actual error message as well as CMS logging for the duration of the failed upload. 

GitHub is now a **verified bug tracker** only.

**Comment by fward1208** [comment]
Error message states "Not found". I turned on debugging and reviewed logs. No logs of the error were present. I just added it to the library manually via sql and added to the layout. No fuss no muss.
