### ISSUE TITLE
Web page embedded 

### ISSUE THREAD

**Issue by jmggs** [xibosignage/xibo#463]
Hi,

I have a webpage  embedded  on xibo with this code: 
<iframe src="http://www.euronews.com/media/player_live_1_14.swf?preroll=1&autoplay=true&fluff=f00ed46d1ba92ababb981df5d5cea5ce&img=&nedstat=news.streaming-live&lng=pt" width="1280" height="720">
</iframe>

in preview layout the swf will go fill the region size.

But on xibo player is just a small window, much smaller than the region. 

Any body know whats wrong?

**Comment by alexharrington** [comment]
Please post support requests over on the Community site:

https://community.xibo.org.uk

This issue tracker will is for *verified* issues only, these are issues previously discussed on community.xibo.org.uk.
