### ISSUE TITLE
Video duration cannot be edited to 0 seconds

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#468]
1.7.2

I can create a video media with 0 duration, but if I subsequently edit the duration to be say 10 seconds, I can't edit it back to 0.

Validation fails with the error:
Expecting a whole number but found 0

Originally reported here:
https://community.xibo.org.uk/t/video-duration-issue/355

**Comment by dasgarner** [comment]
From the PHP Manual for filter_var:

> Note:
> As of PHP 5.4.11, the numbers +0 and -0 validate as both integers as well as floats (using FILTER_VALIDATE_FLOAT and FILTER_VALIDATE_INT). Before PHP 5.4.11 they only validated as floats
