### ISSUE TITLE
android client with a 1.6 server?

### ISSUE THREAD

**Issue by danielzzz** [xibosignage/xibo#472]
is it possible to use android clientes with xibo server 1.6?
I have to hold back the server version because we have some linux clients.

(unless it's possible to use linux 1.6 clients with a 1.7 server)

thanks, dan

**Comment by dasgarner** [comment]
Yes they are compatible (use the latest 1.7 R53)

For future questions please discuss on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
