### ISSUE TITLE
User Group Membership fails to set with >4 users when double clicking

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#474]
1.7.3 CMS.

Create a user group. Add 4 users to it. Save the group.

Now edit the group membership and attempt to add a 5th user to the group by double clicking in the right hand side list another user. The user jumps to the left hand list correctly, but on save the update doesn't happen.

If you drag the user from the right hand list to the left then the problem doesn't occur.

Also if you create a new group and add 5 or 6 users initially by double clicking, only 4 are added to the group. Numbers 5 and 6 aren't added and remain in the right hand list.

**Comment by alexharrington** [comment]
https://community.xibo.org.uk/t/cms-1-7-3-user-group-member-error/407 refers

**Comment by dasgarner** [comment]
This was far more "random" than it seemed. It wasn't adding users to the group where their userId matched the array key of the users already in the group.

**Comment by PeterMis** [comment]
Test:Passed
