### ISSUE TITLE
Backwards compatible

### ISSUE THREAD

**Issue by mymactek** [xibosignage/xibo#482]
Is the windows / server backwards compatible.

have many systems currently on 1.7.1 that need to be updated. Once server is updated to newest version - will it cause any problems on systems for a few days, till they can be updated ?

Thanks !

**Comment by dasgarner** [comment]
Any upgrades "in series" will be compatible unless otherwise stated on the release notes.

For future: Please discuss on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
