### ISSUE TITLE
Repeat specified blocks of days of the week?

### ISSUE THREAD

**Issue by youneeque** [xibosignage/xibo#484]
I've just started evaluating v1.7 and an enhancement request that I submitted (probably long-ago archived) way back when we used v1.2 does not appear to be on the radar... unless my lack of knowledge of v1.7 after only a few days of use is getting in my way.

Way back then, I explained that I work in a school that operates, in general Mon - Fri. So, with very few exceptions such as annual Open Day (usually held on a Sunday) or out-of-hours weekend activities, our displays follow Mon-Fri and, in general, should be blank on weekends. In addition, some recurring displays should be shown just on (for instance) Mon-Wed.

So I'd like to be able to schedule recurring schedules for, say, "every monday and friday" for the next 5 years or "every weekday for the next 5 years". In our current production environment at present (under v1.6.x) I have to make up 5 schedules if I wish to do the second of these options and two if I am to set up the former.

It was suggested way back when I initially asked for this facility that I could schedule permanently recurring schedules as "every day for 5 years" and then schedule (with priority) a blank screen for weekends and after hours. However with our model, this is impractical. Perhaps if there were 2 levels of "priority" we could do it (ie. "no priority" for recurring schedules, "priority 1" for blank screen and priority 2 for weekends)... this might work.

Due to the large number of schools using Xibo, I'm surprised that this facility has not been included. If it's already there in v1.7 and I've missed it, I apologise for taking up your time with such a wordy request. Thanks

**Comment by alexharrington** [comment]
Please post this in the Features category on https://community.xibo.org.uk Github Issues is used by the project as a verified bug tracker only.

Then the community can comment on the merits of your suggestion.
