### ISSUE TITLE
1.7.3 5 days, current day in a big circle template broken for US units

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#485]
When selecting the 5 day template, and US units, the temperature value is correctly shown in degrees F, however the indicated units 'C' is hardcoded in the template, so you see

50°C rather than 50°F

eg
```<div class="maxTemp"><span class="temp">[temperatureMaxFloor]</span>°<span class="unitTemp">C</span></div>```

should be
```<div class="maxTemp"><span class="temp">[temperatureMaxFloor]</span>°<span class="unitTemp">F</span></div>```

I don't see a substitution for the units in the forecast returned at present.

**Comment by PeterMis** [comment]
Test:Passed
