### ISSUE TITLE
1.7 Copy Layout Security bug

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#487]
When copying a layout, it appears that the security for each media item is being created multiple times if there is more than one occurrence of the media item in a single region.

This thread refers:
https://community.xibo.org.uk/t/layout-copy-problem/513

**Comment by dasgarner** [comment]
Permissions to Library Assignments are only resolved to the Layout/Region and not to the specific assignment. 1.8 will not have this issue as the permission is on the Widget.

To prevent duplicate assignments we can keep a cache of region/media assignments already copied and skip any we have already done - thereby only copying the first one.
