### ISSUE TITLE
error webpage can't connect

### ISSUE THREAD

**Issue by marlz** [xibosignage/xibo#494]
hi ,

i have some layout webpage, this webpage i connect to local site (http://localhost/queueing/1.php). first is working, but after view minute or view hours, this webpage appear error message, like the website can't connect. this problem make me headache, even i already put refresh page 10 sec, in my website.

note : i use xibo 1.4.1 cms, xibo player ver 1.6.4, i put interval 30 sec but i also tried 360 sec, but still error.

anybody know how to solve this problem ?

thanks in advance

**Comment by alexharrington** [comment]
Please discuss your issue on the community support site first. Github issues is only for confirmed bugs that have already been discussed there. Thank you.

https://community.xibo.org.uk
