### ISSUE TITLE
dot net client: download problem on intel Atom processors

### ISSUE THREAD

**Issue by pubblisoft** [xibosignage/xibo#495]
Hi,

i have 3 Atom processors base computers and 4 core i3 based computers.
The xibo .net client (actual last version) crash downloading photos or syncronizing web pages; the application works well on core base computers.

**Comment by alexharrington** [comment]
Please discuss this on the Xibo Community first: https://community.xibo.org.uk

Github issues is for confirmed bugs that have been discussed there already only.
