### ISSUE TITLE
CMS Display Profile Settings: Description wrong on Android Expire Modified Layouts

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#496]
CMS 1.7.3

Under an Android Display Settings Profile, the description on Expire Modified Layouts is wrong:
![image](https://cloud.githubusercontent.com/assets/10450518/7197781/012663e0-e4dd-11e4-9fe0-53303ab7d565.png)

See https://community.xibo.org.uk/t/incorrect-description-in-expire-modified-layouts/365

**Comment by PeterMis** [comment]
Test:Passed
