### ISSUE TITLE
1.7.3 Client crashes

### ISSUE THREAD

**Issue by chriskemp010** [xibosignage/xibo#497]
Hello,

Player crashes when moving between scheduled layouts.  It seems to load each one once in the sequence but then when it comes round to display a layout it has already displayed, it crashes.  A look in TaskMan shows 7 or so XiboPlayer instances running...

**Comment by alexharrington** [comment]
Hi Chris

Please discuss this over on the Community site first. Github issues is only for confirmed bugs that have been discussed there already: https://community.xibo.org.uk
