### ISSUE TITLE
Group access not working on Layout example 

### ISSUE THREAD

**Issue by mighiel** [xibosignage/xibo#498]
Hello,

We upgraded from Xibo 1.4.3 to 1.7.3. Only the xibo admin user can view layout examples. Every other user gives the error message below. 

The user group has access to the layout page.  
I tried creating a new layout, but even when the user is the owner of the layout this erros comes up.
Also tried creating a new user and new layout, also same results.

After enabling access to the layout page on the user itself, the user can view the layout example.

Error:message 
{"html":null,"buttons":"","fieldActions":"","uniqueReference":"","success":false,"callBack":null,"message":"U heeft geen rechten om deze pagina te openen.","clockUpdate":false,"sortable":null,"sortingDiv":null,"paging":null,"pageSize":10,"pageNumber":0,"initialSortColumn":0,"initialSortOrder":0,"dialogSize":null,"dialogWidth":0,"dialogHeight":0,"dialogTitle":null,"dialogClass":"","keepOpen":null,"hideMessage":null,"loadForm":null,"loadFormUri":null,"refresh":null,"refreshLocation":null,"focusInFirstInput":true,"modal":false,"nextToken":null,"login":null,"extra":[]}

**Comment by alexharrington** [comment]
Please discuss this over on the Community support site first. Github issues is for confirmed bugs that have been discussed there first only.

https://community.xibo.org.uk
