### ISSUE TITLE
Custom CSS file for Windows client?

### ISSUE THREAD

**Issue by aidanmoher** [xibosignage/xibo#499]
I'm running Xibo on a Windows client, and I'd like to be able to write some custom CSS that defines font-families and font-sizes for various elements (h1, h2, p, etc.) to help bring consistency to the content created by various people in my organization. However, fonts.css appears to overwrite all of my changes whenever a new piece of content it posted.

Is there a way to insert a custom CSS (say, custom-fonts.css) into every slide without having to use inline styles or the WYSIWYG editor?

Thanks!

**Comment by alexharrington** [comment]
Please discuss this on the Xibo Community site. Github issues is for confirmed bugs only that have already been discussed there:

https://community.xibo.org.uk
