### ISSUE TITLE
Impossible to "Add application"

### ISSUE THREAD

**Issue by AmauryUTB** [xibosignage/xibo#504]
Hi !

I installed Xibo 1.7.3.
I tried to add application in Xibo in order to do the monitoring of my android client.

But it is impossible to register.
![sans titre](https://cloud.githubusercontent.com/assets/12138910/7350812/c057a7c0-ed01-11e4-8c54-54fa5f435796.png)

The problem seems to be the Xrds-location : 
The right adress is : http://server/xibo//services.php?xrds
but the system try to connect to : http://server/xibo/index.php/service.php?xrds

May you solve the problem please ?
Or what did I do wrong please ?

Thanks.

**Comment by dasgarner** [comment]
Please discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
