### ISSUE TITLE
Xibo has stopped working

### ISSUE THREAD

**Issue by ygurdag** [xibosignage/xibo#51]
Xibo client stopped working after a little work. I am using xibo 1.7rc1. If you want to test this error on your side; set server connection time to 30 seconds and disconnect client from internet. Xibo starts log files and make more than expected. For example it has done 2000 log files about 20 minutes.

**Comment by dasgarner** [comment]
Are you suggesting that the log file build up is causing Xibo to crash? Are you running out of disk space at all?

It would be interesting to see the crash report if you could get one?

**Comment by knitehawk** [comment]
i can confirm that disconnection from access to server will crash xibo 1.7 windows client on windows 7
here are logs until crash

<trace date="2015-01-25 18:50:23" category="Error"><message>Exception in Run: Unable to connect to the remote server</message><method>RegisterAgent - Run</method><logdate>1/25/2015 6:50:23 PM</logdate><thread>RegisterAgentThread</thread>
</trace>
<trace date="2015-01-25 18:50:44" category="Error"><message>Unable to connect to the remote server</message><method>ScreenShot - Take</method><logdate>1/25/2015 6:50:44 PM</logdate><thread></thread>
</trace>
<trace date="2015-01-25 18:50:44" category="Error"><message>Exception in Run: Unable to connect to the remote server</message><method>ScheduleAgent - Run</method><logdate>1/25/2015 6:50:44 PM</logdate><thread>ScheduleAgentThread</thread>
</trace>

<trace date="2015-01-25 18:50:24" category="Error"><message>Exception in Run: Unable to connect to the remote server</message><method>ScheduleAgent - Run</method><logdate>1/25/2015 6:50:24 PM</logdate><thread>ScheduleAgentThread</thread>
</trace>
<trace date="2015-01-25 18:50:45" category="Error"><message>Exception in Run: Unable to connect to the remote server</message><method>RequiredFilesAgent - Run</method><logdate>1/25/2015 6:50:45 PM</logdate><thread>RequiredFilesAgentThread</thread>
</trace>
<trace date="2015-01-25 18:50:45" category="Error"><message>Unable to connect to the remote server</message><method>ScreenShot - Take</method><logdate>1/25/2015 6:50:45 PM</logdate><thread></thread>
</trace>

**Comment by dasgarner** [comment]
I think we probably want to "back off" if we can't connect - somehow. I don't see how this is any different to 1.6.4 though - i'll investigate.

**Comment by dasgarner** [comment]
Please can you try this EXE: https://github.com/xibosignage/xibo-dotnetclient/blob/7b76de9b96d1da0d8e3b638b8cb873841224df3f/bin/x86/Release/XiboClient.exe

1. Stop the player
2. Copy in the replacement
3. Start the player
