### ISSUE TITLE
Check for php5-zip module

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#511]
php5-zip is required but there's no pre-install check for it, and without it you get a blank white screen.

See: https://community.xibo.org.uk/t/php5-zip-needed-or-blank-screen-on-index-php/847

**Comment by dasgarner** [comment]
This has already been fixed: #381

**Comment by jimheem** [comment]
I can see that in 1.7.3 it DOES indeed check for Zip, however it possibly does not show in the checklist.

**Comment by jimheem** [comment]
Confirmed : I uninstalled php5-zip and reran the install.php. see screenshot

![image](https://cloud.githubusercontent.com/assets/7213299/7538651/888219ea-f56f-11e4-9343-1f0e5cd41c2d.png)

As you can see it falsely says zip is good. Does not give a "next" option though.

Once php5-zip is reinstalled and apache restarted, Next is available

![image](https://cloud.githubusercontent.com/assets/7213299/7538724/10258c38-f570-11e4-9f98-d42e7b00e4ba.png)

**Comment by dasgarner** [comment]
Thanks for the extended debugging there - I spotted the issue and fixed in the attached commit.
