### ISSUE TITLE
Windows Client connecting to CMS, crashes the server

### ISSUE THREAD

**Issue by beckend** [xibosignage/xibo#514]
Xibo CMS 1.7.3
Windows Client 1.7.3
1. Register to CMS, plays fine
2. Uninstall and delete all traces of Xibo on the Client computer. (reformatted)
3 . Delete the Display from CMS.
4. Re-register the Display to CMS, "display is awaiting approval", accept the display in the CMS
5 . Press Save(The underlying connection was closed) OR start the Client normally on the windows computer, crashes the server, logs are empty in CMS.
6. Try to Delete Display from CMS, change Display ID in the Xibo Player Options, same effect, crashes the server.

Unfortunately the server is hosted externally, we do not have "proper" access to the server itself, we can only upload files.

**Comment by dasgarner** [comment]
Please discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
