### ISSUE TITLE
Dataset error

### ISSUE THREAD

**Issue by Ragtec** [xibosignage/xibo#516]
Hi,

I just paid for to convert my trial account to a paid account with Xibo, and now I'm finding I can't do anything with the datasets I created. I've tried deleting, permissions, change columns etc. 7 of the 8 datasets come back with an error as below:
   "index does not support the function: DeleteDataSetForm."
Clicking "view data" just takes me back to my dashboard.

The remaining dataset appears to work as expected.

It is worth noting that the datasets with the problem all have an & symbol in their name. could that cause an issue? if so how can I clean these up if I can't edit them?

Thanks in advance,
Andy

**Comment by PeterMis** [comment]
You can follow the progress regarding this bug here: https://github.com/xibosignage/xibo/issues/517
I'll close this issue so we will have just one about this problem.
