### ISSUE TITLE
Ubuntu client not show on xibo-cms-1.7.3

### ISSUE THREAD

**Issue by manish1987** [xibosignage/xibo#522]
Hi,

I have upgrade my xibo server 1.6 to 1.7 and now it is not showing in my display. My Client site i have xibo client version 1.6. How can i resolve this issue i dose not understand where is the issue.

**Comment by dasgarner** [comment]
Please discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
