### ISSUE TITLE
Users with Group Admin user type, can't see media or layouts from other group members

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#524]
When you have group with few users, then even when user is a group admin user type and he add some media files or layouts, newly added files/layouts will not be visible to other members of the same group (even if they are also group admin user type)

More information and workaround can be found here:
https://community.xibo.org.uk/t/users-with-group-admin-user-type-cant-see-media-or-layouts-from-other-group-members/2447

**Comment by dasgarner** [comment]
Test required against 1.7.4/1.8.0-alpha2 codebases
@PeterMis - can you run some tests?
