### ISSUE TITLE
Ticker Text Cuts Off Instead of Wrapping Around

### ISSUE THREAD

**Issue by Flylowguy** [xibosignage/xibo#527]
I'm using a ticker that accesses an RSS feed. The transition is set to Scroll Vertical, and for some reason the text goes off the side of the screen, no matter what size the region is. It won't wrap around, even if the region is given the whole screen. See the attached screen shot.
![notworking](https://cloud.githubusercontent.com/assets/4967659/7891906/ee900100-0615-11e5-89dc-372de2c42d12.png)

**Comment by dasgarner** [comment]
Sorry for the late reply. If this is still an issue please discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
