### ISSUE TITLE
Datepicker is not putting the correct time (download/update window)

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#529]
For example Download Window start/end time set to 12-15
Actual Download Windows start/end will be set to 13-16 (since UK is gmt+1)
So it's taking into account only gmt time and not real time on the CMS/device.

More information and example with different time zone:
https://community.xibo.org.uk/t/bug-update-and-downlod-timepicker/2529

**Comment by dasgarner** [comment]
The CMS is currently saving the time in GMT, the Android Player parsing it in local time and the Windows Player parsing it in GMT.

The CMS should save in local time - this is the way all other dates are saved (for good or ill).

The Windows Player should use the H/M from the provided date to create a window date.
