### ISSUE TITLE
Screen thumbnail Just the display

### ISSUE THREAD

**Issue by knitehawk** [xibosignage/xibo#53]
For displays that are not using the entire screen to post content to, it would be nice if the screenshot was only the display area.
for instance:
display hight 64
display width 256
thumb nail is almost usless, as you have an entire 1024x769 desktop screen and have to click it to enlarge so you can see whats on the screen.

GREAT PROGRAM AND ENHANCEMENTS!

**Comment by dasgarner** [comment]
Yes, totally agree on this one. The "full desktop" screenshot is overkill - it should only take the active client window.

**Comment by knitehawk** [comment]
Dan,
the modification to the .net client is: screenshot.cs
Rectangle bounds = Screen.GetBounds(Point.Empty);
to
var bounds = Form.ActiveForm;
seems to work great.
now just need to set scaling so you can zoom in (for smaller displays).
