### ISSUE TITLE
Missing default.xml file - this should be in the same path as executable

### ISSUE THREAD

**Issue by sureshsarat** [xibosignage/xibo#532]
I downloaded the Windows Client source. Then tried opening the same in VS 2013. 
I am getting this error "Missing default.xml file" when trying to pen the solution in Visual Studio 2013 Professional.

**Comment by alexharrington** [comment]
Please post your question on the Community site at https://community.xibo.org.uk 

Github issues is only for confirmed bugs which have already been discussed there.
