### ISSUE TITLE
Template tag filter searches layouts 1.7.4

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#535]
1.7.4 CMS
Design -> Templates -> Filter
Enter anything in the tags field and press enter.
Page changes to a layout list with no filtering applied.

Additionally tags aren't shown in the template listing so I'm not sure what use filtering on tag is?

Originally reported here:
https://github.com/xibosignage/xibo/issues/534

**Comment by dasgarner** [comment]
Need to append the "template" tag to any tag entered in the filter

**Comment by dasgarner** [comment]
@PeterMis does this also effect 1.8?

**Comment by PeterMis** [comment]
@dasgarner Yes it does, filter by name is fine but by tags does nothing.
We also might want to display tags there perhaps, currently we have name, owner, description thumbnails and permissions.
