### ISSUE TITLE
Empty XiboClient.config.xml, player does not work after power fealure

### ISSUE THREAD

**Issue by ygurdag** [xibosignage/xibo#54]
Hello,
I am trying Xibo 1.7.0-rc1 server and client. Client was working last night but this morning client shows an error and doesn't work. The error message is: "There is an error in XML document (0,0). Path: C:\Users\Mike\AppData\Roaming\XiboClient.config.xml"
So I find the xml file and its zero, there is nothing inside.
Xibo player and even xibo player options does not work.
I must delete the xml file, client option worked and as you can guess all of my settings lost.
This issue happined 3 computers same (windows 7 and windows 8). I think the problem happens downloading client setting from server and writing those settings to this xml. Maybe client powered off in this threat and file goes empty. I think there should be a copy of (at least first setting we make, server, key exc.) and if client cannot read xiboclient.config.xml could try to read backup.xml and connect to server take all settings again. In this solution client could repair itself and could work without user attraction. My Collection Interval (seconds) setting is 30 seconds, maybe it make the problem often.

Thanks
Michael

**Comment by dasgarner** [comment]
My feeling is that we need to try and find the root cause of the issue (is this you by the way? https://answers.launchpad.net/xibo/+question/261020)

The XiboClient.config.xml file is only written to when the player receives its new config from the CMS - I wonder if it is doing that too often which is in turn causing a crash.

I will investigate and see.

**Comment by ygurdag** [comment]
Thank you for your quick answer. It writes to this xml every 30 seconds (depends on Collection Interval I think), not only player receives its new config. Even I don't change any setting it rewrites file every 30 seconds.
Thanks
Michael,
By the way yes its me(https://answers.launchpad.net/xibo/+question/261020)

**Comment by dasgarner** [comment]
I've modified it so that it only writes to that file when the settings have actually changed. Can you try this EXE? https://github.com/dasgarner/xibo-dotnetclient/blob/master/bin/x86/Release/XiboClient.exe?raw=true

**Comment by ygurdag** [comment]
I will try and let you know, thanks

**Comment by mattiassvedhem** [comment]
This seems to still be a problem in 1.8 RC2 – we're experiencing it when using short collection intervalls on power outages.
There must be a way to make this bullet proof? Maybe a second copy of the file or something so the file is never allowed to be corrupted?

**Comment by dasgarner** [comment]
There have been further modifications to this in the upcoming rc3 - see https://github.com/xibosignage/xibo/issues/1025 for details.
