### ISSUE TITLE
Dataset ascending sort order 

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#542]
Right now when users want to sort dataset in ascending order they need to put
"columnName" in  "order"

while to sort in descending order:
"columnName DESC" in "order"

It would be nice to have a support for "columnName ASC" in "order" too.

**Comment by PeterMis** [comment]
Not quite good I am afraid, while columnName DESC and columnName are still working fine.
ColumnName ASC - unknown error, please contact support

**Comment by dasgarner** [comment]
@PeterMis I see the issue and have made another commit for both series
