### ISSUE TITLE
Enclosure RSS Feed with inline image enclosures

### ISSUE THREAD

**Issue by djfryslan** [xibosignage/xibo#546]
Because it's not possible to add enclosure images into a rss feed, I used Yahoo Pipes to fix this problem. But they stopped this service.

I'd like to attache the images into the description for the next rss feeds:
http://www.nu.nl/rss
http://www.omropfryslan.nl/rss

How can I fix this?

Thank you!

**Comment by dasgarner** [comment]
Please discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
