### ISSUE TITLE
Embedded Chrome Does not Initialize Javascript On Page

### ISSUE THREAD

**Issue by fward1208** [xibosignage/xibo#551]
I have a div to display yo.window weather for the local area, and the page javascript does not initialize when the display settings are using Embedded Chrome.

I am using Xibo Client 1.7.4

**Comment by dasgarner** [comment]
Please discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
