### ISSUE TITLE
Show preview of full layout while creating it.

### ISSUE THREAD

**Issue by knitehawk** [xibosignage/xibo#56]
have some kind of "live" full render window, so that as your adding, or typing it will show you what the full frame finished product will look like at that time. what you see is what you get.
this is very important to a finished product look.
it would make creating a layout MUCH faster then making it 15 times to get the spacing and positioning right. then trying to preview it after, only to find that it needs to be adjusted, and spending 20 mins getting it to look right.

**Comment by dasgarner** [comment]
I am not sure about this one - the idea is that the Layout Designer **does** look like the finished product as it would on the display... no extra preview windows required.

I can certainly see that there could be some improvements to the Layout Designer - but it should already visually represent the final layout.

Do you have any particular examples of where it does not?

**Comment by knitehawk** [comment]
Ah, sorry i should be more clear. i am talking about in more in the time line. if you add text or clock or whatever in the time line (flipclock as well) you have to do alot of experimentation to see where and what font things will look best.
i was thinking of a full render of the full "Frame" your on where you can see the full layout as well as the timeline addition your on.
lets say you add a picture taking 1/4 of the screen on the left in one region, and a text box to the right. it would be nice to see what it looks like as your entering it so you see the full screen render with both the regions while your editing.

**Comment by dasgarner** [comment]
I think I'm starting to understand - so you mean that the "open" "save" "close" interaction when adding media detracts from the design experience and it would be better to be able to still see the designer window (and have that window update) as you were editing timeline items.

**Comment by knitehawk** [comment]
no, i don't mind the open save and close, as you might want to experiment before committing. however in the dialog for adding text or other media you should be able to see how its going to look on the whole sign while editing. that way you can decide BEFORE you save it if thats the way you want it to look.
also
once you hit save, if its a currently running layout. the sign gets it. this adds to confusion on the display, if your constantly updating it and changing it because you have to save it to then see the whole region.

**Comment by dasgarner** [comment]
OK, sounds interesting.

The ability to have an optional 2 step process for editing before a Layout goes out to the displays is definitely something we want to do.

The other sounds like it would be a redesign of the way the Layout Designer works, a ground up sort of change that could get rather complicated. I guess I am having trouble visualising how it might work - we'll raise it for discussion at our next roadmap meeting.

**Comment by dasgarner** [comment]
Closed due to #556
