### ISSUE TITLE
Manual Display Status explanation incorrect

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#560]
It says:

> Row Colour: The status of the display. Red = missing content, Yellow = downloading missing content, Green = Up to Date.

It should say (in better English):

 - tick = up to date (used to be green)
 - ! = not logged in since content change (used to be yellow)
 - cross = player downloading (used to be red)

**Comment by PeterMis** [comment]
As soon as this masterpiece that someone did will be live then it will be good :).
