### ISSUE TITLE
DatePicker on Statistics page is broken with international date enabled

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#561]
When you tick the ' show international dates?' checkbox and change the date format as in the guide to YYYY-MM-dd HH:mm:ss.
Then datepicker on Statistics page will show incorrect dates.
It's being fed the wrong date format with international dates enabled.

**Comment by dasgarner** [comment]
This should be working with 1.8 test - can you confirm?

**Comment by PeterMis** [comment]
I think we talked about it, but just to remember, most formats are working very well on statistics page, the one in question - YYYY-MM-dd HH:mm:ss, not so much, it returns:
2015201520152015-
well you get the idea 
Y-M-d H:m:s is fine, but when you have YY or MM etc. then it's not good.

**Comment by dasgarner** [comment]
This should be solved with the latest Pull - can you retry that please :wink:

**Comment by alexharrington** [comment]
This also affects the bandwidth chart on the Status homepage
