### ISSUE TITLE
live table edit

### ISSUE THREAD

**Issue by tali1974** [xibosignage/xibo#563]
Hi.. can we have "live table edit" in the future release , Something like this "http://demos.9lessons.info/table_edit/TableEdit.htm" on the fadeIN/FadeOut (Image duration and transition)

That will be very helpful. Today i have to open every image and change fadeIN/FadeOut times...

Regards
T

**Comment by dasgarner** [comment]
Please discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
