### ISSUE TITLE
I want to use  xibo with postgresSql   

### ISSUE THREAD

**Issue by sasaxibo** [xibosignage/xibo#564]
i want use xibo using postgres so plz tell me what changes will occurs and in which file exact changes will i do, its urgent

i have self tried but problem in Authenticate() and rend() function plz guide me

sachin.jadhao.external@atos.net

(India) 91 7710947548

**Comment by sasaxibo** [comment]
Dear Founder and Co Founder of XIBO plz provide me installable zip or tar file for XIBO with POSTGRES Sql

**Comment by sasaxibo** [comment]
Dear i want all changes Step By Step Plz

**Comment by dasgarner** [comment]
Please discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
