### ISSUE TITLE
want to change background (theme) of whole XIbo 

### ISSUE THREAD

**Issue by sasaxibo** [xibosignage/xibo#565]
Dear hi

i want to change background (theme) of whole XIbo  plz guide me where exact changes i will do Urgent

Sachin Jadhao 

sachin.jadhao.external@atos.net

(India) 91 7710947548

**Comment by sasaxibo** [comment]
wanted all Required Changes Step by Step plz

**Comment by dasgarner** [comment]
Please discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
