### ISSUE TITLE
Database limits

### ISSUE THREAD

**Issue by designlubbock** [xibosignage/xibo#567]
Hello,

How is it possible to install a CMS and limit the active display count, and space / bandwith ?
Please let me know.

Know this will be an edit most likely in the MySQL Database.

Thank so much !

**Comment by dasgarner** [comment]
Hi,

Yes you can adjust these 3 settings:

 - MAX_LICENSED_DISPLAYS
 - LIBRARY_SIZE_LIMIT_KB
 - MONTHLY_XMDS_TRANSFER_LIMIT_KB

If you could discuss new things on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
