### ISSUE TITLE
Option for permissions to inherit from parent, default to group or default everyone

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#571]
Use case:

There are a group of users that have permissions to collaborate on a layout. One user adds a new region, another user adds some media to an existing region and both of these alterations are hidden from group because all new items default to "owner permissions only".

We already have a default "everyone" permission on new layouts and new media, however this only applies to those two objects. It should be extended with the below additional options and also apply to Regions, Playlists and Widgets.

Additional Options:
 - Everyone (public)
 - Group (all users group memberships have access)
 - Inherit from parent
 - Private (owner only)

It would be even better if view/edit/delete could be specified for each of those options, however this might make it too complex.

**Comment by laercionit** [comment]
Great!
