### ISSUE TITLE
Windows CMS not saving settings

### ISSUE THREAD

**Issue by pieternel** [xibosignage/xibo#575]
Hi Guys, maybe someone can assist please. I have upgraded from 1.7.3 to 1.7.4 now i have not been working with it long, but what i found is that settings are not being saved.
Example - under the DESIGN LAYOUT
When inserting HTML and script the gear on the save button spins for ever and does not save.
The second area where I have noticed the same thing is trying to add forecast. It does not save, the gear spins continuously.

Thanks for your time, any suggestions?

**Comment by dasgarner** [comment]
Hi,

We will need you to follow the report fault process in the CMS so we can get some logs and then open a topic over on our community forum.

Please discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
