### ISSUE TITLE
Windows Scheduled Task

### ISSUE THREAD

**Issue by designlubbock** [xibosignage/xibo#578]
Hello,

setup scheduled task with

C:\wamp\bin\php\php5.5.12\php.exe

arguments

-f C:\wtxdigital\maintenance.php secret

comes back with 0xff when run ...

any help is appreciated ...
Running Windows 10 as OS

**Comment by dasgarner** [comment]
lease discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
