### ISSUE TITLE
Scheduling an event longer than the repeat time.

### ISSUE THREAD

**Issue by StephenRoddick** [xibosignage/xibo#584]
In Xibo 1.7.4 it is possible to schedule an event to have a longer duration that it's repeat time.

I had a user schedule an item to repeat every hour that had a scheduled duration of 15 years.  Attempting to access the schedule for the display group that the user had scheduled this to was effectively impossible as the page was taking forever to load the hundreds (if not thousands) of recurring events it had to try to display on each day.

In the end to fix this I had to 
1. Rename the display group
2. Remove it's members
3. Create a new display group with the old name 
4. Add the displays back to the new group
5. Reschedule the items to the new display group.

At that point I was still unable to delete this display group as it still had things scheduled to it.  I have since dealt with this problem via the database (I know this isn't supported or advisable).

My point is being able to schedule an event to have a duration longer than it's repeat time should not be possible and should be part of the schedule validation to prevent the above issue from happening.

**Comment by dasgarner** [comment]
Scheduling an event with a longer duration than its repeat time is a valid use case of the scheduler - although I admit it is slightly odd.

You can use it to create staggered sets of events to add a Campaign/Layout to the schedule more than once.

I think you would have experienced the same issue with a repeat every hour for 15 years - we've got an item somewhere with a plan to deal with it (basically by generating only a set amount in advance)

Please post future questions [here](https://community.xibo.org.uk).
