### ISSUE TITLE
Remove "Loop" option for Regions

### ISSUE THREAD

**Issue by newburns** [xibosignage/xibo#586]
According to #151 we no longer need the Loop option for a region on the Windows Player.
If I understand the new feature, you can add a duration to the region for the total Layout duration, which will cause that region to loop.
Is that how it works? Will the total Layout duration be displayed when editing a region, so that you can adjust item durations to match the total Layout duration?
Can we remove the loop option in the Region options?

**Comment by dasgarner** [comment]
The two things aren't related - the layout duration will be the duration of the longest region, which is the duration of its media.

Loop determines whether the region should start playing from the beginning once its reached the end of its media.

Please post questions [here](https://community.xibo.org.uk) so we can keep this for bugs only. Thanks!
