### ISSUE TITLE
The name cannot be longer than 100 characters

### ISSUE THREAD

**Issue by mbreckers** [xibosignage/xibo#595]
Getting this error when importing a layout from 1.7.4 into 1.8 alpha.

"The name cannot be longer than 100 characters"

Sometimes fails, sometimes doesnt

![image](https://cloud.githubusercontent.com/assets/8761613/10336636/0a84c574-6cf2-11e5-890d-c62486dd32dc.png)

And I cant see anything that informative in the log:

![image](https://cloud.githubusercontent.com/assets/8761613/10336695/8b32b96a-6cf2-11e5-8d9a-888ea97172aa.png)

**Comment by dasgarner** [comment]
Would it be possible to provide the export you are trying? if so, dan at springsignage.com

**Comment by dasgarner** [comment]
I am pretty sure this has all been tidied up long ago, so I am closing this out. If it isn't resolved, please post on our [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can. Thanks!
