### ISSUE TITLE
[Tag|Namespace] seems to not work well in 1.8

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#598]
So that's what happens to the designer when you use it
![image](https://cloud.githubusercontent.com/assets/12148978/10370263/ef1e04b4-6dd5-11e5-8d6f-3da8851193cb.png)

**Comment by dasgarner** [comment]
Does it happen every time you use it? Or is this with a specific feed?

**Comment by PeterMis** [comment]
I think we can close it, it seems to be fine in general and with this 'weird' one it ok now too (no error) just like in 1.7
