### ISSUE TITLE
New Ubuntu client when it will be released ?

### ISSUE THREAD

**Issue by skonsoft** [xibosignage/xibo#604]
Hello,

We are working with our clients that prefers Ubuntu client. You have stopped the developpement and we are in very bad situation... Now we are using Android client but it's not very fast as ubuntu client.

Please have you a plan when the new ubuntu client will be released ?

We are OK to BUY it if you develop it !!

Thank you a lot !

**Comment by dasgarner** [comment]
There is a discussion on this here: https://community.xibo.org.uk/t/replacement-player-for-the-discontinued-ubuntu-python-client/77

Please discuss this on [community.xibo.org.uk](http://community.xibo.org.uk) before raising on here. GitHub is now a **verified bug tracker** only.
