### ISSUE TITLE
[1.8] Issue with preview enabled in video module

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#609]
When you have preview enabled in video module, it will download {{id}}.mp4 0kb file every time you open(or refresh) the layout designer with video on it.

Also it seems that preview for video isn't really working, but scheduled layout is fine.

**Comment by PeterMis** [comment]
Part about downloading this 0kb file is fixed, although it still doesn't load the video in preview

**Comment by dasgarner** [comment]
you mean Layout Preview? that will most likely be the codec of the video you are testing... only HTML5 `<video>` tag videos are supported in preview.
