### ISSUE TITLE
1.7 Error

### ISSUE THREAD

**Issue by mymactek** [xibosignage/xibo#61]
Downloaded the 1.7 release on windows. Updated server to 1.7 as well.
On clien. Wont download anything. Keeps saying " execption of type " Service.web.services.protocol.
"Unable to get list of files "

Please assist.
Thanks

**Comment by dasgarner** [comment]
Can you have a look in your CMS logs to see if there are any errors listed? That error is being generated by the CMS and passed to the player.

**Comment by mymactek** [comment]
Says "no errors"On Mon, Jan 26, 2015 at 12:54 PM,  xibosignage/xibo <reply@reply.github.com> wrote:            Can you have a look in your CMS logs to see if there are any errors listed? That error is being generated by the CMS and passed to the player.

**Comment by mymactek** [comment]
No log messages for display On Mon, Jan 26, 2015 at 12:54 PM,  Mac Tek <mymactek@gmail.com> wrote:            Says "no errors"On Mon, Jan 26, 2015 at 12:54 PM,  xibosignage/xibo <reply@reply.github.com> wrote:            Can you have a look in your CMS logs to see if there are any errors listed? That error is being generated by the CMS and passed to the player.

**Comment by dasgarner** [comment]
I can see where the error is being raised and unfortunately it is not logged against the display (although it should be).

Can you take a look in the Advanced page at the global CMS log?

**Comment by mymactek** [comment]
Under advanced/log is blankOn Mon, Jan 26, 2015 at 12:56 PM,  xibosignage/xibo <reply@reply.github.com> wrote:            I can see where the error is being raised and unfortunately it is not logged against the display (although it should be).

Can you take a look in the Advanced page at the global CMS log?

**Comment by dasgarner** [comment]
Can you try:

 - Changing the filter on the log page to go back further than 120 seconds
 - Going to the Modules page and clicking Verify Modules in the top right corner

**Comment by mymactek** [comment]
went to Log page :
Interval : 24 Hours
Total errors : 31,828

This is the earliest logs from yesterday that it will show.....
This is page 1,2,3 ( 30 logs )
If you need anything else please let me know so we can get this fixed. This is a DEMO server/test server, but it does run off our Production server, just a different URL / Folder.

Thanks so much !

372	2015-01-26 15:45:11	CMS			<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
373	2015-01-26 15:45:14	CMS			<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
374	2015-01-26 15:45:14	CMS	index		<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
375	2015-01-26 15:45:20	CMS	coreconceptsoverview		<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
376	2015-01-26 15:45:20	CMS	coreconceptsoverview		<errormsg>Requested page does not exist</errormsg>
<errornum>256</errornum>
<errortype>User Error</errortype>
<scriptname>C:\dssserver\www\demo\lib\include.php</scriptname>
<scriptlinenum>181</scriptlinenum>
377	2015-01-26 15:45:21	CMS	error		<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
378	2015-01-26 15:45:23	CMS	statusdashboard		<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
379	2015-01-26 15:45:42	CMS			<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
380	2015-01-26 15:46:12	CMS			<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
381	2015-01-26 15:46:12	CMS			<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
382	2015-01-26 15:46:12	CMS			<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
383	2015-01-26 15:46:12	CMS			<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
384	2015-01-26 15:46:12	CMS	module		<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
385	2015-01-26 15:46:12	CMS			<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
386	2015-01-26 15:46:13	CMS			<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
387	2015-01-26 15:46:13	CMS			<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
388	2015-01-26 15:46:13	CMS			<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
389	2015-01-26 15:46:14	CMS	module		<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
390	2015-01-26 15:46:15	CMS	Media	AddModuleFile	There is no active transaction
391	2015-01-26 15:46:15	CMS	Media	AddModuleFile	There is no active transaction
392	2015-01-26 15:46:15	CMS	Media	AddModuleFile	There is no active transaction
393	2015-01-26 15:46:15	CMS	Media	AddModuleFile	There is no active transaction
394	2015-01-26 15:46:15	CMS	Media	AddModuleFile	There is no active transaction
395	2015-01-26 15:46:15	CMS	Media	AddModuleFile	There is no active transaction
396	2015-01-26 15:46:15	CMS	Media	AddModuleFile	There is no active transaction
397	2015-01-26 15:46:15	CMS	module		<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
398	2015-01-26 15:46:16	CMS			<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
399	2015-01-26 15:46:20	CMS	displayprofile		<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
400	2015-01-26 15:46:20	CMS			<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>
401	2015-01-26 15:46:24	CMS	license		<errormsg>Language not supported. en_GB</errormsg>
<errornum>1024</errornum>
<errortype>User Notice</errortype>
<scriptname>C:\dssserver\www\demo\lib\app\translationengine.class.php</scriptname>
<scriptlinenum>86</scriptlinenum>

**Comment by mymactek** [comment]
When trying to "Verify" modules ... following Logs populated ...

32202	2015-01-27 08:26:55	CMS			<errormsg>SoapFault::SoapFault() expects at least 2 parameters, 1 given</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\dssserver\www\demo\lib\service\xmdssoap4.class.php</scriptname>
<scriptlinenum>689</scriptlinenum>
32201	2015-01-27 08:26:55	CMS			SQLSTATE[42S22]: Column not found: 1054 Unknown column 'media.moduleSystemFile' in 'where clause'
32200	2015-01-27 08:26:52	CMS			SQLSTATE[42S22]: Column not found: 1054 Unknown column 'media.moduleSystemFile' in 'where clause'

**Comment by dasgarner** [comment]
It looks very much like you have a corrupted upgrade somehow - which certainly wont be helping with the situation at all.

The SQL below should have run in `81.sql` when you did the upgrade:
``` sql
ALTER TABLE  `media` ADD  `moduleSystemFile` TINYINT NOT NULL DEFAULT  '0';
```

So the last error message you reported it really strange and implies that the upgrade did not complete successfully.

**Comment by mymactek** [comment]
Which is actually weird, because I did an upgrade and it kept saying" can not delete install.php , when it did. So I created a new directory, and sql database and reset up completely... Now all the errors.Thanks for the help On Wed, Jan 28, 2015 at 2:55 AM,  xibosignage/xibo <reply@reply.github.com> wrote:            It looks very much like you have a corrupted upgrade somehow - which certainly wont be helping with the situation at all.

The SQL below should have run in 81.sql when you did the upgrade:

ALTER TABLE  `media` ADD  `moduleSystemFile` TINYINT NOT NULL DEFAULT  '0';

So the last error message you reported it really strange and implies that the upgrade did not complete successfully.

**Comment by dasgarner** [comment]
Just double checked (just in case) that the `structure.sql` file, which is run on installation has got that column in it - and it does:

``` sql
`moduleSystemFile` tinyint(1) NOT NULL DEFAULT '0',
```

If you were already at the end of the installation when you got "cannot delete install.php", then it would be safe to delete that manually. Interestingly it checks it is able to delete it at the first step of the install - so as you say, odd!

**Comment by mymactek** [comment]
When I upgraded the system from 1.7alpha2, it did the install properly, then it kept loading the " upgrade" page. At the end it would state error: can not delete install.php. So once I manually deleted it, and the other time it did properly - but still kept loading the upgrade page.

What do you think I should do to try and clear the errors ?
We have a production server, same one this is hosted on, with 1.6.x running over 30 screens. When I upgrade it to 1.7 and the clients - need to make sure wont have any errors.

Also any update on when the Android 1.7 final will be released ?

Thanks !

**Comment by mymactek** [comment]
Under Report Fault : Collect Data

This is the information from the .txt the system created ..

--------------------------------------
Environment Checks
--------------------------------------
<table class="table">
    <thead>
        <tr>
                                    <th class="group-false">Item</th>
                        <th class="group-false" data-sorter="tickcross">Status</th>
                        <th class="group-false">Advice</th>
                                </tr>
    </thead>
    <tbody>
                <tr >
                                                <td>PHP Version</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP version 5.3.3 or later required. Detected 5.5.12</td>
                                            </tr>
                <tr >
                                                <td>File System Permissions</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>Write access required for settings.php and install.php</td>
                                            </tr>
                <tr >
                                                <td>MySQL database (PHP MySql)</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>MySQL support must be enabled in PHP.</td>
                                            </tr>
                <tr >
                                                <td>MySQL database (PDO MySql)</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PDO support with MySQL drivers must be enabled in PHP.</td>
                                            </tr>
                <tr >
                                                <td>JSON Extension</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP JSON extension required to function.</td>
                                            </tr>
                <tr >
                                                <td>SOAP Extension</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP SOAP extension required to function.</td>
                                            </tr>
                <tr >
                                                <td>GD Extension</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP GD extension to function.</td>
                                            </tr>
                <tr >
                                                <td>Session</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP session support to function.</td>
                                            </tr>
                <tr >
                                                <td>FileInfo</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>Requires PHP FileInfo support to function. If you are on Windows you need to enable the php_fileinfo.dll in your php.ini file.</td>
                                            </tr>
                <tr >
                                                <td>PCRE</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP PCRE support to function.</td>
                                            </tr>
                <tr >
                                                <td>Gettext</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP Gettext support to function.</td>
                                            </tr>
                <tr >
                                                <td>Calendar Extension</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP Calendar extension to function.</td>
                                            </tr>
                <tr >
                                                <td>DOM Extension</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP DOM core functionality enabled.</td>
                                            </tr>
                <tr >
                                                <td>DOM XML Extension</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP DOM XML extension to function.</td>
                                            </tr>
                <tr >
                                                <td>Mcrypt Extension</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>PHP Mcrypt extension to function.</td>
                                            </tr>
                <tr >
                                                <td>Allow PHP to open external URLs</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>You must have allow_url_fopen = On in your PHP.ini file for RSS Feeds / Anonymous statistics gathering to function.</td>
                                            </tr>
                <tr >
                                                <td>DateTimeZone</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>This enables us to get a list of time zones supported by the hosting server.</td>
                                            </tr>
                <tr >
                                                <td>Large File Uploads</td>
                                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                                <td>Support for uploading large files is recommended.</td>
                                            </tr>
            </tbody>
</table>

--------------------------------------
LOG Dump
--------------------------------------
Date,Page,Function,Message
"2015-01-28 08:39:09","","","SQLSTATE[42S22]: Column not found: 1054 Unknown column 'media.moduleSystemFile' in 'where clause'"
"2015-01-28 08:39:09","","","<errormsg>SoapFault::SoapFault() expects at least 2 parameters, 1 given</errormsg>
<errornum>2</errornum>
<errortype>Warning</errortype>
<scriptname>C:\dssserver\www\demo\lib\service\xmdssoap4.class.php</scriptname>
<scriptlinenum>689</scriptlinenum>
"
"2015-01-28 08:39:09","","","SQLSTATE[42S22]: Column not found: 1054 Unknown column 'media.moduleSystemFile' in 'where clause'"

--------------------------------------
Display Dump
--------------------------------------
DisplayID: 1
Display: Demo Windows Test
Default Layout: Default Layout
Logged In: 1
Last Accessed: 1422455950
Interleave: 0
Licensed: 1


--------------------------------------
Settings Dump
--------------------------------------
Setting: MEDIA_DEFAULT - Value:   private

Setting: LAYOUT_DEFAULT - Value:   private

Setting: defaultUsertype - Value:   User

Setting: userModule - Value:   module_user_general.php

Setting: defaultTimezone - Value:   America/Chicago

Setting: mail_to - Value:   mail@yoursite.com

Setting: mail_from - Value:   mail@yoursite.com

Setting: jpg_length - Value:   10

Setting: ppt_length - Value:   10

Setting: swf_length - Value:   10

Setting: audit - Value:   error

Setting: LIBRARY_LOCATION - Value:   XiboDemo2\

Setting: HELP_BASE - Value:   http://www.xibo.org.uk/manual/

Setting: PHONE_HOME - Value:   On

Setting: PHONE_HOME_URL - Value:   http://www.xibo.org.uk/stats/track.php

Setting: PHONE_HOME_DATE - Value:   0

Setting: SERVER_MODE - Value:   Production

Setting: MAINTENANCE_ENABLED - Value:   Off

Setting: MAINTENANCE_EMAIL_ALERTS - Value:   On

Setting: MAINTENANCE_KEY - Value:   changeme

Setting: MAINTENANCE_LOG_MAXAGE - Value:   30

Setting: MAINTENANCE_STAT_MAXAGE - Value:   30

Setting: MAINTENANCE_ALERT_TOUT - Value:   12

Setting: SHOW_DISPLAY_AS_VNCLINK - Value:   0

Setting: SHOW_DISPLAY_AS_VNC_TGT - Value:   _top

Setting: MAINTENANCE_ALWAYS_ALERT - Value:   Off

Setting: SCHEDULE_LOOKAHEAD - Value:   On

Setting: REQUIRED_FILES_LOOKAHEAD - Value:   172800

Setting: REGION_OPTIONS_COLOURING - Value:   Media Colouring

Setting: LAYOUT_COPY_MEDIA_CHECKB - Value:   Unchecked

Setting: MAX_LICENSED_DISPLAYS - Value:   0

Setting: LIBRARY_MEDIA_UPDATEINALL_CHECKB - Value:   Unchecked

Setting: USER_PASSWORD_POLICY - Value:   

Setting: USER_PASSWORD_ERROR - Value:   

Setting: MODULE_CONFIG_LOCKED_CHECKB - Value:   Unchecked

Setting: LIBRARY_SIZE_LIMIT_KB - Value:   0

Setting: MONTHLY_XMDS_TRANSFER_LIMIT_KB - Value:   0

Setting: DEFAULT_LANGUAGE - Value:   en_GB

Setting: TRANSITION_CONFIG_LOCKED_CHECKB - Value:   Unchecked

Setting: GLOBAL_THEME_NAME - Value:   default

Setting: DEFAULT_LAT - Value:   51.504

Setting: DEFAULT_LONG - Value:   -0.104

Setting: SCHEDULE_WITH_VIEW_PERMISSION - Value:   No

Setting: SETTING_IMPORT_ENABLED - Value:   1

Setting: SETTING_LIBRARY_TIDY_ENABLED - Value:   1

Setting: SENDFILE_MODE - Value:   Off

Setting: EMBEDDED_STATUS_WIDGET - Value:   

Setting: PROXY_HOST - Value:   

Setting: PROXY_PORT - Value:   0

Setting: PROXY_AUTH - Value:   

Setting: DATE_FORMAT - Value:   Y-m-d

Setting: DETECT_LANGUAGE - Value:   1

Setting: DEFAULTS_IMPORTED - Value:   1

Setting: FORCE_HTTPS - Value:   0

Setting: ISSUE_STS - Value:   0

Setting: STS_TTL - Value:   600

Setting: MAINTENANCE_ALERTS_FOR_VIEW_USERS - Value:   0

Setting: CALENDAR_TYPE - Value:   Gregorian


--------------------------------------
Sessions Dump
--------------------------------------
UserAgent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36
RemoteAddress: XXX.XXX.XXX.XXX -->Hidden
Session Data
pagename|s:5:"fault";token|s:32:"e286d92ad4069af2f6c8caffb86132f7";token_timeout|i:1422455986;message|s:0:"";userid|s:1:"1";username|s:10:"dsslubbock";usertype|s:1:"1";display|a:5:{s:14:"filter_display";s:0:"";s:19:"filter_displaygroup";i:0;s:20:"filter_showThumbnail";i:0;s:18:"filter_autoRefresh";i:0;s:13:"DisplayFilter";i:0;}gridToken|s:32:"7113103767d1d2acd81c200be21b8f2b";gridToken_timeout|i:1422455891;
----

**Comment by dasgarner** [comment]
Regarding Android - its released and there is a blog post over on the SS homepage :)

Regarding the upgrade, if I were you i'd definitely take a fresh backup of production and run through the upgrade on a test environment to make sure it works from 1.6 to 1.7.

I've just released some new 1.7.0 files which contain the fixes for the SQL statements that caused all these issues

**Comment by mymactek** [comment]
Alright awesome thank you so much. Will install a new demo system for which we currently use - and run the update make sure no problems. Will give the Android a run !

Thanks so much, and love the work Yal' Do !

**Comment by dasgarner** [comment]
Thanks!! Hope everything goes smoothly for you.

**Comment by mymactek** [comment]
New server . 1.6.3 --> upgrade to 1.7
Success, working fine.
Thanks !
