### ISSUE TITLE
Download/Update window simplification

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#619]
The download/upload window date/times are vastly complicated, the CMS stores a unix time stamp in local time for the time selected in the timepicker.

This is transferred to the Players, at which point they have to reverse engineer the date/time so that they get the time in their own local time (the same time).

We should change the time pickers to save the time in the H:i format - the players can then parse that format and set a local date object to have those Hours and Minutes.

This will be a breaking change in the Windows Player - Android Player will default to no window when a unixtime stamp is provided.

**Comment by PeterMis** [comment]
https://github.com/xibosignage/xibo/issues/638

**Comment by dasgarner** [comment]
Updated the CMS side - will need to update the windows and android players to suit.
