### ISSUE TITLE
Clock Date doesn't work

### ISSUE THREAD

**Issue by AllieKat** [xibosignage/xibo#62]
I cannot get the date on the clock to work. I posted an issue with some details on Launchpad, but now that we're here I figured I'd bring it up and mention that it still doesn't display for me.

**Comment by dasgarner** [comment]
This is you? https://answers.launchpad.net/xibo/+question/260958

So in summary, it displays fine in the preview on the CMS, when you find the file in the library, it displays fine when you open it in IE - but it doesn't display fine when in the player.

I can only imagine this is the "old IE rendering engine issue", which is a bit unfortunate. Can you try adding a new DWORD in your registry on the player PC?

`HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_BROWSER_EMULATION\XiboClient.exe`

with the value:

`decimal 9999`

You'll need to restart the player for it to take effect.

**Comment by AllieKat** [comment]
Yup, I go by Allie now, though I was using an OLD launch pad under my legal name... Yeah. Anyway, that did nothing. Also, switching to CEF did nothing (except make the rendering when it opens really slow and block by block - it takes a few seconds. But still no clock). If I could figure out how to post a ZIP I would post the layout I am using.

**Comment by AllieKat** [comment]
https://www.dropbox.com/s/tkqpt2wtejts7t3/export_default-layout.zip?dl=0

**Comment by dasgarner** [comment]
Fair enough :-)

I'll try out the file and see

**Comment by dasgarner** [comment]
The clock is on top of the date

Try deleting your date region altogether and using the following as the source for your clock region:

``` html
<p><span style="font-size:96px;"><span style="color:#000000;"><span style="font-family:arial,helvetica,sans-serif;"><strong>[HH:mm]</strong></span></span></span></p>

<p><span style="color: rgb(0, 0, 0); font-family: arial, helvetica, sans-serif; font-size: 48px;">[YYYY-MM-DD]</span></p>
```

**Comment by AllieKat** [comment]
Okay, I just put it all in one. I didn't think it would matter since other overlapping regions seem to render just fine.

**Comment by AllieKat** [comment]
P.S. I had hoped that when I got this figured out it might fix the exclamation mark on the display status. It didn't. Any ideas?

**Comment by dasgarner** [comment]
Yes - unfortunately I do... there was a small problem with the first MSI I put out... I switched it quickly in the hope nobody would notice... but of course they did.

If you re-download, un-install and reinstall it will be fixed.


FYI - overlapping regions aren't supported at all in the windows player - they used to be in the Ubuntu player and we will be working to reintroduce them.
