### ISSUE TITLE
XiboClient AppCrash & background problem

### ISSUE THREAD

**Issue by ljoets** [xibosignage/xibo#624]
Hello,
Yesterday, my XiboClient crashed with this message :
![img_0299](https://cloud.githubusercontent.com/assets/11474581/10921197/68f19550-8274-11e5-83c2-c289feacd8db.jpg)
Client is running on W7x86 up-to-date :-\
I don't know if it is related, but my background seems to have a a displaying problem :
![img_0300](https://cloud.githubusercontent.com/assets/11474581/10921269/d3690cd8-8274-11e5-841c-310edb922009.jpg)
Everything worked fine before our 2 week vacation :-(

**Comment by alexharrington** [comment]
Please can you post support requests over on the Community site: https://community.xibo.org.uk

Issues is for confirmed bugs that have been discussed there previously only.

Thank you
