### ISSUE TITLE
Layout options>background>add image not working

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#627]
When you want to upload new image in options>background>add image form, it will upload correctly, but when you click the 'Set background' button it won't work as intended, returning the following error:
:{"files":[{"name":"1446717700-4315","size":0,"type":"","error":"No file was uploaded"}]}"

If you use existing image as a background it works fine, it seems that the problem is with that one button.

Original topic with this issue:
https://community.xibo.org.uk/t/error-when-uploading-setting-background/3967
and 
https://community.xibo.org.uk/t/bug-with-uploading-image/4633

**Comment by Jimmy89** [comment]
It might be related with the new MySQL version I am running. Especially since the error message clearly contains type: "" and I get the error message: Warning: 1265 Data truncated for column 'type' at row 1

**Comment by alexharrington** [comment]
Also referenced here:
https://community.xibo.org.uk/t/bug-with-uploading-image/4633
