### ISSUE TITLE
Ticker skips the last item from the feed

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#644]
It seems that when there is only ticker on the layout, in some cases it does not display the last item from the feed.
So for example it displays 11 items (in single mode, 1 item per page) then skips the 12th one and goes back to the first item.

More details and current workaround:
https://community.xibo.org.uk/t/ticker-is-not-completely-displayed/4233

**Comment by laercionit** [comment]
Hello Peter,

I would just like to know the problem of reason, it is something that
should be repaired in the CMS or the Android Client?

Any predictions to include this adjustment has to version 1.8?

**Comment by dasgarner** [comment]
We've not investigated it yet - but I suspect it is a rounding error when the number of items doesn't fit exactly into the duration (it should round down, not up)... that is guess though

**Comment by laercionit** [comment]
In our test, the ticker has 12 items, they are with the option (duration
per item) of 6 sec...

**Comment by dasgarner** [comment]
Our working theory is that the transition speed is adding a short period of time to each item as it cycles - although this is only a small extra delay per item, when added up over multiple items it can cause a larger drift.

Fix for both series linked.

**Comment by laercionit** [comment]
Hello Dan,

I just test this item using R59 and CMS 1.7.6 and the problem still persists.
