### ISSUE TITLE
how to give  margin or border to the region inside layout

### ISSUE THREAD

**Issue by anupam9841** [xibosignage/xibo#647]
i just want to have many region inside a single layout,it is working while previewing but i need a border or margin for a particular region ...any solution plz.

**Comment by alexharrington** [comment]
Please post your support requests over on the Xibo Community site. The issue tracker is for confirmed bugs only which have been previously discussed on the Community site.

https://community.xibo.org.uk

**Comment by anupam9841** [comment]
ok,thanks
