### ISSUE TITLE
CMS video mute setting

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#648]
As with 1.7.5, the default setting for video mute is set to unmute.
To mute the video sound, we need to at least open and save the video edit form.

It could be a good idea to add some kind of global setting in CMS that will either
mute or unmute uploaded/assigned videos by default depending on user preferences

**Comment by dasgarner** [comment]
#695 fixes the root cause, which is that the setting shows the incorrect value on first load.
