### ISSUE TITLE
Calendar items won't show up...

### ISSUE THREAD

**Issue by mrbcast** [xibosignage/xibo#661]
I have been running xibo on my server for a couple of months now without any problems and suddenly it just stopped showing scheduled events.  The calendar will not show any events no matter what players or all settings I use.  Sometimes it will popup after a while but usually it's just blank spaces.  No matter if I use the days, weeks or months view.  I am on debian 7 in a virtualized container.  Please advise.  Thanks...

**Comment by alexharrington** [comment]
Please post over on the community support site. We use Github issues for tracking confirmed bugs that have been previously discussed there only. 

https://community.xibo.org.uk
