### ISSUE TITLE
Background-Color Overwrite Background-image

### ISSUE THREAD

**Issue by Jenlues** [xibosignage/xibo#67]
Hello,

in Xibo 1.6.4 you have the possibility to choose between Background-Image and Background-Color.
In Versio 1.7.0 Iam forced to choose an Background-Color.

Okay, no problem but when I intregrate a ticker, webpage or a clock the background overrides the background-image and it looks horrible.
The overwrite is in every Region of the Template.

I tried to work already with the new z-index but it doesnt help.

**Comment by dasgarner** [comment]
Just so other people can see the answer you received on Launchpad - it was:

From Alex:
That's not the case. The background colour only affects the layout. It
doesn't change the background colours of the regions.

If it is, then I expect you've used a PNG image as your background image
which isn't supported on the windows client, and gives that effect
