### ISSUE TITLE
Ship additional OFL fonts with the CMS

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#672]
https://community.xibo.org.uk/t/ship-ofl-fonts-as-part-of-the-cms/4525

**Comment by seal20** [comment]
Please add also fonts supporting CJK (chinese, korean and Japanese) languages. For example https://www.google.com/get/noto/ 

Thanks

**Comment by alexharrington** [comment]
My only concern with that is that to support all languages, it's nearly a 500MB download. There's no way we can include that much in the CMS download.

**Comment by dasgarner** [comment]
Have included a few standard fonts, and allowed for layout import/export to take fonts with it (effectively meaning we can supply font bundles in layout exports).

https://github.com/xibosignage/xibo-cms/pull/174
