### ISSUE TITLE
Request Screenshot broken if XMR is not configured 1.8.0a2

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#675]
If XMR isn't configured/working, then the following message comes up

![image](https://cloud.githubusercontent.com/assets/10450518/12062704/6535694e-af99-11e5-9dd8-65f6580ef834.png)

The dialogue however suggests that the Player would be requested to send a screenshot by the old method if XMR weren't available? It doesn't appear to fall back gracefully.

**Comment by dasgarner** [comment]
It intentionally removes the old method to prevent a race condition, however form message could do with some work.

**Comment by dasgarner** [comment]
Changed error to "This Player is not configured or ready to receive push commands over XMR. Please contact your administrator." and removed "The next time..." from the form.
