### ISSUE TITLE
Menu isn't rendered on 1.7.5 with MySQL 5.7.10

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#678]
See https://community.xibo.org.uk/t/admin-panel-does-not-show-navigation-bar/4601/9?u=alex

Query is here:
https://github.com/xibosignage/xibo-cms/blob/master/modules/module_user_general.php#L578

**Comment by Jimmy89** [comment]
Pull request with solution:
https://github.com/xibosignage/xibo-cms/pull/130

**Comment by alexharrington** [comment]
Jimmy. Thanks for that. Please can you sign the CLA. We wouldn't be able to merge your patch unless that were signed. Thank you.

**Comment by Jimmy89** [comment]
I am new to signing with a CLA, but it should be okay now.
About the problem: In my opinion the bug should be triggered by any database (placing an order by on a column not in the select statement is an invalid query). I am surprised earlier versions of MySQL did not throw an error. I will start to use Xibo and will report any other (possibly) incorrect query if they hit the surface.

**Comment by alexharrington** [comment]
You're the first person to mention it, and that query hasn't been modified since 2004 so it's not a general issue for most people clearly.

I don't see your CLA signature pull request. Full details on signing are here:
https://github.com/xibosignage/xibo/blob/master/CONTRIBUTING.md

**Comment by Jimmy89** [comment]
Thanks for the information, the link you provided contained clear information.
I added a CLA signature pull request: 
https://github.com/xibosignage/xibo/pull/679

**Comment by alexharrington** [comment]
Thank you. I've merged your CLA signature. When we're ready to release 1.7.6 we'll review this bug and merge in the fix.

**Comment by dasgarner** [comment]
Reviewed and Merged.

This query doesn't appear in 1.8 and doesn't need forward porting.
