### ISSUE TITLE
Database error 1.6.4 -> 1.7.0

### ISSUE THREAD

**Issue by RobKeeling** [xibosignage/xibo#68]
I have just attempted to update our system to Xibo 1.7.0, though the upgrade process failed with an error mentioning utf32 char sets.

Looking at http://stackoverflow.com/questions/15305199/error-1115-42000-at-line-29-unknown-character-set-utf32​

It seems this needs a much newer version of MySQL than the one we have installed.

There is no mention of a MySql version requirement.

It appears that the code concerned is in 82.sql 

CREATE TABLE IF NOT EXISTS `lktaglayout` (
  `lkTagLayoutId` int(11) NOT NULL AUTO_INCREMENT,
  `tagId` int(11) NOT NULL,
  `layoutId` int(11) NOT NULL,
  PRIMARY KEY (`lkTagLayoutId`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf32 AUTO_INCREMENT=1 ;

can that CHARSET be changed to utf16? safely?

**Comment by dasgarner** [comment]
Sorry - you can change it to utf8 (which is what it should be)
