### ISSUE TITLE
Add new "Current Status" display view to CMS "Displays" dropdown

### ISSUE THREAD

**Issue by nagyrobi** [xibosignage/xibo#680]
Guys, I'm checking the current status of my displays from the CMS, and I always have to jump between two views, in order to see what I need.
I'd like to add a new view type to the displays list, but so far I wasn't able to figure out how to do that.

Basicly what I'd like to see in one page as a new "Current Status" view type are the following fields:

Checkbox, ID, Display, Status, Current Layout, Storage Free, Logged in, Last accessed, Screenshot?, Thumbnail, DropDown menu

Any idea how to add this extra mod?

**Comment by alexharrington** [comment]
Please post support requests and feature requests over on the Community site: https://community.xibo.org.uk

The project uses Github Issues only for confirmed bugs and feature requests that are to be implemented that have been previously discussed there.

Thank you
