### ISSUE TITLE
German translation outdated

### ISSUE THREAD

**Issue by Speedy-Gonzalez** [xibosignage/xibo#69]
Hi,

today I installed Xibo 1.7 and I noticed that quite a few German translations are missing. So I've looked into the de.mo and saw the export date "X-Launchpad-Export-Date: 2015-01-09 12:12".
Please update the file. There are only two untranslated strings left.

Thanks.
Speedy

**Comment by dasgarner** [comment]
The translations were updated as per the release candidate because there was a new import of final strings at release time.

If you have updated some stuff in the mean time you might want to download a copy of de.mo yourself.

We will do it for the next release.

Cheers
