### ISSUE TITLE
Underscores in search filter don't seem to work

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#692]
It seems that "_" alone in filter search by name/tags doesn't have any impact.

But it's not completely ignored, so for example:

You have 2 layouts named dan and da_n
Now in search filer in name:
 _ alone won't do anything (ie it will show all layouts)
da_ will still show both layouts in this example
da_n will show only the layout named da_n which is correct

Similar for tags. 

It seems that if there is no character before and after underscore then it doesn't work correctly (ie it's pretty much ignored).

Original report: https://community.xibo.org.uk/t/cannot-use-underscores-in-search-filters-1-8-alpha2/4789

**Comment by dasgarner** [comment]
Underscores are a keyword in the same way as % - so I think its valid to keep them like they are.. Will add a manual page explaining the behaviour
