### ISSUE TITLE
Error when upgrading 1.6.4 to 1.7.0

### ISSUE THREAD

**Issue by RobKeeling** [xibosignage/xibo#70]
An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 80. Error Message = [SQLSTATE[HY000]: General error: 1025 Error on rename of '.\xibo\schedule_detail' to '.\xibo\#sql2-538-4cf4a' (errno: 152)]

I have made the change of UTF32 to UTF8 in 82.sql but now get the error above.

**Comment by JELedoux** [comment]
I had a similar error upgrading from 1.6.4 to 1.7.0.  I couldn't fix it and had to go back and re-install 1.6.4.

**Comment by dasgarner** [comment]
In 80.sql on line 117 there are the following statements:

``` sql
ALTER TABLE  `schedule` ADD  `DisplayOrder` INT NOT NULL DEFAULT '0';

UPDATE `schedule` SET DisplayOrder = (SELECT MAX(DisplayOrder) FROM `schedule_detail` WHERE schedule_detail.eventid = schedule.eventid);

ALTER TABLE  `schedule_detail` DROP FOREIGN KEY  `schedule_detail_ibfk_9` ;
ALTER TABLE `schedule_detail` DROP `CampaignID`;
ALTER TABLE `schedule_detail` DROP `is_priority`;
ALTER TABLE `schedule_detail` DROP `DisplayOrder`;
```

These operate on the `schedule_detail` table and adjust it so that it is less complex. I would bet on one of these statements being the issue, most likely the UPDATE statement if you have a large schedule_detail table.

That SQL does need to run, but you could try pulling that out of the `80.sql` file and running those statements manually against your installation **before** you run the main upgrade.

**Comment by JELedoux** [comment]
Hi Dan,

I am getting this error when I attempting to upgrade from 1.6.4 to 1.7.0.

An error occurred populating the database. Statement number: 56. Error Message = [SQLSTATE[HY000]: General error: 1005 Can't create table 'lpdxibox_xibodb.#sql-10bf7_30a5c6' (errno: 121)]

Any suggestions?

Thank you,

John Eric Ledoux
IT Specialist
Londonderry Police Department
268A Mammoth Road
Londonderry, NH  03053
Tel: (603) 432-1110
Fax: (603) 432-1117
Email: jledoux@londonderrynh.org

**Comment by dasgarner** [comment]
there are some instructions towards the end of #177 where we are trying to work out which statement is causing the issue - that would also be useful to know in your case.

Can you join the other issue and try the suggestions?

**Comment by JELedoux** [comment]
Will do.

Thank You,

J. Eric Ledoux
Londonderry Police Department
