### ISSUE TITLE
Announcement System

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#701]
Announcement system for creating/presenting CMS announcements:

- [x] Admin Interface
- [x] Notification Centre
- [x] Email Alerts

## Admin Interface
Page/Grid with Add/Edit/Delete functionality for announcements. Add/Edit forms to have a simple text editor with options for:

 - Target User / User Group
 - Target Release Date
 - Checkbox for email delivery
 - Checkbox for delivery through a Widget
 - Checkbox for "interrupt mode" which forces a full screen announcement on navigate

## Notification Centre
Accessible from the header, with an icon indicating new announcements. Drop down tray containing announcement titles. Click through to a full announcement popup.

## Email Alerts
Modify maintenance to send email announcements where there is an email address and the announcement is marked for email delivery.

**Comment by laercionit** [comment]
Hello Dan,

Currently use the Intercom.IO to perform these functions.
It is a tool used worldwide to Saas.

I think the ideal would be to develop a module that integrates with the intercom.
If you do not know the system, I recommend taking a look, you will like.

https://www.intercom.io/

**Comment by dasgarner** [comment]
Hi Laercio,

The particular system mentioned here is in response to some users specific needs to communicate with their employees.

Going forwards it can/will also be used for system health announcements, library usage warnings, etc, etc.

A feature topic in community for Intercom integration would be interesting

**Comment by laercionit** [comment]
Dan, the communications with users of the system can be performed by the intercom. I really like the system, I think it would be a great upgrade to the Xibo provide Customer Success concept.

Our NPS (Net Promoter Score) currently is in 62, which shows that the methodology works.

**Comment by dasgarner** [comment]
I appreciate it might be good for your use case - which is why I suggested creating another Feature topic for it - however not all users of Xibo are going to want to pay to use Intercom (it is quite expensive).
