### ISSUE TITLE
Better regex removal of URLs for Twitter Module

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#703]
See: https://community.xibo.org.uk/t/twitter-feed-removing-url-confusion/4866

Suggested Regex: 

```
~(?i)\b((?:[a-z][\w-]+:(?:/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:\'".,<>?«»“”‘’]))~
```

Replace at: https://github.com/xibosignage/xibo-cms/blob/master/modules/twitter.module.php#L901

**Comment by solarbug** [comment]
ok so i removed this section as you noted above

`   // Handle URL removal if requested
                        if ($removeUrls == 1) {
replaced this line : ====    $tweetText = preg_replace("((https?|ftp|gopher|telnet|file|notes|ms-help):((\/\/)|(\\\\))+[\w\d:#\@%\/;$()~_?\+-=\\\.&]*)", '', $tweetText);
  }
`

and replaced it with these lines
the first two are optional if you want to remove @someone and or #hastags 
i can copy and paste and text from others examples.   So this makes for just straight text twitters - no hashtag, no bit.ly links, no @someones and i Have no idea how it works really but it does. 

`    // Handle URL removal if requested
                        if ($removeUrls == 1) {
                        
   $tweetText = preg_replace('/(\s+|^)@\S+/', '', $tweetText);  // remove @someone//
   $tweetText = preg_replace('/(\s+|^)#\S+/', '', $tweetText);   // remove hashtags//
   // taken from http://daringfireball.net/2010/07/improved_regex_for_matching_urls
    $urlRegex = '~(?i)\b((?:[a-z][\w-]+:(?:/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:\'".,<>?«»“”‘’]))~';
     $tweetText  = preg_replace($urlRegex, '', $tweetText); // remove urls
                         
                         }`

try it if you like, i'd be so thrilled if you were able to use it.    
remove @someone and or hashtags could be an optional check box.  just like the URL Choice. 

and personally I'd like to also remove  the "RT" also for retweet but  I couldn't figure that part out.  - I"m sure its fairly easy but again i'm not a coder.  and no one had done an example of this so i could copy the syntax exactly and just put in search "RT space" and replace with nothing, this was pretty complicated for me as it was.

**Comment by solarbug** [comment]
replacement code 

` $tweetText = preg_replace('/(\s+|^)@\S+/', '', $tweetText);  // remove @someone//
						   $tweetText = preg_replace('/(\s+|^)#\S+/', '', $tweetText);   // remove hashtags//
						   // taken from http://daringfireball.net/2010/07/improved_regex_for_matching_urls
						     $urlRegex = '~(?i)\b((?:[a-z][\w-]+:(?:/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:\'".,<>?«»“”‘’]))~';
						     $tweetText  = preg_replace($urlRegex, '', $tweetText); // remove urls`

**Comment by dasgarner** [comment]
Thank you so much - i've done this in 1.8 release and will patch into 1.7 in due course. The commit message will be along in a bit for you to review.
