### ISSUE TITLE
Transition durations aren't taken into account when calculating Layout Duration

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#705]
see https://community.xibo.org.uk/t/in-transition-within-duration-of-region-out-transition-added-to-duration/4867

**Comment by laercionit** [comment]
The link was wrong, but I could find in the community

**Comment by dasgarner** [comment]
The link seems to be working OK for me - it takes me to a topic titled: "https://community.xibo.org.uk/t/in-transition-within-duration-of-region-out-transition-added-to-duration/4867"
