### ISSUE TITLE
Validate against repeating, overlapping schedules

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#708]
For example:
If the event is set from 13:45 on the 4th Jan 2016, until 2017-01-01, repeated every 5 minutes.
Then, each 5 minutes there is another matching schedule, so all of those schedules are going to match 
Example numbers:
- 200k of schedule calls reduced by 1 every 5 minutes, each schedule call will take few MB of bandwidth allowance.
This way one display is easily able to consume 2G+ of bandwidth in just a couple of days.

It would be great if we were able to detect such a behaviour and could react to it in time. Preferably before it consumes lots of GB of bandwidth allowance.

**Comment by dasgarner** [comment]
If the repeat duration of a schedule sits within the start/end date of that schedule then it is in effect a "recursive" schedule and should be validated against.

For example a schedule running for 1 week, repeating once an hour. In hour 1 there will be 1 instance of it, in hour 2, 2 instances of it, but the end of the week 168 instances of it. Where schedule downloads the last 2 days, and the end of the week there will be 167+168=335 schedule events in the download.

**Comment by dasgarner** [comment]
Added in 1.8
