### ISSUE TITLE
The client does not update content when it is changed in the CMS

### ISSUE THREAD

**Issue by wilo087** [xibosignage/xibo#71]
The client does not update content when it is changed in the CMS. when I close the client and open the content is changed.

**Comment by BitingChaos** [comment]
How long did you wait?

The update time defaults to something like *900* seconds (15 minutes).

I don't know if there is a better way of adjusting it, but I do this:
First you need to create a "Display Settings" profile, then set the update time to something like 60 seconds (1 minute). Next go to the settings of your "Display", click "Advanced", and then apply the Display Settings profile to get it to update every 60 seconds.

**Comment by wilo087** [comment]
Thanks BitingChaos, Let me try and I tell you.

**Comment by wilo087** [comment]
BitingChaos, thanks very much, this solved my problem!

**Comment by dasgarner** [comment]
@BitingChaos - thanks for answering!

"Next go to the settings of your "Display", click "Advanced", and then apply the Display Settings profile to get it to update every 60 seconds."

You could also tick "Default" in Display Profile if you wanted those settings across all of your displays. :)
