### ISSUE TITLE
Creating and using templates makes duplicates of media files

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#718]
Consider this: you create a layout upload 4 images and assign them to it:
let's call them A, B, C, D

Then you save this layout as a template, it will create duplicates of the images in CMS library. 
called "templateName A 2", "templateName B 2", "templateName C 2", "templateName D 2"

Next, if you actually create a new layout with that template images will be duplicated once again and called "newLayoutName" "templateName" A 2 2)
"newLayoutName" "templateName" B 2 2)
"newLayoutName" "templateName" C 2 2)
"newLayoutName" "templateName" D 2 2)

I don't think we should make so many copies of the same media files.
Every time that template will be used another copies will be made.

It could be an option, but perhaps not the default behaviour.

**Comment by dasgarner** [comment]
Media isn't duplicated in 1.8 - saving and template and using it to create a new layout will have the original mediaId's (if the widgets were included when the template was created)

**Comment by dasgarner** [comment]
Will wait for 1.8 (where this isn't a problem)
