### ISSUE TITLE
Regions ignore zindex in Client

### ISSUE THREAD

**Issue by BitingChaos** [xibosignage/xibo#72]
Xibo 1.7.0 final

(Good) Design mode: Setting the z-index in regions places them in front of or in back of other regions.
(BAD) Client mode: the z-index is ignored and regions do not appear as expected!

For example, in Design view:
region1 has a z-index of 10 and appears behind of region2.
region2 has a z-index of 100 and appears on top of region1.

Client view:
region2 is drawn *behind* region1, despite being on top of it in Design view.

**Comment by dasgarner** [comment]
Overlapping regions are not supported in the Windows Player at the current time - this is something we will try and address with the 1.8 release.
