### ISSUE TITLE
1.8 Papercuts - Medium Priority

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#722]
- [x] Some places in CMS you have to press enter after entering something to search for, other places the search happens automatically after a short delay. All instances should be updated so they are uniform and search automatically after a few seconds or on pressing enter directly
- [x] Should be able to edit layout templates (but note that they won’t update layouts based on that template initially)
- [x] Add from library form - move list of currently selected media items to the side to avoid the media results list from moving down when items are added, and to improve ordering UI
- [x] When uploading a video, option to Play until the end should be ticked by default and duration set to 0 not the calculated duration. Calculated duration should still be stored in metadata so region duration can be accurately reported.
- [x] Duration per item on Twitter should be available and selected by default
- [x] Duration per item on Finance should be available and selected by default
- [x] Dataset form - Add Appearance tab with some pre-defined styles there already and option to override with user CSS if desired
- [x] Dataset order by field should be a list of dataset column headings with ASC/DESC option and option to enter custom sort order as SQL instead
- [x] Dataset filter field should have a simple way to do common simple filters (eg Column Value starts with, ends with, greater than, less than, equal); again with option to enter SQL
- [x] Dataset Column picker - column names should be double-clickable to jump between selected/available
- [x] ForecastIO move Units, Language, Update Interval and Daytime Weather conditions to the Advanced tab
- [x] Schedule - have “special date” which is considered to be infinity and option in schedule form to “schedule forever” which then disables the ability to enable repeats
- [x] Schedule Repeat - hard validation (existing bug for that) to prevent cascading schedules from being created

**Comment by dasgarner** [comment]
Removed 

> All filter forms need to look fit the document flow better - and probably keep filter bar open at all times (option to collapse the filter bar would be nice)

as it is expressed here: https://github.com/xibosignage/xibo/issues/699
