### ISSUE TITLE
Invalid layout with "?" status in CMS

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#727]
When we add, for example, a webpage to our layout, that will change layout's status to "?"
Now if we also add an empty region to our layout, players will render it as invalid, but status in CMS will remain as "?", perhaps if something like this occurs the "X" status should be displayed instead.

Affected versions -both 1.7 and 1.8.

**Comment by dasgarner** [comment]
This has been resolved in 1.8 during the papercuts project.
