### ISSUE TITLE
mysql error update 1.6.3 to 1.7.6

### ISSUE THREAD

**Issue by AlexandeDV** [xibosignage/xibo#730]
Hi all,

I am getting this error when I attempting to upgrade from 1.6.3 to 1.7.6.

I'm on RHEL 6.5 (Santiago)

`An error occurred populating the database. Statement number: 57. Error Message = [SQLSTATE[HY000]: General error: 1005 Can't create table 'xibo163.#sql-ac2_ae' (errno: 121)]. File = [Array]. SQL = [ALTER TABLE `blacklist` ADD CONSTRAINT `blacklist_ibfk_1` FOREIGN KEY (`MediaID`) REFERENCES `media` (`mediaID`), ADD CONSTRAINT `blacklist_ibfk_2` FOREIGN KEY (`DisplayID`) REFERENCES `display` (`displayid`)].`

I searched the forum posts, but I have not found the answer to my problem :o(
Any suggestions?

Thank you,
![image](https://cloud.githubusercontent.com/assets/8308197/13316921/a65a51f6-dbb2-11e5-8643-ea329a66cef0.png)

![image](https://cloud.githubusercontent.com/assets/8308197/13316861/3ed2849a-dbb2-11e5-8c6f-a8fc439acd85.png)

**Comment by alexharrington** [comment]
Please post your support requests over on the Community site. Github issues is only for issues that have been confirmed and discussed there previously. Thank you.

**Comment by alexharrington** [comment]
https://community.xibo.org.uk
