### ISSUE TITLE
" " instead of a ' ' is causing dataset/ticker filter to show incorrectly on edit form.

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#737]
Lets say you have a column called `Name` and in this column you have a row called `Alex`

Then in dataset/ticker when you put `Name = "Alex"` it will save, but on edit it will be broken.

It would be good to have a functionality to automatically convert `"` to `'` in dataset/ticker filter to avoid this issue.

**Comment by dasgarner** [comment]
> It would be good to have a functionality to automatically convert " to ' in dataset/ticker filter to avoid this issue.

I think this is actually an encoding issue, such that the data should be escaped for HTML before it gets re-output.
