### ISSUE TITLE
XIbo server can´t upload vídeos

### ISSUE THREAD

**Issue by cesarluisg** [xibosignage/xibo#753]
Hi,
I have Xibo server 1.7.4, and worked well, I could upload video file, but now I can´t.
The error ocurr while I try upload a video, I select a video, I click on "start upload" and the transference begins, but before it ends, the transfer stops and, appears only "**true**" under the file name.
![xiboserver_error_ture_2016_03_29](https://cloud.githubusercontent.com/assets/6969258/14127279/0d0c4ce8-f5ed-11e5-9e72-91f01643e827.png)
What happen?, where will I find the log file?

Thanks

**Comment by alexharrington** [comment]
Please post your support requests over on the Community site at https://community.xibo.org.uk 

Be sure to work through the CMS Post-Installation guide first too.
