### ISSUE TITLE
Option to change permissions and tags in multiple items at once in Media Library

### ISSUE THREAD

**Issue by the1poet** [xibosignage/xibo#765]
Currently using 1.7.6 back-end.
Unless there's something I'm unaware of, if you want to change the permission or edit (for example) the tags or duration for a lot of items uploaded, you have to do it to each item individually.
Say I've just added 50 new photos to the library, I now have to click on the permissions and edit function on each individual item. This is quite time consuming.

**Comment by alexharrington** [comment]
Please log support and feature requests on the community site. https://community.xibo.org.uk 

I believe this has already been logged 
and addressed in 1.8 series though

**Comment by the1poet** [comment]
Should I still put in a request on the community page just in case?

**Comment by alexharrington** [comment]
Sure you're welcome to. In the Features category please.
