### ISSUE TITLE
Posibility of charts from MySql or MSSQL tables

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#77]
From: https://answers.launchpad.net/xibo/+question/261073

Is there a possibility that you will develop in the future graphs that take the input from a MSSQL or MySql query ?
The software is great but it is to bad it does not have graphs. It would be great if you could make that.

Believe it or not we did used to have graphs back in 2006! But they were cut as a little complex for our needs at that time.

**Comment by Adrian-Botas** [comment]
But will you bring graphs back in the future ? And if so when will you bring them back. 
I am developing a project with digital signage displays in production and your software will be perfect if it would have graphs. We will use Android displays.

**Comment by dasgarner** [comment]
We have no immediate plans to bring back the charting functionality as it represents a lot of work and isn't a heavily requested feature.

I've tagged this as an enhancement that requires a blueprint so you can monitor the status here.

**Comment by Adrian-Botas** [comment]
OK. Thank for tagging it as an enhancement and thank you for the answer.

**Comment by kevinrsalisbury** [comment]
Dan,

How about simple charts though? Perhaps by using something like cssplot (MIT License) for basic CSS ploting capabilities with Xibo's dataset feature? 

demo: http://asciimoo.github.io/cssplot/

git: https://github.com/asciimoo/cssplot

Just a thought,

Kevin

**Comment by dasgarner** [comment]
Thanks for the suggestions - by far the biggest consideration for charts is the UI to define them on the layout - you'd need to select your chart types, series, x/y plots, etc, you'd of course need to select their data source, etc.

Xibo already uses morrisjs for the dashboard so we would most likely go with that library for display

**Comment by dasgarner** [comment]
Closing as we now have a Charting module again, and Remote DataSets from JSON/CSV format.
