### ISSUE TITLE
Adding/deleting Members to display group and deleting existing display groups doesn't work

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#773]
Currently(1.8 alpha3) when you try to add a display to display group it will show 'unexpected error'.

Deleting existing members and deleting existing display groups seems to not work as well - report:
https://community.xibo.org.uk/t/deleting-group-1-8-alpha3/5735

**Comment by dasgarner** [comment]
@PeterMis - as far as I can see this bug has been fixed by you: https://github.com/dasgarner/xibo-cms/commit/ac1c4f1e95291b7ec68e2fe8207b9e78394c9210

If so, please close it

**Comment by PeterMis** [comment]
Yes, that would be correct I did fix it, forgot to close it here, will do that now!
