### ISSUE TITLE
Blank page when upgrading xibo 1.6.3 to 1.7

### ISSUE THREAD

**Issue by Korlash** [xibosignage/xibo#78]
Hello, i have a problem when i want to upgrade my xibo server 1.6.3 to 1.7.
I've download the source https://github.com/xibosignage/xibo-cms/archive/1.7.0.tar.gz, create a new folder with the new file and i place my settings.php in this new folder.
after that i go on my xibo server, i write my id user and password and after that i have a blank page with url : http://ipXiboServer/index.php?p=index (with firebug on firefox it's write "500 Internal Server Error").
If i delete my settings.php i can install xibo 1.7 (install.php), and all requirements and ok so i don't understand why i can't upgrade my old server :(.

Have you got some idea? i am on Openbsd 
Ty

**Comment by nagyrobi** [comment]
500 Internal Server Error - what does the webserver log say in the error logs?

**Comment by Korlash** [comment]
Nothing : 
[Thu Jan 29 11:25:22 2015] [error] [client xxx.xxx.xxx.xxx] File does not exist: /var/www/xibo-cms-1.7.0/favicon.ico

In the access.log : 
xxx.xxx.xxx.xxx - - [29/Jan/2015:11:25:22 +0100] "POST /index.php?q=login&referingPage= HTTP/1.1" 302 5 "http://Ip.xibo.server/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
xxx.xxx.xxx.xxx - - [29/Jan/2015:11:25:22 +0100] "GET /index.php?p=index HTTP/1.1" 500 5 "http://Ip.xibo.server/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
xxx.xxx.xxx.xxx - - [29/Jan/2015:11:25:22 +0100] "GET /favicon.ico HTTP/1.1" 404 217 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"
xxx.xxx.xxx.xxx - - [29/Jan/2015:11:25:22 +0100] "GET /favicon.ico HTTP/1.1" 404 217 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0"

**Comment by dasgarner** [comment]
In your old CMS - can you pop it into Test mode from the CMS Settings? Then try your upgrade in the new folder.

Hopefully that will output some hideous error that we can then fix (the error is being hidden behind the 500 error at the moment).

**Comment by Korlash** [comment]
I did it. Error 500 disapear but i have always a blank page without any error :(. (i have try to generate one error on a php page and i can to see it, so....)
I don't understand why...

**Comment by dasgarner** [comment]
That probably means it is erroring before test mode sets error reporting on.

At the top of `lib/include.php` can you edit:

``` php
error_reporting(0);
ini_set('display_errors', 0);
```

to

``` php
error_reporting(E_ALL);
ini_set('display_errors', 1);
```

**Comment by Korlash** [comment]
Indeed i have one error : 
Fatal error: Class 'ZipArchive' not found in /var/www/xibo-cms-1.7.0/lib/data/layout.data.class.php on line 1853

**Comment by dasgarner** [comment]
Are you sure you have 5.3.3?

ZipArchive should be included in [5.2.0 and above](http://php.net/manual/en/class.ziparchive.php)

**Comment by Korlash** [comment]
I have found my problem...
Yes it's php-zip, it's was not installed  :). (you have send your message 1 minute before me hehe).
Thanks for your help

**Comment by dasgarner** [comment]
You're welcome :smile:
