### ISSUE TITLE
Changing DisplayGroup assignment doesn't purge XMDS cache

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#783]
https://community.xibo.org.uk/t/group-assignment-doesnt-trigger-xibo-client/5895/5

**Comment by alexharrington** [comment]
https://github.com/dasgarner/xibo-cms/blob/b33f46440b0e6aba52f569158a46d939ca7956c0/lib/pages/displaygroup.class.php#L482 

and

https://github.com/dasgarner/xibo-cms/blob/b33f46440b0e6aba52f569158a46d939ca7956c0/lib/pages/displaygroup.class.php#L501

maybe need to read:

> PDOConnect::getPool()->getItem('display/' . $displayId);

**Comment by alexharrington** [comment]
With that patch in place it then appears to work as expected if you assign/unassign from the Display Groups page, but doesn't appear to work if you assign/unassign from the Displays page.
