### ISSUE TITLE
Screen Power Saving when running as a Screensaver

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#794]
When running as a screensaver, Xibo seems to prevent Windows Power Management from putting the screen to sleep after the configured time.

This is the desired operation when running as a standalone application, but when running as a screensaver perhaps should be configurable?

Originally reported here:
https://community.xibo.org.uk/t/windows-screensaver-and-monitor-sleep/6103

**Comment by dasgarner** [comment]
No sure how to influence this - perhaps via [SetThreadExecutionState](https://msdn.microsoft.com/en-us/library/windows/desktop/aa373208(v=vs.85).aspx)

**Comment by alexharrington** [comment]
Yes. We currently set those to prevent the display sleeping. I can see a scenario where you'd want the screensaver to keep the screen alive (ie if being used as a screensaver on a kiosk) and where you'd want it to go off per the OP's request. So I think ideally that wants to be somehow configurable.
