### ISSUE TITLE
Display issue with KIBANA (ELK)

### ISSUE THREAD

**Issue by enumanc** [xibosignage/xibo#795]
Hello I have tested Xibo 1.7.7 and I am faced to an issue when trying to display web content coming from an application called KIBANA (ELK);

I have tested either with CEF or Explorer, but it is the same.
I prefer to use xibo with CEIF because wa have to display Server-sent event information (Dashing application) and Explorer doesnot work with this so CEF is better unfortunately does not display ELK that is a huge dashboard application for us.

I have also discribed this issue on their site:
https://discuss.elastic.co/t/display-issue-on-cef-chrome-embedded/35379

**Comment by alexharrington** [comment]
Please post your request on the Community site here: https://community.xibo.org.uk

We keep Github issues for confirmed bugs that have been previously triaged there only. Thank you.

To possibly save you a post, I'd turn CEF off (it isn't stable and will likely be removed) and have a look at the FAQ on Internet Explorer and HTML5 content here:
https://community.xibo.org.uk/t/enabling-html5-in-the-windows-net-player/33
