### ISSUE TITLE
Navigation is not responsive

### ISSUE THREAD

**Issue by brunmk** [xibosignage/xibo#81]
Can´t see the content´s container cause navigation bar isn´t responsive.
![screenshot 28_01_2015 17_24_10](https://cloud.githubusercontent.com/assets/10746512/5945102/2e0bbaf2-a713-11e4-94b3-5facd74c742a.jpg)

**Comment by dasgarner** [comment]
I did try to make it responsive - but I ran out of talent. That being said, we haven't ever supported mobile access to the CMS.

If anyone can make it responsive - that would be great.

**Comment by laercionit** [comment]
Hello, I'm working on it, I need a couple of weeks to finalize. Send to DAN evaluate the result.

**Comment by ygurdag** [comment]
This good for me too, especially drag and drop menus, for ex. client groups, which cannot do with any mobile device.

**Comment by brunmk** [comment]
Thanks for the quick answer Dan.

Laercio already explain everything to me.
