### ISSUE TITLE
Add additional checks for incorrect region dimensions

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#810]
We do need to add some additional logic/checks for incorrect region size values.

Currently it is possible to create region with 0 width and 0 height - it should return an error.

Perhaps it would also be good to add some way to check regions dimensions against layout resolution.
So for example on a 1920x1080 layout, when you try to create 5553434x1212440 region it will return an error.

**Comment by dasgarner** [comment]
I am not sure about checking region dimensions - I agree it could be a good idea to prevent out of bounds data... but I am not sure what rules should be applied to cover mistakes but not intentional values.
