### ISSUE TITLE
Xibo Feed Error

### ISSUE THREAD

**Issue by xibovlbg** [xibosignage/xibo#818]
Some feeds work, others do not.
Proxy settings are entered correctly and functioning well.

Error message in the log:
Feed Error: This XML document is invalid, likely due to invalid characters. XML error: Mismatched tag at line 98, column 172

Is there a solution?

I want to apologize for my bad english.

Thank you,
Thomas

**Comment by alexharrington** [comment]
Please post your question over on our Community site  https://community.xibo.org.uk 

The project uses Github issues for confirmed bugs that have been previously discussed there before only. Thank you
