### ISSUE TITLE
Database migration 82.sql 

### ISSUE THREAD

**Issue by jccolson** [xibosignage/xibo#820]
Can't migrate from xibo 1.6.4 (data present in table tag).

Can you change INSERT to REPLACE in line 7 ?
Example :
before
INSERT INTO `tag` (`tagId`, `tag`) VALUES
after
REPLACE INTO `tag` (`tagId`, `tag`) VALUES

**Comment by dasgarner** [comment]
The `tag` table should not exist - it was not added until 1.7.0-beta (which is 82.sql). I would suggest that there is something else wrong with your installation - perhaps a partial upgrade.

Please ask your question on our [community forum](https://community.xibo.org.uk/) as this bug tracker is for verified bugs only.

Thanks
