### ISSUE TITLE
Old layout continue to play while new layout downloaded

### ISSUE THREAD

**Issue by ygurdag** [xibosignage/xibo#83]
Hello,
I am working day basis, so we make new layout for everyday. When we send tomorrow s layout, some clients downloads but some of them cannot download (3g internet). But after midnight todays layout will finish based on schedule and tomorrow layout start on clients which downloaded tomorrow layout, but the clients which has not finished to download tomorrows layout will show default layout I think. 
How can I sure clients plays old layout while it finishes to download the New Layout. 
If schedule today layout finish time later from midnight, today and tommorow s layout will play together. 
Should I try priority. Please advice me about my way. 
Thanks, Michael.

**Comment by alexharrington** [comment]
The client caches 2 days worth of content automatically, so make sure you get your content on the CMS the day before and that will give the clients plenty of time to download the content.

Failing that, you could do a rolling priority schedule. So on day 1, you schedule layout 1 for today and tomorrow. Then schedule layout 2 for tomorrow with priority and the day after that without priority. Then schedule layout 3 for the 3rd day etc

So

Monday
Layout 1

Tuesday
Layout 1
Layout 2 Priority

Wednesday
Layout 2
Layout 3 Priority

etc

Best wishes

Alex

**Comment by ygurdag** [comment]
Thank you Alex, I will try.

**Comment by ygurdag** [comment]
Alex it works as you said, but the problem is layout restarts in both update. For Example;
Tuesday
Layout 1
Layout 2 Priority (it works as expected) 

Wednesday
Layout 2 (you need to remove Priority but if you remove layout restarts)
Layout 3 Priority (after taking this layout, layout restarts again)
I don't want layout restarts twice. Can we make it one operation while playing old layout (without seeing default layout)
Thanks.
