### ISSUE TITLE
Designer Feature Request - Label Local Video - Enable/Disable Button

### ISSUE THREAD

**Issue by clarrywhite** [xibosignage/xibo#830]
I absolutely love your Xibo digital signage system. I don't know how difficult this would be but I would like to see a way to temporarily disable an event on the timeline rather than delete it. Also, if you could add a name field on the local video that would show up on the timeline entry that would make it even easier. Thank you for reading this.

**Comment by dasgarner** [comment]
Thank you for your suggestion - we have something similar already recorded, which I have added a comment to for retiring a widget on a timeline: https://community.xibo.org.uk/t/media-start-and-end-date/2937

Local Video already has a name field in 1.8

Future comments / suggestions can be raised [here](https://community.xibo.org.uk) and will get seen far quicker - GitHub is for our verified bug tracking.

Cheers
