### ISSUE TITLE
1.7.8 Player cache not cleared when editing a layout in a scheduled campaign

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo#833]
Original report here:
https://community.xibo.org.uk/t/android-client-slowly-get-update-from-cms-after-upgrade-1-7-8/6564

Recreated on unittest.

Layouts 588/591
Campaign "Community 6564 Campaign"

Scheduling that campaign to a Player, then editing layout ID 591, the display status remains as a tick, and the Player doesn't pickup the new content.

**Comment by laercionit** [comment]
Hello Alex, 

You have a date estimate to finalize this item? I have several problems related to this item.

**Comment by laercionit** [comment]
Dan, this path solves the problem and need to update the client android? I ask therefore applied the change and continue with the same problem.
I'm using CMS 1.7.8 + Path and R61

**Comment by alexharrington** [comment]
I've run a test this morning with this patch applied to a 1.7.8 CMS and the bug is indeed fixed there.

To recreate, create a campaign with two valid layouts. Assign the campaign to a display and wait for its status to be come a tick (ie fully up to date). Now change say the duration of a media item in one of the layouts in the campaign, and see that the status indicator for the display changes immediately to ! as expected.

Note the bug #891  may skew your test if you only move a region via drag and drop.
