### ISSUE TITLE
Statistics page - export is broken, some issues with media filter

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#835]
**Export button**

As it is after you click the 'Export' button on Statistics page, it will be blank - no date to select, no devices in the list.

There should be date select available (from, to) and list of connected devices to choose from.

**Media filter in Proof of play**

Seems to do something, but it's not correct, it seems to show all media that were showed on the same layout(s) as the media selected in the filter.

Issues first reported here: https://community.xibo.org.uk/t/export-statistics-details-blank-in-1-8-beta/6613

**Comment by dasgarner** [comment]
We might have some difficulty here with stats collected after 1.7.8 and before 1.8.0-beta, because they were recording the incorrect mediaId on the stat table. However the above fixes should resolve for stats collected in versions outside of that.
