### ISSUE TITLE
Schedule based on media

### ISSUE THREAD

**Issue by ygurdag** [xibosignage/xibo#84]
Hi,
We can schedule layout without problem. But some of media in the layout should have special time period to show or not shown. For example weather forecast should only shown between 8:00 am - 6:00 pm, nothing more. it can be all usage of this media no problem, not every row in layout.  
Thanks
Michael.

**Comment by dasgarner** [comment]
We hope to address this with #1.

It does raise some interesting considerations as it breaks the clear cut "CMS controls schedule" model we currently have.
