### ISSUE TITLE
Ticker - images from rss feed are not downloaded/displayed

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#845]
Currently ticker will not download images correctly.

We need to edit line 626 in Widget/Ticker.php to:
`if (stripos($item->getEnclosureType(), 'image') > -1) {`

Original report topic:
https://community.xibo.org.uk/t/1-8-ticker-image-is-not-shown/6699

**Comment by dasgarner** [comment]
Fixed in https://github.com/dasgarner/xibo-cms/commit/ecbe31472e70e33663b4da84bc8bb4d48b137aa4
