### ISSUE TITLE
Clock media widget is wrong

### ISSUE THREAD

**Issue by ArcticCascade** [xibosignage/xibo#848]
I've been using Xibo for my school's digital displays for a week now, and today I noticed a bug with the Clock widget.
I have mine using the format "[dddd] [do] [MMMM] [YYYY] [Clock] [A]", which today should show "Tuesday 9th August 2016 08:23 AM". However, instead, it is displaying "Tuesday 2nd August 2016 08:23 AM".
A quick check of both the client and server system clocks show the correct date, and changing "[do]" to "[DD]" shows the correct "09"

**Comment by alexharrington** [comment]
The correct syntax is [Do] not [do].

Please see the guide in the manual:
http://xibo.org.uk/manual/en/media_module_clock.html

Also, please note that we use the Issues section of GitHub for confirmed bugs only - ie those that have been previously discussed over on our community site (https://community.xibo.org.uk). Please post support requests there :)
