### ISSUE TITLE
File delete method

### ISSUE THREAD

**Issue by ygurdag** [xibosignage/xibo#85]
Hi,
I don't know about file deletion method of Xibo Server and Client. 
How can we sure about delete unused media on the client disk to preserve disk space on the Client?
Thanks
Michael.

**Comment by alexharrington** [comment]
Hi Michael

Old media is automatically cleaned up on the client once it hasn't been in the schedule for a while. 

Best wishes

Alex

**Comment by ygurdag** [comment]
For a while? Can I set? Becouse I have limited size of disk.

**Comment by alexharrington** [comment]
I don't believe it can be configured at present. It's 30 days on Windows
and shorter on Android

**Comment by dasgarner** [comment]
On windows you can set this in your `XiboClient.config.xml` file located in your Roaming Profile under the Xibo folder.

The setting to change is `<LibraryAgentInterval>2</LibraryAgentInterval>` and is measured in Days.

**Comment by ygurdag** [comment]
Thanks dasgarner, this is lifesaving :)

**Comment by dasgarner** [comment]
Welcome :smile:

**Comment by xibo-de** [comment]
<LibraryAgentInterval>2</LibraryAgentInterval>

I changed this to 2 a few days ago, but today is suddenly there again automatically 30.
