### ISSUE TITLE
Expire modified layouts setting doesn't work for modified media files contained in a Layout

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#863]
This has been an issue since the introduction of Layout file dependency checking - because if a Layout has invalid dependencies it is removed from the Schedule.

The current playing Layout should remain in the Schedule even if it has invalid dependencies - the fact the Layout is currently playing means that it was valid during a prior schedule assessment and should therefore remain in the Schedule if Expire Modified Layouts is not checked.

**Comment by laercionit** [comment]
Hello DAN
You have a date estimate to finalize this item? I have several problems related to this item.

**Comment by dasgarner** [comment]
Modifications have been made for the windows player - the Android player will follow in the next release (issue ID XFA-221 if you need to contact Spring Signage about it).
