### ISSUE TITLE
Upgrading from 1.6.4 to 1.7 DB Issues

### ISSUE THREAD

**Issue by ideschamps** [xibosignage/xibo#87]
Hi

Running version 1.6.4. Downloaded the latest release(1.7.0) an hour ago. Getting the following issues:

An error occurred running the upgrade. Please take a screen shot of this page and seek help. Statement number: 82. Error Message = [SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 1]

Also had error about utf32.

thanks
Ivan

**Comment by dasgarner** [comment]
Where did you download it from? utf32 has been totally removed from the upgrade routine before release (or rather before we adjusted the release after finding these upgrade issues).

I'd imagine you got the duplicate entry error after running into the other error and then retrying. If you are in a partially upgraded state you will need to roll back to your 1.6.4 database backup before trying again.

**Comment by Mondlicht81** [comment]
(just as reference, check my ticket, last 3 comments: https://github.com/xibosignage/xibo/issues/74)

**Comment by ideschamps** [comment]
Hi Dan

We were on 1.4 originally. Upgraded to 1.6 last year Oct. Upgraded to 1.6.4 this morning that we downloaded here from github and then also to 1.7 that we downloaded from here about 8 hours ago.

**Comment by dasgarner** [comment]
I think i've found another potential problem in 82.sql where a table is created with utf16 charset - it should be utf8.

If you ran the upgrade and it failed on that point, then rerunning would give you the error above.

I'll update that file and link it to this issue so you can make the amendment locally, restore your DB and then run the upgrade again. Should be OK then.

@Mondlicht81 - this issue will fix rerunning upgrades (as an alternative to adding DROP statements). #75

**Comment by ideschamps** [comment]
Hi

Upgrade said completed successfully, but now can't get past the screen that keeps on wanting to upgrade. There is also no install.php file left. See below images.

I have tried both master and develop branch and restoring from VM backup.

thanks


![xibo3](https://cloud.githubusercontent.com/assets/10756782/6019827/8e70f1d4-abad-11e4-94b2-615b236d36df.JPG)
![xibo2](https://cloud.githubusercontent.com/assets/10756782/6019828/8e721f1e-abad-11e4-8ab3-89308030b24a.JPG)
![xibo1](https://cloud.githubusercontent.com/assets/10756782/6019826/8e6f7d7c-abad-11e4-81a3-25ddc4cb8aec.JPG)

**Comment by dasgarner** [comment]
The develop branch is not ready to be installed yet - master should have been OK though. You've basically gone too far forwards.

Edit include.php at line number 23. Change it to `define('WEBSITE_VERSION', 85);`

Which should get you out of that loop for now.
