### ISSUE TITLE
Xibo Client/Server 1.7.0 - no statistics

### ISSUE THREAD

**Issue by xibo-de** [xibosignage/xibo#88]
Hi,
In the Display Setting Profiles statistics are enabled. 
The database contains over 1000 entries in stat Table.

But there are no statistics displayed in the statistics menu.
Date, of course I set.

**Comment by dasgarner** [comment]
Can you provide a log file - it should show us the query being run.

**Comment by xibo-de** [comment]
File sent by mail

**Comment by dasgarner** [comment]
Gah, its not logged.

See attached commit for patch files to get it logged.

**Comment by dasgarner** [comment]
I see why its not logged now - the unique id generated for all 3 of those grids is the same, meaning the the 2nd and 3rd grid filter form changes are only refreshing the top grid.

Please see attached commit for patch.
