### ISSUE TITLE
Add more information about displays on display groups page

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#882]
On Display Groups page, when you view the display group members we'd like to add the following information there:
- Display status (on/offline)
- Current version.

Feature requested here - https://community.xibo.org.uk/t/online-column-on-the-screen-version-player/7063/3

**Comment by maurofmferrao** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;l1tidaNR&#x2F;2-add-more-information-about-displays-on-display-groups-page-882"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add more information about displays on display groups page #882</a>

**Comment by dasgarner** [comment]
Looks good!
