### ISSUE TITLE
Multiple Xibo Main Windows open with CEF enabled

### ISSUE THREAD

**Issue by wheels00000** [xibosignage/xibo#90]
I've noticed a couple of times since updating to 1.7.0 that my windows client will end up playing 2 different layouts audio, or that I will have layouts out of audio video sync. Reboot fixes it so far.

**Comment by dasgarner** [comment]
That is unusual - are these videos ones that you have uploaded to the CMS?

**Comment by wheels00000** [comment]
Yea there all uploaded 80% existed before the upgrade from 1.6.4 to 1.7.0. Just did it again turned off double buffering to see if that was the problem but no dice so far. Just hit windows key to see if there was two instances of the client running and it stopped looks like I have 2 layouts running at the same time out of sync. As soon as I pulled it up it fixed it's self. I'll try a clean install of the client.

**Comment by dasgarner** [comment]
A single client can't run two layouts simultaneously - i'm certain of that. You can have two clients running at the same time now though, so maybe that needs further investigation.

Let us know how you get on.

**Comment by wheels00000** [comment]
So looks like I'm getting multiple instances of xibo running. Tried a clean install of 1.7.0 client works fine for a while but then comes back.

**Comment by wheels00000** [comment]
no I haven't installed watchdog.
Shortcut to player in startup
When I'm having the issue there will be multiple instances of Xibo in the task bar. When it's running correctly I usually only have 1

**Comment by dasgarner** [comment]
Have you installed the Screen Saver?

The watchdog is only available from the repository at the moment xibosignage/dotnnetclient-watchdog


We used to forcibly prevent 2 instances of the application from opening at the same time, but had to relax that restriction to help people that wanted 2 copies of the application running (for two independent screens on the same PC).

Xibo doesn't start itself though - so two in the task tray is really odd.

**Comment by wheels00000** [comment]
No I haven't installed the screen saver. but it's weird that sometimes when it start's doing it screen interaction stops it. Windows is showing no screen savers.
Other times it seems to be I have a bunch of instances open.

should I try disabling CEF?

**Comment by dasgarner** [comment]
Yes please - try that and see if that solves the issue.

Perhaps some CEF areas are creating their own windows - i have no idea how that would be happening though :unamused:

**Comment by wheels00000** [comment]
With CEF disabled the problem went away, system has been running for 2 days now no issues.

**Comment by dasgarner** [comment]
CEF retired in 1.8
