### ISSUE TITLE
default value for Transition Duration in/out

### ISSUE THREAD

**Issue by tali1974** [xibosignage/xibo#900]
Hi.. Is it possible to add a default value of Transition Duration in/out. So that i do not need to click on every single image and add xxxx milliseconds in the future.

Or is there away of doing this in 1.8 ? could have been under (/admin/view/Defaults)

Rereads
T

**Comment by dasgarner** [comment]
Waiting on: #1453

**Comment by dasgarner** [comment]
Add to sprint
