### ISSUE TITLE
Switch to Grid

### ISSUE THREAD

**Issue by tali1974** [xibosignage/xibo#901]
When i add a image and set the Transition to fadeIN or fadeOut, its not showing up under the grid view..

![image](https://cloud.githubusercontent.com/assets/5436081/19076022/7d8352e8-8a47-11e6-9ba2-9ca080201eef.png)

maybe in future 1.8.x could you make the GridView editable for some values like fadein/fadeout time and image Duration time...like this https://editor.datatables.net/examples/inline-editing/simple

**Comment by dasgarner** [comment]
Grid view removed in later releases.
