### ISSUE TITLE
1.7.0 Schedule add layout

### ISSUE THREAD

**Issue by wheels00000** [xibosignage/xibo#91]
I may be missing it but can't seem to manage to schedule layouts to start and end on specific dates and times without scheduling it to run for a certain amount of time then going back and editing it.

**Comment by dasgarner** [comment]
Sorry - i'm not sure what you mean? You pick a start and end date - thats it?

**Comment by wheels00000** [comment]
Never mind found it chrome had to update it wasn't displaying correctly
