### ISSUE TITLE
upgrade from 1.4 to 1.7

### ISSUE THREAD

**Issue by Mulkie** [xibosignage/xibo#93]
Hi,

i'm trying to update but it's not working. Is this even possible to make an update from 1.4?

This is my handling for the update
=> download latest version
=> make a copy off the settings.php (the one who is running).
=> paste latest version in same directory as the old one.
=> replace the settings.php.

Before testing, i've cleared my Internet cache.
But i'm not getting on the index page.

Can someone tell me what i'm doing wrong?

Regards
Kevin

**Comment by Mulkie** [comment]
oké, i've done the update to 1.6.
Upgrade was ok.

But when i'm trying to log on i get the follow error:

Incompatible database version detected. Please ensure your database and website versions match. You have database 84 and website 68

**Comment by dasgarner** [comment]
Database 84 is 1.7.0, so I would say you have upgraded to 1.7.0 database, but have 1.6.4 code.

Key point from your list:
=> paste latest version in same directory as the old one.

This is not correct - you must install into a new folder, or archive off the old folder first as described in the release notes.

Generally - no problem going from 1.4 to 1.7, we've upgraded several people between those versions. If you are nervous about such a big jump, you can do it in stages, but functionally its no different.

**Comment by Mulkie** [comment]
morning,

last night, i was able to update to version 1.7.
The only problem i have right now is that the old layout must be upgraded.
When i'm want upgrade the layout its stuck on waiting. I see a gear spinning but nothing is happening.
It's like this for 15 min now.  Anyone had the same problem?

**Comment by dasgarner** [comment]
Can you check for errors in the log please?

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up this **bug tracker**. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
