### ISSUE TITLE
Layout preview is different than on destination display

### ISSUE THREAD

**Issue by Commifreak** [xibosignage/xibo#931]
Hi. We currently use 1.7.9.

It happens quite often, that the layout preview is great but when showed on the final productive display, the layout is "broken". Brokens means, the regions are not on the same position as seen in the layout preview.

Maybe due to other screen resolutions, I dont know.

I search a way to preview the layout exactly as it will be shown on the destination display.

Can you comprehend my issue?

Thanks in advance :)

**Comment by dasgarner** [comment]
We use GitHub for verified bug tracking and development - please post support requests on our [community forum](https://community.xibo.org.uk/c/support). I am sure someone on there will be able to assist you!

Thanks!
