### ISSUE TITLE
Client for Linux

### ISSUE THREAD

**Issue by c0fe** [xibosignage/xibo#932]
I have been looking for Xibo for quite some time but it isn't ideal for me because some of the hardware I have to work with doesn't play too nicely with Android OS but does work well with Linux, specifically Debian distro. I was wondering if it would be a possibility to add a Linux client in addition to the Android and Windows?

**Comment by alexharrington** [comment]
We use Github issues for verified bug tracking only.

Please post your question over on our Community site https://community.xibo.org.uk where you will find extensive discussion about the future direction of a player for Linux already.
