### ISSUE TITLE
Need a "copy" button to put application secret on the clipboard

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#939]
It is impossible to copy at the moment (it wasn't always so I am not sure what has changed, but in any case a copy button would be superior)

**Comment by maurofmferrao** [comment]
Feature is not working on Chrome, it says 'Copied' but that's bs it didn't really copy anything.

**Comment by dasgarner** [comment]
Is this working on Chrome now?

**Comment by maurofmferrao** [comment]
It was tested in Chrome, Opera, Firefox, IE and it's working in all of them right now.
