### ISSUE TITLE
Video fill to region dimensions

### ISSUE THREAD

**Issue by ygurdag** [xibosignage/xibo#94]
Hi,
Some time videos are 16:9 and screen is 4:3, whatever I try with layout' s region size and aspect, nothing helps. Is there option to make video files stretch to fit full screen?

**Comment by dasgarner** [comment]
There isn't an option for this at present. Ill label as an enhancement.

**Comment by dasgarner** [comment]
Done in CMS/Android Player - need to do in windows somehow.

**Comment by dasgarner** [comment]
The Windows Media Player control used by the Windows Player does not support stretching to fit - therefore this will need to be delayed for the new player.

**Comment by dasgarner** [comment]
Moved: https://github.com/xibosignage/xibo-dotnetclient/issues/68
