### ISSUE TITLE
Mark CEF as legacy in display settings and don't send to 1.8 players

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#945]
As we no longer support CEF in 1.8, we probably should remove the checkbox 'Use CEF as the Web Browser' from Display settings -> display profile -> advanced.

**Comment by dasgarner** [comment]
Update the help text on the form, generated from `DisplayProfile.php` and then update `Soap5.php` to skip that setting when sending settings to windows players.

**Comment by dasgarner** [comment]
Looks good.
