### ISSUE TITLE
Improve schedule visibility with user created daypart

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#946]
Currently when you create new daypart and schedule new event using it.
The schedule page will not show start/end time of this event - it shows it as 'all day' event which in most cases will be incorrect (it shows it the same as always daypart).

When you edit existing event and change the daypart to 'Custom' it will default to:
1970-01-01 01:00
2050-12-31 00:00

Perhaps date picker fields should be blank when you change to Custom.

**Comment by dasgarner** [comment]
There is also a problem with the weekly view and day parting events, that show the event time instead of the day part time.
