### ISSUE TITLE
Improve layout timeline ordering

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#948]
When you have let's say 10+ items in the layout timeline, the drag&drop ordering can be rather difficult and certainly not too user friendly.

Perhaps we could add an option to move up/down the items in the grid view (either drag&drop or new button) to make it more viable with lots of items in the timeline.
An option to move multiple selected items up/down could be useful as well.

**Comment by dasgarner** [comment]
Grid view has long been removed - but we should make sure that the timeline handles reordering in both the Layout and Playlist editors in a sensible way when there are > 10 items.

**Comment by dasgarner** [comment]
Add to sprint
