### ISSUE TITLE
Powerpoint not (yet) working with v. 1.7.0

### ISSUE THREAD

**Issue by Mondlicht81** [xibosignage/xibo#95]
Hi,

I have one layout that displays Powerpoint slides. It was working fine on v. 1.6.0, but after the upgrade on all clients I only see "Powerpoint not enabled on this display".

Is there anything I forgot to configure? ...as said it was working in v. 1.6.0.

Thanks a lot in advance for your help!

**Comment by AndrewBrooksBDCH** [comment]
Exactly the same for me.  There used to be an option to configure the individual Display Properties to allow PowerPoint, but that seems to be missing in 1.7.0.  Is there a registry hack?

**Comment by Mondlicht81** [comment]
I found a file C:\Program Files (x86)\Xibo Player\default.config.xml, which contains some powerpoint option. But setting it to true didn't help.

**Comment by dasgarner** [comment]
It is now disabled by default as most people won't have it enabled.

Enabling it is easy - create a display profile, edit it, tick the enable power point box. If all your displays have powerpoint then setting it as the default profile is probably a good idea.

**Comment by AndrewBrooksBDCH** [comment]
Thanks for the update.  I have now got it working…kind of…except that when the PowerPoint Slides open Internet Explorer prompts “Do you want to open this kind of file”.  I seem to remember this is an option in Internet Explorer, but can you confirm where I can find it please?

Thanks
Andrew

**Comment by dasgarner** [comment]
There are instructions in the manual: http://xibo.org.uk/manual/en/media_module_powerpoint.html
