### ISSUE TITLE
Xibo Email Alert: Display is Online again - comes multiple times

### ISSUE THREAD

**Issue by Commifreak** [xibosignage/xibo#952]
Hi,

we use Xibo 1.7.9.

When a display is offline, I get one email. Done.

Wehn  it gets online again, I get the email "... is online again" multiple times. ~25 mails arrived me! With the exact content.

Whats wrong here? Any hint?

The cronjob is configured like this:

```
## Run Xibo cronjob
*/10 * * * *    root    cd /var/www/xibo.jki.bund.de && php maintenance.php changeme
```

![unbenannt](https://cloud.githubusercontent.com/assets/87267/20390153/b4dbaa26-accd-11e6-8355-0158ffaab9cd.JPG)

**Comment by alexharrington** [comment]
Thanks for your report. Please post your question over on our Community Site. We keep Github issues for confirmed bug reports only once they have been discussed there.

I'm pretty sure this is a known issue (to do with the concurrency of file downloads) and has already been resolved in 1.8 series.
