### ISSUE TITLE
Improve Layout timeline 'View Library' form 

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#961]
Edit Layout timeline -> (for example) Image -> View library

1) Assignments field, does not look nice with longer file names:
![image](https://cloud.githubusercontent.com/assets/12148978/20517338/85efa258-b092-11e6-804d-6dd152358da2.png)

2) We could add image thumbnails to this form (like on Library page) to make it easier to select right image.

**Comment by dasgarner** [comment]
Point Number 2 is done - point number 1 is outstanding
