### ISSUE TITLE
Xibo\Storage\PdoStorageService.php Breaks Install

### ISSUE THREAD

**Issue by leeanthony** [xibosignage/xibo#962]
Update to Xibo\Storage\PdoStorageService.php beaks install at line 143.  Calls newConnection prior to ConfigService being setup for dev branch

**Comment by dasgarner** [comment]
Interesting - do you have any further details you can share?

Some steps in the installer are run before the ConfigService is required as they directly call "connect" using the DB connection details provided in the form. `connect()` stores the connection for return later - I am not sure how the changes made to that file effect that.

**Comment by leeanthony** [comment]
Helper/install.php calls $storage->connect() on line 122.   PDOStorageService.php connect() then calls $this->getConnection('default'); on Line 126 which invokes line 143 to generate a new connection based off of the Config service.

**Comment by dasgarner** [comment]
Wow - how did I not see that! Thanks a lot :+1:

**Comment by optimiseseo** [comment]
@leeanthony Can you email me? Have something to discuss with you perthhosting@gmail.com.
