### ISSUE TITLE
Default language in CMS 1.7.0?

### ISSUE THREAD

**Issue by jorsab** [xibosignage/xibo#97]
Hi, When testing CMS 1.7.0.rc1 and setting the default language (Settings/Regional/Default language), the CMS changed accordingly when refreshed. I am now using the released CMS 1.7.0 and the language does not change after modifying the same setting. In both cases the Detect Language checkbox was unchecked and the browser was the same (Chrome 40.0.2214.93 m). I must be missing something. Can you help? Thanks!

**Comment by dasgarner** [comment]
Ah - I see a problem with a last minute fix. I'll adjust it and link a patch momentarily
