### ISSUE TITLE
Linux installation guide

### ISSUE THREAD

**Issue by taismi** [xibosignage/xibo#971]
Could you update Linux installation guide http://xibo.org.uk/manual/en/install_environment_linux.html .

Ubuntu does not have PHP 5 so I tried Debian but no success http://i.imgur.com/DdphkYC.png . For example command curl works but Xibo says it's missing.

**Comment by alexharrington** [comment]
Please post your support requests over on our Community Site https://community.xibo.org.uk

Xibo requires PHP5. If you're using Ubuntu 16.04, then you'll need to install the PHP 5 packages which are available from various repositories, or use Ubuntu 14.04 in the meantime.
