### ISSUE TITLE
List of Events in Schedule should be ordered by Display Order instead of Start Time

### ISSUE THREAD

**Issue by MrYaz** [xibosignage/xibo#972]
When you click on a certain date a list is shown with all the Events scheduled for that particular day.
But the Events are sorted by Start Time instead of by Display order . You should be able to choose the preferred sort order, either directly in the list or in a global setting under Administration->Settings

**Comment by dasgarner** [comment]
Please file this as a feature request on our [Community forum](https://community.xibo.org.uk/c/features) - this issue repository is for verified bug reports only.
