### ISSUE TITLE
Improve Event ordering in Schedule

### ISSUE THREAD

**Issue by MrYaz** [xibosignage/xibo#973]
I find the Event ordering in the Schedule view to be rather unintuitive and tedious, IMHO.
Instead of manually entering the Display order for each event you should be able to change the order by using drag&drop or pressing up/down-buttons. Maybe in the List of Events that are shown when clicking on a certain date.

**Comment by dasgarner** [comment]
Please file this as a feature request on our [Community forum](https://community.xibo.org.uk/c/features) - this issue repository is for verified bug reports only.
