### ISSUE TITLE
Displays selector stays open on top when Adding an event in the Schedule view.

### ISSUE THREAD

**Issue by MrYaz** [xibosignage/xibo#975]
When you click the drop-down selector to select which displays should be visible and click the Add Event button the Display selector is not closed but stays on top, covering the Add Event Dialog.

**Comment by dasgarner** [comment]
Sorry I can't recreate this issue. Please provide more information on the browser you are using, the version of Xibo and a screenshot of the issue.

**Comment by MrYaz** [comment]
After clicking display selector:
![image](https://cloud.githubusercontent.com/assets/1811963/21371715/27315030-c713-11e6-9e4f-bb4e6c5eb824.png)

After clicking Add Event button:
![image](https://cloud.githubusercontent.com/assets/1811963/21371729/37e71432-c713-11e6-9d01-236014465fe0.png)

Chrome version:
55.0.2883.87 m

Same behavior in Firefox version:
47.0.2

Xibo CMS version:
1.7.8

**Comment by dasgarner** [comment]
Fixing this cosmetic issue requires too much change to put in a small maintenance release - the problem does not effect 1.8.
