### ISSUE TITLE
Automate!

### ISSUE THREAD

**Issue by hkbehari** [xibosignage/xibo#979]
Hi,

I don't have  an issue or bug to report but, I like to automate a few processes. Can someone tell/guide me how to do it? 

The stuff I like to automate:
1. When a client installs the player s/w and register the display with the CMS it should auto approve  the Display. 
2. The display should be added to a "Display Groups".
3. A default campagne should be assigned to the newly registered display.

That's it.

**Comment by dasgarner** [comment]
Hi, 
Please ask for assistance on our community forum - https://community.xibo.org.uk/ - as this issues page is for bugs only. You can log in with GitHub to make it easy.
Thanks,
Dan
