### ISSUE TITLE
Dataset View duplicates selected columns

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#987]
When you first create a dataset view item and select columns you wish to show.
It will show then two times, ie you selected 
col1 col2 col3 
it will show
col1 col2 col3 col1 col2 col3

If you edit your dataset view item and navigate to appearance tab, you will see that column selection there is duplicated.
After another edit&save it will duplicate them again, leading to a really not pleasant look.

**Comment by PeterMis** [comment]
Linked issue - https://github.com/xibosignage/xibo/issues/934

**Comment by maurofmferrao** [comment]
The issue was not with the page loading, but with the Save/Apply, that added the selected columns each time Save was clicked. That would generate repeated items.

**Comment by dasgarner** [comment]
@PeterMis - can you please verify this to make sure it fixes the original issue?

**Comment by PeterMis** [comment]
Yes, the column order stays as it was set and there are no repeated items, good work.
