### ISSUE TITLE
Typo on the requirement-check-page

### ISSUE THREAD

**Issue by gumida** [xibosignage/xibo#991]
Hello,
during the installation of Xibo the setup is checking some basic requirements. One of these is "upload_max_size", but shouldn't this be "upload_max_**file**size"?

![2016-12-27_16h05_47](https://cloud.githubusercontent.com/assets/5578303/21502389/b8459ae0-cc4f-11e6-8555-cff69d18ba40.png)

![2016-12-27_16h06_01](https://cloud.githubusercontent.com/assets/5578303/21502388/b6269098-cc4f-11e6-8f66-b201a7e6aa26.png)

**Comment by dasgarner** [comment]
Thanks - i've logged this against the next release.

**Comment by dasgarner** [comment]
This is a translation issue, not a source issue.
