### ISSUE TITLE
Increase the maximum entries show on Displays page

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#993]
We could increase the 'show x entries' on displays page to more than current maximum 100, then the 'CSV' button will export more than 100 entries as well.

Alternatively, we could also add additional form on 'CSV' button to let the user set the amount of displays they wish to export in it - similar in some sense to export button on statistics page.

**Comment by dasgarner** [comment]
The first option is the way to go here - options for 250 and 500 would be nice.
