### ISSUE TITLE
Time picker in display profiles writes 0 instead of 00:00 to the hidden field which breaks Display edit form

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#994]
On a fresh 1.8.0-rc2 the hidden fields for update/download window have value of 0 instead of 00:00, which results in Data missing error on Display edit form. 

![upload](https://cloud.githubusercontent.com/assets/12148978/21604178/9a1d522a-d199-11e6-9f63-eeba1ef93f74.png)

If you change the time to something else than default 00:00 and save, then change it back to 00:00 it's working correctly though.

**Comment by dasgarner** [comment]
This also needs to be corrected for the windows display profile.

**Comment by dasgarner** [comment]
After finding the root cause in the JS control, we could also protect against error when it does have 0 by editing /lib/Controller/Display.php L#615 to:

```
$profile[$i]['valueString'] = ($profile[$i]['value'] == null || $profile[$i]['value'] == '0' ) ? '00:00' : $this->getDate()->parse($profile[$i]['value'], 'H:i')->format('H:i');
```

**Comment by telemanagain** [comment]
Hello all, first let me tell you that I have had a ball the last few days wrapping my brain around xibo, I'm currently running a docker as recommended and I am SO DANG CLOSE to having this up and running. It comes down to not being able to edit a newly connected android device. I have changes the times on Download Window Start Time and Download Window End Time then changed them back. No luck am I not changing things in the right place? forgive me if its probably something stupid I'm an old admin who's been out of the game for almost 6 years. Thats a lifetime in tech years.

**Comment by PeterMis** [comment]
For future reference, please discuss such issues on https://community.xibo.org.uk/

As you can see this issue here is not yet fixed, but the work around to edit display profile assigned to your device -> change download/update windows to lets say 00:15 | 23:55 -> save -> (you should be able to edit display now) -> edit profile again -> change to 00:00 | 00:00 -> save -> edit display should still work.

If not,  please create a topic on Xibo Community site and we can discuss this further.
